### ISSUE TITLE
sigdump doesn't work

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluentd#1008]
I send `kill -CONT` to fluentd's worker process but I got following error.
Config::Section should define `class` method?

```
2016-05-30 09:04:51 +0000 [info]: following tail of dummy.log
Unexpected error undefined method `class' for <Fluent::Config::Section {"log_level":null,"suppress_repeated_stacktrace":null,"emit_error_log_interval":null,"suppress_config_dump":null,"without_source":null,"rpc_endpoint":null,"enable_get_dump":null,"process_name":null,"file_permission":null,"dir_permission":null}>
  /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0.rc.3/lib/fluent/config/section.rb:95:in `method_missing'
  /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigdump-0.2.4/lib/sigdump.rb:74:in `block in dump_object_count'
  /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigdump-0.2.4/lib/sigdump.rb:73:in `each_object'
  /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigdump-0.2.4/lib/sigdump.rb:73:in `dump_object_count'
  /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigdump-0.2.4/lib/sigdump.rb:18:in `block in dump'
  /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `open'
  /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `_open_dump_path'
  /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigdump-0.2.4/lib/sigdump.rb:14:in `dump'
  /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/serverengine-1.6.4/lib/serverengine/server.rb:77:in `block (2 levels) in install_signal_handlers' 
  /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/serverengine-1.6.4/lib/serverengine/signal_thread.rb:98:in `main'
```

**Comment by tagomoris** [comment]
Definitely true > add `class` method

**Comment by tagomoris** [comment]
Done on master branch.

**Comment by tagomoris** [comment]
I got sigdump result on master branch after some fixes.
