### ISSUE TITLE
error when using --no-supervisor option

### ISSUE THREAD

**Issue by m-mizutani** [fluent/fluentd#1027]
fluentd fails when using --no-supervisor option at UNIXSocket.new in `serverengine/socket_manager_unix.rb`. This error may be caused by plugin/in_forward.rb because environment variable `SERVERENGINE_SOCKETMANAGER_PATH` is empty when no supervisor mode.

https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_forward.rb#L62

Steps to Reproduce
---------------

Just start fluentd with --no-supervisor with below configuration.

fluentd or td-agent version.
---------------

- fluentd 0.14.0

Environment information, e.g. OS.
----------------

- OS: OS X 10.11.5
- Ruby: ruby 2.2.0

Configuration and Logs
-----------------

```
% fluentd --no-supervisor -c test/fluentd.conf
2016-06-04 20:13:03 +0900 [info]: reading config file path="test/fluentd.conf"
2016-06-04 20:13:03 +0900 [info]: starting fluentd-0.14.0 without supervision
2016-06-04 20:13:03 +0900 [info]: gem 'fluentd' version '0.14.0'
2016-06-04 20:13:03 +0900 [info]: adding match pattern="test.**" type="stdout"
2016-06-04 20:13:03 +0900 [info]: adding source type="forward"
2016-06-04 20:13:03 +0900 [info]: using configuration file: <ROOT>
  <source>
    @type forward
    port 24224
  </source>
  <match test.**>
    @type stdout
  </match>
</ROOT>
2016-06-04 20:13:03 +0900 [info]: listening fluent socket on 0.0.0.0:24224

2016-06-04 20:13:03 +0900 [error]: unexpected error error_class=TypeError error="no implicit conversion of nil into String"
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/serverengine-1.6.4/lib/serverengine/socket_manager_unix.rb:27:in `initialize'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/serverengine-1.6.4/lib/serverengine/socket_manager_unix.rb:27:in `new'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/serverengine-1.6.4/lib/serverengine/socket_manager_unix.rb:27:in `connect_peer'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/serverengine-1.6.4/lib/serverengine/socket_manager.rb:30:in `listen_tcp'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/plugin/in_forward.rb:100:in `listen'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/plugin/in_forward.rb:68:in `start'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:138:in `block in start'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:127:in `block (2 levels) in lifecycle'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:126:in `each'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:126:in `block in lifecycle'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:113:in `each'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:113:in `lifecycle'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:137:in `start'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/engine.rb:211:in `start'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/engine.rb:175:in `run'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/supervisor.rb:580:in `run_engine'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/supervisor.rb:382:in `block in run_worker'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/supervisor.rb:509:in `call'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/supervisor.rb:509:in `main_process'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/supervisor.rb:378:in `run_worker'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/lib/fluent/command/fluentd.rb:266:in `<top (required)>'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fluentd-0.14.0/bin/fluentd:5:in `<top (required)>'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/bin/fluentd:23:in `load'
  2016-06-04 20:13:03 +0900 [error]: /Users/mizutani/.rbenv/versions/2.2.0/bin/fluentd:23:in `<main>'
2016-06-04 20:13:03 +0900 [error]: unexpected error error="no implicit conversion of nil into String"
  2016-06-04 20:13:03 +0900 [error]: suppressed same stacktrace
```

**Comment by repeatedly** [comment]
@naritta Could you handle this?

**Comment by naritta** [comment]
@repeatedly 
I fixed in https://github.com/fluent/fluentd/pull/1033
Could you review when you have time?
