### ISSUE TITLE
Buffer chunk encoding compatibility between v0.12 and v0.14

### ISSUE THREAD

**Issue by mia-0032** [fluent/fluentd#1106]
Hello,

I am investigating BufferedOutput encoding error reported in https://github.com/mdoi/fluent-plugin-gcloud-pubsub/issues/11.
I found `chunk.msgpack_each` in `BufferedOutput#write` returns different encoded fields between fluentd v0.12 and v0.14.
v0.12 returns `UTF-8` encoded, but v0.14 returns `ASCII-8BIT` encoded.

And the difference occurs when `in_tail` plugin is used and `encoding` option not configured. 
I summarized my investigation to below.

| | v0.14 | v0.12 |
|:--:|:--:|:--:|
| in_dummy | UTF-8 | UTF-8 |
| in_tail with encoding utf-8 | UTF-8 | UTF-8 |
| in_tail without encoding option | ASCII-8BIT | UTF-8 |

Is this behaivior intented?

---

- fluentd version.

v0.12.26 and v0.14.1

- Environment information, e.g. OS.

OS X 10.11.5

- Your configuration
```
<source>
  @type tail
  @id in_tail
  path /path/to/dummy.log
  pos_file /path/to/dummy.log.pos
  tag test.local
  format ltsv
  #encoding utf-8
</source>

#<source>
#  @type dummy
#  tag test.local
#  dummy {"text":"あああ"}
#</source>

<match test.**>
  @type gcloud_pubsub
  @id out_pubsub
  project test-prj
  topic my-topic
  autocreate_topic true
  buffer_type memory
  flush_interval 1s
  try_flush_interval 0.05
  key /path/to/key.json
</match>
```

- Your problem explanation. If you have an error logs, write it together.

Error message:

```
2016-07-16 19:02:33 +0900 [error]: unexpected error error="\"\\xE3\" from ASCII-8BIT to UTF-8"
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/lib/fluent/plugin/out_gcloud_pubsub.rb:61:in `encode'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/lib/fluent/plugin/out_gcloud_pubsub.rb:61:in `to_json'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/lib/fluent/plugin/out_gcloud_pubsub.rb:61:in `block in write'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/vendor/bundle/ruby/2.2.0/gems/fluentd-0.14.1/lib/fluent/event.rb:222:in `each'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/vendor/bundle/ruby/2.2.0/gems/fluentd-0.14.1/lib/fluent/event.rb:222:in `block in each'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/vendor/bundle/ruby/2.2.0/gems/fluentd-0.14.1/lib/fluent/plugin/buffer/memory_chunk.rb:90:in `open'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/vendor/bundle/ruby/2.2.0/gems/fluentd-0.14.1/lib/fluent/plugin/buffer/memory_chunk.rb:90:in `open'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/vendor/bundle/ruby/2.2.0/gems/fluentd-0.14.1/lib/fluent/event.rb:221:in `each'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/lib/fluent/plugin/out_gcloud_pubsub.rb:58:in `write'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/vendor/bundle/ruby/2.2.0/gems/fluentd-0.14.1/lib/fluent/compat/output.rb:119:in `write'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/vendor/bundle/ruby/2.2.0/gems/fluentd-0.14.1/lib/fluent/plugin/output.rb:787:in `try_flush'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/vendor/bundle/ruby/2.2.0/gems/fluentd-0.14.1/lib/fluent/plugin/output.rb:962:in `flush_thread_run'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/vendor/bundle/ruby/2.2.0/gems/fluentd-0.14.1/lib/fluent/plugin/output.rb:369:in `block (2 levels) in start'
  2016-07-16 19:02:33 +0900 [error]: /path/to/fluent-plugin-gcloud-pubsub/vendor/bundle/ruby/2.2.0/gems/fluentd-0.14.1/lib/fluent/plugin_helper/thread.rb:66:in `block in thread_create'
```

Log:
```
id:0000	time:[2016-07-16 19:02:04]	level:DEBUG	method:POST	uri:/api/v1/people	reqtime:3.053540515830725	foobar:dNjtvYKx	text:あ
```

**Comment by repeatedly** [comment]
Hmm... v0.14 seems correct.
Difference between msgpack version may cause this problem.

**Comment by mia-0032** [comment]
@repeatedly Thank you for your reply.

> v0.14 seems correct.

I think so too. 

Which is better way to work properly on both version (v0.12 and v0.14) Fluentd adding `encoding` config param to the plugin or using another module such as `Yajl` (as far as I know `Yajl#dump` don't cause this error) in the plugin?
Or any good ideas?

**Comment by repeatedly** [comment]
Maybe, using `Yajl#dump` is easier for avoiding this problem for now.

**Comment by mia-0032** [comment]
@repeatedly Thank you! I see. I'll close this issue.
