### ISSUE TITLE
multiline mode in_tail plugin update [feature]

### ISSUE THREAD

**Issue by msergg** [fluent/fluentd#1109]
Its will be very usefull to add next feature for multiline mode, that consists of two parts:

1 Its need to have possibility to parse stack traces in logs as one message
as example

2012-02-02 12:12:12 ERROR [Procedure.java:222] Error occured
       Exception in thread "main" java.lang.NullPointerException
        at com.example.myproject.Book.getTitle(Book.java:16)
        at com.example.myproject.Author.getBookTitles(Author.java:25)
        at com.example.myproject.Bootstrap.main(Bootstrap.java:14)
2012-02-02 12:12:12 INFO [Procedure.java:222] Info message1
2012-02-02 12:12:12 INFO [Procedure.java:222] Info message2

We can use multiline to use regexp on first_line to parse FIRST line  "2012-02-02 12:12:12 ERROR [Procedure.java:222] Error occured"
and read all next lines as one field " Exception in thread "main" java.lang.NullPointerException
        at com.example.myproject.Book.getTitle(Book.java:16)
        at com.example.myproject.Author.getBookTitles(Author.java:25)
        at com.example.myproject.Bootstrap.main(Bootstrap.java:14)"
before dont see new pattern as 	"2012-02-02 12:12:12 INFO [Procedure.java:222] Info message1" or smth else.
We can use smth like "trace: true" option to configurate this.

2 The second one is
to group all log lines using some similar field 
as example 
2012-02-02 12:12:12 INFO [Procedure.java:222] rid:111111 Info message1
2012-02-02 12:12:12 INFO [Procedure.java:222] rid:111111 Info message2
2012-02-02 12:12:12 INFO [Procedure.java:222] rid:111222 Info message3
2012-02-02 12:12:12 INFO [Procedure.java:222] rid:111222 Info message4
2012-02-02 12:12:12 INFO [Procedure.java:222] rid:111111 Info message5
2012-02-02 12:12:12 INFO [Procedure.java:222] rid:111111 Info message6

we can group its by rid field, so we can get resalt for rid:111222 as :
 datetime:"2012-02-02 12:12:12" severity:"INFO"  rid:"111222" msg : "Info message3 Info message4"
 
 in cofiguration files we can use 
 multiline: true;
 group_by_field:{rid};
 multiline_timeout: 5s; //to prevent buffer overloading
 
 Please correct if smth like this is already working;
 
 Thank you.

**Comment by repeatedly** [comment]
> 1 Its need to have possibility to parse stack traces in logs as one message

Sorry, I can't understand what do you want

> 2 The second one is
to group all log lines using some similar field

**Comment by msergg** [comment]
From http://docs.fluentd.org/articles/parser-plugin-overview we can parse only exact number of trace lines. but mostly java stack trace line count is variable, so we cant parse them all.

> This Java's stacktrace pattern doesn't work?

2 The second one is to group all log lines using some similar field
This should be done by filter.

Thank you

**Comment by repeatedly** [comment]
> From http://docs.fluentd.org/articles/parser-plugin-overview we can parse only exact number of trace lines.

Where?

**Comment by msergg** [comment]
Yes, thank you a lot.
I just trying to such things later, and cant.
