### ISSUE TITLE
in_forward RuntimeError after logrotate

### ISSUE THREAD

**Issue by Yanson** [fluent/fluentd#1129]
After upgrading to td-agent 2.3.2-0 (fluentd **0.12.26**) I am seeing some servers crash each morning.

It appears to happen after the logroate each day.

```
$ cat /etc/logrotate.d/td-agent
/var/log/td-agent/td-agent.log {
  daily
  rotate 30
  compress
  delaycompress
  notifempty
  create 640 td-agent td-agent
  sharedscripts
  postrotate
    pid=/var/run/td-agent/td-agent.pid
    test -s $pid && kill -USR1 "$(cat $pid)"
  endscript
}
```

```
$ sudo grep SIGUSR1 /var/log/td-agent/td-agent.log.1
2016-07-28 06:29:05 +0000 [debug]: fluent/supervisor.rb:408:block in install_supervisor_signal_handlers: fluentd supervisor process get SIGUSR1
2016-07-28 06:29:05 +0000 [debug]: fluent/supervisor.rb:552:block in install_main_process_signal_handlers: fluentd main process get SIGUSR1
```

```
$ sudo grep RuntimeError /var/log/td-agent/td-agent.log
2016-07-28 06:29:56 +0000 [error]: plugin/in_forward.rb:107:rescue in run: unexpected error error=#<RuntimeError: can't add a new key into hash during iteration> error_class=RuntimeError
```

Note, there is no stack trace associated with the error.

Nothing special about the forward config:
```
<source>
  type forward
</source>
```

I have not been able to reproduce this by sending `USR1` myself.

**Comment by repeatedly** [comment]
Does this happen with only fluentd v0.12.26?

**Comment by repeatedly** [comment]
Hmm... error seems to happen inside Cool.io's run method.
I will check the code.

**Comment by Yanson** [comment]
I don't know if it only happens in that version. I only know it started happening since upgrading to td-agent 2.3.2-0.
It is definitely ongoing, today it brought down 3 of 8 servers. Note, we are running three regions and only the high traffic region was affected (the other 6 servers across two regions remain OK).

Is there another version you would like me to try?

Is there a way to get the stack trace? From the code it appears it should print it but it never shows.

**Comment by repeatedly** [comment]
I checked the cool.io code but I can't find "can't add a new key into hash during iteration" code.

> Note, there is no stack trace associated with the error.

If you okay, could you paste entire logs here?

**Comment by Yanson** [comment]
That error is a generic Ruby exception. We need to find where `in_forward` or `cool.io` is doing that.

Here are logs from this morning:

**/var/log/td-agent/td-agent.log.1**
```
2016-07-29 06:31:42 +0000 [trace]: plugin/in_forward.rb:234:initialize: accepted fluent socket from '172.18.0.92:60987': object_id=70080492968760
2016-07-29 06:31:42 +0000 [trace]: plugin/in_forward.rb:297:respond: sent response to fluent socket
  2016-07-29 06:31:42 +0000 [trace]: plugin/in_forward.rb:302:on_close: closed socket
2016-07-29 06:31:42 +0000 [debug]: fluent/supervisor.rb:408:block in install_supervisor_signal_handlers: fluentd supervisor process get SIGUSR1
2016-07-29 06:31:42 +0000 [debug]: fluent/supervisor.rb:552:block in install_main_process_signal_handlers: fluentd main process get SIGUSR1
2016-07-29 06:31:42 +0000 [info]: fluent/supervisor.rb:553:block in install_main_process_signal_handlers: force flushing buffered events
```

**/var/log/td-agent/td-agent.log**
```
2016-07-29 06:31:43 +0000 [trace]: plugin/in_forward.rb:234:initialize: accepted fluent socket from '172.18.0.93:10173': object_id=70080498632680
2016-07-29 06:31:43 +0000 [debug]: plugin/input_session.rb:122:on_read: on_read
  2016-07-29 06:31:44 +0000 [trace]: plugin/in_forward.rb:302:on_close: closed socket
2016-07-29 06:31:44 +0000 [trace]: plugin/in_forward.rb:234:initialize: accepted fluent socket from '172.18.0.37:33779': object_id=70080508162440
2016-07-29 06:31:44 +0000 [trace]: plugin/in_forward.rb:302:on_close: closed socket
... many of these repeated
2016-07-29 06:32:23 +0000 [trace]: plugin/in_forward.rb:234:initialize: accepted fluent socket from '172.18.0.37:33982': object_id=70080507561160
2016-07-29 06:32:23 +0000 [error]: plugin/in_forward.rb:107:rescue in run: unexpected error error=#<RuntimeError: can't add a new key into hash during iteration> error_class=RuntimeError
2016-07-29 06:32:23 +0000 [debug]: plugin/input_session.rb:122:on_read: on_read
  2016-07-29 06:32:14 +0000 [debug]: fluent/agent.rb:121:rescue in block in flush_recursive: error while force flushing error_class=NoMethodError error=#<NoMethodError: undefined method `outputs' for #<Fluent::RouteOutput:0x007f79c79b37d0>>
2016-07-29 06:32:26 +0000 [debug]: fluent/agent.rb:113:flush_recursive: suppressed same stacktrace
  2016-07-29 06:32:26 +0000 [debug]: fluent/supervisor.rb:561:block (2 levels) in install_main_process_signal_handlers: flushing thread: flushed
  2016-07-29 06:32:26 +0000 [debug]: plugin/out_s3.rb:231:write: out_s3: write chunk: {key:2016-07-29_06,tsuffix:538bff657a8ca444} to s3://com.domain.projecgt/a-logs-prod/fluentd02.region.domain.com/2016-07-29_06_0.gz
  2016-07-29 06:32:26 +0000 [debug]: plugin/out_s3.rb:231:write: out_s3: write chunk: {key:2016-07-29_06,tsuffix:538bff6331a515d7} to s3://com.domain.projecgt/b-logs-prod/2016-07-29_06/other/2016-07-29_06-fluentd02.region.domain.com_0.gz
  2016-07-29 06:32:27 +0000 [debug]: plugin/out_s3.rb:231:write: out_s3: write chunk: {key:2016-07-29_06,tsuffix:538bff6145ba1bf7} to s3://com.domain.projecgt/c-logs-prod/fluentd02.region.domain.com/2016-07-29_06_0.gz
  2016-07-29 06:32:34 +0000 [debug]: plugin/input_session.rb:122:on_read: on_read
  2016-07-29 06:32:44 +0000 [debug]: plugin/input_session.rb:122:on_read: on_read
  2016-07-29 06:32:51 +0000 [trace]: plugin/in_secure_forward.rb:248:block in run: accept tcp connection (ssl session not established yet)
2016-07-29 06:32:51 +0000 [debug]: plugin/input_session.rb:148:start: starting server
2016-07-29 06:32:51 +0000 [trace]: plugin/input_session.rb:150:start: accepting ssl session
```

The `undefined method 'outputs'` error is harmless and shows on servers that do not die. It's due to the route plugin not declaring an empty `outupts` array.

That's the last I see of `in_forward` until restarting the process:
```
2016-07-29 08:59:41 +0000 [info]: plugin/in_forward.rb:88:listen: listening fluent socket on 0.0.0.0:24224
2016-07-29 08:59:41 +0000 [debug]: plugin/in_http.rb:103:start: listening http on 0.0.0.0:9880
2016-07-29 08:59:41 +0000 [debug]: plugin/in_monitor_agent.rb:239:start: listening monitoring http server on http://0.0.0.0:24220/api/plugins
2016-07-29 08:59:41 +0000 [info]: plugin/in_tail.rb:529:initialize: following tail of /var/log/puppet.log
2016-07-29 08:59:41 +0000 [trace]: plugin/in_secure_forward.rb:215:run: setup for ssl sessions
2016-07-29 08:59:41 +0000 [trace]: plugin/in_secure_forward.rb:239:run: start to listen bind="0.0.0.0" port=24284
2016-07-29 08:59:41 +0000 [trace]: plugin/in_secure_forward.rb:241:run: starting SSL server bind="0.0.0.0" port=24284
2016-07-29 08:59:41 +0000 [trace]: plugin/in_secure_forward.rb:245:run: accepting sessions
2016-07-29 08:59:41 +0000 [trace]: plugin/in_forward.rb:234:initialize: accepted fluent socket from '172.18.0.93:29191': object_id=70035891859780
2016-07-29 08:59:41 +0000 [trace]: plugin/in_forward.rb:302:on_close: closed socket
2016-07-29 08:59:41 +0000 [trace]: plugin/in_forward.rb:234:initialize: accepted fluent socket from '172.18.0.37:46665': object_id=70035891856140
2016-07-29 08:59:41 +0000 [trace]: plugin/in_forward.rb:302:on_close: closed socket
```

Not sure why there isn't a stack trace for the in_forwrad RuntimeError.

**Comment by repeatedly** [comment]
> Not sure why there isn't a stack trace for the in_forwrad RuntimeError.

One cause is raising exception inside `error_stacktrace`.
After this error happen, does in_forward stop receiving events?

**Comment by repeatedly** [comment]
And if you hit this problem again,
could you send CONT signal to dump internal status?

http://docs.fluentd.org/articles/trouble-shooting#dump-fluentd-internal-information

**Comment by Yanson** [comment]
Yes, in_forward stops receiving events. The other servers retry until the hit a server that's still up (in this environment we use TCP ELB).
I'll forward the sigdump tomorrow morning when it happens again.

**Comment by Yanson** [comment]
I had SIGCONT in the crontab but apparently that doesn't work. Updated to CONT now so should have the dump tomorrow.

**Comment by Yanson** [comment]
Here it is:

```
Sigdump at 2016-08-04 06:56:01 +0000 process 28007 (/usr/sbin/td-agent)
  Thread #<Thread:0x007f58a219e770> status=run priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `dump_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:34:in `block in dump_all_thread_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `each'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `dump_all_thread_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:16:in `block in dump'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `open'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `_open_dump_path'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:14:in `dump'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:7:in `block in setup'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:350:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:350:in `waitpid'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:350:in `supervise'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:156:in `start'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
      /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
      /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/bin/fluentd:5:in `<top (required)>'
      /opt/td-agent/embedded/bin/fluentd:23:in `load'
      /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
      /usr/sbin/td-agent:7:in `load'
      /usr/sbin/td-agent:7:in `<main>'
  GC stat:
      count: 23
      heap_used: 261
      heap_length: 261
      heap_increment: 0
      heap_live_slot: 105598
      heap_free_slot: 785
      heap_final_slot: 0
      heap_swept_slot: 48264
      heap_eden_page_length: 261
      heap_tomb_page_length: 0
      total_allocated_object: 440868
      total_freed_object: 335270
      malloc_increase: 1884440
      malloc_limit: 16777216
      minor_gc_count: 17
      major_gc_count: 6
      remembered_shady_object: 698
      remembered_shady_object_limit: 952
      old_object: 44367
      old_object_limit: 78792
      oldmalloc_increase: 5358720
      oldmalloc_limit: 16777216
  Built-in objects:
   106,383: TOTAL
    56,186: T_STRING
    24,576: T_NODE
    11,657: T_ARRAY
     5,506: T_DATA
     2,829: T_OBJECT
     2,014: T_CLASS
     1,460: T_REGEXP
       881: FREE
       818: T_HASH
       137: T_MODULE
       129: T_ICLASS
        59: T_RATIONAL
        46: T_MATCH
        36: T_STRUCT
        35: T_FILE
         9: T_FLOAT
         4: T_BIGNUM
         1: T_COMPLEX
```

**Comment by repeatedly** [comment]
So your problem is reproducible, right?

> Here it is:

Sorry, I forgot to mention correct info.
I need parent and child sigdump result.
Your result is parent one. Could you also send SIGCONT to child after same problem happen?

**Comment by Yanson** [comment]
This problem is reoccurring everyday, I think shortly after log rotation. It affects around 50% of the servers unload load (but not the same ones each day). I currently have a cron to restart td-agent each morning.

I should have the child sigdump for you tomorrow.

**Comment by Yanson** [comment]
Child dump:

```
Sigdump at 2016-08-09 06:56:01 +0000 process 20053 (/usr/sbin/td-agent)
  Thread #<Thread:0x007f22e019e768> status=run priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `dump_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:34:in `block in dump_all_thread_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `each'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `dump_all_thread_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:16:in `block in dump'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `open'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `_open_dump_path'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:14:in `dump'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:7:in `block in setup'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run_once'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/engine.rb:199:in `run'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:570:in `run_engine'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:162:in `block in start'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:366:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:366:in `main_process'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:339:in `block in supervise'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:338:in `fork'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:338:in `supervise'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:156:in `start'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
      /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
      /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/bin/fluentd:5:in `<top (required)>'
      /opt/td-agent/embedded/bin/fluentd:23:in `load'
      /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
      /usr/sbin/td-agent:7:in `load'
      /usr/sbin/td-agent:7:in `<main>'
  Thread #<Thread:0x007f22d6a95b78> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
  Thread #<Thread:0x007f22d88a4790> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
<...snip - repeated over 50 times...>
  Thread #<Thread:0x007f22d880edf8> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run_once'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_http.rb:131:in `run'
  Thread #<Thread:0x007f22d93f4b68> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/2.1.0/webrick/server.rb:170:in `select'
      /opt/td-agent/embedded/lib/ruby/2.1.0/webrick/server.rb:170:in `block in start'
      /opt/td-agent/embedded/lib/ruby/2.1.0/webrick/server.rb:32:in `start'
      /opt/td-agent/embedded/lib/ruby/2.1.0/webrick/server.rb:160:in `start'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_monitor_agent.rb:251:in `block in start'
  Thread #<Thread:0x007f22d93e67c0> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run_once'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:253:in `run'
  Thread #<Thread:0x007f22d93e6298> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/ssl.rb:302:in `accept'
      /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/ssl.rb:302:in `accept'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-secure-forward-0.4.1/lib/fluent/plugin/in_secure_forward.rb:247:in `block in run'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-secure-forward-0.4.1/lib/fluent/plugin/in_secure_forward.rb:246:in `loop'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-secure-forward-0.4.1/lib/fluent/plugin/in_secure_forward.rb:246:in `run'
  Thread #<Thread:0x007f22d93e3728> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/engine.rb:167:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/engine.rb:167:in `log_event_loop'
  Thread #<Thread:0x007f22d92e99d0> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/2.1.0/webrick/utils.rb:176:in `sleep'
      /opt/td-agent/embedded/lib/ruby/2.1.0/webrick/utils.rb:176:in `block in initialize'
  Thread #<Thread:0x007f22c5af8f18> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-secure-forward-0.4.1/lib/fluent/plugin/input_session.rb:190:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-secure-forward-0.4.1/lib/fluent/plugin/input_session.rb:190:in `rescue in block in start'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-secure-forward-0.4.1/lib/fluent/plugin/input_session.rb:179:in `block in start'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-secure-forward-0.4.1/lib/fluent/plugin/input_session.rb:178:in `loop'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-secure-forward-0.4.1/lib/fluent/plugin/input_session.rb:178:in `start'
  GC stat:
      count: 145104
      heap_used: 1312
      heap_length: 1506
      heap_increment: 393
      heap_live_slot: 201530
      heap_free_slot: 333225
      heap_final_slot: 0
      heap_swept_slot: 251987
      heap_eden_page_length: 919
      heap_tomb_page_length: 393
      total_allocated_object: 41255410286
      total_freed_object: 41255208756
      malloc_increase: 1499360
      malloc_limit: 33554432
      minor_gc_count: 133663
      major_gc_count: 11441
      remembered_shady_object: 3401
      remembered_shady_object_limit: 6770
      old_object: 164585
      old_object_limit: 328906
      oldmalloc_increase: 76018752
      oldmalloc_limit: 134217728
  Built-in objects:
   534,755: TOTAL
   333,135: FREE
    92,874: T_STRING
    32,618: T_ARRAY
    22,405: T_DATA
    16,743: T_OBJECT
    14,487: T_NODE
    13,997: T_HASH
     5,387: T_CLASS
     1,452: T_REGEXP
       705: T_ICLASS
       397: T_MODULE
       317: T_STRUCT
       105: T_MATCH
        65: T_RATIONAL
        45: T_FILE
        13: T_BIGNUM
         9: T_FLOAT
         1: T_COMPLEX
```

**Comment by tagomoris** [comment]
As far as I checked v0.12 code, signal handler for SIGUSR1 does iteration for `@buffer.keys` without any locks/mutex.
https://github.com/fluent/fluentd/blob/v0.12/lib/fluent/supervisor.rb#L551
https://github.com/fluent/fluentd/blob/v0.12/lib/fluent/agent.rb#L116
https://github.com/fluent/fluentd/blob/v0.12/lib/fluent/output.rb#L293

If the running thread changes from this thread to another thread which is trying to add another key from `in_forward` to `@buffer.keys`, it raises this error.

@repeatedly Can you provide a patch to protect `@buffer.keys` by mutex, or just do `@buffer.keys.dup.each`(I think this works well for this case) in `force_flush` to see whether the patch can improve the situation or not?

(v0.14 has lock to guard for such situation)

**Comment by repeatedly** [comment]
@tagomoris Ah, I forgot to check signal handler path. I will write a patch.

**Comment by repeatedly** [comment]
@Yanson I attached a patch for this problem.
Could you try it on your environment?
One easier way is download output.rb, wget https://raw.githubusercontent.com/fluent/fluentd/36f2c359286c78489b7d71b22412dbf727c32e60/lib/fluent/output.rb, and copy it into your fluentd's lib/fluent/output.rb

**Comment by Yanson** [comment]
Applied it to the env. Should be able to tell if it worked by tomorrow.

**Comment by Yanson** [comment]
One server still seemed to be affected after the fix. Let's give it a few more days to verify. I'll report back on Tuesday.

**Comment by repeatedly** [comment]
Thanks!

**Comment by Yanson** [comment]
I'm afraid this is still happening. Either I applied it to the wrong file or it's not the cause of the issue.

```
# grep SIGUSR1 /var/log/td-agent/td-agent.log.1
2016-08-30 06:41:24 +0000 [debug]: fluent/supervisor.rb:408:block in install_supervisor_signal_handlers: fluentd supervisor process get SIGUSR1
2016-08-30 06:41:24 +0000 [debug]: fluent/supervisor.rb:552:block in install_main_process_signal_handlers: fluentd main process get SIGUSR1
```

```
# grep RuntimeError /var/log/td-agent/td-agent.log
2016-08-30 06:41:35 +0000 [error]: plugin/in_forward.rb:107:rescue in run: unexpected error error=#<RuntimeError: can't add a new key into hash during iteration> error_class=RuntimeError
```

```
# find /opt/td-agent -name output.rb
/opt/td-agent/embedded/lib/ruby/2.1.0/rexml/output.rb
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/test-unit-3.1.9/lib/test/unit/util/output.rb
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-plaintextformatter-0.2.6/test/output.rb
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.61/lib/fluent/output.rb
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/output.rb
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb
```

```
# grep '@buffer.keys' /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb
      buf_keys = @buffer.synchronize { @buffer.keys }
          @buffer.keys.each {|key|
          @buffer.keys.each {|key|
        buf_keys = @buffer.synchronize { @buffer.keys }
```

**Comment by repeatedly** [comment]
Hmm... I see.
I update my patch, https://github.com/fluent/fluentd/pull/1181, to make lock scope longer to check enqueue_buffer has a problem or not.
If you have a time, could you apply new patch again?
Sorry for the inconvenience...

**Comment by Yanson** [comment]
No problem, I've applied it.
If I haven't reported back by this time tomorrow, please ping me as I am going on holiday soon and expect this environment to be torn down by my return. We only have one more opportunity to apply a patch and test it.

**Comment by Yanson** [comment]
Sorry. This updated patch hasn't helped.

**Comment by repeatedly** [comment]
Hmm... so the problem doesn't happen inside buffer operations.

**Comment by repeatedly** [comment]
Happened error is same as before, right?

**Comment by Yanson** [comment]
Yeah, I verified it as shown in #issuecomment-243428071.

**Comment by Yanson** [comment]
I've been able to reproduce this today by forcing logrotate:
```
sudo logrotate -f /etc/logrotate.d/td-agent
```

I've also tried changing `@map.each_key` to `@map.keys.each` in `buf_file.rb` and `buf_memory.rb` but it hasn't helped. Maybe fixing the `error_backtrace` will give us some more clues?

**Comment by repeatedly** [comment]
> Maybe fixing the error_backtrace will give us some more clues?

Yeah, it may help.
Could you apply following patch? `log.puts(e.backtrace)` simply outputs the backtrace of error.

```diff
diff --git a/lib/fluent/plugin/in_forward.rb b/lib/fluent/plugin/in_forward.rb
index f303757..f5e1078 100644
--- a/lib/fluent/plugin/in_forward.rb
+++ b/lib/fluent/plugin/in_forward.rb
@@ -107,7 +107,7 @@ module Fluent
       @loop.run(@blocking_timeout)
     rescue => e
       log.error "unexpected error", error: e, error_class: e.class
-      log.error_backtrace
+      log.puts(e.backtrace)
     end
 
     private
```

**Comment by maxmil** [comment]
@Yanson is on leave and I'm picking up where he left off.

I've applied the patch but the backtrace only goes as far as where coo.io attaches it to an event loop. I presume that the backtrace is lost after this but that this is not the cause.

``
2016-09-06 08:57:01 +0000 [error]: plugin/in_forward.rb:107:rescue in run: unexpected error error=#<RuntimeError: can't add a new key into hash during iteration> error_class=RuntimeError
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/io.rb:35:in `attach'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/io.rb:35:in `attach'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/io.rb:35:in `attach'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/socket.rb:39:in `attach'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/server.rb:40:in `on_connection'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/listener.rb:46:in `on_readable'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run_once'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_forward.rb:105:in `run'
``

**Comment by repeatedly** [comment]
In cool.io, watcher's attach / detach access `@watchers` hash object, but it seems no problem because these methods don't iterate hash object.

If you okay, could you test this problme with latest fluentd v0.14.5?
Executing `/usr/sbin/td-agent-gem install fluentd -v 0.14.5` instead of applying patch is enough.
I'm not sure what the plugins do you use but latest v0.14 should cover existing plugins.

**Comment by maxmil** [comment]
Our config is not compatible with v0.14.5

```
2016-09-06 21:38:26 +0000 [error]: config/section.rb:158:block in generate: config error in:
<buffer time>
  flush_mode interval
  retry_type exponential_backoff
  flush_thread_count 4
  flush_interval 10
  flush_thread_interval 2
  retry_forever 
  retry_max_interval 300
  chunk_limit_size 8m
  queue_length_limit 128
  timekey 86400
</buffer>

2016-09-06 21:38:26 +0000 [error]: fluent/supervisor.rb:608:rescue in main_process: config error file="/etc/td-agent/td-agent.conf" error="'path' parameter is required"
```

Rather than updating we'd like to find and patch the error in v0.12.26

My suspicion is that cool.io is swallowing the error. I haven't looked at the code in detail but is there somewhere we can put error handling after the cool.io event is dispatched back into fluent code to try to log the error?

**Comment by repeatedly** [comment]
> Our config is not compatible with v0.14.5

Could you paste your configuration here without sensitive information?
Buffer related parameters should work without any changes.

**Comment by repeatedly** [comment]
> My suspicion is that cool.io is swallowing the error.

@nurse Cool.io is C extension and does it cut stacktrace information?

**Comment by nurse** [comment]
@repeatedly In C extension there's C level stacks.
But in Ruby level backtrace they don't appear.

`#<RuntimeError: can't add a new key into hash during iteration>` is raised by Ruby's C API, which seems to be called by cool.io.
If we can reproduce the issue, we catch the exception with GDB or investigate with custom built Ruby...

**Comment by Yanson** [comment]
Our environment is no longer available to test/reproduce the issue so I'm afraid I'll have to bow out of this thread.

**Comment by repeatedly** [comment]
I see. Currenlty, this problem happened on only your environment, so temporarily closed.
If anyone hits this problem, reopen this issue!
