### ISSUE TITLE
error_class=Elasticsearch::Transport::Transport::Errors::BadRequest error="[400] {\"error\":\"ElasticsearchParseException[Failed to derive xcontent]\",\"status\":400}

### ISSUE THREAD

**Issue by alogoc** [fluent/fluentd#1158]
**- fluentd or td-agent version.**

`Package: td-agent
Versions:
2.3.2-0 (/var/lib/apt/lists/packages.treasuredata.com_2_ubuntu_trusty_dists_trusty_contrib_binary-amd64_Packages.gz) (/var/lib/dpkg/status)
 Description Language:
                 File: /var/lib/apt/lists/packages.treasuredata.com_2_ubuntu_trusty_dists_trusty_contrib_binary-amd64_Packages.gz
                  MD5: 9a8c3c5185974525f7e38d7f37f5d597`

`Reverse Depends:
Dependencies:
2.3.2-0 - lsb-base (0 (null))
Provides:
2.3.2-0 -
Reverse Provides:`

**- Environment information, e.g. OS.**

Kubernetes on top of CoreOS. 

**- configuration**
 
Fluentd is containerized and is scheduled as daemonset (one container per host).

Fluentd plugins versions:

elasticsearch (1.1.0)
elasticsearch-api (1.1.0)
elasticsearch-transport (1.1.0)
fluent-logger (0.5.1)
fluent-plugin-elasticsearch (1.5.0)
fluent-plugin-secure-forward (0.4.2)
fluent-plugin-td (0.10.28)
fluent-plugin-td-monitoring (0.2.2)
fluentd (0.14.2)

Elasticsearch configuartion on td-agent.conf:

     # Log Forwarding
     <match logs.**  systemd.** kubernetes.** monitor_agent.**>
       @type copy
       <store>
         @type elasticsearch
         log_level error
         include_tag_key true
         tag_key tag
         host elasticsearch
         port 9200
         logstash_format true
         # Set the chunk limit
         buffer_chunk_limit 2m
         # Cap buffer memory usage to 2MiB/chunk * 32 chunks = 64 MiB
         buffer_queue_limit 32
         flush_interval 15s
         # Never wait longer than 5 minutes between retries.
         max_retry_wait 60
         # Disable the limit on the number of retries (retry forever).
         disable_retry_limit
       </store>

**- Problem explanation**

Fluentd is failing on 3 out of 5 nodes on the same cluster. All nodes have exactly the same configuration and using the very same docker image scheduled from kubernetes.

The fluentd-elasticsearch plugin is crashing on the failing nodes and this is the output :

```
  2016-08-11 14:48:10 +0000 [warn]: /usr/sbin/td-agent:7:in `load'
  2016-08-11 14:48:10 +0000 [warn]: /usr/sbin/td-agent:7:in `<main>'
2016-08-11 14:48:10 +0000 [info]: preparing shutdown input plugin type=:monitor_agent plugin_id="object:1c01f38"
2016-08-11 14:48:10 +0000 [info]: preparing shutdown input plugin type=:systemd plugin_id="object:1722da0"
2016-08-11 14:48:10 +0000 [info]: preparing shutdown input plugin type=:systemd plugin_id="object:171923c"
2016-08-11 14:48:10 +0000 [info]: preparing shutdown input plugin type=:systemd plugin_id="object:170ad90"
2016-08-11 14:48:10 +0000 [info]: preparing shutdown input plugin type=:systemd plugin_id="object:170ffd4"
2016-08-11 14:48:10 +0000 [info]: preparing shutdown input plugin type=:tail plugin_id="object:1ba7948"
2016-08-11 14:48:10 +0000 [info]: preparing shutdown input plugin type=:systemd plugin_id="object:1701b8c"
2016-08-11 14:48:10 +0000 [info]: preparing shutdown output plugin type=:record_reformer plugin_id="object:1d95318"
2016-08-11 14:48:10 +0000 [info]: preparing shutdown output plugin type=:copy plugin_id="object:1ddb00c"
2016-08-11 14:48:10 +0000 [info]: preparing shutdown output plugin type=:elasticsearch plugin_id="object:1cc8bec"
2016-08-11 14:48:10 +0000 [warn]: unexpected error while preparing shutdown on output plugin plugin=Fluent::ElasticsearchOutput plugin_id="object:1cc8bec" error_class=Elasticsearch::Transport::Transport::Errors::BadRequest error="[400] {\"error\":\"ElasticsearchParseException[Failed to derive xcontent]\",\"status\":400}"
  2016-08-11 14:48:10 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
  2016-08-11 14:48:10 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
  2016-08-11 14:48:10 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2016-08-11 14:48:10 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/client.rb:128:in `perform_request'
  2016-08-11 14:48:10 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.1.0/lib/elasticsearch/api/actions/bulk.rb:93:in `bulk'
  2016-08-11 14:48:10 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:278:in `send'
  2016-08-11 14:48:10 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.2/lib/fluent/root_agent.rb:197:in `block (3 levels) in shutdown'
2016-08-11 14:48:10 +0000 [info]: preparing shutdown filter plugin type=:kubernetes_metadata plugin_id="object:b87248"
2016-08-11 14:48:10 +0000 [info]: preparing shutdown output plugin type=:null plugin_id="object:ed0b34"
2016-08-11 14:48:10 +0000 [info]: shutting down input plugin type=:monitor_agent plugin_id="object:1c01f38"
2016-08-11 14:48:10 +0000 [info]: shutting down input plugin type=:tail plugin_id="object:1ba7948"
2016-08-11 14:48:10 +0000 [info]: shutting down input plugin type=:systemd plugin_id="object:1722da0"
2016-08-11 14:48:10 +0000 [info]: shutting down input plugin type=:systemd plugin_id="object:170ffd4"
2016-08-11 14:48:10 +0000 [info]: shutting down input plugin type=:systemd plugin_id="object:171923c"
2016-08-11 14:48:10 +0000 [info]: shutting down input plugin type=:systemd plugin_id="object:1701b8c"
2016-08-11 14:48:10 +0000 [info]: shutting down input plugin type=:systemd plugin_id="object:170ad90"
2016-08-11 14:48:10 +0000 [warn]: super was not called in #shutdown: calling it forcedly plugin=Fluent::SystemdInput
2016-08-11 14:48:11 +0000 [warn]: super was not called in #shutdown: calling it forcedly plugin=Fluent::SystemdInput
2016-08-11 14:48:11 +0000 [warn]: super was not called in #shutdown: calling it forcedly plugin=Fluent::SystemdInput
2016-08-11 14:48:11 +0000 [warn]: super was not called in #shutdown: calling it forcedly plugin=Fluent::SystemdInput
2016-08-11 14:48:11 +0000 [warn]: super was not called in #shutdown: calling it forcedly plugin=Fluent::SystemdInput
2016-08-11 14:48:22 +0000 [info]: shutting down output plugin type=:record_reformer plugin_id="object:1d95318"
2016-08-11 14:48:22 +0000 [info]: shutting down output plugin type=:copy plugin_id="object:1ddb00c"
2016-08-11 14:48:22 +0000 [info]: shutting down output plugin type=:elasticsearch plugin_id="object:1cc8bec"
2016-08-11 14:48:22 +0000 [warn]: unexpected error while shutting down on output plugin plugin=Fluent::ElasticsearchOutput plugin_id="object:1cc8bec" error_class=Elasticsearch::Transport::Transport::Errors::BadRequest error="[400] {\"error\":\"ElasticsearchParseException[Failed to derive xcontent]\",\"status\":400}"
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/client.rb:128:in `perform_request'
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.1.0/lib/elasticsearch/api/actions/bulk.rb:93:in `bulk'
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:278:in `send'
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.2/lib/fluent/root_agent.rb:197:in `block (3 levels) in shutdown'
2016-08-11 14:48:22 +0000 [info]: shutting down filter plugin type=:kubernetes_metadata plugin_id="object:b87248"
2016-08-11 14:48:22 +0000 [info]: shutting down output plugin type=:null plugin_id="object:ed0b34"
2016-08-11 14:48:22 +0000 [warn]: unexpected error while calling after_shutdown on output plugin pluguin=Fluent::ElasticsearchOutput plugin_id="object:1cc8bec" error_class=Elasticsearch::Transport::Transport::Errors::BadRequest error="[400] {\"error\":\"ElasticsearchParseException[Failed to derive xcontent]\",\"status\":400}"
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/client.rb:128:in `perform_request'
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.1.0/lib/elasticsearch/api/actions/bulk.rb:93:in `bulk'
  2016-08-11 14:48:22 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:278:in `send'
```

**Comment by repeatedly** [comment]
I'm not sure this is a bug of fluentd / fluent-plugin-elasticsearch: https://github.com/elastic/elasticsearch/issues/8595
We need more information.

**Comment by repeatedly** [comment]
You have already posted same issue on fluent-plugin-elasticsearch.
If the problme is fluentd core, please re-open.
