### ISSUE TITLE
error="undefined method `to_msgpack'

### ISSUE THREAD

**Issue by sallespro** [fluent/fluentd#1160]
Using https://github.com/fluent/fluentd-docker-image, the error shows up with Elasticsearch and InfluxDB Output plugins.

#### Problem(s)

2016-08-11 21:49:35 +0000 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `to_msgpack' for BSON::ObjectId('572a626be5f72f000600000c'):BSON::ObjectId" tag="ast13-ast-1"
  2016-08-11 21:49:35 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:174:in `to_msgpack'
  2016-08-11 21:49:35 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:174:in `format'

#### Steps to replicate

```
  <source>
    type mongo_tail
    url mongodb://mongodb/grid_server
    collection container_logs
    tag_key name
    time_key created_at
    id_store_collection container_logs_tail
  </source>
  <match **>
    type elasticsearch
    logstash_format true
    host elasticsearchhost.example
    port 9200
    index_name fluentd
    type_name fluentd
    include_tag_key true
  </match>
```

**Comment by repeatedly** [comment]
Input plugin should not emit non-json type key/value.
This seems a bug of fluent-plugin-mongo so I close this issue.
Please re-open an issue on fluent-plugin-mongo
