### ISSUE TITLE
es_size not resolved - Fluentd 0.14.2 with Datadog plugin 0.18

### ISSUE THREAD

**Issue by stevenc81** [fluent/fluentd#1163]
2016-08-16 05:29:31 +0000 [warn]: emit transaction failed: error_class=NameError error="undefined local variable or method `es_size' for #<Fluent::DdOutput:007f9ea78381d0>" tag="fluentd.metrics"
  2016-08-16 05:29:31 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/compat/output.rb:368:in `block in handle_stream_simple'
  2016-08-16 05:29:31 +0000 [warn]: /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  2016-08-16 05:29:31 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/compat/output.rb:368:in `handle_stream_simple'
  2016-08-16 05:29:31 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/plugin/output.rb:587:in `execute_chunking'
  2016-08-16 05:29:31 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/plugin/output.rb:531:in `emit_buffered'
  2016-08-16 05:29:31 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/event_router.rb:90:in `emit_stream'
  2016-08-16 05:29:31 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/plugin/in_monitor_agent.rb:265:in `block in start'
  2016-08-16 05:29:31 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/plugin/in_monitor_agent.rb:229:in `on_timer'
  2016-08-16 05:29:31 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run_once'
  2016-08-16 05:29:31 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run'
  2016-08-16 05:29:31 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/plugin/in_monitor_agent.rb:273:in `run'

**Comment by repeatedly** [comment]
Thanks for the report.
It seems a typo here: https://github.com/fluent/fluentd/blob/c18015ca28c4a8a61b632aaa15dc88f9dba2aae5/lib/fluent/compat/output.rb#L368

**Comment by repeatedly** [comment]
Here is a patch: https://github.com/fluent/fluentd/pull/1164
Could you try it?

**Comment by stevenc81** [comment]
Thanks for the prompt fix @repeatedly :) I've fallback to version v0.12 as it seems we have some more compatibility issues with v0.14? Sorry to digress, here is another interesting one that only happens in v0.14

https://github.com/awslabs/aws-fluent-plugin-kinesis/issues/80

**Comment by repeatedly** [comment]
> it seems we have some more compatibility issues with v0.14?

Compatibility layer should work but we don't test all plugins. So it may have a bug.
