### ISSUE TITLE
Unexpected error: "uninitialized constant Fluent::Plugin::MultiOutput"

### ISSUE THREAD

**Issue by fenicks** [fluent/fluentd#1205]
When using fluentd 0.14.4, I encounter an exception described by the logs below. It seems that `Fluent::Plugin::MultiOutput` is not defined : 

```
Command terminated with signal Terminated (pid: 12602)
2016-09-05 23:27:59 +0200 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2016-09-05 23:27:59 +0200 [info]: gem 'fluent-plugin-forest' version '0.3.1'
2016-09-05 23:27:59 +0200 [info]: gem 'fluent-plugin-forest' version '0.3.0'
2016-09-05 23:27:59 +0200 [info]: gem 'fluent-plugin-s3' version '0.7.1'
2016-09-05 23:27:59 +0200 [info]: gem 'fluent-plugin-s3' version '0.7.0'
2016-09-05 23:27:59 +0200 [info]: gem 'fluent-plugin-s3' version '0.6.8'
2016-09-05 23:27:59 +0200 [info]: gem 'fluentd' version '0.14.4'
2016-09-05 23:27:59 +0200 [info]: gem 'fluentd' version '0.14.1'
2016-09-05 23:27:59 +0200 [info]: adding match pattern="kiqli.{test,development,production}.**" type="forest"
2016-09-05 23:27:59 +0200 [error]: unexpected error error="uninitialized constant Fluent::Plugin::MultiOutput\nDid you mean?  Fluent::MultiOutput"
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/lib/fluent/agent.rb:137:in `add_match'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/lib/fluent/agent.rb:69:in `block in configure'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/lib/fluent/agent.rb:63:in `each'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/lib/fluent/agent.rb:63:in `configure'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/lib/fluent/root_agent.rb:86:in `configure'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/lib/fluent/engine.rb:119:in `configure'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/lib/fluent/engine.rb:93:in `run_configure'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/lib/fluent/supervisor.rb:673:in `run_configure'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/lib/fluent/supervisor.rb:435:in `block in run_worker'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/lib/fluent/supervisor.rb:606:in `main_process'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/lib/fluent/supervisor.rb:431:in `run_worker'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/lib/fluent/command/fluentd.rb:271:in `<top (required)>'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/gems/fluentd-0.14.4/bin/fluentd:5:in `<top (required)>'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/bin/fluentd:22:in `load'
  2016-09-05 23:27:59 +0200 [error]: /usr/local/rvm/gems/ruby-2.3.1/bin/fluentd:22:in `<main>'
2016-09-05 23:27:59 +0200 [info]: Worker 0 finished with status 1

```

**Comment by tagomoris** [comment]
We shipped the quick release v0.14.5 with the fix for this issue.
@fenicks Could you check it?

**Comment by fenicks** [comment]
@tagomoris It works. Thank you.

**Comment by tagomoris** [comment]
Good to hear that!
