### ISSUE TITLE
in_tail crashes due to uninitialized constant Fluent::Plugin::MultilineParser on 0.14.5

### ISSUE THREAD

**Issue by warmfusion** [fluent/fluentd#1213]
FluentD 0.14.5
Ruby 2.1.5p2773
Debian Jessie

## Problem

in_tail (and maybe others) do not include the Multiline plugin automatically causing an exception to be thrown when this core coponent is used.

### Fix

Add the following to the includes at the top of in_tail.rb
```
require 'fluent/plugin/parser_multiline'
```

### Stack Trace

```
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: unexpected error error="uninitialized constant Fluent::Plugin::MultilineParser"
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/plugin/in_tail.rb:88:in `configure'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/root_agent.rb:237:in `add_source'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/root_agent.rb:95:in `block in configure'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/root_agent.rb:92:in `each'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/root_agent.rb:92:in `configure'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/engine.rb:119:in `configure'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/engine.rb:93:in `run_configure'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/supervisor.rb:673:in `run_configure'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/supervisor.rb:435:in `block in run_worker'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/supervisor.rb:606:in `call'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/supervisor.rb:606:in `main_process'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/supervisor.rb:431:in `run_worker'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/command/fluentd.rb:271:in `<top (required)>'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/bin/fluentd:5:in `<top (required)>'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /usr/local/bin/fluentd:23:in `load'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /usr/local/bin/fluentd:23:in `<main>'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [info]: Worker 0 finished unexpectedly with status 1
```

**Comment by repeatedly** [comment]
Fixed by https://github.com/fluent/fluentd/pull/1212
