### ISSUE TITLE
time must be a Fluent::EventTime (or Integer): Float

### ISSUE THREAD

**Issue by dimaqq** [fluent/fluentd#1220]
My stack:
* fluentd 0.14.6
* gem install json_pure fluent-plugin-loggly

My config:
* accept fluent's own protocol over tcp
* sender is Python + fluent-logger
* buffered, bulk upload to loggly

Error:
```
fluentd_1  | 2016-09-09 07:51:17 +0000 http: {"module":"misc","level":"INFO","function":"on_get","thread_name":"MainThread","domain":null,"tid":42,"source":"misc.py:36","message":"Serving an empty response","thread":140138439919360,"pid":23,"user":null,"request_id":"V9Jp9awSAAYAAAAJftUAAACA"}
fluentd_1  | 2016-09-09 07:51:17 +0000 [warn]: emit transaction failed: error_class=ArgumentError error="time must be a Fluent::EventTime (or Integer): Float" tag="http"
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/output.rb:561:in `metadata'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/output.rb:659:in `block in handle_stream_with_custom_format'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/event.rb:100:in `each'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/output.rb:658:in `handle_stream_with_custom_format'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/output.rb:602:in `execute_chunking'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/output.rb:544:in `emit_buffered'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/out_copy.rb:38:in `block in process'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/out_copy.rb:37:in `each'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/out_copy.rb:37:in `process'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/multi_output.rb:89:in `emit_sync'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/event_router.rb:153:in `emit_events'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/event_router.rb:90:in `emit_stream'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/event_router.rb:81:in `emit'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/in_forward.rb:376:in `on_message'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/in_forward.rb:231:in `block in handle_connection'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/in_forward.rb:272:in `block (3 levels) in read_messages'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/in_forward.rb:271:in `feed_each'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/in_forward.rb:271:in `block (2 levels) in read_messages'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/in_forward.rb:280:in `block in read_messages'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/in_forward.rb:559:in `on_read'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/io.rb:123:in `on_readable'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/io.rb:186:in `on_readable'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run_once'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run'
fluentd_1  |   2016-09-09 07:51:17 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/in_forward.rb:190:in `run'
fluentd_1  | 2016-09-09 07:51:17 +0000 [error]: unexpected error on reading data from client address="172.18.0.4" error_class=ArgumentError error="time must be a Fluent::EventTime (or Integer): Float"
```

It's partially my responsibility, because I forced a float to `.emit_with_time()`.

My intention was to get fluentd to process timestamp with millisecond granularity.

If I should, in fact use some other data format (a tuple?) please let me know, I can try to come up with a patch against https://github.com/fluent/fluent-logger-python

**Comment by repeatedly** [comment]
> My intention was to get fluentd to process timestamp with millisecond granularity.

Fluentd's event time is nano-second granularity since v0.14.
Each language loggers should support it in the future, not float for millisecond.

**Comment by dimaqq** [comment]
Ok, what is the binary, `msgpack` format for nanosecond timestamp?

**Comment by cosmo0920** [comment]
EventTime ext format specification will help you: https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#eventtime-ext-format

**Comment by dimaqq** [comment]
Thanks, I'll hack up a merge request against python bindings if functionality is not there yet.

**Comment by dimaqq** [comment]
https://github.com/fluent/fluent-logger-python/pull/61 :-)

**Comment by repeatedly** [comment]
Should be handled by other plugins

**Comment by dimaqq** [comment]
Consider that per https://github.com/fluent/fluent-logger-python/pull/61#issuecomment-245987200 plugins cannot simply send new protocol version.

0.12.x handled float in this field (it truncated value to int and accepted the message).

I believe that 0.14.x needs to accept messages with float too, either by truncating to int like before, or by converting float to EventTime internally.

**Comment by tagomoris** [comment]
Fluentd v0.12's behavior about floating point numerics are undocumented, and out of support.
It's unexpected result of calling `to_i` for any objects, including `Float` values, when needed. It's not limited for float.
You can write filter plugins to convert `float` into any objects, using `Filter#filter_with_time` method of Fluentd v0.14. But it can't be supported by Fluentd because of performance reason.

**Comment by dimaqq** [comment]
Well guys, it's up to you.

From end-user perspective it's a regression --- this weird stuff we used to do breaks when we upgrade only `fluentd` in our system.

Perhaps you can get by with documenting this fact, e.g.:

> Backwards compatibility notes:
> Fluentd 0.14 and later is stricter with incoming data if you use its own protocol.
> If you are using xxx, yyy or zzz, please test before deployment.
