### ISSUE TITLE
supervisor.rb:49:in `initialize': No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by sbezverk** [fluent/fluentd#1225]
I am trying to start manually td-agent in docker container and it see the following failure. I would appreciate if somebody could  help to understand what I have done wrong.

```
root@fluentd-elasticsearch:/# /etc/init.d/td-agent start
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:49:in `initialize': No such file or directory @ rb_sysopen - /var/log/td-agent/td-agent.log (Errno::ENOENT)
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:49:in `open'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:49:in `init'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:126:in `start'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/bin/fluentd:6:in `<top (required)>'
        from /opt/td-agent/embedded/bin/fluentd:23:in `load'
        from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
        from /usr/sbin/td-agent:7:in `load'
        from /usr/sbin/td-agent:7:in `<main>'
   ...fail!
```

More complete log:

```
2016-09-10 23:07:30 +0000 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2016-09-10 23:07:30 +0000 [info]: starting fluentd-0.12.12
2016-09-10 23:07:30 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.3.0'
2016-09-10 23:07:30 +0000 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-09-10 23:07:30 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '0.9.0'
2016-09-10 23:07:30 +0000 [info]: gem 'fluent-plugin-mongo' version '0.7.10'
2016-09-10 23:07:30 +0000 [info]: gem 'fluent-plugin-record-reformer' version '0.7.0'
2016-09-10 23:07:30 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.4.1'
2016-09-10 23:07:30 +0000 [info]: gem 'fluent-plugin-s3' version '0.5.9'
2016-09-10 23:07:30 +0000 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2016-09-10 23:07:30 +0000 [info]: gem 'fluent-plugin-td' version '0.10.27'
2016-09-10 23:07:30 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.1'
2016-09-10 23:07:30 +0000 [info]: gem 'fluent-plugin-webhdfs' version '0.4.1'
2016-09-10 23:07:30 +0000 [info]: gem 'fluentd' version '0.12.12'
2016-09-10 23:07:30 +0000 [info]: adding match pattern="reform.**" type="record_reformer"
2016-09-10 23:07:30 +0000 [info]: adding match pattern="**" type="elasticsearch"
2016-09-10 23:07:30 +0000 [info]: adding source type="tail"
2016-09-10 23:07:30 +0000 [info]: adding source type="tail"
2016-09-10 23:07:30 +0000 [info]: adding source type="tail"
2016-09-10 23:07:30 +0000 [info]: adding source type="tail"
2016-09-10 23:07:30 +0000 [info]: adding source type="tail"
2016-09-10 23:07:30 +0000 [info]: adding source type="tail"
2016-09-10 23:07:30 +0000 [info]: adding source type="tail"
2016-09-10 23:07:30 +0000 [info]: using configuration file: <ROOT>
  <source>
    type tail
    format json
    time_key time
    path /varlog/containers/*.log
    pos_file /varlog/es-containers.log.pos
    time_format %Y-%m-%dT%H:%M:%S
    tag reform.*
    read_from_head true
  </source>
  <match reform.**>
    type record_reformer
    enable_ruby true
    tag kubernetes.${tag_suffix[3].split('-')[0..-2].join('-')}
  </match>
  <source>
    type tail
    format none
    path /varlog/startupscript.log
    pos_file /varlog/es-startupscript.log.pos
    tag startupscript
  </source>
  <source>
    type tail
    format none
    path /varlog/docker.log
    pos_file /varlog/es-docker.log.pos
    tag docker
  </source>
  <source>
    type tail
    format none
    path /varlog/kubelet.log
    pos_file /varlog/es-kubelet.log.pos
    tag kubelet
  </source>
  <source>
    type tail
    format none
    path /varlog/kube-apiserver.log
    pos_file /varlog/es-kube-apiserver.log.pos
    tag kube-apiserver
  </source>
  <source>
    type tail
    format none
    path /varlog/kube-controller-manager.log
    pos_file /varlog/es-kube-controller-manager.log.pos
    tag kube-controller-manager
  </source>
  <source>
    type tail
    format none
    path /varlog/kube-scheduler.log
    pos_file /varlog/es-kube-scheduler.log.pos
    tag kube-scheduler
  </source>
  <match **>
    type elasticsearch
    log_level info
    include_tag_key true
    host elasticsearch-logging
    port 9200
    logstash_format true
    buffer_chunk_limit 512K
    buffer_queue_limit 128
    flush_interval 5s
    max_retry_wait 300
    disable_retry_limit 
  </match>
</ROOT>
2016-09-10 23:07:30 +0000 [error]: unexpected error error_class=Errno::ENOENT error=#<Errno::ENOENT: No such file or directory @ rb_sysopen - /varlog/es-containers.log.pos>
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/in_tail.rb:79:in `initialize'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/in_tail.rb:79:in `open'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/in_tail.rb:79:in `start'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/root_agent.rb:111:in `block in start'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/root_agent.rb:110:in `each'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/root_agent.rb:110:in `start'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/engine.rb:201:in `start'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/engine.rb:151:in `run'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:539:in `run_engine'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:143:in `block in start'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:306:in `call'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:306:in `main_process'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:281:in `block in supervise'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:280:in `fork'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:280:in `supervise'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:137:in `start'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/bin/fluentd:6:in `<top (required)>'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2016-09-10 23:07:30 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2016-09-10 23:07:30 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2016-09-10 23:07:30 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2016-09-10 23:07:30 +0000 [info]: shutting down fluentd
2016-09-10 23:07:30 +0000 [info]: process finished code=0
2016-09-10 23:07:30 +0000 [warn]: process died within 1 second. exit.
```

**Comment by repeatedly** [comment]
Log says your container doesn't have `/var/log/td-agent` directory.
td-agent installation script creates related directories, so I assume your docker image build process or setup script remove its directory.

**Comment by sbezverk** [comment]
Thank you veru much for your reply. I pulled the image from gcr.io/google_containers/fluentd-elasticsearch:1.6
I kind of assumed it would be the image ready to use.  I will add a step to create this folder at the time of container start. thank you again..

**Comment by sbezverk** [comment]
Even after I created right before the start /var/log/td-agent folder, the conainer still crashes. td-agent.log show see below, it is like td-agent is misconfigured in the image :(. Could you please share the location of tested Docker file for fluentd?

cat /var/log/td-agent/td-agent.log 
Usage: td-agent [options]
    -s, --setup [DIR=/etc/td-agent]  install sample configuration file to the directory
    -c, --config PATH                config file path (default: /etc/td-agent/td-agent.conf)
        --dry-run                    Check fluentd setup is correct or not
    -p, --plugin DIR                 add plugin directory
    -I PATH                          add library path
    -r NAME                          load library
    -d, --daemon PIDFILE             daemonize fluent process
        --no-supervisor              run without fluent supervisor
        --user USER                  change user
        --group GROUP                change group
    -o, --log PATH                   log file path
    -i CONFIG_STRING,                inline config which is appended to the config file on-fly
        --inline-config
        --emit-error-log-interval SECONDS
                                     suppress interval seconds of emit error logs
        --suppress-repeated-stacktrace [VALUE]
                                     suppress repeated stacktrace
        --without-source             invoke a fluentd without input plugins
        --use-v1-config              Use v1 configuration format (default)
        --use-v0-config              Use v0 configuration format
    -v, --verbose                    increase verbose level (-v: debug, -vv: trace)
    -q, --quiet                      decrease verbose level (-q: warn, -qq: error)
        --suppress-config-dump       suppress config dumping when fluentd starts
    -g, --gemfile GEMFILE            Gemfile path
    -G, --gem-path GEM_INSTALL_PATH  Gemfile install path (default: $(dirname $gemfile)/vendor/bundle)

**Comment by repeatedly** [comment]
Hmm... do you modify td-agent setting?
For fluentd, fluentd-docker-image is one example.
For td-agent, several users build own docker image using td-agent rpm / deb. I just searched it on github and I found one simple example: https://github.com/pebble/docker-td-agent/blob/master/Dockerfile

**Comment by repeatedly** [comment]
Ah, I missed first your reply about `gcr.io/google_containers/fluentd-elasticsearch:1.6`
I'm not sure how fluentd-elasticsearch launches td-agent process but above dockerfile is useful for baseline comparison.

**Comment by tagomoris** [comment]
Is it a problem of the container of `gcr.io/google_containers/fluentd-elasticsearch:1.6`?

**Comment by tagomoris** [comment]
Let me close this issue. Please reopen this if any problem still exists.

**Comment by DrPyser** [comment]
Hi!

I seem to be having a similar issue with the dockerhub `fluent/fluentd:v1.10-1` image:
```
fluentd-dev_fluentd.1.ylrscei7hhbt@R90R4K4C    | fluentd -v -c /fluentd/fluent.conf
fluentd-dev_fluentd.1.ylrscei7hhbt@R90R4K4C    | /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.3/lib/fluent/config.rb:31:in `initialize': No such file or directory @ rb_sysopen -  /fluentd/fluent.conf (Errno::ENOENT)
fluentd-dev_fluentd.1.ylrscei7hhbt@R90R4K4C    |        from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.3/lib/fluent/config.rb:31:in `open'
fluentd-dev_fluentd.1.ylrscei7hhbt@R90R4K4C    |        from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.3/lib/fluent/config.rb:31:in `build'
fluentd-dev_fluentd.1.ylrscei7hhbt@R90R4K4C    |        from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.3/lib/fluent/supervisor.rb:627:in `configure'
fluentd-dev_fluentd.1.ylrscei7hhbt@R90R4K4C    |        from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.3/lib/fluent/command/fluentd.rb:329:in `<top (required)>'
fluentd-dev_fluentd.1.ylrscei7hhbt@R90R4K4C    |        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fluentd-dev_fluentd.1.ylrscei7hhbt@R90R4K4C    |        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
fluentd-dev_fluentd.1.ylrscei7hhbt@R90R4K4C    |        from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.3/bin/fluentd:8:in `<top (required)>'
fluentd-dev_fluentd.1.ylrscei7hhbt@R90R4K4C    |        from /usr/bin/fluentd:23:in `load'
fluentd-dev_fluentd.1.ylrscei7hhbt@R90R4K4C    |        from /usr/bin/fluentd:23:in `<main>'
```

**Comment by DrPyser** [comment]
Oh, I'm using docker swarm configs:
```yaml
services:
  fluentd:
    ...
    configs:
      - source: fluentd_config
        target: /fluentd/fluent.conf
        mode: 777
```
