### ISSUE TITLE
Runtime dependency on json gem

### ISSUE THREAD

**Issue by bdentino** [fluent/fluentd#1237]
Fluentd version 0.14.4
Building custom docker image for fluentd from alpine:3.4

Running fluentd gives the following error:

```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.4/lib/fluent/config/literal_parser.rb:19:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.4/lib/fluent/config/element.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.4/lib/fluent/config.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.4/lib/fluent/supervisor.rb:20:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.4/lib/fluent/command/fluentd.rb:19:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.4/bin/fluentd:5:in `<top (required)>'
	from /usr/bin/fluentd:23:in `load'
	from /usr/bin/fluentd:23:in `<main>'
```

The issue is resolved by running `gem install json`. Maybe fluentd just needs to list this as a runtime dependency? I'm new to ruby so this could also be me just misconfiguring something I don't know about.

Here's my full Dockerfile:

```
FROM alpine:3.4

ENV FLUENTD_OPT= \
    FLUENTD_CONF=fluent.conf \
    FLUENTD_DATA_DIR=/home/fluent \
    FLUENTD_VERSION=0.14.4

RUN apk --no-cache --update add \
                            build-base \
                            ca-certificates \
                            ruby \
                            ruby-irb \
                            ruby-dev \
                            curl && \
    curl -L -o /usr/sbin/dosu https://raw.githubusercontent.com/mvertes/dosu/0.1.0/dosu && \
    chmod +x /usr/sbin/dosu && \
    echo 'gem: --no-document' >> /etc/gemrc && \
    gem install json && \
    gem install fluentd -v $FLUENTD_VERSION && \
    apk del build-base ruby-dev curl && \
    rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /usr/lib/ruby/gems/*/cache/*.gem

RUN adduser -D -g '' -u 1000 -h /home/fluent fluent
RUN chown -R fluent:fluent /home/fluent

WORKDIR /home/fluent

# Tell ruby to install packages as user
RUN echo "gem: --user-install --no-document" >> ~/.gemrc
ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH
ENV GEM_PATH /home/fluent/.gem/ruby/2.3.0:$GEM_PATH

ADD fluent.conf /home/fluent/fluent.conf
ADD plugins /home/fluent/plugins
ADD entrypoint.sh /entrypoint.sh

EXPOSE 24224 5140

CMD /entrypoint.sh
```

**Comment by repeatedly** [comment]
I'm not sure why this happens because ruby itself include json library as a default gems.
I assume this is not the fluentd issue but I can't judge it...

**Comment by repeatedly** [comment]
If you don't hit this problem with normal environment,
the problem is caused by alpine linux's ruby or something.

**Comment by bdentino** [comment]
Yep, I think you're right:

```
(alpine 3.4 w/ apk add --no-cache ruby)
/ # gem list -d

*** LOCAL GEMS ***

did_you_mean (1.0.0)
    Author: Yuki Nishijima
    Homepage: https://github.com/yuki24/did_you_mean
    License: MIT
    Installed at: /usr/lib/ruby/gems/2.3.0

    "Did you mean?" experience in Ruby

minitest (5.8.3)
    Author: Ryan Davis
    Homepage: https://github.com/seattlerb/minitest
    License: MIT
    Installed at: /usr/lib/ruby/gems/2.3.0

    minitest provides a complete suite of testing facilities supporting
    TDD, BDD, mocking, and benchmarking

net-telnet (0.1.1)
    Author: SHIBATA Hiroshi
    Homepage: https://github.com/ruby/net-telnet
    Installed at: /usr/lib/ruby/gems/2.3.0

    Provides telnet client functionality.

power_assert (0.2.6)
    Author: Kazuki Tsujimoto
    Homepage: https://github.com/k-tsj/power_assert
    Licenses: 2-clause BSDL, Ruby's
    Installed at: /usr/lib/ruby/gems/2.3.0

    Power Assert for Ruby

psych (2.0.17)
    Author: Aaron Patterson
    Homepage: http://github.com/tenderlove/psych
    License: MIT
    Installed at (default): /usr/lib/ruby/gems/2.3.0

    Psych is a YAML parser and emitter

rake (10.4.2)
    Authors: Eric Hodel, Jim Weirich
    Homepage: https://github.com/ruby/rake
    License: MIT
    Installed at: /usr/lib/ruby/gems/2.3.0

    Rake is a Make-like program implemented in Ruby

test-unit (3.1.5)
    Authors: Kouhei Sutou, Haruka Yoshihara
    Homepage: http://test-unit.github.io/
    Licenses: Ruby, PSFL
    Installed at: /usr/lib/ruby/gems/2.3.0

    An xUnit family unit testing framework for Ruby.
```

In that case, feel free to close this issue. It's probably worth mentioning though that the official fluentd [Dockerfile](https://hub.docker.com/r/fluent/fluentd/~/dockerfile/) is built off alpine so it might be worth including json in the gemspec just to avoid confusion when upgrading (unless you see some harm in doing so).

**Comment by repeatedly** [comment]
Okay. Could you send a patch to fluentd-docker-image to install json gem?
