### ISSUE TITLE
Getting a `register_impl`: undefined method trace for Nil class

### ISSUE THREAD

**Issue by KunalArora** [fluent/fluentd#1253]
`Environment`

Ruby   ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
Fluentd  fluentd 0.12.29

Code
```rb
require 'fluent/output'

    module Fluent
       class AfscoSupplyOutput < Fluent::Output

        Fluent::Plugin.register_output('reqOrderId', self)
        ......
        end
    end
```

Error

```
/home/kunal/fluent-plugin-afsco/.bundle/ruby/2.3.0/gems/fluentd-0.12.29/lib/fluent/plugin.rb:178: warning: already initialized constant Fluent::Plugin
/home/kunal/fluent-plugin-afsco/lib/fluent/plugin/afsco/version.rb:2: warning: previous definition of Plugin was here
/home/kunal/fluent-plugin-afsco/.bundle/ruby/2.3.0/gems/fluentd-0.12.29/lib/fluent/plugin.rb:122:in `register_impl': undefined method `trace' for nil:NilClass (NoMethodError)
	from /home/kunal/fluent-plugin-afsco/.bundle/ruby/2.3.0/gems/fluentd-0.12.29/lib/fluent/plugin.rb:35:in `register_output'
	from /home/kunal/fluent-plugin-afsco/lib/fluent/plugin/afsco/out_afsco_supply.rb:6:in `<class:AfscoSupplyOutput>'
	from /home/kunal/fluent-plugin-afsco/lib/fluent/plugin/afsco/out_afsco_supply.rb:4:in `<module:Fluent>'
	from /home/kunal/fluent-plugin-afsco/lib/fluent/plugin/afsco/out_afsco_supply.rb:3:in `<top (required)>'
	from /home/kunal/fluent-plugin-afsco/lib/fluent/plugin/afsco.rb:2:in `require'
	from /home/kunal/fluent-plugin-afsco/lib/fluent/plugin/afsco.rb:2:in `<top (required)>'
	from /home/kunal/fluent-plugin-afsco/test/test_helper.rb:1:in `require'
	from /home/kunal/fluent-plugin-afsco/test/test_helper.rb:1:in `<top (required)>'
	from /home/kunal/fluent-plugin-afsco/test/fluent/plugin/test_afsco.rb:1:in `require'
	from /home/kunal/fluent-plugin-afsco/test/fluent/plugin/test_afsco.rb:1:in `<top (required)>'
	from /home/kunal/fluent-plugin-afsco/.bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `require'
	from /home/kunal/fluent-plugin-afsco/.bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /home/kunal/fluent-plugin-afsco/.bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/kunal/fluent-plugin-afsco/.bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test:lib" -I"/home/kunal/fluent-plugin-afsco/.bundle/ruby/2.3.0/gems/rake-10.5.0/lib" "/home/kunal/fluent-plugin-afsco/.bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/fluent/plugin/test_afsco.rb" "test/fluent/plugin/test_out_afsco_supply.rb" "test/test_helper.rb" ]
/home/kunal/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/kunal/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => test
```

**Comment by repeatedly** [comment]
Does this happen on only test, right?

**Comment by KunalArora** [comment]
Yes, this error only shows up during test environment. Development environment is not getting affected by this.

**Comment by repeatedly** [comment]
Could you show me your test code?

**Comment by KunalArora** [comment]
```ruby
require 'test_helper'
require 'time'

class TestOutputAfscoSupply < Minitest::Test
  include Fluent

  def setup
    Test.setup
    @time = Engine.now
  end

  def create_driver conf = ''
    Test::OutputTestDriver.new(AfscoSupplyOutput).configure(conf)
  end

  def test_out_emit_order_status
    WebMock.enable!
    stub_request(:post, "#{DEFAULT_API_ENDPOINT}/order")
      .with(:body => {"product_code" => PRODUCT_CODE, "user_uuid" => USER_UUID, "device_uuid" => DEVICE_UUID})
      .to_return(:status => 200,
                 :body => '{"order_id": <ORDER_ID>}',
                 :headers => {"Content-Type" => "application/json"})
    d = create_driver(%[
      base_url http://www.example.com
      options /order
    ])
    d.run do
      d.emit({
        "user_id" => <USER_UUID>,
        "device_id" => <DEVICE_UUID>,
        "selected_consumables" => {
          "TonerInk_Black" => "TN010BK",
          "TonerInk_Cyan" => "TN010C",
        },
        "object_id" => "1.3.6.1.4.1.2435.2.3.9.4.2.1.5.5.8.0",
        "name" => "brInfoMaintenance",
        "replenish_item" => "TonerInk_Cyan",
      })
    end

    emits = d.emits
    assert_equal 1, emits.length
    assert_equal ORDER_ID, emits[0][2]["order_id"]
    WebMock.disable!
  end

  def test_out_emit_order_status_event_failed
    WebMock.enable!
    stub_request(:post, "#{DEFAULT_API_ENDPOINT}/order")
      .with(:body => {"product_code" => PRODUCT_CODE, "user_uuid" => USER_UUID, "device_uuid" => DEVICE_UUID})
      .to_return(:status => 400, :body => '')

    d = create_driver(%[
      base_url http://www.example.com
      options /order
      ])

    d.run do
      d.emit({
        "user_id" => <USER_UUID>,
        "device_id" => <DEVICE_UUID>,      
        "selected_consumables" => {
          "TonerInk_Black" => "TN010BK",
          "TonerInk_Cyan" => "TN010C",
        },
        "object_id" => "1.3.6.1.4.1.2435.2.3.9.4.2.1.5.5.8.0",
        "name" => "brInfoMaintenance",
        "replenish_item" => "TonerInk_Cyan",
      })
    end

    emits = d.emits
    assert_equal 1, emits.length
    assert d.instance.log.logs[0].include? '[warn]'
    WebMock.disable!
  end
end
```

**Comment by repeatedly** [comment]
test_helper.rb requires fluentd files?

**Comment by KunalArora** [comment]
test_helper file. Yss, it do include fluentd files
```ruby
require 'fluent/plugin/afsco'
require 'minitest/autorun'
require 'webmock/minitest'
require 'fluent/test'

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'fluent/plugin/afsco/out_afsco_supply'
```

**Comment by repeatedly** [comment]
I tested your example with reduced code but no error.
So maybe, full code is needed to debug it.

BTW, `fluent/plugin/afsco/out_afsco_supply.rb` is wrong. You should `fluent/plugin/out_afsco_supply.rb` to follow fluentd plugin mechanizm.

- plugin code

```
% cat lib/fluent/plugin/out_afsco_supply.rb 
require 'fluent/output'

module Fluent
  class AfscoSupplyOutput < Fluent::Output
    Fluent::Plugin.register_output('afsco_supply', self)

  end
end
```

- test code

```
% cat test/test_afsco_supply.rb 
require 'test_helper'
require 'time'

class TestOutputAfscoSupply < Minitest::Test
  include Fluent

  def setup
    Test.setup
    @time = Engine.now
  end

  def create_driver conf = ''
    Test::OutputTestDriver.new(AfscoSupplyOutput).configure(conf)
  end

  def test_out_emit_order_status
  end

  def test_out_emit_order_status_event_failed
  end
end
```

- test_helper.rb

```
% cat test/test_helper.rb 
require 'minitest/autorun'
require 'webmock/minitest'
require 'fluent/test'

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'fluent/plugin/out_afsco_supply
```

- command

```
RUBYLIB=test ruby test/test_afsco_supply.rb
```

Use ruby directory but Rake should work.

**Comment by KunalArora** [comment]
Thanks for the help. It solved my problem!!
