### ISSUE TITLE
v0.14.x cannot boot without json gem but no dependency 

### ISSUE THREAD

**Issue by joker1007** [fluent/fluentd#1275]
- fluentd v0.14.x
- alpine linux 3.4

ruby package of alpine linux v3.4 doesn't have json gem.
I don't know other platforms but other ruby package without json gem exists maybe.

```
/ # apk --no-cache --update add build-base ca-certificates ruby ruby-irb ruby-dev
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/33) Installing binutils-libs (2.26-r0)
# ...
OK: 185 MiB in 44 packages
/ # ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux-musl]
/ # gem list

*** LOCAL GEMS ***

did_you_mean (1.0.0)
minitest (5.8.3)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (2.0.17)
rake (10.4.2)
test-unit (3.1.5)
```

And, fluentd v0.14 requires 'json' gem on `fluent/config/literal_parser.rb`.
Because of it, fluentd v0.14 cannot boot on alpine linux unless user installs 'json' gem manually.

```
/ # fluentd
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/lib/fluent/config/literal_parser.rb:19:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/lib/fluent/config/element.rb:18:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/lib/fluent/config.rb:18:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/lib/fluent/supervisor.rb:20:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/lib/fluent/command/fluentd.rb:19:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/bin/fluentd:5:in `<top (required)>'
        from /usr/bin/fluentd:23:in `load'
        from /usr/bin/fluentd:23:in `<main>
```

especially, official docker images of fluentd-0.14.x cannot boot. it is probrem.
I think that it is better to add 'json' dependency or fix docker image or remove 'json' dependency from code.

**Comment by repeatedly** [comment]
Duplicated https://github.com/fluent/fluentd/issues/1237

**Comment by joker1007** [comment]
Sorry, I missed it.
