### ISSUE TITLE
When I kill fluentd main process, read log file twice.

### ISSUE THREAD

**Issue by llby** [fluent/fluentd#1278]
I use fluentd v12.26
fluentd's sending log file to the aws kinesis.
log files were described file size at pos_file.
But when I kill fluentd main process, and start td-agent service.
all log files were read again.

```
2016-10-17 11:08:57 +0900 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2016-10-17 11:08:57 +0900 [info]: starting fluentd-0.12.26
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-kinesis' version '1.1.0'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-mongo' version '0.7.13'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-s3' version '0.6.8'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-td' version '0.10.28'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-webhdfs' version '0.4.2'
2016-10-17 11:08:57 +0900 [info]: gem 'fluentd' version '0.12.26'
2016-10-17 11:08:57 +0900 [info]: adding filter pattern="log" type="record_transformer"
2016-10-17 11:08:57 +0900 [info]: adding match pattern="log" type="kinesis_producer"
2016-10-17 11:08:57 +0900 [info]: adding source type="tail"
2016-10-17 11:08:57 +0900 [info]: adding source type="monitor_agent"
2016-10-17 11:08:57 +0900 [info]: using configuration file: 
<ROOT>
  <source>
    @type tail
    format ltsv
    path /var/log/some/*.log
    pos_file /var/log/td-agent/log.pos
    read_from_head true
    tag log
    keys time
  </source>
  <filter log>
    type record_transformer
    <record>
      hostname ${hostname}
    </record>
  </filter>
  <match log>
    @type kinesis_producer
    stream_name stream
    region ap-northeast-1
    aws_key_id xxxxxx
    aws_sec_key xxxxxx
    buffer_type file
    buffer_path /var/log/td-agent/buffer/log
    flush_at_shutdown true
    <kinesis_producer>
      record_ttl 300000
    </kinesis_producer>
  </match>
  <source>
    type monitor_agent
    bind 127.0.0.1
    port 24220
  </source>
</ROOT>
```

**Comment by repeatedly** [comment]
Is this reproducible?

**Comment by llby** [comment]
yes anytime.

**Comment by llby** [comment]
detail of situation.

**Comment by repeatedly** [comment]
I can't reproduce this on my local machine.
I assume you did some actions to cause this problem.

**Comment by llby** [comment]
The detail of situation.

There was some files in buffer.
file name is log..qxxxxxxxxx

```
tail td-agent.log
2016-10-17 10:58:51 +0900 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="log"
```

first I tried restart service td-agent
but It was failed.

```
Restarting td-agent: Timeout error occurred trying to stop [失敗]nt...td-agent
```

I tried kill process.
- fluentd sub process
- kinesis_produce
but kinesis_produce was not dead.

so I tried kill main process and start service td-agent.
In this case, it happens every time.

**Comment by llby** [comment]
Repletion

I tried move log files, Before kill main process at other mashine.
And After start service td-agent. I move back log files.

```
tail td-agent.log
2016-10-17 11:09:56 +0900 [info]: following tail of /var/log/some/2016-10-17.10.00
2016-10-17 11:10:15 +0900 [info]: following tail of /var/log/some/2016-10-17.11.00
2016-10-17 11:12:27 +0900 [info]: following tail of /var/log/some/2016-10-17.10.30
2016-10-17 11:30:21 +0900 [info]: following tail of /var/log/some/2016-10-17.11.30
```

log files were followed againg, but it not read this time.

**Comment by llby** [comment]
It seem involved, a timing of read pos_file?

**Comment by repeatedly** [comment]
I want to know in_tail reads log files twice or
aws kinesis resends same buffer twice.
Could you check it?
Maybe, adding `out_copy` and `out_file` is enough.

<match log>
  @type copy
  <store>
     @type file # the number of records should be same as in_tail targets.
  </store>
  <store>
    @type kinesis_producer
  </store>
</match>

**Comment by llby** [comment]
in_tail reads log files twice
because
When I kill main process and start service td-agent.
generated buffer file in `/var/log/td-agent/buffer/`
file name is log..bxxxxxxxxx
buffer file makes by fluentd. isn't it?

```
tail td-agent.log
2016-10-17 11:09:56 +0900 [info]: following tail of /var/log/some/2016-10-17.10.00
2016-10-17 11:10:15 +0900 [info]: following tail of /var/log/some/2016-10-17.11.00
2016-10-17 11:12:27 +0900 [info]: following tail of /var/log/some/2016-10-17.10.30
2016-10-17 11:30:21 +0900 [info]: following tail of /var/log/some/2016-10-17.11.30
```


I experimented
I tried move log files, Before kill main process at other mashine.
And After start service td-agent. I move back log files.
It not generated buffer file in `/var/log/td-agent/buffer/`
only following

```
tail td-agent.log
2016-10-17 11:09:56 +0900 [info]: following tail of /var/log/some/2016-10-17.10.00
2016-10-17 11:10:15 +0900 [info]: following tail of /var/log/some/2016-10-17.11.00
2016-10-17 11:12:27 +0900 [info]: following tail of /var/log/some/2016-10-17.10.30
2016-10-17 11:30:21 +0900 [info]: following tail of /var/log/some/2016-10-17.11.30
```

**Comment by repeatedly** [comment]
Hmm... I can't debug this problem because I don't have reproducible environment.
Could you debug it?
I want to know why pos_file content is ignored.

**Comment by llby** [comment]
I'll go there?
or you came?
or remote?
or teach me how to debug?

There is same condition servers here(aws).
but it already starting process.
so I think It can't modify the code.

**Comment by llby** [comment]
I find other warning.

```
  2016-10-17 18:17:42 +0900 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="log"
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/buffer.rb:204:in `block in emit'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/buffer.rb:193:in `emit'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:268:in `emit'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/event_router.rb:154:in `emit'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/event_router.rb:90:in `emit_stream'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:269:in `receive_lines'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:373:in `call'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:373:in `wrap_receive_lines'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:568:in `call'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:568:in `on_notify'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:399:in `on_notify'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:500:in `call'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:500:in `on_change'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run_once'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:253:in `run'

```
