### ISSUE TITLE
master breaks compat TimeSlicedOutput

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluentd#1300]
- fluentd version

master branch

- problem

Following error happens

```
2016-11-01 06:44:37 +0900 [warn]: failed to flush the buffer. plugin_id="object:3fde154c3b40" retry_time=0 next_retry=2016-11-01 06:44:38 +0900 chunk="54030002ecad9e781b7d16d4ca0121ce" error_class=NoMethodError error="undefined method `call' for nil:NilClass\nDid you mean?  caller"
  2016-11-01 06:44:37 +0900 [warn]: /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/compat/output.rb:104:in `key'
  2016-11-01 06:44:37 +0900 [warn]: /Users/repeatedly/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fluent-plugin-s3-0.7.1/lib/fluent/plugin/out_s3.rb:203:in `write'
  2016-11-01 06:44:37 +0900 [warn]: /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/compat/output.rb:144:in `write'
  2016-11-01 06:44:37 +0900 [warn]: /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/output.rb:995:in `try_flush'
  2016-11-01 06:44:37 +0900 [warn]: /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/output.rb:1188:in `flush_thread_run'
  2016-11-01 06:44:37 +0900 [warn]: /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/output.rb:393:in `block (2 levels) in start'
  2016-11-01 06:44:37 +0900 [warn]: /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/thread.rb:66:in `block in thread_create'
```

In v0.14.8, `@_timezone` is `+0000`.
In master, `@_timezone` is `nil`. This is why this error happens.

- configuration

You can reproduce this problem by following configuration:

```
<source>
  @type forward
</source>

<match s3.**>
  @type s3
  aws_key_id "..."
  aws_sec_key "..."
  s3_bucket fluentd
  path test/
  buffer_type file
  buffer_path /path/to/buffer/s3
  time_slice_format %Y%m%d%H
  flush_interval 10s
</match>
```

**Comment by tagomoris** [comment]
@repeatedly I can't find any clear cause for that. Can you provide any test case for that?

**Comment by repeatedly** [comment]
@tagomoris This problem doesn't happen on your environment?

**Comment by acty-yoshida** [comment]
I'm facing same issue.
When I set "timezone" option explicitly, it can be avoid this.
"utc" keyworkd is not work. It should specify "timezone".

```
<match s3.**>
  ...
  timezone +0000
</match>
```

* Additional information

TimeSlicedOutput.configure is something wrong?
After calling super, @timezone will be initialized to nil.
I think Configurable module is initializing "timezone" to default value.
https://github.com/fluent/fluentd/blob/master/lib/fluent/compat/output.rb#L567

I hope this information will be help for resolve.
