### ISSUE TITLE
When declaring only `utc` in configuration file, Fluentd raise "both of utc and localtime are specified"

### ISSUE THREAD

**Issue by fenicks** [fluent/fluentd#1329]
Fluentd is complaining that I declare both `localtime` and `utc` but only `utc` is declared in my configuration file.

- fluentd version 0.14.9.
- GNU/Linux CentOS-7

#### Configuration
```
<source>
    @type forward
    port ${PORT}
</source>

<match kiqli.{test,development,production}.**>
    @type forest
    subtype s3

    <template>
        format single_value
        add_newline false
        message_key message
        store_as gzip

        aws_key_id ${AWS_ACCESS_KEY_ID}
        aws_sec_key ${AWS_SECRET_ACCESS_KEY}
        s3_bucket ${S3_BUCKET}
        s3_region ${S3_REGION}
        buffer_type file
        buffer_path fluent/var/log/aws_s3/buffer___TAG__

        time_slice_format %Y%m%dT%H
        time_slice_wait 30m
        utc
        buffer_queue_limit 4096
        buffer_chunk_limit 16m
        flush_interval 5m
        flush_at_shutdown true
        num_threads 1
    </template>

    <case kiqli.production.**>
        path logs/production/kiqli_logs_
        flush_interval 1h
    </case>
    <case kiqli.development.**>
        path logs/development/kiqli_logs_
    </case>
    <case kiqli.test.**>
        path logs/test/kiqli_logs_
    </case>
</match>
```
#### Error output
```
2016-11-26 23:25:26 +0100 [error]: Cannot output messages with tag 'kiqli.production'
2016-11-26 23:26:50 +0100 [error]: failed to configure sub output s3: both of utc and localtime are specified, use only one of them
2016-11-26 23:26:50 +0100 [error]: /usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/compat/formatter_utils.rb:52:in `convert_formatter_conf'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/compat/output.rb:647:in `configure'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:107:in `configure'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluent-plugin-s3-0.7.2/lib/fluent/plugin/out_s3.rb:130:in `configure'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluent-plugin-forest-0.3.3/lib/fluent/plugin/out_forest.rb:132:in `block in plant'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluent-plugin-forest-0.3.3/lib/fluent/plugin/out_forest.rb:128:in `synchronize'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluent-plugin-forest-0.3.3/lib/fluent/plugin/out_forest.rb:128:in `plant'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluent-plugin-forest-0.3.3/lib/fluent/plugin/out_forest.rb:169:in `emit'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/compat/output.rb:199:in `process'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/plugin/bare_output.rb:53:in `emit_sync'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/event_router.rb:90:in `emit_stream'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:292:in `on_message'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:201:in `block in handle_connection'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:242:in `block (3 levels) in read_messages'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:241:in `feed_each'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:241:in `block (2 levels) in read_messages'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:250:in `block in read_messages'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:480:in `on_read'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/cool.io-1.4.5/lib/cool.io/io.rb:123:in `on_readable'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/cool.io-1.4.5/lib/cool.io/io.rb:186:in `on_readable'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run_once'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/plugin_helper/event_loop.rb:71:in `block in start'
/usr/local/rvm/gems/ruby-2.3.1@fluentd/gems/fluentd-0.14.9/lib/fluent/plugin_helper/thread.rb:66:in `block in thread_create'
```

**Comment by repeatedly** [comment]
Fixed by https://github.com/fluent/fluentd/pull/1319
