### ISSUE TITLE
Fluentd v0.14.9: json parser plugin occurs undefined method `info' error

### ISSUE THREAD

**Issue by mia-0032** [fluent/fluentd#1343]
Hi,

I'm testing to use Fluentd v0.14.9 without `oj` gem. But json parser plugin occurs undefined method `info' error.

- fluentd or td-agent version.

Fluentd v0.14.9 and master branch version(without oj gem)

- Environment information, e.g. OS.

OSX and Linux(TravisCI)

- Your configuration

I encounterd this error on TravisCI https://travis-ci.org/mia-0032/fluent-plugin-gcloud-pubsub-custom/jobs/180170659 .

And I checked creating simple plugin.

```ruby
require 'fluent/input'
require 'fluent/parser'

module Fluent
  class TestInput < Input
    Fluent::Plugin.register_input('test', self)
    config_param :format, :string,  default: 'json'

    def configure(conf)
      super
      @parser = Plugin.new_parser(@format)
      @parser.configure(conf)
    end
  end
end
```

fluent.conf is below:

```
<source>
  @type test
</source>
```

- Your problem explanation. If you have an error logs, write it together.

```
2016-12-01 17:30:32 +0900 [error]: unexpected error error="undefined method `info' for nil:NilClass"
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/plugin/parser_json.rb:56:in `rescue in configure_json_parser'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/plugin/parser_json.rb:44:in `configure_json_parser'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/plugin/parser_json.rb:40:in `configure'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/plugin/in_test.rb:12:in `configure'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/root_agent.rb:237:in `add_source'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/root_agent.rb:95:in `block in configure'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/root_agent.rb:92:in `each'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/root_agent.rb:92:in `configure'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/engine.rb:119:in `configure'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/engine.rb:93:in `run_configure'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/supervisor.rb:693:in `run_configure'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/supervisor.rb:453:in `block in run_worker'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/supervisor.rb:626:in `main_process'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/supervisor.rb:449:in `run_worker'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/lib/fluent/command/fluentd.rb:288:in `<top (required)>'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/bin/fluentd:5:in `require'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/bin/fluentd:5:in `<top (required)>'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd:23:in `load'
  2016-12-01 17:30:32 +0900 [error]: /path/to/fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd:23:in `<main>'
2016-12-01 17:30:32 +0900 [info]: Worker 0 finished unexpectedly with status 1
```

Thanks.

**Comment by repeatedly** [comment]
In v0.12, log should not use in parser plugin.
I will fix it soon.

**Comment by repeatedly** [comment]
BTW, you can avoid this problem by specifying "json_parser json".

**Comment by mia-0032** [comment]
Thank you for your response!
