### ISSUE TITLE
multiline parser regex format

### ISSUE THREAD

**Issue by liujiawinds** [fluent/fluentd#1354]
```
2016-12-07 02:45:50.714 [Curator-PathChildrenCache-9] ERROR [org.apache.curator.ConnectionState:198] - Connection timed out for connection string (maxcd01-dev01:2181) and timeout (15000) / elapsed (50091)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:195) [curator-client-2.9.1.jar:na]
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:87) [curator-client-2.9.1.jar:na]
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115) [curator-client-2.9.1.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:487) [curator-framework-2.9.1.jar:na]
	at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:226) [curator-framework-2.9.1.jar:na]
	at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:215) [curator-framework-2.9.1.jar:na]
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107) [curator-client-2.9.1.jar:na]
	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForegroundStandard(ExistsBuilderImpl.java:211) [curator-framework-2.9.1.jar:na]
	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:205) [curator-framework-2.9.1.jar:na]
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:168) [curator-framework-2.9.1.jar:na]
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:39) [curator-framework-2.9.1.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.createContainers(CuratorFrameworkImpl.java:193) [curator-framework-2.9.1.jar:na]
	at org.apache.curator.framework.EnsureContainers.internalEnsure(EnsureContainers.java:61) [curator-framework-2.9.1.jar:na]
	at org.apache.curator.framework.EnsureContainers.ensure(EnsureContainers.java:53) [curator-framework-2.9.1.jar:na]
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.ensurePath(PathChildrenCache.java:571) [curator-recipes-2.9.1.jar:na]
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.refresh(PathChildrenCache.java:486) [curator-recipes-2.9.1.jar:na]
	at org.apache.curator.framework.recipes.cache.RefreshOperation.invoke(RefreshOperation.java:35) [curator-recipes-2.9.1.jar:na]
	at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:766) [curator-recipes-2.9.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_92]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

```

I have a log file and its content like above.I'm trying to parse the log file with `multiline parser`.

referred to the document:
```
format multiline
format_firstline /\d{4}-\d{1,2}-\d{1,2}/
format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) \[(?<thread>.*)\] (?<level>[^\s]+)(?<message>.*)/

INPUT:
2013-3-03 14:27:33 [main] INFO  Main - Start
2013-3-03 14:27:33 [main] ERROR Main - Exception
javax.management.RuntimeErrorException: null
    at Main.main(Main.java:16) ~[bin/:na]
2013-3-03 14:27:33 [main] INFO  Main - End

RESULT:
2013-03-03 14:27:33 +0900 zimbra.mailbox: {"thread":"main","level":"INFO","message":"  Main - Start"}
2013-03-03 14:27:33 +0900 zimbra.mailbox: {"thread":"main","level":"ERROR","message":" Main - Exception\njavax.management.RuntimeErrorException: null\n    at Main.main(Main.java:16) ~[bin/:na]"}
2013-03-03 14:27:33 +0900 zimbra.mailbox: {"thread":"main","level":"INFO","message":"  Main - End"}
```

I wrote a regex like this, but it didn't work as I expected. The message field just contains a single ` - `, not the messages except the first line.
```
<source>
  type tail
  path /services/logs/*/*.log
  pos_file /var/log/es-applogs.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag app.*.*
  format multiline
  format_firstline /^\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{3}/
  format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{3}) \[(?<thread>.*?)\] (?<level>[^\s]+)\s+\[(?<class>.*?):(?<rownum>.*?)\](?<message>.*)/
  read_from_head true
</source>

```

- td-agent: 0.12.29
- OS: centOS7

**Comment by liujiawinds** [comment]
@repeatedly Why close this issue??

**Comment by repeatedly** [comment]
See https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
Don't use issue for the question first.
