### ISSUE TITLE
 No such file or directory @ rb_sysopen - fluent.conf (Errno::ENOENT)

### ISSUE THREAD

**Issue by Mr5hanMan** [fluent/fluentd#1381]
Hi,

I've installed fluentd via the [gem installation](http://docs.fluentd.org/articles/install-by-gem), `gem install fleuntd`, on Ubuntu 16.04.
ruby -v  ruby 2.3.1p112 (2016-04-26) 

I was following the documentation I'm trying to setup my config via the dry run command:  
 `fluentd --dry-run -c fluent.conf`

But I am seeing the following output error when it runs:
 
```
/var/lib/gems/2.3.0/gems/fluentd-0.14.10/lib/fluent/supervisor.rb:659:in `read': No such file or directory @ rb_sysopen - fluent.conf (Errno::ENOENT)
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.10/lib/fluent/supervisor.rb:659:in `read_config'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.10/lib/fluent/supervisor.rb:416:in `run_supervisor'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.10/lib/fluent/command/fluentd.rb:286:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.10/bin/fluentd:5:in `<top (required)>'
	from /usr/local/bin/fluentd:23:in `load'
	from /usr/local/bin/fluentd:23:in `<main>'
```

I am wondering if I have something wrong, I have only un-commented parts of the config file where my apache access logs are mention as I am trying to log these. See config:

```
# In v1 configuration, type and id are @ prefix parameters.
# @type and @id are recommended. type and id are still available for backward compatibility

## built-in TCP input
## $ echo <json> | fluent-cat <tag>
<source>
  @type forward
  @id forward_input
</source>

## built-in UNIX socket input
#<source>
#  @type unix
#</source>

# HTTP input
# http://localhost:8888/<tag>?json=<json>
<source>
  @type http
  @id http_input

  port 8888
</source>

## File input
## read apache logs with tag=apache.access
<source>
  @type tail
  format apache
  path /var/log/apache/access.log
  tag apache.access
</source>

## Mutating event filter
## Add hostname and tag fields to apache.access tag events
<filter apache.access>
  @type record_transformer
  <record>
    hostname ${hostname}
    tag ${tag}
  </record>
</filter>

## Selecting event filter
## Remove unnecessary events from apache prefixed tag events
<filter apache.**>
  @type grep
  include1 method GET # pass only GET in 'method' field
  exclude1 message debug # remove debug event
</filter>

# Listen HTTP for monitoring
# http://localhost:24220/api/plugins
# http://localhost:24220/api/plugins?type=TYPE
# http://localhost:24220/api/plugins?tag=MYTAG
<source>
  @type monitor_agent
  @id monitor_agent_input

  port 24220
</source>

# Listen DRb for debug
<source>
  @type debug_agent
  @id debug_agent_input

  bind 127.0.0.1
  port 24230
</source>

## match tag=apache.access and write to file
<match apache.access>
  @type file
  path /var/log/fluent/access
</match>

## match tag=debug.** and dump to console
<match debug.**>
  @type stdout
  @id stdout_output
</match>

# match tag=system.** and forward to another fluent server
<match system.**>
  @type forward
  @id forward_output

  <server>
    host 192.168.0.11
  </server>
  <secondary>
    <server>
      host 192.168.0.12
    </server>
  </secondary>
</match>

## match tag=myapp.** and forward and write to file
#<match myapp.**>
#  @type copy
#  <store>
#    @type forward
#    buffer_type file
#    buffer_path /var/log/fluent/myapp-forward
#    retry_limit 50
#    flush_interval 10s
#    <server>
#      host 192.168.0.13
#    </server>
#  </store>
#  <store>
#    @type file
#    path /var/log/fluent/myapp
#  </store>
#</match>

## match fluent's internal events
#<match fluent.**>
#  @type null
#</match>

## match not matched logs and write to file
#<match **>
#  @type file
#  path /var/log/fluent/else
#  compress gz
#</match>

## Label: For handling complex event routing
#<label @STAGING>
#  <match system.**>
#    @type forward
#    @id staging_forward_output
#    <server>
#      host 192.168.0.101
#    </server>
#  </match>
#</label>
```

Any help would be greatly appreciated.

Kieran

**Comment by repeatedly** [comment]
We show CONTRIBUTING guideline.
Follow it: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem

BTW...

> No such file or directory @ rb_sysopen - fluent.conf (Errno::ENOENT)

Error message shows the cause. You don't have a fluent.conf in working directory.
