### ISSUE TITLE
Cannot get new connection from pool

### ISSUE THREAD

**Issue by zerthimon** [fluent/fluentd#1435]
/fluentd # fluentd --version
fluentd 0.12.29

Running in docker container:
```
FROM fluent/fluentd:latest-onbuild
MAINTAINER mofo@mofo.com

ENV WORKDIR /fluentd
WORKDIR $WORKDIR

USER root
RUN chown -R root:root $WORKDIR \
    && rm -rf /home/fluent \
    && gem install \
        fluent-plugin-elasticsearch \
    && gem sources -c

EXPOSE 24224

VOLUME $WORKDIR/buffer $WORKDIR/log

CMD exec fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
```

Having some strange error and logs are not being written to elastic (buffer file grows):
```
2017-01-01 09:34:01 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type forward
    @id input1
    @label @mainstream
    port 24224
    bind 0.0.0.0
  </source>
  <filter **>
    @type stdout
  </filter>
  <label @mainstream>
    <filter docker.**>
      @type record_transformer
      <record>
        docker_host: somehost
      </record>
    </filter>
    <match docker.**>
      @type elasticsearch
      @id output_docker1
      logstash_format true
      host 10.10.11.1
      port 9200
      flush_interval 5s
      index_name fluentd
      type_name fluentd
      include_tag_key true
      buffer_type file
      buffer_path /fluentd/buffer/elasticsearch.*.buffer
    </match>
    <match **>
      @type file
      @id output1
      path /fluentd/log/data.*.log
      flush_interval 5s
      append true
      time_slice_format %Y%m%d
      time_slice_wait 10m
      time_format %Y%m%dT%H%M%S%z
      buffer_path /fluentd/log/data.*.log
    </match>
  </label>
</ROOT>
2017-01-01 09:34:01 +0000 [info]: listening fluent socket on 0.0.0.0:24224
2017-01-01 09:34:07 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"10.10.11.1", :port=>9200, :scheme=>"http"}
2017-01-01 09:34:07 +0000 fluent.info: {"message":"Connection opened to Elasticsearch cluster => {:host=>\"138.201.19.49\", :port=>9200, :scheme=>\"http\"}"}
2017-01-01 09:34:07 +0000 [warn]: no patterns matched tag="fluent.info"
2017-01-23 14:40:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-01-23 14:40:05 +0000 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="output_docker1"
  2017-01-23 14:40:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:249:in `perform_request'
  2017-01-23 14:40:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2017-01-23 14:40:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
  2017-01-23 14:40:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/bulk.rb:90:in `bulk'
  2017-01-23 14:40:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.8.0/lib/fluent/plugin/out_elasticsearch.rb:338:in `send_bulk'
  2017-01-23 14:40:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.8.0/lib/fluent/plugin/out_elasticsearch.rb:322:in `write'
  2017-01-23 14:40:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:354:in `write_chunk'
  2017-01-23 14:40:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:333:in `pop'
  2017-01-23 14:40:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/output.rb:338:in `try_flush'
  2017-01-23 14:40:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/output.rb:149:in `run'
2017-01-23 14:40:04 +0000 fluent.warn: {"next_retry":"2017-01-23 14:40:05 +0000","error_class":"Elasticsearch::Transport::Transport::Error","error":"Cannot get new connection from pool.","plugin_id":"output_docker1","message":"temporarily failed to flush the buffer. next_retry=2017-01-23 14:40:05 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"output_docker1\""}
2017-01-23 14:40:04 +0000 [warn]: no patterns matched tag="fluent.warn"
2017-01-23 14:40:05 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-01-23 14:40:07 +0000 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="output_docker1"
  2017-01-23 14:40:05 +0000 [warn]: suppressed same stacktrace
2017-01-23 14:40:05 +0000 fluent.warn: {"next_retry":"2017-01-23 14:40:07 +0000","error_class":"Elasticsearch::Transport::Transport::Error","error":"Cannot get new connection from pool.","plugin_id":"output_docker1","message":"temporarily failed to flush the buffer. next_retry=2017-01-23 14:40:07 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"output_docker1\""}
2017-01-23 14:40:07 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-01-23 14:40:11 +0000 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="output_docker1"
  2017-01-23 14:40:07 +0000 [warn]: suppressed same stacktrace
2017-01-23 14:40:07 +0000 fluent.warn: {"next_retry":"2017-01-23 14:40:11 +0000","error_class":"Elasticsearch::Transport::Transport::Error","error":"Cannot get new connection from pool.","plugin_id":"output_docker1","message":"temporarily failed to flush the buffer. next_retry=2017-01-23 14:40:11 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"output_docker1\""}
2017-01-23 14:40:07 +0000 [warn]: no patterns matched tag="fluent.warn"
2017-01-23 14:40:11 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-01-23 14:40:19 +0000 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="output_docker1"
  2017-01-23 14:40:11 +0000 [warn]: suppressed same stacktrace
2017-01-23 14:40:11 +0000 fluent.warn: {"next_retry":"2017-01-23 14:40:19 +0000","error_class":"Elasticsearch::Transport::Transport::Error","error":"Cannot get new connection from pool.","plugin_id":"output_docker1","message":"temporarily failed to flush the buffer. next_retry=2017-01-23 14:40:19 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"output_docker1\""}
2017-01-23 14:40:19 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-01-23 14:40:35 +0000 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="output_docker1"
  2017-01-23 14:40:19 +0000 [warn]: suppressed same stacktrace
2017-01-23 14:40:19 +0000 fluent.warn: {"next_retry":"2017-01-23 14:40:35 +0000","error_class":"Elasticsearch::Transport::Transport::Error","error":"Cannot get new connection from pool.","plugin_id":"output_docker1","message":"temporarily failed to flush the buffer. next_retry=2017-01-23 14:40:35 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"output_docker1\""}
2017-01-23 14:40:35 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-01-23 14:41:06 +0000 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="output_docker1"
```
What may be the cause ?

**Comment by repeatedly** [comment]
Please follow contributing guide: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem

I'm not sure the cause but refer this case: https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/issues/15#issuecomment-254793259
