### ISSUE TITLE
Fluentd v0.12.x displays warnings with Ruby2.4.0

### ISSUE THREAD

**Issue by okkez** [fluent/fluentd#1486]
Fluentd v0.12.x displays following warnings  with Ruby 2.4.0:

```
fluentd/lib/fluent/log.rb:185:in `warn': Fluent::PluginLogger#event at lib/ruby/2.4.0/forwardable.rb:156 forwarding to private method Fluent::Log#event
fluentd/lib/fluent/log.rb:186:in `warn': Fluent::PluginLogger#caller_line at lib/ruby/2.4.0/forwardable.rb:156 forwarding to private method Fluent::Log#caller_line
```

We cannot suppress these warnings in 3rd party plugin's test using following Rakefile.
I think this is very noisy for plugin authors.

```ruby
require "rake/testtask"
Rake::TestTask.new(:test) do |test|
  test.libs << 'lib' << 'test'
  test.pattern = 'test/**/test_*.rb'
  test.verbose = false
  test.warning = false
end
```

This problem has been fixed for v0.14.x.
See also https://github.com/fluent/fluentd/commit/68a4fa4ebe66fa3513519e567deaea5bb7496f5c

**Comment by repeatedly** [comment]
v0.12 is now maintenance mode.
