### ISSUE TITLE
fluentd not take multiple line regex 

### ISSUE THREAD

**Issue by Git-Rajkumar** [fluent/fluentd#1511]
I have some **java Servlet logs**, this log print one log information to multiple line.i try to match, multiple line but its not working for me.

**my log:**

            Jan 30, 2016 8:00:05 AM org.apache.catalina.core.ApplicationContext log
		INFO: SessionListener: sessionCreated('F2DD29C2963A7')
		Jan 30, 2016 8:00:05 AM org.apache.catalina.core.StandardWrapperValve invoke
		SEVERE: Servlet.service() for servlet [jsp] in context with path [/examples] threw exception [javax.servlet.ServletException: javax.servlet.jsp.JspTagException: Invalid JSP file /jsp/num/numguess.jsp] with root cause
		javax.servlet.jsp.JspTagException: Invalid JSP file /jsp/num/numguess.jsp
			at examples.ShowSource.doEndTag(ShowSource.java:46)
			at org.apache.jsp.jsp.source_jsp._jspService(source_jsp.java:81)
			at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
			at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
			at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
			at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
			at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
			at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
			at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
			at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
			at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
			at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
			at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
			at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
			at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
			at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
			at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
			at java.lang.Thread.run(Thread.java:745)

		Jan 30, 2016 8:00:06 AM org.apache.catalina.core.ApplicationContext log
		INFO: SessionListener: sessionCreated('2AFE81A4D78632A48446F0AD7B45EC52')

the above log format , print single log information to multiple lines.

**pattern not match:**

       (?<time>\w+\s+\d[0-9].*\d[0-9]\s\w+)(?<code>.*[\ ])(?<methodid>.*)(?<method>\n[^ :]*)[^ ](?<message>.*)
**I tested  this regex in http://rubular.com/ its matched, but fluentd  get every single line and throw pattern not match:**

Suggest me How to fix this issue.

**Comment by edsiper** [comment]
please share your Fluentd configuration.

Note: for Multiline parsing is expected that you have at least two regular expressions, one for the firstline and another for the other content:

http://docs.fluentd.org/v0.12/articles/in_tail

**Comment by Git-Rajkumar** [comment]
**td-agent.conf:**

		<source>
		  type tail
		  format smps_localhost_log
		  tag apache.access
		  path /var/log/sm_log/localhost.2016-01-30.log-defravlufedapp1
		</source>

		<match apache.access>
		  type stdout
		</match>
**My Regex:**

   'smps_localhost_log' => Proc.new { RegexpParser.new(/^(?<time>\w+\s+\d[0-9].*\d[0-9]\s\w+)(?<code>.*[\ ])(?<methodid>.*)(?<method>\n[^ :]*)[^ ](?<message>.*)$/) }

this Regex I give **/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.52/lib/fluent/parser.rb** , so i give only variable name in source format option in td-agent.conf

Suggest me, what i miss in this configuration.

**Comment by edsiper** [comment]
I suggest you try the multiline configuration from in_tail without touch Fluentd source code for the moment. Once your regular expressions works properly, then you could move them to a place that are more easy to handle for you.

As described earlier, please refer to the in_tail documentation where multiline examples are given.

**Comment by Git-Rajkumar** [comment]
@edsiper  

I flow multiline configuration from in_tail  http://docs.fluentd.org/v0.12/articles/in_tail#multilineflushinterval, but not working right for me 

**Mylog:**

Jan 30, 2016 8:00:05 AM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: sessionCreated('D5C4C9B79498812EED3B3470E575DF1E')

**myfirstline syntax:**
http://rubular.com/r/BqLa4F4uzg
**next linesyntax:**
 http://rubular.com/r/RQ6buW0YvU

**td-agent Configuration:**

		<source>
		  type tail
		  format multiline
		   format_firstline /^(?<time>(.*))(?<code> \\S*) (?<method_level>\\w+)/
		   format1  /(?<method>\\w+)[^ ](?<message>(.*))/
		  tag apache.access
		  path /var/log/sm_log/localhost.2016-01-30.log-defravlufedapp1
		</source>

		<match apache.access>
		  type stdout
		</match>

This Configuration getting result, but its not right:

Output:

        2017-03-21 20:26:25 +0530 apache.access: {"method":"Ja","message":" 30, 2016 8:00:06 AM org.apache.catalina.core.ApplicationContext log"}
        2017-03-21 20:26:25 +0530 apache.access: {"method":"INFO","message":" SessionListener: sessionCreated('2AFE81A4D78632A48446F0AD7B45EC52')"}

the Above error , its not I expected output. i need to get  these multiline  output coming for single output. like http://docs.fluentd.org/v0.12/articles/in_tail#multilineflushinterval in multiline part example
 and I match results in http://rubular.com/r/BqLa4F4uzg and  http://rubular.com/r/RQ6buW0YvU

Suggest me I miss in this Configuration.

**Comment by Git-Rajkumar** [comment]
I have miss configure the  regex format, now works fine

Latest Configuration File:

     <source>
	  type tail
	  format multiline
	  format_firstline /\\w{3}\\s\\d{2}.*\\s\\d{4}\\s\\d{1,2}:\\d{1,2}:\\d{1,2}\\s\\w+/
	  format1 /^(?<time>\\w{3}\\s\\d{2}.*\\s\\d{4}\\s\\d{1,2}:\\d{1,2}:\\d{1,2}\\s\\w+)(?<code> \\S*)(?<method_level> \\w+)(?<method>.\\w+)[^ ](?<message>(.*))/
	  tag apache.access
	  path /var/log/sm_log/localhost.2016-01-30.log-defravlufedapp1
	</source>

output log:

2016-01-30 08:30:13 +0530 apache.access: {"code":" org.apache.catalina.core.ApplicationContext","method_level":" log","method":"**\n**INFO","message":" SessionListener: sessionDestroyed('B098DFA3AA81A40118A9729AD4C39E0C')"

But,  still not getting below thinks 
   **1. time information from log
   2. while get next line of data add \n.how to remove this.** 

Suggest Me how to this

**Comment by okkez** [comment]
I've confirmed with v0.12.43.

```
<source>
  @type tail
  format multiline
  format_firstline /\w{3}\s\d{2}.*\s\d{4}\s\d{1,2}:\d{1,2}:\d{1,2}\s\w+/
  format1 /^(?<time>\w{3}\s\d{2}.*\s\d{4}\s\d{1,2}:\d{1,2}:\d{1,2}\s\w+)(?<code> \S*)(?<method_level> \w+)\n(?<method>.\w+)[^ ](?<message>(.*))/
  tag apache.access
  path local/1511.log
  read_from_head true
</source>

<match>
  @type stdout
</match>
```

```
2016-01-30 08:00:05 +0900 apache.access: {"code":" org.apache.catalina.core.ApplicationContext","method_level":" log","method":"INFO","message":" SessionListener: sessionCreated('D5C4C9B79498812EED3B3470E575DF1E')"}
```

> 1. time information from log

time information has already been in the output.
If you want to keep time value in JSON, use `keep_time_key true`.

> 2. while get next line of data add \n.how to remove this.

Check the above configuration.
