### ISSUE TITLE
Fluentd reporting no match for any log message, but Fluentular shows expected output

### ISSUE THREAD

**Issue by estroz** [fluent/fluentd#1526]
Fluentd version:
```
[root@host /]# fluentd --version
fluentd 0.14.13
```

OS information/environment:
```
[root@host /]# cat /etc/*-release
CentOS Linux release 7.3.1611 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.3.1611 (Core)
CentOS Linux release 7.3.1611 (Core)
```

Configuration file:
```
<source>
  @type tail
  path /var/log/app/app.log*
  pos_file /var/log/fluentd/app.log.pos
  tag tag.*
  format multiline
  format_firstline /^\[(?<level>.*)\] (?<time>[^ ]* [^ ]*) (?<logtext>.*)$/
  format1 /^(?<stacktrace>[^\:]*\: .*)$/
  format2 /^\s*(?<stacktrace>at .*)$/
  time_format %Y-%m-%d %H:%M:%S,%L
  read_from_head true
</source>

<match **>
  @type forward
  flush_interval 5s
  <server>
    name logger
    host 172.17.0.2
    port 24224
    weight 60
  </server>
</match>
```

Fluentd cannot parse my logs with custom `multiline` formats, but Fluentular shows my logs being parsed [correctly](http://fluentular.herokuapp.com/parse?regexp=%2F%5E%5C%5B%28%3F%3Clevel%3E.*%29%5C%5D+%28%3F%3Ctime%3E%5B%5E+%5D*+%5B%5E+%5D*%29+%28%3F%3Clogtext%3E.*%29%24%2F&input=%5B+INFO%5D+2017-04-03+22%3A33%3A49%2C661+com.org.app.AppContextListener+-+Initializing+web+application.&time_format=%25Y-%25m-%25d+%25H%3A%25M%3A%25S%2C%25L). My multiline parsing for stack traces appears to be working correctly as the whole stack trace is appended into one message.

Logs:
```
[ INFO] 2017-04-03 23:31:43,413 com.org.app.AppContextListener - Initializing web application.
[ INFO] 2017-04-03 23:31:43,527 com.org.app.util.CassandraManager - Connecting to Cassandra nodes 127.0.0.1 on port 9042
[ INFO] 2017-04-03 23:31:43,824 com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
[ERROR] 2017-04-03 23:31:44,236 com.org.app.AppContextListener - Unable to initialize web application.
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1] Cannot connect))
        at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233)
        at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1424)
        at com.datastax.driver.core.Cluster.init(Cluster.java:163)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:334)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:309)
        at com.datastax.driver.core.Cluster.connect(Cluster.java:251)
        at com.org.app.util.CassandraManager.createSession(CassandraManager.java:87)
        at com.org.app.util.CassandraManager.getSession(CassandraManager.java:97)
        at com.org.app.AppContextListener.contextInitialized(AppContextListener.java:126)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4717)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5179)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Sample of fluentd logs:
```
2017-04-03 23:13:14 +0000 [info]: #0 following tail of /var/log/app/app.log
2017-04-03 23:13:14 +0000 [warn]: #0 pattern not match: "[ INFO] 2017-04-03 23:12:27,075 com.org.app.AppContextListener - Initializing web application."
2017-04-03 23:13:14 +0000 [warn]: #0 pattern not match: "[ INFO] 2017-04-03 23:12:27,197 com.org.app.util.CassandraManager - Connecting to Cassandra nodes 127.0.0.1 on port 9042"
2017-04-03 23:13:14 +0000 [warn]: #0 pattern not match: "[ INFO] 2017-04-03 23:12:27,505 com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO."
2017-04-03 23:13:14 +0000 [warn]: #0 pattern not match: "[ERROR] 2017-04-03 23:12:28,009 com.org.app.AppContextListener - Unable to initialize web application.\ncom.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1] Cannot connect))\n\tat com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233)\n\tat com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)\n\tat com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1424)\n\tat com.datastax.driver.core.Cluster.init(Cluster.java:163)\n\tat com.datastax.driver.core.Cluster.connectAsync(Cluster.java:334)\n\tat com.datastax.driver.core.Cluster.connectAsync(Cluster.java:309)\n\tat com.datastax.driver.core.Cluster.connect(Cluster.java:251)\n\tat com.org.app.util.CassandraManager.createSession(CassandraManager.java:87)\n\tat com.org.app.util.CassandraManager.getSession(CassandraManager.java:97)\n\tat com.org.app.AppContextListener.contextInitialized(AppContextListener.java:126)\n\tat org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4717)\n\tat org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5179)\n\tat org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)\n\tat org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)\n\tat org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)\n\tat org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)\n\tat org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)\n\tat org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)"
```

**Comment by estroz** [comment]
Fixed. This was a simple case of not using the `multiline` format correctly. Closing.
