### ISSUE TITLE
in_http.rb : if X-Forwarded-For is set, error because undefined method split

### ISSUE THREAD

**Issue by huembi** [fluent/fluentd#1531]
I'm using the edge version (0.14.14) of the [fluent/fluentd](https://hub.docker.com/r/fluent/fluentd/) docker image. The docker container runs inside a Openshift environment which is the RedHat enterprise solution based on Kubernetes.

When I do a request to this fluentd instance, I'm getting an error "undefined method split". By diging into the code, I could figure out, that my environment sets the X-Forwarded-For header and the in_http plugin tries to split the values but fails. See [in_http.rb](https://github.com/fluent/fluentd/blob/d7182c5cfeac99b3b0c6ae7f38ff214a077efc59/lib/fluent/plugin/in_http.rb#L322).

Is the split method wrong on this position? 
As a workaround, can I get over this issue with a smart filter (e.g. removing the X-Forwarded-For header)?

**My configuration:**
```
<source>
  @type http
  port 5140
  bind 0.0.0.0
  tag system
</source>
<match **>
  @type stdout
</match>
```

**Request to my fluentd:**
     curl -v  -X POST -d '"action":"do-some-action"'  http://application.host.com

**Extract of my logfile**
> 2017-04-07 13:40:12.730170309 +0000 fluent.info: {"worker":0,"message":"fluentd worker is now running worker=0"}
2017-04-07 13:40:29 +0000 [warn]: #0 unexpected error error="undefined method `split' for [\"10.191.187.246\", \"10.191.12.238\"]:Array"
  2017-04-07 13:40:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/plugin/in_http.rb:322:in `block in on_headers_complete'
  2017-04-07 13:40:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/plugin/in_http.rb:304:in `each_pair'
  2017-04-07 13:40:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/plugin/in_http.rb:304:in `on_headers_complete'
  2017-04-07 13:40:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/plugin/in_http.rb:282:in `<<'
  2017-04-07 13:40:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/plugin/in_http.rb:282:in `on_read'
  2017-04-07 13:40:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.6/lib/cool.io/io.rb:123:in `on_readable'
  2017-04-07 13:40:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.6/lib/cool.io/io.rb:186:in `on_readable'
  2017-04-07 13:40:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run_once'
  2017-04-07 13:40:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run'
  2017-04-07 13:40:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
  2017-04-07 13:40:29 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2017-04-07 13:40:29 +0000 [warn]: #0 unexpected error error="undefined method `split' for [\"10.191.187.246\", \"10.191.15.246\"]:Array"
  2017-04-07 13:40:29 +0000 [warn]: #0 suppressed same stacktrace

**Comment by repeatedly** [comment]
I reproduced the problem.
If you send multiple `X-Forwarded-For` to in_http, this problem happens.
I will fix it.

**Comment by repeatedly** [comment]
Patch is here: https://github.com/fluent/fluentd/pull/1535
Could you test it on your environment?

https://github.com/fluent/fluentd/wiki/Testing-fluentd-patch

**Comment by huembi** [comment]
Thx for fixing this issue that fast.
Is this fix already in the docker image on https://hub.docker.com/r/fluent/fluentd/?

Did not find the time the last couple of days to test it. Will do it next week and let you know the result.

**Comment by repeatedly** [comment]
v0.12.35 now published: https://hub.docker.com/r/fluent/fluentd/tags/

**Comment by huembi** [comment]
Works like a charm, thx a lot Masahiro
