### ISSUE TITLE
fluent-cat segmentation fault at 0x007f8eed93fc50

### ISSUE THREAD

**Issue by slang800** [fluent/fluentd#1593]
I got this error while loading a few million log entries into fluentd using `cat input | fluent-cat --none docker.couchdb` from within the docker container. I've loaded almost 200 million logs using this method before getting this error, so it's rather surprising. I'll try to find a good way to reproduce it, if it's not totally random.

```
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/msgpack_factory.rb:44: [BUG] Segmentation fault at 0x007f8eed93fc50
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux-musl]

-- Control frame information -----------------------------------------------
c:0014 p:---- s:0074 e:000073 CFUNC  :register_type
c:0013 p:0045 s:0069 e:000068 METHOD /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/msgpack_factory.rb:44
c:0012 p:0008 s:0065 e:000064 METHOD /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/msgpack_factory.rb:49
c:0011 p:0041 s:0061 e:000060 METHOD /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/command/cat.rb:213
c:0010 p:0012 s:0055 e:000054 BLOCK  /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/command/cat.rb:158
c:0009 p:0015 s:0053 e:000052 METHOD /usr/lib/ruby/2.3.0/monitor.rb:214
c:0008 p:0096 s:0050 e:000049 METHOD /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/command/cat.rb:157
c:0007 p:0723 s:0044 E:001f88 TOP    /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/command/cat.rb:319 [FINISH]
c:0006 p:---- s:0027 e:000026 CFUNC  :require
c:0005 p:0124 s:0023 e:000022 METHOD /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
c:0004 p:0058 s:0013 e:000012 TOP    /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/bin/fluent-cat:5 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :load
c:0002 p:0136 s:0006 E:000630 EVAL   /usr/bin/fluent-cat:22 [FINISH]
c:0001 p:0000 s:0002 E:0018a0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/bin/fluent-cat:22:in `<main>'
/usr/bin/fluent-cat:22:in `load'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/bin/fluent-cat:5:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/command/cat.rb:319:in `<top (required)>'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/command/cat.rb:157:in `write'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/command/cat.rb:158:in `block in write'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/command/cat.rb:213:in `write_impl'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/msgpack_factory.rb:49:in `packer'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/msgpack_factory.rb:44:in `factory'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/msgpack_factory.rb:44:in `register_type'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f8eee6c33a7 RBP: 0x00007fffd8268a30 RSP: 0x00007fffd8268a18
 RAX: 0x000000000000000c RBX: 0x000055f55730ffa0 RCX: 0x0000000000000020
 RDX: 0x000000000000000c RDI: 0x00007f8eed93fc40 RSI: 0x0000000000bff10c
  R8: 0x0000000000000000  R9: 0x000055f555593b60 R10: 0x000055f55730ff50
 R11: 0x000055f55730ff00 R12: 0x000055f556bbc280 R13: 0x000055f55730ff50
 R14: 0x0000000000000000 R15: 0x0000000000bff10c EFL: 0x0000000000010202

-- Other runtime information -----------------------------------------------

* Loaded script: /usr/bin/fluent-cat

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /usr/lib/ruby/2.3.0/x86_64-linux-musl/enc/encdb.so
    5 /usr/lib/ruby/2.3.0/x86_64-linux-musl/enc/trans/transdb.so
    6 /usr/lib/ruby/2.3.0/unicode_normalize.rb
    7 /usr/lib/ruby/2.3.0/x86_64-linux-musl/rbconfig.rb
    8 /usr/lib/ruby/2.3.0/rubygems/compatibility.rb
    9 /usr/lib/ruby/2.3.0/rubygems/defaults.rb
   10 /usr/lib/ruby/2.3.0/rubygems/deprecate.rb
   11 /usr/lib/ruby/2.3.0/rubygems/errors.rb
   12 /usr/lib/ruby/2.3.0/rubygems/version.rb
   13 /usr/lib/ruby/2.3.0/rubygems/requirement.rb
   14 /usr/lib/ruby/2.3.0/rubygems/platform.rb
   15 /usr/lib/ruby/2.3.0/rubygems/basic_specification.rb
   16 /usr/lib/ruby/2.3.0/rubygems/stub_specification.rb
   17 /usr/lib/ruby/2.3.0/rubygems/util/list.rb
   18 /usr/lib/ruby/2.3.0/x86_64-linux-musl/stringio.so
   19 /usr/lib/ruby/2.3.0/rubygems/specification.rb
   20 /usr/lib/ruby/2.3.0/rubygems/exceptions.rb
   21 /usr/lib/ruby/2.3.0/rubygems/dependency.rb
   22 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb
   23 /usr/lib/ruby/2.3.0/monitor.rb
   24 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb
   25 /usr/lib/ruby/2.3.0/rubygems.rb
   26 /usr/lib/ruby/2.3.0/rubygems/path_support.rb
   27 /usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/version.rb
   28 /usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb
   29 /usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/levenshtein.rb
   30 /usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/jaro_winkler.rb
   31 /usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkable.rb
   32 /usr/lib/ruby/2.3.0/delegate.rb
   33 /usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   34 /usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   35 /usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   36 /usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   37 /usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/null_checker.rb
   38 /usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/formatter.rb
   39 /usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean.rb
   40 /usr/lib/ruby/2.3.0/optparse.rb
   41 /usr/lib/ruby/gems/2.3.0/gems/serverengine-2.0.5/lib/serverengine/utils.rb
   42 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/env.rb
   43 /usr/lib/ruby/2.3.0/x86_64-linux-musl/date_core.so
   44 /usr/lib/ruby/2.3.0/date.rb
   45 /usr/lib/ruby/2.3.0/time.rb
   46 /usr/lib/ruby/gems/2.3.0/gems/msgpack-1.1.0/lib/msgpack/version.rb
   47 /usr/lib/ruby/gems/2.3.0/gems/msgpack-1.1.0/lib/msgpack/msgpack.so
   48 /usr/lib/ruby/gems/2.3.0/gems/msgpack-1.1.0/lib/msgpack/packer.rb
   49 /usr/lib/ruby/gems/2.3.0/gems/msgpack-1.1.0/lib/msgpack/unpacker.rb
   50 /usr/lib/ruby/gems/2.3.0/gems/msgpack-1.1.0/lib/msgpack/factory.rb
   51 /usr/lib/ruby/gems/2.3.0/gems/msgpack-1.1.0/lib/msgpack/symbol.rb
   52 /usr/lib/ruby/gems/2.3.0/gems/msgpack-1.1.0/lib/msgpack.rb
   53 /usr/lib/ruby/gems/2.3.0/gems/strptime-0.1.9/lib/strptime/version.rb
   54 /usr/lib/ruby/gems/2.3.0/gems/strptime-0.1.9/lib/strptime/strptime.so
   55 /usr/lib/ruby/gems/2.3.0/gems/strptime-0.1.9/lib/strptime.rb
   56 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/ruby_core_support.rb
   57 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/offset_rationals.rb
   58 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/time_or_datetime.rb
   59 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone_definition.rb
   60 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone_offset.rb
   61 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone_transition.rb
   62 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone_transition_definition.rb
   63 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone_index_definition.rb
   64 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone_info.rb
   65 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/data_timezone_info.rb
   66 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/linked_timezone_info.rb
   67 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/transition_data_timezone_info.rb
   68 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/zoneinfo_timezone_info.rb
   69 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/data_source.rb
   70 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/ruby_data_source.rb
   71 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/zoneinfo_data_source.rb
   72 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone_period.rb
   73 /usr/lib/ruby/2.3.0/set.rb
   74 /usr/lib/ruby/gems/2.3.0/gems/thread_safe-0.3.6/lib/thread_safe/version.rb
   75 /usr/lib/ruby/gems/2.3.0/gems/thread_safe-0.3.6/lib/thread_safe/synchronized_delegator.rb
   76 /usr/lib/ruby/gems/2.3.0/gems/thread_safe-0.3.6/lib/thread_safe.rb
   77 /usr/lib/ruby/gems/2.3.0/gems/thread_safe-0.3.6/lib/thread_safe/non_concurrent_cache_backend.rb
   78 /usr/lib/ruby/gems/2.3.0/gems/thread_safe-0.3.6/lib/thread_safe/mri_cache_backend.rb
   79 /usr/lib/ruby/gems/2.3.0/gems/thread_safe-0.3.6/lib/thread_safe/cache.rb
   80 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone.rb
   81 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/info_timezone.rb
   82 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/data_timezone.rb
   83 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/linked_timezone.rb
   84 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone_proxy.rb
   85 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/country_index_definition.rb
   86 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/country_info.rb
   87 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/ruby_country_info.rb
   88 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/zoneinfo_country_info.rb
   89 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/country.rb
   90 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/country_timezone.rb
   91 /usr/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo.rb
   92 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/config/error.rb
   93 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/timezone.rb
   94 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/config/configure_proxy.rb
   95 /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/version.rb
   96 /usr/lib/ruby/2.3.0/ostruct.rb
   97 /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/generic_object.rb
   98 /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/common.rb
   99 /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/ext/parser.so
  100 /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/ext/generator.so
  101 /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/ext.rb
  102 /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json.rb
  103 /usr/lib/ruby/2.3.0/x86_64-linux-musl/strscan.so
  104 /usr/lib/ruby/2.3.0/uri/rfc2396_parser.rb
  105 /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb
  106 /usr/lib/ruby/2.3.0/uri/common.rb
  107 /usr/lib/ruby/2.3.0/uri/generic.rb
  108 /usr/lib/ruby/2.3.0/uri/ftp.rb
  109 /usr/lib/ruby/2.3.0/uri/http.rb
  110 /usr/lib/ruby/2.3.0/uri/https.rb
  111 /usr/lib/ruby/2.3.0/uri/ldap.rb
  112 /usr/lib/ruby/2.3.0/uri/ldaps.rb
  113 /usr/lib/ruby/2.3.0/uri/mailto.rb
  114 /usr/lib/ruby/2.3.0/uri.rb
  115 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/config/basic_parser.rb
  116 /usr/lib/ruby/gems/2.3.0/gems/yajl-ruby-1.3.0/lib/yajl/yajl.so
  117 /usr/lib/ruby/gems/2.3.0/gems/yajl-ruby-1.3.0/lib/yajl.rb
  118 /usr/lib/ruby/2.3.0/e2mmap.rb
  119 /usr/lib/ruby/2.3.0/irb/output-method.rb
  120 /usr/lib/ruby/2.3.0/irb/notifier.rb
  121 /usr/lib/ruby/2.3.0/irb/slex.rb
  122 /usr/lib/ruby/2.3.0/irb/ruby-token.rb
  123 /usr/lib/ruby/2.3.0/irb/ruby-lex.rb
  124 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/config/literal_parser.rb
  125 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/config/element.rb
  126 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/config/v1_parser.rb
  127 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/config/section.rb
  128 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/registry.rb
  129 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/plugin.rb
  130 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/config/types.rb
  131 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/configurable.rb
  132 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/time.rb
  133 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.17/lib/fluent/msgpack_factory.rb
  134 /usr/lib/ruby/2.3.0/x86_64-linux-musl/socket.so
  135 /usr/lib/ruby/2.3.0/x86_64-linux-musl/io/wait.so
  136 /usr/lib/ruby/2.3.0/socket.rb

* Process memory map:

55f555392000-55f555393000 r-xp 00000000 41:59 6256732                    /usr/bin/ruby
55f555592000-55f555593000 r--p 00000000 41:59 6256732                    /usr/bin/ruby
55f555593000-55f555594000 rw-p 00001000 41:59 6256732                    /usr/bin/ruby
55f5569e5000-55f557b12000 rw-p 00000000 00:00 0                          [heap]
7f8eec8e3000-7f8eec8e4000 ---p 00000000 00:00 0 
7f8eec8e4000-7f8eecae6000 rw-p 00000000 00:00 0 
7f8eecae6000-7f8eecce7000 r-xp 00000000 41:59 6257430                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/io/wait.so
7f8eecce7000-7f8eecce8000 r--p 00001000 41:59 6257430                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/io/wait.so
7f8eecce8000-7f8eecce9000 rw-p 00002000 41:59 6257430                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/io/wait.so
7f8eecce9000-7f8eecf0f000 r-xp 00000000 41:59 6257448                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/socket.so
7f8eecf0f000-7f8eecf10000 r--p 00026000 41:59 6257448                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/socket.so
7f8eecf10000-7f8eecf11000 rw-p 00027000 41:59 6257448                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/socket.so
7f8eecf11000-7f8eed119000 r-xp 00000000 41:59 6259863                    /usr/lib/ruby/gems/2.3.0/gems/yajl-ruby-1.3.0/lib/yajl/yajl.so
7f8eed119000-7f8eed11a000 r--p 00008000 41:59 6259863                    /usr/lib/ruby/gems/2.3.0/gems/yajl-ruby-1.3.0/lib/yajl/yajl.so
7f8eed11a000-7f8eed11b000 rw-p 00009000 41:59 6259863                    /usr/lib/ruby/gems/2.3.0/gems/yajl-ruby-1.3.0/lib/yajl/yajl.so
7f8eed11b000-7f8eed31f000 r-xp 00000000 41:59 6257450                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/strscan.so
7f8eed31f000-7f8eed320000 r--p 00004000 41:59 6257450                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/strscan.so
7f8eed320000-7f8eed321000 rw-p 00005000 41:59 6257450                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/strscan.so
7f8eed321000-7f8eed527000 r-xp 00000000 41:59 6258312                    /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/ext/generator.so
7f8eed527000-7f8eed528000 r--p 00006000 41:59 6258312                    /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/ext/generator.so
7f8eed528000-7f8eed529000 rw-p 00007000 41:59 6258312                    /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/ext/generator.so
7f8eed529000-7f8eed72d000 r-xp 00000000 41:59 6258313                    /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/ext/parser.so
7f8eed72d000-7f8eed72e000 r--p 00004000 41:59 6258313                    /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/ext/parser.so
7f8eed72e000-7f8eed72f000 rw-p 00005000 41:59 6258313                    /usr/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/ext/parser.so
7f8eed72f000-7f8eed932000 r-xp 00000000 41:59 6258808                    /usr/lib/ruby/gems/2.3.0/gems/strptime-0.1.9/lib/strptime/strptime.so
7f8eed932000-7f8eed933000 r--p 00003000 41:59 6258808                    /usr/lib/ruby/gems/2.3.0/gems/strptime-0.1.9/lib/strptime/strptime.so
7f8eed933000-7f8eed934000 rw-p 00004000 41:59 6258808                    /usr/lib/ruby/gems/2.3.0/gems/strptime-0.1.9/lib/strptime/strptime.so
7f8eed934000-7f8eedb49000 r-xp 00000000 41:59 6258467                    /usr/lib/ruby/gems/2.3.0/gems/msgpack-1.1.0/lib/msgpack/msgpack.so
7f8eedb49000-7f8eedb4a000 r--p 00015000 41:59 6258467                    /usr/lib/ruby/gems/2.3.0/gems/msgpack-1.1.0/lib/msgpack/msgpack.so
7f8eedb4a000-7f8eedb4b000 rw-p 00016000 41:59 6258467                    /usr/lib/ruby/gems/2.3.0/gems/msgpack-1.1.0/lib/msgpack/msgpack.so
7f8eedb4b000-7f8eedd6e000 r-xp 00000000 41:59 6257356                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/date_core.so
7f8eedd6e000-7f8eedd70000 r--p 00023000 41:59 6257356                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/date_core.so
7f8eedd70000-7f8eedd71000 rw-p 00025000 41:59 6257356                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/date_core.so
7f8eedd71000-7f8eedd72000 rw-p 00000000 00:00 0 
7f8eedd72000-7f8eedf77000 r-xp 00000000 41:59 6257449                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/stringio.so
7f8eedf77000-7f8eedf78000 r--p 00005000 41:59 6257449                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/stringio.so
7f8eedf78000-7f8eedf79000 rw-p 00006000 41:59 6257449                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/stringio.so
7f8eedf79000-7f8eee17b000 r-xp 00000000 41:59 6257412                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/enc/trans/transdb.so
7f8eee17b000-7f8eee17c000 r--p 00002000 41:59 6257412                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/enc/trans/transdb.so
7f8eee17c000-7f8eee17d000 rw-p 00003000 41:59 6257412                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/enc/trans/transdb.so
7f8eee17d000-7f8eee37e000 r-xp 00000000 41:59 6257369                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/enc/encdb.so
7f8eee37e000-7f8eee37f000 r--p 00001000 41:59 6257369                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/enc/encdb.so
7f8eee37f000-7f8eee380000 rw-p 00002000 41:59 6257369                    /usr/lib/ruby/2.3.0/x86_64-linux-musl/enc/encdb.so
7f8eee380000-7f8eee5e1000 r-xp 00000000 41:59 6256742                    /usr/lib/libgmp.so.10.3.1
7f8eee5e1000-7f8eee5e3000 r--p 00061000 41:59 6256742                    /usr/lib/libgmp.so.10.3.1
7f8eee5e3000-7f8eee5e4000 rw-p 00063000 41:59 6256742                    /usr/lib/libgmp.so.10.3.1
7f8eee5e4000-7f8eee9e7000 r-xp 00000000 41:59 6256754                    /usr/lib/libruby.so.2.3.0
7f8eee9e7000-7f8eee9ef000 r--p 00203000 41:59 6256754                    /usr/lib/libruby.so.2.3.0
7f8eee9ef000-7f8eee9f0000 rw-p 0020b000 41:59 6256754                    /usr/lib/libruby.so.2.3.0
7f8eee9f0000-7f8eee9fe000 rw-p 00000000 00:00 0 
7f8eee9fe000-7f8eeea86000 r-xp 00000000 41:59 2091905                    /lib/ld-musl-x86_64.so.1
7f8eeeb7e000-7f8eeeb7f000 r--s 00000000 41:59 1051508                    /etc/localtime
7f8eeeb7f000-7f8eeeb80000 ---p 00000000 00:00 0 
7f8eeeb80000-7f8eeec86000 rw-p 00000000 00:00 0 
7f8eeec86000-7f8eeec87000 r--p 00088000 41:59 2091905                    /lib/ld-musl-x86_64.so.1
7f8eeec87000-7f8eeec88000 rw-p 00089000 41:59 2091905                    /lib/ld-musl-x86_64.so.1
7f8eeec88000-7f8eeec8b000 rw-p 00000000 00:00 0 
7fffd824b000-7fffd826c000 rw-p 00000000 00:00 0                          [stack]
7fffd83df000-7fffd83e1000 r--p 00000000 00:00 0                          [vvar]
7fffd83e1000-7fffd83e3000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Aborted (core dumped)
```

- fluentd version: Docker image `fluentd:v0.14` with image id `b9d8bef4e91e`
- Environment: Docker running on CoreOS

**Comment by repeatedly** [comment]
Does this happen with debian based docker image?
I want to know musl library cause it or not.

**Comment by slang800** [comment]
I haven't been able to reproduce it, even with the same data being uploaded to the worker. I'm not sure how to get it into the same state as before.

**Comment by fujimotos** [comment]
We've encountered the same bug on Fluentd v1.0.2 (as reported in #1860)

After some research, we found that this segfault is reliably reproducible by the following code:

```ruby
require 'fluent/msgpack_factory'
GC.stress = true
Fluent::MessagePackFactory.factory
```

So we suspecet that it might not be a bug of fluent-cat *per se*; Rather there should be
some memory bug in the underlying layer of Fluentd (strong suspect is in msgpack-ruby)

**Comment by repeatedly** [comment]
Thanks fujimotos.
If this problem happen with msgpack v1.2.2, please reopen.
