### ISSUE TITLE
Fluentd Hangs With No Stacktrace

### ISSUE THREAD

**Issue by sammerry** [fluent/fluentd#1621]
- fluentd or td-agent version.
  * td-agent 0.12.26
  * fluent-plugin-kafka (0.5.5)
  * fluent-plugin-multiprocess (0.2.2)
- Environment information, e.g. OS.
  * Ubuntu 14.04.5 LTS
- Your configuration
  * elb -> nginx -> fluentd -> kafka
- Your problem explanation. If you have an error logs, write it together.
  * no stack is thrown in td-agent.log. Nginx shows constant timeouts attempting to connect to fluentd. No buffering.

Sample Nginx Log:
```
2017/07/09 20:17:58 [error] 30642#30642: *6970 pending buffers on next upstream while connecting to upstream, client: <ip>, server: <ip:port>, upstream: "<ip:port>", bytes from/to client:0/0, bytes from/to upstream:0/0
```

This configuration has worked for the past 6 months without issues. Recently, around July 6th randomly and without change it started hanging. Each instance will slowly drop to 2% CPU and reject all incoming TCP connections. The only way to fix it is by restarting td-agent.

The instances drop out of the elb 1 by 1 over the period of an hour without any exception passed from kafka. This may be related to https://github.com/fluent/fluentd/issues/1384.

using  `sudo kill -CONT <master pid>`:
```
Sigdump at 2017-07-09 20:41:05 +0000 process 23622 (/usr/sbin/td-agent)
  Thread #<Thread:0x007f1eb499e650> status=run priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `dump_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:34:in `block in dump_all_thread_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `each'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `dump_all_thread_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:16:in `block in dump'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `open'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `_open_dump_path'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:14:in `dump'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:7:in `block in setup'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:350:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:350:in `waitpid'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:350:in `supervise'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:156:in `start'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
      /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
      /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/bin/fluentd:5:in `<top (required)>'
      /opt/td-agent/embedded/bin/fluentd:23:in `load'
      /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
      /usr/sbin/td-agent:7:in `load'
      /usr/sbin/td-agent:7:in `<main>'
  GC stat:
      count: 19
      heap_used: 261
      heap_length: 261
      heap_increment: 0
      heap_live_slot: 104762
      heap_free_slot: 1624
      heap_final_slot: 0
      heap_swept_slot: 17998
      heap_eden_page_length: 261
      heap_tomb_page_length: 0
      total_allocated_object: 377145
      total_freed_object: 272383
      malloc_increase: 587248
      malloc_limit: 16777216
      minor_gc_count: 14
      major_gc_count: 5
      remembered_shady_object: 672
      remembered_shady_object_limit: 882
      old_object: 40552
      old_object_limit: 70600
      oldmalloc_increase: 4253024
      oldmalloc_limit: 16777216
  Built-in objects:
   106,386: TOTAL
    44,313: T_NODE
    39,105: T_STRING
    10,050: T_ARRAY
     5,631: T_DATA
     2,085: T_OBJECT
     2,014: T_CLASS
     1,534: FREE
       673: T_HASH
       515: T_REGEXP
       137: T_MODULE
       129: T_ICLASS
        59: T_RATIONAL
        49: T_FILE
        40: T_MATCH
        38: T_STRUCT
         9: T_FLOAT
         4: T_BIGNUM
         1: T_COMPLEX
```

using `sudo kill -CONT <child pid>`:
```
Sigdump at 2017-07-09 20:42:50 +0000 process 23632 (/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/command/fluentd.rb)
  Thread #<Thread:0x007f13f359e648> status=run priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `dump_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:34:in `block in dump_all_thread_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `each'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `dump_all_thread_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:16:in `block in dump'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `open'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `_open_dump_path'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:14:in `dump'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:7:in `block in setup'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:87:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:87:in `run'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/engine.rb:199:in `run'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:570:in `run_engine'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:162:in `block in start'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:366:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:366:in `main_process'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:339:in `block in supervise'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:338:in `fork'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:338:in `supervise'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:156:in `start'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/command/fluentd.rb:173:in `<main>'
  Thread #<Thread:0x007f13edc8b358> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
  Thread #<Thread:0x007f13edc89648> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
  Thread #<Thread:0x007f13edc775b0> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
  Thread #<Thread:0x007f13edc75828> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
  Thread #<Thread:0x007f13edc67b10> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
  Thread #<Thread:0x007f13edc65fe0> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
  Thread #<Thread:0x007f13edc64438> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
  Thread #<Thread:0x007f13edc5e4e8> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
  Thread #<Thread:0x007f13edc5c2b0> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
  Thread #<Thread:0x007f13edc52328> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
  Thread #<Thread:0x007f13edc50280> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `sleep'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:174:in `cond_wait'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:158:in `run'
  Thread #<Thread:0x007f13edc40c90> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/2.1.0/webrick/server.rb:170:in `select'
      /opt/td-agent/embedded/lib/ruby/2.1.0/webrick/server.rb:170:in `block in start'
      /opt/td-agent/embedded/lib/ruby/2.1.0/webrick/server.rb:32:in `start'
      /opt/td-agent/embedded/lib/ruby/2.1.0/webrick/server.rb:160:in `start'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_monitor_agent.rb:251:in `block in start'
  GC stat:
      count: 5592
      heap_used: 469
      heap_length: 469
      heap_increment: 0
      heap_live_slot: 141061
      heap_free_slot: 50106
      heap_final_slot: 0
      heap_swept_slot: 87431
      heap_eden_page_length: 347
      heap_tomb_page_length: 122
      total_allocated_object: 589062082
      total_freed_object: 588921021
      malloc_increase: 37824
      malloc_limit: 28546867
      minor_gc_count: 4752
      major_gc_count: 840
      remembered_shady_object: 1073
      remembered_shady_object_limit: 1942
      old_object: 54517
      old_object_limit: 108600
      oldmalloc_increase: 6386512
      oldmalloc_limit: 32628156
  Built-in objects:
   191,167: TOTAL
    74,542: T_DATA
    50,016: FREE
    27,893: T_STRING
    26,073: T_ARRAY
     4,412: T_NODE
     2,902: T_OBJECT
     2,633: T_CLASS
     1,321: T_HASH
       762: T_REGEXP
       169: T_ICLASS
       161: T_STRUCT
       155: T_MODULE
        59: T_RATIONAL
        50: T_FILE
         9: T_FLOAT
         7: T_BIGNUM
         2: T_MATCH
         1: T_COMPLEX
```

Alternate child `sudo kill -CONT <child pid>`:
```
Sigdump at 2017-07-09 20:44:45 +0000 process 23648 (/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/command/fluentd.rb)
  Thread #<Thread:0x007f695e19e640> status=run priority=0
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `dump_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:34:in `block in dump_all_thread_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `each'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `dump_all_thread_backtrace'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:16:in `block in dump'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `open'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `_open_dump_path'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:14:in `dump'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:7:in `block in setup'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:350:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:350:in `waitpid'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:350:in `supervise'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:156:in `start'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/command/fluentd.rb:173:in `<main>'
  GC stat:
      count: 22
      heap_used: 186
      heap_length: 261
      heap_increment: 75
      heap_live_slot: 75028
      heap_free_slot: 784
      heap_final_slot: 0
      heap_swept_slot: 14530
      heap_eden_page_length: 186
      heap_tomb_page_length: 0
      total_allocated_object: 390155
      total_freed_object: 315127
      malloc_increase: 1797016
      malloc_limit: 16777216
      minor_gc_count: 16
      major_gc_count: 6
      remembered_shady_object: 628
      remembered_shady_object_limit: 1256
      old_object: 40102
      old_object_limit: 80204
      oldmalloc_increase: 1797400
      oldmalloc_limit: 16777216
  Built-in objects:
    75,812: TOTAL
    39,887: T_STRING
    14,890: T_NODE
     8,873: T_ARRAY
     5,284: T_DATA
     2,106: T_OBJECT
     2,014: T_CLASS
       968: T_REGEXP
       694: FREE
       638: T_HASH
       137: T_MODULE
       129: T_ICLASS
        59: T_RATIONAL
        51: T_MATCH
        36: T_STRUCT
        32: T_FILE
         9: T_FLOAT
         4: T_BIGNUM
         1: T_COMPLEX
```

**Comment by sumeshpremraj** [comment]
+1

**Comment by repeatedly** [comment]
> Alternate child sudo kill -CONT <child pid>:

Is this worker or supervisor of multiprocess? It seems one thread and it weird.

> using sudo kill -CONT <child pid>

This seems worker process result but there is no input plugin thread info in the log.
In the normal status, is input plugin info shown in sigdump result?

**Comment by sammerry** [comment]
Im using multi process to spin up 4 worker processes on 4 different ports and spreading the load through nginx.

The hanging recently stopped as mysteriously as it started. I can only assume something networking related in AWS. There was no config change.
