### ISSUE TITLE
in_tail stops handing events on 0.14.18 - logrotate?

### ISSUE THREAD

**Issue by warmfusion** [fluent/fluentd#1624]
I think this may be the same as #1383 which is reportedly patched in 0.12.x but I'm still seeing issues on my 0.14.18 deployment.

## Gem list

```
fluent-mixin-rewrite-tag-name (0.1.0)
fluent-plugin-amqp (0.11.0)
fluent-plugin-anonymizer (0.5.1)
fluent-plugin-bigquery (1.0.0)
fluent-plugin-consistent_id (0.2.0)
fluent-plugin-elasticsearch (1.9.5)
fluent-plugin-forest (0.3.3)
fluent-plugin-record-reformer (0.9.0)
fluent-plugin-systemd (0.2.0)
fluentd (0.14.18)
```
## Environment

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie
```

## Configuration

I can't give out our whole configuration (as its huge on the node I've got failures on atm) but here are the significant bits;

<details><summary>Collapsed for brevity</summary><p>

```
<source>
     format json
     time_key datetime.date
     tag articleapi.live
     path /var/log/fte/article-api.log
     pos_file /var/log/fluent/fluentd-pos-fte-article-api-log-live
     @type tail
</source>
...
<source>
     format json
     time_tag timestamp
     tag nginx.techradar.static.access
     path /var/log/nginx/techradar-static-access.log
     pos_file /var/log/fluent/techradar-static-access.pos
     @type tail
</source>

<filter **>
     enable_ruby false
    <record>
        input_tag ${tag}
        last_tag ${tag_parts[-1]}
        hostname REDACTED
    </record>
     @type record_transformer
</filter>


<match **>
     tag_key true
     exchange fluent.fanout
     exchange_type fanout
     hosts ["REDACTED","REDACTED"]
     port 5672
     vhost fluent
     user REDACTED
     pass REDACTED
     buffer_type file
     buffer_path /var/log/fluent/matcher-forwarder.*.buffer
     buffer_chunk_limit 8m
     buffer_queue_limit 128
     flush_interval 5s
     retry_wait 1s
     retry_limit 5
     @type amqp
</match>
```
</p></details>

### Log Rotate
```
/var/log/fte/*.log {
  compress
  compresscmd /bin/bzip2
  compressext .bz2
  copytruncate
  hourly
  nocopy
  nocreate
  rotate 72
}
```

### SigDump
<details><summary>SigDump Shown Here</summary><p>

```
Sigdump at 2017-07-12 09:35:42 +0000 process 31879 (/usr/local/bin/fluentd)
  Thread #<Thread:0x00000001f765b0> status=run priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `backtrace'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `dump_backtrace'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:34:in `block in dump_all_thread_backtrace'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `each'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `dump_all_thread_backtrace'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:16:in `block in dump'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `open'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `_open_dump_path'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:14:in `dump'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/sigdump-0.2.4/lib/sigdump.rb:7:in `block in setup'
      /usr/share/fluentd/lib/fluent/engine.rb:228:in `call'
      /usr/share/fluentd/lib/fluent/engine.rb:228:in `sleep'
      /usr/share/fluentd/lib/fluent/engine.rb:228:in `run'
      /usr/share/fluentd/lib/fluent/supervisor.rb:760:in `run_engine'
      /usr/share/fluentd/lib/fluent/supervisor.rb:508:in `block in run_worker'
      /usr/share/fluentd/lib/fluent/supervisor.rb:684:in `call'
      /usr/share/fluentd/lib/fluent/supervisor.rb:684:in `main_process'
      /usr/share/fluentd/lib/fluent/supervisor.rb:503:in `run_worker'
      /usr/share/fluentd/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
      /usr/share/fluentd/bin/fluentd:5:in `require'
      /usr/share/fluentd/bin/fluentd:5:in `<top (required)>'
      /usr/local/bin/fluentd:17:in `load'
      /usr/local/bin/fluentd:17:in `<main>'
  Thread #<Thread:0x00000002fbebe8> status=sleep priority=0
      /usr/share/fluentd/lib/fluent/plugin/output.rb:1284:in `sleep'
      /usr/share/fluentd/lib/fluent/plugin/output.rb:1284:in `flush_thread_run'
      /usr/share/fluentd/lib/fluent/plugin/output.rb:420:in `block (2 levels) in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000002fbe7d8> status=sleep priority=0
      /usr/share/fluentd/lib/fluent/plugin/output.rb:1241:in `sleep'
      /usr/share/fluentd/lib/fluent/plugin/output.rb:1241:in `enqueue_thread_run'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000002f63bd0> status=sleep priority=0
      /usr/share/fluentd/lib/fluent/plugin/output.rb:1284:in `sleep'
      /usr/share/fluentd/lib/fluent/plugin/output.rb:1284:in `flush_thread_run'
      /usr/share/fluentd/lib/fluent/plugin/output.rb:420:in `block (2 levels) in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000002f63158> status=sleep priority=0
      /usr/share/fluentd/lib/fluent/plugin/output.rb:1241:in `sleep'
      /usr/share/fluentd/lib/fluent/plugin/output.rb:1241:in `enqueue_thread_run'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000002f34178> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000002f31fe0> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000002f309d8> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x000000029a9c80> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x000000029a92f8> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x000000029a86a0> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x007f699028ed98> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x000000045b2a58> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x000000049eadc8> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000004ad2268> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x007f69901a2e48> status=sleep priority=0
      /usr/lib/ruby/2.1.0/webrick/server.rb:170:in `select'
      /usr/lib/ruby/2.1.0/webrick/server.rb:170:in `block in start'
      /usr/lib/ruby/2.1.0/webrick/server.rb:32:in `start'
      /usr/lib/ruby/2.1.0/webrick/server.rb:160:in `start'
      /usr/share/fluentd/lib/fluent/plugin/in_monitor_agent.rb:253:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x007f69901a2ba0> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000005014de8> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000004ab41f0> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x000000049ce088> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000004e526b8> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x000000041ed170> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000004573678> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000004b68538> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x0000000500c990> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x000000048b4a08> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x0000000491b898> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x0000000491a3d0> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x000000048b6218> status=sleep priority=0
      /usr/lib/ruby/2.1.0/webrick/utils.rb:176:in `sleep'
      /usr/lib/ruby/2.1.0/webrick/utils.rb:176:in `block in initialize'
  Thread #<Thread:0x007f69903150a0> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x0000000492b838> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x0000000318c768> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x00000004fca9c8> status=sleep priority=0
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
      /usr/share/fluentd/vendor/bundle/ruby/2.1.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
      /usr/share/fluentd/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
      /usr/share/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  Thread #<Thread:0x0000000422d9a0> status=sleep priority=0
      /usr/share/fluentd/lib/fluent/engine.rb:196:in `sleep'
      /usr/share/fluentd/lib/fluent/engine.rb:196:in `log_event_loop'
  GC stat:
      count: 47963
      heap_used: 936
      heap_length: 1488
      heap_increment: 0
      heap_live_slot: 313370
      heap_free_slot: 68152
      heap_final_slot: 5
      heap_swept_slot: 90964
      heap_eden_page_length: 774
      heap_tomb_page_length: 162
      total_allocated_object: 11086697782
      total_freed_object: 11086384412
      malloc_increase: 30152
      malloc_limit: 16777216
      minor_gc_count: 46605
      major_gc_count: 1358
      remembered_shady_object: 3615
      remembered_shady_object_limit: 6400
      old_object: 77613
      old_object_limit: 132044
      oldmalloc_increase: 30600
      oldmalloc_limit: 16777216
  Built-in objects:
   381,517: TOTAL
   195,689: T_STRING
    68,062: FREE
    42,876: T_ARRAY
    25,754: T_DATA
    20,004: T_HASH
    14,559: T_NODE
     7,067: T_OBJECT
     3,646: T_CLASS
     1,364: T_STRUCT
       664: T_REGEXP
       584: T_RATIONAL
       519: T_MATCH
       375: T_ICLASS
       246: T_MODULE
        82: T_FILE
        16: T_BIGNUM
         9: T_FLOAT
         1: T_COMPLEX
  All objects:
    56,274: String
     8,393: RubyVM::InstructionSequence
     8,280: Array
     5,811: Hash
     2,944: Proc
     2,882: RubyVM::Env
     1,536: Method
     1,303: Class
     1,020: Time
       664: Regexp
       605: Gem::Requirement
       578: Gem::Version
       575: Fluent::PluginHelper::Timer::TimerWatcher
       374: Gem::Dependency
       292: Fluent::EventTime
       288: Fluent::Plugin::TailInput::TailWatcher
       288: Fluent::Plugin::TailInput::TailWatcher::StatWatcher
       286: Fluent::Plugin::TailInput::TailWatcher::RotateHandler
       266: Range
       264: Fluent::Plugin::TailInput::MemoryPositionEntry
       246: Module
       243: Fluent::MultiEventStream
       212: Rational
       195: Struct::StatInfo
       169: Mutex
       168: MatchData
       156: Thread::Backtrace
       142: MessagePack::Buffer
       142: MessagePack::Packer
       136: Enumerator
       132: Fluent::Config::ConfigureProxy
       117: Fluent::Plugin::Buffer::Metadata
       116: Fluent::Config::Element
       113: EOFError
       100: Encoding
        91: Bundler::Dependency
        85: Fluent::Config::Section
        74: Yajl::Parser
        73: File
        71: Gem::Specification
        67: File::Stat
        66: Bundler::LazySpecification::Identifier
        66: Bundler::LazySpecification
        60: Gem::StubSpecification
        59: Bundler::StubSpecification
        55: Fluent::Plugin::Base::State
        51: Gem::StubSpecification::StubLine
        39: Thread
        31: Fluent::PluginHelper::Server::UDPCallbackSocket
        30: Monitor
        28: Fluent::OneEventStream
        26: Coolio::Loop
        26: Fluent::PluginHelper::EventLoop::DefaultWatcher
        24: Fluent::Plugin::TailInput::FilePositionEntry
        24: Fluent::Plugin::JSONParser
        24: Fluent::NumericTimeParser
        23: Fluent::Plugin::TailInput::PositionFile
        23: Fluent::Plugin::TailInput
        20: Gem::Platform
        17: OptionParser::Switch::RequiredArgument
        16: Fluent::Plugin::Buffer::FileChunk
        16: Fluent::Plugin::TailInput::TailWatcher::FIFO
        16: Fluent::Plugin::TailInput::TailWatcher::IOHandler
        15: Fluent::EventRouter::Pipeline
        15: Fluent::EventRouter::Pipeline::FilterOptimizer
        14: Pathname
        13: OptionParser::Switch::NoArgument
        10: Thread::ConditionVariable
        10: Bignum
         9: Set
         9: UnboundMethod
         9: Float
         8: Errno::ENOENT
         8: Fluent::Registry
         8: Bunny::Concurrent::ContinuationQueue
         7: AMQ::Protocol::MethodFrame
         6: AMQ::Protocol::HeaderFrame
         6: OptionParser::OptionMap
         5: Object
         4: AMQ::Protocol::BodyFrame
         4: Coolio::IO::Watcher
         4: Bundler::Index
         4: Bundler::SpecSet
         4: URI::HTTPS
         3: JSON::Ext::Generator::State
         3: OptionParser::List
         3: IRB::Notifier::LeveledNotifier
         3: IO
         3: Logger::Formatter
         3: Fluent::PluginHelper::Server::ServerInfo
         3: Fluent::EventRouter::Rule
         2: OptionParser::Switch::PlacedArgument
         2: Bundler::Source::Rubygems
         2: OptionParser::Switch::OptionalArgument
         2: ThreadGroup
         2: Fluent::Plugin::AMQPOutput
         2: Fluent::Plugin::FileBuffer
         2: IO::Buffer
         2: Fluent::PluginHelper::Server::EventHandler::UDPServer
         2: MessagePack::Factory
         2: UDPSocket
         2: Fluent::AllMatchPattern
         2: Fluent::Plugin::Output::FlushThreadState
         2: Bunny::Session
         2: Logger
         2: TCPServer
         2: Bunny::Authentication::PlainMechanismEncoder
         2: AMQ::Protocol::Exchange::DeclareOk
         2: Logger::LogDevice
         2: Bunny::Exchange
         2: AMQ::Protocol::Channel::OpenOk
         2: Bunny::Concurrent::AtomicFixnum
         2: Logger::LogDevice::LogDeviceMutex
         2: Bundler::GemHelpers::PlatformMatch
         2: Bunny::Channel
         2: Thread::Queue
         2: Bunny::ConsumerWorkPool
         2: Bunny::ReaderLoop
         2: Bunny::HeartbeatSender
         2: AMQ::BitSet
         2: AMQ::IntAllocator
         2: Bunny::ChannelIdAllocator
         2: Socket
         2: Bunny::Transport
         2: ThreadSafe::Cache
         1: NoMemoryError
         1: SystemStackError
         1: Random
         1: Fluent::SystemConfig
         1: Fluent::RootAgent
         1: Fluent::NoMatchMatch
         1: Fluent::EventRouter
         1: Fluent::EventRouter::MatchCache
         1: ARGF.class
         1: Data
         1: RubyVM
         1: Fluent::Plugin::ForwardInput
         1: Binding
         1: fatal
         1: Fluent::GlobMatchPattern
         1: IOError
         1: Bundler::Source::Path
         1: Fluent::Log
         1: ServerEngine::DaemonLogger
         1: Fluent::Supervisor::LoggerInitializer
         1: Fluent::Supervisor
         1: Complex
         1: Bundler::LockfileParser
         1: WEBrick::HTTPVersion
         1: Bundler::Definition
         1: OptionParser
         1: Resolv::DNS::Config
         1: Resolv::DNS
         1: Resolv::Hosts
         1: Resolv
         1: OpenSSL::X509::Store
         1: ArgumentError
         1: Fluent::Plugin::UdpInput
         1: Fluent::EngineClass
         1: Fluent::Compat::NullOutputChain
         1: Fluent::Plugin::RecordTransformerFilter::PlaceholderExpander
         1: Fluent::Plugin::RecordTransformerFilter
         1: IRB::Notifier::NoMsgNotifier
         1: IRB::StdioOutputMethod
         1: IRB::Notifier::CompositeNotifier
         1: Fluent::Plugin::MonitorAgentInput
         1: Bundler::CurrentRuby
         1: WEBrick::Utils::TimeoutHandler
         1: OptionParser::CompletingHash
         1: WEBrick::HTTPServer::MountTable
         1: Bundler::Source::Gemspec
         1: Thread::SizedQueue
         1: WEBrick::HTTPServer
         1: WEBrick::Log
         1: Coolio::TCPServer
         1: Bundler::GemVersionPromoter
         1: Bundler::Runtime
         1: URI::Parser
         1: Bundler::RubygemsIntegration::MoreFuture
         1: Bundler::Settings
         1: Process::Status
         1: Bundler::SourceList
  String 1,764,068 bytes
   Array 2 elements
    Hash 31 pairs
```

</p></details>

# Problem

It appears that every so often, usually around the minutes of the hour (eg 06:50, 09:50, 18:50) we see fluent stop sending events from our systems. I suspect the issue is the same as that reported on #1383 but manifesting on a 0.14.18 deployment.

**Comment by repeatedly** [comment]
in_tail doesn't work properly with `nocreate`.

http://docs.fluentd.org/v0.12/articles/in_tail#logrotate-setting

**Comment by warmfusion** [comment]
Must be said; looking closer at that logrotate config its a bit ... strange... `nocopy`, `nocreate`, `copytruncate`...

I'll have a little chat with the devs and see if we can reproduce this issue when we've tidied up the logrotate nonense 
(Closing for now; will reopen if i can reproduce the issue)
