### ISSUE TITLE
name parameter is required if TLS is used

### ISSUE THREAD

**Issue by notslang** [fluent/fluentd#1626]
If I don't specify a `name` parameter in my `<server>` block I get this error.

```
2017-07-09 06:17:40 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-07-09 06:17:41 +0000 chunk="553db9e8ff34e1d772b2f5bac3514251" error_class=NoMethodError error="undefined method `ascii_only?' for nil:NilClass"
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/openssl/ssl.rb:201:in `verify_hostname'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/openssl/ssl.rb:190:in `block in verify_certificate_identity'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/openssl/ssl.rb:188:in `each'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/openssl/ssl.rb:188:in `verify_certificate_identity'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/openssl/ssl.rb:317:in `post_connection_check'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.18/lib/fluent/plugin_helper/socket.rb:147:in `socket_create_tls'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.18/lib/fluent/plugin/out_forward.rb:319:in `create_transfer_socket'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.18/lib/fluent/plugin/out_forward.rb:631:in `send_data'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.18/lib/fluent/plugin/out_forward.rb:285:in `block in try_write'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.18/lib/fluent/plugin/out_forward.rb:304:in `block in select_a_healthy_node'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.18/lib/fluent/plugin/out_forward.rb:298:in `times'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.18/lib/fluent/plugin/out_forward.rb:298:in `select_a_healthy_node'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.18/lib/fluent/plugin/out_forward.rb:285:in `try_write'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.18/lib/fluent/plugin/output.rb:1034:in `try_flush'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.18/lib/fluent/plugin/output.rb:1268:in `flush_thread_run'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.18/lib/fluent/plugin/output.rb:420:in `block (2 levels) in start'
  2017-07-09 06:17:40 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.18/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2017-07-09 06:17:42 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-07-09 06:17:41 +0000 chunk="553db9e8ff34e1d772b2f5bac3514251" error_class=NoMethodError error="undefined method `ascii_only?' for nil:NilClass"
  2017-07-09 06:17:42 +0000 [warn]: #0 suppressed same stacktrace
2017-07-09 06:17:45 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2017-07-09 06:17:43 +0000 chunk="553db9e8ff34e1d772b2f5bac3514251" error_class=NoMethodError error="undefined method `ascii_only?' for nil:NilClass"
  2017-07-09 06:17:45 +0000 [warn]: #0 suppressed same stacktrace
2017-07-09 06:17:49 +0000 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2017-07-09 06:17:47 +0000 chunk="553db9e8ff34e1d772b2f5bac3514251" error_class=NoMethodError error="undefined method `ascii_only?' for nil:NilClass"
  2017-07-09 06:17:49 +0000 [warn]: #0 suppressed same stacktrace
2017-07-09 06:17:55 +0000 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2017-07-09 06:17:52 +0000 chunk="553db9e8ff34e1d772b2f5bac3514251" error_class=NoMethodError error="undefined method `ascii_only?' for nil:NilClass"
  2017-07-09 06:17:55 +0000 [warn]: #0 suppressed same stacktrace
2017-07-09 06:18:04 +0000 [warn]: #0 failed to flush the buffer. retry_time=4 next_retry_seconds=2017-07-09 06:18:03 +0000 chunk="553db9e8ff34e1d772b2f5bac3514251" error_class=NoMethodError error="undefined method `ascii_only?' for nil:NilClass"
  2017-07-09 06:18:04 +0000 [warn]: #0 suppressed same stacktrace
2017-07-09 06:18:21 +0000 [warn]: #0 failed to flush the buffer. retry_time=5 next_retry_seconds=2017-07-09 06:18:19 +0000 chunk="553db9e8ff34e1d772b2f5bac3514251" error_class=NoMethodError error="undefined method `ascii_only?' for nil:NilClass"
  2017-07-09 06:18:21 +0000 [warn]: #0 suppressed same stacktrace
```

I'm using `0.14` in Docker on CoreOS (image id `44a6f8963228`) and my config is:

```
<source>
  @type forward
  @id input1
  port 24224
</source>
<match **>
  @type forward
  send_timeout 3m
  recover_wait 10s
  heartbeat_interval 5s
  phi_threshold 16
  hard_timeout 10m
  require_ack_response true
  transport tls
  tls_cert_path /fluentd/ca_cert.pem
  <server>
    #name coreos0
    host "xxx.xxx.xxx.xxx"
    port 24225
    weight 60
  </server>
  <buffer>
    @type "file"
    path "/fluentd/log/buffer"
    retry_max_interval 10m
    retry_forever true
    chunk_limit_size 5MB
  </buffer>
</match>
```

Docs should mention this is needed and a better error message would be really nice.

**Comment by repeatedly** [comment]
> Docs should mention this

Yes but there is no v0.14 forward plugin document in the fluentd-docs.
We will mention it in the future.

> a better error message would be really nice.

This is good idea. I will do it.

**Comment by ganmacs** [comment]
Current fluentd always sets default name https://github.com/fluent/fluentd/blob/6ef77be211d33c06c8602f71daa47910822e042e/lib/fluent/plugin/out_forward.rb#L432 . so this was fixed.
