### ISSUE TITLE
elasticsearch down caused td-agent cpu 100%

### ISSUE THREAD

**Issue by hiscal2015** [fluent/fluentd#1636]
td-agent version: 2.3.4

issue:
I use td-agent with fluent-elasticsearch-plugin, when I shutdown elasticsearch, found os cpu usage was 100% because of td-agent, is this the expected behavior?

log:
```
2017-07-19 12:25:59 +0800 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="docker.var.lib.docker.containers.d8062ec627f7872f17cb48bb1e7c643a4765344bf1b3a9308a69f4aa3d62ea55.d8062ec627f7872f17cb48bb1e7c643a4765344bf1b3a9308a69f4aa3d62ea55-json.log"
  2017-07-19 12:25:59 +0800 [warn]: suppressed same stacktrace
2017-07-19 12:25:59 +0800 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="docker.var.lib.docker.containers.d8062ec627f7872f17cb48bb1e7c643a4765344bf1b3a9308a69f4aa3d62ea55.d8062ec627f7872f17cb48bb1e7c643a4765344bf1b3a9308a69f4aa3d62ea55-json.log"
  2017-07-19 12:25:59 +0800 [warn]: suppressed same stacktrace
2017-07-19 12:25:59 +0800 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="docker.var.lib.docker.containers.d8062ec627f7872f17cb48bb1e7c643a4765344bf1b3a9308a69f4aa3d62ea55.d8062ec627f7872f17cb48bb1e7c643a4765344bf1b3a9308a69f4aa3d62ea55-json.log"
  2017-07-19 12:25:59 +0800 [warn]: suppressed same stacktrace
2017-07-19 12:25:59 +0800 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="docker.var.lib.docker.containers.d8062ec627f7872f17cb48bb1e7c643a4765344bf1b3a9308a69f4aa3d62ea55.d8062ec627f7872f17cb48bb1e7c643a4765344bf1b3a9308a69f4aa3d62ea55-json.log"
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:204:in `block in emit'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:193:in `emit'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/output.rb:467:in `emit'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/event_router.rb:154:in `emit'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/event_router.rb:90:in `emit_stream'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:291:in `receive_lines'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:401:in `call'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:401:in `wrap_receive_lines'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:596:in `call'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:596:in `on_notify'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:427:in `on_notify'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:512:in `call'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:512:in `on_timer'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run_once'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:275:in `run'
2017-07-19 12:25:59 +0800 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="docker.var.lib.docker.containers.569301d2e763f87321b9a63bfc71e07df72740641a643c099b2cd39b5c211f5d.569301d2e763f87321b9a63bfc71e07df72740641a643c099b2cd39b5c211f5d-json.log"
  2017-07-19 12:25:59 +0800 [warn]: suppressed same stacktrace
2017-07-19 12:25:59 +0800 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="docker.var.lib.docker.containers.d8062ec627f7872f17cb48bb1e7c643a4765344bf1b3a9308a69f4aa3d62ea55.d8062ec627f7872f17cb48bb1e7c643a4765344bf1b3a9308a69f4aa3d62ea55-json.log"
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:204:in `block in emit'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:193:in `emit'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/output.rb:467:in `emit'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/event_router.rb:154:in `emit'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/event_router.rb:90:in `emit_stream'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:291:in `receive_lines'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:401:in `call'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:401:in `wrap_receive_lines'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:596:in `call'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:596:in `on_notify'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:427:in `on_notify'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:528:in `call'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:528:in `on_change'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run_once'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run'
  2017-07-19 12:25:59 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_tail.rb:275:in `run'
```

![ranchercpu](https://user-images.githubusercontent.com/15604715/28351824-f5df047e-6c84-11e7-9586-483148c2b4a8.jpg)

**Comment by roasties** [comment]
+1 for this - we are encountering the same issue. CPU load 100% when attempting to flush buffer when ES is down.

**Comment by repeatedly** [comment]
Does this happen with other plugin? only ES plugin?

**Comment by jclosure** [comment]
+1 same issue.  If the ES endpoint is not available, we see very high cpu:
```bash
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   36 td-agent  20   0  295092  81952   9420 S 102.8  1.0  32:50.47 ruby
```

**Comment by omaransari-home24** [comment]
Essentially, what's going on is that the queue has reached its limit. Check the retry settings for the ES plugin. By default it can be a high number, and if you have the exponential backoff algorithm enabled, the queue can remain full indefinitely. Make it more resilient to network errors by setting a sane retry_max_times value so that chunks are dropped eventually and threads free up.
