### ISSUE TITLE
The section *.pos file was not output?

### ISSUE THREAD

**Issue by hiddletian** [fluent/fluentd#1639]
td-agent version: 0.12.26
issue:
some *.pos file was not output,when you put the configure point one project, the projectname.pos where output and update.
I want to know fluentd have handle limit default?

follow log why?
2017-07-19 21:55:36 +0800 [info]: shutting down fluentd
2017-07-19 21:55:36 +0800 [info]: shutting down input type="tail" plugin_id="object:3f9149d28aec"
2017-07-19 21:55:36 +0800 [info]: shutting down input type="tail" plugin_id="object:3f914a1210a4"
2017-07-19 21:55:36 +0800 [info]: shutting down input type="tail" plugin_id="object:3f914a182034"
2017-07-19 21:55:36 +0800 [info]: shutting down input type="debug_agent" plugin_id="object:3f914a17b2ac"
2017-07-19 21:55:36 +0800 [info]: shutting down input type="tail" plugin_id="object:3f9149d0cf40"
2017-07-19 21:55:36 +0800 [info]: shutting down input type="monitor_agent" plugin_id="object:3f9147cd617c"
2017-07-19 21:55:36 +0800 [info]: shutting down output type="null" plugin_id="object:3f9149db6c48"
2017-07-19 21:55:36 +0800 [info]: shutting down output type="copy" plugin_id="object:3f91480f8908"
2017-07-19 21:55:36 +0800 [warn]: emit transaction failed: error_class=Errno::ENOENT error="No such file or directory @ sys_fail2 - (/var/log/td-agent/elasticsearch-transfer-buffer/beeper_lbs_archive.cache.archive.beeper_lbs.request.b554aaad2c4c14ea3.log, /var/log/td-agent/elasticsearch-transfer-buffer/beeper_lbs_archive.cache.archive.beeper_lbs.request.q554aaad2c4c14ea3.log)" tag="archive.beeper_lbs.request"
  2017-07-19 21:55:36 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/buffer.rb:239:in `block in emit'
2017-07-19 21:55:36 +0800 [info]: shutting down output type="copy" plugin_id="object:3f9149da9f0c"
  2017-07-19 21:55:36 +0800 [warn]: suppressed same stacktrace

**Comment by repeatedly** [comment]
Please follow https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem :)

**Comment by hiddletian** [comment]
td-agent version: 0.12.26
os:centos 6.5

issue:
some *.pos file was not output,when you put the configure point one project, the projectname.pos where output and update.

cat /etc/td-agent/td-agent.conf
<source>
  @type multiprocess

  <process>
    cmdline -c /etc/td-agent/fluentd_child1.conf --log /var/log/td-agent/fluentd_child1.log
    sleep_before_start 1s
    sleep_before_shutdown 5s
  </process>
  <process>
    cmdline -c /etc/td-agent/fluentd_elasticsearch.conf --log /var/log/td-agent/fluentd_elasticsearch.log
    sleep_before_start 1s
    sleep_before_shutdown 5s
  </process>
</source>

cat /etc/td-agent/fluentd_child1.conf
<source>
  @type forward
  port 24224
</source>

@include conf.d/*.conf

<match **>
  @type copy
  <store>
    @type file
    path /plog/other/system
    timezone Asia/Shanghai
    format out_file
    time_slice_format %Y%m%d
    flush_interval 5s
    append true
    time_format %Y-%m-%d %H:%M:%S
    buffer_type memory
    buffer_chunk_limit 4m
    buffer_queue_limit 32
    flush_interval 5s
    flush_at_shutdown true
    disable_retry_limit false
    retry_wait 1s
    retry_limit 5
  </store>
</match>

cat /etc/td-agent/fluentd_elasticsearch.conf
@include archive_elasticsearch_conf.d/*.conf


<match **>
  @type copy
  <store>
    @type file
    path /plog/other/system
    timezone Asia/Shanghai
    format out_file
    time_slice_format %Y%m%d
    flush_interval 5s
    append true
    time_format %Y-%m-%d %H:%M:%S
    buffer_type memory
    buffer_chunk_limit 4m
    buffer_queue_limit 32
    flush_interval 5s
    flush_at_shutdown true
    disable_retry_limit false
    #retry_wait 1s
    retry_limit 5
  </store>
</match>


# debug agent

<source>
  type monitor_agent
  bind 0.0.0.0
  port 24220
</source>

for log:
tail -10 /var/log/td-agent/fluentd_child1.log
2017-07-20 22:59:15 +0800 [warn]: To avoid problems, set a smaller number to the buffer_chunk_limit
2017-07-20 22:59:15 +0800 [warn]: in the forward output ``at the log forwarding server.``
2017-07-20 23:00:02 +0800 [warn]: Size of the emitted data exceeds buffer_chunk_limit.
2017-07-20 23:00:02 +0800 [warn]: This may occur problems in the output plugins ``at this server.``
2017-07-20 23:00:02 +0800 [warn]: To avoid problems, set a smaller number to the buffer_chunk_limit
2017-07-20 23:00:02 +0800 [warn]: in the forward output ``at the log forwarding server.``
2017-07-20 23:01:47 +0800 [warn]: Size of the emitted data exceeds buffer_chunk_limit.
2017-07-20 23:01:47 +0800 [warn]: This may occur problems in the output plugins ``at this server.``
2017-07-20 23:01:47 +0800 [warn]: To avoid problems, set a smaller number to the buffer_chunk_limit
2017-07-20 23:01:47 +0800 [warn]: in the forward output ``at the log forwarding server.``

have a pos file at 2017-07-19 21:55 was stop update,so I select yesterday logs

2017-07-19 21:55:36 +0800 [info]: shutting down fluentd
2017-07-19 21:55:36 +0800 [info]: shutting down input type="tail" plugin_id="object:3f9149d28aec"
2017-07-19 21:55:36 +0800 [info]: shutting down input type="tail" plugin_id="object:3f914a1210a4"
2017-07-19 21:55:36 +0800 [info]: shutting down input type="tail" plugin_id="object:3f914a182034"
2017-07-19 21:55:36 +0800 [info]: shutting down input type="debug_agent" plugin_id="object:3f914a17b2ac"
2017-07-19 21:55:36 +0800 [info]: shutting down input type="tail" plugin_id="object:3f9149d0cf40"
2017-07-19 21:55:36 +0800 [info]: shutting down input type="monitor_agent" plugin_id="object:3f9147cd617c"
2017-07-19 21:55:36 +0800 [info]: shutting down output type="null" plugin_id="object:3f9149db6c48"
2017-07-19 21:55:36 +0800 [info]: shutting down output type="copy" plugin_id="object:3f91480f8908"
2017-07-19 21:55:36 +0800 [warn]: emit transaction failed: error_class=Errno::ENOENT error="No such file or directory @ sys_fail2 - (/var/log/td-agent/elasticsearch-transfer-buffer/beeper_lbs_archive.cache.archive.beeper_lbs.request.b554aaad2c4c14ea3.log, /var/log/td-agent/elasticsearch-transfer-buffer/beeper_lbs_archive.cache.archive.beeper_lbs.request.q554aaad2c4c14ea3.log)" tag="archive.beeper_lbs.request"
2017-07-19 21:55:36 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/buffer.rb:239:in `block in emit'
2017-07-19 21:55:36 +0800 [info]: shutting down output type="copy" plugin_id="object:3f9149da9f0c"
2017-07-19 21:55:36 +0800 [warn]: suppressed same stacktrace
