### ISSUE TITLE
Opportunity to assign hash to variable in record_transformer filter

### ISSUE THREAD

**Issue by cazorla19** [fluent/fluentd#1652]
Hi! I'm just wondering about one Fluentd feature, is it supported or not.
I want to assign hash object to variable `record_transfrormer` filter. I tried few ways and no one didn't work out correctly.

The goal I pursue: generate `tags` variable as a hash to pass it to [dogstatsd](https://github.com/ryotarai/fluent-plugin-dogstatsd) output. That way I'll have tag in my metrics.
So, the only way I can create hash is a `record_transformer` plugin. I tried 2 ways:

1. Pass hash in braces

```
<filter **>
  @type record_transformer
  enable_ruby true
  <record>
    Host "#{Socket.gethostname}"
    IP "#{(Socket.ip_address_list.detect do |intf| intf.ipv4_private? end).ip_address}"
    key 'myservice.fluentd.messages.rate_avg'
    value 1
    tags {'log_name': \'${tag}\'}
  </record>
</filter>
```

Here I'm getting an error

```
2017-08-02 08:11:34 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 08:11:35 +0000 error_class="NoMethodError" error="undefined method `map' for \"{'log_name': 'example.nginx.access'}\":String" plugin_id="object:3fb38361ed30"
  2017-08-02 08:11:34 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-dogstatsd-0.0.6/lib/fluent/plugin/out_dogstatsd.rb:76:in `block (2 levels) in write'
  2017-08-02 08:11:34 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin/buf_memory.rb:67:in `feed_each'
  2017-08-02 08:11:34 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin/buf_memory.rb:67:in `msgpack_each'
  2017-08-02 08:11:34 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-dogstatsd-0.0.6/lib/fluent/plugin/out_dogstatsd.rb:42:in `block in write'
  2017-08-02 08:11:34 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/dogstatsd-ruby-1.4.1/lib/statsd.rb:236:in `batch'
  2017-08-02 08:11:34 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-dogstatsd-0.0.6/lib/fluent/plugin/out_dogstatsd.rb:41:in `write'
  2017-08-02 08:11:34 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/buffer.rb:354:in `write_chunk'
  2017-08-02 08:11:34 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/buffer.rb:333:in `pop'
  2017-08-02 08:11:34 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/output.rb:342:in `try_flush'
  2017-08-02 08:11:34 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/output.rb:149:in `run'
```

2. Assign as a key

```
<filter **>
  @type record_transformer
  enable_ruby true
  <record>
    Host "#{Socket.gethostname}"
    IP "#{(Socket.ip_address_list.detect do |intf| intf.ipv4_private? end).ip_address}"
    key 'myservice.fluentd.messages.rate_avg'
    value 1
    tags['log_name'] "${tag}"
  </record>
</filter>
```

Here I'm getting nothing. Here is the output of logged `tags` variable.

```
          tags = if @flat_tags || @flat_tag
                   record
                 else
                   record['tags']
                 end
          if tags
            options[:tags] = tags.map do |k, v|
              "#{k}:#{v}"
            end
          end
         log.info(tags)
```

```
2017-08-02 09:22:05 +0000 [info]:
2017-08-02 09:22:05 +0000 [info]:
2017-08-02 09:22:05 +0000 [info]:
2017-08-02 09:22:05 +0000 [info]:
2017-08-02 09:22:05 +0000 [info]:
```

So, does Fluentd support hashes creation? If so, please, explain how to do this to fit my case.

Thanks in advance.

**Comment by mikebryant** [comment]
In your first case, are you getting warnings like this? -> https://github.com/fluent/fluentd/blob/5c62aab5644859376d5373e0ccffe325e2c2468d/lib/fluent/plugin/filter_record_transformer.rb#L119

Try:
```
<filter **>
  @type record_transformer
  enable_ruby true
  <record>
    Host "#{Socket.gethostname}"
    IP "#{(Socket.ip_address_list.detect do |intf| intf.ipv4_private? end).ip_address}"
    key 'myservice.fluentd.messages.rate_avg'
    value 1
    tags {"log_name": "${tag}"}
  </record>
</filter>
```
(Note the use of double quotes in the json object)

**Comment by ganmacs** [comment]
it's a stale issue. I'm closing. if you have any problem, updating fluentd might help it.
