### ISSUE TITLE
 thread exited by unexpected error Errno::ENOTCONN

### ISSUE THREAD

**Issue by wzyplus** [fluent/fluentd#1658]
### Fluentd Version
0.14.20

### Environment
- docker image build from fluent/fluentd:v0.14.20-onbuild
- running on Ubuntu 14.04.4

### Configure
```
<source>
  @type  forward
  port  24224
  @label @APP_LOG
</source>

<system>
  log_level warn
  processd_name fluentd
</system>

<label @APP_LOG>
  <match release.**>
    @type copy
    <store>
      # add tag prefix and re-emit record
      @type rewrite_tag_filter
      rewriterule1 log \"level":\s*"error\" to_slack.${tag}
    </store>
    <store>
      @type rewrite_tag_filter
      rewriterule1 log .* normal.${tag}
    </store>
  </match>
  <match {dev,debug}.**>
    @type copy
    <store>
      # add tag prefix and re-emit record
      @type rewrite_tag_filter
      rewriterule1 log \"level":\s*"error\" debug_error_to_slack.${tag}
      rewriterule2 log \"level":\s*"(warn|warning)\" debug_warn_to_slack.${tag}
    </store>
    <store>
      @type rewrite_tag_filter
      rewriterule1 log .* normal.${tag}
    </store>
  </match>

  # add hostname, env, app to record
  <filter **>
    @type record_modifier
    <record>
      hostname "#{ENV['HOSTNAME']}"
      env ${tag_parts[1]}
      app ${tag_parts[2]}
    </record>
  </filter>

  # parse json
  <filter **>
    @type parser
    key_name log
    reserve_time false
    reserve_data true
    inject_key_prefix log_
	<parse>
	  @type json
	  time_key time
	  keep_time_key true
	</parse>
  </filter>

  <match to_slack.**>
    @type slack
    webhook_url "#{ENV['SLACK_URL']}"
    parse none
    channel hustonwehaveaproblem
    username Apollo13
    icon_emoji :weary:
    color danger
    flush_interval 1s
    message "@channel\n message: %s\n app: [%s][%s][%s]\n time: %s\n hostname: %s\n raw: %s"
    message_keys log_msg,app,env,container_id,log_time,hostname,log

    time_key log_time

    buffer_type file
    buffer_path /fluentd/buffer/to_slack.*.buffer
    buffer_chunk_limit 10m
    buffer_queue_limit 32

    disable_retry_limit false
    retry_limit 60
    retry_wait 5s
    max_retry_wait 60s

    <parse>
    </parse>
    <format>
    </format>
  </match>

  <match debug_warn_to_slack.*.{watchpoint-ss-worker,watchpoint-dw-worker}>
    @type null
    <parse>
    </parse>
  </match>

  <match {debug_error_to_slack,debug_warn_to_slack}.**>
    @type slack
    webhook_url "#{ENV['SLACK_URL']}"
    parse none
    channel noproblem
    username Apollo13
    icon_emoji :weary:
    color danger
    flush_interval 1s
    message "@channel\n message: %s\n app: [%s][%s][%s]\n time: %s\n hostname: %s\n raw: %s"
    message_keys log_msg,app,env,container_id,log_time,hostname,log

    time_key log_time

    buffer_type file
    buffer_path /fluentd/buffer/debug_to_slack.*.buffer
    buffer_chunk_limit 10m
    buffer_queue_limit 32

    disable_retry_limit false
    retry_limit 60
    retry_wait 5s
    max_retry_wait 60s

    <parse>
    </parse>
    <format>
    </format>
  </match>

  <match **>
    @type elasticsearch
    host "#{ENV['ES_HOST']}"
    port "#{ENV['ES_PORT']}"

    logstash_format true
    logstash_prefix app-log
    type_name app-log
    time_key log_time
    remove_keys log_time

    buffer_type file
    buffer_path /fluentd/buffer/app-log.*.buffer
    buffer_chunk_limit 50m
    buffer_queue_limit 128
    flush_interval 2s
    num_threads 4
    reload_connections false
    request_timeout 40s

    disable_retry_limit false
    retry_limit 60
    retry_wait 5s
    max_retry_wait 60s
  </match>
</label>

<filter **>
  @type record_modifier
  <record>
    hostname "#{ENV['HOSTNAME']}"
  </record>
</filter>

<match **>
  @type elasticsearch
  host "#{ENV['ES_HOST']}"
  port "#{ENV['ES_PORT']}"

  logstash_format true
  logstash_prefix fluentd-log
  logstash_dateformat %Y
  type_name fluentd-log

  disable_retry_limit false
  retry_limit 60
  retry_wait 5s
  max_retry_wait 60s
  reload_connections false
</match>
```

### Logs
```
fluentd_1 | 2017-08-05 22:21:15 +0800 [warn]: section <parse> is not used in <match **> of elasticsearch plugin
fluentd_1 | 2017-08-05 22:21:15 +0800 [warn]: #0 thread exited by unexpected error plugin=Fluent::Plugin::ForwardInput title=:event_loop error_class=Errno::ENOTCONN error="Socket not connected - getpeername(2)"
fluentd_1 | 2017-08-05 22:21:15 +0800 [error]: #0 unexpected error error_class=Errno::ENOTCONN error="Socket not connected - getpeername(2)"
fluentd_1 |   2017-08-05 22:21:15 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.0/lib/cool.io/socket.rb:147:in `peeraddr'
fluentd_1 |   2017-08-05 22:21:15 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.0/lib/cool.io/socket.rb:147:in `initialize'
fluentd_1 |   2017-08-05 22:21:15 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin_helper/server.rb:530:in `initialize'
fluentd_1 |   2017-08-05 22:21:15 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.0/lib/cool.io/server.rb:40:in `new'
fluentd_1 |   2017-08-05 22:21:15 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.0/lib/cool.io/server.rb:40:in `on_connection'
fluentd_1 |   2017-08-05 22:21:15 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.0/lib/cool.io/listener.rb:46:in `on_readable'
fluentd_1 |   2017-08-05 22:21:15 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run_once'
fluentd_1 |   2017-08-05 22:21:15 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.5.0/lib/cool.io/loop.rb:88:in `run'
fluentd_1 |   2017-08-05 22:21:15 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
fluentd_1 |   2017-08-05 22:21:15 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

Logs is forwarded by docker log driver.

**Comment by repeatedly** [comment]
Fixed cool.io: https://github.com/tarcieri/cool.io/commit/cb9e2d95cdc55afed28b4e56cf7d551990a6280f
Update your cool.io to latest 1.5.1 should fix this problem.

**Comment by michaelfortin** [comment]
I have the same error using fluentd version 1.12.4, with open.io 1.7.1.

#### Docker image
fluent/fluentd:v1.12-1

#### Configuration
```
<source>
  @type syslog
  port 514
  bind 0.0.0.0
  <transport tls>
    ca_path /certificates/ca-cert.pem
    cert_path /certificates/server-cert.pem
    private_key_path /certificates/server-key.pem
  </transport>
  <parse>
    message_format auto
    with_priority true
    parser_type string
  </parse>
  frame_type traditional
  source_hostname_key hostname
  source_address_key address
  severity_key severity
  priority_key priority
  facility_key facility
  tag syslog
</source>
```

#### Logs
```
#<Thread:0x00007fee19b77208@event_loop /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/plugin_helper/thread.rb:70 run> terminated with exception (report_on_exception is true):
/usr/lib/ruby/2.7.0/openssl/ssl.rb:239:in `peeraddr': Socket not connected - getpeername(2) (Errno::ENOTCONN)
from /usr/lib/ruby/2.7.0/openssl/ssl.rb:239:in `peeraddr'
from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/plugin_helper/server.rb:713:in `rescue in try_tls_accept'
from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/plugin_helper/server.rb:696:in `try_tls_accept'
from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/plugin_helper/server.rb:730:in `on_readable'
from /usr/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:186:in `on_readable'
from /usr/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
from /usr/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-07-21 19:12:20 +0000 [warn]: #0 thread exited by unexpected error plugin=Fluent::Plugin::SyslogInput title=:event_loop error_class=Errno::ENOTCONN error="Socket not connected - getpeername(2)"
/usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/plugin_helper/server.rb:697:in `accept_nonblock': Connection reset by peer - SSL_accept (Errno::ECONNRESET)
from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/plugin_helper/server.rb:697:in `try_tls_accept'
from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/plugin_helper/server.rb:730:in `on_readable'
from /usr/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:186:in `on_readable'
from /usr/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
from /usr/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```
