### ISSUE TITLE
purge buffer chunk failed

### ISSUE THREAD

**Issue by wzyplus** [fluent/fluentd#1659]
### Fluentd Version
0.14.20

### Environment
- docker image build from fluent/fluentd:v0.14.20-onbuild
- running on Ubuntu 14.04.4

### Configure
```
<source>
  @type  forward
  port  24224
  @label @APP_LOG
</source>

<system>
  log_level warn
  processd_name fluentd
</system>

<label @APP_LOG>
  <match release.**>
    @type copy
    <store>
      # add tag prefix and re-emit record
      @type rewrite_tag_filter
      rewriterule1 log \"level":\s*"error\" to_slack.${tag}
    </store>
    <store>
      @type rewrite_tag_filter
      rewriterule1 log .* normal.${tag}
    </store>
  </match>
  <match {dev,debug}.**>
    @type copy
    <store>
      # add tag prefix and re-emit record
      @type rewrite_tag_filter
      rewriterule1 log \"level":\s*"error\" debug_error_to_slack.${tag}
      rewriterule2 log \"level":\s*"(warn|warning)\" debug_warn_to_slack.${tag}
    </store>
    <store>
      @type rewrite_tag_filter
      rewriterule1 log .* normal.${tag}
    </store>
  </match>

  # add hostname, env, app to record
  <filter **>
    @type record_modifier
    <record>
      hostname "#{ENV['HOSTNAME']}"
      env ${tag_parts[1]}
      app ${tag_parts[2]}
    </record>
  </filter>

  # parse json
  <filter **>
    @type parser
    key_name log
    reserve_time false
    reserve_data true
    inject_key_prefix log_
	<parse>
	  @type json
	  time_key time
	  keep_time_key true
	</parse>
  </filter>

  <match to_slack.**>
    @type slack
    webhook_url "#{ENV['SLACK_URL']}"
    parse none
    channel hustonwehaveaproblem
    username Apollo13
    icon_emoji :weary:
    color danger
    flush_interval 1s
    message "@channel\n message: %s\n app: [%s][%s][%s]\n time: %s\n hostname: %s\n raw: %s"
    message_keys log_msg,app,env,container_id,log_time,hostname,log

    time_key log_time

    buffer_type file
    buffer_path /fluentd/buffer/to_slack.*.buffer
    buffer_chunk_limit 10m
    buffer_queue_limit 32

    disable_retry_limit false
    retry_limit 60
    retry_wait 5s
    max_retry_wait 60s

    <parse>
    </parse>
    <format>
    </format>
  </match>

  <match debug_warn_to_slack.*.{watchpoint-ss-worker,watchpoint-dw-worker}>
    @type null
    <parse>
    </parse>
  </match>

  <match {debug_error_to_slack,debug_warn_to_slack}.**>
    @type slack
    webhook_url "#{ENV['SLACK_URL']}"
    parse none
    channel noproblem
    username Apollo13
    icon_emoji :weary:
    color danger
    flush_interval 1s
    message "@channel\n message: %s\n app: [%s][%s][%s]\n time: %s\n hostname: %s\n raw: %s"
    message_keys log_msg,app,env,container_id,log_time,hostname,log

    time_key log_time

    buffer_type file
    buffer_path /fluentd/buffer/debug_to_slack.*.buffer
    buffer_chunk_limit 10m
    buffer_queue_limit 32

    disable_retry_limit false
    retry_limit 60
    retry_wait 5s
    max_retry_wait 60s

    <parse>
    </parse>
    <format>
    </format>
  </match>

  <match **>
    @type elasticsearch
    host "#{ENV['ES_HOST']}"
    port "#{ENV['ES_PORT']}"

    logstash_format true
    logstash_prefix app-log
    type_name app-log
    time_key log_time
    remove_keys log_time

    buffer_type file
    buffer_path /fluentd/buffer/app-log.*.buffer
    buffer_chunk_limit 50m
    buffer_queue_limit 128
    flush_interval 2s
    num_threads 4
    reload_connections false
    request_timeout 40s

    disable_retry_limit false
    retry_limit 60
    retry_wait 5s
    max_retry_wait 60s
  </match>
</label>

<filter **>
  @type record_modifier
  <record>
    hostname "#{ENV['HOSTNAME']}"
  </record>
</filter>

<match **>
  @type elasticsearch
  host "#{ENV['ES_HOST']}"
  port "#{ENV['ES_PORT']}"

  logstash_format true
  logstash_prefix fluentd-log
  logstash_dateformat %Y
  type_name fluentd-log

  disable_retry_limit false
  retry_limit 60
  retry_wait 5s
  max_retry_wait 60s
  reload_connections false
</match>
```

### Logs
```
fluentd_old_1 | 2017-08-05 21:54:12 +0800 [warn]: section <parse> is not used in <match **> of elasticsearch plugin
fluentd_old_1 | 2017-08-05 21:54:13 +0800 [error]: #0 failed to purge buffer chunk chunk_id="555ea4ce9b0f9abb" error_class=Errno::ENOENT error=#<Errno::ENOENT: No such file or directory @ unlink_internal - /fluentd/buffer/app-log.normal.dev.watchpoint-ss-worker.q55
5ea4ce9b0f9abb.buffer.meta>
fluentd_old_1 |   2017-08-05 21:54:13 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin/buffer/file_chunk.rb:160:in `unlink'
fluentd_old_1 |   2017-08-05 21:54:13 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin/buffer/file_chunk.rb:160:in `purge'
fluentd_old_1 |   2017-08-05 21:54:13 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin/buffer.rb:403:in `block in purge_chunk'
fluentd_old_1 |   2017-08-05 21:54:13 +0800 [error]: #0 /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
fluentd_old_1 |   2017-08-05 21:54:13 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin/buffer.rb:395:in `purge_chunk'
fluentd_old_1 |   2017-08-05 21:54:13 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin/output.rb:934:in `commit_write'
fluentd_old_1 |   2017-08-05 21:54:13 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin/output.rb:1047:in `try_flush'
fluentd_old_1 |   2017-08-05 21:54:13 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin/output.rb:1268:in `flush_thread_run'
fluentd_old_1 |   2017-08-05 21:54:13 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin/output.rb:420:in `block (2 levels) in start'
fluentd_old_1 |   2017-08-05 21:54:13 +0800 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

Logs is forwarded by docker log driver.

**Comment by wzyplus** [comment]
Update to version 1.2.2 and works well.

**Comment by g3kr** [comment]
@wzyplus seeing the same error with fluentd version 1.14.2. Any thoughts why this might happen?
<img width="1466" alt="Screen Shot 2022-08-09 at 11 09 28 PM" src="https://user-images.githubusercontent.com/6721657/183802283-c211c7bc-bfa9-4d9e-8358-f5166c232367.png">

**Comment by karthiknagraj** [comment]
Seeing the same error in 1.13.2 as well.
