### ISSUE TITLE
fluentd-sender(0.14.20) become cpu 100% after fluentd-server down

### ISSUE THREAD

**Issue by bungoume** [fluent/fluentd#1665]
After the connection to the server is lost, the fluentd-sender CPU usage become 100%.
Even if the server is restored, CPU still sticks to max.

fluentd(sender) version: 0.14.20

![image](https://user-images.githubusercontent.com/507733/29460393-cb4b1da6-8462-11e7-9776-a378ece76437.png)
21:36 - server down
21:38 - server reovered

## fluentd sender config
https://github.com/bungoume/log-sender/blob/master/fluent.tmpl#L147-L168

**Comment by repeatedly** [comment]
Do you have reproducible step?
I tested destination shutdown on my Mac but forwarder's CPU is lower...

**Comment by GLStephen** [comment]
I've seen this behavior as well. The target server for a forwarder has a blip and then the sending server spikes and stays high CPU.

**Comment by repeatedly** [comment]
@GLStephen Could you tell me your setting and traffic?
I can't reproduce on my environment so I want to reproduce the problem first.

**Comment by bungoume** [comment]
It was reproduced when AWS CLB(ELB) was placed in front of the aggregator(server).

log sender -> ELB -> aggregator

when ELB->aggs connection was closed, 
sender seems to misunderstand that aggregator server has downed and recovered.
And, sender CPU will be 100%.

```
2017-08-28 10:03:15 +0000 [warn]: #0 [forward_any] destination node closed the connection. regard it as unavailable. host="log-aggregator.local" port=24224
2017-08-28 10:03:16 +0000 [warn]: #0 [forward_any] recovered forwarding server '' host="log-aggregator.local" port=24224
2017-08-28 10:03:16 +0000 [warn]: #0 [forward_any] destination node closed the connection. regard it as unavailable. host="log-aggregator.local" port=24224
2017-08-28 10:03:16 +0000 [warn]: #0 [forward_any] failed to flush the buffer. retry_time=1 next_retry_seconds=2017-08-28 10:03:17 +0000 chunk="557cd66b41ec2fe08ea752ca6ee2d50e" error_class=Fluent::Plugin::ForwardOutput::ConnectionClosedError error="failed to establish connection with node "
  2017-08-28 10:03:16 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-0.14.20/lib/fluent/plugin/out_forward.rb:606:in `send_data_actual'
  2017-08-28 10:03:16 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-0.14.20/lib/fluent/plugin/out_forward.rb:633:in `send_data'
  2017-08-28 10:03:16 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-0.14.20/lib/fluent/plugin/out_forward.rb:285:in `block in try_write'
  2017-08-28 10:03:16 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-0.14.20/lib/fluent/plugin/out_forward.rb:304:in `block in select_a_healthy_node'
  2017-08-28 10:03:16 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-0.14.20/lib/fluent/plugin/out_forward.rb:298:in `times'
  2017-08-28 10:03:16 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-0.14.20/lib/fluent/plugin/out_forward.rb:298:in `select_a_healthy_node'
  2017-08-28 10:03:16 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-0.14.20/lib/fluent/plugin/out_forward.rb:285:in `try_write'
  2017-08-28 10:03:16 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-0.14.20/lib/fluent/plugin/output.rb:1034:in `try_flush'
  2017-08-28 10:03:16 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-0.14.20/lib/fluent/plugin/output.rb:1268:in `flush_thread_run'
  2017-08-28 10:03:16 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-0.14.20/lib/fluent/plugin/output.rb:420:in `block (2 levels) in start'
  2017-08-28 10:03:16 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-0.14.20/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2017-08-28 10:03:16 +0000 [warn]: #0 [forward_any] recovered forwarding server '' host="log-aggregator.local" port=24224
2017-08-28 10:03:19 +0000 [warn]: #0 [forward_any] destination node closed the connection. regard it as unavailable. host="log-aggregator.local" port=24224
2017-08-28 10:03:19 +0000 [warn]: #0 [forward_any] destination node closed the connection. regard it as unavailable. host="log-aggregator.local" port=24224
2017-08-28 10:03:19 +0000 [warn]: #0 [forward_any] destination node closed the connection. regard it as unavailable. host="log-aggregator.local" port=24224
2017-08-28 10:03:19 +0000 [warn]: #0 [forward_any] destination node closed the connection. regard it as unavailable. host="log-aggregator.local" port=24224
2017-08-28 10:03:19 +0000 [warn]: #0 [forward_any] destination node closed the connection. regard it as unavailable. host="log-aggregator.local" port=24224
2017-08-28 10:03:19 +0000 [warn]: #0 [forward_any] destination node closed the connection. regard it as unavailable. host="log-aggregator.local" port=24224
2017-08-28 10:03:19 +0000 [warn]: #0 [forward_any] destination node closed the connection. regard it as unavailable. host="log-aggregator.local" port=24224
2017-08-28 10:03:19 +0000 [warn]: #0 [forward_any] destination node closed the connection. regard it as unavailable. host="log-aggregator.local" port=24224
2017-08-28 10:03:19 +0000 [warn]: #0 [forward_any] recovered forwarding server '' host="log-aggregator.local" port=24224
2017-08-28 10:03:20 +0000 [warn]: #0 [forward_any] destination node closed the connection. regard it as unavailable. host="log-aggregator.local" port=24224
2017-08-28 10:03:21 +0000 [warn]: #0 [forward_any] recovered forwarding server '' host="log-aggregator.local" port=24224
```

**Comment by GLStephen** [comment]
@repeatedly there are some aspects to our config I would prefer not to make public. What info do you need exactly? The basics are. We are using flowcounter to forward message counts every 15 seconds. Running about 1m messages a minute. We have also seen what appears to be deadlocking with 14 at these volumes.

**Comment by GLStephen** [comment]
@repeatedly more info is here, we are seeing this as related to the above, sending about 1m events/hour

https://github.com/kaizenplatform/fluent-plugin-bigquery/issues/143

**Comment by repeatedly** [comment]
@GLStephen Above link is for deadlock. Do you hit 100% CPU problem together?

**Comment by repeatedly** [comment]
@bungoume It means the problem doesn't happen without AWS CLB/ELB?

**Comment by GLStephen** [comment]
@repeatedly I've seen both happen together in a forwarding pair. Our aggregator, referenced above will deadlock and the downstream flowcounter metric server will do this 100% CPU thing like above.

**Comment by bungoume** [comment]
@repeatedly yes,
log-sender -> ELB connection was closed or 
log-aggregator downed only when log-sender directory connect,
the problem does not happen.

**Comment by repeatedly** [comment]
@GLStephen Thanks. I will fix deadlock issue first.

@bungoume So the ELB returns wrong response? I'm not familiar with ELB connection handling so I want to know what's the return in this situation.

**Comment by bungoume** [comment]
We collected logs. (fluentd log, ruby profile, and TCP dump)
[fluentd20170829.tar.gz](https://github.com/fluent/fluentd/files/1259199/fluentd20170829.tar.gz)

10.81.24.149: client (log-sender)
10.81.21.192: server (log-aggregator ELB)

### Normal case
![image](https://user-images.githubusercontent.com/507733/29805964-ae54de7c-8cc7-11e7-875b-4dc4d8acde90.png)

* client send message (No.7) and TCP-ACK(No.10)
* server returns software-ACK (No.12)
    ex: `ackVX21QxVErW1j597Kn12TZQ==` message
* FIN by client (No.16-18)

### Problem case
![image](https://user-images.githubusercontent.com/507733/29806165-bfa17874-8cc8-11e7-8c9a-7200c96f5043.png)

* client send message (No.538) and TCP-ACK(No.540)
* FIN by server (No.543-)

**Comment by repeatedly** [comment]
@bungoume Thanks!

@GLStephen One question. Do you forward logs between fluentd nodes directly? Not use ELB like bungoume, right?

**Comment by GLStephen** [comment]
@repeatedly Correct, we connect directly from the forwarder to the aggregator

**Comment by repeatedly** [comment]
@bungoume Could you get sigdump result from problematic fluentd instance?

**Comment by okkez** [comment]
@bungoume Could you try #1684 ?

**Comment by bungoume** [comment]
@repeatedly 
Add `require 'sigdump/setup'` at `/usr/bin/fluentd` and attach the executed log.
[sigdump(normal)-1549.txt](https://github.com/fluent/fluentd/files/1280563/sigdump.normal.-1549.txt)
[sigdump(cpu100)-267.txt (send SIGCONT twice)](https://github.com/fluent/fluentd/files/1280564/sigdump.cpu100.-267.txt)


I tried #1684 but it did not resolve.
![image](https://user-images.githubusercontent.com/507733/30105137-a07bf904-9332-11e7-8ad9-579999261a92.png)

**Comment by repeatedly** [comment]
@bungoume Thanks.
I wrote a patch for this problem. Could you test this? > https://github.com/fluent/fluentd/pull/1686

**Comment by bungoume** [comment]
@repeatedly Thank you!
The bug seems to have been fixed.

However, I get a lot of logs.
log:
[20170907T012240.txt](https://github.com/fluent/fluentd/files/1283242/20170907T012240.txt)

2017-09-07 01:20:08 Block ELB->log-agg connect
2017-09-07 01:21:40 Fix ELB->log-agg connect
2017-09-07 01:22:38 Stop fluentd

**Comment by repeatedly** [comment]
If you have lots of chunks, it seems normal because such logs are generated by each chunk.

**Comment by repeatedly** [comment]
I'm not sure this case is popular or not.
If there are lots of servers behind ELB, retried chunks are routed to live aggregators, right?

**Comment by bungoume** [comment]
Yes, it does not occur much.
However, it may be caused by log-aggregators deployment error or configuration bug.

It is fatal for all applications to die due to fluentd.

**Comment by repeatedly** [comment]
>  it may be caused by log-aggregators deployment error or configuration bug.

How to detect this by fluentd forwarder side?

**Comment by bungoume** [comment]
I think there is no need to distinguish it from network error.
Would you please reduce the amount of logs, including network errors?

**Comment by bungoume** [comment]
@repeatedly how is this issue?
This problem also occurred in using AWS-NLB and v0.14.23.

**Comment by bungoume** [comment]
@repeatedly Unfortunately, this problem has also reappeared on fluentd-1.0.0.rc1(Ruby 2.4.2)

**Comment by bungoume** [comment]
[fluent.txt](https://github.com/fluent/fluentd/files/1533579/fluent.txt)
This is the sender log when CPU reaches 100%.

**Comment by repeatedly** [comment]
Is this same situation or other network sequence?

**Comment by bungoume** [comment]
the last report is using NLB.
Occurs when log-aggregator stops due to Elasticsearch failure.

**Comment by nathan-oakes** [comment]
I have noticed this same issue, but not on all nodes. Config is using 1.0 (td-agent3): 
Within Datacenter: [td-agent in_tail, out_forward on nodes] -> [td-agent in_forward, out_forward on "Forwarder"] -> Within AWS VPC over IPSEC tunnel [in_forward, out_elasticsearch and out_s3 on Aggregator].
