### ISSUE TITLE
fluentd-0.12 cannot load plugin which contains native extension

### ISSUE THREAD

**Issue by codeout** [fluent/fluentd#1668]
I wrote [fluent-plugin-sflow](https://github.com/codeout/fluent-plugin-sflow) which contains a native extension, but fluentd-0.12 cannot load it and says:

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo /etc/init.d/td-agent restart
Restarting td-agent: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sflow-0.1.0//opt/td-agent/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/fluent-plugin-sflow-0.1.0/fluent/plugin/in_sflow (LoadError)
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:172:in `block in try_load_plugin'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:170:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:170:in `try_load_plugin'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:130:in `new_impl'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:55:in `new_input'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:154:in `add_source'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:95:in `block in configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:92:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:92:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:129:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:103:in `run_configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:489:in `run_configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:200:in `dry_run'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:147:in `start'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/bin/fluentd:5:in `<top (required)>'
	from /opt/td-agent/embedded/bin/fluentd:23:in `load'
	from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
	from /usr/sbin/td-agent:7:in `load'
	from /usr/sbin/td-agent:7:in `<main>'
 * td-agent
```

The plugin provides ```in_sflow.rb``` which requires a native extension in there.

```
# fluent-plugin-sflow.gemspec

Gem::Specification.new do |spec|
...
  spec.require_paths = ["lib"]
  spec.extensions    = ["ext/sflowtool/extconf.rb"]
```

This is probably due to ```require_paths order``` in fluent/plugin.rb:

```ruby
    137     def try_load_plugin(name, type)
...
    167       # prefer newer version
    168       specs = specs.sort_by { |spec| spec.version }
    169       if spec = specs.last
    170         spec.require_paths.each { |lib|
    171           file = "#{spec.full_gem_path}/#{lib}/#{path}"
    172           require file                                       # this raises
    173         }
    174       end
```

```spec.require_paths``` would be
```
["/opt/td-agent/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/fluent-plugin-sflow-0.1.0", "lib"]
```
and tries

```
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sflow-0.1.0//opt/td-agent/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/fluent-plugin-sflow-0.1.0/fluent/plugin/in_sflow
```

first, though it's located in

```
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sflow-0.1.0/lib/fluent/plugin/
```

so fails.

## Configuration

My configuration looks like:

```
# /etc/td-agent/td-agent.conf

<source>
  @type sflow
  tag sflow.event
</source>

<match sflow.event>
  @type elasticsearch
  type_name sflow
  logstash_format true
  logstash_prefix flow
</match>
```

## Patch?

Confirmed that plugin loader worked with a patch as below, but I have no idea whether it's straightforward or not.

```diff
      # prefer newer version
      specs = specs.sort_by { |spec| spec.version }
      if spec = specs.last
        spec.require_paths.each { |lib|
          file = "#{spec.full_gem_path}/#{lib}/#{path}"
-          require file
+          require file if File.exist?("#{file}.rb")
        }
      end
```

## Note

:warning: My fluent-plugin is another implementation of published version of fluent-plugin-sflow, it's not available as a gem yet. Installed like this:

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo td-agent-gem install specific_install
Successfully installed specific_install-0.3.3
Parsing documentation for specific_install-0.3.3
Done installing documentation for specific_install after 0 seconds
1 gem installed

vagrant@vagrant-ubuntu-trusty-64:~$ sudo td-agent-gem specific_install https://github.com/codeout/fluent-plugin-sflow.
git
/usr/bin/git
git installing from https://github.com/codeout/fluent-plugin-sflow.git
Cloning into '/tmp/d20170822-10454-wyle75'...
remote: Counting objects: 159, done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 159 (delta 64), reused 155 (delta 63), pack-reused 0
Receiving objects: 100% (159/159), 86.04 KiB | 0 bytes/s, done.
Resolving deltas: 100% (64/64), done.
Checking connectivity... done.
WARNING:  licenses is empty, but is recommended.  Use a license abbreviation from:
http://opensource.org/licenses/alphabetical
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: fluent-plugin-sflow
  Version: 0.1.0
  File: fluent-plugin-sflow-0.1.0.gem
Building native extensions.  This could take a while...
Successfully installed
```

## My environment

- fluentd or td-agent version.
  - td-agent 2.3.5-0 (fluentd 0.12.35)
  - which is installed by [official instruction](https://docs.fluentd.org/v0.12/articles/install-by-deb)
- Environment information, e.g. OS.
  - Ubuntu 14.04.3 (64bit)

**Comment by repeatedly** [comment]
Does this happen with fleuntd v0.14?
I'm not sure why `spec.require_paths` generates such verbose path but your changes seems good for me.

**Comment by codeout** [comment]
No problem at all with v0.14.

After quick look into the code, fortunately I found the same ```if``` condition there 😄 

```ruby
# lib/fluent/registry.rb

 98       if spec = specs.last
 99         spec.require_paths.each { |lib|                   # returns the same verbose paths as v0.12
100           file = "#{spec.full_gem_path}/#{lib}/#{path}"
101           if File.exist?("#{file}.rb")                    # good
102             require file
103             return
104           end
105         }
106       end
```

So should I open PR for v0.12 ?

**Comment by repeatedly** [comment]
Ah, I see.

> So should I open PR for v0.12 ?

Yes, please :)

**Comment by codeout** [comment]
The PR has been merged. Thanks!
