### ISSUE TITLE
fluentd gives unexcepted error when sending SIGHUP signal

### ISSUE THREAD

**Issue by mikkohoo** [fluent/fluentd#1674]
Following scenario was tested with official 0.14.19 and 0.14.20 fluentd docker images.

**Description:**
We have used SIGHUP signal to reload configuration each time our configuration changes. This has been working perfectly in our use case until 0.14.20. Apparently something has been changed in 0.14.20 since now we get following error each time we send SIGHUP signal to fluentd process.
```
2017-08-29 06:16:25 +0000 [error]: #0 unexpected error error_class=SignalException error="SIGHUP"
  2017-08-29 06:16:25 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/engine.rb:228:in `sleep'
  2017-08-29 06:16:25 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/engine.rb:228:in `run'
  2017-08-29 06:16:25 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/supervisor.rb:772:in `run_engine'
  2017-08-29 06:16:25 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/supervisor.rb:521:in `block in run_worker'
  2017-08-29 06:16:25 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/supervisor.rb:697:in `main_process'
  2017-08-29 06:16:25 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/supervisor.rb:516:in `run_worker'
  2017-08-29 06:16:25 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2017-08-29 06:16:25 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-08-29 06:16:25 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-08-29 06:16:25 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/bin/fluentd:5:in `<top (required)>'
  2017-08-29 06:16:25 +0000 [error]: #0 /usr/bin/fluentd:22:in `load'
  2017-08-29 06:16:25 +0000 [error]: #0 /usr/bin/fluentd:22:in `<main>'
```
**How to reproduce:**
```
docker run -d --name signal_test fluent/fluentd:v0.14.20
docker kill -s "SIGHUP" signal_test
docker logs signal_test
```
[Complete log](https://gist.github.com/mikkohoo/cb56c5d443f171bc1d0b7706cf5e667d)

**Comment by repeatedly** [comment]
We recently changed the signal handling of docker image: https://github.com/fluent/fluentd-docker-image/pull/93

Could you check this is the cause or not?
We didn't change fluentd internal signal handling recently.

**Comment by kkurten** [comment]
I did some quick debugging to find the root cause of the issue (I work in the same team as mikkohoo). The dump-init sends the SIGHUP signal correctly to Fluentd supervisor so that part seems to work fine. However, I noticed couple issues in the signal handling code that seem to cause the issue.

- https://github.com/fluent/fluentd/blob/master/lib/fluent/engine.rb#L231 was changed at some point to catch all Exceptions. Problem is that it also catches the SignalException so the worker does not get properly shutdown.
- When Fluentd supervisor receives SIGHUP the kill_worker function (https://github.com/fluent/fluentd/blob/master/lib/fluent/supervisor.rb#L174 ) gets called and it kills all the worker processes. However, it seems that when a worker is killed the PID of the worker is not removed from config[:worker_pid] array. When you send another SIGHUP it always fails because supervisor tries to kill a worker process that no longer exists and you get an "Unexpected error No such process" error.

Note that I'm not familiar with Fluentd codebase and I also rarely do any Ruby programming so take the above with grain of salt. :)

**Comment by repeatedly** [comment]
I see. Thanks for further investigation.
So does adding `--single-child` to this line fix the problem?
https://github.com/fluent/fluentd-docker-image/blob/943ce25fa978a8933947fe2c62b89bf9dc461d17/entrypoint.sh.erb#L2

**Comment by kkurten** [comment]
I think the entrypoint script will break down if the parameter is added to the shebang line because parameter handling is a bit weird in shebang lines. It would probably be cleaner to add `ENV DUMB_INIT_SETSID=0` to Dockerfile. This would have the same effect than adding --single-child parameter to the shebang.

This change would fix the dumb-init issue but not the config[:worker_pid] cleanup issue in supervisor implementation. It is easy to reproduce by sending SIGHUP twice to Fluentd . You should always get the "Unexpected error No such process" error after sending the second SIGHUP. 

Older Fluentd versions (like 0.14.15) probably work because the config[:worker_pid] was a single value, not an array. When supervisor received the SIGHUP it killed the old worker and overwrote config[:worker_pid] with the new worker PID. In this commit https://github.com/fluent/fluentd/commit/ed5f0cbfdba74a9033cc771cef1b6fa0c187579d the config[:worker_pid] was changed to array but nothing seems to remove the worker PID from array when worker is killed.

**Comment by repeatedly** [comment]
Patch for this issue:
- https://github.com/fluent/fluentd/pull/1683
- https://github.com/fluent/fluentd-docker-image/pull/95

**Comment by repeatedly** [comment]
Build new fluentd images with above 2 patch.
Try it!

**Comment by mikkohoo** [comment]
Working as expect, good job!
