### ISSUE TITLE
`require': cannot load such file -- rmodbus (LoadError) !!!	

### ISSUE THREAD

**Issue by sankujain** [fluent/fluentd#1676]
Hello,

We are using td-agent 0.14 and we are trying to implement modbus tcp/ip input plugin for fluentd
This is the plugin we are referring:
`
https://github.com/iomz/fluent-plugin-modbus
`
Initially it was working fine but now it is giving error as::
```

2017-08-29 14:02:28 +0530 [info]: reading config file path="modbus.conf"
2017-08-29 14:02:28 +0530 [info]: starting fluentd-0.14.16 as dry run mode
/opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rmodbus (LoadError)
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /etc/td-agent/plugin/in_modbus.rb:2:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/registry.rb:68:in `search'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/registry.rb:44:in `lookup'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/plugin.rb:146:in `new_impl'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/plugin.rb:100:in `new_input'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/root_agent.rb:265:in `add_source'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/root_agent.rb:119:in `block in configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/root_agent.rb:115:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/root_agent.rb:115:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/engine.rb:127:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/engine.rb:92:in `run_configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/supervisor.rb:733:in `run_configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/supervisor.rb:521:in `dry_run'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/supervisor.rb:460:in `run_supervisor'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.16/bin/fluentd:5:in `<top (required)>'
	from /opt/td-agent/embedded/bin/fluentd:22:in `load'
	from /opt/td-agent/embedded/bin/fluentd:22:in `<top (required)>'
	from /usr/sbin/td-agent:7:in `load'
	from /usr/sbin/td-agent:7:in `<main>'
root@sanku:

```

The configuration file is :

```
<source>
    @type modbus
    tag modbus.sensor1     # An unique sensor name following 'modbus.'
    host 127.0.0.1 # ModBus host
    port 5565               # ModBus port
    polling_time 0,30      # Poll data at seconds separated by colons
    modbus_retry 1         # Retry counts for TCP connection to ModBus host
    reg_size 16            # Register size of ModBus I/O device in bit
    reg_addr 0             # Address of the register to read
    nregs 1                # Number of sequential registers to read [1-2]
</source>

```

We have successfully installed the gem and bundle it.

```
root@sanku:/etc/td-agent/plugin/fluent-plugin-modbus# bundle show rmodbus
/var/lib/gems/2.3.0/gems/rmodbus-1.3.3

```

Can you enlighten us where we are doing wrong?

**Comment by repeatedly** [comment]
See: https://docs.fluentd.org/v0.12/articles/faq#i-installed-td-agent-and-want-to-add-custom-plugins-how-do-i-do-it and https://docs.fluentd.org/v0.12/articles/plugin-management first.

> /var/lib/gems/2.3.0/gems/rmodbus-1.3.3

Is not td-agent's ruby directory. This is why you got this error.

And please follow the guideline: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
Next we will close without comment.

**Comment by sankujain** [comment]
Thank you for prompt response.
