### ISSUE TITLE
concat multiline issue

### ISSUE THREAD

**Issue by Evertvz** [fluent/fluentd#1693]
Hello,

I have checked this in the documentation, asked the question on slack, asked the question in the mailing list and got no answers so I'm starting to assume this is a bug.

- fluentd or td-agent version.
-> docker image fluent/fluentd:v0.12-onbuild
- Environment information, e.g. OS.
-> ubuntu
- The configuration
```
<filter *.**>
  @type concat
  key log
  stream_identity_key container_id
  multiline_start_regexp /^(?<Exception>[a-zA-z_]*\..*\..*\..*Exception)/
  continuous_line_regexp /Caused\sby:|\s+at\s.*|\s+ \.\.\. (\d)+ more/
  flush_interval 60
</filter>
```
- The problem
I'm trying to assemble the lines of a stack trace. The first 25 lines work fine, the 26th line gets cut off altough the regex matches when tested elsewhere.

Here is an example stack trace
```
com.orbitz.consul.ConsulException: Consul request failed
        at com.orbitz.consul.util.Http.extractConsulResponse(Http.java:54)
        at com.orbitz.consul.HealthClient.getChecksByState(HealthClient.java:241)
        at com.orbitz.consul.HealthClient.getChecksByState(HealthClient.java:225)
        at be.mdcpartners.webbalancer.consul.ConsulBasedApplicationManager$Updater.run(ConsulBasedApplicationManager.java:85)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: timeout
        at com.orbitz.okio.Okio$3.newTimeoutException(Okio.java:212)
        at com.orbitz.okio.AsyncTimeout.exit(AsyncTimeout.java:288)
        at com.orbitz.okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
        at com.orbitz.okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
        at com.orbitz.okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
        at com.orbitz.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
        at com.orbitz.okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
        at com.orbitz.okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
        at com.orbitz.okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
        at com.orbitz.okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
        at com.orbitz.okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
        at com.orbitz.okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
        at com.orbitz.okhttp3.RealCall.getResponse(RealCall.java:244)
        at com.orbitz.okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
        at com.orbitz.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
        at com.orbitz.okhttp3.RealCall.execute(RealCall.java:57)
        at com.orbitz.retrofit.OkHttpCall.execute(OkHttpCall.java:174)
        at com.orbitz.consul.util.Http.extractConsulResponse(Http.java:52)
        ... 4 more
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:204)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at com.orbitz.okio.Okio$2.read(Okio.java:140)
        at com.orbitz.okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
        ... 19 more
```

This is a copy-paste of a result, as you can see only the first 25 lines are grouped together.
```
com.orbitz.consul.ConsulException: Consul request failed 
	at com.orbitz.consul.util.Http.extractConsulResponse(Http.java:54) 
	at com.orbitz.consul.HealthClient.getChecksByState(HealthClient.java:241) 
	at com.orbitz.consul.HealthClient.getChecksByState(HealthClient.java:225) 
	at be.mdcpartners.webbalancer.consul.ConsulBasedApplicationManager$Updater.run(ConsulBasedApplicationManager.java:85) 
	at java.lang.Thread.run(Thread.java:748) 
Caused by: java.net.SocketTimeoutException: timeout 
	at com.orbitz.okio.Okio$3.newTimeoutException(Okio.java:212) 
	at com.orbitz.okio.AsyncTimeout.exit(AsyncTimeout.java:288) 
	at com.orbitz.okio.AsyncTimeout$2.read(AsyncTimeout.java:242) 
	at com.orbitz.okio.RealBufferedSource.indexOf(RealBufferedSource.java:325) 
	at com.orbitz.okio.RealBufferedSource.indexOf(RealBufferedSource.java:314) 
	at com.orbitz.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210) 
	at com.orbitz.okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184) 
	at com.orbitz.okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125) 
	at com.orbitz.okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775) 
	at com.orbitz.okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86) 
	at com.orbitz.okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760) 
	at com.orbitz.okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613) 
	at com.orbitz.okhttp3.RealCall.getResponse(RealCall.java:244) 
	at com.orbitz.okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201) 
	at com.orbitz.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163) 
	at com.orbitz.okhttp3.RealCall.execute(RealCall.java:57) 
	at com.orbitz.retrofit.OkHttpCall.execute(OkHttpCall.java:174) 
	at com.orbitz.consul.util.Http.extractConsulResponse(Http.java:52) 
```

This is a separate message
```
	... 4 more 
```

At first sight this looks like an easy to solve problem but after validating the regex in regex101, asking the question in slack and the mailinglist I don't see why this should not be working. I haven't seen any cutoff limit in the documentation either.

**Comment by okkez** [comment]
@Evertvz This is not Fluentd's issue. This is a question about fluent-plugin-concat usage.
You should create an issue on https://github.com/fluent-plugins-nursery/fluent-plugin-concat/issues
Could you close this issue and create new issue on https://github.com/fluent-plugins-nursery/fluent-plugin-concat/issues ?

**Comment by Evertvz** [comment]
ok will do, apologies.

**Comment by ErandikaH** [comment]
@Evertvz Do you find a solution for this issue?

**Comment by Evertvz** [comment]
Hello,

To be honest I do not remember since this was such a long time ago.

Best regards,
Evert
