### ISSUE TITLE
out_file/buffer plugin bug: dynamically set path

### ISSUE THREAD

**Issue by rahulwa** [fluent/fluentd#1755]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
td-agent 0.14.23

- Environment information, e.g. OS.
Ubuntu 16.04 OS

- Your configuration

```
<system>
  log_level debug
</system>

<source>
  type forward
  port 24224
</source>

<match stage-app.**>
    @type file
      path /home/alpha/apps/${tag[1]}/current/log/staging
      compress gzip
      append true
      <buffer tag >
        timekey_use_utc
        timekey 1d
        timekey_wait 10m
      </buffer>
</match>
```

- Your problem explanation. If you have an error logs, write it together.

Even though i am setting up `path` dynamically but it tries to resolve path variable at startup and tries to verify. Below td-agent.log

```
2017-11-17 12:56:57 +0000 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2017-11-17 12:56:57 +0000 [error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="out_file: `/home/alpha/apps//current/log/staging.log.gz` is not writable"
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/plugin/out_file.rb:147:in `configure'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/plugin.rb:164:in `configure'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/agent.rb:130:in `add_match'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/agent.rb:72:in `block in configure'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/agent.rb:64:in `each'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/agent.rb:64:in `configure'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/root_agent.rb:112:in `configure'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/engine.rb:131:in `configure'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/engine.rb:96:in `run_configure'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/supervisor.rb:770:in `run_configure'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/supervisor.rb:553:in `dry_run'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/supervisor.rb:571:in `supervise'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/supervisor.rb:476:in `run_supervisor'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.23/bin/fluentd:5:in `<top (required)>'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2017-11-17 12:56:57 +0000 [debug]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2017-11-17 12:56:57 +0000 [debug]: /usr/sbin/td-agent:7:in `load'
  2017-11-17 12:56:57 +0000 [debug]: /usr/sbin/td-agent:7:in `<main>'
```

**Comment by repeatedly** [comment]
Does td-agent(fluentd) have write permission of `/home/alpha/apps/`?

**Comment by rahulwa** [comment]
Thank you very much. It works after giving write permission. 
Btw td-agent already had write permission on log (`/home/alpha/apps/*/current/log/`) directory.
I was using forest plugin on 0.12 and it didn't use to check permission this explicitly.

**Comment by rahulwa** [comment]
I just noticed that td-agent creates file even upon using dynamic tagging in path.

```
tree \$\{tag\[1\]\}
${tag[1]}
└── current
    └── log
        └── staging
```

```
2017-11-22 12:53:23 +0000 [info]: fluent/log.rb:316:call: Received graceful stop
2017-11-22 12:53:24 +0000 [debug]: #0 fluentd main process get SIGTERM
2017-11-22 12:53:24 +0000 [debug]: #0 getting start to shutdown main process
2017-11-22 12:53:24 +0000 [info]: #0 fluentd worker is now stopping worker=0
2017-11-22 12:53:24 +0000 [info]: #0 shutting down fluentd worker worker=0
2017-11-22 12:53:24 +0000 [debug]: #0 calling stop on input plugin type=:forward plugin_id="object:3fd295583764"
2017-11-22 12:53:24 +0000 [debug]: #0 calling stop on output plugin type=:copy plugin_id="object:3fd2959f3790"
2017-11-22 12:53:24 +0000 [debug]: #0 calling stop on output plugin type=:elasticsearch plugin_id="object:3fd295e41608"
2017-11-22 12:53:24 +0000 [debug]: #0 calling stop on output plugin type=:file plugin_id="object:3fd29597a278"
2017-11-22 12:53:24 +0000 [debug]: #0 preparing shutdown input plugin type=:forward plugin_id="object:3fd295583764"
2017-11-22 12:53:24 +0000 [debug]: #0 preparing shutdown output plugin type=:elasticsearch plugin_id="object:3fd295e41608"
2017-11-22 12:53:24 +0000 [debug]: #0 preparing shutdown output plugin type=:copy plugin_id="object:3fd2959f3790"
2017-11-22 12:53:24 +0000 [debug]: #0 preparing shutdown output plugin type=:file plugin_id="object:3fd29597a278"
2017-11-22 12:53:24 +0000 [info]: #0 shutting down input plugin type=:forward plugin_id="object:3fd295583764"
2017-11-22 12:53:24 +0000 [info]: #0 shutting down output plugin type=:copy plugin_id="object:3fd2959f3790"
2017-11-22 12:53:24 +0000 [info]: #0 shutting down output plugin type=:elasticsearch plugin_id="object:3fd295e41608"
2017-11-22 12:53:24 +0000 [info]: #0 shutting down output plugin type=:file plugin_id="object:3fd29597a278"
2017-11-22 12:53:24 +0000 [debug]: #0 calling after_shutdown on input plugin type=:forward plugin_id="object:3fd295583764"
2017-11-22 12:53:24 +0000 [debug]: #0 calling after_shutdown on output plugin type=:copy plugin_id="object:3fd2959f3790"
2017-11-22 12:53:24 +0000 [debug]: #0 calling after_shutdown on output plugin type=:elasticsearch plugin_id="object:3fd295e41608"
2017-11-22 12:53:24 +0000 [debug]: #0 calling after_shutdown on output plugin type=:file plugin_id="object:3fd29597a278"
2017-11-22 12:53:24 +0000 [debug]: #0 closing input plugin type=:forward plugin_id="object:3fd295583764"
2017-11-22 12:53:24 +0000 [debug]: #0 closing output plugin type=:elasticsearch plugin_id="object:3fd295e41608"
2017-11-22 12:53:24 +0000 [debug]: #0 closing buffer instance=70173717519240
2017-11-22 12:53:24 +0000 [debug]: #0 closing output plugin type=:copy plugin_id="object:3fd2959f3790"
2017-11-22 12:53:24 +0000 [debug]: #0 closing output plugin type=:file plugin_id="object:3fd29597a278"
2017-11-22 12:53:24 +0000 [debug]: #0 closing buffer instance=70173691104920
2017-11-22 12:53:24 +0000 [debug]: #0 calling terminate on input plugin type=:forward plugin_id="object:3fd295583764"
2017-11-22 12:53:24 +0000 [debug]: #0 calling terminate on output plugin type=:copy plugin_id="object:3fd2959f3790"
2017-11-22 12:53:24 +0000 [debug]: #0 calling terminate on output plugin type=:elasticsearch plugin_id="object:3fd295e41608"
2017-11-22 12:53:24 +0000 [debug]: #0 calling terminate on output plugin type=:file plugin_id="object:3fd29597a278"
2017-11-22 12:53:24 +0000 [info]: fluent/log.rb:316:call: Worker 0 finished with status 0
2017-11-22 12:53:25 +0000 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2017-11-22 12:53:25 +0000 [warn]: 'type' is deprecated parameter name. use '@type' instead.
2017-11-22 12:53:25 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level debug
  </system>
  <source>
    type forward
    port 24224
  </source>
  <match stage-app.**>
    @type file
    path "/home/alpha/apps/${tag[1]}/current/log/staging"
    compress gzip
    append true
    <buffer tag>
      timekey 1d
      timekey_use_utc true
      timekey_wait 10m
      path "/home/alpha/apps/${tag[1]}/current/log/staging"
    </buffer>
  </match>
</ROOT>
2017-11-22 12:53:25 +0000 [info]: starting fluentd-0.14.23 pid=8509 ruby="2.1.10"
2017-11-22 12:53:25 +0000 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/sbin/td-agent", "--log", "/var/log/td-agent/td-agent.log", "--daemon", "/var/run/td-agent/td-agent.pid", "--under-supervisor"]
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.1.1'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.0.0'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.10.2'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-forest' version '0.3.3'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-kafka' version '0.6.1'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-mongo' version '0.8.1'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-record-modifier' version '0.6.0'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.6'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-s3' version '0.8.5'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-td' version '0.10.29'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.3'
2017-11-22 12:53:26 +0000 [info]: gem 'fluent-plugin-webhdfs' version '0.7.1'
2017-11-22 12:53:26 +0000 [info]: gem 'fluentd' version '0.14.23'
2017-11-22 12:53:26 +0000 [info]: gem 'fluentd' version '0.12.40'
2017-11-22 12:53:26 +0000 [info]: adding match pattern="stage-app.**" type="file"
2017-11-22 12:53:26 +0000 [warn]: #0 'type' is deprecated parameter name. use '@type' instead.
2017-11-22 12:53:26 +0000 [info]: adding source type="forward"
2017-11-22 12:53:26 +0000 [info]: #0 starting fluentd worker pid=8519 ppid=8514 worker=0
2017-11-22 12:53:26 +0000 [debug]: #0 buffer started instance=69913801912940 stage_size=0 queue_size=0
2017-11-22 12:53:26 +0000 [info]: #0 listening port port=24224 bind="0.0.0.0"
2017-11-22 12:53:26 +0000 [debug]: #0 enqueue_thread actually running
2017-11-22 12:53:26 +0000 [info]: #0 fluentd worker is now running worker=0
2017-11-22 12:53:26 +0000 [debug]: #0 flush_thread actually running
```

**Comment by repeatedly** [comment]
> I just noticed that td-agent creates file even upon using dynamic tagging in path.

Yes because placeholder is processed during buffer chunk flush.
We can embed actual value at buffering phase but it has large performance penalty.

**Comment by rahulwa** [comment]
@repeatedly Good to know. I was thinking that it might be unexpected behaviour.
