### ISSUE TITLE
secondary_file output not working

### ISSUE THREAD

**Issue by gabfl** [fluent/fluentd#1822]
- Issue summary:

I added a `<secondary>` node with the type `type secondary_file`.

It is my understanding that once the main node in `<server>` is not available anymore, Fluentd should output everything to the `secondary_file`. This is not happening.

- fluentd or td-agent version.

```bash
$ td-agent --version
td-agent 1.0.2
```

- Environment information, e.g. OS.

```bash
$ uname -a
Linux ip-10-0-0-148 3.13.0-139-generic #188-Ubuntu SMP Tue Jan 9 14:43:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

- Your configuration

```
# Monitor agent
<source>
  @type monitor_agent
  bind 127.0.0.1
  port 24220
</source>

<match forwardme.**>
  # @type stdout

  @type forward
  send_timeout 60s
  recover_wait 10s
  heartbeat_type tcp
  heartbeat_interval 1s
  phi_threshold 16
  hard_timeout 60s

  <buffer time,tag,message>
    type memory
    timekey 2s
    timekey_wait 1s
    flush_interval 1s
  </buffer>

  <server>
      name ****
      host ****
      port 24224
      weight 60
  </server>

  <secondary>
    type secondary_file
    directory /var/log/td-agent/
    basename failed
  </secondary>
</match>

## built-in TCP input
## @see http://docs.fluentd.org/articles/in_forward
<source>
  @type forward
</source>

# HTTP input
# POST http://localhost:8888/<tag>?json=<json>
# POST http://localhost:8888/td.myapp.login?json={"user"%3A"me"}
# @see http://docs.fluentd.org/articles/in_http
<source>
  @type http
  port 8888
</source>

## live debugging agent
<source>
  @type debug_agent
  bind 127.0.0.1
  port 24230
</source>
```

- Your problem explanation. If you have an error logs, write it together.

It is my understanding that after the following log event:
```
2018-01-17 14:30:51 -0500 [info]: #0 fluentd worker is now running worker=0
2018-01-17 14:32:59 -0500 [warn]: #0 detached forwarding server '****' host="****" port=24224 hard_timeout=true
```

inputs should be forwarded to the `secondary_file` type and I should not get the following:

```
2018-01-17 14:33:15 -0500 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-01-17 14:33:15 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 14:33:15 -0500 [warn]: #0 suppressed same stacktrace
```

Full logs:

```
2018-01-17 14:30:50 -0500 [info]: starting fluentd-1.0.2 pid=8372 ruby="2.4.2"
2018-01-17 14:30:50 -0500 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/sbin/td-agent", "--log", "/var/log/td-agent/td-agent.log", "--daemon", "/var/run/td-agent/td-agent.pid", "--under-supervisor"]
2018-01-17 14:30:51 -0500 [info]: gem 'fluent-plugin-elasticsearch' version '2.4.0'
2018-01-17 14:30:51 -0500 [info]: gem 'fluent-plugin-kafka' version '0.6.5'
2018-01-17 14:30:51 -0500 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.0.1'
2018-01-17 14:30:51 -0500 [info]: gem 'fluent-plugin-s3' version '1.1.0'
2018-01-17 14:30:51 -0500 [info]: gem 'fluent-plugin-td' version '1.0.0'
2018-01-17 14:30:51 -0500 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.3'
2018-01-17 14:30:51 -0500 [info]: gem 'fluent-plugin-webhdfs' version '1.2.2'
2018-01-17 14:30:51 -0500 [info]: gem 'fluentd' version '1.0.2'
2018-01-17 14:30:51 -0500 [info]: adding match pattern="td.*.*" type="tdlog"
2018-01-17 14:30:51 -0500 [info]: adding match pattern="debug.**" type="stdout"
2018-01-17 14:30:51 -0500 [info]: adding match pattern="forwardme.**" type="forward"
2018-01-17 14:30:51 -0500 [warn]: #0 'flush_interval' is ignored because default 'flush_mode' is not 'interval': 'lazy'
2018-01-17 14:30:51 -0500 [warn]: #0 'heartbeat_type tcp' is deprecated. use 'transport' instead.
2018-01-17 14:30:51 -0500 [info]: #0 adding forwarding server '****' host="****" port=24224 weight=60 plugin_id="object:3fac707cf1e4"
2018-01-17 14:30:51 -0500 [info]: adding source type="monitor_agent"
2018-01-17 14:30:51 -0500 [info]: adding source type="forward"
2018-01-17 14:30:51 -0500 [info]: adding source type="http"
2018-01-17 14:30:51 -0500 [info]: adding source type="debug_agent"
2018-01-17 14:30:51 -0500 [info]: #0 starting fluentd worker pid=8382 ppid=8377 worker=0
2018-01-17 14:30:51 -0500 [info]: #0 delayed_commit_timeout is overwritten by ack_response_timeout
2018-01-17 14:30:51 -0500 [info]: #0 listening dRuby uri="druby://127.0.0.1:24230" object="Fluent::Engine"
2018-01-17 14:30:51 -0500 [info]: #0 listening port port=24224 bind="0.0.0.0"
2018-01-17 14:30:51 -0500 [info]: #0 fluentd worker is now running worker=0
2018-01-17 14:32:59 -0500 [warn]: #0 detached forwarding server '****' host="****" port=24224 hard_timeout=true
2018-01-17 14:33:13 -0500 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-01-17 14:33:14 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Errno::ETIMEDOUT error="Connection timed out - connect(2) for \"*****\" port 24224"
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/socket.rb:59:in `initialize'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/socket.rb:59:in `new'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/socket.rb:59:in `socket_create_tcp'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:334:in `create_transfer_socket'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:633:in `send_data'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:269:in `block in write'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:304:in `block in select_a_healthy_node'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:298:in `times'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:298:in `select_a_healthy_node'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:269:in `write'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-01-17 14:33:13 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-01-17 14:33:14 -0500 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-01-17 14:33:14 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 14:33:14 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:313:in `select_a_healthy_node'
  2018-01-17 14:33:14 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:269:in `write'
  2018-01-17 14:33:14 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
  2018-01-17 14:33:14 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
  2018-01-17 14:33:14 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-01-17 14:33:14 -0500 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-01-17 14:33:15 -0500 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-01-17 14:33:15 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 14:33:15 -0500 [warn]: #0 suppressed same stacktrace
2018-01-17 14:33:17 -0500 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2018-01-17 14:33:17 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 14:33:17 -0500 [warn]: #0 suppressed same stacktrace
2018-01-17 14:33:21 -0500 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2018-01-17 14:33:21 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 14:33:21 -0500 [warn]: #0 suppressed same stacktrace
2018-01-17 14:33:30 -0500 [warn]: #0 failed to flush the buffer. retry_time=4 next_retry_seconds=2018-01-17 14:33:30 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 14:33:30 -0500 [warn]: #0 suppressed same stacktrace
2018-01-17 14:33:45 -0500 [warn]: #0 failed to flush the buffer. retry_time=5 next_retry_seconds=2018-01-17 14:33:45 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 14:33:45 -0500 [warn]: #0 suppressed same stacktrace
2018-01-17 14:34:14 -0500 [warn]: #0 failed to flush the buffer. retry_time=6 next_retry_seconds=2018-01-17 14:34:14 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 14:34:14 -0500 [warn]: #0 suppressed same stacktrace
2018-01-17 14:35:25 -0500 [warn]: #0 failed to flush the buffer. retry_time=7 next_retry_seconds=2018-01-17 14:35:25 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 14:35:25 -0500 [warn]: #0 suppressed same stacktrace
2018-01-17 14:37:34 -0500 [warn]: #0 failed to flush the buffer. retry_time=8 next_retry_seconds=2018-01-17 14:37:34 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 14:37:34 -0500 [warn]: #0 suppressed same stacktrace
2018-01-17 14:42:12 -0500 [warn]: #0 failed to flush the buffer. retry_time=9 next_retry_seconds=2018-01-17 14:42:12 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 14:42:12 -0500 [warn]: #0 suppressed same stacktrace
2018-01-17 14:50:48 -0500 [warn]: #0 failed to flush the buffer. retry_time=10 next_retry_seconds=2018-01-17 14:50:48 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 14:50:48 -0500 [warn]: #0 suppressed same stacktrace
2018-01-17 15:07:53 -0500 [warn]: #0 failed to flush the buffer. retry_time=11 next_retry_seconds=2018-01-17 15:07:53 -0500 chunk="562fde33c70e8191005fc3cdbbf4ae89" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
  2018-01-17 15:07:53 -0500 [warn]: #0 suppressed same stacktrace
root@:~# 

```

**Comment by repeatedly** [comment]
Checking the behaviour.

**Comment by gabfl** [comment]
@repeatedly Thanks. Just so you know I staged an Ubuntu 16.04 instance yesterday, just installed Fluentd, used the example available on https://github.com/fluent/fluentd/blob/master/example/secondary_file.conf and the behavior was the same as described above.

**Comment by kasiprasad** [comment]
I'm also facing this issue. Tried the configuration from the /example/secondary_file.conf as well and not working. Any estimated fix planned? This is somewhat of showstopper for me.

**Comment by gabfl** [comment]
@repeatedly did you get a chance to look into the issue?

thanks a lot

**Comment by repeatedly** [comment]
I tested modified configuration for test and it worked as expected.

- conf

```
<source>
  @type forward
</source>

<match test>
  @type forward

  <buffer time,tag,message>
    @type memory
    timekey 2s
    timekey_wait 1s
    flush_mode interval
    flush_interval 1s
    # use smaller retry setting for test
    retry_max_interval 2s
    retry_timeout 10s
  </buffer>

  <server>
    host 0.0.0.0
    port 24225
  </server>

  <secondary>
    @type secondary_file
    directory log/secondary/
    basename ${tag}_%Y%m%d%L_${message}
  </secondary>
</match>
```

- log

```
2018-04-13 04:58:52 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-04-13 04:58:53 +0900 chunk="569ac2f3f53d8884708e347761663047" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"0.0.0.0\" port 24225"
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/socket.rb:59:in `initialize'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/socket.rb:59:in `new'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/socket.rb:59:in `socket_create_tcp'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/out_forward.rb:334:in `create_transfer_socket'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/out_forward.rb:633:in `send_data'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/out_forward.rb:269:in `block in write'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/out_forward.rb:304:in `block in select_a_healthy_node'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/out_forward.rb:298:in `times'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/out_forward.rb:298:in `select_a_healthy_node'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/out_forward.rb:269:in `write'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/output.rb:1096:in `try_flush'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/output.rb:1329:in `flush_thread_run'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-04-13 04:58:52 +0900 [warn]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-04-13 04:58:53 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-04-13 04:58:53 +0900 chunk="569ac2f3f53d8884708e347761663047" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"0.0.0.0\" port 24225"
  2018-04-13 04:58:53 +0900 [warn]: #0 suppressed same stacktrace
2018-04-13 04:58:54 +0900 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-04-13 04:58:54 +0900 chunk="569ac2f3f53d8884708e347761663047" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"0.0.0.0\" port 24225"
  2018-04-13 04:58:54 +0900 [warn]: #0 suppressed same stacktrace
2018-04-13 04:58:56 +0900 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2018-04-13 04:58:56 +0900 chunk="569ac2f3f53d8884708e347761663047" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"0.0.0.0\" port 24225"
  2018-04-13 04:58:56 +0900 [warn]: #0 suppressed same stacktrace
2018-04-13 04:58:58 +0900 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2018-04-13 04:58:58 +0900 chunk="569ac2f3f53d8884708e347761663047" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"0.0.0.0\" port 24225"
  2018-04-13 04:58:58 +0900 [warn]: #0 suppressed same stacktrace
2018-04-13 04:59:00 +0900 [warn]: #0 failed to flush the buffer. retry_time=4 next_retry_seconds=2018-04-13 04:59:00 +0900 chunk="569ac2f3f53d8884708e347761663047" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"0.0.0.0\" port 24225"
  2018-04-13 04:59:00 +0900 [warn]: #0 suppressed same stacktrace
2018-04-13 04:59:00 +0900 [warn]: #0 retry succeeded by secondary. chunk_id="569ac2f3f53d8884708e347761663047"
```

- secondary flushed result

```
% ls log/secondary 
test_20180413000_hey.0
```

**Comment by gabfl** [comment]
> But this issue says don't retry and call secondary immediately, right?

I am not sure I understand your question but the config I used is exactly the one documented when I filed the issue

**Comment by repeatedly** [comment]
From your log, the behaviour is expected because retry doesn't reach secondary threshold. See document and retry parameters: https://docs.fluentd.org/v1.0/articles/output-plugin-overview#secondary-output

**Comment by kasiprasad** [comment]
Ok, @repeatedly - I'm still not exactly sure why your example works.

Perhaps it would be helpful to update the documentation for Secondary to indicate exactly how/when to expect the secondary to be utilized. A few different examples would be helpful. Also, I'm still not sure whether the secondary would continue to be used if/when connectivity is re-established to the target server.

Can you please explain a little further? 

Thank you.

**Comment by daipom** [comment]
If the connection is restored and the retry succeeds, the output is sent to the primary, not the secondary.
If the connection continues to fail up to the threshold, it will be output to the secondary.

If you have any problems with retries in the latest version, please contact us again.
