### ISSUE TITLE
can't load plugins in --plugin dir

### ISSUE THREAD

**Issue by fujiwara** [fluent/fluentd#1826]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
Fluentd 1.1.0

- Environment information, e.g. OS.
  - macOS Sierra 10.12.6
  - ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15] (rbenv)

- Your configuration
```
<filter test.**>
  @type test_filter
</filter>
<match test.**>
  @type stdout
</match>
```

```ruby
# plugins/test_filter.rb
module Fluent
  class TestFilter < Filter
    Plugin.register_filter('test_filter', self)
    def filter(tag, time, record)
      record["test"] = true
      record
    end
  end
end
```

- Your problem explanation. If you have an error logs, write it together.

I want to load `plugins/test_filter.rb` using `--plugin` option, but an error occured `Unknown filter plugin 'test_filter'`.

```console
$ fluentd --dry-run --config ./fluentd.conf --plugin ./plugins --verbose
2018-01-24 15:32:56 +0900 [info]: fluent/log.rb:322:info: parsing config file is succeeded path="/Users/fujiwara/tmp/fluentd/fluentd.conf"
2018-01-24 15:32:56 +0900 [info]: fluent/log.rb:322:info: starting fluentd-1.1.0 as dry run mode ruby="2.4.1"
2018-01-24 15:32:56 +0900 [error]: fluent/log.rb:362:error: config error file="/Users/fujiwara/tmp/fluentd/fluentd.conf" error_class=Fluent::ConfigError error="Unknown filter plugin 'test_filter'. Run 'gem search -rd fluent-plugin' to find plugins"
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/registry.rb:48:in `lookup'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/plugin.rb:146:in `new_impl'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/plugin.rb:108:in `new_filter'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/agent.rb:150:in `add_filter'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/agent.rb:70:in `block in configure'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/agent.rb:64:in `each'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/agent.rb:64:in `configure'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/root_agent.rb:112:in `configure'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/engine.rb:131:in `configure'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/engine.rb:96:in `run_configure'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/supervisor.rb:770:in `run_configure'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/supervisor.rb:553:in `dry_run'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/supervisor.rb:540:in `dry_run_cmd'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/supervisor.rb:475:in `run_supervisor'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/bin/fluentd:8:in `require'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/bin/fluentd:8:in `<top (required)>'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/bin/fluentd:22:in `load'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/bin/fluentd:22:in `<top (required)>'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
  2018-01-24 15:32:56 +0900 [debug]: fluent/supervisor.rb:475:run_supervisor: /Users/fujiwara/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
```

Fluentd 0.12.42 has no problem.

```console
$ fluentd --dry-run --config ./fluentd.conf --plugin ./plugins --verbose
2018-01-24 15:37:01 +0900 [info]: fluent/supervisor.rb:471:read_config: reading config file path="/Users/fujiwara/tmp/fluentd/fluentd.conf"
2018-01-24 15:37:01 +0900 [info]: fluent/supervisor.rb:195:dry_run: starting fluentd-0.12.42 as dry run mode
2018-01-24 15:37:01 +0900 [info]: fluent/engine.rb:126:block in configure: gem 'fluentd' version '0.12.42'
2018-01-24 15:37:01 +0900 [info]: fluent/agent.rb:141:add_filter: adding filter pattern="test.**" type="test_filter"
2018-01-24 15:37:01 +0900 [info]: fluent/agent.rb:129:add_match: adding match pattern="test.**" type="stdout"
2018-01-24 15:37:01 +0900 [info]: fluent/engine.rb:133:configure: using configuration file: <ROOT>
  <filter test.**>
    @type test_filter
  </filter>
  <match test.**>
    @type stdout
  </match>
</ROOT>
```

**Comment by repeatedly** [comment]
I remember now. This is expected behaviour.
See this issue why v1 has this problem: https://github.com/fluent/fluentd/issues/1445

Chaning plugin file name to `filter_test_filter.rb` should fix this problem.

**Comment by fujiwara** [comment]
Thanks!
I renamed file to `filter_test_filter.rb`, works fine.
