### ISSUE TITLE
in_udp appears to be broken/non-existent in td-agent 3.1.1 for windows

### ISSUE THREAD

**Issue by bcharboneauiherb** [fluent/fluentd#1840]
I am trying to use in_udp as an alternative to in_syslog for a specific multiline pattern. I have not even added the `<parse>` directive to it yet and it fails.
```
<source>
  @type udp
  port 514
  bind 0.0.0.0
  tag syslog
</source>
```
when trying to configure td-agent 3.1.1 on windows i get the following terminating exception:
```
C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/config/section.rb:178:in `block in generate':
 parse: init is specified, but there're parameters without default values:@type (ArgumentError)
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/config/section.rb:169:in `each'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/config/section.rb:169:in `generate'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/configurable.rb:94:in `configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/base.rb:57:in `configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_id.rb:39:in `configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/log.rb:570:in `configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/event_emitter.rb:73:in `configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/extract.rb:78:in `configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/parser.rb:83:in `configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/server.rb:306:in `configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_udp.rb:50:in `configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin.rb:164:in `configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:282:in `add_source'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:122:in `block in configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:118:in `each'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:118:in `configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:131:in `configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:96:in `run_configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:770:in `run_configure'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:553:in `dry_run'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:571:in `supervise'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:476:in `run_supervisor'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/command/fluentd.rb:310:in `<top(required)>'
        from C:/opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from C:/opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/bin/fluentd:8:in `<top (required)>'
        from C:/opt/td-agent/embedded/bin/fluentd:22:in `load'
        from C:/opt/td-agent/embedded/bin/fluentd:22:in `<main>'

**Comment by repeatedly** [comment]
> I have not even added the <parse> directive to it yet and it fails.

**Comment by repeatedly** [comment]
And this doesn't follow contributing guide: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md
So closed.

**Comment by bcharboneauiherb** [comment]
Tried the parse directive still gets hung up on asking for @type

**Comment by repeatedly** [comment]
Could you paste the configuration? Here is simple conf and log.

```
2018-02-03 01:24:28 +0900 [info]: parsing config file is succeeded path="a.conf"
2018-02-03 01:24:28 +0900 [info]: using configuration file: <ROOT>
  <source>
    @type udp
    tag "test"
    <parse>
      @type "json"
    </parse>
  </source>
</ROOT>
2018-02-03 01:24:28 +0900 [info]: starting fluentd-1.1.0 pid=44375 ruby="2.4.2"
2018-02-03 01:24:28 +0900 [info]: spawn command to main:  cmdline=["/Users/repeatedly/.rbenv/versions/2.4.2/bin/ruby", "-Eascii-8bit:ascii-8bit", "/Users/repeatedly/dev/fluentd/fluentd/bin/fluentd", "-c", "a.conf", "--under-supervisor"]
2018-02-03 01:24:29 +0900 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.8'
2018-02-03 01:24:29 +0900 [info]: gem 'fluent-plugin-elasticsearch' version '2.5.0'
2018-02-03 01:24:29 +0900 [info]: gem 'fluent-plugin-flatten-hash' version '0.5.1'
2018-02-03 01:24:29 +0900 [info]: gem 'fluent-plugin-flowcounter-simple' version '0.0.4'
2018-02-03 01:24:29 +0900 [info]: gem 'fluent-plugin-grok-parser' version '2.1.4'
2018-02-03 01:24:29 +0900 [info]: gem 'fluent-plugin-kafka' version '0.6.4'
2018-02-03 01:24:29 +0900 [info]: gem 'fluent-plugin-mongo' version '1.1.0'
2018-02-03 01:24:29 +0900 [info]: gem 'fluent-plugin-record-modifier' version '0.6.2'
2018-02-03 01:24:29 +0900 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.0.1'
2018-02-03 01:24:29 +0900 [info]: gem 'fluent-plugin-td' version '1.0.0'
2018-02-03 01:24:29 +0900 [info]: gem 'fluentd' version '1.1.0'
2018-02-03 01:24:29 +0900 [info]: gem 'fluentd' version '0.14.16'
2018-02-03 01:24:29 +0900 [info]: adding source type="udp"
2018-02-03 01:24:29 +0900 [info]: #0 starting fluentd worker pid=44403 ppid=44375 worker=0
2018-02-03 01:24:29 +0900 [info]: #0 listening udp socket bind="0.0.0.0" port=5160
2018-02-03 01:24:29 +0900 [info]: #0 fluentd worker is now running worker=0
```
