### ISSUE TITLE
Succeeded retry resets retry counter when flushing with multiple threads

### ISSUE THREAD

**Issue by mikkohoo** [fluent/fluentd#1854]
**td-agent v3.1.1**
**elasticsearch 6.1**

We are using td-agent to receive events and elasticsearch output plugin to push those events to elasticsearch index. In order to optimize throughtput to elasticsearch, we have configured elasticsearch output plugin to flush chunks using multiple threads(flush_thread_count 8). Our elasticsearch has been configured with 'automatic index creation' set **false** in order to have better control who and how index has been created. This is means that elasticsearch might receive 'index not found' exceptions from elasticsearch if there isn't a target index for that particular event. Event tag is used to specifiy target index.

We notice an odd behaviour when elasticsearch is attempting to flush chunk which contains a record which doesn't have target index in elasticsearch. In this case chunk should fail and retry count increased until retry limit is reached and chunk is discarded. But we notice that chunk is never discarded since something is always resetting the retry counter. After some debugging, we notice that successful retries might do this. See the logs below:

```
2018-02-09 09:24:13 +0200 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-02-09 09:24:14 +0200 chunk="564c200642d57480f4972ea3ad8d7433" error_class=Fluent::Plugin::ElasticsearchErrorHandler::UnrecognizedElasticsearchError error="Unrecognized elasticsearch errors returned, retrying  {\"took\"=>0, \"errors\"=>true, \"items\"=>[{\"index\"=>{\"_index\"=>\"retry.foobar\", \"_type\"=>\"fluentd\", \"_id\"=>nil, \"status\"=>404, \"error\"=>{\"type\"=>\"index_not_found_exception\", \"reason\"=>\"no such index and [action.auto_create_index] contains [-*] which forbids automatic creation of the index\", \"index_uuid\"=>\"_na_\", \"index\"=>\"retry.foobar\"}}}]}"
  2018-02-09 09:24:13 +0200 [warn]: #0 suppressed same stacktrace
2018-02-09 09:24:14 +0200 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-02-09 09:24:14 +0200 chunk="564c200642d57480f4972ea3ad8d7433" error_class=Fluent::Plugin::ElasticsearchErrorHandler::UnrecognizedElasticsearchError error="Unrecognized elasticsearch errors returned, retrying  {\"took\"=>0, \"errors\"=>true, \"items\"=>[{\"index\"=>{\"_index\"=>\"retry.foobar\", \"_type\"=>\"fluentd\", \"_id\"=>nil, \"status\"=>404, \"error\"=>{\"type\"=>\"index_not_found_exception\", \"reason\"=>\"no such index and [action.auto_create_index] contains [-*] which forbids automatic creation of the index\", \"index_uuid\"=>\"_na_\", \"index\"=>\"retry.foobar\"}}}]}"
  2018-02-09 09:24:14 +0200 [warn]: #0 suppressed same stacktrace
2018-02-09 09:24:15 +0200 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-02-09 09:24:15 +0200 chunk="564c200642d57480f4972ea3ad8d7433" error_class=Fluent::Plugin::ElasticsearchErrorHandler::UnrecognizedElasticsearchError error="Unrecognized elasticsearch errors returned, retrying  {\"took\"=>0, \"errors\"=>true, \"items\"=>[{\"index\"=>{\"_index\"=>\"retry.foobar\", \"_type\"=>\"fluentd\", \"_id\"=>nil, \"status\"=>404, \"error\"=>{\"type\"=>\"index_not_found_exception\", \"reason\"=>\"no such index and [action.auto_create_index] contains [-*] which forbids automatic creation of the index\", \"index_uuid\"=>\"_na_\", \"index\"=>\"retry.foobar\"}}}]}"
  2018-02-09 09:24:15 +0200 [warn]: #0 suppressed same stacktrace
2018-02-09 09:24:15 +0200 [warn]: #0 retry succeeded. chunk_id="564c269be60c62aa81bd4195eaa9a080"
2018-02-09 09:24:16 +0200 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-02-09 09:24:17 +0200 chunk="564c200642d57480f4972ea3ad8d7433" error_class=Fluent::Plugin::ElasticsearchErrorHandler::UnrecognizedElasticsearchError error="Unrecognized elasticsearch errors returned, retrying  {\"took\"=>0, \"errors\"=>true, \"items\"=>[{\"index\"=>{\"_index\"=>\"retry.foobar\", \"_type\"=>\"fluentd\", \"_id\"=>nil, \"status\"=>404, \"error\"=>{\"type\"=>\"index_not_found_exception\", \"reason\"=>\"no such index and [action.auto_create_index] contains [-*] which forbids automatic creation of the index\", \"index_uuid\"=>\"_na_\", \"index\"=>\"retry.foobar\"}}}]}"
  2018-02-09 09:24:16 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/elasticsearch_error_handler.rb:83:in `handle_error'
  2018-02-09 09:24:16 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:427:in `send_bulk'
  2018-02-09 09:24:16 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:411:in `write'
  2018-02-09 09:24:16 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
  2018-02-09 09:24:16 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
  2018-02-09 09:24:16 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-02-09 09:24:16 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-02-09 09:24:17 +0200 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-02-09 09:24:17 +0200 chunk="564c200642d57480f4972ea3ad8d7433" error_class=Fluent::Plugin::ElasticsearchErrorHandler::UnrecognizedElasticsearchError error="Unrecognized elasticsearch errors returned, retrying  {\"took\"=>0, \"errors\"=>true, \"items\"=>[{\"index\"=>{\"_index\"=>\"retry.foobar\", \"_type\"=>\"fluentd\", \"_id\"=>nil, \"status\"=>404, \"error\"=>{\"type\"=>\"index_not_found_exception\", \"reason\"=>\"no such index and [action.auto_create_index] contains [-*] which forbids automatic creation of the index\", \"index_uuid\"=>\"_na_\", \"index\"=>\"retry.foobar\"}}}]}"
  2018-02-09 09:24:17 +0200 [warn]: #0 suppressed same stacktrace
2018-02-09 09:24:18 +0200 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-02-09 09:24:18 +0200 chunk="564c200642d57480f4972ea3ad8d7433" error_class=Fluent::Plugin::ElasticsearchErrorHandler::UnrecognizedElasticsearchError error="Unrecognized elasticsearch errors returned, retrying  {\"took\"=>0, \"errors\"=>true, \"items\"=>[{\"index\"=>{\"_index\"=>\"retry.foobar\", \"_type\"=>\"fluentd\", \"_id\"=>nil, \"status\"=>404, \"error\"=>{\"type\"=>\"index_not_found_exception\", \"reason\"=>\"no such index and [action.auto_create_index] contains [-*] which forbids automatic creation of the index\", \"index_uuid\"=>\"_na_\", \"index\"=>\"retry.foobar\"}}}]}"
  2018-02-09 09:24:18 +0200 [warn]: #0 suppressed same stacktrace
2018-02-09 09:24:20 +0200 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2018-02-09 09:24:20 +0200 chunk="564c200642d57480f4972ea3ad8d7433" error_class=Fluent::Plugin::ElasticsearchErrorHandler::UnrecognizedElasticsearchError error="Unrecognized elasticsearch errors returned, retrying  {\"took\"=>0, \"errors\"=>true, \"items\"=>[{\"index\"=>{\"_index\"=>\"retry.foobar\", \"_type\"=>\"fluentd\", \"_id\"=>nil, \"status\"=>404, \"error\"=>{\"type\"=>\"index_not_found_exception\", \"reason\"=>\"no such index and [action.auto_create_index] contains [-*] which forbids automatic creation of the index\", \"index_uuid\"=>\"_na_\", \"index\"=>\"retry.foobar\"}}}]}"
  2018-02-09 09:24:20 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/elasticsearch_error_handler.rb:83:in `handle_error'
  2018-02-09 09:24:20 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:427:in `send_bulk'
  2018-02-09 09:24:20 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:411:in `write'
  2018-02-09 09:24:20 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
  2018-02-09 09:24:20 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
  2018-02-09 09:24:20 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-02-09 09:24:20 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-02-09 09:24:24 +0200 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2018-02-09 09:24:24 +0200 chunk="564c200642d57480f4972ea3ad8d7433" error_class=Fluent::Plugin::ElasticsearchErrorHandler::UnrecognizedElasticsearchError error="Unrecognized elasticsearch errors returned, retrying  {\"took\"=>0, \"errors\"=>true, \"items\"=>[{\"index\"=>{\"_index\"=>\"retry.foobar\", \"_type\"=>\"fluentd\", \"_id\"=>nil, \"status\"=>404, \"error\"=>{\"type\"=>\"index_not_found_exception\", \"reason\"=>\"no such index and [action.auto_create_index] contains [-*] which forbids automatic creation of the index\", \"index_uuid\"=>\"_na_\", \"index\"=>\"retry.foobar\"}}}]}"
  2018-02-09 09:24:24 +0200 [warn]: #0 suppressed same stacktrace
2018-02-09 09:24:32 +0200 [warn]: #0 failed to flush the buffer. retry_time=4 next_retry_seconds=2018-02-09 09:24:32 +0200 chunk="564c200642d57480f4972ea3ad8d7433" error_class=Fluent::Plugin::ElasticsearchErrorHandler::UnrecognizedElasticsearchError error="Unrecognized elasticsearch errors returned, retrying  {\"took\"=>0, \"errors\"=>true, \"items\"=>[{\"index\"=>{\"_index\"=>\"retry.foobar\", \"_type\"=>\"fluentd\", \"_id\"=>nil, \"status\"=>404, \"error\"=>{\"type\"=>\"index_not_found_exception\", \"reason\"=>\"no such index and [action.auto_create_index] contains [-*] which forbids automatic creation of the index\", \"index_uuid\"=>\"_na_\", \"index\"=>\"retry.foobar\"}}}]}"
  2018-02-09 09:24:32 +0200 [warn]: #0 suppressed same stacktrace
2018-02-09 09:24:32 +0200 [warn]: #0 retry succeeded. chunk_id="564c26a6595b3ffe84b1fa866cb32f62"
2018-02-09 09:24:33 +0200 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-02-09 09:24:34 +0200 chunk="564c200642d57480f4972ea3ad8d7433" error_class=Fluent::Plugin::ElasticsearchErrorHandler::UnrecognizedElasticsearchError error="Unrecognized elasticsearch errors returned, retrying  {\"took\"=>0, \"errors\"=>true, \"items\"=>[{\"index\"=>{\"_index\"=>\"retry.foobar\", \"_type\"=>\"fluentd\", \"_id\"=>nil, \"status\"=>404, \"error\"=>{\"type\"=>\"index_not_found_exception\", \"reason\"=>\"no such index and [action.auto_create_index] contains [-*] which forbids automatic creation of the index\", \"index_uuid\"=>\"_na_\", \"index\"=>\"retry.foobar\"}}}]}"
  2018-02-09 09:24:33 +0200 [warn]: #0 suppressed same stacktrace
```

After every `retry succeeded.` counter is reseted `retry_time=0`. This is also causing heavy performance impact since exponential backoff never kicks in. We tested this without `flush_thread_count` parameter(1 thread) and retries work just fine. Apparently there is some race condition related to multiple threads which causing this.

Full trace level log: https://gist.github.com/mikkohoo/c8d320fa6e6a08edea33ecd055c24568

My configuration:
```
<source>
  @type forward
</source>

<source>
  @type dummy
  tag retry.test
  rate 1
  dummy {"message":"foobar"}
</source>

<match retry.**>
  @type elasticsearch

   index_name ${tag}

  <buffer>
    @type file
    path buffer
    flush_mode interval
    flush_interval 10s
    flush_thread_count 8
  </buffer>

  ssl_verify false
  hosts xxx
  user elastic
  password xxxx

  include_timestamp true
</match>
```

Steps to reproduce:
- Start elasticsearch with automatic index creation set to false
- Create retry.test index
- Start td-agent with given configuration
- Dummy output plugin will generate events to retry.test index
- Send event which doesn't target index `echo '{"message":"foobar"}'|fluent-cat retry.foobar`
- Invalid event is placed among successful events in the chunk
- Wait and see how after `retry succeeded.` counter is reseted `retry_time=0`

**Comment by repeatedly** [comment]
This is expected behaviour. retry state is shared between multiple threads because retry is mainly for unexpected failure, unstable network, destinatino down and etc.
I assume you can use grep filter for removing such unused records from event stream before elasticsearch plugin.

**Comment by mikkohoo** [comment]
I understand, this is a corner case which might be hard to resolve without rewriting whole retrying mechanics. Unfortunately grep plugin won't help in this case since we don't know beforehand does the event have a index in the elasticsearch.

**Comment by tirelibirefe** [comment]
I have the same problem.
I deleted indices, deleted patterns reinstalled indices & patterns and reinstalled fluentd nothing changed.
What is the solution of expected behaviour?
