### ISSUE TITLE
fluentd got exception on big log files with 1 million lines

### ISSUE THREAD

**Issue by robertchen** [fluent/fluentd#1872]
fluentd or td-agent version.
td-agent-3.1.1-0.el7.x86_64
Environment information, e.g. OS.
centos
Your configuration
```
<source>
  @type tail
  path /var/log/testlogs/*.log
  pos_file /tmp/webapps.log.pos
  read_from_head true
  tag webapps
...
</source>
<source>
  @type tail
  path /home/centos/jobtestlogs/*/*.log,/home/centos/jobtestlogs/*/*/*.log
  exclude_path ["/home/centos/jobtestlogs/webapps/*"]
  pos_file /tmp/jobs.log.pos
  read_from_head true
  tag jobs
...
</source>
```
Your problem explanation. If you have an error logs, write it together.
The td-agent forward to fluentd, my jobs log file has almost 1 million lines, I got below issue in fluentd and the logs did not write to elasticsearch, if I tructated the logfile to 10000 lines I saw the logs could be written to elasticsearch:

```
2018-02-26 20:50:31 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-02-26 20:50:32 +0000 chunk="56623a3aebc14c36300fc2f8ad0ae17c" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Could not push logs to Elasticsearch after 2 retries. Connection reset by peer (Errno::ECONNRESET)"
  2018-02-26 20:50:31 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.7.0/lib/fluent/plugin/out_elasticsearch.rb:460:in `rescue in send_bulk'
  2018-02-26 20:50:31 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.7.0/lib/fluent/plugin/out_elasticsearch.rb:446:in `send_bulk'
  2018-02-26 20:50:31 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.7.0/lib/fluent/plugin/out_elasticsearch.rb:433:in `write'
  2018-02-26 20:50:31 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1094:in `try_flush'
  2018-02-26 20:50:31 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1319:in `flush_thread_run'
  2018-02-26 20:50:31 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-02-26 20:50:31 +0000 [warn]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.1.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-02-26 20:50:31.145091703 +0000 fluent.info: {"message":"Connection opened to Elasticsearch cluster => {:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\"}"}
2018-02-26 20:50:31.191919856 +0000 fluent.warn: {"retry_time":0,"next_retry_seconds":"2018-02-26 20:50:32 +0000","chunk":"56623a3aebc14c36300fc2f8ad0ae17c","error":"#<Fluent::Plugin::ElasticsearchOutput::ConnectionFailure: Could not push logs to Elasticsearch after 2 retries. Connection reset by peer (Errno::ECONNRESET)>","message":"failed to flush the buffer. retry_time=0 next_retry_seconds=2018-02-26 20:50:32 +0000 chunk=\"56623a3aebc14c36300fc2f8ad0ae17c\" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error=\"Could not push logs to Elasticsearch after 2 retries. Connection reset by peer (Errno::ECONNRESET)\""}
```

**Comment by repeatedly** [comment]
This seesm fluent-plugin-elasticsearch or elasticsearch issue. Closed.
