### ISSUE TITLE
MessagePack::UnpackError with  memory usage go high

### ISSUE THREAD

**Issue by David-Gee** [fluent/fluentd#1882]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

-td-agent 1.1.21
-CentOS 6.5
-configuration
`---`- <source>
    type forward
    port 60000
</source>
<source>
    type http
    port 8888
  </source>
  <source>
    type monitor_agent
    port 24220
  </source>
  <source>
    type debug_agent
    port 24230
  </source>
  <match debug.**>
    type stdout
  </match>
  <match system.**>
    type forward
    <server>
      host 192.168.0.11
    </server>
    <secondary>
      <server>
        host 192.168.0.12
      </server>
    </secondary>
  </match>
  <match login_pf_tw.**>
    type copy
    <store>
      type file_alternative
      path /data/from_infra/mobage/tw/login_pro/login_pro.log.%Y%m%d
      flush_interval 1s
      output_include_time false
      output_include_tag false
      output_data_type attr:message
    </store>
    <store>
      type kafka
      brokers 10.96.30.61:9092,10.96.30.62:9092,10.96.30.63:9092,10.96.30.64:9092,10.96.30.65:9092,10.96.30.66:9092
      default_topic sdk_log_tw
      output_data_type json
      output_include_tag false
      output_include_time false
    </store>
  </match>`
-----memory usage go higher and can't receive log anymore. Print warning log and error all the time as memory usage rise constantly。After rebooting, it returns to normal.

-----log as below
2018-03-08 14:45:55 +0800 [warn]: emit transaction failed  error_class=MessagePack::UnpackError error=#<MessagePack::UnpackError: parse error.>
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/event.rb:173:in `feed_each'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/event.rb:173:in `each'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/output.rb:519:in `emit'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/output.rb:33:in `next'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_copy.rb:73:in `emit'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/match.rb:36:in `emit'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/engine.rb:160:in `emit_stream'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:148:in `on_message'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:235:in `call'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:235:in `block in on_read_msgpack'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:234:in `feed_each'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:234:in `on_read_msgpack'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:220:in `call'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:220:in `on_read'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/cool.io-1.1.1/lib/cool.io/io.rb:108:in `on_readable'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/cool.io-1.1.1/lib/cool.io/io.rb:170:in `on_readable'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/cool.io-1.1.1/lib/cool.io/loop.rb:96:in `run_once'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/cool.io-1.1.1/lib/cool.io/loop.rb:96:in `run'
  2018-03-08 14:45:55 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:95:in `run'
2018-03-08 14:45:55 +0800 [error]: forward error error=#<MessagePack::UnpackError: parse error.> error_class=MessagePack::UnpackError
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/event.rb:173:in `feed_each'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/event.rb:173:in `each'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/output.rb:519:in `emit'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/output.rb:33:in `next'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_copy.rb:73:in `emit'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/match.rb:36:in `emit'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/engine.rb:160:in `emit_stream'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:148:in `on_message'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:235:in `call'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:235:in `block in on_read_msgpack'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:234:in `feed_each'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:234:in `on_read_msgpack'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:220:in `call'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:220:in `on_read'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/cool.io-1.1.1/lib/cool.io/io.rb:108:in `on_readable'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/cool.io-1.1.1/lib/cool.io/io.rb:170:in `on_readable'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/cool.io-1.1.1/lib/cool.io/loop.rb:96:in `run_once'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/cool.io-1.1.1/lib/cool.io/loop.rb:96:in `run'
  2018-03-08 14:45:55 +0800 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/in_forward.rb:95:in `run'

**Comment by repeatedly** [comment]
fluentd v0.10 is EOL so we close this issue.
If you hit this problem with latest fluentd and msgpack combo, please reopen it.
