### ISSUE TITLE
Fluentd cannot connect to Elasticsearch

### ISSUE THREAD

**Issue by linuxandunix** [fluent/fluentd#1899]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- 'fluentd' version '0.14.13'
    'fluent-plugin-elasticsearch' version '1.9.5'
   docker.
- Amazon Linux AMI
-
---
"Args": [
            "-c",
            "/loadConfig.sh && fluentd -c /fluentd/etc/${FLUENTD_CONF} -p /fluentd/plugins $FLUENTD_OPT"
        ],

---
Truncated output of /fluentd/etc/${FLUENTD_CONF}

 @type elasticsearch
 **host ELK_ELB_ADDRESS**
 port 9400
 logstash_format true
 logstash_prefix fluentd
 template_name fluent_elastic_mapping
 template_file /fluentd/etc/fluent_elastic_mapping.template
 flush_interval 3s
 request_timeout 25s
 slow_flush_log_threshold 30.0
 buffer_type file
 buffer_path /fluentd/buffer
 buffer_chunk_limit 16M
 buffer_queue_limit 4096
 retry_limit 20
 retry_wait 15s
 num_threads 2

echo $ELK_ELB_ADDRESS  returns NULL

- In the above configuration, someone changed the elasticsearch "host" to a variable which was not exported. The value was NULL.
Fluentd crashed with following message;

2018-03-15 08:53:47 +0000 [error]: #0 unexpected error error_class=Fluent::ElasticsearchOutput::**ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"ELK_ELB_ADDRESS\", :port=>9400**, :scheme=>\"http\"})!"
  2018-03-15 08:53:47 +0000 [error]: #0 /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-elasticsearch-1.9.5/lib/fluent/plugin/out_elasticsearch.rb:162:in `client'
  2018-03-15 08:53:47 +0000 [error]: #0 /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-elasticsearch-1.9.5/lib/fluent/plugin/elasticsearch_index_template.rb:12:in `template_exists?'
  2018-03-15 08:53:47 +0000 [error]: #0 /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-elasticsearch-1.9.5/lib/fluent/plugin/elasticsearch_index_template.rb:23:in `template_install'
  2018-03-15 08:53:47 +0000 [error]: #0 /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-elasticsearch-1.9.5/lib/fluent/plugin/out_elasticsearch.rb:92:in `configure'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/plugin.rb:164:in `configure'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/agent.rb:128:in `add_match'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/agent.rb:71:in `block in configure'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/agent.rb:64:in `each'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/agent.rb:64:in `configure'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/root_agent.rb:86:in `configure'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/engine.rb:117:in `configure'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/engine.rb:91:in `run_configure'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/supervisor.rb:724:in `run_configure'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/supervisor.rb:494:in `block in run_worker'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/supervisor.rb:652:in `main_process'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/supervisor.rb:490:in `run_worker'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/command/fluentd.rb:300:in `<top (required)>'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/bin/fluentd:5:in `<top (required)>'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/bin/fluentd:22:in `load'
  2018-03-15 08:53:47 +0000 [error]: #0 /usr/bin/fluentd:22:in `<main>'
2018-03-15 08:53:48 +0000 [info]: Worker 0 finished unexpectedly with status 1
2018-03-15 08:53:48 +0000 [info]: gem 'fluent-plugin-concat' version '2.0.1'
2018-03-15 08:53:48 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.9.5'
2018-03-15 08:53:48 +0000 [info]: gem 'fluent-plugin-elasticsearch-timestamp-check' version '0.2.1'
2018-03-15 08:53:48 +0000 [info]: gem 'fluent-plugin-grok-parser' version '2.1.2'
2018-03-15 08:53:48 +0000 [info]: gem 'fluentd' version '0.14.13'

The error message "ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"ELK_ELB_ADDRESS\", :port=>9400**, :scheme=>\"http\"})!""  is not sufficient to debug. It'd be great if a more verbose message is printed, maybe like "couldn't resolve host"

**Comment by repeatedly** [comment]
This is elasticsearch plugin issue, not fluentd core. Closed.

**Comment by qasmi** [comment]
I have also the same proplem de you have any idea @repeatedly please
