### ISSUE TITLE
end of file reached error

### ISSUE THREAD

**Issue by dmnfortytwo** [fluent/fluentd#1923]
For some reason fluentd stopped to send logs and started to eat cpu (~1 core), memory (~650M) and flood its logfile with same error:

```
2018-04-03 17:56:01 +0000 [warn]: #0 pattern not match: ""
2018-04-03 17:56:19 +0000 [error]: #0 unexpected error while receiving ack message error_class=EOFError error="end of file reached"
  2018-04-03 17:56:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/openssl/buffering.rb:125:in `sysread'
  2018-04-03 17:56:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/openssl/buffering.rb:125:in `readpartial'
  2018-04-03 17:56:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:427:in `read_ack_from_sock'
  2018-04-03 17:56:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:501:in `block in ack_reader'
  2018-04-03 17:56:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:500:in `each'
  2018-04-03 17:56:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_forward.rb:500:in `ack_reader'
  2018-04-03 17:56:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-04-03 17:56:19 +0000 [error]: #0 unexpected error while receiving ack message error_class=EOFError error="end of file reached"
  2018-04-03 17:56:19 +0000 [error]: #0 suppressed same stacktrace
2018-04-03 17:56:19 +0000 [error]: #0 unexpected error while receiving ack message error_class=EOFError error="end of file reached"
  2018-04-03 17:56:19 +0000 [error]: #0 suppressed same stacktrace
2018-04-03 17:56:19 +0000 [error]: #0 unexpected error while receiving ack message error_class=EOFError error="end of file reached"
  2018-04-03 17:56:19 +0000 [error]: #0 suppressed same stacktrace
2018-04-03 17:56:19 +0000 [error]: #0 unexpected error while receiving ack message error_class=EOFError error="end of file reached"
  2018-04-03 17:56:19 +0000 [error]: #0 suppressed same stacktrace
2018-04-03 17:56:19 +0000 [error]: #0 unexpected error while receiving ack message error_class=EOFError error="end of file reached"
  2018-04-03 17:56:19 +0000 [error]: #0 suppressed same stacktrace
2018-04-03 17:56:19 +0000 [error]: #0 unexpected error while receiving ack message error_class=EOFError error="end of file reached"
  2018-04-03 17:56:19 +0000 [error]: #0 suppressed same stacktrace
2018-04-03 17:56:19 +0000 [error]: #0 unexpected error while receiving ack message error_class=EOFError error="end of file reached"
```

Restart helped, now its trying to flush output buffer to logs storage.

2018-04-03 18:28:32 +0000 [info]: starting fluentd-1.0.2 pid=15951 ruby="2.4.2"
2018-04-03 18:28:32 +0000 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/sbin/td-agent", "--log", "/var/log/td-agent/td-agent.log", "--daemon", "/var/
run/td-agent/td-agent.pid", "--under-supervisor"]
2018-04-03 18:28:32 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.4.0'
2018-04-03 18:28:32 +0000 [info]: gem 'fluent-plugin-kafka' version '0.6.5'
2018-04-03 18:28:32 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.0.1'
2018-04-03 18:28:32 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.0'
2018-04-03 18:28:32 +0000 [info]: gem 'fluent-plugin-td' version '1.0.0'
2018-04-03 18:28:32 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.3'
2018-04-03 18:28:32 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.2.2'
2018-04-03 18:28:32 +0000 [info]: gem 'fluentd' version '1.0.2'

output_forward settings:

```
  <match **>
    @type forward
    transport tls
    require_ack_response true
    expire_dns_cache 300
    tls_cert_path /etc/td-agent/bundle.pem
    tls_allow_self_signed_cert true
    tls_verify_hostname false
    <server>
      name "harvester"
      host "harvester.logs.zzz.z"
    </server>
    <server>
      name "harvester-b"
      host "harvester-b.logs.zzz.z"
    </server>
    <buffer>
      @type "file"
      flush_mode interval
      flush_interval 10s
      retry_type periodic
      retry_wait 10s
      retry_timeout 10d
      path "/var/lib/td-agent/buffers/output_forward"
    </buffer>
    <security>
      shared_key xxxxxx
      self_hostname "admin1.zzz.zzz.z"
    </security>
  </match>
```
On server side I have haproxy and fluentd with same version.

**Comment by dmnfortytwo** [comment]
UPD: All (fscking all) clients are affected!

**Comment by repeatedly** [comment]
It seems TLS socket raises EOFError, not ECONNRESET.
Patch is here: https://github.com/fluent/fluentd/pull/1925
