### ISSUE TITLE
BufferChunkOverflowError blocking subsequent log transmission

### ISSUE THREAD

**Issue by blackholegalaxy** [fluent/fluentd#1946]
# Environment
 * fluentd: (docker) v1.1.2-debian
 * plugins:
    *  fluent-plugin-elasticsearch: 2.8.5
    * fluent-plugin-concat: 2.2.1

# Encountered error
Sometimes we get a BufferChunkOverflowError. It prevents any further log to be transmitted to our elasticsearch. Fluentd just stops any job.

Maybe our configuration is faulty in some way. I followed documentation about Buffer and all defaults works for us. 

We just wonder why this error occurs and fluentd just doens't "flush" the oversized buffer. As documentation states: 

> buffer_chunk_limit
> The maximum size of a chunk allowed (default: 8MB)
> If a chunk grows more than the limit, it gets flushed to the output queue automatically.

# Configuration

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<filter docker.project.backend>
  @type parser
  format json
  key_name log
</filter>

<filter docker.**>
  @type concat
  key log
  flush_interval 5
  separator ""
  stream_identity_key container_id
  multiline_end_regexp /\\n$/
  timeout_label @NORMAL
</filter>

<match **>
  @type relabel
  @label @NORMAL
</match>

<label @NORMAL>
  <match docker.**>
    @type copy
      
    <store>
      @type elasticsearch
      host elasticsearch
      port 9200
      # user elastic
      # password changeme
      logstash_format true
      logstash_prefix fluentd
      logstash_dateformat %Y.%m.%d
      include_tag_key true
      tag_key @log_name
    </store>
      
    <store>
      @type stdout
    </store>
  </match>
  <match fluent.**>
    @type null
  </match>
</label>

```

# Error

```
[info]: #0 Timeout flush: docker.project.dev.db:fcc440c2d75388f89e51846a10f4ad29feade58ec2f610d251a4fffce3e90134
[warn]: #0 chunk bytes limit exceeds for an emitted event stream: 27710002bytes
[warn]: #0 emit transaction failed: error_class=Fluent::Plugin::Buffer::BufferChunkOverflowError error="a 27710002bytes record is larger than buffer chunk limit size" location="/var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/buffer.rb:660:in `block in write_step_by_step'" tag="docker.project.staging.client"
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/buffer.rb:660:in `block in write_step_by_step'
[warn]: #0 /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/buffer.rb:641:in `write_step_by_step'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/buffer.rb:590:in `write_once'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/buffer.rb:278:in `block in write'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/buffer.rb:276:in `each'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/buffer.rb:276:in `write'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/output.rb:967:in `block in handle_stream_simple'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/output.rb:851:in `write_guard'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/output.rb:966:in `handle_stream_simple'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/output.rb:841:in `execute_chunking'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/output.rb:771:in `emit_buffered'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/out_copy.rb:58:in `block in process'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/out_copy.rb:56:in `each'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/out_copy.rb:56:in `each_with_index'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/out_copy.rb:56:in `process'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin/multi_output.rb:148:in `emit_sync'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/event_router.rb:96:in `emit_stream'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/event_router.rb:87:in `emit'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-concat-2.2.1/lib/fluent/plugin/filter_concat.rb:255:in `handle_timeout_error'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-concat-2.2.1/lib/fluent/plugin/filter_concat.rb:228:in `block in flush_timeout_buffer'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-concat-2.2.1/lib/fluent/plugin/filter_concat.rb:221:in `each'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-concat-2.2.1/lib/fluent/plugin/filter_concat.rb:221:in `flush_timeout_buffer'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-concat-2.2.1/lib/fluent/plugin/filter_concat.rb:111:in `on_timer'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
[warn]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
[warn]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
[warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.1.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
[error]: #0 Unexpected error raised. Stopping the timer. title=:filter_concat_timer error_class=Fluent::Plugin::Buffer::BufferChunkOverflowError error="a 27710002bytes record is larger than buffer chunk limit size"
[error]: #0 suppressed same stacktrace
[error]: #0 Timer detached. title=:filter_concat_timer
```

**Comment by fujimotos** [comment]
@blackholegalaxy

I believe your problem has been fixed by https://github.com/fluent-plugins-nursery/fluent-plugin-concat/pull/48.
So upgrade the plugin to v2.2.2 and you will see the processing continues without halting.

### What was the problem?

It was essentially a bug of `fluent-plugin-concat` (rather than Fluentd itself)

The problem was that `fluent-plugin-concat` failed to catch internal exceptions
where it should have, and these unhandled exceptions blew off its flushing thread
(the thread responsible for shipping data).

For more details, see the pull request
