### ISSUE TITLE
in_forward plugin, multi-process environment, unexpected error error_class=TypeError error="no implicit conversion of nil into String"

### ISSUE THREAD

**Issue by makknife** [fluent/fluentd#1971]
I am trying to use multiple workers.
If I set workers=1 my configuration works as expected, but setting it to 2 or more creates an Error.

I will have to debug further, but wanted to ask if there's something maybe wrong in my configuration? Fluentd docs say that there's no need to use multiple ports and all workers will share the port. Do i still have to install the multiprocess plugin manually? I am using fluent v1.2.0

Please take a look at the bottom `/var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/in_forward.rb` snipet where `server_create_connection` seems to be causing the error. 

fluentd.conf
```
<system>
  workers 2
  log_level trace
  root_dir /var/log/fluentd/workers
</system>
<source>
  @id    input_from_edge
  @type  forward
  @label @aggr_traffic
  port 5140
</source>
<filter **>
  @type stdout
</filter>
<label @aggr_traffic>
  <match **>
    @type s3
    @id output_metrics
    store_as gzip_command
    aws_key_id ${AWS_ACCESS_KEY_ID}
    aws_sec_key ${AWS_SECRET_ACCESS_KEY}
    s3_bucket ${S3_BUCKET}
    s3_region ${S3_REGION}
    #s3_object_key_format <format string> #(optional; default="%{path}%{time_slice}_%{index}.%{file_extension}")
    auto_create_bucket false
    check_apikey_on_start true
    flush_interval 5m
    flush_at_shutdown true
    time_slice_format %Y%m%d
    time_slice_wait 1m
    time_format %Y%m%dT%H%M%S%z
    utc
    buffer_path /var/log/fluentd/pcf.*.buffer
    buffer_queue_limit 512
    buffer_chunk_limit 16m
  </match>
</label>
```
#
#
fluentd.log
```
...
2018-05-04 21:19:21 +0000 [debug]: #0 [output_metrics] buffer started instance=10598880 stage_size=0 queue_size=0
2018-05-04 21:19:21 +0000 [debug]: #0 [output_metrics] enqueue_thread actually running
2018-05-04 21:19:21 +0000 [trace]: #0 [output_metrics] enqueueing all chunks in buffer instance=10598880
2018-05-04 21:19:21 +0000 [trace]: #0 [output_metrics] enqueueing all chunks in buffer instance=10598880
2018-05-04 21:19:21 +0000 [debug]: #0 [output_metrics] flush_thread actually running
2018-05-04 21:19:21 +0000 [info]: #0 [input_from_edge] listening port port=5140 bind="0.0.0.0"
2018-05-04 21:19:21 +0000 [error]: #0 unexpected error error_class=TypeError error="no implicit conversion of nil into String"
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/serverengine-2.0.6/lib/serverengine/socket_manager_unix.rb:27:in `initialize'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/serverengine-2.0.6/lib/serverengine/socket_manager_unix.rb:27:in `new'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/serverengine-2.0.6/lib/serverengine/socket_manager_unix.rb:27:in `connect_peer'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/serverengine-2.0.6/lib/serverengine/socket_manager.rb:40:in `listen'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/serverengine-2.0.6/lib/serverengine/socket_manager.rb:55:in `listen_tcp'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin_helper/server.rb:352:in `server_create_tcp_socket'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin_helper/server.rb:212:in `server_create_for_tcp_connection'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin_helper/server.rb:92:in `server_create_connection'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/in_forward.rb:158:in `start'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:165:in `block in start'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:153:in `each'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:140:in `each'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:140:in `lifecycle'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:164:in `start'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/engine.rb:274:in `start'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/engine.rb:219:in `run'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:799:in `run_engine'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:549:in `block in run_worker'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:724:in `main_process'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:544:in `run_worker'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-05-04 21:19:21 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-05-04 21:19:21 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-05-04 21:19:21 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.0/bin/fluentd:8:in `<top (required)>'
  2018-05-04 21:19:21 +0000 [error]: #0 /usr/local/bin/fluentd:23:in `load'
  2018-05-04 21:19:21 +0000 [error]: #0 /usr/local/bin/fluentd:23:in `<main>'
2018-05-04 21:19:21 +0000 [error]: #0 unexpected error error_class=TypeError error="no implicit conversion of nil into String"
  2018-05-04 21:19:21 +0000 [error]: #0 suppressed same stacktrace
```
#
#
/var/lib/gems/2.3.0/gems/fluentd-1.2.0/lib/fluent/plugin/in_forward.rb
```
152     def start
153       super
154
155       shared_socket = system_config.workers > 1
156
157       log.info "listening port", port: @port, bind: @bind
158       server_create_connection(
159         :in_forward_server, @port,
160         bind: @bind,
161         shared: shared_socket,
162         resolve_name: @resolve_hostname,
163         linger_timeout: @linger_timeout,
164         backlog: @backlog,
165         &method(:handle_connection)
166       )
```

**Comment by repeatedly** [comment]
Will check after flight.

**Comment by makknife** [comment]
any updates? Thanks

**Comment by makknife** [comment]
I was able to fix this issue.

Our fluentd project didn't do the preinstallation steps outlined 
@ https://docs.fluentd.org/v1.0/articles/install-by-gem

I am running on aws. Here are the commands.
  # Preinstallation steps
  mv limits.conf /etc/security/limits.conf #aws ec2 reboot-instances --instance-ids
  mv sysctl.conf /etc/sysctl.conf
  sysctl -p

Thanks
