### ISSUE TITLE
File is not writable and failed to flush buffer

### ISSUE THREAD

**Issue by WOoWBOo** [fluent/fluentd#2004]
- fluentd or td-agent version.
fluentd version 0.12.29
- Environment information, e.g. OS.
Ubuntu 16.04.1 LTS

- configuration
`<match  system.**>`
`    @type copy`
    `<store>`
     ` @type "elasticsearch"`
      `host "localhost"`
      `port 9200`
      `include_tag_key true`
      `tag_key "@log_name"`
      `logstash_format true`
      `flush_interval 10s`
    `</store>`
    `<store>`
      `@type "file"`
      `path "/var/log/fluent/wg/"`
      `time_slice_format %Y%m%d%H%M`
      `time_slice_wait 10m`
      `flush_interval 5m`
      `time_format %Y%m%dT%H%M%S%z`
      `compress gzip`
      `utc `
    `</store>`
  `</match>`
  `<source>`
    `@type syslog`
    `port 42185`
    `tag "system"`
  `</source>`

- out_file error:
2018-05-24 19:28:23 -0400 [error]: fluent/log.rb:362:call: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="out_file: `/var/log/fluent/wg/.201805242328_**.log.gz` is not writable"

- failed to buffer:
2018-05-24 19:10:24 -0400 [info]: #0 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
2018-05-24 19:10:24 -0400 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-05-24 19:10:24 -0400 [info]: #0 Detected ES 6.x: ES 7.x will only accept `_doc` in type_name.
2018-05-24 19:10:24 -0400 [warn]: #0 'utc' is deperecated for output plugin. This parameter is used for formatter plugin in compatibility layer. If you want to use same feature, use timekey_use_utc parameter in <buffer> directive instead
2018-05-24 19:10:24 -0400 [info]: #0 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
2018-05-24 19:10:24 -0400 [warn]: #0 'time_format' specified without 'time_key', will be ignored
2018-05-24 19:10:24 -0400 [info]: adding source type="syslog"
2018-05-24 19:10:24 -0400 [info]: #0 starting fluentd worker pid=19499 ppid=19494 worker=0
2018-05-24 19:10:25 -0400 [info]: #0 listening syslog socket on 0.0.0.0:42185 with udp
2018-05-24 19:10:25 -0400 [info]: #0 fluentd worker is now running worker=0
2018-05-24 19:11:33 -0400 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-05-24 19:11:34 -0400 chunk="56cfbc514bdc8f3a5b5e15115567b318" error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="Elasticsearch returned errors, retrying. Add '@log_level debug' to your config to see the full response"
  2018-05-24 19:11:33 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-2.9.0/lib/fluent/plugin/elasticsearch_error_handler.rb:73:in `block in handle_error'
  2018-05-24 19:11:33 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-2.9.0/lib/fluent/plugin/elasticsearch_error_handler.rb:65:in `each_key'
  2018-05-24 19:11:33 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-2.9.0/lib/fluent/plugin/elasticsearch_error_handler.rb:65:in `handle_error'
  2018-05-24 19:11:33 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-2.9.0/lib/fluent/plugin/out_elasticsearch.rb:496:in `send_bulk'
  2018-05-24 19:11:33 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-2.9.0/lib/fluent/plugin/out_elasticsearch.rb:397:in `write'
  2018-05-24 19:11:33 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:1096:in `try_flush'
  2018-05-24 19:11:33 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:1329:in `flush_thread_run'
  2018-05-24 19:11:33 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-05-24 19:11:33 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-1.1.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-05-24 19:11:34 -0400 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-05-24 19:11:34 -0400 chunk="56cfbc514bdc8f3a5b5e15115567b318" error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="Elasticsearch returned errors, retrying. Add '@log_level debug' to your config to see the full response"
  2018-05-24 19:11:34 -0400 [warn]: #0 suppressed same stacktrace
2018-05-24 19:11:36 -0400 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-05-24 19:11:35 -0400 chunk="56cfbc514bdc8f3a5b5e15115567b318" error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="Elasticsearch returned errors, retrying. Add '@log_level debug' to your config to see the full response"

any solution?

**Comment by repeatedly** [comment]
> /var/log/fluent/wg/.201805242328_**.log.gz is not writable

Error says the cause. You need to add write permission to fluentd.

> failed to flush the buffer. retry_time=0 next_retry_seconds=2018-05-24 19:11:34 -0400 chunk="56cfbc514bdc8f3a5b5e15115567b318" error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="Elasticsearch returned errors, retrying. Add '@log_level debug' to your config to see the full response"

Error says elasticsearch returns error so ES or your configuration issue.

**Comment by repeatedly** [comment]
This is not fluentd issue. Closed.
