### ISSUE TITLE
 [error]: #0 A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### ISSUE THREAD

**Issue by sandeepmreddy** [fluent/fluentd#2005]
2018-05-25 16:10:03 +0530 [error]: #0 A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/connection.rb:136:in `rescue in open'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/connection.rb:119:in `open'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/connection.rb:95:in `block in send_request'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/connection.rb:94:in `send_request'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/broker.rb:127:in `send_request'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/broker.rb:57:in `list_offsets'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/fetch_operation.rb:141:in `resolve_offsets'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/fetch_operation.rb:65:in `block in execute'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/fetch_operation.rb:64:in `each'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/fetch_operation.rb:64:in `flat_map'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/fetch_operation.rb:64:in `execute'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/client.rb:391:in `fetch_messages'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/in_kafka.rb:254:in `consume'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/in_kafka.rb:244:in `call'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/in_kafka.rb:244:in `on_timer'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2018-05-25 16:10:03 +0530 [error]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/in_kafka.rb:212:in `run'

**Comment by repeatedly** [comment]
This is not fluentd core issue. Closed.
