### ISSUE TITLE
unexpected error error_class=NameError error="uninitialized constant Fluent::Parser\nDid you mean?  Parts"

### ISSUE THREAD

**Issue by 13567436138** [fluent/fluentd#2029]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.2.0
- Environment information, e.g. OS.
- Your configuration
- Your problem explanation. If you have an error logs, write it together.

```
2018-06-21 12:11:28 +0000 [error]: unexpected error error_class=NameError error="uninitialized constant Fluent::Parser\nDid you mean?  Parts"
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-esslowquery-1.1.0/lib/fluent/plugin/parser_es_slow_query.rb:2:in `<module:Fluent>'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-esslowquery-1.1.0/lib/fluent/plugin/parser_es_slow_query.rb:1:in `<top (required)>'
  2018-06-21 12:11:28 +0000 [error]: /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2018-06-21 12:11:28 +0000 [error]: /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/registry.rb:102:in `block in search'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/registry.rb:99:in `each'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/registry.rb:99:in `search'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/registry.rb:44:in `lookup'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin.rb:146:in `new_impl'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin.rb:123:in `new_parser'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin_helper/parser.rb:89:in `block in configure'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin_helper/parser.rb:85:in `each'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin_helper/parser.rb:85:in `configure'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/in_tail.rb:118:in `configure'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin.rb:164:in `configure'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/root_agent.rb:282:in `add_source'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/root_agent.rb:122:in `block in configure'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/root_agent.rb:118:in `each'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/root_agent.rb:118:in `configure'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/engine.rb:131:in `configure'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/engine.rb:96:in `run_configure'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/supervisor.rb:770:in `run_configure'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/supervisor.rb:522:in `block in run_worker'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/supervisor.rb:699:in `main_process'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/supervisor.rb:518:in `run_worker'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-06-21 12:11:28 +0000 [error]: /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2018-06-21 12:11:28 +0000 [error]: /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2018-06-21 12:11:28 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/bin/fluentd:8:in `<top (required)>'
  2018-06-21 12:11:28 +0000 [error]: /usr/local/bin/fluentd:23:in `load'
  2018-06-21 12:11:28 +0000 [error]: /usr/local/bin/fluentd:23:in `<main>'
```

**Comment by repeatedly** [comment]
The problem is fluent-plugin-esslowquery lacks `require 'fluent/parser'`.
See https://docs.fluentd.org/v0.12/articles/plugin-development#parser-plugins

This is not fluentd core issue. Closed.
