### ISSUE TITLE
IP binding not working

### ISSUE THREAD

**Issue by cyyeong** [fluent/fluentd#2036]
Using td-agent version 3.2.0 on Linux RHEL7.

Setup a fluentd aggregator as central collector. The basic configuration was working fine with:
```
<source>
  @type forward
  bind 0.0.0.0
  port 24226
</source>
```

But when configured to bind with a specific IP, things started to break:
```
<source>
  @type forward
  bind 10.198.66.181
  port 24226
</source>
```

The logs:
_2018-06-26 03:47:48 +0100 [info]: Worker 0 finished unexpectedly with status 1
2018-06-26 03:47:48 +0100 [info]: gem 'fluent-plugin-elasticsearch' version '2.10.3'
2018-06-26 03:47:48 +0100 [info]: gem 'fluent-plugin-kafka' version '0.7.3'
2018-06-26 03:47:48 +0100 [info]: gem 'fluent-plugin-record-modifier' version '1.1.0'
2018-06-26 03:47:48 +0100 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.0'
2018-06-26 03:47:48 +0100 [info]: gem 'fluent-plugin-s3' version '1.1.3'
2018-06-26 03:47:48 +0100 [info]: gem 'fluent-plugin-td' version '1.0.0'
2018-06-26 03:47:48 +0100 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2018-06-26 03:47:48 +0100 [info]: gem 'fluent-plugin-webhdfs' version '1.2.3'
2018-06-26 03:47:48 +0100 [info]: gem 'fluentd' version '1.2.2'
2018-06-26 03:47:48 +0100 [info]: adding match pattern="td.*.*" type="tdlog"
2018-06-26 03:47:48 +0100 [warn]: #0 [output_td] secondary type should be same with primary one primary="Fluent::Plugin::TreasureDataLogOutput" secondary="Fluent::Plugin::FileOutput"
2018-06-26 03:47:48 +0100 [info]: adding match pattern="debug.**" type="stdout"
2018-06-26 03:47:48 +0100 [info]: adding match pattern="**" type="elasticsearch"
2018-06-26 03:47:49 +0100 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"somehost.dev.net", :port=>9200, :scheme=>"http"}
2018-06-26 03:47:49 +0100 [info]: #0 Detected ES 6.x: ES 7.x will only accept `_doc` in type_name.
2018-06-26 03:47:49 +0100 [info]: adding source type="http"
2018-06-26 03:47:49 +0100 [info]: adding source type="debug_agent"
2018-06-26 03:47:49 +0100 [info]: adding source type="forward"
2018-06-26 03:47:49 +0100 [info]: #0 starting fluentd worker pid=21158 ppid=20992 worker=0
2018-06-26 03:47:49 +0100 [info]: #0 listening port port=24226 bind="10.198.66.181"
2018-06-26 03:47:49 +0100 [error]: #0 unexpected error error_class=Errno::EADDRNOTAVAIL error="Cannot assign requested address - bind(2) for \"10.198.66.181\" port 24226"
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/server.rb:354:in `initialize'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/server.rb:354:in `new'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/server.rb:354:in `server_create_tcp_socket'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/server.rb:212:in `server_create_for_tcp_connection'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/server.rb:92:in `server_create_connection'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_forward.rb:158:in `start'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:165:in `block in start'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:153:in `each'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:140:in `each'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:140:in `lifecycle'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:164:in `start'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/engine.rb:274:in `start'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/engine.rb:219:in `run'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:799:in `run_engine'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:549:in `block in run_worker'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:724:in `main_process'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:544:in `run_worker'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/bin/fluentd:8:in `<top (required)>'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2018-06-26 03:47:49 +0100 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `<main>'_

**Comment by repeatedly** [comment]
> unexpected error error_class=Errno::EADDRNOTAVAIL error="Cannot assign requested address - bind(2) for "10.198.66.181" port 24226"

This means `10.198.66.181` is not exist or not local address: http://man7.org/linux/man-pages/man2/bind.2.html
So the problem is out side of fluentd.

**Comment by mayureshrandomtree** [comment]
got any solution to this?
