### ISSUE TITLE
What is the Proper way to terminate fluentd -v ?

### ISSUE THREAD

**Issue by ibrasec** [fluent/fluentd#2064]
Hi...

when i do $ fluentd -v   to troubleshoot, and then i want to close the verbose mode using Ctrl+C,  i receive some log errors, is there a way to safely terminate the verbose mode other than Ctrl+C

Also the verbose mode for some reason, duplicate the log recieved by kibana, and for some reason one of my grok pattern doesn't work unless i activate (fluentd -v)... 

fluentd.cnf
------------------------

```
<source>
  @type tail
  path /var/log/syslog
  tag test
  <parse>
    @type grok
    custom_pattern_path /etc/fluent/custom_pattern
    <grok>
      pattern XXXXXXX
    </grok>

    <grok>
      pattern YYYYYYY
    </grok>

    <grok>
      pattern ZZZZZZZ
    </grok>

  </parse>
</source>

<match test>
  @type copy
  <store>
     @type elasticsearch
     logstash_format true
     logstash_prefix syslogreg
     flush_interval 5s
  </store>
</match>
```

logs when when ctrl+C
------------------------
^C2018-07-09 09:02:08 +0000 [debug]: #0 fluent/log.rb:302:call: fluentd main process get SIGINT
2018-07-09 09:02:08 +0000 [info]: fluent/log.rb:322:call: Received graceful stop
2018-07-09 09:02:09 +0000 [debug]: #0 fluent/log.rb:302:call: fluentd main process get SIGTERM
2018-07-09 09:02:09 +0000 [debug]: #0 fluent/log.rb:302:call: getting start to shutdown main process
2018-07-09 09:02:09 +0000 [info]: #0 fluent/log.rb:322:call: fluentd worker is now stopping worker=0
2018-07-09 09:02:09 +0000 [info]: #0 fluent/log.rb:322:call: shutting down fluentd worker worker=0
2018-07-09 09:02:09 +0000 [debug]: #0 fluent/log.rb:302:call: calling stop on input plugin type=:tail plugin_id="object:12cd124"
2018-07-09 09:02:09 +0000 [debug]: #0 fluent/log.rb:302:call: calling stop on output plugin type=:copy plugin_id="object:113710c"
2018-07-09 09:02:09 +0000 [debug]: #0 fluent/log.rb:302:call: calling stop on output plugin type=:elasticsearch plugin_id="object:d1d710"
2018-07-09 09:02:09 +0000 [info]: #0 fluent/log.rb:322:call: Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
**2018-07-09 09:02:09 +0000 [warn]: #0 fluent/log.rb:342:call: unexpected error while calling stop on output plugin plugin=Fluent::ElasticsearchOutput plugin_id="object:d1d710"** **error_class=Elasticsearch::Transport::Transport::Errors::BadRequest error="[400] {\"error\":{\"root_cause\":[{\"type\":\"parse_exception\",\"reason\":\"Failed to derive xcontent\"}],\"type\":\"parse_exception\",\"reason\":\"Failed to derive xcontent\"},\"status\":400}"**
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/bulk.rb:90:in `bulk'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluent-plugin-elasticsearch-1.7.0/lib/fluent/plugin/out_elasticsearch.rb:334:in `send'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:205:in `block (2 levels) in shutdown'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:153:in `each'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:140:in `each'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:140:in `lifecycle'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:202:in `block in shutdown'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:256:in `call'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:256:in `shutdown'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/engine.rb:278:in `shutdown'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/engine.rb:247:in `run'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:799:in `run_engine'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:549:in `block in run_worker'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:724:in `call'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:724:in `main_process'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:544:in `run_worker'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/bin/fluentd:8:in `<top (required)>'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/bin/fluentd:23:in `load'
  2018-07-09 09:02:09 +0000 [warn]: #0 fluent/root_agent.rb:153:each: /usr/local/rvm/gems/ruby-2.2.4/bin/fluentd:23:in `<main>'
2018-07-09 09:02:09 +0000 [debug]: #0 fluent/log.rb:302:call: preparing shutdown input plugin type=:tail plugin_id="object:12cd124"
2018-07-09 09:02:09 +0000 [info]: #0 fluent/log.rb:322:call: shutting down input plugin type=:tail plugin_id="object:12cd124"
2018-07-09 09:02:09 +0000 [debug]: #0 fluent/log.rb:302:call: preparing shutdown output plugin type=:elasticsearch plugin_id="object:d1d710"
2018-07-09 09:02:09 +0000 [debug]: #0 fluent/log.rb:302:call: preparing shutdown output plugin type=:copy plugin_id="object:113710c"
2018-07-09 09:02:09 +0000 [info]: #0 fluent/log.rb:322:call: shutting down output plugin type=:copy plugin_id="object:113710c"
**2018-07-09 09:02:09 +0000 [warn]: #0 fluent/log.rb:342:call: unexpected error while shutting down on output plugin plugin=Fluent::ElasticsearchOutput plugin_id="object:d1d710" error_class=Elasticsearch::Transport::Transport::Errors::BadRequest error="[400] {\"error\":{\"root_cause\":[{\"type\":\"parse_exception\",\"reason\":\"Failed to derive xcontent\"}],\"type\":\"parse_exception\",\"reason\":\"Failed to derive xcontent\"},\"status\":400}"**
**2018-07-09 09:02:09 +0000 [warn]: #0 fluent/log.rb:342:call: unexpected error while shutting down on output plugin plugin=Fluent::ElasticsearchOutput plugin_id="object:d1d710" error_class=NoMethodError error="undefined method `[]' for nil:NilClass"
2018-07-09 09:02:09 +0000 [error]: #0 fluent/log.rb:362:call: unexpected error error_class=NoMethodError error="undefined method `[]' for nil:NilClass"**
  2018-07-09 09:02:09 +0000 [error]: #0 fluent/supervisor.rb:723:main_process: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/log.rb:502:in `caller_line'
  2018-07-09 09:02:09 +0000 [error]: #0 fluent/supervisor.rb:723:main_process: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/log.rb:421:in `dump_stacktrace'
  2018-07-09 09:02:09 +0000 [error]: #0 fluent/supervisor.rb:723:main_process: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/log.rb:348:in `warn_backtrace'
  2018-07-09 09:02:09 +0000 [error]: #0 fluent/supervisor.rb:723:main_process: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:249:in `rescue in block (3 levels) in shutdown'
  2018-07-09 09:02:09 +0000 [error]: #0 fluent/supervisor.rb:723:main_process: /usr/local/rvm/gems/ruby-2.2.4/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:228:in `block (3 levels) in shutdown'
2018-07-09 09:02:10 +0000 [info]: fluent/log.rb:322:call: Worker 0 finished with status 1

**Comment by repeatedly** [comment]
> Worker 0 finished with status 1

This is finished properly. Plugin is sandbox so errors in plugin doesn't effect fluentd shudown.

**Comment by repeatedly** [comment]
And don't use question for github issue. Follow guideline.
