### ISSUE TITLE
Failed to flush the buffer. Error_class=NoMethodError error="undefined method reason_phrase

### ISSUE THREAD

**Issue by laurentiu92** [fluent/fluentd#2065]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version: 3.1.1
- Environment information, e.g. OS : Centos7

- Your configuration
```xml
<source>
  @type secure_forward
  shared_key XXXXXX
  self_hostname "${HOSTNAME}"
  secure false
</source>

<match output_tag>
    @type copy
    <store>
     @type elasticsearch_dynamic
     include_tag_key true
     hosts <IP>,<IP>,<IP>
     port 9200
     logstash_format true
     logstash_prefix openshift-noprod-${record['kubernetes']['namespace_name'] || 'unknown'}
     <buffer>
       @type memory
       flush_interval 5s
       queue_limit_length 32
       chunk_limit_size 2M
       retry_forever
       flush_thread_count 8
       retry_max_interval 30
     </buffer>
    </store>
    <store>
     @type relabel
     @label @NOTIFICATION
    </store>
</match>

<label @NOTIFICATION>
      <filter output_tag>
        @type grep
        <regexp>
         key $.kubernetes.container_name
         pattern oma-payments
        </regexp>
      </filter>
      <match output_tag>
         @type swift
        auth_url https://localhost:5000/v2.0/tokens
        auth_user XXXXXXXXXXXX
        auth_api_key XXXXXXXXXXXX
        auth_region RegionOne
        auth_tenant OM_Addons_DevOps
        swift_container om_addons_payments
        swift_object_key_format %{path}%{time_slice}_%{index}.json
        ssl_verify false
        path logs/
        buffer_path /var/log/fluent/swift
        time_slice_format %Y%m%d-%H
        time_slice_wait 10m
        utc
      </match>
</label>
```

- Your problem explanation. If you have an error logs, write it together.
I am encountering a strange fluentd behavior when elastic and swift plugin are mixed together in the same configuration.
Important mentions:  - swift plugin is working using this config but elasticsearch not
                                   - elasticsearch plugin is working correctly if the second plugin in this config would 
                                      be  file for example

2018-07-10 17:16:46 +0200 [warn]: #0 failed to flush the buffer. retry_time=9 next_retry_seconds=2018-07-10 17:17:17 +0200 chunk="570a69b93b8bc6681002eb456c1a6c87" error_class=NoMethodError error="undefined method `reason_phrase' for #<
Excon::Response:0x00007fbb3d0be410>"
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/excon.rb:55:in `call'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/faraday.rb:23:in `block in perform_request'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:262:in `perform_request'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/client.rb:131:in `perform_request'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-api-5.0.4/lib/elasticsearch/api/actions/ping.rb:20:in `ping'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:64:in `client'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:221:in `rescue in send_bulk'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:216:in `send_bulk'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:209:in `block in write'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:208:in `each'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:208:in `write'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-07-10 17:16:46 +0200 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-07-10 17:16:46 +0200 [warn]: #0 failed to flush the buffer. retry_time=10 next_retry_seconds=2018-07-10 17:17:18 +0200 chunk="570a69d52f7ae63996a7b311e35d17b2" error_class=NoMethodError error="undefined method `reason_phrase' for #
<Excon::Response:0x00007fbb40ca3c28>"

**Comment by repeatedly** [comment]
This seems elasticsearch plugin isseu. closed.
