### ISSUE TITLE
 syslog failed to emit error_class=NoMethodError error="undefined method `to_msgpack'

### ISSUE THREAD

**Issue by aplsms** [fluent/fluentd#2072]
When I add elasticsearch output plugin I have errors like these:

 ```
2018-07-13 20:22:30 +0000 [error]: #0 syslog failed to emit error_class=NoMethodError error="undefined method `to_msgpack' for 2018-07-13 20:22:30 +0000:Time" tag="system.daemon.warn" record="{\"host\":\"ip-10-78-46-81\",\"ident\":\"dd.collector\",\"pid\":\"1595\",\"msgid\":\"-\",\"extradata\":\"-\",\"message\":\" WARNING (disk.py:105): Unable to get disk metrics for /run/docker/netns/default: [Errno 13] Permission denied: '/run/docker/netns/default'\",\"remotehostip\":\"10.78.46.81\",\"remotehostname\":\"10.78.46.81\"}"
2018-07-13 20:22:30 +0000 [warn]: #1 emit transaction failed: error_class=NoMethodError error="undefined method `to_msgpack' for 2018-07-13 20:22:30 +0000:Time" location="/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event.rb:61:in `write'" tag="system.daemon.warn"

2018-07-13 20:22:30 +0000 [warn]: #1 suppressed same stacktrace

2018-07-13 20:22:30 +0000 [error]: #1 syslog failed to emit error_class=NoMethodError error="undefined method `to_msgpack' for 2018-07-13 20:22:30 +0000:Time" tag="system.daemon.warn" record="{\"host\":\"ip-10-78-46-81\",\"ident\":\"dd.collector\",\"pid\":\"1595\",\"msgid\":\"-\",\"extradata\":\"-\",\"message\":\" WARNING (disk.py:105): Unable to get disk metrics for /var/lib/docker/containers/46bb1b4adeb06d225644244ed874325e7a7ec7bc5091a07e630d7ea6844fed70/shm: [Errno 13] Permission denied: '/var/lib/docker/containers/46bb1b4adeb06d225644244ed874325e7a7ec7bc5091a07e630d7ea6844fed70/shm'\",\"remotehostip\":\"10.78.46.81\",\"remotehostname\":\"10.78.46.81\"}"
```

Without Elasticsearch plugin there is no such issues.

Versions: 
fluentd-1.2.2 pid=1 ruby="2.4.4"
fluent-plugin-bigquery' version '1.2.0'
fluent-plugin-elasticsearch' version '2.11.1'
fluent-plugin-elasticsearch' version '2.10.3'
fluent-plugin-gelf-hs' version '1.0.7'
fluent-plugin-kafka' version '0.7.3'
fluent-plugin-record-modifier' version '1.1.0'
fluent-plugin-rewrite-tag-filter' version '2.1.0'
fluent-plugin-s3' version '1.1.3'
fluent-plugin-secure-forward' version '0.4.5'
fluent-plugin-td' version '1.0.0'
fluent-plugin-td-monitoring' version '0.2.4'
fluent-plugin-webhdfs' version '1.2.3'
fluentd' version '1.2.2'

Elasticsearch server 6.3.0

Fluentd running in docker container 

Configuration:

```
<system>
  log_level info
  workers 2
</system>

<source>
  @type forward
  port 30284
  bind 0.0.0.0
  source_address_key remotehostip
  source_hostname_key remotehostname
  <transport tls>
    ca_cert_path        /fluentd/ssl/cert.pem
    ca_private_key_path /fluentd/ssl/key.pem
    ca_private_key_passphrase ##########
  </transport>
  <security>
    shared_key ####################
    self_hostname logs.corp
  </security>
</source>

# regular fluentd forwarder
<source>
  @type forward
  port 34224
  bind 0.0.0.0
  source_address_key remotehostip
  source_hostname_key remotehostname
</source>

# minitoring REST API
<source>
  @type monitor_agent
  bind 0.0.0.0
  port 34220
</source>

# syslog  forwarder
<source>
  @type syslog
  port 5140
  bind 0.0.0.0
  tag system
  source_address_key remotehostip
  source_hostname_key remotehostname
  <parse>
    message_format auto
  </parse>
</source>

<filter system.**>
  @type record_transformer
  enable_ruby
  <record>
    localtime
    facility ${tag_parts[1]}
    priority ${tag_parts[2]}
    tag ${tag}
    time ${time}
    formatted_time ${time.strftime('%Y-%m-%dT%H:%M:%S+07:00')}
  </record>
</filter>

<match system.daemon.** system.kernel.** system.kern.** system.mail.** system.cron.** >
  @type copy
  <store>
    @type s3
    s3_bucket trueaccord-infra-logs
    s3_region us-west-2
    path %Y/%m/%d
    time_slice_format %Y%m%d-%H
    s3_object_key_format %{path}/syslog-%{time_slice}_%{index}.%{file_extension}

    <buffer tag,time>
      @type             file
      path              /fluentd/buffers/s3/infra/syslogs/
      timekey           1h   # 1 hour partition
      timekey_wait      10m
      timekey_use_utc   true
      chunk_limit_size  256m
    </buffer>

    <format>
      @type json
    </format>
  </store>
  <store>
    @type elasticsearch
    host {{elastic_host}}
    port {{elastic_port}}
    logstash_format true
    include_timestamp true
    utc_index true
  </store>
</match>
```

I've tried run 2 different versions of Elasticsearch output plugins -- result the same.

**Comment by aplsms** [comment]
trace:

```
2018-07-13 22:00:00 +0000 [warn]: #1 emit transaction failed: error_class=NoMethodError error="undefined method `to_msgpack' for 2018-07-13 22:00:00 +0000:Time" location="/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event.rb:61:in `write'" tag="docker.nexus.c311cc613c30"
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event.rb:61:in `write'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event.rb:61:in `block in to_msgpack_stream'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event.rb:193:in `block in each'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event.rb:192:in `each'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event.rb:192:in `each'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event.rb:60:in `to_msgpack_stream'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:893:in `block in <class:Output>'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/buffer.rb:566:in `block in write_once'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/buffer.rb:557:in `write_once'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/buffer.rb:282:in `block in write'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/buffer.rb:280:in `each'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/buffer.rb:280:in `write'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:970:in `block in handle_stream_simple'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:854:in `write_guard'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:969:in `handle_stream_simple'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:844:in `execute_chunking'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:774:in `emit_buffered'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/out_copy.rb:58:in `block in process'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/out_copy.rb:56:in `each'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/out_copy.rb:56:in `each_with_index'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/out_copy.rb:56:in `process'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/multi_output.rb:148:in `emit_sync'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event_router.rb:159:in `emit_events'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event_router.rb:96:in `emit_stream'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event_router.rb:87:in `emit'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_forward.rb:337:in `on_message'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_forward.rb:211:in `block in handle_connection'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_forward.rb:248:in `block (3 levels) in read_messages'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_forward.rb:247:in `feed_each'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_forward.rb:247:in `block (2 levels) in read_messages'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_forward.rb:256:in `block in read_messages'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/server.rb:593:in `on_read_without_connection'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/io.rb:123:in `on_readable'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/io.rb:186:in `on_readable'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2018-07-13 22:00:00 +0000 [warn]: #1 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-07-13 22:00:00 +0000 [error]: #1 unexpected error on reading data host="ip-10-78-44-252.us-west-2.compute.internal" port=56022 error_class=NoMethodError error="undefined method `to_msgpack' for 2018-07-13 22:00:00 +0000:Time"
  2018-07-13 22:00:00 +0000 [error]: #1 suppressed same stacktrace
```

**Comment by repeatedly** [comment]
The point is `enable_ruby`.
With `enable_ruby`, `time` inside `${}` is `Time` object, not String: https://github.com/fluent/fluentd/blob/d2137c2ead8eff95bf8f14ee0a17d5e160e4db9c/lib/fluent/plugin/filter_record_transformer.rb#L255
In addition, `${}` result is used directly so filtered record has Time object unexpectedly.
To avoid above error, removing `time ${time}` or call `to_f` like method, e.g. `${time.to_f}`, to change result is needed.

**Comment by meskai** [comment]
Hi, I faced same problem. But instead of syslog i m using rabbitmq as a source. Is there any progress?

**Comment by repeatedly** [comment]
What does "same problem" mean?
Do you use "time ${time}" with `enable_ruby`?
If so, you can avoid the error by using above comment way.

**Comment by meskai** [comment]
Sorry my bad. I have to give detailed information.
I m not using filter neiter time ${time}.
I have very basic configuration.

Configuration
---------------
```
<system>
  log_level info
  <log>
    time_format %Y-%m-%dT%H:%M:%S.%N%z
  </log>
</system>

<source>
  @type rabbitmq
  tag rabbitlog
  host 127.0.0.1
  user guest
  pass guest
  vhost /
  exchange app-logging
  queue log_que
  durable true
  routing_key rabbitlog
  heartbeat 10
  <parse>
    @type json
	time_key @timestamp
	keep_time_key false
  </parse>
</source>

#<match rabbitlog>
#  @type stdout
#</match>

<match rabbitlog>
  @type elasticsearch
  host localhost
  port 9200
  logstash_format true
</match>
```

fluentd-1.0.2 ruby="2.4.2"

plugins
----------

> 'fluent-plugin-elasticsearch' version '2.4.0'
> 'fluent-plugin-kafka' version '0.6.5'
> 'fluent-plugin-rabbitmq' version '0.0.3'
> 'fluent-plugin-rewrite-tag-filter' version '2.0.1'
> 'fluent-plugin-s3' version '1.1.0'
> 'fluent-plugin-td' version '1.0.0'                                       
> 'fluent-plugin-td-monitoring' version '0.2.3'                            
> 'fluent-plugin-webhdfs' version '1.2.2'                                  
> 'fluent-plugin-windows-eventlog' version '0.2.2' 


Trace
------

> 2018-07-25T14:01:59.141706000+0300 [warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `to_msgpack' for 2018-07-25 17:01:56 +0300:Time" location="C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event.rb:61:in `write'" tag="rabbitlog"                                                                    
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event.rb:61:in `write'                                                                                                 
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event.rb:61:in `block in to_msgpack_stream'
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event.rb:107:in `each'
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event.rb:60:in `to_msgpack_stream'                                                                                     
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:890:in `block in <class:Output>'                                                                      
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/buffer.rb:541:in `block in write_once'                                                                          
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'                                                                                                                       
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/buffer.rb:532:in `write_once'                                                                                   
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/buffer.rb:277:in `block in write'                                                                               
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/buffer.rb:275:in `each'                                                                                         
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/buffer.rb:275:in `write'                                                                                        
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:967:in `block in handle_stream_simple'
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:851:in `write_guard'                                                                                  
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:966:in `handle_stream_simple'                                                                         
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:841:in `execute_chunking'                                                                             
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:771:in `emit_buffered'                                                                                
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event_router.rb:96:in `emit_stream'                                                                                    
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event_router.rb:87:in `emit'                                                                                           
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-rabbitmq-0.0.3/lib/fluent/plugin/in_rabbitmq.rb:118:in `block (2 levels) in start'                                                
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/parser_json.rb:64:in `parse'                                                                                    
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-rabbitmq-0.0.3/lib/fluent/plugin/in_rabbitmq.rb:116:in `block in start'                                                           
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/consumer.rb:56:in `call'                                                                                                  
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/channel.rb:1717:in `block in handle_frameset'                                                                             
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/consumer_work_pool.rb:107:in `block (2 levels) in run_loop'                                                               
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/consumer_work_pool.rb:102:in `loop'                                                                                       
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/consumer_work_pool.rb:102:in `block in run_loop'                                                                          
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/consumer_work_pool.rb:101:in `catch'                                                                                      
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/consumer_work_pool.rb:101:in `run_loop'                                                                                 
> 2018-07-25T14:01:59.157705000+0300 [error]: #0 Uncaught exception from consumer 
> #<Bunny::Consumer:54245120 @channel_id=1 @queue=log_que> @consumer_tag=bunny-1532516459000-621352643544>: #<NoMethodError: undefined method `to_msgpack' for 2018-07-25 17:01:56 +0300:Time> @ 
> C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event.rb:61:in `write'

**Comment by repeatedly** [comment]
@meskai I'm not familiar with rabbitmq plugin but it seems rabbitmq plugin has a bug.
I assume https://github.com/nttcom/fluent-plugin-rabbitmq/blob/c515d9a323e93495c44b0ee372e861ef15f17b22/lib/fluent/plugin/in_rabbitmq.rb#L117 this line is wrong. `properties[:timestamp]` may return `Time` object.

**Comment by meskai** [comment]
Thanx for help @repeatedly .

**Comment by fujimotos** [comment]
FWIW, I have fixed the plugin bug pointed out by @repeatedly in nttcom/fluent-plugin-rabbitmq/pull/7.

So "No Method" errors around RabbitMQInput should be gone when the patch gets merged.
