### ISSUE TITLE
fluentd worker process gets restarted when clients (fluent-bit) send wrong shared key in TLS mutual auth + shared key setup.

### ISSUE THREAD

**Issue by samitpal** [fluent/fluentd#2085]
- Fluentd  version: version 1.1
- Environment information : Ubuntu 16.01
- Fluentd configuration used below

---- fluentd config -----
```
<source>
  @type monitor_agent
  bind 0.0.0.0
  port 24220
</source>

<source>
  @type forward
  @id forward
  port 24224
  bind 0.0.0.0

  @log_level debug
  <security>
    self_hostname myhost
    shared_key veryverysecret
  </security>
  <transport tls>
    version TLSv1_2
    ca_path  /home/ubuntu/client_auth/certs/ca.crt.pem
    cert_path  /home/ubuntu/client_auth/certs/server.crt.pem
    private_key_path  /home/ubuntu/client_auth/private/server.key.pem
    client_cert_auth true
  </transport>
</source>

 <filter logs.**>
     @type record_transformer
     @id record_transformer
     enable_ruby true
     <record>
         # the timestamp field has be named as @timestamp for kibana to work properly.
         @timestamp ${time.strftime('%Y %b %d %H:%M:%S')}
     </record>
 </filter>

<match logs.**>
  @type copy
  @id copy
  <store>
   @type stdout
   @id stdout
  </store>
</match>
```

- I use fluent-bit as forwarders to send logs to fluentd which act as routers. As you will notice from the configs above I'm using TLS mutual auth with shared key. Whenever there is mismatch in the shared key, the fluentd worker process gets killed and restarted with the following error logs.

```
2018-07-24 05:07:30 +0000 [debug]: #0 [forward] generating helo
2018-07-24 05:07:30 +0000 [debug]: #0 [forward] checking ping
2018-07-24 05:07:30 +0000 [warn]: #0 [forward] Shared key mismatch address="xx.xx.xx.xx" hostname=""
2018-07-24 05:07:30 +0000 [debug]: #0 [forward] generating pong
2018-07-24 05:07:30 +0000 [warn]: #0 [forward] thread exited by unexpected error plugin=Fluent::Plugin::ForwardInput title=:event_loop error_class=ThreadError error="deadlock; recursive locking"
2018-07-24 05:07:30 +0000 [error]: #0 fluent/log.rb:362:error: unexpected error error_class=ThreadError error="deadlock; recursive locking"
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/plugin_helper/server.rb:762:in `synchronize'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/plugin_helper/server.rb:762:in `close'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/plugin_helper/server.rb:408:in `close'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/plugin/in_forward.rb:202:in `block (2 levels) in handle_connection'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/plugin_helper/server.rb:421:in `block in on'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: (eval):9:in `on_write_complete'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/io.rb:147:in `on_writable'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/plugin_helper/server.rb:728:in `block in on_writable'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/plugin_helper/server.rb:724:in `synchronize'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/plugin_helper/server.rb:724:in `on_writable'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/io.rb:190:in `on_writable'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:523:block in run_worker: /var/lib/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-07-24 05:07:30 +0000 [error]: #0 fluent/log.rb:362:error: unexpected error error_class=ThreadError error="deadlock; recursive locking"
  2018-07-24 05:07:30 +0000 [error]: #0 fluent/supervisor.rb:698:main_process: suppressed same stacktrace
2018-07-24 05:07:30 +0000 [info]: fluent/log.rb:322:info: Worker 0 finished unexpectedly with status 1
```

**Comment by utshav2008** [comment]
Are there any further updates on this? I guess I am still facing this

**Comment by repeatedly** [comment]
> I guess I am still facing this

What does this sentence mean?
Using proper shared_key doesn't fix the problem?

**Comment by utshav2008** [comment]
If anyone tries to connect using incorrect shared key, fluentd tends to restart. It works with the correct shared key.

**Comment by samitpal** [comment]
Imho, fluentd process should not get restarted just because it received a mismatched shared key

**Comment by dpgaspar** [comment]
I've got the same problem, using td-agent 3.2.1

**Comment by repeatedly** [comment]
Patch is here: https://github.com/fluent/fluentd/pull/2165
