### ISSUE TITLE
fluentd v1.2.4 forward to fluentd v0.12.x sometimes get an error (already add time_as_integer true)

### ISSUE THREAD

**Issue by breath-co2** [fluent/fluentd#2104]
out forward fluentd version is v1.2.4, in forward fluentd version is v0.12.43

out config:
```apache
<source>
  @type http
  port 9800
  body_size_limit 8m
  <parse>
    @type json
    keep_time_key true
    time_type unixtime
    timezone +08:00
  </parse>
</source>

<match data.*>
    @type forward
    heartbeat_interval 10s
    require_ack_response false
    ack_response_timeout 180
    time_as_integer true
    <buffer tag>
      @type file
      path /data/buffer/forward.*.buffer
      flush_thread_count 4
      flush_interval 1
      flush_thread_burst_interval 0.1
      retry_forever true
      retry_max_interval 30
      chunk_limit_size 2m
      queue_limit_length 10000
      queued_chunks_limit_size 4
    </buffer>
    <server>
      host 10.3.2.100
      port 12360
    </server>
</match>
```

in forward config:
```apache
<source>
  @type forward
  port 12360
  skip_invalid_event true
</source>
<match data.**>
  @type stdout
</match>
```

sometimes fluentd log is that: 
```
2018-08-15 15:03:01 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 50550" tag=1534316580 time={"account"=>"77853535", "after"=>15, "amount"=>0, "amount2"=>0, "cid"=>1, "count"=>1, "eid"=>1534316580565, "from_pid"=>0, "ispay"=>0, "itemid"=>80, "logid"=>"1534316580565", "pid"=>34359820439, "sid"=>8, "time"=>1534316580, "type"=>1, "value"=>1} record=nil
2018-08-15 15:03:01 +0800 [warn]: incoming chunk is broken: source="host: 10.3.2.1, addr: 10.3.2.1, port: 50550" msg={"size"=>400, "compressed"=>"text"}
2018-08-15 15:18:31 +0800 [warn]: buffer flush took longer time than slow_flush_log_threshold: plugin_id="object:cbb128" elapsed_time=31.097528849 slow_flush_log_threshold=20.0
2018-08-15 15:21:24 +0800 [warn]: buffer flush took longer time than slow_flush_log_threshold: plugin_id="object:cbb128" elapsed_time=20.508955354 slow_flush_log_threshold=20.0


2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318612 time={"account"=>"76151149", "after"=>39320, "amount"=>0, "cid"=>1, "coin_type"=>1, "eid"=>1534318612713, "ispay"=>0, "logid"=>"1534318612713", "oid"=>"", "pid"=>4295125238, "sid"=>1, "time"=>1534318612, "type"=>0, "value"=>-3000} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318612 time={"account"=>"77853319", "after"=>112950, "amount"=>0, "cid"=>1, "coin_type"=>1, "eid"=>1534318612807, "ispay"=>0, "logid"=>"1534318612807", "oid"=>"", "pid"=>4295122394, "sid"=>1, "time"=>1534318612, "type"=>21002, "value"=>20000} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318612 time={"account"=>"77853319", "after"=>1900, "amount"=>0, "cid"=>1, "coin_type"=>0, "eid"=>1534318612807, "ispay"=>0, "logid"=>"1534318612807", "oid"=>"", "pid"=>4295122394, "sid"=>1, "time"=>1534318612, "type"=>12001, "value"=>-10} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318612 time={"account"=>"", "after"=>81020, "amount"=>0, "cid"=>1, "coin_type"=>1, "eid"=>1534318612829, "ispay"=>1, "logid"=>"1534318612829", "oid"=>"", "pid"=>34359870942, "sid"=>8, "time"=>1534318612, "type"=>22002, "value"=>-6000} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318613 time={"account"=>"78057100", "after"=>28020, "amount"=>0, "cid"=>1, "coin_type"=>1, "eid"=>1534318613016, "ispay"=>0, "logid"=>"1534318613016", "oid"=>"", "pid"=>34359871350, "sid"=>8, "time"=>1534318613, "type"=>0, "value"=>-3000} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318612 time={"account"=>"74742603", "after"=>1040, "amount"=>0, "cid"=>1, "coin_type"=>0, "eid"=>1534318612901, "ispay"=>0, "logid"=>"1534318612901", "oid"=>"", "pid"=>4294984778, "sid"=>1, "time"=>1534318612, "type"=>11001, "value"=>100} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318612 time={"account"=>"76150703", "after"=>1035, "amount"=>0, "cid"=>1, "coin_type"=>0, "eid"=>1534318612995, "ispay"=>0, "logid"=>"1534318612995", "oid"=>"", "pid"=>4295125221, "sid"=>1, "time"=>1534318612, "type"=>11011, "value"=>200} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318613 time={"account"=>"45924500", "after"=>41195, "amount"=>0, "cid"=>1, "coin_type"=>1, "eid"=>1534318613079, "ispay"=>0, "logid"=>"1534318613079", "oid"=>"", "pid"=>34359870343, "sid"=>8, "time"=>1534318613, "type"=>21002, "value"=>20000} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318613 time={"account"=>"45924500", "after"=>1045, "amount"=>0, "cid"=>1, "coin_type"=>0, "eid"=>1534318613079, "ispay"=>0, "logid"=>"1534318613079", "oid"=>"", "pid"=>34359870343, "sid"=>8, "time"=>1534318613, "type"=>12001, "value"=>-10} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318612 time={"account"=>"78024194", "after"=>100, "amount"=>0, "cid"=>1, "coin_type"=>0, "eid"=>1534318612917, "ispay"=>0, "logid"=>"1534318612917", "oid"=>"", "pid"=>4295142960, "sid"=>1, "time"=>1534318612, "type"=>11004, "value"=>100} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318613 time={"account"=>"78025248", "after"=>1000, "amount"=>0, "cid"=>1, "coin_type"=>0, "eid"=>1534318613057, "ispay"=>0, "logid"=>"1534318613057", "oid"=>"", "pid"=>4295143028, "sid"=>1, "time"=>1534318613, "type"=>11004, "value"=>100} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318613 time={"account"=>"77627079", "after"=>130035, "amount"=>0, "cid"=>1, "coin_type"=>1, "eid"=>1534318613235, "ispay"=>0, "logid"=>"1534318613235", "oid"=>"", "pid"=>34359788935, "sid"=>8, "time"=>1534318613, "type"=>21004, "value"=>360} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318613 time={"account"=>"77627079", "after"=>130395, "amount"=>0, "cid"=>1, "coin_type"=>1, "eid"=>1534318613235, "ispay"=>0, "logid"=>"1534318613235", "oid"=>"", "pid"=>34359788935, "sid"=>8, "time"=>1534318613, "type"=>21004, "value"=>360} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318613 time={"account"=>"77627079", "after"=>130755, "amount"=>0, "cid"=>1, "coin_type"=>1, "eid"=>1534318613235, "ispay"=>0, "logid"=>"1534318613235", "oid"=>"", "pid"=>34359788935, "sid"=>8, "time"=>1534318613, "type"=>21004, "value"=>360} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318613 time={"account"=>"77627079", "after"=>131115, "amount"=>0, "cid"=>1, "coin_type"=>1, "eid"=>1534318613235, "ispay"=>0, "logid"=>"1534318613235", "oid"=>"", "pid"=>34359788935, "sid"=>8, "time"=>1534318613, "type"=>21004, "value"=>360} record=nil
2018-08-15 15:36:54 +0800 [warn]: got invalid event and drop it: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" tag=1534318613 time={"account"=>"77627079", "after"=>131475, "amount"=>0, "cid"=>1, "coin_type"=>1, "eid"=>1534318613235, "ispay"=>0, "logid"=>"1534318613235", "oid"=>"", "pid"=>34359788935, "sid"=>8, "time"=>1534318613, "type"=>21004, "value"=>360} record=nil
2018-08-15 15:36:54 +0800 [warn]: incoming chunk is broken: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" msg={"size"=>129, "compressed"=>"text"}
```

**Comment by breath-co2** [comment]
other error logs:
```
2018-08-15 15:36:54 +0800 [warn]: incoming chunk is broken: source="host: 10.3.2.1, addr: 10.3.2.1, port: 31124" msg={"size"=>129, "compressed"=>"text"}
2018-08-15 15:51:12 +0800 [error]: forward error error=#<TypeError: no implicit conversion of String into Integer> error_class=TypeError
  2018-08-15 15:51:12 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:349:in `[]'
  2018-08-15 15:51:12 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:349:in `respond'
  2018-08-15 15:51:12 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:339:in `block in on_read_msgpack'
  2018-08-15 15:51:12 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:337:in `feed_each'
  2018-08-15 15:51:12 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:337:in `on_read_msgpack'
  2018-08-15 15:51:12 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.5.3/lib/cool.io/io.rb:123:in `on_readable'
  2018-08-15 15:51:12 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.5.3/lib/cool.io/io.rb:186:in `on_readable'
  2018-08-15 15:51:12 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2018-08-15 15:51:12 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2018-08-15 15:51:12 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:120:in `run'
```
