### ISSUE TITLE
Input plugin discards all messages if they don't fit in the chunk size

### ISSUE THREAD

**Issue by roicostas** [fluent/fluentd#2107]
Lets say chunk_limit_size is 8MB and there is a group of 10s of messages that fill 4MB of the chunk. If a new message of size > 4MB arrives. Fluentd raises an exception saying that it cannot emit because the event stream is bigger than the chunk size and discards **ALL** messages.

We are dealing with odd long lines that are complete dumps of big xml files or database tables which make fluentd discard other messages. Can we limit the size of processed messages in any way? We would like to go with this, is it possible?

Another workaround may be to increase a lot the chunk_limit although we may have to move to file buffers or to emit only line by line which may produce performance overhead.

Any suggestion? 

Error message, with chunk_limit of 1MB to reproduce:
```
2018-08-17 10:41:27 +0000 [warn]: #0 chunk bytes limit exceeds for an emitted event stream: 3087649bytes
2018-08-17 10:41:27 +0000 [warn]: #0 emit transaction failed: error_class=Fluent::Plugin::Buffer::BufferChunkOverflowError error="a 3086878bytes record is larger than buffer chunk limit size" location="/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/buffer.rb:677:in `block in write_step_by_step'" tag="xxx"
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/buffer.rb:677:in `block in write_step_by_step'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/buffer.rb:658:in `write_step_by_step'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/buffer.rb:607:in `write_once'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/buffer.rb:282:in `block in write'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/buffer.rb:280:in `each'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/buffer.rb:280:in `write'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:970:in `block in handle_stream_simple'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:854:in `write_guard'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:969:in `handle_stream_simple'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:844:in `execute_chunking'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:774:in `emit_buffered'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event_router.rb:159:in `emit_events'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/event_router.rb:96:in `emit_stream'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_tail.rb:385:in `receive_lines'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_tail.rb:503:in `wrap_receive_lines'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_tail.rb:714:in `block in handle_notify'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_tail.rb:758:in `with_io'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_tail.rb:692:in `handle_notify'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_tail.rb:688:in `block in on_notify'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_tail.rb:688:in `synchronize'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_tail.rb:688:in `on_notify'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_tail.rb:534:in `on_notify'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/in_tail.rb:620:in `on_change'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2018-08-17 10:41:27 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
````
 
Environment:
OS: rhel 7.5
Version: td-agent 1.2.2
Plugins: in_tail -> out_forward

**Comment by dmnfortytwo** [comment]
We've got the same problem. Logs are flooded with `record is larger than buffer chunk limit size` errors.
Fluentd 1.2.5, Ruby 2.4.4

@repeatedly, could you kindly take a look?

**Comment by okkez** [comment]
Fluentd does not discard *ALL* messages when `BufferChunkOverflowError`.

```
<source>
  @type dummy
  dummy [
    {"message": "message1"},
    {"message": "message2"}, 
    {"message": "message3"}, 
    {"message": "larger than chunk_size_limit"},
    {"message": "message4"}, 
    {"message": "message5"}
  ]
  tag dummy
</source>

<match dummy>
  @type stdout
  <buffer tag>
    @type memory
    chunk_limit_size 70
  </buffer>
</match>
```

Run Fluentd with the above configuration:

```
2018-11-29 12:16:19 +0900 [info]: #0 fluentd worker is now running worker=0
2018-11-29 12:16:20.091005533 +0900 dummy: {"message":"message1"}
2018-11-29 12:16:21.092650781 +0900 dummy: {"message":"message2"}
2018-11-29 12:16:23 +0900 [warn]: #0 emit transaction failed: error_class=Fluent::Plugin::Buffer::BufferChunkOverflowError error="a 
73bytes record is larger than buffer chunk limit size" location="/home/kenji/ruby/td-family/fluentd/lib/fluent/plugin/buffer.rb:677:
in `block in write_step_by_step'" tag="dummy"
(snip backtrace)
2018-11-29 12:16:22.094201767 +0900 dummy: {"message":"message3"}
2018-11-29 12:16:24.097083894 +0900 dummy: {"message":"message4"}
2018-11-29 12:16:25.098125827 +0900 dummy: {"message":"message5"}
2018-11-29 12:16:26.099308199 +0900 dummy: {"message":"message1"}
2018-11-29 12:16:27.000716911 +0900 dummy: {"message":"message2"}
2018-11-29 12:16:29 +0900 [warn]: #0 emit transaction failed: error_class=Fluent::Plugin::Buffer::BufferChunkOverflowError error="a 73bytes record is larger than buffer chunk limit size" location="/home/kenji/ruby/td-family/fluentd/lib/fluent/plugin/buffer.rb:677:in `block in write_step_by_step'" tag="dummy"
  2018-11-29 12:16:29 +0900 [warn]: #0 suppressed same stacktrace
2018-11-29 12:16:28.002327120 +0900 dummy: {"message":"message3"}
2018-11-29 12:16:30.005503499 +0900 dummy: {"message":"message4"}
2018-11-29 12:16:31.006576837 +0900 dummy: {"message":"message5"}
```

**Comment by ganmacs** [comment]
No response from the author. I'm closing
