### ISSUE TITLE
queued_chunks_limit_size does not limit the number of chunk files created

### ISSUE THREAD

**Issue by mrudrego** [fluent/fluentd#2128]
Hi,

We are using fluentd-1.2.2 (td-agent-3.1.1-0.el7.x86_64.rpm).

fluentd buffer is used to buffer files. But we were facing issues when elasticsearch is down. The number of files created is increasing which results in all the fd resources being consumed.
The chunk files are getting created infinitely when destination is not reachable even when queued_chunks_limit_size 2

td-agent.conf:

```aconf
 <source>
    @type dummy
    tag "log.test"
    auto_increment_key "test"

    dummy {"hello":"world"}
  </source>
  <match log.*>
    @type copy
    <store>
      @type "elasticsearch"
      @log_level "info"
      include_tag_key true
      host "172.17.0.2"

      port 9200
      logstash_format true
      logstash_prefix "journal"
      <buffer tag>
        @type "file"
        path "/tmp/fluentd122/"
        flush_mode interval
        flush_interval 1s
        retry_forever true
        retry_max_interval 5s
        chunk_limit_size 2k

        queued_chunks_limit_size 2
      </buffer>
    </store>
    <store>
      @type "stdout"
    </store>
  </match>
```

The fluentd logs are as below:
```log
[root@vm-10-197-171-9 /home/cloud-user/mahesh]$ td-agent -c td-agent.conf
2018-09-11 12:44:21 +0000 [info]: parsing config file is succeeded path="td-agent.conf"
2018-09-11 12:44:22 +0000 [warn]: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2018-09-11 12:44:22 +0000 [warn]: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2018-09-11 12:44:22 +0000 [info]: using configuration file: <ROOT>

  <source>
    @type dummy
    tag "log.test"
    auto_increment_key "test"

    dummy {"hello":"world"}
  </source>
  <match log.*>
    @type copy
    <store>
      @type "elasticsearch"
      @log_level "info"
      include_tag_key true
      host "172.17.0.2"

      port 9200
      logstash_format true
      logstash_prefix "journal"
      <buffer tag>
        @type "file"
        path "/tmp/fluentd122/"
        flush_mode interval
        flush_interval 1s
        retry_forever true
        retry_max_interval 5s
        chunk_limit_size 2k

        queued_chunks_limit_size 2
      </buffer>
    </store>
    <store>
      @type "stdout"
    </store>
  </match>
</ROOT>
2018-09-11 12:44:22 +0000 [info]: starting fluentd-1.2.2 pid=5446 ruby="2.4.4"
2018-09-11 12:44:22 +0000 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/sbin/td-agent", "-c", "td-agent.conf", "--under-supervisor"]
2018-09-11 12:44:22 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.10.3'
2018-09-11 12:44:22 +0000 [info]: gem 'fluent-plugin-kafka' version '0.7.3'
2018-09-11 12:44:22 +0000 [info]: gem 'fluent-plugin-record-modifier' version '1.1.0'
2018-09-11 12:44:22 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.0'
2018-09-11 12:44:22 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.3'
2018-09-11 12:44:22 +0000 [info]: gem 'fluent-plugin-td' version '1.0.0'
2018-09-11 12:44:22 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2018-09-11 12:44:22 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.2.3'
2018-09-11 12:44:22 +0000 [info]: gem 'fluentd' version '1.2.2'
2018-09-11 12:44:22 +0000 [info]: adding match pattern="log.*" type="copy"
2018-09-11 12:44:22 +0000 [info]: adding source type="dummy"
2018-09-11 12:44:22 +0000 [warn]: #0 both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2018-09-11 12:44:22 +0000 [warn]: #0 both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2018-09-11 12:44:22 +0000 [info]: #0 starting fluentd worker pid=5450 ppid=5446 worker=0
2018-09-11 12:44:22 +0000 [info]: #0 fluentd worker is now running worker=0
2018-09-11 12:44:23.031627925 +0000 log.test: {"hello":"world","test":0}
2018-09-11 12:44:24.038717060 +0000 log.test: {"hello":"world","test":1}
2018-09-11 12:44:25.040413341 +0000 log.test: {"hello":"world","test":2}
2018-09-11 12:44:25 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-09-11 12:44:26 +0000 chunk="57597d552b47fa0eb9fc417c8fe24de8" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"172.17.0.2\", :port=>9200, :scheme=>\"http\"})!"
  2018-09-11 12:44:25 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.10.3/lib/fluent/plugin/out_elasticsearch.rb:262:in `client'
  2018-09-11 12:44:25 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.10.3/lib/fluent/plugin/out_elasticsearch.rb:521:in `rescue in send_bulk'
  2018-09-11 12:44:25 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.10.3/lib/fluent/plugin/out_elasticsearch.rb:512:in `send_bulk'
  2018-09-11 12:44:25 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.10.3/lib/fluent/plugin/out_elasticsearch.rb:414:in `write'
  2018-09-11 12:44:25 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:1099:in `try_flush'
  2018-09-11 12:44:25 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:1378:in `flush_thread_run'
  2018-09-11 12:44:25 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:440:in `block (2 levels) in start'
  2018-09-11 12:44:25 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-09-11 12:44:26.044883361 +0000 log.test: {"hello":"world","test":3}
2018-09-11 12:44:26 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-09-11 12:44:26 +0000 chunk="57597d552b47fa0eb9fc417c8fe24de8" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"172.17.0.2\", :port=>9200, :scheme=>\"http\"})!"
  2018-09-11 12:44:26 +0000 [warn]: #0 suppressed same stacktrace
2018-09-11 12:44:26 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-09-11 12:44:26 +0000 chunk="57597d552b47fa0eb9fc417c8fe24de8" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"172.17.0.2\", :port=>9200, :scheme=>\"http\"})!"
  2018-09-11 12:44:26 +0000 [warn]: #0 suppressed same stacktrace
2018-09-11 12:44:27.046902096 +0000 log.test: {"hello":"world","test":4}
2018-09-11 12:44:28.048874091 +0000 log.test: {"hello":"world","test":5}
2018-09-11 12:44:28 +0000 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2018-09-11 12:44:28 +0000 chunk="57597d552b47fa0eb9fc417c8fe24de8" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"172.17.0.2\", :port=>9200, :scheme=>\"http\"})!"
  2018-09-11 12:44:28 +0000 [warn]: #0 suppressed same stacktrace
2018-09-11 12:44:29.050509308 +0000 log.test: {"hello":"world","test":6}
2018-09-11 12:44:30.052141194 +0000 log.test: {"hello":"world","test":7}
2018-09-11 12:44:31.053766455 +0000 log.test: {"hello":"world","test":8}
2018-09-11 12:44:32.055380838 +0000 log.test: {"hello":"world","test":9}
```

 The buffered directory list is as below:

```log
[root@vm-10-197-171-9 /tmp/fluentd122]$ ls -lhrt
total 96K
-rw-------. 1 root root   60 Sep 11 12:44 buffer.q57597d552b47fa0eb9fc417c8fe24de8.log
-rw-------. 1 root root   72 Sep 11 12:44 buffer.q57597d552b47fa0eb9fc417c8fe24de8.log.meta
-rw-------. 1 root root   60 Sep 11 12:44 buffer.q57597d5715aa1d017eec6480debcd428.log
-rw-------. 1 root root   72 Sep 11 12:44 buffer.q57597d5715aa1d017eec6480debcd428.log.meta
-rw-------. 1 root root 2.0K Sep 11 12:45 buffer.q57597d58ff8c5d286795c35b92c0f5d5.log
-rw-------. 1 root root   72 Sep 11 12:45 buffer.q57597d58ff8c5d286795c35b92c0f5d5.log.meta
-rw-------. 1 root root 2.0K Sep 11 12:46 buffer.q57597d96f7d13f9a3e980ef3acd775e2.log
-rw-------. 1 root root   72 Sep 11 12:46 buffer.q57597d96f7d13f9a3e980ef3acd775e2.log.meta
-rw-------. 1 root root 2.0K Sep 11 12:47 buffer.q57597dd5fbe5432ac7182fcbb6e5c6aa.log
-rw-------. 1 root root   72 Sep 11 12:47 buffer.q57597dd5fbe5432ac7182fcbb6e5c6aa.log.meta
-rw-------. 1 root root   72 Sep 11 12:48 buffer.q57597e11fd2f45b013d18804d599549e.log.meta
-rw-------. 1 root root 2.0K Sep 11 12:48 buffer.q57597e11fd2f45b013d18804d599549e.log
-rw-------. 1 root root 2.0K Sep 11 12:49 buffer.q57597e4e15fda7acc217dfbc0febeedd.log
-rw-------. 1 root root   72 Sep 11 12:49 buffer.q57597e4e15fda7acc217dfbc0febeedd.log.meta
-rw-------. 1 root root 2.0K Sep 11 12:50 buffer.q57597e8847c6aecd2ce87369fdea5957.log
-rw-------. 1 root root   72 Sep 11 12:50 buffer.q57597e8847c6aecd2ce87369fdea5957.log.meta
-rw-------. 1 root root   72 Sep 11 12:51 buffer.q57597ec27b25c2e8202d252ee642d68c.log.meta
-rw-------. 1 root root 2.0K Sep 11 12:51 buffer.q57597ec27b25c2e8202d252ee642d68c.log
-rw-------. 1 root root   72 Sep 11 12:52 buffer.q57597efc949547fdb5baf37db8bf67f4.log.meta
-rw-------. 1 root root 2.0K Sep 11 12:52 buffer.q57597efc949547fdb5baf37db8bf67f4.log
-rw-------. 1 root root 2.0K Sep 11 12:53 buffer.q57597f36d0849cd6d3808ec9c090775c.log
-rw-------. 1 root root   72 Sep 11 12:53 buffer.q57597f36d0849cd6d3808ec9c090775c.log.meta
-rw-------. 1 root root   72 Sep 11 12:54 buffer.b57597f70f2f7f7034cccb24890701285.log.meta
-rw-------. 1 root root 1.5K Sep 11 12:54 buffer.b57597f70f2f7f7034cccb24890701285.log
```

Any help is greatly appreciated.

Thanks in advance,
Mahesh

**Comment by m1keil** [comment]
can confirm the same issue. `queued_chunks_limit_size` doesn't seem to do anything.

another config example:

```
<match **>
  @type kinesis_streams_aggregated
  region <region>
  stream_name <stream-name>
  <assume_role_credentials>
    role_session_name <session>
    role_arn <arn>
  </assume_role_credentials>
  <buffer>
    @type file
    path /var/spool/td-agent/buffers
    flush_at_shutdown true
    flush_interval 1s
    flush_thread_count 16
    chunk_limit_size 300k
    queued_chunks_limit_size 100
    retry_max_interval 300s
    retry_forever true
  </buffer>
</match>
```

```
/var/spool/td-agent/buffers$ du -h
611M	./worker0
619M	./worker1
1.2G	.
```

```
/var/spool/td-agent/buffers$ find . -type f -name *.log | wc -l
3141
```
