### ISSUE TITLE
got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `+' for nil:NilClass"

### ISSUE THREAD

**Issue by anjanimax** [fluent/fluentd#2146]
'fluentd' version '1.2.2'

I am getting following error on parsing tomcat logs and sending it to elasticsearch.

2018-10-10 12:26:57 +0800 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `+' for nil:NilClass"
2018-10-10 12:26:57 +0800 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_3fd677cb1398/577d843c038a83d656a6417f0dc61cdf.log

**VERSIONS:**
gem 'fluent-plugin-elasticsearch' version '2.10.3'
gem 'fluent-plugin-kafka' version '0.7.3'
gem 'fluent-plugin-record-modifier' version '1.1.0'
gem 'fluent-plugin-rewrite-tag-filter' version '2.1.0'
gem 'fluent-plugin-s3' version '1.1.3'
gem 'fluent-plugin-td' version '1.0.0'
gem 'fluent-plugin-td-monitoring' version '0.2.4'
gem 'fluent-plugin-webhdfs' version '1.2.3'
gem 'fluentd' version '1.2.2'

**ENVIRONMENT:**

**CONFIG**
<ROOT>
  <system>
    log_level info
  </system>
  <source>
    @type tail
    format multiline
    format_firstline /[0-9]{4}-[0-9]{2}-[0-9]{2}/
    format1 /^(?<datetime>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})\[(?<thread>[^\]]*)\]\[(?<level>[A-Z]*)\s{0,1}\]\[(?<service>[^\]]*)\]- (?<message>.*)$/
    multiline_flush_interval 3s
    read_from_head true
    path "/opt/ent/ca/apps/appname/logs/appname-srv.log"
    pos_file "/tmp/appname.pos"
    tag "appname.log"
    <parse>
      format_firstline /[0-9]{4}-[0-9]{2}-[0-9]{2}/
      @type multiline
      format1 /^(?<datetime>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})\[(?<thread>[^\]]*)\]\[(?<level>[A-Z]*)\s{0,1}\]\[(?<service>[^\]]*)\]- (?<message>.*)$/
    </parse>
  </source>
  <filter appname.log>
    @type record_transformer
    <record>
      hostname ${hostname}
    </record>
    <record>
      client ca
    </record>
    <record>
      app appname
    </record>
  </filter>
  <filter appname.log>
    @type grep
    <regexp>
      key "level"
      pattern ERROR
    </regexp>
  </filter>
  <filter appname.log>
    @type record_transformer
    enable_ruby 
    <record>
    </record>
    </filter>
  <match appname.log>
    @type elasticsearch
    host ""
    port 9220
    logstash_format true
    logstash_prefix "appname.log"
    flush_interval 1s
    index_name "appname"
    type_name "appname"
    <buffer>
      flush_interval 1s
    </buffer>
  </match>
  <source>
    @type tail
    format multiline
    format_firstline /[0-9]{4}-[0-9]{2}-[0-9]{2}/
    format1 /^(?<datetime>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})\[(?<thread>[^\]]*)\]\[(?<level>[A-Z]*)\s{0,1}\]\[(?<service>[^\]]*)\]- (?<message>.*)$/
    multiline_flush_interval 3s
    read_from_head true
    path "/opt/ent/ca/apps/appname/logs/appname.stacktrace.log"
    pos_file "/tmp/appname.stacktrace.pos"
    tag "appname.stacktrace.log"
    <parse>
      format_firstline /[0-9]{4}-[0-9]{2}-[0-9]{2}/
      @type multiline
      format1 /^(?<datetime>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})\[(?<thread>[^\]]*)\]\[(?<level>[A-Z]*)\s{0,1}\]\[(?<service>[^\]]*)\]- (?<message>.*)$/
    </parse>
  </source>
  <filter appname.stacktrace.log>
    @type record_transformer
    <record>
      hostname ${hostname}
    </record>
    <record>
      client ca
    </record>
<record>
      app appname
    </record>
  </filter>
  <filter appname.stacktrace.log>
    @type grep
    <regexp>
      key "level"
      pattern ERROR
    </regexp>
  </filter>
  <filter appname.stacktrace.log>
    @type record_transformer
    enable_ruby 
    <record>
      es_timestamp ${ require 'date';record["datetime"] << " MST";DateTime.parse(record["datetime"]).iso8601(9) }
    </record>
  </filter>
  <match appname.stacktrace.log>
    @type elasticsearch
    host ""
    port 9220
    logstash_format true
    logstash_prefix "appname.log"
    flush_interval 1s
    index_name "appname"
    type_name "appname"
    <buffer>
      flush_interval 1s
    </buffer>
  </match>
</ROOT>

**ENVIRONMENT**:
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID:	OracleServer
Description:	Oracle Linux Server release 6.8
Release:	6.8
Codename:	n/a

td-agent 1.2.2

**LOGS**:
2018-10-10 12:26:56 +0800 [info]: starting fluentd-1.2.2 pid=99593 ruby="2.4.4"
2018-10-10 12:26:56 +0800 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/sbin/td-agent", "--log", "/var/log/td-agent/td-
agent.log", "--use-v1-config", "--group", "td-agent", "--daemon", "/var/run/td-agent/td-agent.pid", "--under-supervisor"]
2018-10-10 12:26:56 +0800 [info]: gem 'fluent-plugin-elasticsearch' version '2.10.3'
2018-10-10 12:26:56 +0800 [info]: gem 'fluent-plugin-kafka' version '0.7.3'
2018-10-10 12:26:56 +0800 [info]: gem 'fluent-plugin-record-modifier' version '1.1.0'
2018-10-10 12:26:56 +0800 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.0'
2018-10-10 12:26:56 +0800 [info]: gem 'fluent-plugin-s3' version '1.1.3'
2018-10-10 12:26:56 +0800 [info]: gem 'fluent-plugin-td' version '1.0.0'
2018-10-10 12:26:56 +0800 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2018-10-10 12:26:56 +0800 [info]: gem 'fluent-plugin-webhdfs' version '1.2.3'
2018-10-10 12:26:56 +0800 [info]: gem 'fluentd' version '1.2.2'
2018-10-10 12:26:56 +0800 [info]: adding filter pattern="appname.log" type="record_transformer"
2018-10-10 12:26:56 +0800 [info]: adding filter pattern="appname.log" type="grep"
2018-10-10 12:26:56 +0800 [info]: adding filter pattern="appname.log" type="record_transformer"
2018-10-10 12:26:56 +0800 [info]: adding match pattern="appname.log" type="elasticsearch"
2018-10-10 12:26:56 +0800 [info]: #0 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
2018-10-10 12:26:56 +0800 [info]: adding filter pattern="appname.stacktrace.log" type="record_transformer"
2018-10-10 12:26:56 +0800 [info]: adding filter pattern="appname.stacktrace.log" type="grep"
2018-10-10 12:26:56 +0800 [info]: adding filter pattern="appname.stacktrace.log" type="record_transformer"
2018-10-10 12:26:56 +0800 [info]: adding match pattern="appname.stacktrace.log" type="elasticsearch"
2018-10-10 12:26:56 +0800 [info]: #0 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
2018-10-10 12:26:56 +0800 [info]: adding source type="tail"
2018-10-10 12:26:56 +0800 [info]: adding source type="tail"
2018-10-10 12:26:56 +0800 [info]: #0 starting fluentd worker pid=99608 ppid=99603 worker=0
2018-10-10 12:26:56 +0800 [info]: #0 following tail of /opt/ent/ca/apps/appname/logs/appname.stacktrace.log
2018-10-10 12:26:56 +0800 [info]: #0 following tail of /opt/ent/ca/apps/appname/logs/appname-srv.log
2018-10-10 12:26:56 +0800 [info]: #0 disable filter chain optimization because [Fluent::Plugin::RecordTransformerFilter, Fluent::Plugin::RecordTransformerFilter] uses `#filter_stream` method.
2018-10-10 12:26:57 +0800 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `+' for nil:NilClass"
2018-10-10 12:26:57 +0800 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_3fd677cb1398/577d843c038a83d656a6417f0dc61cdf.log
2018-10-10 12:26:58 +0800 [info]: #0 fluentd worker is now running worker=0
2018-10-10 12:26:58 +0800 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `+' for nil:NilClass"
2018-10-10 12:26:58 +0800 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_3fd677cb1398/577d843cf442cdbf617cc12c97a64260.log

Also to mention that same td-agent version and td-agent config is working for other nodes in same cluster.

Content of chunk
<88><A8>datetime<C4>^W2018-10-10 13:43:09,707<A6>thread<C4>^Thttp-nio-7079-exec-6<A5>level<C4>^EERROR<A7>service<C4>ESCappn.auditing.AuditHelper<A7>message<C5>8^ZAuditHelper.saveApiAuditTrail : Error in saving the audit trail for the request /workflow/getTasksForCenter
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'org.springframework.security.web.firewall.FirewalledResponse@7913a1f4' with class 'org.springframework.security.web.firewall.FirewalledResponse' to class 'appn.auditing.HttpCustomResponseWrapper'
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:392)
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:306)
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:227)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:601)
        at appn.auditing.AuditHelper.getRequestAndResponseAuditMaps(AuditHelper.groovy:237)
        at appn.auditing.AuditHelper.getRequestAndResponseAuditMaps(AuditHelper.groovy)
        at sun.reflect.GeneratedMethodAccessor1220.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.lang.Thread.run(Thread.java:748)<A8>hostname<C4>^Lapphost2<A6>client<A2>ca<A3>app<A7>appname

**Comment by anjanimax** [comment]
Found the issue. Environment variable for ElasticSearch IP was not picked correctly.
