### ISSUE TITLE
Fluent not able to authentocate with Kafka over TLS 

### ISSUE THREAD

**Issue by himmatb** [fluent/fluentd#2154]
- fluentd or td-agent version. - fluentd 1.1.1
- Environment information, : Solaris 

-  configuration
<source>
   @type tail
   #path /opt/app/fluentd_links/finbroker.log
   #path /opt/test-logs/finbroker.log
   path /etc/fluent/aaa
   #pos_file /var/fluentd/file2
   tag tibcologs-finbroker
   read_from_head true
   format none
</source>

<match **>
  @type kafka
  brokers "kafka-amq-cluster-kafka-bootstrap-logging.xxxx.xxxx.com:443"
  ssl_ca_cert /etc/fluent/keys/client-ca-cert.crt
  default_topic topic-xyz
  output_data_type json
  flush_interval 1s
</match>

I am trying to connect Fluentd agent with Kafka over TLS encryption as mentioned in above configuration but I am getting below error while connecting. Please help me to resolve and identify issue. 

Same certificates i am using for logstash i am able to connect . i don't know  where i am doing wrong.

- Your problem explanation. If you have an error logs, write it together.

Below is error log : 

2018-10-24 11:17:01 +0400 [info]: #0 initialized kafka producer: kafka
2018-10-24 11:17:01 +0400 [warn]: #0 emit transaction failed: error_class=Kafka::ConnectionError error="Could not connect to any of the seed brokers:\n- kafka://kafka-amq-cluster-kafka-bootstrap-logging.xxxx.xxxx.com:443: Connection error EOFError: end of file reached" location="/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:407:in `fetch_cluster_info'" tag="fluent.info"
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:407:in `fetch_cluster_info'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:367:in `cluster_info'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:95:in `refresh_metadata!'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:50:in `add_target_topics'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:276:in `deliver_messages_with_retries'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:238:in `block in deliver_messages'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/instrumenter.rb:23:in `instrument'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/producer.rb:231:in `deliver_messages'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.7.9/lib/fluent/plugin/out_kafka.rb:240:in `emit'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/compat/output.rb:164:in `process'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/plugin/output.rb:760:in `emit_sync'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/event_router.rb:96:in `emit_stream'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/event_router.rb:87:in `emit'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/engine.rb:207:in `block in log_event_loop'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/engine.rb:205:in `each'
  2018-10-24 11:17:01 +0400 [warn]: #0 /usr/local/lib/ruby/gems/2.4.0/gems/fluentd-1.1.1/lib/fluent/engine.rb:205:in `log_event_loop'
2018-10-24 11:17:01 +0400 [error]: #0 failed to emit fluentd's log event tag="fluent.info" event={"worker"=>0, "message"=>"fluentd worker is now running worker=0"} error_class=Kafka::ConnectionError error="Could not connect to any of the seed brokers:\n- kafka://kafka-amq-cluster-kafka-bootstrap-logging.xxxx.xxxx.com:443: Connection error EOFError: end of file reached"

Thanks In Advance!!

Himmat.

**Comment by repeatedly** [comment]
This doesn't follow contribution guide so closed.

**Comment by himmatb** [comment]
Even its not working with RedHat !!
