### ISSUE TITLE
Can out_copy be used in secondary?

### ISSUE THREAD

**Issue by dtmistry** [fluent/fluentd#2167]
*Env*  - Fluentd V1.0 docker container

*Config* -

```xml
<system>
    @log_level debug
</system>

# Listen to events on Unix domain socket
<source>
  @type unix
  path /var/run/events.sock
  @log_level debug
</source>

# Monitor retries and emit events from various plugins
<source>
  @type prometheus_output_monitor
  interval 10
  <labels>
    hostname ${hostname}
  </labels>
  @id output_monitor
</source>

# Enable prometheus metrics
<source>
  @type prometheus
  bind 0.0.0.0
  port 24231
  metrics_path /prometheus/metrics
</source>

# Filter plugin to count incoming events
<filter events.*>
  @type prometheus
  @id prometheus_filter_plugin
  <metric>
    name fluentd_events_input_num_records_total
    type counter
    desc The total number of incoming records
    <labels>
      tag ${tag}
      hostname ${hostname}
    </labels>
  </metric>
</filter>

<match events.*>
  @type copy
  <store>
    # count outgoing events
    @id prometheus_output_plugin
    @type prometheus
    <metric>
      name fluentd_events_output_num_records_total
      type counter
      desc The total number of outgoing events
      <labels>
        tag ${tag}
        hostname ${hostname}
      </labels>
    </metric>
  </store>
  <store>
    @type kinesis_streams
    stream_name test_stream
    region us-east-1
    <secondary>
        @type copy
        # emit error metric
        <store>
            @type prometheus
            <metric>
                 name fluentd_error_events_output_num_records_total
                 type counter
                 desc The total number of outgoing events
                 <labels>
                     tag ${tag}
                     hostname ${hostname}
                 </labels>
            </metric>
        </store> 
        <store>
           @type stdout
        </store>
    </secondary>
  </store>
</match>
```

Can `out_copy` be used in a secondary? When I try to use the config above, I get an error as below. Should that be a config error?

```bash
/usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:365:in `configure': undefined method `acts_as_secondary' for #<Fluent::Plugin::CopyOutput:007f2dbbca6e40> (NoMethodError)
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/inject.rb:104:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/event_emitter.rb:73:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/compat/output.rb:285:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/compat/set_time_key_mixin.rb:34:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/compat/set_tag_key_mixin.rb:31:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kinesis-2.1.1/lib/fluent/plugin/kinesis_helper/client.rb:72:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kinesis-2.1.1/lib/fluent/plugin/kinesis_helper/api.rb:33:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/formatter.rb:83:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kinesis-2.1.1/lib/fluent/plugin/kinesis.rb:81:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kinesis-2.1.1/lib/fluent/plugin/kinesis_helper/api.rb:53:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kinesis-2.1.1/lib/fluent/plugin/out_kinesis_streams.rb:30:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin.rb:164:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/multi_output.rb:74:in `block in configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/multi_output.rb:63:in `each'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/multi_output.rb:63:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_copy.rb:36:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin.rb:164:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/agent.rb:130:in `add_match'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/agent.rb:72:in `block in configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/agent.rb:64:in `each'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/agent.rb:64:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:112:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:131:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:96:in `run_configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:770:in `run_configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:553:in `dry_run'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:571:in `supervise'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:476:in `run_supervisor'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/bin/fluentd:8:in `<top (required)>'
        from /usr/bin/fluentd:22:in `load'
        from /usr/bin/fluentd:22:in `<main>'
```

**Comment by repeatedly** [comment]
Patch is here: https://github.com/fluent/fluentd/pull/2169

**Comment by dtmistry** [comment]
Thanks @repeatedly
