### ISSUE TITLE
uninitialized constant Fluent::Plugin::FirewallParser::Plugin (NameError)

### ISSUE THREAD

**Issue by FraLarghi** [fluent/fluentd#2265]
Hi guys, I'm trying to write my own plugins for Fluentd.
I want to write a parser for Cisco ASA firewalls, starting from a general one and then maybe parsing all the messages codes. 
I followed the tutorial example and this is my first try:

```
require 'fluent/plugin/parser'

module Fluent::Plugin
  class FirewallParser < Parser
    # Register this parser as "cisco_asa_simple"
    Plugin.register_parser("cisco_asa_simple", self)

    config_param :delimiter, :string, default: " "   # delimiter is configurable with " " as default
    config_param :time_format, :string, default: nil # time_format is configurable

    RGX1 = /^(\<\d*\>)?(?<time>[a-zA-Z]{3} [0-9]{1,2} [0-9]{4} [0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2}): %ASA\-(?<severity>[0-9])\-(?<code_id>[0-9]{6,7}): (?<message>.*)$/
    REGEX = Regexp.union(RGX1)
    TIME_FORMAT = "%b %d %Y %H:%M:%S:"
    # This method is called after config_params have read configuration parameters

    def configure(conf)
      super
      if @delimiter.length != 1
        raise ConfigError, "delimiter must be a single character. #{@delimiter} is not."
      end
      # TimeParser class is already given. It takes a single argument as the time format to parse the time string with.
      @time_parser = TimeParser.new(TIME_FORMAT)
    end

    def parse(text)
      record = {}
      time = nil
      unless m = REGEX.match(text)
        yield nil, nil
      else

        time = @time_parser.parse(m['time'])
        record["severity"] = m['severity'].to_i if m['severity']
        record["code_id"] = m['code_id'].to_i if m['code_id']
        record["message"] = m['message']
        
        yield time, record
      end
    end
  end
end
```

I then put it in my container where I have Fluentd installed and working, but when i try to parse some logs with my plugin this is the error stacktrace given:

```
2019-01-17 16:32:33 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluentd.conf"
/fluentd/plugins/parser_cisco_asa_simple.rb:6:in `<class:FirewallParser>': uninitialized constant Fluent::Plugin::FirewallParser::Plugin (NameError)
Did you mean?  Fluent::Plugin
               Fluent::PluginId
	from /fluentd/plugins/parser_cisco_asa_simple.rb:4:in `<module:Plugin>'
	from /fluentd/plugins/parser_cisco_asa_simple.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/registry.rb:68:in `search'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/registry.rb:44:in `lookup'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/plugin.rb:146:in `new_impl'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/plugin.rb:123:in `new_parser'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/plugin_helper/parser.rb:89:in `block in configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/plugin_helper/parser.rb:85:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/plugin_helper/parser.rb:85:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/plugin/in_syslog.rb:110:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/plugin.rb:164:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/root_agent.rb:282:in `add_source'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/root_agent.rb:122:in `block in configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/root_agent.rb:118:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/root_agent.rb:118:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/engine.rb:131:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/engine.rb:96:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/supervisor.rb:795:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/supervisor.rb:579:in `dry_run'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/supervisor.rb:597:in `supervise'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/supervisor.rb:502:in `run_supervisor'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-1.3.0/bin/fluentd:8:in `<top (required)>'
	from /usr/local/bin/fluentd:22:in `load'
	from /usr/local/bin/fluentd:22:in `<main>'

```

I tried some changes but this error keeps showing up.

**Comment by repeatedly** [comment]
How about `Fluent::Plugin.register_parser("cisco_asa_simple", self)` instead of `Plugin.register_parser("cisco_asa_simple", self)`?

**Comment by FraLarghi** [comment]
Thanks man it's working, I'm not practical with Ruby! 👍
