### ISSUE TITLE
fluentd cant read file

### ISSUE THREAD

**Issue by beatlejuse** [fluent/fluentd#2271]
- fluentd or td-agent version.
fluentd:1.3.0
- Environment information, e.g. OS.
Ubuntu 18.04.1 LTS / docker 18.09.0
- Your configuration
```
<source>
  @type tail
  path /var/lib/docker/containers/733.log
  pos_file "/tmp/cache/td-agent/docker.log.pos"
  tag docker.*
  <parse>
    time_format "%Y-%m-%dT%H:%M:%S.%NZ"
    @type none
    time_type string
  </parse>
</source>

<match **>
  @type copy
  <store>
    @type "stdout"
  </store>
  <store>
    @type "gelf"
    protocol "udp"
    host "fluentd"
    port 24224
    flush_interval 5s
  </store>
</match>
```
- Your problem explanation. If you have an error logs, write it together.
first I set up reading docker logs, but fluentd did not read these logs.
so I configured it to read a single file. after which I got the error:
```
fluentd-node    | 2019-01-21 08:28:33 +0000 [error]: #0 fluent/log.rb:362:error: unexpected error error_class=Errno::EACCES error="Permission denied @ rb_file_s_stat - /var/lib/docker/containers/733.log"
fluentd-node    |   2019-01-21 08:28:33 +0000 [error]: #0 fluent/supervisor.rb:723:main_process: suppressed same stacktrace
fluentd-node    | 2019-01-21 08:28:33 +0000 [info]: fluent/log.rb:322:info: Worker 0 finished unexpectedly with status 1
fluentd-node    | 2019-01-21 08:28:34 +0000 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-elasticsearch' version '3.0.2'
fluentd-node    | 2019-01-21 08:28:34 +0000 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-gelf-hs' version '1.0.7'
fluentd-node    | 2019-01-21 08:28:34 +0000 [info]: fluent/log.rb:322:info: gem 'fluentd' version '1.3.2'
fluentd-node    | 2019-01-21 08:28:34 +0000 [info]: fluent/log.rb:322:info: adding match pattern="**" type="copy"
fluentd-node    | 2019-01-21 08:28:34 +0000 [debug]: #0 fluent/log.rb:302:debug: adding store type="stdout"
fluentd-node    | 2019-01-21 08:28:34 +0000 [debug]: #0 fluent/log.rb:302:debug: adding store type="gelf"
fluentd-node    | 2019-01-21 08:28:34 +0000 [info]: fluent/log.rb:322:info: adding source type="tail"
fluentd-node    | 2019-01-21 08:28:34 +0000 [info]: #0 fluent/log.rb:322:info: starting fluentd worker pid=66 ppid=6 worker=0
fluentd-node    | 2019-01-21 08:28:34 +0000 [debug]: #0 fluent/log.rb:302:debug: buffer started instance=69825182733720 stage_size=0 queue_size=0
fluentd-node    | 2019-01-21 08:28:34 +0000 [error]: #0 fluent/log.rb:362:error: unexpected error error_class=Errno::EACCES error="Permission denied @ rb_file_s_stat - /var/lib/docker/containers/733.log"
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/in_tail.rb:539:in `stat'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/in_tail.rb:539:in `on_notify'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/in_tail.rb:521:in `attach'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/in_tail.rb:270:in `setup_watcher'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/in_tail.rb:301:in `block in start_watchers'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/in_tail.rb:287:in `each'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/in_tail.rb:287:in `start_watchers'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/in_tail.rb:264:in `refresh_watchers'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/in_tail.rb:195:in `start'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/root_agent.rb:165:in `block in start'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/root_agent.rb:153:in `each'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/root_agent.rb:153:in `block in lifecycle'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/root_agent.rb:140:in `each'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/root_agent.rb:140:in `lifecycle'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/root_agent.rb:164:in `start'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/engine.rb:274:in `start'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/engine.rb:219:in `run'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/supervisor.rb:799:in `run_engine'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/supervisor.rb:549:in `block in run_worker'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/supervisor.rb:724:in `main_process'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/supervisor.rb:544:in `run_worker'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/bin/fluentd:8:in `<top (required)>'
fluentd-node    |   2019-01-21 08:28:34 +0000 [error]: #0 fluent/supervisor.rb:549:block in run_worker: /usr/local/bin/fluentd:22:in `load'
```
the error says that there is no access to the file, although in fact the rights are granted to the maximum:

```
docker exec -it fluentd-node bash
root@45f3f1669222:/# ls -la /var/lib/docker/containers/
total 36
drwx------ 8 root   root   4096 Jan 21 08:25 .
drwxr-xr-x 3 root   root   4096 Jan 21 08:25 ..
drwx------ 4 root   root   4096 Jan 21 08:25 45f3f166922234eafa1cacf44e54179e10a2ddc8f436c8dc88de3a144bc41453
-rwxrwxrwx 1 fluent fluent  370 Jan 21 07:56 733.log
drwx------ 4 root   root   4096 Dec 26 14:34 73316832539cf3ecd03499ad96b2c802b237d7071625738ddbfd650161b8a7d5
drwx------ 4 root   root   4096 Dec 10 09:00 7a3f5548751881029cdc92b4e837939155a00b9753a44c3f2ff79c0972f00499
drwx------ 4 root   root   4096 Jan 18 12:56 981a08df9c2e2350272f2add4d2f2ae79a4294ae10ee4142749b265d431e6ff4
drwx------ 4 root   root   4096 Jan 15 15:03 a4732cf03991fc1f4074594c7584496a71b36b4103974e06da911c378ab87eba
drwx------ 4 root   root   4096 Dec 10 13:19 f619ec01f701f6911224b32f49ac004c43e20c8fc95c73717882709ec065cb30
```

**Comment by repeatedly** [comment]
Do you grant permission to all directories? `/var`, `/var/lib`, `/var/lib/docker` ?

**Comment by beatlejuse** [comment]
Yes, I even looked at which PID uses the fluent inside the container and assigned this PID as the owner and group to the file 733.log

**Comment by beatlejuse** [comment]
all other folders (/var, /var/lib, /var/lib/docker) are service and i cannot change the rights and owners, otherwise the docker will break

**Comment by repeatedly** [comment]
> but from inside the container the contents of / var / lib / docker / containers / are visible (ls) and the files are read (cat) when I go inside the running container (docker exec).

Because the user is root, right?
If you can't change the all directories, please run fluentd as root user.

**Comment by beatlejuse** [comment]
I tried to run the docker compose from the root. it'll be enough?

**Comment by beatlejuse** [comment]
also i try to run container with "privileged" mode.

**Comment by beatlejuse** [comment]
file docker-compose presented above. if it is wrong, explain what.
used image fluentd:1.3.0. This is your image downloaded from your repository.
if you can’t write code, don’t take up this business.
I personally despise the people you are trying to help, pointing out their mistake, and in response they begin to explain to me that I am incorrectly launching their program.
PS: in the end, I used a beatfile and he did an excellent job with this task, unlike fluentd.
