### ISSUE TITLE
Error with parsing java logs

### ISSUE THREAD

**Issue by sd2020bs** [fluent/fluentd#2313]
Hello. I have problem with java stacktrace.
- fluentd version:td-agent-3.3.0-1
- Operating system: `centos 7.5 `

I have java-logs like there:
2019-02-26 00:00:03,707 WARN ConnectThread [WsClientImpl]:215 - {front_site} ws error: Failed to connect to 'localhost:3003': Connection refused (Connection refused)
2019-02-26 00:00:03,707 INFO ConnectThread [WsClientImpl]:155 - {front_site} reconnect after 5000ms...
2019-02-26 00:00:08,160 ERROR Async-14--refreshTickets  - Couldn't get tickers
 java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
       ......

And fluentd's config:

```
<source>
  @type tail
  format multiline
  format_firstline /\d{4}-\d{1,2}-\d{1-2}/
  format1 /^(?<logtime>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,3})\s(?<loglevel>[^\s]+) (??<logfield>.*)/
  path /home/user/app/server.log
  tag td.app
</source>
<match td.app>
    @type file
    path /var/log/td-agent/app
</match>

```
Config sample i have been got from there (Java stacktrace log):
https://docs.fluentd.org/v1.0/articles/parser_multiline

And fluentd can't parse it. I receive in td-agent's log many strings like this:
2019-02-26 12:16:58 +0000 [warn]: #0 got incomplete line before first line from /home/user/app/server.log: " \tat java.lang.Thread.run(Thread.java:748)\n"

Directory /var/log/td-agent/app  is empty too.

**Comment by okkez** [comment]
Please check [fluent-plugin-detect-exceptions](https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions) and [fluent-plugin-concat](https://github.com/fluent-plugins-nursery/fluent-plugin-concat).
