### ISSUE TITLE
fluentd1.4.0 [input_forward] thread exited by unexpected error plugin=Fluent::Plugin::ForwardInput title=:event_loop error_class=Errno::ENOTCONN error="Transport endpoint is not connected - getpeername(2)"

### ISSUE THREAD

**Issue by YanXiaobin-Ben** [fluent/fluentd#2332]
I am using fluentd1.4.0 version, I have a very serious problem, the following error message has been repeated in the log, what is the cause?Thank you

2019-03-15 20:23:20 +0800 [info]: adding source type="forward"
2019-03-15 20:23:20 +0800 [info]: #0 starting fluentd worker pid=16212 ppid=22133 worker=0
2019-03-15 20:23:20 +0800 [info]: #0 [out_kafka] initialized kafka producer: kafka
2019-03-15 20:23:20 +0800 [info]: #0 [input_forward] listening port port=24224 bind="0.0.0.0"
2019-03-15 20:23:20 +0800 [info]: #0 fluentd worker is now running worker=0
2019-03-15 20:23:20 +0800 [warn]: #6 [input_forward] thread exited by unexpected error plugin=Fluent::Plugin::ForwardInput title=:event_loop error_class=Errno::ENOTCONN error="Transport endpoint is not connected - getpeername(2)"
2019-03-15 20:23:20 +0800 [error]: #6 unexpected error error_class=Errno::ENOTCONN error="Transport endpoint is not connected - getpeername(2)"
  2019-03-15 20:23:20 +0800 [error]: #6 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/socket.rb:147:in `peeraddr'
  2019-03-15 20:23:20 +0800 [error]: #6 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/socket.rb:147:in `initialize'
  2019-03-15 20:23:20 +0800 [error]: #6 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/server.rb:560:in `initialize'
  2019-03-15 20:23:20 +0800 [error]: #6 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/server.rb:40:in `new'
  2019-03-15 20:23:20 +0800 [error]: #6 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/server.rb:40:in `on_connection'
  2019-03-15 20:23:20 +0800 [error]: #6 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/listener.rb:46:in `on_readable'
  2019-03-15 20:23:20 +0800 [error]: #6 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run_once'
  2019-03-15 20:23:20 +0800 [error]: #6 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run'
  2019-03-15 20:23:20 +0800 [error]: #6 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-03-15 20:23:20 +0800 [error]: #6 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-03-15 20:23:20 +0800 [error]: #6 unexpected error error_class=Errno::ENOTCONN error="Transport endpoint is not connected - getpeername(2)"
  2019-03-15 20:23:20 +0800 [error]: #6 suppressed same stacktrace
2019-03-15 20:23:20 +0800 [info]: Worker 6 finished unexpectedly with status 1
2019-03-15 20:23:21 +0800 [info]: #6 [out_kafka] brokers has been set directly: ["170.23.116.216:9091"]
2019-03-15 20:23:21 +0800 [info]: #6 starting fluentd worker pid=16254 ppid=22133 worker=6
2019-03-15 20:23:21 +0800 [info]: #6 [out_kafka] initialized kafka producer: kafka
2019-03-15 20:23:21 +0800 [info]: #6 [input_forward] listening port port=24224 bind="0.0.0.0"
2019-03-15 20:23:21 +0800 [info]: #6 fluentd worker is now running worker=6
2019-03-15 20:23:22 +0800 [warn]: #3 [input_forward] thread exited by unexpected error plugin=Fluent::Plugin::ForwardInput title=:event_loop error_class=Errno::ENOTCONN error="Transport endpoint is not connected - getpeername(2)"
2019-03-15 20:23:22 +0800 [error]: #3 unexpected error error_class=Errno::ENOTCONN error="Transport endpoint is not connected - getpeername(2)"
  2019-03-15 20:23:22 +0800 [error]: #3 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/socket.rb:147:in `peeraddr'
  2019-03-15 20:23:22 +0800 [error]: #3 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/socket.rb:147:in `initialize'
  2019-03-15 20:23:22 +0800 [error]: #3 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/server.rb:560:in `initialize'
  2019-03-15 20:23:22 +0800 [error]: #3 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/server.rb:40:in `new'
  2019-03-15 20:23:22 +0800 [error]: #3 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/server.rb:40:in `on_connection'
  2019-03-15 20:23:22 +0800 [error]: #3 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/listener.rb:46:in `on_readable'
  2019-03-15 20:23:22 +0800 [error]: #3 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run_once'
  2019-03-15 20:23:22 +0800 [error]: #3 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run'
  2019-03-15 20:23:22 +0800 [error]: #3 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-03-15 20:23:22 +0800 [error]: #3 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-1.4.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-03-15 20:23:22 +0800 [error]: #3 unexpected error error_class=Errno::ENOTCONN error="Transport endpoint is not connected - getpeername(2)"
  2019-03-15 20:23:22 +0800 [error]: #3 suppressed same stacktrace
2019-03-15 20:23:22 +0800 [info]: Worker 3 finished unexpectedly with status 1
2019-03-15 20:23:23 +0800 [info]: #3 [out_kafka] brokers has been set directly: ["170.23.116.216:9091"]
2019-03-15 20:23:23 +0800 [info]: #3 starting fluentd worker pid=16298 ppid=22133 worker=3
2019-03-15 20:23:23 +0800 [info]: #3 [out_kafka] initialized kafka producer: kafka
2019-03-15 20:23:23 +0800 [info]: #3 [input_forward] listening port port=24224 bind="0.0.0.0"
2019-03-15 20:23:23 +0800 [info]: #3 fluentd worker is now running worker=3

**Comment by repeatedly** [comment]
From your log, your forward side connection is closed before calling getpeername.
I'm not sure why this happens but I will check how to ignore this error.

**Comment by YanXiaobin-Ben** [comment]
thanks for your checking.I will continue to pay attention to this issue.

**Comment by repeatedly** [comment]
The problem is you use older cool.io.

https://github.com/tarcieri/cool.io/blob/c79b4dff788071fcc45fac838d5d76dc645b8c1d/lib/cool.io/socket.rb#L149

Recent cool.io has already resolved this problem so updating cool.io resolve this problem.

**Comment by YanXiaobin-Ben** [comment]
The problem has been solved, thank you very much.
