### ISSUE TITLE
fluentd stop sending logs to elasticsearch after a few hours(@type forward)

### ISSUE THREAD

**Issue by bidiudiu** [fluent/fluentd#2334]
- fluentd version: v0.12-debian
- Environment information: docker

I'm following https://docs.fluentd.org/v0.12/articles/docker-logging-efk-compose and have a simple EFK setup which has a very strange behaviour. Fluentd seems to stop sending information to elasticsearch after few hours it is up. From docker's log, there's error information:

```
 2019-03-20 02:07:53 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-20 02:07:54 +0000 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="object:3f880ef7f118"
  2019-03-20 02:07:53 +0000 [warn]: /var/lib/gems/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:249:in `perform_request'
  2019-03-20 02:07:53 +0000 [warn]: /var/lib/gems/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2019-03-20 02:07:53 +0000 [warn]: /var/lib/gems/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
  2019-03-20 02:07:53 +0000 [warn]: /var/lib/gems/2.3.0/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/bulk.rb:90:in `bulk'
  2019-03-20 02:07:53 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/out_elasticsearch.rb:353:in `send_bulk'
  2019-03-20 02:07:53 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/out_elasticsearch.rb:339:in `write_objects'
  2019-03-20 02:07:53 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.43/lib/fluent/output.rb:490:in `write'
  2019-03-20 02:07:53 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:354:in `write_chunk'
  2019-03-20 02:07:53 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:333:in `pop'
  2019-03-20 02:07:53 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.43/lib/fluent/output.rb:342:in `try_flush'
  2019-03-20 02:07:53 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.43/lib/fluent/output.rb:149:in `run'
```

I find some people met similar problem when using '@type tail', but find no issue related to '@type forward'. Do you have any suggestions to find the root of this problem? Thank you in advance. 

Here're my configs:
`docker-compose.yml:`
```yaml
version: '2'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24225:24225"
      - "24225:24225/udp"
  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"
  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
```
`Dockerfile for fluentd:`

```dockerfile
FROM fluent/fluentd:v0.12-debian
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-rdoc", "--no-ri", "--version", "1.9.2"]
```

`fluent.conf:`
```aconf
<source>
  @type forward
  port 24225
  bind 0.0.0.0
</source>
<filter xxx.xxx>
  @type parser
  key_name log
  reserve_data yes
  format /^Type=[(?<logtype>[^]]\*)] Message=[(?<logmessage>[\s\S]\*)]/
</filter>
<match xxx.xxx>
  @type copy
  <store>
    @type elasticsearch
    host elasticsearch
    port 9200
    logstash_format true
    logstash_prefix fluentd
    logstash_dateformat %Y%m%d
    include_tag_key true
    type_name access_log
    tag_key @log_name
    flush_interval 1s
  </store>
  <store>
    @type stdout
  </store>
</match>
```

**Comment by ChSch3000** [comment]
I have a similar issue with the fluentd-kubernetes-daemonset
See here: https://github.com/fluent/fluentd-kubernetes-daemonset/issues/280

**Comment by bidiudiu** [comment]
Solved and close this issue:
reconnect_on_error true
reload_on_failure true
reload_connections false
