### ISSUE TITLE
Logger not initialized in SyslogParser

### ISSUE THREAD

**Issue by Wolodija** [fluent/fluentd#2338]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version. 
```
root@25f10cd2daed:/# fluentd --version
fluentd 1.3.3

```
- Environment information:
	- Operating system: `cat /etc/os-release` - shouldn't matter
	- Kernel version: `uname -r` - shouldn't matter
- Custom plugin (shouldn't matter)

There is problem here: https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/parser_syslog.rb#L120

```
                rescue Fluent::TimeParser::TimeParseError => e
                  if @support_rfc5424_without_subseconds
                    log.trace(e) <--- HERE
                    @time_parser_rfc5424_without_subseconds.parse(time_str)
                  else
```

log seems to be uninitialized. I am not fluent (hehe) in fluentd code architecture, so I'm not sure how to solve it. Probably some inclusion of Logger.

Here is stacktrace
```
2019-03-20 05:29:46 +0000 [error]: #0 fluent/log.rb:362:error: unexpected error on reading data host="172.28.0.1" port=50592 error_class=NoMethodError error="undefined method `trace' for nil:NilClass"
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin/parser_syslog.rb:120:in `rescue in block (2 levels) in parse_plain'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin/parser_syslog.rb:116:in `block (2 levels) in parse_plain'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin/parser_syslog.rb:114:in `synchronize'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin/parser_syslog.rb:114:in `block in parse_plain'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin/parser_syslog.rb:108:in `each'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin/parser_syslog.rb:108:in `parse_plain'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluent-plugin-custom-0.1.0/lib/fluent/plugin/in_custom.rb:98:in `parse'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluent-plugin-custom-0.1.0/lib/fluent/plugin/in_custom.rb:134:in `block (2 levels) in start'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluent-plugin-custom-0.1.0/lib/fluent/plugin/in_custom.rb:132:in `each'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluent-plugin-custom-0.1.0/lib/fluent/plugin/in_custom.rb:132:in `block in start'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/server.rb:621:in `on_read_with_connection'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/io.rb:123:in `on_readable'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/io.rb:186:in `on_readable'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-03-20 05:29:46 +0000 [error]: #0 cool.io/io.rb:186:on_readable: /var/lib/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by repeatedly** [comment]
Maybe, your custom plugin has wrong code for parser initialization.
I assume you create syslog parser directly, not via parser helper.
if so, could you try parser helper API?

https://docs.fluentd.org/v1.0/articles/api-plugin-helper-parser

**Comment by Wolodija** [comment]
Yeah, you're right. What I want to achieve with custom plugin is using multiple parsers. If parser fails I want to have fallback. Using parser helper forces me to use exactly one parser section.

I checked the solution with helper. It works fine. I had to left dead-one config section `parser` (I wanted to avoid that), but it's acceptable. Thanks and sorry for taking your time

**Comment by ganmacs** [comment]
it seems not to be  fluentd's issue.
