### ISSUE TITLE
Support forward to AWS ELB?

### ISSUE THREAD

**Issue by suanziliu** [fluent/fluentd#2339]
- fluentd or td-agent version.
td-agent --version
td-agent 0.12.43
- Environment information:
	- Operating system: `cat /etc/os-release`
`$ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
`
	- Kernel version: `uname -r`
`3.16.0-29-generic`

- Your configuration
`<match **>`
  `@type forward`
 `buffer_type file`
`  buffer_path /var/log/td-agent/buffer/forward/log/`
  `buffer_chunk_limit 256m`
 ` buffer_queue_limit 128`
  `num_threads 1 # the number of threads to flush the buffer`
 ` flush_interval 5s`
`  expire_dns_cache 600`
 ` <server>`
  `  host AWS ELB DNS Name: xxx.ap-northeast-1.elb.amazonaws.com`
     `port 80`
 ` </server>`
  ` </match>`

- Your problem explanation. If you have an error logs, write it together.

When I use an internal AWS ELB to connect with td-agent and td-agent-aggregator,
td-agent cannot forward logs to ELB.
Log shows:

```
2019-03-20 11:08:38 +0000 [warn]: detached forwarding server 'xxx.ap-northeast-1.elb.amazonaws.com:80' host="xxx.ap-northeast-1.elb.amazonaws.com" port=80 hard_timeout=true
2019-03-20 11:08:43 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-20 11:08:44 +0000 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3fccc9e964e0"
  2019-03-20 11:08:43 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/plugin/out_forward.rb:222:in `write_objects'
  2019-03-20 11:08:43 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/output.rb:490:in `write'
  2019-03-20 11:08:43 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:354:in `write_chunk'
  2019-03-20 11:08:43 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:333:in `pop'
  2019-03-20 11:08:43 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/output.rb:342:in `try_flush'
  2019-03-20 11:08:43 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/output.rb:149:in `run'
2019-03-20 11:08:44 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-20 11:08:46 +0000 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3fccc9e964e0"
  2019-03-20 11:08:44 +0000 [warn]: suppressed same stacktrace
2019-03-20 11:08:46 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-20 11:08:51 +0000 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3fccc9e964e0"
  2019-03-20 11:08:46 +0000 [warn]: suppressed same stacktrace
2019-03-20 11:08:51 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-20 11:08:59 +0000 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3fccc9e964e0"
  2019-03-20 11:08:51 +0000 [warn]: suppressed same stacktrace
2019-03-20 11:08:59 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-20 11:09:17 +0000 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3fccc9e964e0"
  2019-03-20 11:08:59 +0000 [warn]: suppressed same stacktrace
2019-03-20 11:09:17 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-20 11:09:48 +0000 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3fccc9e964e0"
  2019-03-20 11:09:17 +0000 [warn]: suppressed same stacktrace
2019-03-20 11:09:48 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-20 11:10:53 +0000 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3fccc9e964e0"
  2019-03-20 11:09:48 +0000 [warn]: suppressed same stacktrace
2019-03-20 11:10:53 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-20 11:12:56 +0000 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3fccc9e964e0"
  2019-03-20 11:10:53 +0000 [warn]: suppressed same stacktrace
```

When testing connection: 
1. on td-agent machine(an AWS EC2), I can connect to the ELB via 
`nc -v xxxx.ap-northeast-1.elb.amazonaws.com 80`
2. On AWS Console, ELB health check success, listener config:
`Load Balancer Protocol --> TCP`
`Load Balancer Port --> 80`
`Instance Protocol --> TCP`
`Instance Port --> 24224`
`Cipher --> N/A	`
`SSL Certificate --> N/A`

So I think this problem is caused by `td-agent cannot connect to aws ELB`

Is there anything wrong for my operation?

**Comment by repeatedly** [comment]
fluentd uses UDP for heartbeat by default.
How about changing to tcp heartbeat?

**Comment by suanziliu** [comment]
@repeatedly 
I tried to config `tcp` like following:
```
<match *.*.{system}.**>
  @type forward
  buffer_type file
  buffer_path /var/log/td-agent/buffer/forward/log/
  buffer_chunk_limit 16m
  buffer_queue_limit 128
  num_threads 1 # the number of threads to flush the buffer
  flush_interval 2s
  require_ack_response true
  heartbeat_type tcp
  <server>
    host  <elb>
    port 80
  </server>
</match>
```

Sometimes it works fine, but when when I start to apply it to production env. The same issue happens again:
```
2019-05-28 03:52:57 +0000 [warn]: detached forwarding server '<elb dns name> host=<elb dns name> port=80 hard_timeout=true
```

**Comment by ganmacs** [comment]
> Sometimes it works fine, but when when I start to apply it to production env.

it's your env problem, then. closing because fluentd is not related.
