### ISSUE TITLE
td-agent 0.12.29 temporarily failed to flush the buffer with error_class="Errno::ECONNREFUSED" error="Connection refused - connect(2)

### ISSUE THREAD

**Issue by Hearen** [fluent/fluentd#2362]
```
2019-03-29 12:40:14 +0000 [info]: shutting down input type="tail" plugin_id="object:3fbca03b9344"
2019-03-29 12:40:14 +0000 [info]: shutting down input type="tail" plugin_id="object:3fbca03b2e68"
2019-03-29 12:40:14 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-29 12:40:15 +0000 error_class="Errno::ECONNREFUSED" error="Connection refused - connect(2) for \"10.131.71.236\" port 24224" plugin_id="object:3fbca1c28010"
  2019-03-29 12:40:14 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/out_forward.rb:378:in `initialize'
  2019-03-29 12:40:14 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/out_forward.rb:378:in `new'
  2019-03-29 12:40:14 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/out_forward.rb:378:in `connect'
  2019-03-29 12:40:14 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/out_forward.rb:299:in `send_data'
  2019-03-29 12:40:14 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/out_forward.rb:210:in `block in write_objects'
  2019-03-29 12:40:14 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/out_forward.rb:204:in `times'
  2019-03-29 12:40:14 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/out_forward.rb:204:in `write_objects'
  2019-03-29 12:40:14 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:480:in `write'
  2019-03-29 12:40:14 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:354:in `write_chunk'
  2019-03-29 12:40:14 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:333:in `pop'
  2019-03-29 12:40:14 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:338:in `try_flush'
  2019-03-29 12:40:14 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:149:in `run'
2019-03-29 12:40:15 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-29 12:40:17 +0000 error_class="Errno::ECONNREFUSED" error="Connection refused - connect(2) for \"10.131.71.236\" port 24224" plugin_id="object:3fbca1c28010"
  2019-03-29 12:40:15 +0000 [warn]: suppressed same stacktrace
2019-03-29 12:40:17 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-29 12:40:21 +0000 error_class="Errno::ECONNREFUSED" error="Connection refused - connect(2) for \"10.131.71.236\" port 24224" plugin_id="object:3fbca1c28010"
  2019-03-29 12:40:17 +0000 [warn]: suppressed same stacktrace
2019-03-29 12:40:21 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-29 12:40:28 +0000 error_class="Errno::ECONNREFUSED" error="Connection refused - connect(2) for \"10.131.71.236\" port 24224" plugin_id="object:3fbca1c28010"
  2019-03-29 12:40:21 +0000 [warn]: suppressed same stacktrace
....
2019-03-29 12:40:44 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-29 12:41:17 +0000 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3fbca1c28010"
  2019-03-29 12:40:44 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/out_forward.rb:222:in `write_objects'
  2019-03-29 12:40:44 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:480:in `write'
  2019-03-29 12:40:44 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:354:in `write_chunk'
  2019-03-29 12:40:44 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:333:in `pop'
  2019-03-29 12:40:44 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:338:in `try_flush'
  2019-03-29 12:40:44 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/output.rb:149:in `run'
2019-03-29 12:40:45 +0000 [info]: detected rotation of /var/lib/docker/containers/2de155e7d2c63b47d603d9c2d57aa316755e8e5403ef9e16828c0608bcb9713e/2de155e7d2c63b47d603d9c2d57aa316755e8e5403ef9e16828c0608bcb9713e-json.log; waiting 5 seconds
2019-03-29 12:40:45 +0000 [info]: following tail of /var/lib/docker/containers/2de155e7d2c63b47d603d9c2d57aa316755e8e5403ef9e16828c0608bcb9713e/2de155e7d2c63b47d603d9c2d57aa316755e8e5403ef9e16828c0608bcb9713e-json.log
2019-03-29 12:40:50 +0000 [warn]: detached forwarding server '10.131.71.235:24224' host="10.131.71.235" port=24224 phi=16.041213987303383
2019-03-29 12:40:52 +0000 [warn]: detached forwarding server '10.131.71.236:24224' host="10.131.71.236" port=24224 phi=16.382732943338386
```

```
$ td-agent --version
td-agent 0.12.29


$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial


$ uname -r
4.4.0-1077-aws

```

I am recently watching **some** (most of the time it's working as expected) similar logs printed, sorry I haven't pasted all the configurations, since there are pretty many. I can enclose them when it's required accordingly.

**Comment by kenhys** [comment]
I guess that your fluentd configuration file is like this:


```
<match ...>
  @type forward
  <server>
    name ...
    host 10.131.71.235
    port 24224
  </server>
  <server>
    name ...
    host 10.131.71.236
    port 24224
 </server>
</match>
```

It seems that  '10.131.71.235:24224' host works, if so, there is something wrong with '10.131.71.236:24224' host.
Investigating diference between 10.131.71.235:24224' and '10.131.71.236:24224' may help you.

**Comment by cosmo0920** [comment]
Fluentd v0.12 series already EOL and no response.
https://www.fluentd.org/blog/drop-schedule-announcement-in-2019
Please consider to use Fluentd v1.
If you hit this issue on Fluentd v1, please add a comment on this issue.
Anyway, thanks for using Fluentd!
Closing.
