### ISSUE TITLE
how to avoid BufferQueueLimitError for in_forward plugin of aggregator td-agent

### ISSUE THREAD

**Issue by foxracle** [fluent/fluentd#2370]
- fluentd or td-agent version.
td-agent : 2.5.0

error log:

```
 2019-03-22 16:14:04 +0800 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" location="/opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:204:in `block in emit'" tag="x.y.z"
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:204:in `block in emit'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:193:in `emit'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/output.rb:593:in `block in emit'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/output.rb:592:in `each'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/output.rb:592:in `emit'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/output.rb:42:in `next'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/plugin/out_copy.rb:78:in `emit'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/event_router.rb:90:in `emit_stream'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:178:in `on_message'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:338:in `call'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:338:in `block in on_read_msgpack'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:337:in `feed_each'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:337:in `on_read_msgpack'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:323:in `call'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:323:in `on_read'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/cool.io-1.5.1/lib/cool.io/io.rb:123:in `on_readable'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/cool.io-1.5.1/lib/cool.io/io.rb:186:in `on_readable'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/cool.io-1.5.1/lib/cool.io/loop.rb:88:in `run_once'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/cool.io-1.5.1/lib/cool.io/loop.rb:88:in `run'
  2019-03-22 16:14:04 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/plugin/in_forward.rb:120:in `run'
2019-03-22 16:14:04 +0800 [error]: forward error error=#<Fluent::BufferQueueLimitError: queue size exceeds limit> error_class=Fluent::BufferQueueLimitError
  2019-03-22 16:14:04 +0800 [error]: suppressed same stacktrace
```

we can use buffer_type file to buffer the received data for out_forward. we also know that out_forward plugin supports load-balancing and automatic fail-over.

but in our scenario, the Buffer Queue exceeded the limit of in_forward, how can we avoid this?
Does in_forward supports  buffer_type file?

Thanks

**Comment by foxracle** [comment]
anyone any hint?

**Comment by ganmacs** [comment]
it's stale. I'm closing. if you still have any problem, updating fluentd might be helpful.
