### ISSUE TITLE
test: secondary plugin can do delayed commit even if primary does not do it, and non-committed chunks will be rollbacked by primary:F

### ISSUE THREAD

**Issue by henrich** [fluent/fluentd#2375]
- fluentd version: 1.4.2
- Environment information:
	- Operating system: PRETTY_NAME="Debian GNU/Linux buster/sid"
                                        NAME="Debian GNU/Linux"
                                        ID=debian
                                        HOME_URL="https://www.debian.org/"
                                        SUPPORT_URL="https://www.debian.org/support"
                                        BUG_REPORT_URL="https://bugs.debian.org/"
	- Kernel version: 4.19.0-3-amd64
- Your problem explanation:

 Now I'm trying to make deb fluentd package since some package needs to be built for its newer version dependency ([itamae](https://tracker.debian.org/pkg/itamae) debian package needs ruby-fluent-logger to be updated to new upstream release, and [ruby-fluent-logger](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926236) debian package needs fluentd to be built. What a happy dependency hell! ;).

And almost done but one failure during tests remains as below. Could you give advice, please?

```
(snip)
    test: secondary plugin can do delayed commit even if primary does not do it, and non-committed chunks will be rollbacked by primary:F                                                 
===============================================================================                                                                                                               
Failure: test: secondary plugin can do delayed commit even if primary does not do it, and non-committed chunks will be rollbacked by primary(BufferedOutputSecondaryTest::secondary plugin fea
ture for buffered output with periodical retry): <nil> is not true.                                                                                                                           
/build/fluentd-1.4.2/test/plugin/test_output_as_buffered_secondary.rb:627:in `block (2 levels) in <class:BufferedOutputSecondaryTest>'                                                        
     624:         break if @i.buffer.dequeued.size == 0                                                                                                                                       
     625:       end                                                                                                                                                                           
     626:                                                                                                                                                                                     
  => 627:       assert @i.retry                                                                                                                                                               
     628:       logs = @i.log.out.logs                                                                                                                                                        
     629:       waiting(4){ sleep 0.1 until logs.select{|l| l.include?("[warn]: failed to flush the buffer chunk, timeout to commit.") }.size == 2 }                                          
     630:       assert{ logs.select{|l| l.include?("[warn]: failed to flush the buffer chunk, timeout to commit.") }.size == 2 }                                                              
===============================================================================                                                                                                               
: (2.011796) 
(snip)
Finished in 989.684912106 seconds.                                                                                                                                                            
-------------------------------------------------------------------------------                                                                                                               
2748 tests, 11194 assertions, 1 failures, 0 errors, 1 pendings, 0 omissions, 1 notifications                                                                                                  
99.9272% passed                                                                                                                                                                               
-------------------------------------------------------------------------------                                                                                                               
2.78 tests/s, 11.31 assertions/s                                                                                                                                                              
rake aborted!                                                                                                                                                                                 
Command failed with status (1): [ruby -w -I"test" -Eascii-8bit:ascii-8bit  "/usr/lib/ruby/vendor_ruby/rake/rake_test_loader.rb" "test/scripts/fluent/plugin/out_test.rb" "test/command/test_bi
nlog_reader.rb" "test/command/test_ca_generate.rb" "test/command/test_fluentd.rb" "test/command/test_plugin_config_formatter.rb" "test/command/test_plugin_generator.rb" "test/compat/test_cal
ls_super.rb" "test/compat/test_parser.rb" "test/config/test_config_parser.rb" "test/config/test_configurable.rb" "test/config/test_configure_proxy.rb" "test/config/test_dsl.rb" "test/config/
test_element.rb" "test/config/test_literal_parser.rb" "test/config/test_plugin_configuration.rb" "test/config/test_section.rb" "test/config/test_system_config.rb" "test/config/test_types.rb"
 "test/counter/test_client.rb" "test/counter/test_error.rb" "test/counter/test_mutex_hash.rb" "test/counter/test_server.rb" "test/counter/test_store.rb" "test/counter/test_validator.rb" "tes
t/plugin/test_bare_output.rb" "test/plugin/test_base.rb" "test/plugin/test_buf_file.rb" "test/plugin/test_buf_memory.rb" "test/plugin/test_buffer.rb" "test/plugin/test_buffer_chunk.rb" "test
/plugin/test_buffer_file_chunk.rb" "test/plugin/test_buffer_memory_chunk.rb" "test/plugin/test_compressable.rb" "test/plugin/test_file_util.rb" "test/plugin/test_filter.rb" "test/plugin/test
_filter_grep.rb" "test/plugin/test_filter_parser.rb" "test/plugin/test_filter_record_transformer.rb" "test/plugin/test_filter_stdout.rb" "test/plugin/test_formatter_csv.rb" "test/plugin/test
_formatter_hash.rb" "test/plugin/test_formatter_json.rb" "test/plugin/test_formatter_ltsv.rb" "test/plugin/test_formatter_msgpack.rb" "test/plugin/test_formatter_out_file.rb" "test/plugin/te
st_formatter_single_value.rb" "test/plugin/test_formatter_tsv.rb" "test/plugin/test_in_debug_agent.rb" "test/plugin/test_in_dummy.rb" "test/plugin/test_in_exec.rb" "test/plugin/test_in_forwa
rd.rb" "test/plugin/test_in_gc_stat.rb" "test/plugin/test_in_http.rb" "test/plugin/test_in_monitor_agent.rb" "test/plugin/test_in_object_space.rb" "test/plugin/test_in_syslog.rb" "test/plugi
n/test_in_tail.rb" "test/plugin/test_in_tcp.rb" "test/plugin/test_in_udp.rb" "test/plugin/test_in_unix.rb" "test/plugin/test_input.rb" "test/plugin/test_metadata.rb" "test/plugin/test_multi_
output.rb" "test/plugin/test_out_copy.rb" "test/plugin/test_out_exec.rb" "test/plugin/test_out_exec_filter.rb" "test/plugin/test_out_file.rb" "test/plugin/test_out_forward.rb" "test/plugin/t
est_out_null.rb" "test/plugin/test_out_relabel.rb" "test/plugin/test_out_roundrobin.rb" "test/plugin/test_out_secondary_file.rb" "test/plugin/test_out_stdout.rb" "test/plugin/test_out_stream
.rb" "test/plugin/test_output.rb" "test/plugin/test_output_as_buffered.rb" "test/plugin/test_output_as_buffered_backup.rb" "test/plugin/test_output_as_buffered_compress.rb" "test/plugin/test
_output_as_buffered_overflow.rb" "test/plugin/test_output_as_buffered_retries.rb" "test/plugin/test_output_as_buffered_secondary.rb" "test/plugin/test_output_as_standard.rb" "test/plugin/tes
t_owned_by.rb" "test/plugin/test_parser.rb" "test/plugin/test_parser_apache.rb" "test/plugin/test_parser_apache2.rb" "test/plugin/test_parser_apache_error.rb" "test/plugin/test_parser_csv.rb
" "test/plugin/test_parser_json.rb" "test/plugin/test_parser_labeled_tsv.rb" "test/plugin/test_parser_multiline.rb" "test/plugin/test_parser_nginx.rb" "test/plugin/test_parser_none.rb" "test
/plugin/test_parser_regexp.rb" "test/plugin/test_parser_syslog.rb" "test/plugin/test_parser_tsv.rb" "test/plugin/test_storage.rb" "test/plugin/test_storage_local.rb" "test/plugin/test_string
_util.rb" "test/plugin_helper/test_child_process.rb" "test/plugin_helper/test_compat_parameters.rb" "test/plugin_helper/test_event_emitter.rb" "test/plugin_helper/test_event_loop.rb" "test/p
lugin_helper/test_extract.rb" "test/plugin_helper/test_formatter.rb" "test/plugin_helper/test_inject.rb" "test/plugin_helper/test_parser.rb" "test/plugin_helper/test_record_accessor.rb" "tes
t/plugin_helper/test_retry_state.rb" "test/plugin_helper/test_server.rb" "test/plugin_helper/test_storage.rb" "test/plugin_helper/test_thread.rb" "test/plugin_helper/test_timer.rb" "test/tes
t_clock.rb" "test/test_config.rb" "test/test_configdsl.rb" "test/test_event.rb" "test/test_event_router.rb" "test/test_event_time.rb" "test/test_filter.rb" "test/test_formatter.rb" "test/tes
t_input.rb" "test/test_log.rb" "test/test_match.rb" "test/test_mixin.rb" "test/test_output.rb" "test/test_plugin.rb" "test/test_plugin_classes.rb" "test/test_plugin_helper.rb" "test/test_plu
gin_id.rb" "test/test_process.rb" "test/test_root_agent.rb" "test/test_supervisor.rb" "test/test_test_drivers.rb" "test/test_time_formatter.rb" "test/test_time_parser.rb" "test/test_unique_i
d.rb" -v] 
```

Note: To be built, add [some patches](https://salsa.debian.org/ruby-team/fluentd/tree/debian/sid/debian/patches) to the package

Thanks!

**Comment by repeatedly** [comment]
This test sometimes failed by timing issue. Does this test alwasy fail on your environment?

**Comment by henrich** [comment]
> This test sometimes failed by timing issue. Does this test alwasy fail on your environment?

Tried 2 or 3 times, at least (since it takes looong time...).
I'll try it on other environments later.

**Comment by okkez** [comment]
FYI: The following command will reduce test time. This will fail about 3 times in 10 times.

```
$ bundle exec rake test TESTOPTS="--name='test: secondary plugin can do delayed commit even if primary does not do it, and non-committed chunks will be rollbacked by primary'" TEST=test/plugin/test_output_as_buffered_secondary.rb
```

**Comment by henrich** [comment]
Thanks @okkez !

Sometimes succeed, and sometimes failed as below.

```ruby
root@hp:/tmp/fluentd# rake test TESTOPTS="--name='test: secondary plugin can do delayed commit even if primary does not do it, and non-committed chunks will be rollbacked by primary'" TEST=test/plugin/test_output_as_buffered_secondary.rb --trace
** Invoke test (first_time)
** Invoke base_test (first_time)
** Execute base_test
/usr/bin/ruby2.5 -w -I"lib:test" -Eascii-8bit:ascii-8bit  "/usr/lib/ruby/vendor_ruby/rake/rake_test_loader.rb" "test/plugin/test_output_as_buffered_secondary.rb" --name='test: secondary plugin can do delayed commit even if primary does not do it, and non-committed chunks will be rollbacked by primary'
/tmp/fluentd/test/plugin/test_output_as_buffered_secondary.rb:744: warning: assigned but unused variable - prev_num_errors
/tmp/fluentd/lib/fluent/config/literal_parser.rb:218: warning: assigned but unused variable - e
/tmp/fluentd/lib/fluent/log.rb:195: warning: method redefined; discarding old time_format=
/tmp/fluentd/lib/fluent/plugin_helper/socket.rb:118: warning: shadowing outer local variable - cert_path
Loaded suite /usr/lib/ruby/vendor_ruby/rake/rake_test_loader
Started
F
==============================================================================================================================================================================================
     624:         break if @i.buffer.dequeued.size == 0
     625:       end
     626:
  => 627:       assert @i.retry
     628:       logs = @i.log.out.logs
     629:       waiting(4){ sleep 0.1 until logs.select{|l| l.include?("[warn]: failed to flush the buffer chunk, timeout to commit.") }.size == 2 }
     630:       assert{ logs.select{|l| l.include?("[warn]: failed to flush the buffer chunk, timeout to commit.") }.size == 2 }
/tmp/fluentd/test/plugin/test_output_as_buffered_secondary.rb:627:in `block (2 levels) in <class:BufferedOutputSecondaryTest>'
Failure: test: secondary plugin can do delayed commit even if primary does not do it, and non-committed chunks will be rollbacked by primary(BufferedOutputSecondaryTest::secondary plugin feature for buffered output with periodical retry): <nil> is not true.
==============================================================================================================================================================================================

Finished in 2.031937841 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 tests, 20 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
0.49 tests/s, 9.84 assertions/s
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -Eascii-8bit:ascii-8bit  "/usr/lib/ruby/vendor_ruby/rake/rake_test_loader.rb" "test/plugin/test_output_as_buffered_secondary.rb" --name='test: secondary plugin can do delayed commit even if primary does not do it, and non-committed chunks will be rollbacked by primary']
/usr/lib/ruby/vendor_ruby/rake/testtask.rb:130:in `block (3 levels) in define'
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:57:in `sh'
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:105:in `ruby'
/usr/lib/ruby/vendor_ruby/rake/testtask.rb:117:in `block (2 levels) in define'
/usr/lib/ruby/vendor_ruby/rake/file_utils_ext.rb:59:in `verbose'
/usr/lib/ruby/vendor_ruby/rake/testtask.rb:111:in `block in define'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:237:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:212:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:182:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:125:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:83:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:80:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => test => base_test
```
