### ISSUE TITLE
File too large - sendfile error: buff file cant flush

### ISSUE THREAD

**Issue by hongbk** [fluent/fluentd#2385]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

-  fluentd 1.3.3
- Environment information:
	- Operating system: centos 7
	- Kernel version: 3.10.0-514.10.2.el7.x86_64
- Your configuration
```
 <match s3log.apache.**>
    @type exec_filter
    command /opt/td-agent/exec_filter/rgw_log_binder.rb
    tag s3log.parsed
    <format>
      @type json
    </format>
    <parse>
      @type msgpack
    </parse>
    <buffer>
      @type file
      path /var/log/td-agent/accounting/buffer
      flush_interval 10s
      chunk_limit_size 32m
      flush_at_shutdown false
    </buffer>
  </match>

  <match s3log.parsed>
    @type file
    path /root/access.log
    path_suffix
    <format>
      @type pipe
    </format>
    <buffer time>
      timekey 86400
      timekey_zone Asia/Tokyo
      timekey_wait 5m
      flush_thread_count 4
      flush_at_shutdown true
    </buffer>
    append true
  </match>
```
- problem:  i update fluentd version from 0.12 to 1.3.3 and after running for an extended period of time, i see this error like below:
```
2019-04-17 17:22:23 +0900 [info]: starting fluentd-1.4.2 pid=27717 ruby="2.4.5"
2019-04-17 17:22:23 +0900 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/opt/td-agent/embedded/bin/fluentd", "--log", "/var/log/td-agent/td-agent.log", "--daemon", "/var/run/td-agent/td-agent.pid", "--under-supervisor"]
2019-04-17 17:22:24 +0900 [info]: gem 'fluent-plugin-elasticsearch' version '3.1.0'
2019-04-17 17:22:24 +0900 [info]: gem 'fluent-plugin-kafka' version '0.8.4'
2019-04-17 17:22:24 +0900 [info]: gem 'fluent-plugin-record-modifier' version '2.0.0'
2019-04-17 17:22:24 +0900 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.1'
2019-04-17 17:22:24 +0900 [info]: gem 'fluent-plugin-s3' version '1.1.7'
2019-04-17 17:22:24 +0900 [info]: gem 'fluent-plugin-td' version '1.0.0'
2019-04-17 17:22:24 +0900 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2019-04-17 17:22:24 +0900 [info]: gem 'fluent-plugin-webhdfs' version '1.2.3'
2019-04-17 17:22:24 +0900 [info]: gem 'fluentd' version '1.4.2'
2019-04-17 17:22:24 +0900 [info]: gem 'fluentd' version '1.3.3'
2019-04-17 17:22:24 +0900 [info]: #0 adding match pattern="s3log.apache.**" type="exec_filter"
2019-04-17 17:22:24 +0900 [info]: #1 adding match pattern="s3log.apache.**" type="exec_filter"
2019-04-17 17:22:24 +0900 [info]: #0 adding match pattern="s3log.parsed" type="file"
2019-04-17 17:22:24 +0900 [info]: #1 adding match pattern="s3log.parsed" type="elasticsearch"
2019-04-17 17:22:24 +0900 [info]: #0 adding source type="forward"
2019-04-17 17:22:24 +0900 [info]: #0 starting fluentd worker pid=28790 ppid=28774 worker=0
2019-04-17 17:22:24 +0900 [info]: #0 listening port port=5000 bind="0.0.0.0"
2019-04-17 17:22:24 +0900 [info]: #0 fluentd worker is now running worker=0
2019-04-17 17:22:24 +0900 [info]: #1 Detected ES 6.x: ES 7.x will only accept `_doc` in type_name.
2019-04-17 17:22:24 +0900 [info]: #1 adding source type="forward"
2019-04-17 17:22:24 +0900 [info]: #1 starting fluentd worker pid=28791 ppid=28774 worker=1
2019-04-17 17:22:24 +0900 [info]: #1 listening port port=5001 bind="0.0.0.0"
2019-04-17 17:22:24 +0900 [info]: #1 fluentd worker is now running worker=1
2019-04-17 17:23:01 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=27.338050535006914 slow_flush_log_threshold=20.0 plugin_id="object:3fa5fb5dd884"
2019-04-17 17:23:29 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=27.836166456982028 slow_flush_log_threshold=20.0 plugin_id="object:3fa5fb5dd884"
2019-04-17 17:23:56 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=27.19106018700404 slow_flush_log_threshold=20.0 plugin_id="object:3fa5fb5dd884"
2019-04-17 17:24:25 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=27.947554534999654 slow_flush_log_threshold=20.0 plugin_id="object:3fa5fb5dd884"
2019-04-17 17:24:53 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=28.211437780992128 slow_flush_log_threshold=20.0 plugin_id="object:3fa5fb5dd884"
2019-04-17 17:25:25 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=31.367226305010263 slow_flush_log_threshold=20.0 plugin_id="object:3fa5fb5dd884"
2019-04-17 17:25:54 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=29.292056334990775 slow_flush_log_threshold=20.0 plugin_id="object:3fa5fb5dd884"
2019-04-17 17:26:22 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=28.071627512021223 slow_flush_log_threshold=20.0 plugin_id="object:3fa5fb5dd884"
2019-04-17 17:26:53 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=30.0183132509992 slow_flush_log_threshold=20.0 plugin_id="object:3fa5fb5dd884"
2019-04-17 17:27:22 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=28.99996836599894 slow_flush_log_threshold=20.0 plugin_id="object:3fa5fb5dd884"
2019-04-17 17:27:49 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=27.008288053999422 slow_flush_log_threshold=20.0 plugin_id="object:3fa5fb5dd884"
2019-04-17 17:44:27 +0900 [warn]: #1 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=20.787148875999264 slow_flush_log_threshold=20.0 plugin_id="object:3fc937c98034"
2019-04-17 18:49:56 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-04-17 18:49:57 +0900 chunk="586b6ce135bdebef1dd50b4dcfd3c273" error_class=Errno::EFBIG error="File too large - sendfile"
2019-04-17 18:49:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/buffer/chunk.rb:162:in `copy_stream'
2019-04-17 18:49:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/buffer/chunk.rb:162:in `block in write_to'
2019-04-17 18:49:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/buffer/file_chunk.rb:172:in `open'
2019-04-17 18:49:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/buffer/chunk.rb:161:in `write_to'
2019-04-17 18:49:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/out_exec_filter.rb:277:in `write'
2019-04-17 18:49:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1125:in `try_flush'
2019-04-17 18:49:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
2019-04-17 18:49:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
2019-04-17 18:49:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-04-17 18:49:57 +0900 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2019-04-17 18:49:58 +0900 chunk="586b6ce135bdebef1dd50b4dcfd3c273" error_class=Errno::EFBIG error="File too large - sendfile"
```
- i check file size, but not too large
```
[root@xxxx ~]# ll -lh /var/log/td-agent/accounting/buffer/ | grep 586b6ce135bdebef1dd50b4dcfd3c273
-rw-r--r-- 1 td-agent td-agent 3.8M  4月 17 18:49 buffer.q586b6ce135bdebef1dd50b4dcfd3c273.log
-rw-r--r-- 1 td-agent td-agent   66  4月 17 18:49 buffer.q586b6ce135bdebef1dd50b4dcfd3c273.log.meta
[root@xxxx ~]# 
```

**Comment by repeatedly** [comment]
ulimit is bigger than 3.8M, right?

**Comment by hongbk** [comment]
yes, file size is unlimited
```
[root@xxxx ~]# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31217
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 131072
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 32768
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[root@xxxx~]#
```

**Comment by tnaoto** [comment]
Hi

I work in the same team as Mr. hongbk.
This problem has not been resolved yet.

Detailed log will be attached.
Advice please.


The trace of the place where the error occurred is as follows.
```
2019-05-20 13:00:42 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-05-20 13:00:43 +0900 chunk="58949c653edc89860ae0043aa6acfd6d" error_class=Errno::EFBIG error="File too large - sendfile"
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/buffer/chunk.rb:162:in `copy_stream'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/buffer/chunk.rb:162:in `block in write_to'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/buffer/file_chunk.rb:172:in `open'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/buffer/chunk.rb:161:in `write_to'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/out_exec_filter.rb:278:in `write'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```


```
[]# uname -a
Linux stgnosadlog101 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[]# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core) 

sysctl -p
net.core.somaxconn = 1024
net.core.netdev_max_backlog = 5000
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_wmem = 4096 12582912 16777216
net.ipv4.tcp_rmem = 4096 12582912 16777216
net.ipv4.tcp_max_syn_backlog = 8096
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_tw_reuse = 1
net.ipv4.ip_local_port_range = 10240 65535

```

All logs
```
2019-05-20 10:35:48 +0900 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2019-05-20 10:35:48 +0900 [info]: adding match pattern="s3log.apache.**" type="exec_filter"
2019-05-20 10:35:48 +0900 [info]: adding match pattern="s3log.parsed" type="file"
2019-05-20 10:35:48 +0900 [info]: adding match pattern="s3log.apache.**" type="exec_filter"
2019-05-20 10:35:48 +0900 [info]: adding match pattern="s3log.parsed" type="elasticsearch"
2019-05-20 10:35:48 +0900 [info]: adding source type="forward"
2019-05-20 10:35:48 +0900 [info]: adding source type="forward"
2019-05-20 10:35:48 +0900 [info]: using configuration file: <ROOT>
  <system>
    workers 2
  </system>
  <worker 0>
    <source>
      @type forward
      port 5000
      bind "0.0.0.0"
    </source>
    <match s3log.apache.**>
      @type exec_filter
      command "/opt/td-agent/exec_filter/xxxxx.rb"
      tag "s3log.parsed"
      <format>
        @type "json"
      </format>
      <parse>
        @type "msgpack"
      </parse>
      <buffer>
        @type "file"
        path "/var/log/td-agent/xxx/buffer"
        flush_interval 4s
        chunk_limit_size 16m
        flush_at_shutdown false
      </buffer>
    </match>
    <match s3log.parsed>
      @type file
      path "/xxxx/logs/xxxxx.log"
      path_suffix ""
      append true
      <format>
        @type "pipe"
      </format>
      <buffer time>
        timekey 86400
        timekey_zone "Asia/Tokyo"
        timekey_wait 5m
        flush_thread_count 4
        flush_at_shutdown true
        path "/xxxx/logs/xxxx.log"
      </buffer>
    </match>
  </worker>
  <worker 1>
    <source>
      @type forward
      port 5001
      bind "0.0.0.0"
    </source>
    <match s3log.apache.**>
      @type exec_filter
      command "/opt/td-agent/exec_filter/xxx.rb"
      tag "s3log.parsed"
      slow_flush_log_threshold 40
      <format>
        @type "json"
      </format>
      <parse>
        @type "msgpack"
        localtime true
      </parse>
      <buffer>
        flush_interval 10s
      </buffer>
    </match>
    <match s3log.parsed>
      @type elasticsearch
      hosts "xxxx"
      type_name "analyze"
      logstash_format true
      logstash_prefix "xxxx-101"
      time_key_exclude_timestamp true
      time_key "timestamp"
      utc_index false
      reconnect_on_error true
      reload_on_failure true
      reload_connections false
      request_timeout 120s
      <buffer>
        @type "memory"
        retry_max_times 17
        retry_max_interval 1.0s
        flush_thread_count 4
        flush_interval 1s
        flush_at_shutdown true
      </buffer>
    </match>
  </worker>
</ROOT>
2019-05-20 10:35:48 +0900 [info]: starting fluentd-1.4.2 pid=1071 ruby="2.4.5"
2019-05-20 10:35:48 +0900 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/opt/td-agent/embedded/bin/fluentd", "--log", "/var/log/td-agent/td-agent.log", "--daemon", "/var/run/td-agent/td-agent.pid", "--under-supervisor"]
2019-05-20 10:35:49 +0900 [info]: gem 'fluent-plugin-elasticsearch' version '3.4.3'
2019-05-20 10:35:49 +0900 [info]: gem 'fluent-plugin-elasticsearch' version '3.1.0'
2019-05-20 10:35:49 +0900 [info]: gem 'fluent-plugin-kafka' version '0.9.2'
2019-05-20 10:35:49 +0900 [info]: gem 'fluent-plugin-kafka' version '0.8.4'
2019-05-20 10:35:49 +0900 [info]: gem 'fluent-plugin-prometheus' version '1.3.0'
2019-05-20 10:35:49 +0900 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
2019-05-20 10:35:49 +0900 [info]: gem 'fluent-plugin-record-modifier' version '2.0.0'
2019-05-20 10:35:49 +0900 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.1'
2019-05-20 10:35:49 +0900 [info]: gem 'fluent-plugin-s3' version '1.1.9'
2019-05-20 10:35:49 +0900 [info]: gem 'fluent-plugin-td' version '1.0.0'
2019-05-20 10:35:49 +0900 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2019-05-20 10:35:49 +0900 [info]: gem 'fluent-plugin-webhdfs' version '1.2.3'
2019-05-20 10:35:49 +0900 [info]: gem 'fluentd' version '1.4.2'
2019-05-20 10:35:49 +0900 [info]: #0 adding match pattern="s3log.apache.**" type="exec_filter"
2019-05-20 10:35:49 +0900 [info]: #1 adding match pattern="s3log.apache.**" type="exec_filter"
2019-05-20 10:35:49 +0900 [info]: #0 adding match pattern="s3log.parsed" type="file"
2019-05-20 10:35:49 +0900 [info]: #1 adding match pattern="s3log.parsed" type="elasticsearch"
2019-05-20 10:35:49 +0900 [info]: #0 adding source type="forward"
2019-05-20 10:35:49 +0900 [info]: #0 starting fluentd worker pid=2150 ppid=2145 worker=0
2019-05-20 10:35:49 +0900 [info]: #0 listening port port=5000 bind="0.0.0.0"
2019-05-20 10:35:49 +0900 [info]: #0 fluentd worker is now running worker=0
2019-05-20 10:35:49 +0900 [info]: #1 Detected ES 6.x: ES 7.x will only accept `_doc` in type_name.
2019-05-20 10:35:49 +0900 [info]: #1 adding source type="forward"
2019-05-20 10:35:49 +0900 [info]: #1 starting fluentd worker pid=2151 ppid=2145 worker=1
2019-05-20 10:35:49 +0900 [info]: #1 listening port port=5001 bind="0.0.0.0"
2019-05-20 10:35:49 +0900 [info]: #1 fluentd worker is now running worker=1
2019-05-20 11:22:36 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=25.332830129000286 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:33:40 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=27.884042015999967 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:34:26 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=37.69371274199966 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:35:41 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=60.36171208099995 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:36:01 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=20.20440501999974 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:37:02 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=60.154139103000034 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:37:41 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=39.045153389999996 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:38:37 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=55.792495661999965 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:39:38 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=59.40090662500006 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:40:35 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=56.67484779100005 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:41:38 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=62.4803975599998 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:42:39 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=59.893230584999856 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:43:36 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=57.17502806399989 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:44:36 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=58.93918931899998 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:45:32 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=56.58739697600049 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:46:36 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=63.53212713100038 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:47:33 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=56.361491801999364 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:48:46 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=72.16737529500006 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 11:49:11 +0900 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=25.2513490729998 slow_flush_log_threshold=20.0 plugin_id="object:3f856e6e6f1c"
2019-05-20 13:00:42 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-05-20 13:00:43 +0900 chunk="58949c653edc89860ae0043aa6acfd6d" error_class=Errno::EFBIG error="File too large - sendfile"
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/buffer/chunk.rb:162:in `copy_stream'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/buffer/chunk.rb:162:in `block in write_to'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/buffer/file_chunk.rb:172:in `open'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/buffer/chunk.rb:161:in `write_to'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/out_exec_filter.rb:278:in `write'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
  2019-05-20 13:00:42 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-05-20 13:00:43 +0900 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2019-05-20 13:00:44 +0900 chunk="58949c653edc89860ae0043aa6acfd6d" error_class=Errno::EFBIG error="File too large - sendfile"
  2019-05-20 13:00:43 +0900 [warn]: #0 suppressed same stacktrace
2019-05-20 13:00:44 +0900 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2019-05-20 13:00:46 +0900 chunk="58949c653edc89860ae0043aa6acfd6d" error_class=Errno::EFBIG error="File too large - sendfile"
  2019-05-20 13:00:44 +0900 [warn]: #0 suppressed same stacktrace
2019-05-20 13:00:46 +0900 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2019-05-20 13:00:50 +0900 chunk="58949c653edc89860ae0043aa6acfd6d" error_class=Errno::EFBIG error="File too large - sendfile"
  2019-05-20 13:00:46 +0900 [warn]: #0 suppressed same stacktrace
2019-05-20 13:00:50 +0900 [warn]: #0 failed to flush the buffer. retry_time=4 next_retry_seconds=2019-05-20 13:00:57 +0900 chunk="58949c653edc89860ae0043aa6acfd6d" error_class=Errno::EFBIG error="File too large - sendfile"
  2019-05-20 13:00:50 +0900 [warn]: #0 suppressed same stacktrace
2019-05-20 13:00:57 +0900 [warn]: #0 failed to flush the buffer. retry_time=5 next_retry_seconds=2019-05-20 13:01:14 +0900 chunk="58949c653edc89860ae0043aa6acfd6d" error_class=Errno::EFBIG error="File too large - sendfile"
  2019-05-20 13:00:57 +0900 [warn]: #0 suppressed same stacktrace
2019-05-20 13:01:14 +0900 [warn]: #0 failed to flush the buffer. retry_time=6 next_retry_seconds=2019-05-20 13:01:49 +0900 chunk="58949c653edc89860ae0043aa6acfd6d" error_class=Errno::EFBIG error="File too large - sendfile"
  2019-05-20 13:01:14 +0900 [warn]: #0 suppressed same stacktrace
2019-05-20 13:01:49 +0900 [warn]: #0 failed to flush the buffer. retry_time=7 next_retry_seconds=2019-05-20 13:02:51 +0900 chunk="58949c653edc89860ae0043aa6acfd6d" error_class=Errno::EFBIG error="File too large - sendfile"
  2019-05-20 13:01:49 +0900 [warn]: #0 suppressed same stacktrace
2019-05-20 13:02:51 +0900 [warn]: #0 failed to flush the buffer. retry_time=8 next_retry_seconds=2019-05-20 13:05:01 +0900 chunk="58949c653edc89860ae0043aa6acfd6d" error_class=Errno::EFBIG error="File too large - sendfile"
  2019-05-20 13:02:51 +0900 [warn]: #0 suppressed same stacktrace
2019-05-20 13:05:01 +0900 [warn]: #0 failed to flush the buffer. retry_time=9 next_retry_seconds=2019-05-20 13:08:59 +0900 chunk="58949c653edc89860ae0043aa6acfd6d" error_class=Errno::EFBIG error="File too large - sendfile"
  2019-05-20 13:05:01 +0900 [warn]: #0 suppressed same stacktrace
2019-05-20 13:08:59 +0900 [warn]: #0 failed to flush the buffer. retry_time=10 next_retry_seconds=2019-05-20 13:17:45 +0900 chunk="58949c653edc89860ae0043aa6acfd6d" error_class=Errno::EFBIG error="File too large - sendfile"
  2019-05-20 13:08:59 +0900 [warn]: #0 suppressed same stacktrace
2019-05-20 13:10:08 +0900 [info]: Received graceful stop
2019-05-20 13:10:08 +0900 [info]: Received graceful stop
```

```
[]# pstree td-agent -p -u -h
fluentd(2145)─┬─ruby(2150)─┬─rgw_log_binder.(2164)───{rgw_log_binder.}(2168)
              │            ├─{ruby}(2153)
              │            ├─{ruby}(2156)
              │            ├─{ruby}(2157)
              │            ├─{ruby}(2158)
              │            ├─{ruby}(2159)
              │            ├─{ruby}(2160)
              │            ├─{ruby}(2161)
              │            ├─{ruby}(2162)
              │            ├─{ruby}(2163)
              │            ├─{ruby}(2165)
              │            ├─{ruby}(2166)
              │            └─{ruby}(2167)
              ├─ruby(2151)─┬─rgw_log_binder.(2177)───{rgw_log_binder.}(2180)
              │            ├─{ruby}(2154)
              │            ├─{ruby}(2169)
              │            ├─{ruby}(2170)
              │            ├─{ruby}(2171)
              │            ├─{ruby}(2172)
              │            ├─{ruby}(2173)
              │            ├─{ruby}(2174)
              │            ├─{ruby}(2175)
              │            ├─{ruby}(2176)
              │            ├─{ruby}(2178)
              │            ├─{ruby}(2179)
              │            └─{ruby}(2181)
              ├─{fluentd}(2146)
              ├─{fluentd}(2148)
              └─{fluentd}(2149)
```

I tried taking "strace" but there was no call to "sendfile".

**Comment by vishaljoshi** [comment]
@hongbk  @tnaoto  have you guys  resolved this  issue? we are facing the same error.
