### ISSUE TITLE
Cannot use env var in private key passphrase

### ISSUE THREAD

**Issue by rolandjitsu** [fluent/fluentd#2410]
**Version**
td-agent `3.4.0`

**OS**
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Kernel**
`4.15.0-1030-gcp`

**Configuration**
```
# Receive messages from Fluent Bit
# https://docs.fluentd.org/v1.0/articles/in_forward
<source>
  @type forward
  host 0.0.0.0
  port 5000
  <transport tls>
    cert_path /etc/td-agent/certs/fluentd.cert.pem
    private_key_path /etc/td-agent/certs/fluentd.key.pem
    private_key_passphrase "#{ENV['FLD_CERT_PASS']}"
    client_cert_auth true
    ca_path /etc/td-agent/certs/ca.cert.pem
  </transport>
  <security>
    self_hostname "#{ENV['HOSTNAME']}"
    shared_key "#{ENV['FLD_SHARED_KEY']}"
  </security>
</source>

# Save data in ES
# https://docs.fluentd.org/v1.0/articles/out_elasticsearch
<match my.logs>
  @type elasticsearch
  hosts "#{ENV['ES_NODE_1']}","#{ENV['ES_NODE_2']}"
  user fluentd
  password "#{ENV['FLD_ES_PASS']}"
  index_name ${tag}
  <buffer>
    flush_thread_count 2
  </buffer>
</match>
```

**Issue**
I was trying to use an env var to get the pass for a private key when configuring the forward input, but it seems like that causes a problem.

**Logs**
```
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/cert_option.rb:79:in `new'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/cert_option.rb:79:in `cert_option_load'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/cert_option.rb:55:in `cert_option_server_validate!'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/server.rb:316:in `configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/in_forward.rb:102:in `configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin.rb:164:in `configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:320:in `add_source'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:160:in `block in configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:156:in `each'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:156:in `configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/engine.rb:131:in `configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/engine.rb:96:in `run_configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:801:in `run_configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:579:in `dry_run'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:597:in `supervise'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:502:in `run_supervisor'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/bin/fluentd:8:in `<top (required)>'
```

**Comment by ganmacs** [comment]
Could you paste **complete** error logs?

and this is similar to https://groups.google.com/forum/#!topic/fluentd/RJJWAjag2Lc

> How to set environment variable for fluentd?
> I assume your environment variable is not passed to fluentd process.

**Comment by rolandjitsu** [comment]
@ganmacs there's not much else besides what I pasted:
```
May 10 05:17:31 vanaheim systemd[1]: Starting td-agent: Fluentd based data collector for Treasure Data...
May 10 05:17:32 vanaheim fluentd[20918]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/cert_option.rb:79:in `initialize': Neither PUB key nor PRIV key: nested asn1 error (OpenSSL::PKey::RSAError)
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/cert_option.rb:79:in `new'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/cert_option.rb:79:in `cert_option_load'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/cert_option.rb:55:in `cert_option_server_validate!'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/server.rb:316:in `configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/in_forward.rb:102:in `configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin.rb:164:in `configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:320:in `add_source'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:160:in `block in configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:156:in `each'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:156:in `configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/engine.rb:131:in `configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/engine.rb:96:in `run_configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:801:in `run_configure'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:579:in `dry_run'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:597:in `supervise'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:502:in `run_supervisor'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/bin/fluentd:8:in `<top (required)>'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/bin/fluentd:23:in `load'
May 10 05:17:32 vanaheim fluentd[20918]:         from /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
May 10 05:17:32 vanaheim systemd[1]: td-agent.service: Control process exited, code=exited status=1
May 10 05:17:32 vanaheim systemd[1]: td-agent.service: Failed with result 'exit-code'.
May 10 05:17:32 vanaheim systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
```

**Comment by ganmacs** [comment]
I wanted to look at this line which shows the error name.

```
May 10 05:17:32 vanaheim fluentd[20918]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/cert_option.rb:79:in `initialize': Neither PUB key nor PRIV key: nested asn1 error (OpenSSL::PKey::RSAError)
```

I checked this. This error could also occur if private_key_passphrase is wrong.
I think it could pass the env var. but passphrase might be wrong.
So please check the value of passphrase is correct.

**Comment by rolandjitsu** [comment]
I'm sure it's correct, because it's currently running with the passphrase in plain text. It's the same for the shared key, it's not working. `FLD_ES_PASS` works tough.

Note that these vars are in `/etc/environment` file.

**Comment by didjcodt** [comment]
Hi, 
I am currently facing the exact same issue. The `shared_key` does not accept the env variable (directly given by a docker container), but it works for other env variables and the plaintext replacement works too. Do you have any news on this issue?

**Comment by repeatedly** [comment]
I didn't reproduce this problem on my env, fluentd v1.5.0 / ruby 2.6.3.
fluentd's envvar handling seems to work with shared_key.
Here is my test:

- in_forward conf

```
<source>
  @type forward
  port 5000
  <security>
    self_hostname "#{Socket.gethostname}"
    shared_key "#{ENV['FLD_SHARED_KEY']}"
  </security>
</source>

<match test.**>
  @type stdout
</match>
```

- out_forward conf

```
<source>
  @type forward
</source>

<match test.**>
  @type forward
  <security>
    self_hostname "#{Socket.gethostname}"
    shared_key "#{ENV['FLD_SHARED_KEY']}"
  </security>
  <server>
    host 127.0.0.1
    port 5000
  </server>
  <buffer>
    flush_interval 3s # for test
  </buffer>
</match>
```

- run out_forward with test shared_key

```
FLD_SHARED_KEY=test RUBYLIB=~/dev/fluentd/fluentd/lib ~/dev/fluentd/fluentd/bin/fluentd -c out.conf
```

- send test event

```
echo '{"k":"v"}' | fluent-cat test.foo
```

- run in_forward with test shared_key

```
% FLD_SHARED_KEY=test RUBYLIB=~/dev/fluentd/fluentd/lib ~/dev/fluentd/fluentd/bin/fluentd -c in.conf
...snip...
2019-05-22 12:03:46 +0200 [info]: adding source type="forward"
"test"  # Insert print debug to check the shared_key value is correct or not
2019-05-22 12:03:46 +0200 [info]: #0 starting fluentd worker pid=93603 ppid=93590 worker=0
2019-05-22 12:03:46 +0200 [info]: #0 listening port port=5000 bind="0.0.0.0"
2019-05-22 12:03:46 +0200 [info]: #0 fluentd worker is now running worker=0
2019-05-22 12:05:09.920380000 +0200 test.foo: {"k":"v"}
^C2019-05-22 12:05:16 +0200 [info]: Received graceful stop
```

- run in_forward with testt shared_key (wrong test)

```
% FLD_SHARED_KEY=testt RUBYLIB=~/dev/fluentd/fluentd/lib ~/dev/fluentd/fluentd/bin/fluentd -c in.conf
...snip...
2019-05-22 12:05:24 +0200 [info]: adding source type="forward"
"testt"
2019-05-22 12:05:24 +0200 [info]: #0 starting fluentd worker pid=93779 ppid=93766 worker=0
2019-05-22 12:05:24 +0200 [info]: #0 listening port port=5000 bind="0.0.0.0"
2019-05-22 12:05:24 +0200 [info]: #0 fluentd worker is now running worker=0
2019-05-22 12:05:31 +0200 [warn]: #0 Shared key mismatch address="127.0.0.1" hostname="repeatedly.local"
```

So there are several cases:
- parameter value is wrong
- passing envvar is something wrong, change value or insert something.

Maybe, you need to check passed value is wrong or not to add debug code.

**Comment by rolandjitsu** [comment]
Could it be special characters such as `+`, `=` that makes it break?

**Comment by repeatedly** [comment]
fluentd itself doesn't touch it.
Above my env, "tes+t" works correctly.

```
% FLD_SHARED_KEY=tes+t RUBYLIB=~/dev/fluentd/fluentd/lib ~/dev/fluentd/fluentd/bin/fluentd -c in.conf
...snip...
2019-05-22 12:22:31 +0200 [info]: adding source type="forward"
"tes+t"
2019-05-22 12:22:31 +0200 [info]: #0 starting fluentd worker pid=93908 ppid=93895 worker=0
2019-05-22 12:22:31 +0200 [info]: #0 listening port port=5000 bind="0.0.0.0"
2019-05-22 12:22:31 +0200 [info]: #0 fluentd worker is now running worker=0
2019-05-22 12:22:49.299183000 +0200 test.foo: {"k":"v"}
```

But I'm not sure the other environment, e.g. handling envvar of `/etc/environment`.

**Comment by didjcodt** [comment]
An upgrade to v1.5 worked, thanks!
For others who might get issues with it: I also got issues because of newlines in variable

**Comment by ganmacs** [comment]
Seem to be fixed.
