### ISSUE TITLE
datacounter NaN error

### ISSUE THREAD

**Issue by stager0909-ray** [fluent/fluentd#2414]
Hello, I need your help.

fluentd version : 1.4.2
cat /etc/os-release : Alpine v3.7
uname -r : 3.10.0-957.1.3.e17.x86_64
datacounter version = 1.0.0
```
<source>
  @type tail
  path /data0/haproxy/log/haproxy.log
  pos_file /fluntd/log_pos/haproxy.log.tail.pos
  rotate_wait 3s
  tag http.log
  format json
  time_key time
  time_format %d/%b/%Y:%H:%M:%S.%N
</source>
```
and I use datacounter plugin after some step
```
<match status_code_v2.haproxy.access.rewrite.from.**.to.**>
  @type datacounter
  count_interval 5s
  aggregate tag
  output_per_tag true
  tag_prefix datacounter
  count_key status_code

  pattern1 1xx ^1\d\d$
  pattern2 2xx ^2\d\d$
  pattern3 3xx ^3\d\d$
  pattern4 404 ^404$
  pattern5 4xx ^4\d\d$
  pattern6 502 ^502$
  pattern7 503 ^503$
  pattern8 504 ^504$
  pattern9 5xx ^5\d\d$
</match>
```
question
1. Log rotation logs occur at the same time. I use one tail process.
Why is it a single process and does it happen at the same time?
```
2019-05-20 23:30:19 +0900 [info]: #0 following tail of /data0/haproxy/log/haproxy.log
2019-05-20 23:31:21 +0900 [info]: #0 detected rotation of /data0/haproxy/log/haproxy.log; waiting 3 seconds
2019-05-20 23:31:21 +0900 [info]: #0 detected rotation of /data0/haproxy/log/haproxy.log; waiting 3 seconds
2019-05-20 23:31:21 +0900 [info]: #0 detected rotation of /data0/haproxy/log/haproxy.log; waiting 3 seconds
2019-05-20 23:31:21 +0900 [info]: #0 following tail of /data0/haproxy/log/haproxy.log
2019-05-20 23:32:23 +0900 [info]: #0 detected rotation of /data0/haproxy/log/haproxy.log; waiting 3 seconds
2019-05-20 23:32:23 +0900 [info]: #0 detected rotation of /data0/haproxy/log/haproxy.log; waiting 3 seconds
2019-05-20 23:32:23 +0900 [info]: #0 detected rotation of /data0/haproxy/log/haproxy.log; waiting 3 seconds
2019-05-20 23:32:23 +0900 [info]: #0 following tail of /data0/haproxy/log/haproxy.log
2019-05-20 23:33:22 +0900 [info]: #0 detected rotation of /data0/haproxy/log/haproxy.log; waiting 3 seconds
2019-05-20 23:33:22 +0900 [info]: #0 detected rotation of /data0/haproxy/log/haproxy.log; waiting 3 seconds
2019-05-20 23:33:22 +0900 [info]: #0 detected rotation of /data0/haproxy/log/haproxy.log; waiting 3 seconds
2019-05-20 23:33:22 +0900 [info]: #0 following tail of /data0/haproxy/log/haproxy.log
```

2. datacounter NaN Error
```
2019-05-20 23:33:23 +0900 [error]: #0 Unexpected error raised. Stopping the timer. title=:out_datacounter_timer error_class=FloatDomainError error="NaN"
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-datacounter-1.0.0/lib/fluent/plugin/out_datacounter.rb:183:in `floor'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-datacounter-1.0.0/lib/fluent/plugin/out_datacounter.rb:183:in `block in generate_fields'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-datacounter-1.0.0/lib/fluent/plugin/out_datacounter.rb:180:in `each'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-datacounter-1.0.0/lib/fluent/plugin/out_datacounter.rb:180:in `each_with_index'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-datacounter-1.0.0/lib/fluent/plugin/out_datacounter.rb:180:in `generate_fields'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-datacounter-1.0.0/lib/fluent/plugin/out_datacounter.rb:214:in `block in generate_output_per_tags'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-datacounter-1.0.0/lib/fluent/plugin/out_datacounter.rb:213:in `each'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-datacounter-1.0.0/lib/fluent/plugin/out_datacounter.rb:213:in `generate_output_per_tags'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-datacounter-1.0.0/lib/fluent/plugin/out_datacounter.rb:232:in `flush_per_tags'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-datacounter-1.0.0/lib/fluent/plugin/out_datacounter.rb:239:in `flush_emit'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-datacounter-1.0.0/lib/fluent/plugin/out_datacounter.rb:253:in `watch'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run_once'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-05-20 23:33:23 +0900 [error]: #0 /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-05-20 23:33:24 +0900 [error]: #0 Timer detached. title=:out_datacounter_timer```

/data0/haproxy/haproxy.log to <source> tail and count with datacounter. However, when log # 1 continues and log # 2 occurs, fluent does not operate normally.
The occurrence of NaN is expected to occur when there is no data for 5 seconds of datacounter count_interval. Is that right?
If so, it is not understood that there is no data for 5 seconds. This is because rotate_wait 3s, datacounter count_interval 5s.

Please help me.

**Comment by stager0909-ray** [comment]
1. Log rotation logs occur at the same time. I use one tail process.
Why is it a single process and does it happen at the same time?
=> I sovled this issue. When I use rewrite_tag_filter, if there is no invert true setting, the same log appears at the same time as below. invert true After adding the setting, I noticed that the log was only taken once at the same time.

But I do not sovled datacounter NaN issue. Please help me.

**Comment by stager0909-ray** [comment]
When I use aggregate as a tag in datacounter, can NaN occur if there are many tags?
