### ISSUE TITLE
Multiline parser does not log

### ISSUE THREAD

**Issue by lindsjan** [fluent/fluentd#2476]
**Describe the bug**
For one Jboss application i am forced to read the separate log files. Added <source> - definition with parse type none - works fine but stack traces end up each in separate events. After changing parser type to multiline, rows not ending up in Splunk. No config errors in fluent log. With trace on, there are no matching rows sent to HEC.  emit_unmatched_lines set to true but no such reported either in the fluentd log.

**To Reproduce**
source- definition:
```
  <source>
      @id tail.file.jboss_server
      @type tail
      @label @SPLUNK
      tag tail.file.jboss_server
      path /logs/*/app/*/server.log
      pos_file /logs/jboss_server-fluentd-messages.pos
      read_from_head true
      path_key source
      emit_unmatched_lines true
      multiline_flush_interval 5s
        <parse>
          @type multiline
          time_key time
          format_firstline /\d{4}-\d{2}-\d{2}/
          format1  /^(?<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{1,2}:\d{1,2},\d{3}) (?<message>.*)/
        </parse>
    </source>
```
sample log row:
```
2019-07-03 09:15:19,058 ERROR [com.some.app.UserDetailsServiceImpl] (http-0.0.0.0:8080-6) Error retrieving user information for username nonexisting: org.springframework.security.core.userdetails.UsernameNotFoundException: User not found: nonexisting
	at com.some.app.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.java:86) [Runner_Arc.jar:]
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:82) [spring-security-core-3.0.2.RELEASE.jar:]
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:124) [spring-security-core-3.0.2.RELEASE.jar:]
	at org.springframework.security.authentication.ProviderManager.doAuthentication(ProviderManager.java:120) [spring-security-core-3.0.2.RELEASE.jar:]
	at org.springframework.security.authentication.AbstractAuthenticationManager.authenticate(AbstractAuthenticationManager.java:48) [spring-security-core-3.0.2.RELEASE.jar:]
```

**Expected behavior**
Log row sent as one event to Hec
Reasonable error or warning in fluentd log if there is something wrong with the parser conf or if the regexp does not match

**Your Environment**
- Splunc Connect 1.1.0 (fluentd-hec:1.1.0)

**Your Configuration**
see above

**Your Error Log**
Nothing written in the fluentd log concerning this

**Additional context**

Used Fluentular to verify format1 regexp pattern.

**Comment by repeatedly** [comment]
I tested your configuration with stdout and it works. So no warning for regexp pattern seems correct.

```
2019-07-03 09:15:19.058000000 +0900 tail.file.jboss_server: {"message":"ERROR [com.some.app.UserDetailsServiceImpl] (http-0.0.0.0:8080-6) Error retrieving user information for username nonexisting: org.springframework.security.core.userdetails.UsernameNotFoundException: User not found: nonexisting\n\tat com.some.app.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.java:86) [Runner_Arc.jar:]\n\tat org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:82) [spring-security-core-3.0.2.RELEASE.jar:]\n\tat org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:124) [spring-security-core-3.0.2.RELEASE.jar:]\n\tat org.springframework.security.authentication.ProviderManager.doAuthentication(ProviderManager.java:120) [spring-security-core-3.0.2.RELEASE.jar:]\n\tat org.springframework.security.authentication.AbstractAuthenticationManager.authenticate(AbstractAuthenticationManager.java:48) [spring-security-core-3.0.2.RELEASE.jar:]","source":"./server.log"}
```

You can use stdout to check in_tail works or not on your test.
