### ISSUE TITLE
splunk-kubernetes-logging monit_agent

### ISSUE THREAD

**Issue by ronak-agarwal** [fluent/fluentd#2536]
Installing spunk-logging-agent as daemonSet on all Openshift nodes using helm charts provided.
My helm client version - 1.2.0
My Openshift version - 3.9.0

helm upgrade  --wait --install --timeout 600  --values ./splunk-kubernetes-logging/values.yaml splunk-kubernetes-logging ./splunk-kubernetes-logging --namespace=logging --tiller-namespace tiller

only changed value in values .yaml is cluster_name to 'oc1-nwsl-site:443' which is my cluster-name when I see my 'oc config view'
```
/usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/config/basic_parser.rb:92:in `parse_error!': expected end of line at output.conf line 104,163 (Fluent::ConfigParseError)
103:     @type jq_transformer
104:     jq ".record.source = \"namespace:#{ENV['MY_NAMESPACE']}/pod:#{ENV['MY_POD_NAME']}\" | .record.sourcetype = \"fluentd:monitor-agent\" | .record.cluster_name = "oc1-nwsl-site:443" | .record"

     -------------------------------------------------------------------------------------------------------------------------------------------------------------------^
105:   </filter>
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/config/v1_parser.rb:132:in `parse_element'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/config/v1_parser.rb:95:in `parse_element'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/config/v1_parser.rb:95:in `parse_element'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/config/v1_parser.rb:166:in `block in eval_include'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/config/v1_parser.rb:160:in `each'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/config/v1_parser.rb:160:in `eval_include'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/config/v1_parser.rb:145:in `parse_include'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/config/v1_parser.rb:104:in `parse_element'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/config/v1_parser.rb:43:in `parse!'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/config/v1_parser.rb:33:in `parse'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/config.rb:39:in `parse'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/supervisor.rb:766:in `read_config'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/supervisor.rb:477:in `run_supervisor'
	from /usr/local/bundle/gems/fluentd-1.4.0/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/bundle/gems/fluentd-1.4.0/bin/fluentd:8:in `<top (required)>'
	from /usr/local/bundle/bin/fluentd:23:in `load'
	from /usr/local/bundle/bin/fluentd:23:in `<main>'
```

**Comment by ganmacs** [comment]
You need escape double quote.
`jq ".record.source = \"namespace:#{ENV['MY_NAMESPACE']}/pod:#{ENV['MY_POD_NAME']}\" | .record.sourcetype = \"fluentd:monitor-agent\" | .record.cluster_name = \"oc1-nwsl-site:443\" | .record"` is right.

BTW, see https://github.com/fluent/fluentd/blob/8535c9a5b0ee4f7e3b0dd65de8954f9436eafecc/CONTRIBUTING.md#got-a-question-or-problem
