### ISSUE TITLE
fluentd exits with Errno::ETIMEDOUT error="Connection timed out - SSL_accept"

### ISSUE THREAD

**Issue by maadtechie** [fluent/fluentd#2548]
```2019-08-01 06:59:41 +0000 [info]: gem 'fluent-plugin-gelf-hs' version '1.0.8'
2019-08-01 06:59:41 +0000 [info]: gem 'fluent-plugin-newsyslog' version '0.1.2'
2019-08-01 06:59:41 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
2019-08-01 06:59:41 +0000 [info]: gem 'fluentd' version '1.4.2'
2019-08-01 06:59:41 +0000 [info]: adding match pattern="fluent.**" type="null"
2019-08-01 06:59:41 +0000 [info]: adding filter pattern="**" type="record_modifier"
2019-08-01 06:59:41 +0000 [info]: adding match pattern="**" type="gelf"
2019-08-01 06:59:41 +0000 [info]: adding source type="forward"
2019-08-01 06:59:41 +0000 [info]: #0 starting fluentd worker pid=7681 ppid=6 worker=0
2019-08-01 06:59:41 +0000 [info]: #0 listening port port=xxxxx bind="0.0.0.0"
2019-08-01 06:59:41 +0000 [info]: #0 fluentd worker is now running worker=0 
```     

Fluentd recieves messages from Fluentbit via forward and sends them to Graylog via gelf. Most of the time it works and we can see log messages, but from time to time Fluentd dies with this error:

```
2019-08-01 06:59:41 +0000 [warn]: #0 thread exited by unexpected error plugin=Fluent::Plugin::ForwardInput title=:event_loop error_class=Errno::ETIMEDOUT error="Connection timed out - SSL_accept"
2019-08-01 06:59:41 +0000 [error]: #0 unexpected error error_class=Errno::ETIMEDOUT error="Connection timed out - SSL_accept"
2019-08-01 06:59:41 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/server.rb:695:in `accept_nonblock'
2019-08-01 06:59:41 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/server.rb:695:in `try_handshake'
2019-08-01 06:59:41 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/server.rb:711:in `try_tls_accept'
2019-08-01 06:59:41 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/server.rb:738:in `on_readable'
2019-08-01 06:59:41 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.4/lib/cool.io/io.rb:186:in `on_readable'
2019-08-01 06:59:41 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run_once'
2019-08-01 06:59:41 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run'
2019-08-01 06:59:41 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
2019-08-01 06:59:41 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-08-01 06:59:41 +0000 [error]: #0 unexpected error error_class=Errno::ETIMEDOUT error="Connection timed out - SSL_accept" 
 ```              
**Fluentd** source config :      
```<source>
  @type forward
  port xxxxx
  bind 0.0.0.0
  <security>
    self_hostname "fluentd_hostname"
    shared_key "shared_key"
  </security>
  <transport tls>
    version                TLSv1_2
    ca_path                /etc/xxx/xxx/ca.crt.pem
    cert_path              /etc/xxx/xxx/server.crt.pem
    private_key_path       /etc/xxx/xxx/server.key.pem
    private_key_passphrase "private_key_pass"
    client_cert_auth       true
  </transport>
</source>  
```

**Comment by repeatedly** [comment]
Hmm... I'm not sure why ssl_accept raises ETIMEDOUT but thread should not be died.
Will add ETIMEDOUT to exception list.

**Comment by repeatedly** [comment]
Patch: https://github.com/fluent/fluentd/pull/2595
