### ISSUE TITLE
Defining a `send` method on a plugin causes failure on shutdown

### ISSUE THREAD

**Issue by ccheek21** [fluent/fluentd#2613]
**Describe the bug**
When a plugin defines a `send` method, it causes a failure during plugin lifecycle operations because it overrides [`Object.send`](https://ruby-doc.org/core-2.4.5/Object.html#method-i-send) which is used in [`root_agent.rb`](https://github.com/fluent/fluentd/blob/a2a164e782d919da5044cc2fd8235e7d9dc12780/lib/fluent/root_agent.rb#L280). 

This caused an issue in the New Relic output plugin ([link](https://github.com/newrelic/newrelic-fluentd-output/pull/9))

This should be fairly easily fixable by using `Object.__send__` instead of `Object.send` (as suggested by the Ruby docs).

**To Reproduce**
1) Create a plugin with a `send` method like the New Relic output plugin did that takes a non-symbol argument
2) Shut down fluentd
3) Examine logs for stacktrace

**Expected behavior**
Shutdown still works correctly

**Your Environment**

- Fluentd or td-agent version: Tested on Fluentd 1.3.3 and 1.7.1
- Operating system: CentOS 7
- Kernel version: 3.10.0-862.11.6.el7.x86_64

**Your Configuration**

```
 <ROOT>
  <source>
    @type syslog
    bind "0.0.0.0"
    port 5140
    tag "e8475b22-48cf-4ae9-a92c-854960028d31.syslog"
    protocol_type tcp
  </source>
  <match e8475b22-48cf-4ae9-a92c-854960028d31.**>
    @type record_reformer
    tag "${tag_suffix[1]}"
    <record>
      bindplane_source_name Test Newrelic Syslog
      bindplane_source_id e8475b22-48cf-4ae9-a92c-854960028d31
      bindplane_source_type syslog
    </record>
  </match>
  <match **>
    @type newrelic
    api_key "<redacted>"
  </match>
</ROOT>

```

**Your Error Log**

```
2019-09-10 10:32:26 -0400 [info]: starting fluentd-1.7.1 pid=5463 ruby="2.4.5"
2019-09-10 10:32:26 -0400 [info]: spawn command to main:  cmdline=["/opt/bluemedora/bindplane-log-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/opt/bluemedora/bindplane-log-agent/embedded/bin/fluentd", "--log", "/var/log/bindplane-log-agent/bindplane-fluentd.log", "--daemon", "/var/run/bindplane-fluentd/bindplane-fluentd.pid", "--log-rotate-age", "5", "--log-rotate-size", "10485760", "--under-supervisor"]
2019-09-10 10:32:26 -0400 [info]: gem 'fluent-plugin-newrelic' version '1.1.1'
2019-09-10 10:32:26 -0400 [info]: gem 'fluent-plugin-record-reformer' version '0.9.1'
2019-09-10 10:32:26 -0400 [info]: gem 'fluentd' version '1.7.1'
2019-09-10 10:32:26 -0400 [info]: adding match pattern="e8475b22-48cf-4ae9-a92c-854960028d31.**" type="record_reformer"
2019-09-10 10:32:26 -0400 [info]: adding match pattern="**" type="newrelic"
2019-09-10 10:32:26 -0400 [info]: adding source type="syslog"
2019-09-10 10:32:26 -0400 [warn]: #0 'protocol_type' parameter is deprecated: use transport directive
2019-09-10 10:32:26 -0400 [warn]: parameter 'concurrent_requests' in <match **>
  @type newrelic
  api_key "hd4LQ08bCP5KJy0ClJ1iZ5ZQYCS149M9"
  concurrent_requests 4
</match> is not used.
2019-09-10 10:32:26 -0400 [info]: #0 starting fluentd worker pid=5473 ppid=5468 worker=0
2019-09-10 10:32:26 -0400 [info]: #0 listening syslog socket on 0.0.0.0:5140 with tcp
2019-09-10 10:32:26 -0400 [info]: #0 fluentd worker is now running worker=0
2019-09-10 11:33:36 -0400 [info]: Received graceful stop
2019-09-10 11:33:36 -0400 [info]: Received graceful stop
2019-09-10 11:33:36 -0400 [info]: #0 fluentd worker is now stopping worker=0
2019-09-10 11:33:36 -0400 [info]: #0 shutting down fluentd worker worker=0
2019-09-10 11:33:36 -0400 [warn]: #0 unexpected error while calling stop on output plugin plugin=Fluent::Plugin::NewrelicOutput plugin_id="object:1650094" error_class=NoMethodError error="undefined method `bytesize' for :stopped?:Symbol"
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:183:in `send_request_with_body'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:121:in `exec'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1444:in `block in transport_request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1443:in `catch'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1416:in `request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:877:in `start'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1407:in `request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-newrelic-1.1.1/lib/fluent/plugin/out_newrelic.rb:128:in `send'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:243:in `block (2 levels) in shutdown'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:191:in `each'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:191:in `block in lifecycle'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:178:in `each'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:178:in `lifecycle'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:240:in `block in shutdown'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:294:in `shutdown'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/engine.rb:278:in `shutdown'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/engine.rb:247:in `run'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:808:in `run_engine'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:551:in `block in run_worker'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:733:in `main_process'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:546:in `run_worker'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/command/fluentd.rb:320:in `<top (required)>'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/bin/fluentd:8:in `<top (required)>'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/bin/fluentd:23:in `load'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/bin/fluentd:23:in `<main>'
2019-09-10 11:33:36 -0400 [info]: #0 shutting down input plugin type=:syslog plugin_id="object:15f5658"
2019-09-10 11:33:36 -0400 [info]: #0 shutting down output plugin type=:record_reformer plugin_id="object:162b500"
2019-09-10 11:33:36 -0400 [warn]: #0 unexpected error while preparing shutdown on output plugin plugin=Fluent::Plugin::NewrelicOutput plugin_id="object:1650094" error_class=NoMethodError error="undefined method `bytesize' for :before_shutdown?:Symbol"
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:183:in `send_request_with_body'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:121:in `exec'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1444:in `block in transport_request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1443:in `catch'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1416:in `request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:877:in `start'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1407:in `request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-newrelic-1.1.1/lib/fluent/plugin/out_newrelic.rb:128:in `send'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:273:in `block (3 levels) in shutdown'
2019-09-10 11:33:36 -0400 [info]: #0 shutting down output plugin type=:newrelic plugin_id="object:1650094"
2019-09-10 11:33:36 -0400 [warn]: #0 unexpected error while shutting down on output plugin plugin=Fluent::Plugin::NewrelicOutput plugin_id="object:1650094" error_class=NoMethodError error="undefined method `bytesize' for :shutdown?:Symbol"
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:183:in `send_request_with_body'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:121:in `exec'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1444:in `block in transport_request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1443:in `catch'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1416:in `request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:877:in `start'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1407:in `request'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-newrelic-1.1.1/lib/fluent/plugin/out_newrelic.rb:128:in `send'
  2019-09-10 11:33:36 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:280:in `block (3 levels) in shutdown'
2019-09-10 11:33:37 -0400 [warn]: #0 unexpected error while calling after_shutdown on output plugin plugin=Fluent::Plugin::NewrelicOutput plugin_id="object:1650094" error_class=NoMethodError error="undefined method `bytesize' for :after_shutdown?:Symbol"
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:183:in `send_request_with_body'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:121:in `exec'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1444:in `block in transport_request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1443:in `catch'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1416:in `request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:877:in `start'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1407:in `request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-newrelic-1.1.1/lib/fluent/plugin/out_newrelic.rb:128:in `send'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:243:in `block (2 levels) in shutdown'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:191:in `each'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:191:in `block in lifecycle'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:178:in `each'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:178:in `lifecycle'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:240:in `block in shutdown'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:299:in `shutdown'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/engine.rb:278:in `shutdown'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/engine.rb:247:in `run'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:808:in `run_engine'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:551:in `block in run_worker'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:733:in `main_process'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:546:in `run_worker'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/command/fluentd.rb:320:in `<top (required)>'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/bin/fluentd:8:in `<top (required)>'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/bin/fluentd:23:in `load'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/bin/fluentd:23:in `<main>'
2019-09-10 11:33:37 -0400 [warn]: #0 unexpected error while closing on output plugin plugin=Fluent::Plugin::NewrelicOutput plugin_id="object:1650094" error_class=NoMethodError error="undefined method `bytesize' for :closed?:Symbol"
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:183:in `send_request_with_body'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:121:in `exec'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1444:in `block in transport_request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1443:in `catch'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1416:in `request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:877:in `start'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1407:in `request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-newrelic-1.1.1/lib/fluent/plugin/out_newrelic.rb:128:in `send'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:283:in `block (3 levels) in shutdown'
2019-09-10 11:33:37 -0400 [warn]: #0 unexpected error while calling terminate on output plugin plugin=Fluent::Plugin::NewrelicOutput plugin_id="object:1650094" error_class=NoMethodError error="undefined method `bytesize' for :terminated?:Symbol"
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:183:in `send_request_with_body'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:121:in `exec'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1444:in `block in transport_request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1443:in `catch'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1416:in `request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:877:in `start'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/net/http.rb:1407:in `request'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-newrelic-1.1.1/lib/fluent/plugin/out_newrelic.rb:128:in `send'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:243:in `block (2 levels) in shutdown'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:191:in `each'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:191:in `block in lifecycle'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:178:in `each'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:178:in `lifecycle'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:240:in `block in shutdown'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:303:in `shutdown'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/engine.rb:278:in `shutdown'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/engine.rb:247:in `run'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:808:in `run_engine'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:551:in `block in run_worker'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:733:in `main_process'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:546:in `run_worker'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/command/fluentd.rb:320:in `<top (required)>'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/bin/fluentd:8:in `<top (required)>'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/bin/fluentd:23:in `load'
  2019-09-10 11:33:37 -0400 [warn]: #0 /opt/bluemedora/bindplane-log-agent/embedded/bin/fluentd:23:in `<main>'
2019-09-10 11:33:37 -0400 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::NewrelicOutput title=:enqueue_thread thread=#<Thread:0x0000000001f04d20@enqueue_thread@/opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2019-09-10 11:33:37 -0400 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::NewrelicOutput title=:flush_thread_0 thread=#<Thread:0x0000000001f05248@flush_thread_0@/opt/bluemedora/bindplane-log-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.1/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2019-09-10 11:33:37 -0400 [info]: Worker 0 finished with status 0
```

**Comment by ganmacs** [comment]
> This should be fairly easily fixable by using Object.__send__ instead of Object.send (as suggested by the Ruby docs).

Right. I'll fix it. thank you for your report 👍
