### ISSUE TITLE
stacktrace multiline concatenation doesn't work with fluent-plugin-detect-exceptions

### ISSUE THREAD

**Issue by y0zg** [fluent/fluentd#2675]
**Describe the bug**
Fluentd image does have `fluent-plugin-detect-exceptions` install, see below Docker image reference. 

Part of fluentd config with exception detect config:
```
      <match raw.kubernetes.**>
        @id raw.kubernetes
        @type detect_exceptions
        remove_tag_prefix raw
        message log
        stream stream
        multiline_flush_interval 5
        buffer_queue_limit 4096
        buffer_chunk_limit 1024m
        max_bytes 500000
        max_lines 1000
      </match>
```

**To Reproduce**
Deploy EFK stack:
- elasticsearch helm chart https://github.com/elastic/helm-charts/tree/master/elasticsearch
- fluentd helm chart https://github.com/kiwigrid/helm-charts/tree/master/charts/fluentd-elasticsearch
- kibana helm chart https://github.com/helm/charts/tree/master/stable/kibana

**Expected behavior**
There should be stacktrace log details in elasticsearch message from pods stdout

**Your Environment**
- Kubernetes: 
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8+IKS", GitCommit:"e92d4d66e0fbcf26d180f9564d6d310341a98481", GitTreeState:"clean", BuildDate:"2019-10-17T11:20:25Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker image: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image
- Fluentd version: `fluentd 1.6.3`
- fluent-plugin-detect-exceptions: `0.0.12`
- Operating system: `Debian GNU/Linux 9 (stretch)`
- Kernel version: `4.15.0-64-generic`

**Fluentd Configuration**

```
     <match fluent**>
        @type null
      </match>
      <match journal**>
        @type null
      </match>
      <match kubelet.**>
        @type null
      </match>
      <match kubernetes.var.log.containers.**_kube-system_**.log>
          @type null
      </match>
      <match kubernetes.var.log.containers.**_logging_**.log>
          @type null
      </match>
      <source>
        @id fluentd-containers.log
        @type tail
        @log_level info
        path /var/log/containers/*.log
        pos_file /var/log/containers.log.pos
        tag raw.kubernetes.*
        read_from_head true
        <parse>
          @type multi_format
          <pattern>
            format json
            time_key time
            time_format %Y-%m-%dT%H:%M:%S.%NZr
          </pattern>
          <pattern>
            format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
            time_format %Y-%m-%dT%H:%M:%S.%N%:z
          </pattern>
        </parse>
      </source>

      # Detect exceptions in the log output and forward them as one log entry.
      <match raw.kubernetes.**>
        @id raw.kubernetes
        @type detect_exceptions
        remove_tag_prefix raw
        message log
        stream stream
        multiline_flush_interval 5
        buffer_queue_limit 4096
        buffer_chunk_limit 1024m
        max_bytes 500000
        max_lines 1000
      </match>

    # Concatenate multi-line logs
      <filter **>
        @id filter_concat
        @type concat
        key message
        multiline_end_regexp /\n$/
        separator ""
      </filter>
  
      # Enriches records with Kubernetes metadata
      <filter kubernetes.**>
        @id filter_kubernetes_metadata
        @type kubernetes_metadata
      </filter>

 # index
      <filter kubernetes.**>
        #@id filter_parser
        @type parser
        key_name log
        reserve_data true
        reserve_time true
        <parse>
          @type grok
          grok_failure_key grokfailure
          <grok>
            pattern \x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]%{TIMESTAMP_ISO8601:java_timestamp}%{DATA:ignore1}\s\x1B\[[0-9;]*[a-zA-Z]%{DATA:java_loglevel}\e%{GREEDYDATA:ignore2}\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]\[%{DATA:java_thread}\]\s*\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]%{DATA:ignore3} \s*\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]%{DATA:java_class} %{DATA:ignore4} \x1B\[[0-9;]*[a-zA-Z] \x1B\[[0-9;]*[a-zA-Z]\:\x1B\[[0-9;]*[a-zA-Z]%{SPACE}%{GREEDYDATA:java_message}
          </grok>
        </parse>
      </filter>

      # Fixes json fields in Elasticsearch
      <filter kubernetes.**>
        @id filter_parser
        @type parser
        key_name log
        reserve_data true
        remove_key_name_field true
        <parse>
          @type multi_format
          <pattern>
            format json
          </pattern>
          <pattern>
            format none
          </pattern>
        </parse>
      </filter>

...
...
  output.conf: |-
    <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level "#{ENV['OUTPUT_LOG_LEVEL']}"
      include_tag_key true
      host "#{ENV['OUTPUT_HOST']}"
      port "#{ENV['OUTPUT_PORT']}"
      path "#{ENV['OUTPUT_PATH']}"
      scheme "#{ENV['OUTPUT_SCHEME']}"
      ssl_verify "#{ENV['OUTPUT_SSL_VERIFY']}"
      ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
      type_name "#{ENV['OUTPUT_TYPE_NAME']}"
      user "#{ENV['OUTPUT_USER']}"
      password "#{ENV['OUTPUT_PASSWORD']}"
      logstash_format true
      logstash_prefix "#{ENV['LOGSTASH_PREFIX']}"
      reconnect_on_error true
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
        queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
        overflow_action block
      </buffer>
    </match>

```

**Your Log**

**UPD**: I noted line breaker between error and stack trace could cause the issue
```
2019-10-30 12:02:36.202 ERROR 7 --- [nio-8030-exec-8] e.i.k.k.g.dataset.client.DatasetClient   : {"title":"Not Found","status":404,"detail":"There is no such dataset draft by entityId: 777"}

org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:85)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:123)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:785)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:743)
```

stacktrace  message in elasticsearh is split with many log entries:

1.
```
2019-10-30 12:02:36.202 ERROR 7 --- [nio-8030-exec-8] e.i.k.k.g.dataset.client.DatasetClient   : {"title":"Not Found","status":404,"detail":"There is no such dataset draft by entityId: 777"}
```
2.
```
	at java.base/java.lang.Thread.run(Unknown Source)
```
3.
```
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
```
4.
```
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
```

Expected single message should include stacktrace:
```
2019-10-30 12:02:36.202 ERROR 7 --- [nio-8030-exec-8] e.i.k.k.g.dataset.client.DatasetClient   : {"title":"Not Found","status":404,"detail":"There is no such dataset draft by entityId: 777"}
at java.base/java.lang.Thread.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
...
...

```

**Comment by floriankoch** [comment]
if you tke a look here https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions/blob/master/lib/fluent/plugin/exception_detector.rb , the regex does not detect this exception

I think you need to open this bug against the fluent-plugin-detect-exceptions repository
