### ISSUE TITLE
fluentd dies with unexpected error plugin=Fluent::Plugin::ForwardInput title=:event_loop error_class=Errno::ECONNREFUSED error="Connection refused - SSL_accept"

### ISSUE THREAD

**Issue by antoninblanc** [fluent/fluentd#2694]
**Describe the bug**

```
2019-11-13 11:55:19 +0100 [warn]: thread exited by unexpected error plugin=Fluent::Plugin::ForwardInput title=:event_loop error_class=Errno::ECONNREFUSED error="Connection refused - SSL_accept"
2019-11-13 11:55:19 +0100 [error]: unexpected error error_class=Errno::ECONNREFUSED error="Connection refused - SSL_accept"
  2019-11-13 11:55:19 +0100 [error]: /usr/lib64/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin_helper/server.rb:695:in `accept_nonblock'
  2019-11-13 11:55:19 +0100 [error]: /usr/lib64/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin_helper/server.rb:695:in `try_handshake'
  2019-11-13 11:55:19 +0100 [error]: /usr/lib64/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin_helper/server.rb:711:in `try_tls_accept'
  2019-11-13 11:55:19 +0100 [error]: /usr/lib64/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin_helper/server.rb:738:in `on_readable'
  2019-11-13 11:55:19 +0100 [error]: /usr/lib64/ruby/gems/2.4.0/gems/cool.io-1.5.4/lib/cool.io/io.rb:186:in `on_readable'
  2019-11-13 11:55:19 +0100 [error]: /usr/lib64/ruby/gems/2.4.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run_once'
  2019-11-13 11:55:19 +0100 [error]: /usr/lib64/ruby/gems/2.4.0/gems/cool.io-1.5.4/lib/cool.io/loop.rb:88:in `run'
  2019-11-13 11:55:19 +0100 [error]: /usr/lib64/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-11-13 11:55:19 +0100 [error]: /usr/lib64/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-11-13 11:55:19 +0100 [error]: unexpected error error_class=Errno::ECONNREFUSED error="Connection refused - SSL_accept"
```

**Your Environment**

 - fluentd 1.7.4
 - Operating system: Gentoo Linux
 - Kernel version: 4.14.55-gentoo

**Your Configuration**

```
<source>
  @type forward
  bind ::
  port 24224
  <transport tls>
    cert_path /etc/letsencrypt/live/xxxxxxxxx/fullchain.pem
    private_key_path /etc/letsencrypt/live/xxxxxxxxx/privkey.pem
    private_key_passphrase
  </transport>
  <security>
    shared_key xxxxxxxxx
    self_hostname xxxxxxxxx
  </security>
</source>
```
**Additional context**

May be similar to https://github.com/fluent/fluentd/issues/2135

**Comment by repeatedly** [comment]
Ah, `SSL_accept` returns more different error...
Here is a patch: https://github.com/fluent/fluentd/pull/2695
