### ISSUE TITLE
Gem::ConflictError: Unable to activate activesupport-5.2.3, because tzinfo-2.0.0 conflicts with tzinfo (~> 1.1) 

### ISSUE THREAD

**Issue by mokaymakci** [fluent/fluentd#2726]
Hi folks,

I am using td-agent 3.5.1 and fluent-plugin-sql 1.1.1 on Fedora 31 (kernel 5.3.14-300.fc31.x86_64). When I start the service then a gem conflict error occurs:

```
-- A start job for unit td-agent.service has begun execution.
-- 
-- The job identifier is 4773.
  fluentd[8590]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2290:in `raise_if_conflicts': Unable to activate activesupport-5.2.3, because tzinfo-2.0.0 conflicts with tzinfo (~> 1.1) (Gem::ConflictError)
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1410:in `activate'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1444:in `block in activate_dependencies'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1430:in `each'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1430:in `activate_dependencies'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1412:in `activate'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:213:in `try_activate'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-sql-1.1.1/lib/fluent/plugin/in_sql.rb:23:in `<module:Plugin>'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-sql-1.1.1/lib/fluent/plugin/in_sql.rb:21:in `<top (required)>'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/registry.rb:102:in `block in search'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/registry.rb:99:in `each'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/registry.rb:99:in `search'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/registry.rb:44:in `lookup'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin.rb:146:in `new_impl'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin.rb:100:in `new_input'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:315:in `add_source'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:160:in `block in configure'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:156:in `each'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:156:in `configure'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/engine.rb:131:in `configure'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/engine.rb:96:in `run_configure'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:812:in `run_configure'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:589:in `dry_run'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:607:in `supervise'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:512:in `run_supervisor'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/command/fluentd.rb:324:in `<top (required)>'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  fluentd[8590]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/bin/fluentd:8:in `<top (required)>'
  fluentd[8590]:         from /opt/td-agent/embedded/bin/fluentd:23:in `load'
  fluentd[8590]:         from /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
  systemd[1]: td-agent.service: Control process exited, code=exited, status=1/FAILURE

```
and my td-agent.conf is below:

```

# system settings
<system>
  log_level warn
  workers 8
</system>

## built-in TCP input
## @see http://docs.fluentd.org/articles/in_forward
<source>
  @type forward
  @id input_forward
  tag app.log
</source>

# sp logs
<worker 0>
 <source>
  @type sql
  @log_level warn

  host localhost
  database postgres_demo
  adapter postgresql
  username ***
  password ***
  tag_prefix local.postgres  
  select_interval 5s  
  select_limit 500     
  state_file /var/run/fluentd/sql_state
  <table>
   table public.sample
   tag demo.optional
   update_column id
  </table>
 </source>
</worker>

## live debugging agent
<source>
  @type debug_agent
  @id input_debug_agent
  bind 127.0.0.1
  port 24230
</source>

# parse JSON log field
<filter app.log>
 @type parser
 key_name log
 reserve_time true
 reserve_data true
 remove_key_name_field true
 <parse>
   @type json
 </parse>
</filter>

## match tag=debug.** and dump to console
<match debug.**>
  @type stdout
  @id output_stdout
</match>

## elastic search output
<match app.log local.postgres**>
  @type elasticsearch
  host localhost
  port 9200
  index fluentd
  logstash_format true
  reload_connections false
  reconnect_on_error true
  reload_on_failure true
  logstash_prefix fluentd
  <buffer>
    @type file
    path /var/log/td-agent/buffer/td
  </buffer>
</match>
```
td-agent-gem list is below:

```
activemodel (5.2.3)
activerecord (5.2.3)
activerecord-import (0.28.2)
activerecord-postgresql-adapter (0.0.1)
activesupport (5.2.3)
addressable (2.7.0)
arel (9.0.0)
aws-eventstream (1.0.3)
aws-partitions (1.230.0)
aws-sdk-core (3.72.0)
aws-sdk-kms (1.25.0)
aws-sdk-s3 (1.52.0)
aws-sdk-sqs (1.23.0)
aws-sigv4 (1.1.0)
bigdecimal (default: 1.3.2)
bundler (1.16.6)
concurrent-ruby (1.1.5)
cool.io (1.5.4)
did_you_mean (1.1.0)
dig_rb (1.0.1)
digest-crc (0.4.1)
elasticsearch (6.8.0)
elasticsearch-api (6.8.0)
elasticsearch-transport (6.8.0)
excon (0.68.0)
faraday (0.17.0)
ffi (1.11.1)
fluent-config-regexp-type (1.0.0)
fluent-logger (0.8.2)
fluent-plugin-elasticsearch (3.5.5)
fluent-plugin-kafka (0.12.1)
fluent-plugin-prometheus (1.7.0)
fluent-plugin-record-modifier (2.0.1)
fluent-plugin-rewrite-tag-filter (2.2.0)
fluent-plugin-s3 (1.2.0)
fluent-plugin-sql (1.1.1)
fluent-plugin-td (1.0.0)
fluent-plugin-td-monitoring (0.2.4)
fluent-plugin-webhdfs (1.2.4)
fluentd (1.7.4, 1.6.3)
hirb (0.7.3)
http_parser.rb (0.6.0)
httpclient (2.8.2.4)
i18n (1.6.0)
io-console (default: 0.4.6)
ipaddress (0.8.3)
jmespath (1.4.0)
json (default: 2.0.4)
ltsv (0.1.2)
mini_portile2 (2.4.0)
minitest (5.10.1)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7)
msgpack (1.2.9)
multi_json (1.14.1)
multipart-post (2.1.1)
net-telnet (0.1.1)
nokogiri (1.10.4)
ohai (6.20.0)
oj (3.7.12)
openssl (default: 2.0.9)
parallel (1.18.0)
pg (0.21.0)
power_assert (0.4.1)
prometheus-client (0.9.0)
psych (default: 2.2.2)
public_suffix (4.0.1)
quantile (0.2.1)
rake (12.3.3, 12.0.0)
rdkafka (0.7.0)
rdoc (default: 5.0.1)
ruby-kafka (0.7.10)
ruby-progressbar (1.10.1)
rubyzip (2.0.0)
serverengine (2.1.1)
sigdump (0.2.4)
strptime (0.2.3)
systemu (2.5.2)
td (0.16.5)
td-client (1.0.7)
td-logger (0.3.27)
test-unit (3.2.3)
thread_safe (0.3.6)
tzinfo (2.0.0, 1.2.5)
tzinfo-data (1.2019.3)
webhdfs (0.8.0)
xmlrpc (0.2.1)
yajl-ruby (1.4.1)
zip-zip (0.3)
```
tzinfo 2.0.0 conflictis with tzinfo 1.2.5, how could I fix this? Is there an update for this problem?

Thank you.

**Comment by ashie** [comment]
See #2634 and https://github.com/fluent/fluent-plugin-sql/issues/77

**Comment by mokaymakci** [comment]
Is the fix which is mentioned released? Because I am using the latest version.

**Comment by repeatedly** [comment]
You can Install 1.8.0 pre-release version with `--pre` option.

**Comment by repeatedly** [comment]
Released 1.8.0 with the fix.

**Comment by mokaymakci** [comment]
What about the td-agent release?

**Comment by repeatedly** [comment]
We have a plan to release new td-agent at the mid or late of Jan.

**Comment by fabrice-etanchaud** [comment]
Do you have an estimated time of arrival for the next td-agent release that will work with the sql plugin ?
Best
