### ISSUE TITLE
"parse_error!': got incomplete JSON array configuration at fluentd.conf" when time_format start with [

### ISSUE THREAD

**Issue by tiendungitd** [fluent/fluentd#2740]
I tried to parsing log from php-fpm, the log as below. 

`[2019-12-14 09:07:03] request.INFO: Matched route "user_api_loginapi_auth_login". {"route":"user_api_loginapi_auth_login","route_parameters":{"_route":"user_api_loginapi_auth_login","_controller":"App\\Homecca\\APIBundle\\Controller\\UserController::loginAction","_format":null},"request_uri":"http://identity-fpm.test.svc/identity/v1/auth/login","method":"POST"} []`

Every line of log will start with [%Y-%m-%d %H:%M:%S], so I set time_format as the configuration

```

    <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/*.log
      pos_file /var/log/fluentd-containers.log.pos
      format /^(?<time>.+): (?<msg>.*)$/
      time_format [%Y-%m-%d %H:%M:%S]
      tag raw.kubernetes.*
      read_from_head true
    </source>
    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>
```
But I got a fluentd error:
```
/var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/config/basic_parser.rb:92:in `parse_error!': got incomplete JSON array configuration at fluentd.conf line 21,9 (Fluent::ConfigParseError)
 20:   max_lines 1000
 21: </match>

     ---------^
        from /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/config/literal_parser.rb:252:in `scan_json'
        from /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/config/literal_parser.rb:61:in `parse_literal'
        from /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/config/v1_parser.rb:130:in `parse_element'
        from /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/config/v1_parser.rb:95:in `parse_element'
        from /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/config/v1_parser.rb:43:in `parse!'
        from /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/config/v1_parser.rb:33:in `parse'
        from /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/config.rb:39:in `parse'
        from /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:766:in `read_config'
        from /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:477:in `run_supervisor'
        from /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/fluentd-1.2.4/bin/fluentd:8:in `<top (required)>'
        from /usr/local/bin/fluentd:22:in `load'
        from /usr/local/bin/fluentd:22:in `<main>'

```
**Envirnoment**
'fluent-plugin-concat' version '2.3.0'
'fluent-plugin-detect-exceptions' version '0.0.11'
'fluent-plugin-elasticsearch' version '2.11.11'
fluent-plugin-kubernetes_metadata_filter' version '2.0.0'
'fluent-plugin-multi-format-parser' version '1.0.0'
'fluent-plugin-prometheus' version '1.0.1'
'fluent-plugin-systemd' version '1.0.1'
 'fluentd' version '1.2.4'

Thanks.

**Comment by ganmacs** [comment]
it's a workaround.
```
<source>
  @type tail
  path ./log/test/*.log
  format /^\[(?<time>[^\]]+)\]: (?<msg>.*)$/
  time_format %Y-%m-%d %H:%M:%S
  tag raw.kubernetes.*
  read_from_head true
</source>
```

Actual log
```
[2000-01-11 15:06:02]: "GET /test/test/test HTTP/1.1" 200 0
```

log
```
2019-12-24 18:03:51 +0900 [info]: parsing config file is succeeded path="example/debug/parser_error.conf"
2019-12-24 18:03:51 +0900 [info]: gem 'fluentd' version '1.8.0'
2019-12-24 18:03:51 +0900 [warn]: 'pos_file PATH' parameter is not set to a 'tail' source.
2019-12-24 18:03:51 +0900 [warn]: this parameter is highly recommended to save the position to resume tailing.
2019-12-24 18:03:51 +0900 [info]: using configuration file: <ROOT>
  <source>
    @type tail
    path "./log/test/*.log"
    format /^\[(?<time>[^\]]+)\]: (?<msg>.*)$/
    time_format %Y-%m-%d %H:%M:%S
    tag "raw.kubernetes.*"
    read_from_head true
    <parse>
      time_format %Y-%m-%d %H:%M:%S
      @type regexp
      expression ^\[(?<time>[^\]]+)\]: (?<msg>.*)$
    </parse>
  </source>
  <match raw.kubernetes.**>
    @type stdout
  </match>
</ROOT>
2019-12-24 18:03:51 +0900 [info]: starting fluentd-1.8.0 pid=63922 ruby="2.6.5"
2019-12-24 18:03:51 +0900 [info]: spawn command to main:  cmdline=["/.rbenv/versions/2.6.5/bin/ruby", "-Eascii-8bit:ascii-8bit", "-rbundler/setup", "/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/fluentd", "-c", "example/debug/parser_error.conf", "--under-supervisor"]
2019-12-24 18:03:52 +0900 [info]: adding match pattern="raw.kubernetes.**" type="stdout"
2019-12-24 18:03:52 +0900 [info]: adding source type="tail"
2019-12-24 18:03:52 +0900 [warn]: #0 'pos_file PATH' parameter is not set to a 'tail' source.
2019-12-24 18:03:52 +0900 [warn]: #0 this parameter is highly recommended to save the position to resume tailing.
2019-12-24 18:03:52 +0900 [info]: #0 starting fluentd worker pid=63936 ppid=63922 worker=0
2019-12-24 18:03:52 +0900 [info]: #0 following tail of ./log/test/test.log
2000-01-11 15:06:02.000000000 +0900 raw.kubernetes.log.test.test.log: {"msg":"\"GET /test/test/test HTTP/1.1\" 200 0"}
2019-12-24 18:03:52 +0900 [info]: #0 fluentd worker is now running worker=0
^C2019-12-24 18:03:56 +0900 [info]: Received graceful stop
2019-12-24 18:03:57 +0900 [info]: #0 fluentd worker is now stopping worker=0
2019-12-24 18:03:57 +0900 [info]: #0 shutting down fluentd worker worker=0
2019-12-24 18:03:57 +0900 [info]: #0 shutting down input plugin type=:tail plugin_id="object:3fd6e555c7a0"
2019-12-24 18:03:57 +0900 [info]: #0 shutting down output plugin type=:stdout plugin_id="object:3fd6e50618f4"
2019-12-24 18:03:58 +0900 [info]: Worker 0 finished with status 0
```

BTW read https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md
