### ISSUE TITLE
Address in use - bind(2) for 0.0.0.0:24224

### ISSUE THREAD

**Issue by loposk** [fluent/fluentd#2788]
[Documentation says](https://docs.fluentd.org/deployment/multi-process-workers#input-plugin):
Server plugin helper based plugin can share port between workers. For example, forward input plugin doesn't need multiple ports on multi process workers. forward input's port is shared between workers.

With this configuration
/fluentd/etc/fluent.conf:
```
@include /fluentd/etc/configuration/filter/*.conf
@include /fluentd/etc/configuration/match/*.conf
<system>
  workers 6
  log_level warn
</system>
<source>
  @type monitor_agent
  bind 0.0.0.0
  port 24220
</source>
<source>
  @type forward
  port 24224
  bind 0.0.0.0
  source_hostname_key hostname
</source>
<source>
  @type http
  port 9880
  bind 0.0.0.0
  body_size_limit 32m
  keepalive_timeout 10s
  add_remote_addr
  <parse>
    @type regexp
    expression /(?<message>.*)/
  </parse>
</source>
<source>
  @type syslog
  port 5140
  bind 0.0.0.0
  tag syslog
  message_length_limit 4096
  source_hostname_key hostname
</source>
```
I get this error
```
2020-01-22 10:53:37 +0300 [error]: #4 unexpected error error_class=Errno::EADDRINUSE error="Address in use - bind(2) for 0.0.0.0:24224"
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/2.5.0/socket.rb:201:in `bind'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/2.5.0/socket.rb:201:in `listen'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/2.5.0/socket.rb:764:in `block in tcp_server_sockets'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/2.5.0/socket.rb:227:in `each'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/2.5.0/socket.rb:227:in `foreach'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/2.5.0/socket.rb:762:in `tcp_server_sockets'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/2.5.0/webrick/utils.rb:65:in `create_listeners'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/2.5.0/webrick/server.rb:127:in `listen'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/2.5.0/webrick/server.rb:108:in `initialize'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/2.5.0/webrick/httpserver.rb:47:in `initialize'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/plugin_helper/http_server/compat/server.rb:31:in `new'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/plugin_helper/http_server/compat/server.rb:31:in `initialize'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/plugin_helper/http_server.rb:47:in `new'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/plugin_helper/http_server.rb:47:in `create_http_server'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/plugin/in_monitor_agent.rb:211:in `start'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/root_agent.rb:203:in `block in start'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/root_agent.rb:191:in `each'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/root_agent.rb:191:in `block in lifecycle'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/root_agent.rb:178:in `each'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/root_agent.rb:178:in `lifecycle'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/root_agent.rb:202:in `start'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/engine.rb:274:in `start'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/engine.rb:219:in `run'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/supervisor.rb:808:in `run_engine'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/supervisor.rb:551:in `block in run_worker'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/supervisor.rb:733:in `main_process'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/supervisor.rb:546:in `run_worker'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/lib/fluent/command/fluentd.rb:320:in `<top (required)>'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.6.2/bin/fluentd:8:in `<top (required)>'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/bin/fluentd:23:in `load'
  2020-01-22 10:53:37 +0300 [error]: #4 /usr/bin/fluentd:23:in `<main>'
2020-01-22 10:53:37 +0300 [error]: #4 unexpected error error_class=Errno::EADDRINUSE error="Address in use - bind(2) for 0.0.0.0:24224"
  2020-01-22 10:53:37 +0300 [error]: #4 suppressed same stacktrace
```

But this configuration works fine:
```
@include /fluentd/etc/configuration/filter/*.conf
@include /fluentd/etc/configuration/match/*.conf
<system>
  workers 6
  log_level warn
</system>
<worker 0-1>
  <source>
    @type monitor_agent
    bind 0.0.0.0
    port 24220
  </source>
  <source>
    @type forward
    port 24224
    bind 0.0.0.0
    source_hostname_key hostname
  </source>
  <source>
    @type http
    port 9880
    bind 0.0.0.0
    body_size_limit 32m
    keepalive_timeout 10s
    add_remote_addr
    <parse>
      @type regexp
      expression /(?<message>.*)/
    </parse>
  </source>
  <source>
    @type syslog
    port 5140
    bind 0.0.0.0
    tag syslog
    message_length_limit 4096
    source_hostname_key hostname
  </source>
</worker>
```

Information from host:
```
netstat -nlpt | grep 24224
tcp6       0      0 :::24224                :::*                    LISTEN      73663/docker-proxy

ps aux | grep 73663
root      73663  0.0  0.1 307072  2112 ?        Sl   09:54   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 24224 -container-ip 172.19.0.2 -container-port 24224
```
Information from Fluentd container
```
netstat -nlpt | grep 24224
tcp      129      0 0.0.0.0:24224           0.0.0.0:*               LISTEN      6/ruby

ps aux | grep " 6 "
    6 fluent    0:07 {fluentd} /usr/bin/ruby /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins
 7314 fluent    0:00 grep  6 

ps 
PID   USER     TIME  COMMAND
    1 fluent    0:00 tini -- /bin/entrypoint.sh fluentd
    6 fluent    0:07 {fluentd} /usr/bin/ruby /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins
   16 fluent    1h16 /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins --under-supervis
   17 fluent    1h20 /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins --under-supervis
   18 fluent    1h17 /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins --under-supervis
   19 fluent    1h19 /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins --under-supervis
   25 fluent    1h17 /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins --under-supervis
 2154 fluent    0:00 sh
 8803 fluent    0:00 /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins --under-supervis
 8805 fluent    0:00 ps
```

**Comment by repeatedly** [comment]
See https://docs.fluentd.org/input/monitor_agent#multi-process-environment

**Comment by loposk** [comment]
Thanks =)
