### ISSUE TITLE
configure: undefined method `dry_run_mode'

### ISSUE THREAD

**Issue by tangjiaxing669** [fluent/fluentd#2804]
This is my info:

```
[root@Jasontom ~]# td-agent --version
td-agent 1.9.0

[root@Jasontom ~]# td-agent-gem --version
WARN: Unresolved specs during Gem::Specification.reset:
      tzinfo (< 3.0, >= 1.0, >= 1.0.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
2.6.14

[root@Jasontom ~]# cat /etc/td-agent/td-agent.conf
<source>
  @type tail
  @label @accesslog_nginx
  <parse>
    @type nginx
  </parse>
  path /var/log/nginx/access.log
  pos_path /var/log/nginx/access.log.pos
  tag accesslog.nginx.parse
</source>

<match **>
  @type elasticsearch
  host 172.16.130.143
  port 9200
  flush_interval 10s
  # index_name fluentd.${tag}.%Y-%m-%d
  logstash_format true
  logstash_prefix ${tag}
</match>

<label @accesslog_nginx>
  <match **>
    @type elasticsearch
    @id accesslog_nginx
    @log_level info
    host 172.16.130.143
    port 9200
    flush_interval 10s
    logstash_format true
    logstash_prefix ${tag}
  </match>
</label>
```

When I start fluentd, I get the following exception:

```
[root@Jasontom ~]# td-agent --dry-run -c /etc/td-agent/td-agent.conf -vv
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-elasticsearch' version '3.5.5'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-elasticsearch' version '2.12.5'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-kafka' version '0.12.1'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-mongo' version '1.3.0'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-prometheus' version '1.7.0'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-record-modifier' version '2.0.1'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-s3' version '1.2.0'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-td' version '1.0.0'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-webhdfs' version '1.2.4'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluentd' version '1.9.0'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: gem 'fluentd' version '1.7.4'
2020-01-29 21:53:45 +0800 [info]: fluent/log.rb:322:info: starting fluentd-1.9.0 as dry run mode ruby="2.4.9"
2020-01-29 21:53:45 +0800 [trace]: fluent/log.rb:281:trace: registered output plugin 'elasticsearch'
2020-01-29 21:53:45 +0800 [info]: [accesslog_nginx] 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
2020-01-29 21:53:45 +0800 [trace]: fluent/log.rb:281:trace: registered buffer plugin 'memory'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-3.5.5/lib/fluent/plugin/out_elasticsearch.rb:190:in `configure': undefined method `dry_run_mode' for #<Fluent::EngineClass:0x000000000312ee60> (NoMethodError)
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/plugin.rb:173:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/agent.rb:132:in `add_match'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/agent.rb:74:in `block in configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/agent.rb:64:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/agent.rb:64:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/label.rb:31:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/root_agent.rb:143:in `block in configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/root_agent.rb:143:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/root_agent.rb:143:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/engine.rb:105:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/engine.rb:80:in `run_configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/supervisor.rb:541:in `run_supervisor'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/lib/fluent/command/fluentd.rb:330:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.0/bin/fluentd:8:in `<top (required)>'
	from /opt/td-agent/embedded/bin/fluentd:23:in `load'
	from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
	from /usr/sbin/td-agent:7:in `load'
	from /usr/sbin/td-agent:7:in `<main>'
```

**Comment by repeatedly** [comment]
Your elasticsearch plugin is old. Please udpate it.

**Comment by tangjiaxing669** [comment]
@repeatedly Thanks. solved this problem.

**Comment by fdbatista** [comment]
@repeatedly Sorry, i am having the same issue, how can i update the plugin? I am using the latest elasticsearch docker image, but i don't know what you mean.
