### ISSUE TITLE
in_tail Multiline mode does not work

### ISSUE THREAD

**Issue by yingjianjian** [fluent/fluentd#2844]
Multi-line mode keeps getting stuck when there are many lines
My configuration：
`    

     <source>
     @type tail
     @id isc-algo-engine-service
     format multiline
     multiline_flush_interval 3s
     format_firstline /\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(,|.)\d{3}/
     format1 /^(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(,|.)\d{3}) (?<hostname>.*) (?<appname>\[.*\]) (?<loglevel>([A-a]lert|ALERT|[D|d]ebug|DEBUG|[N|n]otice|NOTICE|[I|i]nfo|INFO|[W|w]arn?(?:ing)?|WARN?(?:ING)?|ERR?(?:OR)?|[C|c]rit?(?:ical)?|CRIT?(?:ICAL)?|[F|f]atal|FATAL|[S|s]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)) (?<class>.* .* .*) (?<process>[\s\S]*) (?<thread>[\s\S]*) : (?<message>.*)/
     path /srv/isc-algo-engine-service/logs/out-test.log
     pos_file /var/log/python2.posg
     tag java-online.*
     time_format %Y-%m-%dT%H:%M:%S.%NZ
     refresh_interval 120
    </source>
`

Run in a single line：
stout：
`

2020-02-26T13:53:35+00:00       java-online.srv.isc-algo-engine-service.logs.out-test.log       {"timestamp":"2020-02-26 12:23:13,910","hostname":"isc-algo-engine-service-7896997cdc-bvnhb","appname":"[isc-algo-engine-service]","loglevel":"ERROR","class":"utility wrapper 127","process":"[31]","thread":"[140659836589824]","message":"Traceback (most r2020年 02月 26日 星期三 21:53:32 CST"}`

In multiple lines, you need to wait for a long time, or even stop working：

ttt.log:
`

2020-02-26 12:23:13,897 isc-algo-engine-service-7896997cdc-bvnhb [isc-algo-engine-service] ERROR utility wrapper 127 [31] [140659836589824] : Traceback (most r
ecent call last)
java.lang.NullPointerException: null
        at com.isyscore.os.isclink.data.save.run.emq.EmqHandleRunnable.tagOldUpload(EmqHandleRunnable.java:70)
        at com.isyscore.os.isclink.data.save.run.emq.EmqHandleRunnable.run(EmqHandleRunnable.java:47)
        at com.isyscore.os.isclink.data.save.run.emq.EmqHandleRunnable$$FastClassBySpringCGLIB$$29f375f2.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
        at com.isyscore.boot.web.monitor.MonitorAspect.doAroundService(MonitorAspect.java:30)
        at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
~
`
`
[root@isys-dev logs]# cat ttt.log >> out-test.log ;date
2020年 02月 26日 星期三 22:05:19 CST
`

After 11 minutes  stdout:

`2020-02-26T14:16:09+00:00       java-online.srv.isc-algo-engine-service.logs.out-test.log       {"timestamp":"2020-02-26 12:23:13,897","hostname":"isc-algo-engine-service-7896997cdc-bvnhb","appname":"[isc-algo-engine-service]","loglevel":"ERROR","class":"utility wrapper 127","process":"[31]","thread":"[140659836589824]","message":"Traceback (most r\necent call last)\njava.lang.NullPointerException: null\n        at com.isyscore.os.isclink.data.save.run.emq.EmqHandleRunnable.tagOldUpload(EmqHandleRunnable.java:70)\n        at com.isyscore.os.isclink.data.save.run.emq.EmqHandleRunnable.run(EmqHandleRunnable.java:47)\n        at com.isyscore.os.isclink.data.save.run.emq.EmqHandleRunnable$$FastClassBySpringCGLIB$$29f375f2.invoke(<generated>)\n        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\n        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)\n        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n        at com.isyscore.boot.web.monitor.MonitorAspect.doAroundService(MonitorAspect.java:30)\n        at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)\n        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)"}
`

Great Gods, please help
Thank you！

**Comment by ganmacs** [comment]
Read this. https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md
and follow the issue tempalte.
