### ISSUE TITLE
flush_at_shutdown not behaving as expected for memory buffers

### ISSUE THREAD

**Issue by buch11** [fluent/fluentd#2845]
**Describe the bug**
I am using fluentd with beloe pipeline config:
```
   <source>
      @type http
      port 8888
      bind 127.0.0.1
      body_size_limit 2m
      keepalive_timeout 10s
    </source>
    <match some-logs>
      @type copy
      <store>
        @type stdout
        <format>
        output_type json
        </format>
      </store>
      <store ignore_error>
        @type http
        <buffer>
          flush_interval 1s
          overflow_action drop_oldest_chunk
          chunk_limit_size 2mb
          flush_thread_count 10
         flush_at_shutdown true
        </buffer>
        endpoint https://output:6065/
        <format>
        @type json
        </format>
      </store>
    </match>

```

Usecase:
If I shutdown fluentd when its retrying to post one of the messages to "endpoint", it simply shutsdown without any error or anything else reported and everything that was buffered in memory is lost. Please find below logs indicating the same : 

```
2020-02-26 05:50:33 +0000 [debug]: #0 Post data to https://output:6065/ with chunk(59f742d29f5b8a5b173a64a6c99853e1)
2020-02-26 05:50:39 +0000 [debug]: #0 taking back chunk for errors. chunk="59f742d29f5b8a5b173a64a6c99853e1"
2020-02-26 05:50:39 +0000 [warn]: #0 failed to flush the buffer. retry_time=4 next_retry_seconds=2020-02-26 05:50:47 +0000 chunk="59f742d29f5b8a5b173a64a6c99853e1" error_class=SocketError error="Failed to open TCP connection to logstash:6065 (getaddrinfo: Temporary failure in name resolution)"
  2020-02-26 05:50:39 +0000 [warn]: #0 /usr/local/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect'
  2020-02-26 05:50:39 +0000 [warn]: #0 /usr/local/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
  2020-02-26 05:50:39 +0000 [warn]: #0 /usr/local/lib/ruby/2.6.0/timeout.rb:76:in `timeout'
  2020-02-26 05:50:39 +0000 [warn]: #0 /usr/local/lib/ruby/2.6.0/net/http.rb:945:in `connect'
  2020-02-26 05:50:39 +0000 [warn]: #0 /usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
  2020-02-26 05:50:39 +0000 [warn]: #0 /usr/local/lib/ruby/2.6.0/net/http.rb:919:in `start'
  2020-02-26 05:50:39 +0000 [warn]: #0 /usr/local/lib/ruby/2.6.0/net/http.rb:605:in `start'
  2020-02-26 05:50:39 +0000 [warn]: #0 /fluentd/plugins/out_http.rb:209:in `send_request'
  2020-02-26 05:50:39 +0000 [warn]: #0 /fluentd/plugins/out_http.rb:117:in `write'
  2020-02-26 05:50:39 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2020-02-26 05:50:39 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
  2020-02-26 05:50:39 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
  2020-02-26 05:50:39 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-02-26 05:50:41 +0000 [info]: fluent/log.rb:322:info: Received graceful stop
2020-02-26 05:50:41 +0000 [debug]: #0 fluentd main process get SIGTERM
2020-02-26 05:50:41 +0000 [debug]: #0 getting start to shutdown main process
2020-02-26 05:50:42 +0000 [info]: #0 fluentd worker is now stopping worker=0
2020-02-26 05:50:42 +0000 [info]: #0 shutting down fluentd worker worker=0
2020-02-26 05:50:42 +0000 [debug]: #0 calling stop on input plugin type=:http plugin_id="object:3feef6550d14"
2020-02-26 05:50:42 +0000 [debug]: #0 calling stop on output plugin type=:copy plugin_id="object:3feef71f775c"
2020-02-26 05:50:42 +0000 [debug]: #0 calling stop on output plugin type=:stdout plugin_id="object:3feef657a948"
2020-02-26 05:50:42 +0000 [debug]: #0 calling stop on output plugin type=:http plugin_id="object:3feef51095b8"
2020-02-26 05:50:42 +0000 [debug]: #0 preparing shutdown input plugin type=:http plugin_id="object:3feef6550d14"
2020-02-26 05:50:42 +0000 [info]: #0 shutting down input plugin type=:http plugin_id="object:3feef6550d14"
2020-02-26 05:50:42 +0000 [debug]: #0 preparing shutdown output plugin type=:copy plugin_id="object:3feef71f775c"
2020-02-26 05:50:42 +0000 [info]: #0 shutting down output plugin type=:copy plugin_id="object:3feef71f775c"
2020-02-26 05:50:42 +0000 [debug]: #0 preparing shutdown output plugin type=:http plugin_id="object:3feef51095b8"
2020-02-26 05:50:42 +0000 [debug]: #0 preparing shutdown output plugin type=:stdout plugin_id="object:3feef657a948"
2020-02-26 05:50:42 +0000 [info]: #0 shutting down output plugin type=:stdout plugin_id="object:3feef657a948"
2020-02-26 05:50:42 +0000 [info]: #0 shutting down output plugin type=:http plugin_id="object:3feef51095b8"
2020-02-26 05:50:42 +0000 [debug]: #0 calling after_shutdown on input plugin type=:http plugin_id="object:3feef6550d14"
2020-02-26 05:50:42 +0000 [debug]: #0 calling after_shutdown on output plugin type=:copy plugin_id="object:3feef71f775c"
2020-02-26 05:50:42 +0000 [debug]: #0 calling after_shutdown on output plugin type=:stdout plugin_id="object:3feef657a948"
2020-02-26 05:50:42 +0000 [debug]: #0 calling after_shutdown on output plugin type=:http plugin_id="object:3feef51095b8"
2020-02-26 05:50:42 +0000 [debug]: #0 closing input plugin type=:http plugin_id="object:3feef6550d14"
2020-02-26 05:50:42 +0000 [debug]: #0 closing output plugin type=:copy plugin_id="object:3feef71f775c"
2020-02-26 05:50:42 +0000 [debug]: #0 closing output plugin type=:stdout plugin_id="object:3feef657a948"
2020-02-26 05:50:42 +0000 [debug]: #0 closing output plugin type=:http plugin_id="object:3feef51095b8"
2020-02-26 05:50:42 +0000 [debug]: #0 closing buffer instance=70295546411220
2020-02-26 05:50:42 +0000 [debug]: #0 calling terminate on input plugin type=:http plugin_id="object:3feef6550d14"
2020-02-26 05:50:42 +0000 [debug]: #0 calling terminate on output plugin type=:copy plugin_id="object:3feef71f775c"
2020-02-26 05:50:42 +0000 [debug]: #0 calling terminate on output plugin type=:stdout plugin_id="object:3feef657a948"
2020-02-26 05:50:42 +0000 [debug]: #0 calling terminate on output plugin type=:http plugin_id="object:3feef51095b8"
2020-02-26 05:50:42 +0000 [info]: fluent/log.rb:322:info: Worker 0 finished with status 0
```

============================================================

**Expected behavior**
Fluentd must try to flush before it shutsdown in case of graceful shutdowns. 

**My Environment**

- Fluentd or td-agent version: fluentd 1.4.2
- Docker Image : fluentd:v1.4.2-debian-2.0

**Comment by buch11** [comment]
I am not sure if I am looking at the right place or not but ...

Should this https://github.com/fluent/fluentd/blob/c152369171784fed429dffab249b5d1ec34bcc71/lib/fluent/supervisor.rb#L766

be called here?? : 
https://github.com/fluent/fluentd/blob/c152369171784fed429dffab249b5d1ec34bcc71/lib/fluent/supervisor.rb#L725


Thoughts?

**Comment by ganmacs** [comment]
No. it's no related to this.
Output#force_flush flushes buffering data in Output#before_shutdown. 

https://github.com/fluent/fluentd/blob/e67718f3332a848cda1f4ab0f78aaf3694a638d9/lib/fluent/plugin/output.rb#L494

According to your error log, HTTP output is retrying because of the error. 
fluentd doesn't flush all buffer if the output is retrying.

https://github.com/fluent/fluentd/blob/e67718f3332a848cda1f4ab0f78aaf3694a638d9/lib/fluent/plugin/output.rb#L809

If you don't want to get data loss, we recommend you to use file buffer or file single buffer plugin insead of memory plugin.

**Comment by buch11** [comment]
@ganmacs - thanks for prompt response! 
Logically, should it not retry once again before shutting down? In my case, my target endpoint was available when I shutdown fluentd - if fluentd had retried just once, buffer flush would have succeeded. 

We are running this setup in a kubernetes cluster and for some specific reasons, we are trying to stay away from disk buffers. 

Is there any other alternative to force buffer flush ( for memory buffers ) for in memory buffers?

**Comment by repeatedly** [comment]
> if fluentd had retried just once, buffer flush would have succeeded.

From the fluentd side, fluentd/plugin is hard to know this point because flush threads are retrying and holding queuing chunks.
To support re-flush in shutdown phase, adding option like `wait_and_clear_retries` is one way.
Of course, this may cause long time shutdown.

**Comment by buch11** [comment]
@repeatedly  - well, its a tradeoff. If you want to achieve something on the lines of guaranteed delivery, you have to sacrifice faster shutdowns. In my case, the data flowing this pipeline is sensitive and we are not allowed to lose any messages at all. But its ok for me to wait for a little longer ( because I know that my upstream wont stay down for any longer than x minutes)

So, its a +1 for wait_and_clear_retries_at_shutdown from my side.

**Comment by AlbinoFreitas** [comment]
Hey, @buch11. I'm facing the same problem but I didn't find this option (wait_and_clear_retries_at_shutdown) on fluentd's documentation. Is it available for use?
