### ISSUE TITLE
With encryption, Fluentd complains incoming chunk is broken

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluentd#2865]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

Fluentd does not communicate with TLS transport.

**To Reproduce**
* Generate self signed certificate

```
$ bundle exec fluent-ca-cert pem fluentd
```

* Create server and client fluentd configurations
* Connect Fluentds with TLS
* Boom :boom:

**Expected behavior**

Fluentd can handle TLS transport even if using self-signed certificate.

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
  - revision: 47be96e3a98fa247b59e479f7c62bfeff1a9ec55
- Operating system: `cat /etc/os-release`
  - macOS 10.15.3 
  - [Update] Ubuntu bionic 18.04.4 LTS"
- Kernel version: `uname -r`
  - macOS: 19.3.0
  - Ubuntu Bionic: 5.3.0-40-lowlatency

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

#### Server

```aconf
<source>
  @type forward
  port 24224
  <transport>
    cert_path ./pem/ca_cert.pem
    private_key_path ./pem/ca_key.pem
    private_key_passphrase fluentd
  </transport>
</source>
<match xxx.**>
  @type stdout
</match>
```

#### Client

```aconf
<source>
  @type forward
  port 24225
</source>
<filter xxx.**>
  @type stdout
</filter>
<match xxx.**>
  @type forward
  transport tls
  tls_cert_path ./pem/ca_cert.pem
  tls_verify_hostname false
  tls_allow_self_signed_cert true
  <server>
    host localhost
    port 24224
  </server>
</match>
```

**Your Error Log**

```
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=22
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=3
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=1
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=2
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=0
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=1
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=0
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=1
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=-4
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=3
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=3
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=46
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=-28
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=43
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=11
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=38
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=74
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=125
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg="\x90\xC7\n\xCA\xFC\x99j\u03386\xD7S\u0019\vpo\x8B\xB4t\x86\xB9\x8F"
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=68
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=9
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=0
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=0
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg="\u0328\u032A\xC0\xAF\xC0\xAD\xC0"
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg="\xC0\x9F\xC0"
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=93
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=97
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=87
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=83
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=43
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=47
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=0
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg="\u0000\x9E"
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg="\xC0\xAC\xC0\xA2\xC0\x9E\xC0\\\xC0`\xC0V\xC0R"
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=36
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=40
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=0
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=107
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=0
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=106
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=115
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=119
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=0
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=""
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=true
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=35
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=39
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=0
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=103
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=0
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=64
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=114
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=118
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=0
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg="\u0000\xBD\xC0\n\xC0\u0014\u00009\u00008\u0000\x88\u0000\x87\xC0\t\xC0\u0013\u00003\u00002\u0000\x9A\u0000\x99\u0000E\u0000D"
2020-03-06 18:46:33 +0900 [warn]: #0 incoming chunk is broken: host="192.168.11.5" msg=0
2020-03-06 18:46:33 +0900 [error]: #0 unexpected error on reading data host="192.168.11.5" port=61805 error_class=TypeError error="no implicit conversion of String into Integer"
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:311:in `[]'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:311:in `on_message'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:226:in `block in handle_connection'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:263:in `block (3 levels) in read_messages'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:262:in `feed_each'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:262:in `block (2 levels) in read_messages'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:271:in `block in read_messages'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin_helper/server.rb:611:in `on_read_without_connection'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/vendor/bundle/ruby/2.7.0/gems/cool.io-1.6.0/lib/cool.io/io.rb:123:in `on_readable'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/vendor/bundle/ruby/2.7.0/gems/cool.io-1.6.0/lib/cool.io/io.rb:186:in `on_readable'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/vendor/bundle/ruby/2.7.0/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/vendor/bundle/ruby/2.7.0/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2020-03-06 18:46:33 +0900 [error]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Additional context**

Am I missing something to connect with TLS?

With insecure TLS, I also got error:

```aconf
  <system>
    workers 2
  </system>
  <worker 0>
    <source>
      @type forward
      port 30000
      <transport>
        insecure true
      </transport>
    </source>
    <match xxx.**>
      @type stdout
      @id out_stdout
    </match>
  </worker>
  <worker 1>
    <source>
      @type forward
      port 24224
    </source>
    <match xxx.**>
      @type forward
      transport tls
      tls_insecure_mode true
      require_ack_response false
      <buffer>
        @type "memory"
        flush_interval 1s
      </buffer>
      <service>
        host "127.0.0.1"
        port 30000
      </service>
    </match>
```

```
2020-03-09 14:43:28 +0900 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=22
2020-03-09 14:43:28 +0900 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=3
2020-03-09 14:43:28 +0900 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=1
2020-03-09 14:43:28 +0900 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=0
2020-03-09 14:43:28 +0900 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg="\u0001\u0000\u0000\xB9\u0003\u0003\xBAZ\xAB\xAC\xE6\xBE\xEE\u0015\u0001P\xD8MU\x99exx\xD3dYF\xCF\xDE"
2020-03-09 14:43:28 +0900 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=-32
2020-03-09 14:43:28 +0900 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=54
2020-03-09 14:43:28 +0900 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=-14
2020-03-09 14:43:28 +0900 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=64
2020-03-09 14:43:28 +0900 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=94
2020-03-09 14:43:28 +0900 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=52
2020-03-09 14:43:28 +0900 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=95
2020-03-09 14:43:28 +0900 [warn]: #0 emit transaction failed: error_class=TypeError error="no implicit conversion of Integer into String" location="/Users/cosmo/GitHub/fluentd/lib/fluent/match.rb:128:in `match'" tag=48
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/match.rb:128:in `match'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/match.rb:128:in `match'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/event_router.rb:68:in `match?'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/event_router.rb:245:in `block in find'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/event_router.rb:244:in `each'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/event_router.rb:244:in `each_with_index'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/event_router.rb:244:in `find'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/event_router.rb:112:in `block in match'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/event_router.rb:130:in `get'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/event_router.rb:111:in `match'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/event_router.rb:97:in `emit_stream'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/event_router.rb:88:in `emit'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:355:in `on_message'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:226:in `block in handle_connection'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:263:in `block (3 levels) in read_messages'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:262:in `feed_each'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:262:in `block (2 levels) in read_messages'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin/in_forward.rb:271:in `block in read_messages'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin_helper/server.rb:611:in `on_read_without_connection'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/vendor/bundle/ruby/2.6.0/gems/cool.io-1.6.0/lib/cool.io/io.rb:123:in `on_readable'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/vendor/bundle/ruby/2.6.0/gems/cool.io-1.6.0/lib/cool.io/io.rb:186:in `on_readable'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/vendor/bundle/ruby/2.6.0/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/vendor/bundle/ruby/2.6.0/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2020-03-09 14:43:28 +0900 [warn]: #0 /Users/cosmo/GitHub/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-03-09 14:43:28 +0900 [error]: #0 unexpected error on reading data host="127.0.0.1" port=58979 error_class=TypeError error="no implicit conversion of Integer into String"
  2020-03-09 14:43:28 +0900 [error]: #0 suppressed same stacktrace
```

**Comment by fil-monterey** [comment]
The cert file on server and client may be mismatching. 

Another possible cause is the 2 different receiver/sender configs , one encrypting the stream and the other sending unencrypted.

**Comment by ganmacs** [comment]
I figured out it's the error that occurs in macOS. I checked it in macOS(10.15.3 build ver: 19D76)  and ubuntu:bionic([rubylang/ruby](https://hub.docker.com/r/rubylang/ruby)) docker image.
The reason why the error occurs is that getaddrinfo(3) returns the address whose family is ipv6 before the address whose family is ipv4.
Therefore, This error always occurs when running fluentd in macOS and `host` value in server section of out_forward is `localhost`.

out_forward tries to connect `::1` instead of `127.0.0.1` because the following code uses first value(which is ipv6 address) as the hostname.

https://github.com/fluent/fluentd/blob/8f2ea4bb26e5735b36acf5f6dc0fa5796ce4c4f9/lib/fluent/plugin/out_forward.rb#L731


```sh
# ubuntu:bionic
$ docker run --rm -it rubylang/ruby:2.6.5-bionic ruby -e 'require "socket"; p Socket.getaddrinfo("localhost", 80, nil, Socket::SOCK_STREAM)'
[["AF_INET", 80, "127.0.0.1", "127.0.0.1", 2, 1, 6], ["AF_INET6", 80, "::1", "::1", 10, 1, 6]]
$ docker run --rm -it rubylang/ruby:2.7.0-bionic ruby -e 'require "socket"; p Socket.getaddrinfo("localhost", 80, nil, Socket::SOCK_STREAM)'
[["AF_INET", 80, "127.0.0.1", "127.0.0.1", 2, 1, 6], ["AF_INET6", 80, "::1", "::1", 10, 1, 6]]

# macos:catalina
$ rbenv local 2.6.5; bundle exec ruby -e 'require "socket"; p Socket.getaddrinfo("localhost", 80, nil, Socket::SOCK_STREAM)'
[["AF_INET6", 80, "::1", "::1", 30, 1, 6], ["AF_INET", 80, "127.0.0.1", "127.0.0.1", 2, 1, 6]]
$ rbenv local 2.7.0; bundle exec ruby -e 'require "socket"; p Socket.getaddrinfo("localhost", 80, nil, Socket::SOCK_STREAM)'
[["AF_INET6", 80, "::1", "::1", 30, 1, 6], ["AF_INET", 80, "127.0.0.1", "127.0.0.1", 2, 1, 6]]
```
Code for checking the value  getaddrinfo(3) returns.

```c
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <netinet/in.h>
#include <sys/socket.h>

#ifndef   NI_MAXHOST
#define   NI_MAXHOST 1025
#endif

int main(void)
{
  char *hostname = "localhost";
  char *service = "http";
  struct addrinfo hints, *res0, *res;
  int err;

  memset(&hints, 0, sizeof(hints));
  hints.ai_socktype = SOCK_STREAM;
  hints.ai_family = PF_UNSPEC;

  if ((err = getaddrinfo(hostname, service, &hints, &res0)) != 0) {
    printf("error %d\n", err);
    return 1;
  }

  for (res=res0; res!=NULL; res=res->ai_next) {
    if(res->ai_family == AF_INET) {
      puts("ipv4");
    } else if(res->ai_family == AF_INET6) {
      puts("ipv6");
    }
  }

  return 0;
}
```

Minimal reproducible example

server
```
<source>
  @type forward
</source>

<match test>
  @type stdout
</match>
```

client
```
<source>
  @type dummy
  tag test
</source>

<match test>
  @type forward

  <server>
    host localhost // if it's 127.0.0.1 then it works well
    port 24224
  </server>
  flush_interval 0
</match>
```

**Comment by cosmo0920** [comment]
I also got error with TLS insecure mode....

**Comment by ganmacs** [comment]
oh…sorry. My answer was completely difference with this issue....  I found another bug...
Your config needs `tls` in the argument of transport  (`<transport tls>` is correct).
The following config is correct .

```
<source>
  @type forward
  port 24224
  <transport tls>
    cert_path ./pem/ca_cert.pem
    private_key_path ./pem/ca_key.pem
    private_key_passphrase fluentd
  </transport>
</source>
<match xxx.**>
  @type stdout
</match>
```

**Comment by cosmo0920** [comment]
> The following config is correct .

Oops. I've overlooked `tls` attributes in `<transport>`.
Thanks for the answear and sorry for bothering in issue ticket. :cold_sweat:
