### ISSUE TITLE
emit transaction failed IOError  from S3 Input

### ISSUE THREAD

**Issue by jydonff** [fluent/fluentd#2880]
**Describe the bug**

**To Reproduce**
fluentd process : s3 source file -> filter / edit -> destination s3 bucket output

1. s3 input  ( by sqs)
2. s3 output  buffer size 16MB
3. over 80MB json file  s3 upload ( over 50,000 lines) -> under 40MB  size file is no error !
 

**Expected behavior**

**Your Environment**
1. fluentd version 1.7 & 1.9.2  . error is same.
3. instance type : m4.large (2cpu, 8GB  Ram)
4. fluentd worker : 1

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
- Operating system: `cat /etc/os-release`
- Kernel version: `uname -r`

**Your Configuration**

```
<system>
    workers 1 
    root_dir /var/log/td-agent/buffer  
</system>

<source>
  @type s3

  # aws_key_id
  # aws_sec_key
  s3_bucket mybucket
  s3_region ap-northeast-1
  store_as json 
  tag s3log.all
  <sqs>
    queue_name  my-sqs
  </sqs>
  <parse>
      @type json 
  </parse>
</source>

<match s3log.all>
    @type rewrite_tag_filter   
    <rule>
       key sid
       pattern (.*)
       tag s3.$1.server
    </rule>      
</match>

<match s3.*.server>
    @type s3
    s3_bucket seoul-test  
    s3_region ap-northeast-2  
    store_as json
    hex_random_length 10
    utc     
    acl bucket-owner-full-control    
    slow_flush_log_threshold 60    
    s3_object_key_format  "server/${sid}/${type}/%Y/%m/%d/%H/${type}-%Y%m%d%H-%M-#{Socket.gethostname}-nxlog-args4_%{index}.json"
    <buffer time,sid,type>
        @type file  
        path /var/log/td-agent/buffer/log-server        
        timekey 1m  
        timekey_wait 0s
        timekey_use_utc true        
        queue_limit_length 512
        chunk_limit_size  16m
        flush_mode interval 
        flush_interval 1m
        flush_at_shutdown true
        flush_thread_count 1  
    </buffer>
    <format>
        @type json 
    </format>    
</match>
```

**Your Error Log**
debug log 
```
2020-03-12 04:21:39 +0000 [debug]: #0 [s3_server] Created new chunk chunk_id="5a0a0b07757ae72c424b16fcf7cfea55" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1583986860, tag=nil, variables={:sid=>"11111", :type=>"abcdLog"}>
2020-03-12 04:21:39 +0000 [warn]: #0 fluent/log.rb:342:warn: emit transaction failed: error_class=IOError error="closed stream" location="/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/buffer/file_chunk.rb:86:in `pos'" tag="s3.11111.server"
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/buffer/file_chunk.rb:86:in `pos'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/buffer/file_chunk.rb:86:in `rollback'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/buffer.rb:321:in `rescue in block in write'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/buffer.rb:314:in `block in write'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/buffer.rb:313:in `each'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/buffer.rb:313:in `write'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/output.rb:951:in `block in handle_stream_with_custom_format'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/output.rb:877:in `write_guard'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/output.rb:950:in `handle_stream_with_custom_format'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/output.rb:869:in `execute_chunking'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/output.rb:797:in `emit_buffered'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/event_router.rb:160:in `emit_events'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/event_router.rb:97:in `emit_stream'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-rewrite-tag-filter-2.2.0/lib/fluent/plugin/out_rewrite_tag_filter.rb:85:in `block in process'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-rewrite-tag-filter-2.2.0/lib/fluent/plugin/out_rewrite_tag_filter.rb:84:in `each'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-rewrite-tag-filter-2.2.0/lib/fluent/plugin/out_rewrite_tag_filter.rb:84:in `process'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/output.rb:786:in `emit_sync'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/event_router.rb:160:in `emit_events'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/event_router.rb:97:in `emit_stream'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-s3-1.1.11/lib/fluent/plugin/in_s3.rb:276:in `process'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-s3-1.1.11/lib/fluent/plugin/in_s3.rb:173:in `block in run'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-sqs-1.20.0/lib/aws-sdk-sqs/queue_poller.rb:413:in `block in yield_messages'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-sqs-1.20.0/lib/aws-sdk-sqs/queue_poller.rb:412:in `each'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-sqs-1.20.0/lib/aws-sdk-sqs/queue_poller.rb:412:in `yield_messages'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-sqs-1.20.0/lib/aws-sdk-sqs/queue_poller.rb:405:in `block in process_messages'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-sqs-1.20.0/lib/aws-sdk-sqs/queue_poller.rb:404:in `catch'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-sqs-1.20.0/lib/aws-sdk-sqs/queue_poller.rb:404:in `process_messages'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-sqs-1.20.0/lib/aws-sdk-sqs/queue_poller.rb:336:in `block (2 levels) in poll'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-sqs-1.20.0/lib/aws-sdk-sqs/queue_poller.rb:331:in `loop'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-sqs-1.20.0/lib/aws-sdk-sqs/queue_poller.rb:331:in `block in poll'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-sqs-1.20.0/lib/aws-sdk-sqs/queue_poller.rb:330:in `catch'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-sqs-1.20.0/lib/aws-sdk-sqs/queue_poller.rb:330:in `poll'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-s3-1.1.11/lib/fluent/plugin/in_s3.rb:167:in `run'
  2020-03-12 04:21:39 +0000 [warn]: #0 plugin/out_rewrite_tag_filter.rb:85:block in process: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-03-12 04:21:39 +0000 [warn]: #0 fluent/log.rb:342:warn: emit transaction failed: error_class=IOError error="closed stream" location="/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.0/lib/fluent/plugin/buffer/file_chunk.rb:86:in `pos'" tag="s3log.all"


```

**Additional context**

**Comment by ganmacs** [comment]
>  error="closed stream"

The error log says the file is already closed. Can you give us more error log about it or other error?

**Comment by jydonff** [comment]
> > error="closed stream"
> 
> The error log says the file is already closed. Can you give us more error log about it or other error?

It is currently under investigation.
The error log is the same.
old td-agent (0.12) is good working. ( no error. destination s3 bucket saved)

Is there anything I need to investigate further?
