### ISSUE TITLE
escaped message and multiline stacktrace  from elasticsearch are not parsed

### ISSUE THREAD

**Issue by obeyda** [fluent/fluentd#2931]
**Describe the bug**

escaped message property and multiline stacktrace logs from elasticsearch are not parsed correctly

**To Reproduce**

basic helm install with elasticsearch, kibana and fluentd-elasticsearch charts
<details>
  <summary>Sample of the Log which causes the issue</summary>

```json 

{"type": "server", "timestamp": "2020-04-02T18:12:24,879Z", "level": "DEBUG", "component": "o.e.a.b.TransportShardBulkAction", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "[logstash-2020.04.02][0] failed to execute bulk item (index) index {[logstash-2020.04.02][_doc][DKoYPHEBXqgdAZngGlKk], source[{\"stream\":\"stdout\",\"StatusCode\":\"OK\",\"EventId\":{\"Id\":101,\"Name\":\"RequestEnd\"},\"ConnectionId\":\"0HLUN3DL88C1U\",\"@timestamp\":\"2020-04-02T18:12:09.690394005+00:00\"}]}", "cluster.uuid": "FUbLQJb7QX-zhJ1f_Z7B4A", "node.id": "9YyIKNfNRsKrZ-UX6pYaaA" , 
"stacktrace": ["org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [StatusCode] of type [long] in document with id 'DKoYPHEBXqgdAZngGlKk'. Preview of field's value: 'OK'",
"at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:306) ~[elasticsearch-7.6.1.jar:7.6.1]",
"at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:488) ~[elasticsearch-7.6.1.jar:7.6.1]",
"at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:614) ~[elasticsearch-7.6.1.jar:7.6.1]",
"at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:427) ~[elasticsearch-7.6.1.jar:7.6.1]",
"at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:395) ~[elasticsearch-7.6.1.jar:7.6.1]",
"Caused by: java.lang.IllegalArgumentException: For input string: \"OK\"",
"at org.elasticsearch.index.mapper.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:1050) ~[elasticsearch-7.6.1.jar:7.6.1]",
"at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:284) ~[elasticsearch-7.6.1.jar:7.6.1]",
"... 160 more"] }
```

</details>

**Expected behavior**

- message is parsed.
- multiline stacktrace is parsed correctly in a single document

**Actual behavior**
- message property is not parsed correctly, it is a string (see screenshot) 
- each line of the stacktrace property is parsed as a single document (see screenshot)

*Screenshot of (only) message property*
![image](https://user-images.githubusercontent.com/15065966/78342315-fedf2a00-7590-11ea-80b4-0919a3e6f581.png)

**Your Environment**
kubernetes

- Fluentd or td-agent version: quay.io/fluentd_elasticsearch/fluentd:v3.0.0

**Your Configuration**

```
  containers.input.conf: |-
    <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/containers.log.pos
      tag raw.kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>

    <filter **>
      @id filter_concat
      @type concat
      key message
      multiline_end_regexp /\n$/
      separator ""
      timeout_label @NORMAL
      flush_interval 5
    </filter>

    <filter kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>

    <filter kubernetes.**>
      @id filter_parser
      @type parser
      key_name log
      reserve_time true
      reserve_data true
      remove_key_name_field true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>
  output.conf: |-

    <match **>
      @type relabel
      @label @NORMAL
    </match>

    <label @NORMAL>
    <match **>
      @id elasticsearch
      @type "#{ENV['OUTPUT_TYPE']}"
      @log_level "#{ENV['OUTPUT_LOG_LEVEL']}"
      include_tag_key true
      host "#{ENV['OUTPUT_HOST']}"
      port "#{ENV['OUTPUT_PORT']}"
      path "#{ENV['OUTPUT_PATH']}"
      scheme "#{ENV['OUTPUT_SCHEME']}"
      ssl_verify "#{ENV['OUTPUT_SSL_VERIFY']}"
      ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
      type_name "#{ENV['OUTPUT_TYPE_NAME']}"
      user "#{ENV['OUTPUT_USER']}"
      password "#{ENV['OUTPUT_PASSWORD']}"
      logstash_format true
      logstash_prefix "#{ENV['LOGSTASH_PREFIX']}"
      reconnect_on_error true
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
        queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
        overflow_action block
      </buffer>
    </match>
    </label>

    <source>
      @id minion
      @type tail
      format /^(?<time>[^ ]* [^ ,]*)[^\[]*\[[^\]]*\]\[(?<severity>[^ \]]*) *\] (?<message>.*)$/
      time_format %Y-%m-%d %H:%M:%S
      path /var/log/salt/minion
      pos_file /var/log/salt.pos
      tag salt
    </source>

    <source>
      @id docker.log
      @type tail
      format /time="(?<time>[^)]*)" level=(?<severity>[^ ]*) msg="(?<message>[^"]*)"( err="(?<error>[^"]*)")?( statusCode=($<status_code>\d+))?/
      path /var/log/docker.log
      pos_file /var/log/docker.log.pos
      tag docker
    </source>

```

**Comment by floriankoch** [comment]
This is not "supported" per default  by fluentd, you need this plugin
https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions
