### ISSUE TITLE
After starting fluentd getting buffer error

### ISSUE THREAD

**Issue by skdjango001** [fluent/fluentd#2932]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
Getting error when running td-agent command after that buffer error coming  

**To Reproduce**

**Expected behavior**

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
- Operating system: `cat /etc/os-release`
- Kernel version: `uname -r`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**
2020-04-03 16:32:52 +0530 [error]: #0 failed to purge buffer chunk chunk_id="5a24d58e553b7eb9928505d802509502" error_class=Errno::ENOENT error=#<Errno::ENOENT: No such file or directory @ unlink_internal - /etc/td-agent/test-multiple/out-file/authlog/buffer/buffer.q5a24d58e553b7eb9928505d802509502.log>
  2020-04-03 16:32:52 +0530 [error]: #0 suppressed same stacktrace
2020-04-03 16:33:15 +0530 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=285.11238964647055 slow_flush_log_threshold=20.0 plugin_id="object:2abad538f120"
2020-04-03 16:33:15 +0530 [error]: #0 failed to purge buffer chunk chunk_id="5a25bdfa3be19b5edbdd370869e9b3bd" error_class=Errno::ENOENT error=#<Errno::ENOENT: No such file or directory @ unlink_internal - /etc/td-agent/test-multiple/out-file/apache_error/buffer/buffer.q5a25bdfa3be19b5edbdd370869e9b3bd.log>
  2020-04-03 16:33:15 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.2/lib/fluent/plugin/buffer/file_chunk.rb:163:in `unlink'
  2020-04-03 16:33:15 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.2/lib/fluent/plugin/buffer/file_chunk.rb:163:in `purge'
  2020-04-03 16:33:15 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.2/lib/fluent/plugin/buffer.rb:511:in `block in purge_chunk'
  2020-04-03 16:33:15 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
  2020-04-03 16:33:15 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.2/lib/fluent/plugin/buffer.rb:502:in `purge_chunk'
  2020-04-03 16:33:15 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.2/lib/fluent/plugin/output.rb:1018:in `commit_write'
  2020-04-03 16:33:15 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.2/lib/fluent/plugin/output.rb:1137:in `try_flush'
  2020-04-03 16:33:15 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.2/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-04-03 16:33:15 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.2/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-04-03 16:33:15 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.9.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

**Additional context**

**Comment by ganmacs** [comment]
> To Reproduce

This section is blank. so we can't handle it.
