### ISSUE TITLE
Error: failed to expand record.to_json ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by icpenguins** [fluent/fluentd#2964]
**Describe the bug**

Fluentd is being used to process SYSLOGs from an access point. The configuration is working with several different access points in the environment, but this particular access point messages occasionally cause an exception.

***Errors***

```bash
2020-04-20 14:01:39 +0000 [warn]: #0 dump an error event: error_class=RuntimeError error="failed to expand `record.to_json` : error = \"\\xE7\" from ASCII-8
BIT to UTF-8" location="/usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.1/lib/fluent/plugin/filter_record_transformer.rb:310:in `rescue in expand'" tag="unifi.ke
rn.warn" time=2020-04-20 07:01:40.000000000 +0000 record={"host"=>"U7NHD,e063da216001,v4.0.80.10875:", "ident"=>"kernel", "message"=>"pSsid=icueH`l-\x1A\xE7
\t\x17\xFF\xFF"}
2020-04-20 14:31:30 +0000 [warn]: #0 dump an error event: error_class=RuntimeError error="failed to expand `record.to_json` : error = \"\\xFF\" from ASCII-8
BIT to UTF-8" location="/usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.1/lib/fluent/plugin/filter_record_transformer.rb:310:in `rescue in expand'" tag="unifi.ke
rn.warn" time=2020-04-20 07:31:30.000000000 +0000 record={"host"=>"U7NHD,e063da216001,v4.0.80.10875:", "ident"=>"kernel", "message"=>"pSsid=icueH`l-\x1Ao\b\
x17\xFF\xFF\xFF"}
2020-04-20 15:20:11 +0000 [warn]: #0 dump an error event: error_class=RuntimeError error="failed to expand `record.to_json` : error = \"\\xAD\" from ASCII-8
BIT to UTF-8" location="/usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.1/lib/fluent/plugin/filter_record_transformer.rb:310:in `rescue in expand'" tag="unifi.ke
rn.warn" time=2020-04-20 08:20:11.000000000 +0000 record={"host"=>"U7NHD,e063da216001,v4.0.80.10875:", "ident"=>"kernel", "message"=>"pSsid=icueH`l-\x1A\xAD
\t\e\xFF\xFF"}
2020-04-20 19:12:29 +0000 [warn]: #0 dump an error event: error_class=RuntimeError error="failed to expand `record.to_json` : error = \"\\xE7\" from ASCII-8
BIT to UTF-8" location="/usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.1/lib/fluent/plugin/filter_record_transformer.rb:310:in `rescue in expand'" tag="unifi.ke
rn.warn" time=2020-04-20 12:12:29.000000000 +0000 record={"host"=>"U7NHD,e063da216001,v4.0.80.10875:", "ident"=>"kernel", "message"=>"pSsid=icueH`l-\x1A\xE7
\t\x17\xFF\xFF"}
```

**To Reproduce**

1. Build docker image

```dockerfile
FROM fluent/fluentd:v1.9.1-1.0

USER root

RUN fluent-gem install fluent-plugin-newrelic
```

2. Run image with the following configuration

```xml
<ROOT>
  <source>
    @type http
    port 9880
    bind "0.0.0.0"
  </source>
  <source>
    @type syslog
    port 5140
    bind "0.0.0.0"
    tag "unifi"
  </source>
  <filter unifi.**>
    @type grep
    <exclude>
      key "message"
      pattern /VDEV_MGR_DEBID_DEFINITION_START|BEACON_EVENT_SWBA_SEND_FAILED/
    </exclude>
  </filter>
  <filter unifi.**>
    @type record_transformer
    renew_record true
    enable_ruby true
    <record>
      timestamp ${time.to_f}
      hostname ${record["host"]}
      service ${tag_prefix[1]}
      log_level ${tag_suffix[2]}
      message ${record.to_json}
    </record>
  </filter>
  <source>
    @type syslog
    port 5142
    bind "0.0.0.0"
    tag "edge-max"
  </source>
  <filter edge-max.**>
    @type grep
    <exclude>
      key "message"
      pattern /(bin\/mount -o remount \/opt\/vyatta\/config\/tmp|opt\/vyatta\/sbin\/ubnt_vtysh|iptables-save -c -t|iptables -t nat -L UBNT_PFOR_DNAT_RULES -
vnx)|(pam_unix\(sudo:session\): session (closed|opened) for user root)/
    </exclude>
  </filter>
  <filter edge-max.**>
    @type record_transformer
    renew_record true
    enable_ruby true
    <record>
      timestamp ${time.to_f}
      hostname ${record["host"]}
      service ${tag_prefix[1]}
      log_level ${tag_suffix[2]}
      message ${record.to_json}
    </record>
  </filter>
  <source>
    @type syslog
    port 5144
    bind "0.0.0.0"
    tag "cisco-sg300"
    <parse>
      message_format rfc5424
    </parse>
  </source>
  <source>
    @type syslog
    port 5146
    bind "0.0.0.0"
    tag "printer-m454dw"
  </source>
  <match **>
    @type newrelic
    api_key "{redacted}"
  </match>
</ROOT>
```

**Expected behavior**

I would expect that the exception for ASCII to UTF-8 not fail.

**Your Environment**

This is running in the provided Docker Hub image from fluent/fluentd

```bash
2020-04-20 03:26:05 +0000 [info]: starting fluentd-1.10.1 pid=9 ruby="2.5.8"
2020-04-20 03:26:05 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluen
td.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
```

**Comment by repeatedly** [comment]
FAQ mentions this case: https://docs.fluentd.org/quickstart/faq#i-got-encoding-error-inside-plugin-how-to-fix-it
