### ISSUE TITLE
td-agent crashed when hostname cannot be resolved

### ISSUE THREAD

**Issue by theanotherwise** [fluent/fluentd#3007]
**Describe the bug**
When the hostname is set to domain, which cannot be resolved, fluentd crashed, **td-agent not crashed and works correctly when can resolve the domain**.

**To Reproduce**
 * stop td-agent
 * set host as to domain which cannot be resolved by DNS
 * start td-agent

**Expected behavior**
td-agent crashed

**Your Environment**

- Fluentd or td-agent version: `1.10.2`
- Operating system: `18.04.4 LTS (Bionic Beaver)`
- Kernel version: `5.3.0-53-generic`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<source>
  @type syslog
  port 5140
  bind 127.0.0.1
  tag syslog
  <parse>
...
  </parse>
</source>

<match **>
...
  <server>
    host hostname.hostndomain
    port 24224
    <transport tcp>
    </transport>
  </server>
...
</match>
```
**Your Error Log**
```
May 25 12:24:01 zeta fluentd[20412]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/out_forward.rb:723:in `getaddrinfo': getaddrinfo: Temporary failure in name resolution (SocketError)
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/out_forward.rb:723:in `resolve_dns!'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/out_forward.rb:709:in `resolved_host'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/out_forward.rb:569:in `validate_host_resolution!'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/out_forward.rb:258:in `block in configure'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/out_forward.rb:253:in `each'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/out_forward.rb:253:in `configure'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin.rb:173:in `configure'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/agent.rb:132:in `add_match'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/agent.rb:74:in `block in configure'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/agent.rb:64:in `each'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/agent.rb:64:in `configure'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/root_agent.rb:146:in `configure'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/engine.rb:105:in `configure'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/engine.rb:80:in `run_configure'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/supervisor.rb:551:in `run_supervisor'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/command/fluentd.rb:330:in `<top (required)>'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/bin/fluentd:8:in `<top (required)>'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/bin/fluentd:23:in `load'
May 25 12:24:01 zeta fluentd[20412]:         from /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
May 25 12:24:01 zeta systemd[1]: td-agent.service: Control process exited, code=exited status=1
May 25 12:24:01 zeta systemd[1]: td-agent.service: Failed with result 'exit-code'.
May 25 12:24:01 zeta systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
```

**Additional context**

```
2020-05-25 13:20:34 +0200 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2020-05-25 13:20:34 +0200 [info]: gem 'fluent-plugin-elasticsearch' version '4.0.7'
2020-05-25 13:20:34 +0200 [info]: gem 'fluent-plugin-kafka' version '0.13.0'
2020-05-25 13:20:34 +0200 [info]: gem 'fluent-plugin-prometheus' version '1.7.3'
2020-05-25 13:20:34 +0200 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.0.2'
2020-05-25 13:20:34 +0200 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-05-25 13:20:34 +0200 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2020-05-25 13:20:34 +0200 [info]: gem 'fluent-plugin-s3' version '1.3.1'
2020-05-25 13:20:34 +0200 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-05-25 13:20:34 +0200 [info]: gem 'fluent-plugin-td' version '1.1.0'
2020-05-25 13:20:34 +0200 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2020-05-25 13:20:34 +0200 [info]: gem 'fluent-plugin-webhdfs' version '1.2.4'
2020-05-25 13:20:34 +0200 [info]: gem 'fluentd' version '1.10.2'
2020-05-25 13:20:34 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3fd2d1c42f3c"
2020-05-25 13:20:34 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3fd2d1c42f3c"
2020-05-25 13:20:34 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3fd2d1c42f3c"
2020-05-25 13:20:35 +0200 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-elasticsearch' version '4.0.7'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-kafka' version '0.13.0'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-prometheus' version '1.7.3'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.0.2'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-s3' version '1.3.1'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-td' version '1.1.0'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-webhdfs' version '1.2.4'
2020-05-25 13:20:35 +0200 [info]: gem 'fluentd' version '1.10.2'
2020-05-25 13:20:35 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3fb29aa50f78"
2020-05-25 13:20:35 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3fb29aa50f78"
2020-05-25 13:20:35 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3fb29aa50f78"
2020-05-25 13:20:35 +0200 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-elasticsearch' version '4.0.7'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-kafka' version '0.13.0'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-prometheus' version '1.7.3'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.0.2'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-s3' version '1.3.1'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-td' version '1.1.0'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2020-05-25 13:20:35 +0200 [info]: gem 'fluent-plugin-webhdfs' version '1.2.4'
2020-05-25 13:20:35 +0200 [info]: gem 'fluentd' version '1.10.2'
2020-05-25 13:20:35 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3ff2e6752ccc"
2020-05-25 13:20:35 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3ff2e6752ccc"
2020-05-25 13:20:35 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3ff2e6752ccc"
2020-05-25 13:20:36 +0200 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-elasticsearch' version '4.0.7'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-kafka' version '0.13.0'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-prometheus' version '1.7.3'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.0.2'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-s3' version '1.3.1'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-td' version '1.1.0'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-webhdfs' version '1.2.4'
2020-05-25 13:20:36 +0200 [info]: gem 'fluentd' version '1.10.2'
2020-05-25 13:20:36 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3f8454433920"
2020-05-25 13:20:36 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3f8454433920"
2020-05-25 13:20:36 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3f8454433920"
2020-05-25 13:20:36 +0200 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-elasticsearch' version '4.0.7'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-kafka' version '0.13.0'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-prometheus' version '1.7.3'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.0.2'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-s3' version '1.3.1'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-td' version '1.1.0'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2020-05-25 13:20:36 +0200 [info]: gem 'fluent-plugin-webhdfs' version '1.2.4'
2020-05-25 13:20:36 +0200 [info]: gem 'fluentd' version '1.10.2'
2020-05-25 13:20:36 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3fc295450f78"
2020-05-25 13:20:36 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3fc295450f78"
2020-05-25 13:20:36 +0200 [info]: adding forwarding server 'hostname.hostndomain:24224' host="hostname.hostndomain" port=24224 weight=60 plugin_id="object:3fc295450f78"
```

**Comment by theanotherwise** [comment]
``

**Comment by repeatedly** [comment]
This is expected behavior for safety.
If you can guarantee that these errors are ignorable, set `ignore_network_errors_at_startup`: https://docs.fluentd.org/output/forward#ignore_network_errors_at_startup

**Comment by theanotherwise** [comment]
@repeatedly 

When `fluentd` starts running and crashed on DNS resolution error, that will not start if DNS starts resolving correctly... 

Default systemd params:
`StartLimitIntervalSec=10s`
`StartLimitBurst=5`

After 5 tries every 10 seconds `systemd` will stop trying to start correct `fluentd`, and one of the hosts will not send logs, to moment that start `fluentd` again manually or remote command.

What if I set `ignore_network_errors_at_startup` to `true` and DNS will not resolve the hostname? Will `fluentd` lose logs?
