### ISSUE TITLE
Multiline json: pattern not matched

### ISSUE THREAD

**Issue by everythings-gonna-be-alright** [fluent/fluentd#3087]
**Describe the bug**
My raw record ( as i know it look like valid json):
```
{"type": "server", "timestamp": "2020-07-27T22:43:48,874+03:00", "level": "WARN", "component": "o.e.a.b.TransportShardBulkAction", "cluster.name": "request_log", "node.name": "node4.example.com", "message": "[[example][4]] failed to perform indices:data/write/bulk[s] on replica [example][4], node[example], [R], s[STARTED], a[id=example]", "cluster.uuid": "example", "node.id": "example" , 
"stacktrace": ["org.elasticsearch.transport.NodeNotConnectedException: [node4.example.com][10.55.136.4:9300] Node not connected",
"at org.elasticsearch.transport.ClusterConnectionManager.getConnection(ClusterConnectionManager.java:189) ~[elasticsearch-7.8.0.jar:7.8.0]",
"at org.elasticsearch.transport.TransportService.getConnection(TransportService.java:674) ~[elasticsearch-7.8.0.jar:7.8.0]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]"] }
```
My fluentd config:
```
    <source>
          @type tail
          format json
          json_parser json
          time_format %iso8601
          pos_file /pos/elasticsearch.log.pos
          path /example/*elasticsearch-*.log
          path_key tailed_path
          refresh_interval 15s
          tag example.dynamic
    </source>
```

Resoult:
```
2020-07-27 22:43:48 +0300 [warn]: #4 pattern not matched: "{\"type\": \"server\", \"timestamp\": \"2020-07-27T22:43:48,071+03:00\", \"level\": \"WARN\", \"component\": \"o.e.a.b.TransportShardBulkAction\", \"cluster.name\": \"example\", \"node.name\": \"node4.example.com\", \"message\": \"[[example][4]] failed to perform indices:data/write/bulk[s] on replica [example][4], node[example, [R], s[STARTED], a[id=example]\", \"cluster.uuid\": \"example\", \"node.id\": \"example\" , "
2020-07-27 22:43:48 +0300 [warn]: #4 pattern not matched: "\"stacktrace\": [\"org.elasticsearch.transport.NodeNotConnectedException: [node4.example.com][10.55.136.4:9300] Node not connected\","
2020-07-27 22:43:48 +0300 [warn]: #4 pattern not matched: "\"at org.elasticsearch.transport.ClusterConnectionManager.getConnection(ClusterConnectionManager.java:189) ~[elasticsearch-7.8.0.jar:7.8.0]\","
2020-07-27 22:43:48 +0300 [warn]: #4 pattern not matched: "\"at org.elasticsearch.transport.TransportService.getConnection(TransportService.java:674) ~[elasticsearch-7.8.0.jar:7.8.0]\","
```

**Environment**
docker image `fluent/fluentd:v1.11-1`
docker version `19.03.5, build 633a0ea838`

**Comment by everythings-gonna-be-alright** [comment]
But overall, it's a controversial topic.
Because we don't know exactly where the recording must end if the line with closing character `}` will lost.
