### ISSUE TITLE
MessagePack::UnknownExtTypeError

### ISSUE THREAD

**Issue by epcim** [fluent/fluentd#3136]
**Describe the bug**

Actually not sure what is happening, seems like bug that was already fixed: 
But this time fluenbtbit forwards to fluentd.

Version:
- fluentd-1.10.4 pid=6 ruby="2.5.8"
- Fluent Bit v1.4.4

Fluentd logs:
```
2020-09-26 11:00:24 +0000 [info]: #0 disable filter chain optimization because [Fluent::Plugin::RecordTransformerFilter, Fluent::Plugin::RecordTransformerFilter, Fluen
t::Plugin::RecordTransformerFilter, Fluent::Plugin::RecordTransformerFilter, Fluent::Plugin::RecordTransformerFilter] uses `#filter_stream` method.
2020-09-26 11:00:28 +0000 [info]: #0 disable filter chain optimization because [Fluent::Plugin::RecordTransformerFilter, Fluent::Plugin::RecordTransformerFilter, Fluen
t::Plugin::RecordTransformerFilter, Fluent::Plugin::RecordTransformerFilter, Fluent::Plugin::RecordTransformerFilter] uses `#filter_stream` method.
2020-09-26 11:00:33 +0000 [error]: #0 unexpected error on reading data host="192.168.12.219" port=32912 error_class=MessagePack::UnknownExtTypeError error="unexpected 
extension type"
  2020-09-26 11:00:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.4/lib/fluent/plugin/in_forward.rb:262:in `feed_each'
  2020-09-26 11:00:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.4/lib/fluent/plugin/in_forward.rb:262:in `block (2 levels) in read_messages'
  2020-09-26 11:00:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.4/lib/fluent/plugin/in_forward.rb:271:in `block in read_messages'
  2020-09-26 11:00:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.4/lib/fluent/plugin_helper/server.rb:768:in `on_read_without_connection'
  2020-09-26 11:00:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.6.0/lib/cool.io/io.rb:123:in `on_readable'
  2020-09-26 11:00:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.4/lib/fluent/plugin_helper/server.rb:729:in `on_readable'
  2020-09-26 11:00:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.6.0/lib/cool.io/io.rb:186:in `on_readable'
  2020-09-26 11:00:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
  2020-09-26 11:00:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
  2020-09-26 11:00:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.4/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2020-09-26 11:00:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-09-26 11:00:43 +0000 [error]: #0 unexpected error on reading data host="192.168.12.219" port=32916 error_class=MessagePack::UnknownExtTypeError error="unexpected extension type"
  2020-09-26 11:00:43 +0000 [error]: #0 suppressed same stacktrace
2020-09-26 11:00:48 +0000 [error]: #0 unexpected error on reading data host="192.168.12.219" port=32922 error_class=MessagePack::UnknownExtTypeError error="unexpected extension type"
  2020-09-26 11:00:48 +0000 [error]: #0 suppressed same stacktrace
2020-09-26 11:01:01 +0000 [error]: #0 unexpected error on reading data host="192.168.12.219" port=33366 error_class=MessagePack::UnknownExtTypeError error="unexpected extension type"
  2020-09-26 11:01:01 +0000 [error]: #0 suppressed same stacktrace
```

On fluentbit almost clear with occasional `warning | [input:forward:forward.0] fd=300 incoming data exceed limit (512000 bytes)` - Which I know why and I expect such input is immediately dropped anyway. 

```
2020 Sep 26 10:58:55 gc01 fluentbit-hf875: info | [filter:throttle:throttle.0] 1601117935: limit is 40000.00 per 60s with window size of 5, current rate is: 1074 per interval
2020 Sep 26 10:59:02 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 10:59:28 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 10:59:30 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 10:59:36 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 10:59:40 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 10:59:55 gc01 fluentbit-hf875: info | [filter:throttle:throttle.0] 1601117995: limit is 40000.00 per 60s with window size of 5, current rate is: 1076 per interval
2020 Sep 26 11:00:55 gc01 fluentbit-hf875: info | [filter:throttle:throttle.0] 1601118055: limit is 40000.00 per 60s with window size of 5, current rate is: 1227 per interval
2020 Sep 26 11:01:37 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 11:01:55 gc01 fluentbit-hf875: info | [filter:throttle:throttle.0] 1601118115: limit is 40000.00 per 60s with window size of 5, current rate is: 1269 per interval
2020 Sep 26 11:02:03 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 11:02:29 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 11:02:55 gc01 fluentbit-hf875: info | [filter:throttle:throttle.0] 1601118175: limit is 40000.00 per 60s with window size of 5, current rate is: 1171 per interval
2020 Sep 26 11:03:04 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 11:03:23 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 11:03:41 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 11:03:55 gc01 fluentbit-hf875: info | [filter:throttle:throttle.0] 1601118235: limit is 40000.00 per 60s with window size of 5, current rate is: 1183 per interval
2020 Sep 26 11:04:32 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 11:04:55 gc01 fluentbit-hf875: info | [filter:throttle:throttle.0] 1601118295: limit is 40000.00 per 60s with window size of 5, current rate is: 925 per interval
2020 Sep 26 11:05:11 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=94 incoming data exceed limit (512000 bytes)
2020 Sep 26 11:05:13 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=286 incoming data exceed limit (512000 bytes)
2020 Sep 26 11:05:20 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=286 incoming data exceed limit (512000 bytes)
2020 Sep 26 11:05:40 gc01 fluentbit-hf875: warning | [input:forward:forward.0] fd=286 incoming data exceed limit (512000 bytes)

```

**Expected behavior**
Shall not happen (any falback possible?)

We need more details on this error, tracing what packet on input forward caused it. It's not clear at all where the things go wrong.

**Your Environment**

centos 7 & amazonlinux

**Your Configuration**

can provide later, but too big to simply paste in...

**Additional context**

BTW: max buffer 512KB on fluentbit side is big enough, however does anyone has experience with bigger ie: 1024MB?

**Comment by epcim** [comment]
I dont see more related dertails in debug logs. Here it seems that above 512KB data are frequent, but in general it was not the case, so hard to catch with debug the event on right node.

**Comment by repeatedly** [comment]
This error happens when incoming data uses invalid msgpack type.
fluentd's in_forward simply passes incoming data to MessagePack decoder.
If this error happens with fluent-bit, the problem is fluent-bit's out_forward has a corner case bug.

**Comment by epcim** [comment]
`incoming data exceed limit (512000 bytes)` is not root cause. I increased the limit, still having the MessagePack decoder issue.

Any other way to debug?

**Comment by kenhys** [comment]
@epcim how did you solved https://github.com/fluent/fluent-bit/issues/2643?, upgrading fluent-bit version or something else?

**Comment by kenhys** [comment]
I'll close this issue without a response for a while.

**Comment by epcim** [comment]
@kenhys we do still "occasionally" experience the issue. It end up in "probably chunk" fail to re-send.
