### ISSUE TITLE
1.12.0: tail plugin crashes worker upon ENOENT (cannot stat() file)

### ISSUE THREAD

**Issue by jgehrcke** [fluent/fluentd#3273]
```
[info]: gem 'fluentd' version '1.12.0'

...

[error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:200:in `block in start'
[error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/in_tail.rb:234:in `start'
[error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/in_tail.rb:353:in `refresh_watchers'
[error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/in_tail.rb:390:in `start_watchers'
[error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/in_tail.rb:390:in `each_value'
[error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/in_tail.rb:409:in `block in start_watchers'
[error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/in_tail.rb:409:in `stat'
[error]: #0 unexpected error error_class=Errno::ENOENT error="No such file or directory @ rb_file_s_stat - /var/log/containers/foo-55fc795779-l66hb_foo_foo-ee7d580da4f6fac071b1e0fa8533fcada239a88404ed2fcde16480fbcd4a39fb.log"
```

I think it is fair to say that at the system call boundary between application and OS the individual system calls like `stat()` / `open()` should always be wrapped with local error handling, expecting the system call to fail. This can then be retried in graceful degradation fashion, w/o affecting the other operations performed by the worker process. An appropriate action would be to log a warning/error showing how the system call failed. Is that what fluentd devs would agree with?

This was observed with Fluentd `1.12.0`, see log above. As per the change 

- This could be related to https://github.com/fluent/fluentd/issues/3224.
- This might be a regression introduced via https://github.com/fluent/fluentd/pull/3155 / https://github.com/fluent/fluentd/pull/2992

The `stat()` call that crashes the worker is https://github.com/fluent/fluentd/blame/65a9edf4e05cf64c7ed0de56e12b3c9a0774e0d6/lib/fluent/plugin/in_tail.rb#L409

As this is part of the inotify-based watch system, of course there's always the race condition between being delivered information about a new file to be there, and it maybe already having disappeared in the moment when we try to access it. Looks like even before the last refactor this stat() wasn't protected: 
https://github.com/fluent/fluentd/pull/3196/files#diff-456fdeb51bc472beb48891caac0d063e0073655dba7ac2b72e6fdc67dc6ac802R409

**Comment by jgehrcke** [comment]
Sorry for that. Tried again with https://github.com/fluent/fluentd/issues/3274.
