### ISSUE TITLE
Tail input plugin doesn't respect SIGTERM  signal 

### ISSUE THREAD

**Issue by shenmuxiaosen** [fluent/fluentd#3323]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
We use tail input plugin to read logs. And Fluentd is deployed as daemonset in Kubernetes. During deployment, Kubernetes will first send a SIGTERM signal to Fluentd container to ask it to gracefully shut down. But tail input plugin keeps reading data until the container eventually killed. 

**To Reproduce**
Run Fluentd in Kubernetes and trigger a deployment. 

**Expected behavior**
When receive SIGTERM, tail should stop reading, keep record of current position and flush out memory buffers. 

**Your Environment**

- Fluentd or td-agent version: `td-agent 4.1.0 fluentd 1.12.1 (e3effa337593618cbd7f0f4ef071766df1ec69a0)`
- Operating system: `Ubuntu 18.04.5 LTS (Bionic Beaver)`
- Kernel version: `5.4.0-1039-azure`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-containers.log.pos
  time_key @timestamp
  tag kubernetes.*
  format json
  read_from_head true
</source>
```

**Your Error Log**

```
N/A
```

**Additional context**

N/A

**Comment by ashie** [comment]
It may be a same issue with https://github.com/fluent/fluentd/pull/3185#discussion_r607012100

**Comment by shenmuxiaosen** [comment]
@ashie Do you have a rough ETA when v.1.13.0 can be released? Besides the issue you mentioned above, we also hit this one https://github.com/fluent/fluentd/issues/3324 and I saw the fix has been merged already.

**Comment by ashie** [comment]
> @ashie Do you have a rough ETA when v.1.13.0 can be released? Besides the issue you mentioned above, we also hit this one #3324 and I saw the fix has been merged already.

v1.12.2 which fixes for #3324 is already released: https://rubygems.org/gems/fluentd/versions/1.12.2
We found another bug in v1.12.2 though... #3327 We'll release 1.12.3 to fix it.
td-agent which includes v1.12.2 isn't released yet, we are preparing it now: https://github.com/fluent-plugins-nursery/td-agent-builder/pull/288

**Comment by fujimotos** [comment]
> **Describe the bug**
> We use tail input plugin to read logs. And Fluentd is deployed as daemonset in Kubernetes. During deployment, Kubernetes will first send a SIGTERM signal to Fluentd container to ask it to gracefully shut down. But tail input plugin keeps reading data until the container eventually killed.

@shenmuxiaosen @ashie For what it is worth, I could not reproduce this
particular issue. I used the following configuration:

```xml
<source>
  @type tail
  path test.log
  pos_file fluentd-containers.log.pos
  time_key @timestamp
  tag kubernetes.*
  read_from_head true
  format json
</source>
```

and set up a moderately-busy writer:

```shell
$ while true; do cat log >> test.log; sleep 0.01; done;
```

I can confirm Fluentd always shutdown cleanly on SIGTERM.

I tested Fluentd v1.12.1 and v1.12.2. Both worked fine. Neither I saw
any shutdown delay nor irregular exit while my testing.

I'm a bit suspecting that the real issue may not in Fluentd per se, but
rather in how the k8s/docker image is set up. I'm thinking something
like fluent/fluentd-docker-image/issues/92.

I'd like to hear from @shenmuxiaosen if upgrading to v1.12.2 resolves
the shutdown issue, but if not, we might need to look at k8s/docker to fix
this issue.

**Comment by shenmuxiaosen** [comment]
> > **Describe the bug**
> > We use tail input plugin to read logs. And Fluentd is deployed as daemonset in Kubernetes. During deployment, Kubernetes will first send a SIGTERM signal to Fluentd container to ask it to gracefully shut down. But tail input plugin keeps reading data until the container eventually killed.
> 
> @shenmuxiaosen @ashie For what it is worth, I could not reproduce this
> particular issue. I used the following configuration:
> 
> ```
> <source>
>   @type tail
>   path test.log
>   pos_file fluentd-containers.log.pos
>   time_key @timestamp
>   tag kubernetes.*
>   read_from_head true
>   format json
> </source>
> ```
> 
> and set up a moderately-busy writer:
> 
> ```shell
> $ while true; do cat log >> test.log; sleep 0.01; done;
> ```
> 
> I can confirm Fluentd always shutdown cleanly on SIGTERM.
> 
> I tested Fluentd v1.12.1 and v1.12.2. Both worked fine. Neither I saw
> any shutdown delay nor irregular exit while my testing.
> 
> I'm a bit suspecting that the real issue may not in Fluentd per se, but
> rather in how the k8s/docker image is set up. I'm thinking something
> like [fluent/fluentd-docker-image/issues/92](https://github.com/fluent/fluentd-docker-image/issues/92).
> 
> I'd like to hear from @shenmuxiaosen if upgrading to v1.12.2 resolves
> the shutdown issue, but if not, we might need to look at k8s/docker to fix
> this issue.

In our Kubernetes cluster, we configured the shut down grace period for fluentd container to be 5 minutes. So K8s will send SIGTERM signal right away after pod shutdown requested and waited 5 minutes to send the kill signal. Then our observation is that tail input plugin kept reading new logs during this 5 minutes. Ideally we expect tail to stop right away and the grace period is just used to clear buffers and preparing for shutdown. FYI, we are still using v1.12.1 as ashie mentioned v1.12.2 introduces another bug.

**Comment by ashie** [comment]
Maybe I've reproduced this issue.
When I create a large log file (more than 100MB) and use `read_from_head`, fluentd doesn't respond to SIGTERM signal until completing to read the file. This is because `TailWatcher::IOHandler#handle_notify` runs busy loop.

https://github.com/fluent/fluentd/blob/4455d3442a2ae868c557dc9c42af21a242d9c30e/lib/fluent/plugin/in_tail.rb#L912-L940

The log throttling feature #3185 may resolve this issue.

**Comment by ashie** [comment]
> When I create a large log file (more than 100MB) and use read_from_head, fluentd doesn't respond to SIGTERM signal until completing to read the file. This is because TailWatcher::IOHandler#handle_notify runs busy loop.

Why it blocks shoudown is that it is occurred on the main thread during startup process. It can avoid by [`skip_refresh_on_startup`](https://docs.fluentd.org/v/1.0/input/tail#skip_refresh_on_startup) (FYI: https://www.fluentd.org/blog/fluentd-v0.12.33-has-been-released).

But when I use this option and killing the process while reading a large file, following error is occurred. It doesn't seem graceful:

```
2021-05-01 22:32:45 +0900 [error]: #0 closed stream
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail/position_file.rb:212:in `pos='
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail/position_file.rb:212:in `block in update_pos'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail/position_file.rb:211:in `synchronize'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail/position_file.rb:211:in `update_pos'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:934:in `block in handle_notify'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:965:in `with_io'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:913:in `handle_notify'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:896:in `block in on_notify'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:896:in `synchronize'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:896:in `on_notify'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:725:in `on_notify'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:376:in `setup_watcher'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:410:in `block in start_watchers'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:396:in `each_value'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:396:in `start_watchers'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:359:in `refresh_watchers'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-05-01 22:32:45 +0900 [error]: #0 Unexpected error raised. Stopping the timer. title=:in_tail_refresh_watchers error_class=IOError error="closed stream"
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail/position_file.rb:46:in `seek'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail/position_file.rb:46:in `block in []'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail/position_file.rb:45:in `synchronize'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail/position_file.rb:45:in `[]'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:399:in `block in start_watchers'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:396:in `each_value'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:396:in `start_watchers'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:359:in `refresh_watchers'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2021-05-01 22:32:45 +0900 [error]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-05-01 22:32:45 +0900 [warn]: #0 thread exited by unexpected error plugin=Fluent::Plugin::TailInput title=:event_loop error_class=RuntimeError error="not attached to a loop"
#<Thread:0x0000556c9f4c4d50@event_loop /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/thread.rb:70 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	12: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
	11: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
	10: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
	 9: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
	 8: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
	 7: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:359:in `refresh_watchers'
	 6: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:396:in `start_watchers'
	 5: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:396:in `each_value'
	 4: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail.rb:399:in `block in start_watchers'
	 3: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail/position_file.rb:45:in `[]'
	 2: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail/position_file.rb:45:in `synchronize'
	 1: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail/position_file.rb:46:in `block in []'
/home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/in_tail/position_file.rb:46:in `seek': closed stream (IOError)
	6: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
	5: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
	4: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
	3: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
	2: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/timer.rb:81:in `on_timer'
	1: from /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/timer.rb:84:in `rescue in on_timer'
/home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/timer.rb:84:in `detach': not attached to a loop (RuntimeError)
2021-05-01 22:32:45 +0900 [warn]: #0 unexpected error while calling after_shutdown on input plugin plugin=Fluent::Plugin::TailInput plugin_id="object:938" error_class=RuntimeError error="not attached to a loop"
  2021-05-01 22:32:45 +0900 [warn]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/timer.rb:84:in `detach'
  2021-05-01 22:32:45 +0900 [warn]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/timer.rb:84:in `rescue in on_timer'
  2021-05-01 22:32:45 +0900 [warn]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/timer.rb:81:in `on_timer'
  2021-05-01 22:32:45 +0900 [warn]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2021-05-01 22:32:45 +0900 [warn]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2021-05-01 22:32:45 +0900 [warn]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2021-05-01 22:32:45 +0900 [warn]: #0 /home/aho/Projects/Fluentd/fluentd/issues/3239/vendor/bundle/ruby/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-05-01 22:32:45 +0900 [info]: Worker 0 finished with status 0
```

**Comment by fujimotos** [comment]
@ashie If that is the case, wouldn't this resolve this issue?
I'm thinking adding something like below (very rough sketch):
```ruby
do
    ....
   read_more = false if shutdown?
while read_more 
```

**Comment by ashie** [comment]
> @ashie If that is the case, wouldn't this resolve this issue?
> I'm thinking adding something like below (very rough sketch):
> 
> ```ruby
> do
>     ....
>    read_more = false if shutdown?
> while read_more 
> ```

Thanks. Yes, I think something like that is required.

**Comment by fujimotos** [comment]
Note: I suspect that #3345 is a similar issue, that is, `in_tail` doing a busy
loop prevents the shutdown, thus reload is being delayed.

Maybe we can save two birds here with a single patch.

**Comment by ashie** [comment]
#3380 has been merged. 
v1.13.0 will ship it (will be released at the end of this month).
Please use with `skip_refresh_on_startup`.
