### ISSUE TITLE
error_class=Zlib::GzipFile::Error error="not in gzip format"

### ISSUE THREAD

**Issue by sumo-drosiek** [fluent/fluentd#3350]
**Describe the bug**
After some time of working, fluentd is starting to produce following errors

```
2021-03-24 11:06:52 +0000 [warn]: #0 [sumologic.endpoint.logs.default] failed to flush the buffer. retry_time=0 next_retry_seconds=2021-03-24 11:06:53 +0000 chunk="5be45feac120cff4dccdc496747843a8" error_class=Zlib::GzipFile::Error error="not in gzip format"
```

It has been reported to us by our users, as well we are seeing this on several environments. Error is non-deterministic and we unfortunately doesn't have stacktrace for it (yet). Only observation we have is that mentioned chunk file is empty

**To Reproduce**
N/A

**Expected behavior**
No error

**Your Environment**

- Fluentd or td-agent version: `fluentd 1.12.1`
- Operating system: `PRETTY_NAME="Debian GNU/Linux 10 (buster)`
- Kernel version: `https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1522`

**Your Configuration**

https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1522

**Your Error Log**

https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1522

**Additional context**

https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1522

**Comment by kenhys** [comment]
> 2021-03-24 11:06:52 +0000 [warn]: #0 [sumologic.endpoint.logs.default] failed to flush the buffer. retry_time=0 next_retry_seconds=2021-03-24 11:06:53 +0000 chunk="5be45feac120cff4dccdc496747843a8" error_class=Zlib::GzipFile::Error error="not in gzip format"

It was caused by an empty buffer.

```
fluent@collection-sumologic-1:/$ ls -l /fluentd/buffer/logs.default/
total 8
-rw-r--r-- 1 fluent fluent    0 Mar 19 12:18 buffer.b5bde2b7225ad70f7d1eeb473af979652.log
-rw-r--r-- 1 fluent fluent    0 Mar 19 12:25 buffer.b5bde2d0693d05a4d7dd397e388bbac72.log
-rw-r--r-- 1 fluent fluent 3753 Mar 22 08:30 buffer.b5be1be15c62766245a80e6d8561c420c.log
-rw-r--r-- 1 fluent fluent   86 Mar 22 08:30 buffer.b5be1be15c62766245a80e6d8561c420c.log.meta
```

Is there any warning logs before `error_class=Zlib::GzipFile::Error error="not in gzip format"`?

**Comment by sumo-drosiek** [comment]
@kenhys Maybe before first occurrence, but we do not have logs for that due to rotation. Will update in case I catch them

**Comment by sumo-drosiek** [comment]
I have a stacktrace, but it doesn't explain why the buffer files are empty

```txt
2021-05-12 06:42:36 +0000 [warn]: #0 [sumologic.endpoint.events] failed to flush the buffer. retry_time=0 next_retry_seconds=2021-05-12 06:4
2:37 +0000 chunk="5c199dd08455004f4289b8dc35c38103" error_class=Zlib::GzipFile::Error error="not in gzip format"
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin/compressable.rb:79:in `initialize'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin/compressable.rb:79:in `new'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin/compressable.rb:79:in `block in io_decompress'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin/compressable.rb:78:in `loop'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin/compressable.rb:78:in `io_decompress'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin/compressable.rb:38:in `decompress'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin/buffer/chunk.rb:212:in `block in open'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin/buffer/file_chunk.rb:171:in `open'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin/buffer/chunk.rb:205:in `open'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/event.rb:314:in `each'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-sumologic_output-1.7.1/lib/fluent/plugin/out_sumologic.rb:301:in `write'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin/output.rb:1136:in `try_flush'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin/output.rb:1448:in `flush_thread_run'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'
  2021-05-12 06:42:36 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.12.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by zlymeda** [comment]
I saw the same issue. I did not use gzip before. Then I have changed the configuration and used gzip; but this is now failing for the existing buffer.
Is there a way to "migrate" old non-gzip buffer to gzip so that fluent can process it?

@sumo-drosiek did you recently change buffer to be gzipped? if so I think that's the problem

**Comment by sumo-drosiek** [comment]
@zlymeda

Thanks for suggestion, but this is scenario with clear installation with gzip buffer :(
There wasn't any non-gzip leftovers

**Comment by Zachary-Love** [comment]
Had this same issue. I had the `flush_interval` on the match (output) set to 1 second. I upped it to 30 seconds and the issue disappeared! Hope this helps someone.

**Comment by dfisicaro** [comment]
@Zachary-Love Thanks a lot. I had the same issue which was strange. 

I was testing a reingest of some logs we saved from a couple yrs ago which were saved in GZIP format to an S3 bucket. We were using an older version of fluentd i think 3.x and now I was trying to reingest these using fluentd (td-agent 4.2) via SQS/S3 plugin and I was getting the same error: 

error_class=Zlib::GzipFile::Error error="not in gzip format"

I had my "flush_interval" at 5s and now changed it to 30s and its working.

The other weird thing is I have my "flush_interval" set to 5s on some environments which we have writing to an S3 bucket and I'm doing the same process, and they work perfectly fine. The only difference I see is they are using the same version of the td-agent (On the Forwarder and Consumer side). I'm not sure if this is a bug between versions but thanks so much. 

Thanks.
