### ISSUE TITLE
NameError: uninitialized constant RubyVM for non-CRuby

### ISSUE THREAD

**Issue by eregon** [fluent/fluentd#3375]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
Starting fluentd on any other implementation than CRuby (e.g. TruffleRuby) causes:
```
$ bundle exec fluentd -c receiver.conf
bundler: failed to load command: fluentd (/home/eregon/.rubies/truffleruby-dev/bin/fluentd)
NameError: uninitialized constant RubyVM
  /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/fluentd-1.12.3/bin/fluentd:4:in `const_missing'
  /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/fluentd-1.12.3/bin/fluentd:4:in `<top (required)>'
  <internal:core> core/kernel.rb:400:in `load'
  <internal:core> core/kernel.rb:400:in `load'
  /home/eregon/.rubies/truffleruby-dev/bin/fluentd:23:in `<top (required)>'
  <internal:core> core/kernel.rb:400:in `load'
  <internal:core> core/kernel.rb:400:in `load'
```
due to
https://github.com/fluent/fluentd/blob/5bd334613fa0561298cf9b7acbdd65043ad9e473/bin/fluentd#L4
https://github.com/fluent/fluentd/pull/1764

**To Reproduce**
I used https://github.com/fluent/fluentd-benchmark/tree/master/one_forward but any fluent command would do

**Expected behavior**
It should work.

The `rescue nil` is not enough, for instance this also fails on CRuby:
```
$ ruby -ve 'RubyVM2::InstructionSequence.compile_option = {trace_instruction: false} rescue nil'
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]
Traceback (most recent call last):
-e:1:in `<main>': uninitialized constant RubyVM2 (NameError)
```

I think the issue is the `rescue nil` only applies to `{trace_instruction: false}` and not the whole assignment.

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`: 1.12.3

**Comment by cosmo0920** [comment]
I'm not familiar with TruffleRuby. But, other C-Ruby implementation can be handle to install C extension such as cool.io, msgpack-ruby and other gems?
If so, we should investigate how to support TruffleRuby.

**Comment by eregon** [comment]
Yes, TruffleRuby supports C extensions: https://github.com/oracle/truffleruby/blob/master/doc/user/compatibility.md
I ran the `one_forward` benchmark on it (by commenting out that line) and it seems to work fine.
I also ran the test suite and a good part passes but not everything.

**Comment by cosmo0920** [comment]
I'd confirmed that `truffleruby` can handle C extensions.
But some gems are still not working correctly.
We should investigate more about this issue.

**Comment by ashie** [comment]
Fixed by #3376

**Comment by eregon** [comment]
Thank you for the fix!
