### ISSUE TITLE
uninitialized constant Fluent::TailInput (NameError)

### ISSUE THREAD

**Issue by leanghychhay** [fluent/fluentd#3381]
Hello guy, I try to use my custom plugins for fluentd. I want to write an additional in_tail plugin feature. 
Here is the code I try:

```
root@test0044:/etc/td-agent/plugin# cat in_tail_asis_alternative.rb
# Fluent::AsisAlternativeInput
# Fluent::AsisParser
module Fluent

class AsisAlternativeInput < Fluent::TailInput
 Plugin.register_input('tail_asis_alternative', self)
 def initialize
 super
 @parser = nil
end

def configure(conf)
 super
 host = `hostname -f`.chomp
 @tag += '.' unless @tag.end_with?('.')
 @tag += host
end

def configure_parser(conf)
 @parser = AsisParser.new
 @parser.configure(conf)
end

end

class AsisParser
 include Configurable

 config_param :asis_key, :string, :default => 'message'

def parse(text)
 record = {}
 record[@asis_key] = text
 return Engine.now, record
end

end

end
```

```
root@test0044:/etc/td-agent/conf.d# cat syslog.conf
<source>
 @type tail_asis_alternative
 path /var/log/syslog
 pos_file /var/log/td-agent/pos/syslog.pos
 tag raw.syslog
</source>

<source>
 @type tail_asis_alternative
 path /var/log/bashlog
 pos_file /var/log/td-agent/pos/bashlog.pos
 tag raw.bashlog
</source>

<source>
 @type tail_asis_alternative
 path /var/log/auth.log
 pos_file /var/log/td-agent/pos/authlog.pos
 tag raw.authlog
</source>
```

**Comment by cosmo0920** [comment]
@leanghychhay Follow the issue template but your specified class is wrong. `Fluent::Plugin::TailInput` is correct.

**Comment by leanghychhay** [comment]
@cosmo0920 I try to change to Fluent::Plugin::TailInput but still the same error

```
module Fluent

class AsisAlternativeInput < Fluent::Plugin::TailInput
 Plugin.register_input('tail_asis_alternative', self)
 def initialize
 super
 @parser = nil
end

def configure(conf)
 super
 host = `hostname -f`.chomp
 @tag += '.' unless @tag.end_with?('.')
 @tag += host
end

def configure_parser(conf)
 @parser = AsisParser.new
 @parser.configure(conf)
end

end

class AsisParser
 include Configurable

 config_param :asis_key, :string, :default => 'message'

def parse(text)
 record = {}
 record[@asis_key] = text
 return Engine.now, record
end

end

end
```

My dry-run

```
Traceback (most recent call last):
	22: from /usr/sbin/td-agent:15:in `<main>'
	21: from /usr/sbin/td-agent:15:in `load'
	20: from /opt/td-agent/bin/fluentd:23:in `<top (required)>'
	19: from /opt/td-agent/bin/fluentd:23:in `load'
	18: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/bin/fluentd:8:in `<top (required)>'
	17: from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	16: from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	15: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/command/fluentd.rb:345:in `<top (required)>'
	14: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/supervisor.rb:648:in `run_supervisor'
	13: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/engine.rb:80:in `run_configure'
	12: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/engine.rb:105:in `configure'
	11: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/root_agent.rb:152:in `configure'
	10: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/root_agent.rb:152:in `each'
	 9: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/root_agent.rb:158:in `block in configure'
	 8: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/root_agent.rb:312:in `add_source'
	 7: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin.rb:105:in `new_input'
	 6: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin.rb:160:in `new_impl'
	 5: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/registry.rb:44:in `lookup'
	 4: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/registry.rb:68:in `search'
	 3: from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 2: from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 1: from /etc/td-agent/plugin/in_tail_asis_alternative.rb:1:in `<top (required)>'
/etc/td-agent/plugin/in_tail_asis_alternative.rb:3:in `<module:Fluent>': uninitialized constant Fluent::Plugin::TailInput (NameError)
```

**Comment by cosmo0920** [comment]
You shouldn't use closed issue.
And **please don't use issue tracker as community forum**.
_Read [CONTRIBUTION.md](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) carefully._
You should send your question into https://discuss.fluentd.org.
