### ISSUE TITLE
High CPU usage in flush thread

### ISSUE THREAD

**Issue by jiejieling** [fluent/fluentd#3387]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
   Our fluentd have a high cpu usage after run 2 days.  
   Use top to show the thread cpu info like this:
![image](https://user-images.githubusercontent.com/3351054/119291280-c4e35280-bc80-11eb-9865-f781857d2acd.png)

   And use strace to show the thread info like this:
![image](https://user-images.githubusercontent.com/3351054/119291337-ddec0380-bc80-11eb-9c32-3ebc0593fdde.png)

**To Reproduce**
None

**Expected behavior**
find and fix the problem

**Your Environment**

- Fluentd or td-agent version: 1.12.3
- Operating system: CentOS Linux release 7.7.1908 (Core)
- Kernel version: 3.10.0-1062.el7.x86_64 #1 SMP
- FLunetd run in K8s, k8s version: 1.16.4

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**
  Our fluentd output config :

```
<match metric.**>
    @type forward

    require_ack_response true
  
    <buffer>
        @type file
        path /data/var/fluentd/buffer/xxxx
        queue_limit_length 8192
        chunk_limit_size 4m

        flush_at_shutdown true
        flush_interval 3
        retry_forever true
        flush_thread_count 4
        overflow_action block
    
    </buffer>

    <server>
        host xxxxx
        port 24224
    </server>

</match>

<match tomcat.**>
    @type elasticsearch
    hosts xxxx
    user fluentd
    password fluentd
    reload_connections false
    request_timeout 60s

    logstash_prefix tomcat
    utc_index false
    logstash_format true
    include_tag_key true
    reload_on_failure true

    <buffer>
        @type file
        path /data/var/fluentd/buffer/xxx-es
        queue_limit_length 8192
        chunk_limit_size 4m

        flush_interval 3
        retry_forever true
        flush_thread_count 4
        overflow_action block
    </buffer>
</match>
```
**Your Error Log**
None

**Additional context**
   Check the buffer files , We found the tomcat tag buffer has be blocked, so I think the high cpu usage flush_thread_2 maybe is a tomcat tag flush thread.

**Comment by ashie** [comment]
Could you try to get a stack trace of the worker process?

```
$ kill -CONT <pid>
$ cat /tmp/sigdump-<pid>.log
```

**Comment by ashie** [comment]
Maybe same with #3382

**Comment by jiejieling** [comment]
[sigdump-33.log](https://github.com/fluent/fluentd/files/6529682/sigdump-33.log)

Is the flush_thread_2 thread  working for getting the ES host ?

**Comment by ashie** [comment]
```
  Thread #<Thread:0x0000562c82ebbf90@flush_thread_2 /srv/fluentd/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/thread.rb:70 run> status=run priority=0
      /srv/fluentd/lib/ruby/2.7.0/securerandom.rb:123:in `urandom'
      /srv/fluentd/lib/ruby/2.7.0/securerandom.rb:123:in `gen_random_urandom'
      /srv/fluentd/lib/ruby/2.7.0/securerandom.rb:73:in `bytes'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:606:in `random_number'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:606:in `random'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:625:in `block in allocate_request_id'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:622:in `synchronize'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:622:in `allocate_request_id'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:842:in `sender'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:527:in `block in fetch_resource'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:1124:in `block (3 levels) in resolv'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:1122:in `each'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:1122:in `block (2 levels) in resolv'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:1121:in `each'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:1121:in `block in resolv'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:1119:in `each'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:1119:in `resolv'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:521:in `fetch_resource'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:507:in `each_resource'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:402:in `each_address'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:116:in `block in each_address'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:115:in `each'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:115:in `each_address'
      /srv/fluentd/lib/ruby/2.7.0/resolv.rb:58:in `each_address'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/excon-0.81.0/lib/excon/socket.rb:110:in `connect'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/excon-0.81.0/lib/excon/socket.rb:49:in `initialize'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/excon-0.81.0/lib/excon/connection.rb:463:in `new'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/excon-0.81.0/lib/excon/connection.rb:463:in `socket'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/excon-0.81.0/lib/excon/connection.rb:118:in `request_call'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/excon-0.81.0/lib/excon/middlewares/mock.rb:57:in `request_call'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/excon-0.81.0/lib/excon/middlewares/instrumentor.rb:34:in `request_call'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/excon-0.81.0/lib/excon/middlewares/idempotent.rb:19:in `request_call'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/excon-0.81.0/lib/excon/middlewares/base.rb:22:in `request_call'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/excon-0.81.0/lib/excon/middlewares/base.rb:22:in `request_call'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/excon-0.81.0/lib/excon/connection.rb:273:in `request'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `block in call'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/faraday-1.4.1/lib/faraday/adapter.rb:55:in `connection'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `call'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/faraday-1.4.1/lib/faraday/rack_builder.rb:154:in `build_response'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/faraday-1.4.1/lib/faraday/connection.rb:492:in `run_request'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.12.0/lib/elasticsearch/transport/transport/http/faraday.rb:48:in `block in perform_request'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.12.0/lib/elasticsearch/transport/transport/base.rb:288:in `perform_request'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.12.0/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.12.0/lib/elasticsearch/transport/client.rb:191:in `perform_request'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/elasticsearch-api-7.12.0/lib/elasticsearch/api/actions/bulk.rb:69:in `bulk'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.3/lib/fluent/plugin/out_elasticsearch.rb:1062:in `send_bulk'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.3/lib/fluent/plugin/out_elasticsearch.rb:875:in `block in write'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.3/lib/fluent/plugin/out_elasticsearch.rb:874:in `each'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.3/lib/fluent/plugin/out_elasticsearch.rb:874:in `write'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/output.rb:1138:in `try_flush'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/output.rb:1450:in `flush_thread_run'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'
      /srv/fluentd/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by jiejieling** [comment]
I got it , it's the ruby securerandom  problem 
think u.

**Comment by ashie** [comment]
> I got it , it's the ruby securerandom problem

I'm not sure yet.
Could you describe the detail if you got it?

**Comment by ashie** [comment]
Hmm, something may pass a large size to `Random.random`.
I can reproduce the high CPU usage issue by this:
```
$ irb
irb(main):001:0> Random.urandom(2**31)
```

**Comment by jiejieling** [comment]
Sorry, I don't know why this is, but ruby 2.2.0(use OpenSSL::Random) in our env is ok,  I have trIed to rewrite the securerandom.rb with using OpenSSL::Random to fix this problem.

**Comment by ashie** [comment]
Hmm, interesting. Thanks!

**Comment by dzikismigol** [comment]
Problem lies somewhere in the `/usr/lib/ruby/2.7.0/resolv.rb`, pasted below. Ruby keeps generating random request IDs, probably because of a collision caused by (?) not calling `free_request_id`.

My workaround for now is to use `http_backend typhoeus` in the output configuration. Typhoeus handles persistent TCP connections and thus doesn't use DNS.

```rb
    603     if defined? SecureRandom
    604       def self.random(arg) # :nodoc:
    605         begin
    606           SecureRandom.random_number(arg)
    607         rescue NotImplementedError
    608           rand(arg)
    609         end
    610       end
    611     else
    612       def self.random(arg) # :nodoc:
    613         rand(arg)
    614       end
    615     end
    616 
    617     RequestID = {} # :nodoc:
    618     RequestIDMutex = Thread::Mutex.new # :nodoc:
    619 
    620     def self.allocate_request_id(host, port) # :nodoc:
    621       id = nil
    622       RequestIDMutex.synchronize {
    623         h = (RequestID[[host, port]] ||= {})
    624         begin
    625           id = random(0x0000..0xffff)
    626         end while h[id]
    627         h[id] = true
    628       }
    629       id
    630     end
    631 
    632     def self.free_request_id(host, port, id) # :nodoc:
    633       RequestIDMutex.synchronize {
    634         key = [host, port]
    635         if h = RequestID[key]
    636           h.delete id
    637           if h.empty?
    638             RequestID.delete key
    639           end
    640         end
    641       }
    642     end
```

**Comment by ashie** [comment]
> Problem lies somewhere in the /usr/lib/ruby/2.7.0/resolv.rb, pasted below. Ruby keeps generating random request IDs, probably because of a collision caused by (?) not calling free_request_id.

Thanks for the report.
I think https://github.com/ruby/resolv/pull/9 is the fix for it, please try resolv 0.2.1.

**Comment by jiejieling** [comment]
ok, I will try it

**Comment by ashie** [comment]
FYI: Probably `RUBYLIB=/path/to/resolve-0.2.1/lib` is required to force load it: https://github.com/fluent/fluentd-docker-image/pull/275

**Comment by jiejieling** [comment]
Hi, the resolv 0.2.1 is useful for us. Thanks
