### ISSUE TITLE
fluent-plugin-generate crashes during gemspec generation

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#3442]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
When I ran `fluent-plugin-generate` command to generate a skeleton plugin, it crashes with the output below:
```
$ fluent-plugin-generate input awesome
License: Apache-2.0
	create Gemfile
	create README.md
	create Rakefile
/Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/fluentd-1.13.1/lib/fluent/command/plugin_generator.rb:180:in `bundler_version': uninitialized constant FluentPluginGenerator::Bundler (NameError)
	from (erb):23:in `template'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/3.0.0/erb.rb:905:in `eval'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/3.0.0/erb.rb:905:in `result'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/fluentd-1.13.1/lib/fluent/command/plugin_generator.rb:80:in `template'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/fluentd-1.13.1/lib/fluent/command/plugin_generator.rb:53:in `block (2 levels) in call'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/3.0.0/pathname.rb:571:in `block in find'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/3.0.0/find.rb:49:in `block (2 levels) in find'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/3.0.0/find.rb:48:in `catch'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/3.0.0/find.rb:48:in `block in find'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/3.0.0/find.rb:43:in `each'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/3.0.0/find.rb:43:in `find'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/3.0.0/pathname.rb:571:in `find'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/fluentd-1.13.1/lib/fluent/command/plugin_generator.rb:45:in `block in call'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/fluentd-1.13.1/lib/fluent/command/plugin_generator.rb:43:in `chdir'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/fluentd-1.13.1/lib/fluent/command/plugin_generator.rb:43:in `call'
	from /Users/tagomoris/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/fluentd-1.13.1/bin/fluent-plugin-generate:5:in `<top (required)>'
	from /Users/tagomoris/.rbenv/versions/3.0.0/bin/fluent-plugin-generate:23:in `load'
	from /Users/tagomoris/.rbenv/versions/3.0.0/bin/fluent-plugin-generate:23:in `<main>'
```

It seems a failure during generating a gemspec file (according to the order of [the sample output in the doc](https://docs.fluentd.org/plugin-development#generating-plugin-project-skeleton)).

**To Reproduce**
Run `fluent-plugin-generate input awesome`.

**Expected behavior**
It finishes successfully, without errors.

**Your Environment**
- Fluentd 1.13.1
- macOS Big Sur (11.4)
- Ruby 3.0.0 (and 2.7.3 too)

**Your Configuration**
Nothing.

**Your Error Log**
See above.

**Comment by ashie** [comment]
I've confirmed it.
Could you take a look? @kenhys

**Comment by kenhys** [comment]
Hmm, it assumed existence of .lock file.
