### ISSUE TITLE
Field extracted using record_transformer is not accessible in output plugin

### ISSUE THREAD

**Issue by jasoninmel** [fluent/fluentd#3496]
### Describe the bug

Unable to use a field added in the using record_transformer in the output plugin.

In the fluentd documentation regarding [embedded ruby code](https://docs.fluentd.org/configuration/config-file#embedded-ruby-code) it is shown accessing field values with #{...} expression. However this is not working in the configuration I have built. 

Is this a known issue in a specific version of fluentd ?

### To Reproduce

1. Create a custom field using record transformer 
2. Use field in output plugin using #{...} expression.

### Expected behavior

File name to be "/var/fluent/log/log/default-data.b5cad72eb203cf02944432cd5d2fdf69b.log" where default namespace to be extracted from x_namespace_name field.

### Your Environment

```markdown
- Fluentd version:fluentd-1.3.2
- TD Agent version: 
- Operating system: Linux version 3.10.0-1127.19.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Tue Aug 25 17:23:54 UTC 2020
- Kernel version: 3.10.0-1127.19.1.el7.x86_64

Versions:  ruby="2.5.8" (This is the version picked up by Docker config when use fluent/fluentd:latest)
```

### Your Configuration

Create a field using record transformer

```
<filter kubernetes.**>
  @type record_transformer
  enable_ruby true
  <record>
    x_namespace_name ${record['kubernetes']['namespace_name']}
  </record>
</filter>
```

Use field in output plugin.

```
<match kubernetes.**>
  @type file
  @id   output1
  path         "/var/fluent/log/log/#{x_namespace_name}-data.*.log"
  append       true
</match>
```

### Your Error Log

```shell
/usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/config/literal_parser.rb:171:in `instance_eval': undefined local variable or method `x_namespace_name' for #<Binding:0x0000555912f89128> (NameError)
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/config/literal_parser.rb:171:in `instance_eval'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/config/literal_parser.rb:171:in `eval_embedded_code'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/config/literal_parser.rb:93:in `scan_double_quoted_string'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/config/literal_parser.rb:72:in `scan_string'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/config/literal_parser.rb:65:in `parse_literal'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/config/v1_parser.rb:130:in `parse_element'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/config/v1_parser.rb:95:in `parse_element'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/config/v1_parser.rb:43:in `parse!'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/config/v1_parser.rb:33:in `parse'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/config.rb:39:in `parse'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/supervisor.rb:766:in `read_config'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/supervisor.rb:477:in `run_supervisor'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/bin/fluentd:8:in `<top (required)>'
	from /usr/bin/fluentd:23:in `load'
	from /usr/bin/fluentd:23:in `<main>'
```

### Additional context

I'm running FluentD in Kind Kubernetes cluster. I'm using following Dockerfile to build the fluentD image.

```
FROM fluent/fluentd:latest

# Use root account to use apk
USER root

# below RUN includes plugin as examples elasticsearch is not required
# # you may customize including plugins as you wish
RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install fluent-plugin-kubernetes_metadata_filter \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install fluent-plugin-json-in-json-2 \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

COPY fluent.conf /fluentd/etc/
COPY entrypoint.sh /bin/

RUN mkdir -p /var/fluent/log
RUN chmod 777 /var/fluent/log
```

**Comment by kenhys** [comment]
As x_namespace_name is a field in a record, use `${x_namespace_name}` in match section.


```
<match kubernetes.**>
  @type file
  @id   output1
  path         "/var/fluent/log/log/${x_namespace_name}-data.*.log"
  append       true
</match>
```

See https://docs.fluentd.org/output/file#path

**Comment by jasoninmel** [comment]
I have tried that but get following error;

```
2021-09-01 04:56:34 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2021-09-01 04:56:35 +0000 [warn]: !! The environment variable 'K8S_NODE_NAME' is not set to the node name which can affect the API server and watch efficiency !!
2021-09-01 04:56:35 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Parameter 'path: /var/fluent/log/log/${x_namespace_name}-data.%Y%m%d.log' has placeholders, but chunk keys doesn't have keys x_namespace_name"
```

**Comment by kenhys** [comment]
Ah, as the error log says, when using placeholder in path, put it in  chunk keys.
something like this:

```
<match kubernetes.**>

  path         "/var/fluent/log/log/${x_namespace_name}-data.*.log"
  <buffer x_namespace_name>
    ...
  </buffer>
</match>
```

**Comment by jasoninmel** [comment]
Thanks @kenhys . Here is my updated configuration of the output plugin.

```
<match kubernetes.**>
  @type file
  @id   output1
  path         "/var/fluent/log/log/${x_namespace_name}-data.*.log"
  append       true
  <buffer x_namespace_name>
    timekey 5s
    flush_interval 5s
  </buffer>
</match>
```

I'm getting the following error;

`/usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.2/lib/fluent/plugin/out_file.rb:277:in `generate_path_template': BUG: configuration error must be raised for path including '*' without timekey (RuntimeError)`

**Comment by kenhys** [comment]
Oh, try without '*'. ` path         "/var/fluent/log/log/${x_namespace_name}-data.log"`

**Comment by jasoninmel** [comment]
Thanks @kenhys. Now it's working. There is one directory still get created with the fieldname which I'm not sure why but rest of the logs get created with namespace name as expected. However there seems to be slow due to buffering. Is that expected?

**Comment by jasoninmel** [comment]
hey @kenhys , is it possible to use kubernetes meta-data directly in the output configuration without adding a custom field? For example, can I use ${record['kubernetes']['namespace_name']} in match section ?
