### ISSUE TITLE
Memory issues probably related to too many open files

### ISSUE THREAD

**Issue by LukasJerabek** [fluent/fluentd#3620]
### Describe the bug

Until recently we have used fluentd only to aggregate logs on our production server from all apps into one file and notify on slack based on severity. Later we added new monitoring server which is accepting nginx metrics forwarded from production fluentd (flushed every 10 seconds, 8 tags, only approx 10-50 of log records in total) and monitoring fluentd saves them into postgres database. Around Christmas I added self monitoring of resources on monitoring server resulting in configs below. I have made sure everything is set as here https://docs.fluentd.org/installation/before-install.

Once I set up getting data for memory metrics I noticed it consumes a lot of memory and I thought its quite much for fluentd to ask for so much memory. Because data comes from sources and goes to matches and no buffer files were created (or really only few temprorary), so why would memory keep rising for 8 hours...

![2 5 9](https://user-images.githubusercontent.com/55019231/152753656-d22a5ad5-1a05-4503-b2a3-6d8349fda6da.png)

That was when I was using ruby 2.5.9 on monitoring server, so I tried new versions, since I new we have ruby 2.7.5. on production. This is with version 2.7.4.

![2 7 4](https://user-images.githubusercontent.com/55019231/152754240-d3e96c2c-dc6d-4ed5-a37e-3b62338b8958.png)

As you can see it didnt let the app into swap that much and there are these weired 15 minutes - 1 hour intervals where memory got cleaned and the exec input plugin apparently didnt work at all,because those are lines connecting data before and after memory clean are not actual data, its empty there. However, the part where the nginx logs are handled was working during that time, so probably only in_exec plugin was out of order. So I have tried ruby 3.0.2

![3 0 2](https://user-images.githubusercontent.com/55019231/152756181-7f86f02a-2b04-40df-9829-bee89fbe93d3.png)

There on blue lines around 02/03 12:00 those lines are when I have tried RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=0.9
and the second one is using jemalloc - did not helped as well. The single line after that is adding RUBY_GC_MALLOC_LIMIT_MAX=8000000, RUBY_GC_OLDMALLOC_LIMIT_MAX=8000000, which was just plain guess.

Thats when I noticed these logs on screenshot - I have put them below in error section. I have also checked that OOM killer is not the one who does this (no logs in journalctl).

After that I came back to 2.5.9 with jemalloc
![bakc to 2 5 9](https://user-images.githubusercontent.com/55019231/152757163-ae5cf4d5-1591-467b-a22b-79c5290ab9b4.png)

first blue line is when I removed jemalloc - obviously jemalloc wasnt helping at all.
second line is removing RUBY_GC_MALLOC_LIMIT_MAX=8000000 RUBY_GC_OLDMALLOC_LIMIT_MAX=8000000
third is just a detail, I removed logrotation parameter from command line.
But at the end I started getting these errors in fluentd.log in quotes (not in screenshot) - I have put them below in error section.

So it seems that I will also get eventually these errors with 2.5.9, but the memory at least stabilizes for a while before that.

### To Reproduce

This is to motivate to futher exploring these issues, apparently fluentd does something weird with newer Ruby versions. I have noticed none of the issues about memory leaks say what ruby version they use.

### Expected behavior

- Fluentd should be efficient with newer versions of Ruby at least as before, or it should be updated in documention, currently it says it is compatible with ruby >=2.4.
- When fluentd is set according to documentation, it should not have too many open files problems.
- I am also hoping for some tips how to investigate more, since I obviously cant try every ruby GC parameter, ruby version, ...alloc options, also I dont know if the measuring resources causes this, since if I remove it, I wont have the info if it worked. 

### Your Environment

```markdown
- Fluentd version: 1.14.4 (installed as gem)
- TD Agent version: - 
- Operating system: Rocky linux 8
- Kernel version: 4.18.0-348.12.2.el8_5.x86_64
```

### Your Configuration

```apache
Systemd:
[Unit]
Description=Fluentd Service
After=network.target
StartLimitIntervalSec=0

[Service]
User={{ user }} 
Group={{ user }}
WorkingDirectory={{ home }}/
Environment="PATH={{ home }}/bin:/usr/bin"
ExecStart=/bin/sh {{ home }}/bin/fluentd-starter.sh
PrivateTmp=true
LimitAS=infinity
LimitRSS=infinity
LimitNOFILE=65536
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target

starter script:
#!/bin/sh
exec 2>&1
export GEM_PATH={{ home }}/.gem/ruby:${GEM_PATH}
exec {{ home }}/bin/fluentd _{{ fluentd_version }}_ -o {{ home }}/log/fluentd.log -c {{ home }}/config/fluentd/fluentd.conf -vv

fluentd.conf:
<system>
  process_name fluentd_monitor
</system>

@include fluentd_roger_nginx_metrics.conf
@include fluentd_monitor_resource_metrics.conf

fluentd_roger_nginx_metrics.conf:
<source>
  @type forward
  port 24224
  bind 0.0.0.0
  <transport tls>
    cert_path /etc/fluentd/certs/monitor_fluentd.crt
    private_key_path /etc/fluentd/certs/monitor_fluentd.key
    client_cert_auth true
    ca_path /etc/fluentd/certs/prod_fluentd.crt
  </transport>
</source>

<match nginx.status.api>
  @type exec
  command {{ home }}/config/fluentd/plugin/psql_nginx_status_metrics.sh {{ roger_db_roger_user_conn_string.stdout }} nginx_api_stub_status
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields active_connections,accepts,handled,requests,reading,writing,waiting,time_local
  </format>
  <buffer time>
    @type file
    path {{ home }}/log/fluentd/nginx.status.api.buff
    timekey 10s
    timekey_wait 0s
    flush_mode lazy
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/log/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>

<match nginx.status.infin>
  @type exec
  command {{ home }}/config/fluentd/plugin/psql_nginx_status_metrics.sh {{ roger_db_roger_user_conn_string.stdout }} nginx_infin_stub_status
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields active_connections,accepts,handled,requests,reading,writing,waiting,time_local
  </format>
  <buffer time>
    @type file
    path {{ home }}/log/fluentd/nginx.status.infin.buff
    timekey 10s
    timekey_wait 0s
    flush_mode lazy
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/log/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>

<match nginx.status.aukce>
  @type exec
  command {{ home }}/config/fluentd/plugin/psql_nginx_status_metrics.sh {{ roger_db_roger_user_conn_string.stdout }} nginx_aukce_stub_status
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields active_connections,accepts,handled,requests,reading,writing,waiting,time_local
  </format>
  <buffer time>
    @type file
    path {{ home }}/log/fluentd/nginx.status.aukce.buff
    timekey 10s
    timekey_wait 0s
    flush_mode lazy
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/log/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>

<match nginx.status.platba>
  @type exec
  command {{ home }}/config/fluentd/plugin/psql_nginx_status_metrics.sh {{ roger_db_roger_user_conn_string.stdout }} nginx_platba_stub_status
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields active_connections,accepts,handled,requests,reading,writing,waiting,time_local
  </format>
  <buffer time>
    @type file
    path {{ home }}/log/fluentd/nginx.status.platba.buff
    timekey 10s
    timekey_wait 0s
    flush_mode lazy
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/log/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>

<match nginx.access_log.api>
  @type exec
  command {{ home }}/config/fluentd/plugin/psql_nginx_access_log.sh {{ roger_db_roger_user_conn_string.stdout }} nginx_api_access_log
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields remote_addr,remote_user,time_local,request_type,request_path,status,body_bytes_sent,http_referer,http_user_agent,http_x_forwarded_for,host,server_name,request_time,upstream_addr,upstream_status,upstream_response_time,upstream_response_length,upstream_cache_status
  </format>
  <buffer time>
    @type file
    path {{ home }}/log/fluentd/nginx.access_log.api.buff
    timekey 10s
    timekey_wait 0s
    flush_mode lazy
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/log/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>

<match nginx.access_log.aukce>
  @type exec
  command {{ home }}/config/fluentd/plugin/psql_nginx_access_log.sh {{ roger_db_roger_user_conn_string.stdout }} nginx_aukce_access_log
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields remote_addr,remote_user,time_local,request_type,request_path,status,body_bytes_sent,http_referer,http_user_agent,http_x_forwarded_for,host,server_name,request_time,upstream_addr,upstream_status,upstream_response_time,upstream_response_length,upstream_cache_status
  </format>
  <buffer time>
    @type file
    path {{ home }}/log/fluentd/nginx.access_log.aukce.buff
    timekey 10s
    timekey_wait 0s
    flush_mode lazy
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/log/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>

<match nginx.access_log.infin>
  @type exec
  command {{ home }}/config/fluentd/plugin/psql_nginx_access_log.sh {{ roger_db_roger_user_conn_string.stdout }} nginx_infin_access_log
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields remote_addr,remote_user,time_local,request_type,request_path,status,body_bytes_sent,http_referer,http_user_agent,http_x_forwarded_for,host,server_name,request_time,upstream_addr,upstream_status,upstream_response_time,upstream_response_length,upstream_cache_status
  </format>
  <buffer time>
    @type file
    path {{ home }}/log/fluentd/nginx.access_log.infin.buff
    timekey 10s
    timekey_wait 0s
    flush_mode lazy
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/log/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>

<match nginx.access_log.platba>
  @type exec
  command {{ home }}/config/fluentd/plugin/psql_nginx_access_log.sh {{ roger_db_roger_user_conn_string.stdout }} nginx_platba_access_log
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields remote_addr,remote_user,time_local,request_type,request_path,status,body_bytes_sent,http_referer,http_user_agent,http_x_forwarded_for,host,server_name,request_time,upstream_addr,upstream_status,upstream_response_time,upstream_response_length,upstream_cache_status
  </format>
  <buffer time>
    @type file
    path {{ home }}/log/fluentd/nginx.access_log.platba.buff
    timekey 10s
    timekey_wait 0s
    flush_mode lazy
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/log/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>

fluentd_monitor_resource_metrics.conf:
<source>
  @type exec
  tag hardware.cpu_saturation
  run_interval 1m
  command {{ home }}/config/fluentd/plugin/get_cpu_saturation_metrics.sh
  <parse>
    @type json
    types avg_load_1:float,avg_load_5:float,avg_load_15:float
  </parse>
</source>

<source>
  @type exec
  tag hardware.cpu_utilization
  run_interval 1s
  command {{ home }}/config/fluentd/plugin/get_cpu_utilization_metrics.sh
  <parse>
    @type json
    types usr:float,nice:float,sys:float,iowait:float,irq:float,soft:float,steal:float,guest:float,gnice:float,idle:float
  </parse>
</source>

<source>
  @type exec
  tag hardware.memory
  run_interval 1s
  command {{ home }}/config/fluentd/plugin/get_memory_metrics.sh
  <parse>
    @type json
    types mem_available:float,swap_total:float,swap_free:float
  </parse>
</source>

<source>
  @type exec
  tag hardware.disk
  run_interval 30m
  command {{ home }}/config/fluentd/plugin/get_disk_metrics.sh
  <parse>
    @type json
    types space_used:float
  </parse>
</source>

<filter hardware.*>
  @type record_transformer
  enable_ruby
  <record>
    time_local ${time.strftime('%Y-%m-%dT%H:%M:%S%z')}
  </record>
</filter>

<match hardware.cpu_saturation>
  @type exec
  command {{ home }}/config/fluentd/plugin/psql_cpu_saturation.sh {{ monitor_db_monitor_user_conn_string.stdout }} cpu_saturation
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields time_local,avg_load_1,avg_load_5,avg_load_15
  </format>
  <buffer tag>
    @type file
    path {{ home }}/log/fluentd/hardware.cpu_saturation.buff
    flush_mode immediate
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/log/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>

<match hardware.cpu_utilization>
  @type exec
  command {{ home }}/config/fluentd/plugin/psql_cpu_utilization.sh {{ monitor_db_monitor_user_conn_string.stdout }} cpu_utilization
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields time_local,usr,nice,sys,iowait,irq,soft,steal,guest,gnice,idle
  </format>
  <buffer time>
    @type file
    path {{ home }}/log/fluentd/hardware.cpu_utilization.buff
    timekey 10s
    timekey_wait 0s
    flush_mode lazy
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/log/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>

<match hardware.memory>
  @type exec
  command {{ home }}/config/fluentd/plugin/psql_memory.sh {{ monitor_db_monitor_user_conn_string.stdout }} memory
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields time_local,mem_available,swap_total,swap_free
  </format>
  <buffer time>
    @type file
    path {{ home }}/log/fluentd/hardware.memory.buff
    timekey 10s
    timekey_wait 0s
    flush_mode lazy
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/log/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>

<match hardware.disk>
  @type exec
  command {{ home }}/config/fluentd/plugin/psql_disk.sh {{ monitor_db_monitor_user_conn_string.stdout }} disk
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields time_local,space_used
  </format>
  <buffer tag>
    @type file
    path {{ home }}/log/fluentd/hardware.disk.buff
    flush_mode immediate
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/log/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>
```

### Your Error Log

```shell
![errors](https://user-images.githubusercontent.com/55019231/152758271-ce24a0bf-f517-4c4e-afe4-c9c0adc6de12.png)


2022-02-07 08:47:50 +0100 [warn]: #0 fluent/log.rb:351:warn: failed to flush the buffer. retry_times=0 next_retry_time=2022-02-07 08:47:52 +0100 chunk="5d76889e6da581696844bc759a1e319e" error_class=Errno
::EMFILE error="Too many open files"
.
.
.
2022-02-07 08:47:52 +0100 [error]: #0 fluent/log.rb:372:error: Unexpected error raised. Stopping the timer. title=:child_process_execute error_class=Errno::EMFILE error="Too many open files - /dev/null"
  2022-02-07 08:47:52 +0100 [error]: #0 cool.io/loop.rb:88:run: /usr/share/ruby/open3.rb:199:in `spawn'
  2022-02-07 08:47:52 +0100 [error]: #0 cool.io/loop.rb:88:run: /usr/share/ruby/open3.rb:199:in `popen_run'
  2022-02-07 08:47:52 +0100 [error]: #0 cool.io/loop.rb:88:run: /usr/share/ruby/open3.rb:147:in `popen2'
  2022-02-07 08:47:52 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/child_process.rb:265:in `child_process_execute_once'
  2022-02-07 08:47:52 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/child_process.rb:96:in `block in child_process_execute'
  2022-02-07 08:47:52 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/child_process.rb:114:in `block in child_process_execute'
  2022-02-07 08:47:52 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2022-02-07 08:47:52 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2022-02-07 08:47:52 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2022-02-07 08:47:52 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2022-02-07 08:47:52 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2022-02-07 08:47:52 +0100 [error]: #0 fluent/log.rb:372:error: Timer detached. title=:child_process_execute

```
```


### Additional context

The scripts which fluentd uses 
get_cpu_saturation_metrics.sh
```
#!/bin/sh
avg_load="$(cut -d ' ' -f 1,2,3 < /proc/loadavg)"
read -r avg_load_1 avg_load_5 avg_load_15 <<<"${avg_load}"

printf '{"avg_load_1":"%s","avg_load_5":"%s","avg_load_15":"%s"}' \
"$avg_load_1" \
"$avg_load_5" \
"$avg_load_15" \

```
get_cpu_utilization_metrics.sh
```
#!/bin/sh
utilization=$(mpstat | grep all | awk '{ \
    print $4 " " $5 " " $6 " " $7 " " $8 " " $9 " "$10 " " $11 " " $12 " " $12; \
    exit}')
read -r usr nice sys iowait irq soft steal guest gnice idle <<<"${utilization}"

printf '{"usr":"%s","nice":"%s","sys":"%s","iowait":"%s","irq":"%s","soft":"%s","steal":"%s","guest":"%s","gnice":"%s","idle":"%s"}' \
"$usr" \
"$nice" \
"$sys" \
"$iowait" \
"$irq" \
"$soft" \
"$steal" \
"$guest" \
"$gnice" \
"$idle" \
```

get_disk_metrics.sh
```
#!/bin/sh
space_used=$(df | grep /$ | awk '{printf "%.3f", $3/1024/1024;exit}')

printf '{"space_used":"%s"}' "$space_used"
```

get_memory_metrics.sh
```
#!/bin/sh
space_used=$(df | grep /$ | awk '{printf "%.3f", $3/1024/1024;exit}')

printf '{"space_used":"%s"}' "$space_used"
```

scripts starting "psql_" are all analogic, the just ose different table names:
```
#!/bin/sh
exec /usr/bin/psql "$1?sslmode=disable" -c "\copy $2 (table_first,table_second) FROM '$3' DELIMITER '|';"
```

**Comment by LukasJerabek** [comment]
So now its the time when memory starts swapping, when I check ls /proc/<fluentd PID>/fd/ it askes Display all 36181 possibilities? (y or n). What is wrong with my setup? Is something wrong with fluentd, or is it the scripts?

**Comment by LukasJerabek** [comment]
So I have tried to let it be for longer time without restart on 2.5.9 version and memory cleaning happened as well also with in_exec not providing any data for an hour or so.

![2 5 9  longer](https://user-images.githubusercontent.com/55019231/152943579-111855bc-1bad-462e-8dca-f58945747e66.png)


and there was these logs in fluentd.log
```
2022-02-08 01:02:51 +0100 [warn]: #0 fluent/log.rb:351:warn: failed to flush the buffer. retry_times=0 next_retry_time=2022-02-08 01:02:52 +0100 chunk="5d77636e2b4efd9453d98c86eff8f62c" error_class=IOError error="closed stream"
  2022-02-08 01:02:52 +0100 [warn]: #0 plugin/output.rb:1235:rescue in try_flush: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin/buffer/file_chunk.rb:170:in `seek'
  2022-02-08 01:02:52 +0100 [warn]: #0 plugin/output.rb:1235:rescue in try_flush: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin/buffer/file_chunk.rb:170:in `open'
  2022-02-08 01:02:52 +0100 [warn]: #0 plugin/output.rb:1235:rescue in try_flush: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin/buffer/chunk.rb:179:in `write_to'
  2022-02-08 01:02:52 +0100 [warn]: #0 plugin/output.rb:1235:rescue in try_flush: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin/out_secondary_file.rb:80:in `block in write'
  2022-02-08 01:02:52 +0100 [warn]: #0 plugin/output.rb:1235:rescue in try_flush: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin/out_secondary_file.rb:78:in `open'
  2022-02-08 01:02:52 +0100 [warn]: #0 plugin/output.rb:1235:rescue in try_flush: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin/out_secondary_file.rb:78:in `write'
  2022-02-08 01:02:52 +0100 [warn]: #0 plugin/output.rb:1235:rescue in try_flush: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin/output.rb:1179:in `try_flush'
  2022-02-08 01:02:52 +0100 [warn]: #0 plugin/output.rb:1235:rescue in try_flush: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin/output.rb:1491:in `flush_thread_run'
  2022-02-08 01:02:52 +0100 [warn]: #0 plugin/output.rb:1235:rescue in try_flush: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin/output.rb:499:in `block (2 levels) in start'
  2022-02-08 01:02:52 +0100 [warn]: #0 plugin/output.rb:1235:rescue in try_flush: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
...
2022-02-08 01:02:52 +0100 [warn]: #0 fluent/log.rb:351:warn: previous child process is still running. skipped. title=:exec_input command="/home/monitor/config/fluentd/plugin/get_memory_metrics.sh" arguments=nil interval=1 parallel=false
2022-02-08 01:02:52 +0100 [warn]: #0 fluent/log.rb:351:warn: previous child process is still running. skipped. title=:exec_input command="/home/monitor/config/fluentd/plugin/get_cpu_utilization_metrics.sh" arguments=nil interval=1 parallel=false
...
2022-02-08 01:18:53 +0100 [error]: #0 fluent/log.rb:372:error: Unexpected error raised. Stopping the timer. title=:child_process_execute error_class=Errno::EMFILE error="Too many open files"
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /usr/share/ruby/open3.rb:144:in `pipe'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /usr/share/ruby/open3.rb:144:in `popen2'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/child_process.rb:265:in `child_process_execute_once'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/child_process.rb:96:in `block in child_process_execute'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/child_process.rb:114:in `block in child_process_execute'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2022-02-08 01:18:53 +0100 [error]: #0 fluent/log.rb:372:error: Unexpected error raised. Stopping the timer. title=:child_process_execute error_class=Errno::EMFILE error="Too many open files"
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /usr/share/ruby/open3.rb:140:in `pipe'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /usr/share/ruby/open3.rb:140:in `popen2'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/child_process.rb:265:in `child_process_execute_once'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/child_process.rb:96:in `block in child_process_execute'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/child_process.rb:114:in `block in child_process_execute'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2022-02-08 01:18:53 +0100 [error]: #0 cool.io/loop.rb:88:run: /home/monitor/.gem/ruby/gems/fluentd-1.14.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2022-02-08 01:18:53 +0100 [error]: #0 fluent/log.rb:372:error: Timer detached. title=:child_process_execute
```

**Comment by LukasJerabek** [comment]
Could this be "file descriptors" leak? 
https://stackoverflow.com/questions/13354948/does-using-the-ruby-file-class-without-closing-leak-memory
https://github.com/jruby/jruby/issues/221
I know these are old and may not be relevant anymore, but the idea of not relying on GC might still be relevant.

**Comment by LukasJerabek** [comment]
So when I noticed the file descriptors rising infinitely I could narrow the problem and try different configurations while checking their behaviour. I think it would not stand out here and I will open new issue without the bloat around. Ruby was a wrong leed I got onto since I noticed difference in different versions, but I think it was just different handling of one core problem.

**Comment by LukasJerabek** [comment]
So when I noticed the file descriptors rising infinitely I could narrow the problem and try different configurations while checking their behaviour. I think it would not stand out here and I will open new issue without the bloat around. Ruby was a wrong leed I got onto since I noticed difference in different versions, but I think it was just different handling of one core problem.
