### ISSUE TITLE
Getting failure undefined method 'add' for nil:NilClass, when are trying to upgrading the fluentd image version from "v1.11.5-debian-1.0" to "v1.14.5-debian-1.0"

### ISSUE THREAD

**Issue by janmesh81** [fluent/fluentd#3655]
### Describe the bug

We are trying to upgrade the fluentd image version from "v1.11.5-debian-1.0" to "v1.14.5-debian-1.0" which breaks the working configuration. After upgrading, fluentd is failing with error undefined method 'add' for nil:NilClass error in  'measure_metrics' method of **filter.rb**. 
From investigation it seems like, **@emit_records_metrics** variable used in **measure_metrics** method is not initialized. So, invoking **add** method on uninitialized object is resulting in to this failure. 

### To Reproduce

Configure a pipeline with a filter plugin (e.g. json_transform) where configure method is overridden without invoking super. 
e.g.
<filter tag>
        @type json_transform
        transform_script flatten
</filter>

### Expected behavior

Fluentd shouldn't result in error, it should work without error. Like it was working till v1.11.5 in our case.

### Your Environment

```markdown
- Fluentd version: fluentd 1.14.5
- TD Agent version: NA
- Operating system:
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- Kernel version:3.10.0-1160.11.1.el7.x86_64
```

### Your Configuration

```apache
<source>
	@type tail
    tag test
    path /fluentd/log/applog/test_file.json
	read_from_head true
	pos_file /fluentd/log/applog/test_file.pos
	follow_inodes true
	refresh_interval 2
	enable_stat_watcher false
	from_encoding UTF-8
	encoding UTF-8
</source>

<filter test>
	@type json_transform
	transform_script flatten
</filter>

<match test>
	@type copy
	<store>
        	@type file
        	path /fluentd/log/applog/out/${tag}
        	<format>
            		@type json
        	</format>
        	add_path_suffix true
        	path_suffix .json
        	append true
        	<buffer tag>
                	@type file
                	flush_mode immediate
              		path /fluentd/log/applog/out//buffer_store
                	timekey 0s
                	timekey_wait 0s
        	</buffer>
	</store>
</match>
```

### Your Error Log

```shell
Below logs are captured by adding a logger statement in event_router.rb at line# 231
$log.info "Exception message is ::: #{e.message}, stacktrace is :: #{e.backtrace.inspect}"

Outcome of log statement: 
 #0 Exception message is ::: undefined method `add' for nil:NilClass, stacktrace is :: 
 ["/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/filter.rb:70:in `measure_metrics'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/event_router.rb:229:in `block (3 levels) in optimized_filter_stream'",
 "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/event_router.rb:216:in `each'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/event_router.rb:216:in `block (2 levels) in optimized_filter_stream'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/event_router.rb:215:in `catch'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/event_router.rb:215:in `block in optimized_filter_stream'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/event.rb:196:in `block in each'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/event.rb:195:in `each'", 
 "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/event.rb:195:in`each'", 
 "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/event_router.rb:211:in `optimized_filter_stream'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/event_router.rb:197:in `filter_stream'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/event_router.rb:180:in `emit_events'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/event_router.rb:115:in `emit_stream'", 
 "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:615:in `receive_lines'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:1089:in `block in handle_notify'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:1125:in `with_io'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:1058:in `handle_notify'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:1001:in `block in on_notify'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:1001:in `synchronize'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:1001:in `on_notify'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:816:in `on_notify'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:446:in `construct_watcher'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:457:in `block in start_watchers'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:456:in `each_value'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:456:in `start_watchers'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:386:in `refresh_watchers'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/plugin/in_tail.rb:256:in `start'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:203:in `block in start'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:191:in `each'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:191:in `block in lifecycle'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:178:in `each'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:178:in `lifecycle'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:202:in `start'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/engine.rb:248:in`start'",
 "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/engine.rb:147:in `run'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:717:in`block in run_worker'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:968:in `main_process'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:708:in `run_worker'", "/usr/local/bundle/gems/fluentd-1.14.5/lib/fluent/command/fluentd.rb:372:in `<top (required)>'", "/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'", "/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in`require'", "/usr/local/bundle/gems/fluentd-1.14.5/bin/fluentd:15:in`<top(required)>'", 
 "/usr/local/bundle/bin/fluentd:23:in `load'", 
 "/usr/local/bundle/bin/fluentd:23:in `<main>'"]
```

### Additional context

This failure will be applicable for all the filter plugins where configure method is overridden and super is not called from the configure method of plugin class. 

e.g. Below is the code snippet of configure method from filter_json_transform.rb

def configure(conf)
      @transform_script = conf['transform_script']
      if DEFAULTS.include?(@transform_script)
        @transform_script = "#{__dir__}/../../transform/#{@transform_script}.rb"
      elsif @transform_script == 'custom'
        @transform_script = conf['script_path']
      end

      require @transform_script
      @transformer = JSONTransformer.new
    end

In measure_metrics method of fiter.rb, like @emit_size_metrics.add is protected by @enable_size_metrics flag. 
@emit_records_metrics.add should be protected by a null check. 
Working code snippet below:

def measure_metrics(es)
        @emit_records_metrics.add(es.size) **if !@emit_records_metrics.nil?**
        @emit_size_metrics.add(es.to_msgpack_stream.bytesize) if @enable_size_metrics
      end

**Comment by ashie** [comment]
> Configure a pipeline with a filter plugin (e.g. json_transform) where configure method is overridden without invoking super.

Plugins have to call `super` if they override `configure` method, we don't guarantee that a plugin which doesn't call `super` work correctly .
https://docs.fluentd.org/plugin-development/api-plugin-base#configure-conf

So that it's fluent-plugin-json-transformer's issue.
