### ISSUE TITLE
RegexpError unmatched range specifier in char-class regression

### ISSUE THREAD

**Issue by d33psky** [fluent/fluentd#3675]
### Describe the bug

(old) fluentd 1.4.0 supports this config : 
```(?<backend_server>[\w-<>]+)```
whereas version 1.14.3 refuses the ```<>``` part and throws
```/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/config/types.rb:87:in `initialize': unmatched range specifier in char-class``` `(RegexpError)`

### To Reproduce

have a file like /etc/td-agent/conf.d/20-source-haproxy.conf
```
<source>
  type tail
  path /var/log/haproxy.log
  tag haproxy
  pos_file /var/log/td-agent/tmp/haproxy.log.pos
  format /^\w+[ ]+\d+ \d+:\d+:\d+ [^ ]+ (?<ps>(\w|-)+)\[(?<pid>\d+)\]: (?<remote_address>[\w\.]+):(?<client_port>\d+) \[(?<time>.+)\] (?<frontend>[\w-]+) (?<backend>[\w-]+)\/(?<backend_server>[\w-<>]+) (?<time_queue>-?\d+)\/(?<time_wait>-?\d+)\/(?<time_connect>-?\d+)\/(?<time_response>-?\d+)\/(?<total_time>-?\d+) (?<http_status>\d+) (?<body_bytes_sent>\d+) (?:(?<request_cookie>[^ ]{2,})|(?<request_cookie>[^-^ ]{1})|-) (?:(?<response_cookie>[^ ]{2,})|(?<response_cookie>[^-^ ]{1})|-) (?<termination_state>[^ ]+) (?<active_conn>\d+)\/(?<frontend_conn>\d+)\/(?<backend_conn>\d+)\/(?<server_conn>\d+)\/(?<retries>\d+) (?<server_queue>\d+)\/(?<backend_queue>\d+) (?:{(?:(?<http_host>[^\|]+)\||\|)(?:(?<http_header_forwarded_for>[^\|]+)\||\|)(?:(?<request_id>[^\|]+)\||\|)(?:(?<http_cf_connecting_ip>[^}]+)} |} ))?"(?<http_method>\S+) (?<path>[^ ]*) [^ ]+?"/
  time_format %d/%B/%Y:%H:%M:%S
  types client_port:integer,time_queue:integer,time_wait:integer,time_connect:integer,time_response:integer,total_time:integer,http_status:integer,body_bytes_sent:integer,active_conn:integer,frontend_conn:integer,backend_conn:integer,server_conn:integer,retries:integer,server_queue:integer,backend_queue:integer,pid:integer
</source>
```
and try to start `systemctl --full --no-pager start td-agent.service`

### Expected behavior

accept the config file and start up.

### Your Environment

```markdown
- Fluentd version: 1.14.3
- TD Agent version: 4.3.0-1
- Operating system: Ubuntu 20.04.3 LTS
- Kernel version: 5.13.0-30-generic
```

### Your Configuration

```apache
Stock td-agent install with the above listed /etc/td-agent/conf.d/20-source-haproxy.conf file
```

### Your Error Log

```shell
Traceback (most recent call last):
            31: from /opt/td-agent/bin/fluentd:23:in `<main>'
            30: from /opt/td-agent/bin/fluentd:23:in `load'
            29: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/bin/fluentd:15:in `<top (required)>'
            28: from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
            27: from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
            26: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
            25: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/supervisor.rb:665:in `run_supervisor'
            24: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/engine.rb:80:in `run_configure'
            23: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/engine.rb:105:in `configure'
            22: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/root_agent.rb:155:in `configure'
            21: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/root_agent.rb:155:in `each'
            20: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/root_agent.rb:161:in `block in configure'
            19: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/root_agent.rb:320:in `add_source'
            18: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin.rb:187:in `configure'
            17: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin/in_tail.rb:137:in `configure'
            16: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin_helper/parser.rb:85:in `configure'
            15: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin_helper/parser.rb:85:in `each'
            14: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin_helper/parser.rb:90:in `block in configure'
            13: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin.rb:187:in `configure'
            12: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin/parser_regexp.rb:34:in `configure'
            11: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin/parser.rb:115:in `configure'
            10: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/time.rb:168:in `configure'
             9: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin/base.rb:63:in `configure'
             8: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/configurable.rb:94:in `configure'
             7: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/config/section.rb:159:in `generate'
             6: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/config/section.rb:159:in `each_pair'
             5: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/config/section.rb:179:in `block in generate'
             4: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/config/section.rb:179:in `instance_exec'
             3: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/config/types.rb:178:in `block in <module:Config>'
             2: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/config/types.rb:87:in `regexp_value'
             1: from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/config/types.rb:87:in `compile'
    /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/config/types.rb:87:in `initialize': unmatched range specifier in char-class: /^\\w+[ ]+\\d+ \\d+:\\d+:\\d+ [^ ]+ (?<ps>(\\w|-)+)\\[(?<pid>\\d+)\\]: (?<remote_address>[\\w\\.]+):(?<client_port>\\d+) \\[(?<time>.+)\\] (?<frontend>[\\w-]+) (?<backend>[\\w-]+)\\/(?<backend_server>[\\w-<>]+) (?<time_queue>-?\\d+)\\/(?<time_wait>-?\\d+)\\/(?<time_connect>-?\\d+)\\/(?<time_response>-?\\d+)\\/(?<total_time>-?\\d+) (?<http_status>\\d+) (?<body_bytes_sent>\\d+) (?:(?<request_cookie>[^ ]{2,})|(?<request_cookie>[^-^ ]{1})|-) (?:(?<response_cookie>[^ ]{2,})|(?<response_cookie>[^-^ ]{1})|-) (?<termination_state>[^ ]+) (?<active_conn>\\d+)\\/(?<frontend_conn>\\d+)\\/(?<backend_conn>\\d+)\\/(?<server_conn>\\d+)\\/(?<retries>\\d+) (?<server_queue>\\d+)\\/(?<backend_queue>\\d+) (?:{(?:(?<http_host>[^\\|]+)\\||\\|)(?:(?<http_header_forwarded_for>[^\\|]+)\\||\\|)(?:(?<request_id>[^\\|]+)\\||\\|)(?:(?<http_cf_connecting_ip>[^}]+)} |} ))?"(?<http_method>\\S+) (?<path>[^ ]*) [^ ]+?"/ (RegexpError)
```
```


### Additional context

_No response_

**Comment by ashie** [comment]
Your regexp is wrong, it should be:
```diff
- (?<backend_server>[\w-<>]+)
+ (?<backend_server>[\w\-<>]+)
```

`-` in `[]` means range specifier, not `-` itself so that you need to escape it by `\`.
