### ISSUE TITLE
Parser Error Syslog Blocks in Ruby Functions

### ISSUE THREAD

**Issue by sysnetstriver** [fluent/fluentd#3676]
### Describe the bug

Network appliances are sending syslog messages via UDP on port 514. (Cisco, Fortinet, Meraki, Mellanox, IBM),  No fluentbit/fluentd collector agent is installed on these boxes as they are closed-source vendor proprietary operating systems. 
I have logs being ingested into our fluentd aggregator, however, parser errors in ruby functions are happening., amongst others.

### To Reproduce

Configure network appliances to send syslogs to fluentd aggregator over UDP port 514.  No additional configuration is done for sender messages format. Configure td-agent.conf for syslog directive and parser plugin. Configure parser manually.

### Expected behavior

I expect fluentd aggregator parser to parse the syslogs successfully without error.

### Your Environment

```markdown
- TD Agent version: td-agent 4.3.0 fluentd 1.14.3 (438a82aead488a86180cd484bbc4e7e344a9032b)
- Operating system: 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
- Kernel version:
Linux fluentd 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Your Configuration

```apache
<system>
  Log_Level debug
</system>

<source>
  @type syslog
  port 514
  bind 0.0.0.0
  tag system
  <parse>
    @type syslog
    parser_type string
    support_colonless_ident true
    expression /^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[^ :\[]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/ #RFC 3164
    expression /\A\<(?<pri>[0-9]{1,3})\>[1-9]\d{0,2} (?<time>[^ ]+) (?<host>[!-~]{1,255}) (?<ident>[!-~]{1,48}) (?<pid>[!-~]{1,128}) (?<msgid>[!-~]{1,32}) (?<extradata>(?:\-|(?:\[.*?(?<!\\)\])+))(?: (?<message>.+))?\z/ #RFC 5424
    with_priority true
    time_type string
    time_format %b %d %Y %H:%M:%S
    rfc5424_time_format %Y-%m-%dT%H:%M:%S.%L%Z
    keep_time_key true
    message_format auto
  </parse>
</source>

<match system.**>
  @type stdout
</match>
```

### Your Error Log

```shell
Td agent logs showing ruby functions error for parsing handler and block in udp server starting:
 
2022-03-15 19:46:58 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin/parser_syslog.rb:317:in `parse_rfc3164'
  2022-03-15 19:46:58 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin/in_syslog.rb:241:in `message_handler'
  2022-03-15 19:46:58 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin/in_syslog.rb:174:in `block in start_udp_server'
  2022-03-15 19:46:58 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin_helper/server.rb:543:in `on_readable_with_sock'
  2022-03-15 19:46:58 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:186:in `on_readable'
  2022-03-15 19:46:58 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2022-03-15 19:46:58 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2022-03-15 19:46:58 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2022-03-15 19:46:58 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

 2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/time.rb:280:in `rescue in parse'
  2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/time.rb:277:in `parse'
  2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin/parser_syslog.rb:488:in `rescue in parse_rfc5424'
  2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin/parser_syslog.rb:485:in `parse_rfc5424'
  2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin/parser_syslog.rb:153:in `parse_auto'
  2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin/in_syslog.rb:241:in `message_handler'
  2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin/in_syslog.rb:174:in `block in start_udp_server'
  2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin_helper/server.rb:543:in `on_readable_with_sock'
  2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:186:in `on_readable'
  2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2022-03-15 20:29:12 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

Td agent logs showing correctly parsed Firepower logs:

2022-03-15 20:29:12.000000000 +0000 system.local4.info: {"host":"%FTD-6-305011:","ident":"Built","message":"dynamic TCP translation from any:192.168.10.105/50572 to outside:99.153.68.49/50572","time":"Mar 15 2022 20:29:12:"}
2022-03-15 20:29:12.000000000 +0000 system.local4.info: {"host":"%FTD-6-302013:","ident":"Built","message":"inbound TCP connection 49388191 for corporate:192.168.10.105/50572 (99.153.68.49/50572) to outside:35.170.134.110/443 (35.170.134.110/443)","time":"Mar 15 2022 20:29:12:"}
2022-03-15 20:29:12.000000000 +0000 system.local4.info: {"host":"%FTD-6-302015:","ident":"Built","message":"inbound UDP connection 49388192 for sentry_net-dnat:192.168.192.12/57728 (192.168.192.12/57728) to rack_servers:192.168.140.6/53 (192.168.140.6/53)","time":"Mar 15 2022 20:29:12:"}

Td agent logs showing invalid input data for other Firepower logs and other network appliances:

Firepower:

2022-03-15 20:29:12 +0000 [error]: #0 invalid input data="<118>2022-03-15T20:27:12Z   %FTD-6-430003: EventPriority: Low, DeviceUUID: 70c3f210-e998-11ea-8078-b53815b2546b, InstanceID: 4, FirstPacketSecond: 2022-03-15T20:27:12Z, ConnectionID: 39156, AccessControlRuleAction: Allow, SrcIP: 192.168.140.8, DstIP: 8.8.8.8, SrcPort: 2960, DstPort: 53, Protocol: udp, IngressInterface: rack_servers, EgressInterface: outside, IngressZone: inside_zone, EgressZone: outside_zone, IngressVRF: Global, EgressVRF: Global, ACPolicy: NGFW-Access-Policy, AccessControlRuleName: Inside_Outside_Primary_Circuit_Rule, User: Not Found, Client: DNS client, ApplicationProtocol: DNS, ConnectionDuration: 0, InitiatorPackets: 1, ResponderPackets: 1, InitiatorBytes: 91, ResponderBytes: 151, NAPPolicy: Invalid ID, DNSQuery: api.snapcraft.io, DNSRecordType: a host address, DNSResponseType: No Error, DNS_TTL: 46, NAT_InitiatorPort: 2960, NAT_ResponderPort: 53, NAT_InitiatorIP: 99.153.68.49, NAT_ResponderIP: 8.8.8.8" error_class=Fluent::TimeParser::TimeParseError error="invalid time format: value = , error_class = ArgumentError, error = string doesn't match"


Fortigate:

2022-03-15 20:35:12 +0000 [error]: #0 invalid input data="<189>date=2022-03-15 time=15:35:12 devname=\"fortigate01montopolis\" devid=\"FG100FTK21004605\" eventtime=1647376512655680870 tz=\"-0500\" logid=\"0001000014\" type=\"traffic\" subtype=\"local\" level=\"notice\" vd=\"root\" srcip=162.142.125.242 srcport=17193 srcintf=\"wan1\" srcintfrole=\"wan\" dstip=216.137.66.217 dstport=9005 dstintf=\"root\" dstintfrole=\"undefined\" srccountry=\"United States\" dstcountry=\"United States\" sessionid=8924557 proto=6 action=\"deny\" policyid=0 policytype=\"local-in-policy\" service=\"tcp/9005\" trandisp=\"noop\" app=\"tcp/9005\" duration=0 sentbyte=0 rcvdbyte=0 sentpkt=0 rcvdpkt=0 appcat=\"unscanned\" crscore=5 craction=262144 crlevel=\"low\"" error_class=Fluent::TimeParser::TimeParseError error="invalid time format: value = date=2022-03-15 time=15:35:12 devname=\"fortigate01montopolis\" devid=\"FG100FTK21004605\", error_class = ArgumentError, error = string doesn't match"

Meraki:

2022-03-15 20:29:12 +0000 [error]: #0 invalid input data="<134>1 1647376152.772521309 Austin_MR46 flows allow src=192.168.100.68 dst=91.189.89.90 mac=3C:F0:11:FE:8E:7C protocol=tcp sport=34354 dport=80" error_class=Fluent::TimeParser::TimeParseError error="invalid time format: value = 1647376152.772521309, error_class = ArgumentError, error = string doesn't match"
```

### Additional context

Maybe this will be useful. The two syslog streams coming into the aggregator from the Cisco firepower. The logs from our Cisco firewpower are a prime example of what I am trying to account for. The system sends FTD ( security event logs for example ) and FXOS logs ( chassis syslogs ). One is being parsed correctly, the other is not. This seems to be affected by the ruby syslog, server, time, and parsing functions errors ? A hint is the `value = ,` in the error log example for one of the logs that come from the Firepower. It is odd the one of the log streams works with the parser but the other does not.

![image](https://user-images.githubusercontent.com/98474444/158468489-384ae6c8-ee26-433b-b851-39afb6754ba0.png)

**Comment by sysnetstriver** [comment]
Forgot to mention that I did the systemd unit file config for the td-agent service in order to bind well-known port 514 as the socket stream:
```
[Unit]
Description=td-agent: Fluentd based data collector for Treasure Data
Documentation=https://docs.treasuredata.com/display/public/PD/About+Treasure+Data%%27s+Server-Side+Agent
After=network-online.target
Wants=network-online.target

[Service]
User=td-agent
Group=td-agent
LimitNOFILE=999999
Environment=LD_PRELOAD=/opt/td-agent/lib/libjemalloc.so
Environment=GEM_HOME=/opt/td-agent/lib/ruby/gems/2.7.0/
Environment=GEM_PATH=/opt/td-agent/lib/ruby/gems/2.7.0/
Environment=FLUENT_CONF=/etc/td-agent/td-agent.conf
Environment=FLUENT_PLUGIN=/etc/td-agent/plugin
Environment=FLUENT_SOCKET=/var/run/td-agent/td-agent.sock
Environment=TD_AGENT_LOG_FILE=/var/log/td-agent/td-agent.log
Environment=TD_AGENT_OPTIONS=
EnvironmentFile=-/etc/default/td-agent
PIDFile=/var/run/td-agent/td-agent.pid
RuntimeDirectory=td-agent
Type=forking
# XXX: Fix fluentd executables path
ExecStart=/opt/td-agent/bin/fluentd --log $TD_AGENT_LOG_FILE --daemon /var/run/td-agent/td-agent.pid $TD_AGENT_OPTIONS
ExecStop=/bin/kill -TERM ${MAINPID}
ExecReload=/bin/kill -HUP ${MAINPID}
Restart=always
TimeoutStopSec=120
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

**Comment by ashie** [comment]
All of invalid messages you mentioned don't follow both RFC 3164 and RFC 5424, so you may need to use regexp parser for them.

e.g.)

> <118>2022-03-15T20:27:12Z   %FTD-6-430003:...

If it uses RFC 3164, the time format should be like `Apr 17 11:26:00`: https://datatracker.ietf.org/doc/html/rfc3164#section-4.1.2
It it uses RFC 5424, the head of the message should be `<118>1`: https://datatracker.ietf.org/doc/html/rfc5424#section-6.5


BTW in this case Fluentd detects it as RFC 5424:
https://github.com/fluent/fluentd/blob/b04e8084a887dc8395d49c606f474e33a396997c/lib/fluent/plugin/parser_syslog.rb#L41
https://github.com/fluent/fluentd/blob/b04e8084a887dc8395d49c606f474e33a396997c/lib/fluent/plugin/parser_syslog.rb#L149

It seems problematic, we might need to fix it:

* Trailing space isn't checked
* Although only the version `1` is valid for now but it allows other versions
* What's mean the trailing `\d{0,2}`?
