### ISSUE TITLE
error_class=Yajl::EncodeError error="'Infinity' is an invalid number"

### ISSUE THREAD

**Issue by ajardan** [fluent/fluentd#3870]
### Describe the bug

After a while td-agent produces this error in the logs, and after several retries, it stops delivering logs

### To Reproduce

Not sure, there's nothing specific we are using to cause this issue

### Expected behavior

Logs being delivered

### Your Environment

```markdown
- Fluentd version:
- TD Agent version: 1.15.0
- Operating system: CentOS Linux release 7.9.2009
- Kernel version: 3.10.0-1160.71.1.el7.x86_64
```

### Your Configuration

```apache
@include conf.d/*.conf

<filter **>
  #
  # BE AWARE: we use the record_transformer only to inject some datamodel
  # ... there is no typical record transformation
  #
  @type record_modifier
  <inject>
    # add GELF-mandatory "host" (aka "source")
    hostname_key host

    # add GELF-mandatory "timestamp"
    # ... use parsed time-info stored in fluentd-datamodel
    time_key timestamp

    # all servers use UTC
    utc true
  </inject>
  <record>
    level_txt ${(record.has_key?('level_txt') ? record["level_txt"].to_s.downcase : 'undefined')}
    level ${(record.has_key?('level') ? record["level"].is_a?(Integer) ? record["level"] : 99 : 6)}
  </record>
</filter>

############################################################################################
#############################################################################################
########################################################################## docker.foo
#############################################################################################

#################################################
<match docker.svc1>
  @type copy
    <store>
    @type cloudwatch_logs
    <buffer>
      chunk_limit_size 32MB
      flush_interval 5s
      flush_thread_count 2
      retry_forever true
    </buffer>
    log_group_name live-docker
    log_stream_name svc1
    auto_create_stream true
    region eu-central-1
  </store>
  </match>

#################################################
<match docker.svc2>
  @type copy
    <store>
    @type cloudwatch_logs
    <buffer>
      chunk_limit_size 32MB
      flush_interval 5s
      flush_thread_count 2
      retry_forever true
    </buffer>
    log_group_name live-docker
    log_stream_name svc2
    auto_create_stream true
    region eu-central-1
  </store>
  </match>

#################################################
<match docker.svc3>
  @type copy
    <store>
    @type cloudwatch_logs
    <buffer>
      chunk_limit_size 32MB
      flush_interval 5s
      flush_thread_count 2
      retry_forever true
    </buffer>
    log_group_name live-docker
    log_stream_name svc3
    auto_create_stream true
    region eu-central-1
  </store>
  </match>

#################################################
<match docker.svc4>
  @type copy
    <store>
    @type cloudwatch_logs
    <buffer>
      chunk_limit_size 32MB
      flush_interval 5s
      flush_thread_count 2
      retry_forever true
    </buffer>
    log_group_name live-docker
    log_stream_name svc4
    auto_create_stream true
    region eu-central-1
  </store>
  </match>


#############################################################################################
########################################################################## infrastructure.foo
#############################################################################################

#################################################
<match infrastructure.service.nginx_access>
  @type copy
    <store>
    @type cloudwatch_logs
    <buffer>
      chunk_limit_size 32MB
      flush_interval 5s
      flush_thread_count 2
      retry_forever true
    </buffer>
    log_group_name live-infrastructure
    log_stream_name service.nginx_access
    auto_create_stream true
    region eu-central-1
  </store>
  </match>

#################################################
<match infrastructure.service.nginx_error>
  @type copy
    <store>
    @type cloudwatch_logs
    <buffer>
      chunk_limit_size 32MB
      flush_interval 5s
      flush_thread_count 2
      retry_forever true
    </buffer>
    log_group_name live-infrastructure
    log_stream_name service.nginx_error
    auto_create_stream true
    region eu-central-1
  </store>
  </match>

#################################################
<match infrastructure.service.**>
  @type copy
    <store>
    @type cloudwatch_logs
    <buffer>
      chunk_limit_size 32MB
      flush_interval 5s
      flush_thread_count 2
      retry_forever true
    </buffer>
    log_group_name live-infrastructure
    log_stream_name service.catchall
    auto_create_stream true
    region eu-central-1
  </store>
  </match>

#############################################################################################
########################################################################## fallback
#############################################################################################
# ... to avoid losing logs => route to default port
#
<match **>
  @type copy
    <store>
    @type cloudwatch_logs
    <buffer>
      chunk_limit_size 32MB
      flush_interval 5s
      flush_thread_count 2
      retry_forever true
    </buffer>
    log_group_name live-catchall
    log_stream_name general
    auto_create_stream true
    region eu-central-1
  </store>
  </match>
```

### Your Error Log

```shell
2022-08-23 08:48:20 +0000 [warn]: #0 failed to flush the buffer. retry_times=0 next_retry_time=2022-08-23 08:48:21 +0000 chunk="5e6e4a0022a7ff23c5b06427ec61c131" error_class=Yajl::EncodeError error="'Infinity' is an invalid number"
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/yajl-ruby-1.4.1/lib/yajl.rb:80:in `encode'
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/yajl-ruby-1.4.1/lib/yajl.rb:80:in `encode'
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/yajl-ruby-1.4.1/lib/yajl.rb:23:in `dump'
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.14.3/lib/fluent/plugin/out_cloudwatch_logs.rb:108:in `block in configure'
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.14.3/lib/fluent/plugin/out_cloudwatch_logs.rb:299:in `block (2 levels) in write'
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.14.3/lib/fluent/plugin/out_cloudwatch_logs.rb:285:in `each'
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.14.3/lib/fluent/plugin/out_cloudwatch_logs.rb:285:in `block in write'
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.14.3/lib/fluent/plugin/out_cloudwatch_logs.rb:235:in `each'
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.14.3/lib/fluent/plugin/out_cloudwatch_logs.rb:235:in `write'
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.15.0/lib/fluent/plugin/output.rb:1180:in `try_flush'
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.15.0/lib/fluent/plugin/output.rb:1501:in `flush_thread_run'
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.15.0/lib/fluent/plugin/output.rb:501:in `block (2 levels) in start'
  2022-08-23 08:48:20 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.15.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by ajardan** [comment]
Looks like this is caused by a JSON event containing a value set to Infinity, which cannot be properly processed by yajl-ruby, the issue happens here: 

https://github.com/brianmario/yajl-ruby/blob/e8de283a6d64f0902740fd09e858fc3d7d803161/ext/yajl/yajl_ext.c#L257

**Comment by ajardan** [comment]
Here is an event that can be used to trigger this issue:

```
{"log":"{\"details\":{\"instana.trace.id\":Infinity},\"full_message\":\"Failed to find access token\\n\",\"host\":\"d1653032c3d4\",\"level\":6,\"level_txt\":\"info\",\"logger_name\":\"org.springframework.security.oauth2.provider.token.store.JdbcTokenStore\",\"message\":\"Failed to find access token\",\"thread_name\":\"https-jsse-nio-8443-exec-321\",\"timestamp\":1661346253.396,\"version\":\"1.0\"}\n","stream":"stdout","time":"2022-08-24T13:04:13.396516342Z"}
```

**Comment by ashie** [comment]
> Looks like this is caused by a JSON event containing a value set to Infinity, which cannot be properly processed by yajl-ruby, the issue happens here:
> 
> https://github.com/brianmario/yajl-ruby/blob/e8de283a6d64f0902740fd09e858fc3d7d803161/ext/yajl/yajl_ext.c#L257

`Infinity` is invalid for JSON, so that it's a problem of incoming data, not a bug.

Probably there is a work around for it.
Please try to use `json` module instead of yajl-ruby.
```ruby
irb(main):001:0> require 'json'
=> true
irb(main):002:0> JSON.load('{"id":Infinity}')
=> {"id"=>Infinity}
```
You can switch it by `json_handler` of fluent-plugin-cloundwatch-logs:
https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/blob/master/lib/fluent/plugin/out_cloudwatch_logs.rb#L53
```
json_handler json
```

**Comment by ajardan** [comment]
While this is indeed a problem with the incoming data, should this stop fluentd from working ?

**Comment by ashie** [comment]
It should be handled in fluent-plugin-cloundwatch-logs.
Could you forward your issue to https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/issues ?
