### ISSUE TITLE
Fluentd has 2 million open files, specifically connections and many errors

### ISSUE THREAD

**Issue by waqarsky** [fluent/fluentd#3943]
### Describe the bug

When I check the output of lsof I can see over 2M connections in ESTABLISHED or CLOSE_WAIT

```ruby2.7 2749468 2750970 worker-14 fluentd 62u IPv4 1356781066 0t0 TCP {URL REDACTED}:5044->ip-10-153-7-71.eu-central-1.compute.internal:13637 (CLOSE_WAIT)```

I am using the latest version of the filebeat input plugin and here is the config for that: 
```
<source>
  @type beats
  metadata_as_tag
  port 5044
  bind 0.0.0.0
</source>
```
I also see these errors in the fluentd log: 

```
 2022-11-03 15:45:16.318073120 +0000 fluent.error: {"error":"invalid block type","message":"unexpected error error=\"invalid block type\""}
2022-11-03 15:45:16.318157025 +0000 fluent.error: {"error":"unsupported protocol 249","message":"unexpected error error=\"unsupported protocol 249\""}
2022-11-03 15:45:16 +0000 [error]: #0 unexpected error error="unsupported protocol 249"
  2022-11-03 15:45:16 +0000 [error]: #0 /var/lib/gems/2.7.0/gems/fluent-plugin-beats-1.1.0/lib/lumberjack/beats/server.rb:233:in `handle_version'
  2022-11-03 15:45:16 +0000 [error]: #0 /var/lib/gems/2.7.0/gems/fluent-plugin-beats-1.1.0/lib/lumberjack/beats/server.rb:218:in `header'
  2022-11-03 15:45:16 +0000 [error]: #0 /var/lib/gems/2.7.0/gems/fluent-plugin-beats-1.1.0/lib/lumberjack/beats/server.rb:171:in `feed'
  2022-11-03 15:45:16 +0000 [error]: #0 /var/lib/gems/2.7.0/gems/fluent-plugin-beats-1.1.0/lib/lumberjack/beats/server.rb:353:in `read_socket'
  2022-11-03 15:45:16 +0000 [error]: #0 /var/lib/gems/2.7.0/gems/fluent-plugin-beats-1.1.0/lib/lumberjack/beats/server.rb:328:in `run'
  2022-11-03 15:45:16 +0000 [error]: #0 /var/lib/gems/2.7.0/gems/fluent-plugin-beats-1.1.0/lib/fluent/plugin/in_beats.rb:111:in `block in run'
  2022-11-03 15:45:16 +0000 [error]: #0 /var/lib/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
  2022-11-03 15:45:16 +0000 [error]: #0 /var/lib/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
  2022-11-03 15:45:16 +0000 [error]: #0 /var/lib/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
  2022-11-03 15:45:16 +0000 [error]: #0 /var/lib/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
  2022-11-03 15:45:16 +0000 [error]: #0 /var/lib/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
  2022-11-03 15:45:16 +0000 [error]: #0 /var/lib/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
```

On the filebeat side I can see these errors: 

```
{"level":"error","timestamp":"2022-11-03T15:17:06.891Z","logger":"publisher_pipeline_output","caller":"pipeline/output.go:180","message":"failed
 to publish events: client is not connected"}```


```
$ fluentd --version
fluentd 1.15.2

https://github.com/repeatedly/fluent-plugin-beats @ v1.1.0
```

The logs come in but extremely slowly and sometimes they dont come in at all until filebeat process is restarted
Any help appreciated

### To Reproduce

* Set up beats input
* Configure filebeat to point to fluentd and send logs
* Have over 100 machines sending logs to this input 

### Expected behavior

* Logs should come in as normal.
* No errors such as 
```2022-11-03 15:48:55.819145267 +0000 fluent.error: {"error":"invalid block type","message":"unexpected error error=\"invalid block type\""}```
* Not 2M open connections

### Your Environment

```markdown
- Fluentd version: fluentd 1.15.2
- TD Agent version: N/A 
- Operating system: Ubuntu 
- Kernel version: 5.4.0-1029-aws
```

### Your Configuration

```apache
<source>
  @type beats
  metadata_as_tag
  port 5044
  bind 0.0.0.0
</source>
```
```


### Your Error Log

```shell
As above
```

**Comment by fujimotos** [comment]
This is a bug of `fluent-plugin-beats` (rather than fluentd core).

The probability is that your beat client version does not match the
server module in the plugim. Here is a similar issue reported there:

https://github.com/repeatedly/fluent-plugin-beats/issues/4

Please open an issue on the plugin repo and ask further help there.

**Comment by waqarsky** [comment]
@fujimotos  Please note I have already tried to raise an issue on that plugin. I dont know the channels to do so, but it should be mentioned somewhere that that plugin is no longer supported. There is no response to multiple raised issues. 
Thanks
