### ISSUE TITLE
Unable to use snappy compression with fluentdv1.x

### ISSUE THREAD

**Issue by beerus11** [fluent/fluentd#4017]
### Describe the bug

Unable to use snappy compression with fluentdv1.x, getting the some exception when the producer pushes messages. In fluent configuration, "snappy" compression is enabled.

### To Reproduce

1. Using docker official image v1.15-1,
2. compression snappy is enabled on fluent configuration file on a topic
3. Try pushing messages in that topic

### Expected behavior

Wants to enable snappy compression on a Kafka topic.

### Your Environment

```markdown
- Fluent version: 1.x docker image
- TD Agent version: not sure, how to check.I'm using 1.x image
- Operating system: alphine
- Kernel version: not sure using official 1.15-1 docker image.
```

### Your Configuration

```apache
Docker image - 

FROM fluent/fluentd:v1.15-1

# Use root account to use apk
USER root
# below RUN includes plugin as examples elasticsearch is not required
# you may customize including plugins as you wish
RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base curl ruby ruby-dev autoconf automake libtool g++ snappy-dev

RUN fluent-gem install snappy
RUN fluent-gem install fluent-plugin-kafka
RUN fluent-gem install fluent-plugin-prometheus
RUN sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

USER root
```

### Your Error Log

```shell
/usr/lib/ruby/gems/3.1.0/gems/ruby-kafka-1.5.0/lib/kafka/snappy_codec.rb:16:in `rescue in load': Using snappy compression requires adding a dependency on the `snappy` gem to your Gemfile. (LoadError)

from /usr/lib/ruby/gems/3.1.0/gems/ruby-kafka-1.5.0/lib/kafka/snappy_codec.rb:13:in `load'

from /usr/lib/ruby/gems/3.1.0/gems/ruby-kafka-1.5.0/lib/kafka/compression.rb:30:in `find_codec'

from /usr/lib/ruby/gems/3.1.0/gems/ruby-kafka-1.5.0/lib/kafka/compressor.rb:28:in `initialize'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/kafka_producer_ext.rb:51:in `new'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/kafka_producer_ext.rb:51:in `custom_producer'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:210:in `create_producer'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:277:in `block in get_producer'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:274:in `synchronize'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:274:in `get_producer'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:323:in `write'

from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1180:in `try_flush'

from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1501:in `flush_thread_run'

from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:501:in `block (2 levels) in start'

from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

<internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': Error loading shared library libsnappy.so.1: No such file or directory (needed by /usr/lib/ruby/gems/3.1.0/gems/snappy-0.3.0/lib/snappy_ext.so) - /usr/lib/ruby/gems/3.1.0/gems/snappy-0.3.0/lib/snappy_ext.so (LoadError)

from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'

from /usr/lib/ruby/gems/3.1.0/gems/snappy-0.3.0/lib/snappy.rb:5:in `<top (required)>'

from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'

from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'

from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'

from /usr/lib/ruby/gems/3.1.0/gems/ruby-kafka-1.5.0/lib/kafka/snappy_codec.rb:14:in `load'

from /usr/lib/ruby/gems/3.1.0/gems/ruby-kafka-1.5.0/lib/kafka/compression.rb:30:in `find_codec'

from /usr/lib/ruby/gems/3.1.0/gems/ruby-kafka-1.5.0/lib/kafka/compressor.rb:28:in `initialize'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/kafka_producer_ext.rb:51:in `new'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/kafka_producer_ext.rb:51:in `custom_producer'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:210:in `create_producer'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:277:in `block in get_producer'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:274:in `synchronize'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:274:in `get_producer'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:323:in `write'

from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1180:in `try_flush'

from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1501:in `flush_thread_run'

from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:501:in `block (2 levels) in start'

from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

<internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- snappy (LoadError)

from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'

from /usr/lib/ruby/gems/3.1.0/gems/ruby-kafka-1.5.0/lib/kafka/snappy_codec.rb:14:in `load'

from /usr/lib/ruby/gems/3.1.0/gems/ruby-kafka-1.5.0/lib/kafka/compression.rb:30:in `find_codec'

from /usr/lib/ruby/gems/3.1.0/gems/ruby-kafka-1.5.0/lib/kafka/compressor.rb:28:in `initialize'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/kafka_producer_ext.rb:51:in `new'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/kafka_producer_ext.rb:51:in `custom_producer'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:210:in `create_producer'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:277:in `block in get_producer'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:274:in `synchronize'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:274:in `get_producer'

from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:323:in `write'

from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1180:in `try_flush'

from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1501:in `flush_thread_run'

from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:501:in `block (2 levels) in start'

from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by beerus11** [comment]
found the issue in the docker file, snappy dependent on some. so file, which was being removed in rm -rf command.

following fix , works for me:
RUN apk --no-cache add ruby-dev snappy g++ snappy-dev make \
 && sudo gem install fluent-plugin-kafka -v 0.17.1 \
 && sudo gem install snappy -v 0.0.17 \
 && sudo gem install fluent-plugin-prometheus -v 1.8.4 \
&& sudo gem sources --clear-all
