### ISSUE TITLE
CI: Some tests about signal handlers sometimes fail

### ISSUE THREAD

**Issue by daipom** [fluent/fluentd#4063]
### Describe the bug

`test_cont_in_main_process_signal_handlers` and `test_cont_in_supervisor_signal_handler` of `SupervisorTest` sometimes fail.

```
===============================================================================
Failure: test_cont_in_main_process_signal_handlers(SupervisorTest):
  class()
  Called 0 times.
  Expected 1 times.
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:74:in `block in dump_object_count'
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:73:in `each_object'
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:73:in `dump_object_count'
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:18:in `block in dump'
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `open'
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `_open_dump_path'
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:14:in `dump'
/home/runner/work/fluentd/fluentd/lib/fluent/supervisor.rb:1027:in `dump_non_windows'
/home/runner/work/fluentd/fluentd/lib/fluent/supervisor.rb:943:in `block in install_main_process_signal_handlers'
/home/runner/work/fluentd/fluentd/test/test_supervisor.rb:221:in `kill'
/home/runner/work/fluentd/fluentd/test/test_supervisor.rb:221:in `test_cont_in_main_process_signal_handlers'
     218:     sv = Fluent::Supervisor.new(opts)
     219:     sv.send(:install_main_process_signal_handlers)
     220: 
  => 221:     Process.kill :CONT, Process.pid
     222: 
     223:     sleep 1
     224: 
===============================================================================
F
===============================================================================
Failure: test_cont_in_supervisor_signal_handler(SupervisorTest):
  class()
  Called 0 times.
  Expected 1 times.
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:74:in `block in dump_object_count'
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:73:in `each_object'
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:73:in `dump_object_count'
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:18:in `block in dump'
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `open'
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `_open_dump_path'
/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/gems/3.0.0/gems/sigdump-0.2.4/lib/sigdump.rb:14:in `dump'
/home/runner/work/fluentd/fluentd/lib/fluent/supervisor.rb:1027:in `dump_non_windows'
/home/runner/work/fluentd/fluentd/lib/fluent/supervisor.rb:943:in `block in install_main_process_signal_handlers'
/home/runner/work/fluentd/fluentd/test/test_supervisor.rb:305:in `kill'
/home/runner/work/fluentd/fluentd/test/test_supervisor.rb:305:in `test_cont_in_supervisor_signal_handler'
     302:     server = DummyServer.new
     303:     server.install_supervisor_signal_handlers
     304: 
  => 305:     Process.kill :CONT, Process.pid
     306: 
     307:     sleep 1
     308: 
===============================================================================
```

This is similar to 0d126dedf131637fad7d6dabf8a9c86fd5cf3eca

* #3680

### To Reproduce

I can't reproduce this on my local yet.

In CI, sometimes these tests fail on Ubuntu.

### Expected behavior

The tests always succeed.

### Your Environment

```markdown
None
```

### Your Configuration

```apache
None
```

### Your Error Log

```shell
None
```

**Comment by daipom** [comment]
I'm not sure, but I remember this issue started after the following fix.

* https://github.com/fluent/fluentd/pull/4043
* https://github.com/fluent/fluentd/pull/4044
* https://github.com/fluent/fluentd/pull/4050

**Comment by Watson1978** [comment]
I'm guessing that the issue is related to `dont_allow` in rr gem.
If it use the object applied `dont_allow` in the other test through `ObjectSpace.each_object`, it will cause the error.

```ruby
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'rr'
  gem 'test-unit'
  gem 'test-unit-rr'
end

class SampleTest < ::Test::Unit::TestCase
  def test_a
    dont_allow(mock!).foo
  end

  def test_b
    ObjectSpace.each_object { |obj|
      obj.class
    }
  end
end
```

```
$ ruby rr_1.rb
Loaded suite rr_1
Started
F
=================================================================================================================================================================
Failure: test_b(SampleTest):
  Called 1 time.
  Expected 0 times.
rr_1.rb:16:in `block in test_b'
     13: 
     14:   def test_b
     15:     ObjectSpace.each_object { |obj|
  => 16:       obj.class
     17:     }
     18:   end
     19: end
rr_1.rb:15:in `each_object'
rr_1.rb:15:in `test_b'
=================================================================================================================================================================
Finished in 0.001690435 seconds.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
2 tests, 0 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
50% passed
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
1183.13 tests/s, 0.00 assertions/s
```

However, if it applied `never` instead of `dont_allow`, it works well.

```ruby
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'rr'
  gem 'test-unit'
  gem 'test-unit-rr'
end

class SampleTest < ::Test::Unit::TestCase
  def test_a
    mock!.foo.never
  end

  def test_b
    ObjectSpace.each_object {|obj|
      obj.class
    }
  end
end
```

```
$ ruby rr_2.rb
Loaded suite rr_2
Started
Finished in 0.002811038 seconds.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
2 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
711.48 tests/s, 0.00 assertions/s
```

**Comment by Watson1978** [comment]
The reason this occurs only occasionally is probably because the object applied `dont_allow` was collected by GC.

If the object is alived, looks for me it appears to be causing problems.

**Comment by daipom** [comment]
@Watson1978 Thanks!!
Looks like `dont_allow` of RR has some issues.

```rb
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'rr'
  gem 'test-unit'
  gem 'test-unit-rr'
end

class SampleTest < ::Test::Unit::TestCase
  def test_a
    dont_allow!.foo
  end

  def test_b
    ObjectSpace.each_object do |obj|
      obj.class
    end
  end
end
```

```console
$ ruby test.rb
Loaded suite test
Started
F
====================================================================================================================================================================
Failure: test_b(SampleTest):
  Called 1 time.
  Expected 0 times.
test.rb:16:in `block in test_b'
     13: 
     14:   def test_b
     15:     ObjectSpace.each_object do |obj|
  => 16:       obj.class
     17:     end
     18:   end
     19: end
test.rb:15:in `each_object'
test.rb:15:in `test_b'
====================================================================================================================================================================
Finished in 0.003105795 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
2 tests, 0 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
50% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
643.96 tests/s, 0.00 assertions/s
```

**Comment by daipom** [comment]
It appears that `#dont_allow / #dont_allow!` API of RR has some issues.

@Watson1978 Could you please send an issue to https://github.com/rr/rr?

**Comment by Watson1978** [comment]
Maybe, I think dont_allow has right behavior.
Fluentd's tests are rea case because its using ObjectSpace.each_object.

**Comment by daipom** [comment]
Hmm, I'm concerned about this `dont_allow` behavior, so I have sent an issue.
Thanks for your investigation!

**Comment by daipom** [comment]
This still happens.
Confirmed on macOS.

https://github.com/fluent/fluentd/actions/runs/12501773512/job/34879770493

```
 2) Failure: test_cont_in_main_process_signal_handlers(SupervisorTest):
  class()
  Called 0 times.
  Expected 1 times.
/Users/runner/hostedtoolcache/Ruby/3.1.6/arm64/lib/ruby/gems/3.1.0/gems/sigdump-0.2.5/lib/sigdump.rb:76:in `block in dump_object_count'
/Users/runner/hostedtoolcache/Ruby/3.1.6/arm64/lib/ruby/gems/3.1.0/gems/sigdump-0.2.5/lib/sigdump.rb:75:in `each_object'
/Users/runner/hostedtoolcache/Ruby/3.1.6/arm64/lib/ruby/gems/3.1.0/gems/sigdump-0.2.5/lib/sigdump.rb:75:in `dump_object_count'
/Users/runner/hostedtoolcache/Ruby/3.1.6/arm64/lib/ruby/gems/3.1.0/gems/sigdump-0.2.5/lib/sigdump.rb:18:in `block in dump'
/Users/runner/hostedtoolcache/Ruby/3.1.6/arm64/lib/ruby/gems/3.1.0/gems/sigdump-0.2.5/lib/sigdump.rb:138:in `open'
/Users/runner/hostedtoolcache/Ruby/3.1.6/arm64/lib/ruby/gems/3.1.0/gems/sigdump-0.2.5/lib/sigdump.rb:138:in `_open_dump_path'
/Users/runner/hostedtoolcache/Ruby/3.1.6/arm64/lib/ruby/gems/3.1.0/gems/sigdump-0.2.5/lib/sigdump.rb:14:in `dump'
/Users/runner/work/fluentd/fluentd/lib/fluent/supervisor.rb:1096:in `dump_non_windows'
/Users/runner/work/fluentd/fluentd/lib/fluent/supervisor.rb:996:in `block in install_main_process_signal_handlers'
/Users/runner/work/fluentd/fluentd/test/test_supervisor.rb:270:in `kill'
/Users/runner/work/fluentd/fluentd/test/test_supervisor.rb:270:in `test_cont_in_main_process_signal_handlers'
     267:     sv = Fluent::Supervisor.new({})
     268:     sv.send(:install_main_process_signal_handlers)
     269: 
  => 270:     Process.kill :CONT, Process.pid
     271: 
     272:     sleep 1
     273: 
```

**Comment by Watson1978** [comment]
Looks like that `mock(Process).kill(:WINCH, -1).never` causes this error.

```ruby
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'rr'
  gem 'test-unit'
  gem 'test-unit-rr'
end

class SampleTest < ::Test::Unit::TestCase
  def test_a
    mock(Process).kill(:WINCH, -1).never

    ObjectSpace.each_object { |obj|
      obj.class
    }
  end
end
```

```
$ ruby -v rr.rb
ruby 3.1.6p260 (2024-05-29 revision a777087be6) [arm64-darwin24]
Loaded suite rr
Started
F
===========================================================================================================================
Failure: test_b(SampleTest):
  class()
  Called 0 times.
  Expected 1 times.
rr.rb:14:in `block in test_b'
     11:     mock(Process).kill(:WINCH, -1).never
     12: 
     13:     ObjectSpace.each_object { |obj|
  => 14:       obj.class
     15:     }
     16:   end
     17: end
rr.rb:13:in `each_object'
rr.rb:13:in `test_b'
===========================================================================================================================
Finished in 0.00499 seconds.
---------------------------------------------------------------------------------------------------------------------------
1 tests, 0 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
---------------------------------------------------------------------------------------------------------------------------
200.40 tests/s, 0.00 assertions/s
```

**Comment by daipom** [comment]
It appears to me that `Sigdump.dump` is entirely incompatible with RR.
We have already fixed the `dont_allow` issue, but other APIs of RR have the same issue with Sigdump.

```rb
class SampleTest < ::Test::Unit::TestCase
  def test_a
    mock(String).foo.never
    mock(String).bar.never

    ObjectSpace.each_object do |obj|
      obj.class
    end
  end
end
```

```
Loaded suite test
Started
F
==================================================================================================================================================================================================================================================================================
Failure: test_a(SampleTest):
  class()
  Called 0 times.
  Expected 1 times.
test.rb:54:in `block in test_a'
     51:     mock(String).bar.never
     52: 
     53:     ObjectSpace.each_object do |obj|
  => 54:       obj.class
     55:     end
     56:   end
     57: end
test.rb:53:in `each_object'
test.rb:53:in `test_a'
==================================================================================================================================================================================================================================================================================
Finished in 0.004406066 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 tests, 0 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Sigdump uses `ObjectSpace`, and calls `Klass#class` method.
When the `Klass` is `DoubleDefinition` of RR, then it sets some expectations.
It can cause a test failure by the order of objects, etc.

**Comment by daipom** [comment]
Perhaps a better solution would be to run GC in the Sigdump tests.
It will remove `DoubleDefinition` objects made in other tests.
