### ISSUE TITLE
Flush thread high CPU with particular pod

### ISSUE THREAD

**Issue by alantang888** [fluent/fluentd#4067]
### Describe the bug

Fluentd have high CPU usage. It can consume 1 core on K8S node.

That particular pod is one of our own application. And it output JSON log. We check those log output is not included any special char. Also is valid JSON format.

### To Reproduce

When deploy fluentd pod with that particular application pod in same node. After a while (can be few hours, 1 day or few days) fluentd will start consume high CPU.

When high CPU happened. It won't go down. It can keep high CPU for a day. Restart fluentd container. It can return to normal. But normally will go to high loading within one hour.

When delete that particular application pod. Fluentd also can return to normal. After a while (can be few hours, 1 day or few days) fluentd will start consume high CPU.

### Expected behavior

Fluentd should keep low cpu usage. Since just around 30 logs message/min.

### Your Environment

```markdown
- Fluentd version: 1.13.3
- Operating system: Amazon Linux 2, docker image: fluent/fluentd-kubernetes-daemonset:v1.13-debian-elasticsearch7-1 (Newer image contain elasticsearch 7.14. It will not run with our ES7.10 oss build)
- Kernel version: 5.4.228-131.415.amzn2.x86_64
```

### Your Configuration

```apache
# Mostly is default from helm chart (version 0.3.9). Just added rewrite_tag_filter to make one namespace use plaintext logging.
 <ROOT>
  <source>
    @type prometheus
    @id in_prometheus
    bind "0.0.0.0"
    port 24231
    metrics_path "/metrics"
  </source>
  <source>
    @type prometheus_output_monitor
    @id in_prometheus_output_monitor
  </source>
  <label @FLUENT_LOG>
    <match fluent.**>
      @type null
      @id ignore_fluent_logs
    </match>
  </label>
  <source>
    @type tail
    @id in_tail_cluster_autoscaler
    multiline_flush_interval 5s
    path "/var/log/cluster-autoscaler.log"
    pos_file "/var/log/fluentd-cluster-autoscaler.log.pos"
    tag "cluster-autoscaler"
    <parse>
      @type "kubernetes"
      unmatched_lines
      expression /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/m
      time_format "%m%d %H:%M:%S.%N"
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_container_logs
    path "/var/log/containers/*.log"
    pos_file "/var/log/fluentd-containers.log.pos"
    tag "kubernetes.*"
    exclude_path []
    read_from_head true
    <parse>
      @type "cri"
      time_format "%Y-%m-%dT%H:%M:%S.%NZ"
      unmatched_lines
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_docker
    path "/var/log/docker.log"
    pos_file "/var/log/fluentd-docker.log.pos"
    tag "docker"
    <parse>
      @type "regexp"
      expression /^time="(?<time>[^)]*)" level=(?<severity>[^ ]*) msg="(?<message>[^"]*)"( err="(?<error>[^"]*)")?( statusCode=($<status_code>\d+))?/
      unmatched_lines
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_etcd
    path "/var/log/etcd.log"
    pos_file "/var/log/fluentd-etcd.log.pos"
    tag "etcd"
    <parse>
      @type "none"
      unmatched_lines
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_glbc
    multiline_flush_interval 5s
    path "/var/log/glbc.log"
    pos_file "/var/log/fluentd-glbc.log.pos"
    tag "glbc"
    <parse>
      @type "kubernetes"
      unmatched_lines
      expression /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/m
      time_format "%m%d %H:%M:%S.%N"
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_kube_apiserver_audit
    multiline_flush_interval 5s
    path "/var/log/kubernetes/kube-apiserver-audit.log"
    pos_file "/var/log/kube-apiserver-audit.log.pos"
    tag "kube-apiserver-audit"
    <parse>
      @type "multiline"
      format_firstline "/^\\S+\\s+AUDIT:/"
      format1 /^(?<time>\S+) AUDIT:(?: (?:id="(?<id>(?:[^"\\]|\\.)*)"|ip="(?<ip>(?:[^"\\]|\\.)*)"|method="(?<method>(?:[^"\\]|\\.)*)"|user="(?<user>(?:[^"\\]|\\.)*)"|groups="(?<groups>(?:[^"\\]|\\.)*)"|as="(?<as>(?:[^"\\]|\\.)*)"|asgroups="(?<asgroups>(?:[^"\\]|\\.)*)"|namespace="(?<namespace>(?:[^"\\]|\\.)*)"|uri="(?<uri>(?:[^"\\]|\\.)*)"|response="(?<response>(?:[^"\\]|\\.)*)"|\w+="(?:[^"\\]|\\.)*"))*/
      time_format "%Y-%m-%dT%T.%L%Z"
      unmatched_lines
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_kube_apiserver
    multiline_flush_interval 5s
    path "/var/log/kube-apiserver.log"
    pos_file "/var/log/fluentd-kube-apiserver.log.pos"
    tag "kube-apiserver"
    <parse>
      @type "kubernetes"
      unmatched_lines
      expression /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/m
      time_format "%m%d %H:%M:%S.%N"
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_kube_controller_manager
    multiline_flush_interval 5s
    path "/var/log/kube-controller-manager.log"
    pos_file "/var/log/fluentd-kube-controller-manager.log.pos"
    tag "kube-controller-manager"
    <parse>
      @type "kubernetes"
      unmatched_lines
      expression /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/m
      time_format "%m%d %H:%M:%S.%N"
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_kube_proxy
    multiline_flush_interval 5s
    path "/var/log/kube-proxy.log"
    pos_file "/var/log/fluentd-kube-proxy.log.pos"
    tag "kube-proxy"
    <parse>
      @type "kubernetes"
      unmatched_lines
      expression /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/m
      time_format "%m%d %H:%M:%S.%N"
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_kube_scheduler
    multiline_flush_interval 5s
    path "/var/log/kube-scheduler.log"
    pos_file "/var/log/fluentd-kube-scheduler.log.pos"
    tag "kube-scheduler"
    <parse>
      @type "kubernetes"
      unmatched_lines
      expression /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/m
      time_format "%m%d %H:%M:%S.%N"
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_kubelet
    multiline_flush_interval 5s
    path "/var/log/kubelet.log"
    pos_file "/var/log/fluentd-kubelet.log.pos"
    tag "kubelet"
    <parse>
      @type "kubernetes"
      unmatched_lines
      expression /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/m
      time_format "%m%d %H:%M:%S.%N"
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_rescheduler
    multiline_flush_interval 5s
    path "/var/log/rescheduler.log"
    pos_file "/var/log/fluentd-rescheduler.log.pos"
    tag "rescheduler"
    <parse>
      @type "kubernetes"
      unmatched_lines
      expression /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/m
      time_format "%m%d %H:%M:%S.%N"
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_minion
    path "/var/log/salt/minion"
    pos_file "/var/log/fluentd-salt.pos"
    tag "salt"
    <parse>
      @type "regexp"
      expression /^(?<time>[^ ]* [^ ,]*)[^\[]*\[[^\]]*\]\[(?<severity>[^ \]]*) *\] (?<message>.*)$/
      time_format "%Y-%m-%d %H:%M:%S"
      unmatched_lines
    </parse>
  </source>
  <source>
    @type tail
    @id in_tail_startupscript
    path "/var/log/startupscript.log"
    pos_file "/var/log/fluentd-startupscript.log.pos"
    tag "startupscript"
    <parse>
      @type "syslog"
      unmatched_lines
    </parse>
  </source>
  <filter kubernetes.**>
    @type kubernetes_metadata
    @id filter_kube_metadata
    kubernetes_url "https://172.20.0.1:443/api"
    verify_ssl true
    ca_file ""
    skip_labels true
    skip_container_metadata false
    skip_master_url true
    skip_namespace_metadata true
    watch true
  </filter>
  <match kubernetes.**>
    @type rewrite_tag_filter
    <rule>
      key "$[\'kubernetes\'][\'namespace_name\']"
      pattern ^beta$
      tag "plaintext.app"
    </rule>
    <rule>
      key "$[\'kubernetes\'][\'namespace_name\']"
      pattern ^beta$
      tag "normal.app"
      invert true
    </rule>
  </match>
  <filter plaintext.app>
    @id filter_plaintext_parser
    @type parser
    key_name "message"
    reserve_time true
    reserve_data true
    remove_key_name_field true
    inject_key_prefix "log."
    <parse>
      @type "none"
    </parse>
  </filter>
  <filter normal.app>
    @id filter_parser
    @type parser
    key_name "message"
    reserve_time true
    reserve_data true
    remove_key_name_field true
    inject_key_prefix "log."
    <parse>
      @type "multi_format"
      <pattern>
        format json
      </pattern>
      <pattern>
        format none
      </pattern>
    </parse>
  </filter>
  <match **>
    @type elasticsearch
    @id out_es
    @log_level "info"
    include_tag_key true
    host "elasticsearch-elasticsearch.elasticsearch"
    port 9200
    path ""
    scheme https
    ssl_verify false
    ssl_version TLSv1_2
    user "logstash"
    password xxxxxx
    reload_connections false
    reconnect_on_error true
    reload_on_failure false
    log_es_400_reason true
    logstash_prefix "logstash-staging"
    logstash_dateformat "%Y.%m.%d"
    logstash_format true
    index_name "logstash"
    target_index_key
    type_name "fluentd"
    include_timestamp false
    template_name
    template_file
    template_overwrite false
    sniffer_class_name "Fluent::Plugin::ElasticsearchSimpleSniffer"
    request_timeout 5s
    application_name default
    suppress_type_name true
    enable_ilm false
    ilm_policy_id logstash-policy
    ilm_policy {}
    ilm_policy_overwrite false
    <buffer>
      flush_thread_count 8
      flush_interval 5s
      chunk_limit_size 2M
      queue_limit_length 256
      retry_max_interval 30
      retry_forever true
    </buffer>
  </match>
</ROOT>
```

### Your Error Log

```shell
Didn't found any error. All are info log like:
`[info]: #0 [filter_kube_metadata] stats - namespace_cache_size: 0, pod_cache_size: 33, pod_cache_watch_delete_ignored: 7, pod_cache_watch_updates: 26, pod_cache_host_updates: 61, pod_cache_watch_ignored: 7, pod_cache_api_updates: 11, id_cache_miss: 11, pod_watch_gone_errors: 1, pod_watch_gone_notices: 1`
or 
`[info]: [filter_kube_metadata] 410 Gone encountered. Restarting pod watch to reset resource versions.410 Gone`
or
`[info]: #0 [filter_kube_metadata] 410 Gone encountered. Restarting pod watch to reset resource versions.410 Gone`
```

### Additional context

Attached a sigdump. When high CPU happen. Normally is happen on thread `flush_thread_2` or `flush_thread_3`. And checked few time. They are same. Except the line contain thread name.

Example for one lof sigdump with `flush_thread_2`:
```
  Thread #<Thread:0x00007f9a8857d300@flush_thread_2@/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/thread.rb:70 run> status=run priority=0
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/socket.rb:284:in `select'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/socket.rb:284:in `select_with_timeout'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/socket.rb:250:in `rescue in block in write_nonblock'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/socket.rb:234:in `block in write_nonblock'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/socket.rb:232:in `loop'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/socket.rb:232:in `write_nonblock'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/socket.rb:81:in `write'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/connection.rb:179:in `request_call'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/middlewares/mock.rb:57:in `request_call'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/middlewares/instrumentor.rb:34:in `request_call'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/middlewares/idempotent.rb:19:in `request_call'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/middlewares/base.rb:22:in `request_call'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/middlewares/base.rb:22:in `request_call'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/excon-0.85.0/lib/excon/connection.rb:273:in `request'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `block in call'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/faraday-1.6.0/lib/faraday/adapter.rb:50:in `connection'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `call'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/faraday-1.6.0/lib/faraday/rack_builder.rb:154:in `build_response'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/faraday-1.6.0/lib/faraday/connection.rb:495:in `run_request'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:48:in `block in perform_request'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:288:in `perform_request'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/client.rb:192:in `perform_request'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/actions/bulk.rb:69:in `bulk'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-5.0.5/lib/fluent/plugin/out_elasticsearch.rb:1110:in `send_bulk'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-5.0.5/lib/fluent/plugin/out_elasticsearch.rb:878:in `block in write'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-5.0.5/lib/fluent/plugin/out_elasticsearch.rb:877:in `each'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-5.0.5/lib/fluent/plugin/out_elasticsearch.rb:877:in `write'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:1138:in `try_flush'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:1450:in `flush_thread_run'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'
      /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

This sigdump is busy on `flush_thread_3` [sigdump.txt](https://github.com/fluent/fluentd/files/10803838/sigdump.txt)

After restart fluentd or delete that particular pod. sigdump showing those flush_thread are `sleep`.

**Comment by alantang888** [comment]
I tried change the docker image to `fluent/fluentd-kubernetes-daemonset:v1.15.3-debian-opensearch-1.1`. Also got the same result.

```
  Thread #<Thread:0x00007eff2b5bccb0@flush_thread_0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/thread.rb:70 sleep> status=sleep priority=0
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/socket.rb:305:in `select'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/socket.rb:305:in `select_with_timeout'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/socket.rb:271:in `rescue in block in write_nonblock'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/socket.rb:255:in `block in write_nonblock'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/socket.rb:253:in `loop'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/socket.rb:253:in `write_nonblock'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/socket.rb:95:in `write'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/connection.rb:182:in `request_call'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/middlewares/mock.rb:57:in `request_call'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/middlewares/instrumentor.rb:34:in `request_call'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/middlewares/idempotent.rb:19:in `request_call'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/middlewares/base.rb:22:in `request_call'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/middlewares/base.rb:22:in `request_call'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/connection.rb:286:in `request'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `block in call'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/adapter.rb:50:in `connection'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `call'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:154:in `build_response'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/connection.rb:516:in `run_request'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/opensearch-transport-2.1.0/lib/opensearch/transport/transport/http/faraday.rb:56:in `block in perform_request'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/opensearch-transport-2.1.0/lib/opensearch/transport/transport/base.rb:297:in `perform_request'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/opensearch-transport-2.1.0/lib/opensearch/transport/transport/http/faraday.rb:45:in `perform_request'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/opensearch-transport-2.1.0/lib/opensearch/transport/client.rb:193:in `perform_request'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/opensearch-ruby-2.1.0/lib/opensearch.rb:48:in `method_missing'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/opensearch-api-2.1.0/lib/opensearch/api/actions/bulk.rb:72:in `bulk'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-opensearch-1.0.10/lib/fluent/plugin/out_opensearch.rb:1106:in `send_bulk'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-opensearch-1.0.10/lib/fluent/plugin/out_opensearch.rb:907:in `block in write'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-opensearch-1.0.10/lib/fluent/plugin/out_opensearch.rb:906:in `each'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-opensearch-1.0.10/lib/fluent/plugin/out_opensearch.rb:906:in `write'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1180:in `try_flush'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1501:in `flush_thread_run'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:501:in `block (2 levels) in start'
      /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by alantang888** [comment]
Just tried increase that particular deployment to 2 replicas. Then after few days. Fluentd with those pods. Both high CPU. They are not happen on same time. That have around 1.5 hrs different.

**Comment by alantang888** [comment]
Something is more strange. Even we suppress log message. Only few start log will print to stdout. The same thing situation still can happen. Is that something wrong on fluentd K8S plugin??

**Comment by alantang888** [comment]
Hello, @daipom would you mind to help is that fluentd bug? Or any plug-in bug? Or anything I can try?? I really no idea what's happen on this T____T

**Comment by daipom** [comment]
We need to identify which plugin is consuming CPU.

In looking at the sigdumps, it may be possible that `faraday`, which is commonly used by `out_elasticsearch` and `out_opensearch`, is the cause.

Please replace them with `out_stdout` and see if the same phenomenon occurs.

```xml
<match **>
  @type stdout
</match>
```

**Comment by alantang888** [comment]
Changed to `@type null` not such issue. So can close this ticket.
