### ISSUE TITLE
Why do Fluentd aggregators stop flushing buffers once in a while and refuse to resume flushing after restart?

### ISSUE THREAD

**Issue by gerib** [fluent/fluentd#4068]
We have two hosts running Fluentd aggregators in `podman` containers with 3 workers each which output events to Elasticsearch:
```
# podman ps
CONTAINER ID  IMAGE                                                                       COMMAND     CREATED      STATUS          PORTS       NAMES
817f630d06a3  [...]/fluentd-aggregator:prod-v1.14.0-1.0  fluentd     3 hours ago  Up 3 hours ago              fluentd

# ps -ef|grep fluentd
root      104791       1  0 10:42 ?        00:00:08 /usr/bin/podman run --net host -v /etc/fluentd:/fluentd/etc -v /var/lib/fluentd/buffer:/fluentd/buffer --hostname fluentd --name fluentd -p 0.0.0.0:3001:3001/tcp -p 0.0.0.0:3002:3002/tcp [...Gitlab repo...]/fluentd-aggregator:prod-v1.14.0-1.0
root      104803       1  0 10:42 ?        00:00:00 /usr/bin/conmon --api-version 1 -c 817f630d06a3216ff5bbab09a7517f8f3666d2141efcb1cd98fb53cab0a7d027 -u 817f630d06a3216ff5bbab09a7517f8f3666d2141efcb1cd98fb53cab0a7d027 -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/817f630d06a3216ff5bbab09a7517f8f3666d2141efcb1cd98fb53cab0a7d027/userdata -p /run/containers/storage/overlay-containers/817f630d06a3216ff5bbab09a7517f8f3666d2141efcb1cd98fb53cab0a7d027/userdata/pidfile -n fluentd --exit-dir /run/libpod/exits --full-attach -s -l k8s-file:/var/lib/containers/storage/overlay-containers/817f630d06a3216ff5bbab09a7517f8f3666d2141efcb1cd98fb53cab0a7d027/userdata/ctr.log --log-level warning --runtime-arg --log-format=json --runtime-arg --log --runtime-arg=/run/containers/storage/overlay-containers/817f630d06a3216ff5bbab09a7517f8f3666d2141efcb1cd98fb53cab0a7d027/userdata/oci-log --conmon-pidfile /run/containers/storage/overlay-containers/817f630d06a3216ff5bbab09a7517f8f3666d2141efcb1cd98fb53cab0a7d027/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /var/lib/containers/storage --exit-command-arg --runroot --exit-command-arg /run/containers/storage --exit-command-arg --log-level --exit-command-arg warning --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/libpod --exit-command-arg --network-config-dir --exit-command-arg  --exit-command-arg --network-backend --exit-command-arg cni --exit-command-arg --volumepath --exit-command-arg /var/lib/containers/storage/volumes --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.mountopt=nodev,metacopy=on --exit-command-arg --events-backend --exit-command-arg file --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 817f630d06a3216ff5bbab09a7517f8f3666d2141efcb1cd98fb53cab0a7d027
fluent    104815  104803  0 10:42 ?        00:00:00 tini -- /bin/entrypoint.sh fluentd
fluent    104827  104815  0 10:42 ?        00:00:06 /usr/bin/ruby /usr/bin/fluentd --config /fluentd/etc/fluent.conf --plugin /fluentd/plugins
fluent    104846  104827 79 10:42 ?        02:23:32 /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd --config /fluentd/etc/fluent.conf --plugin /fluentd/plugins --under-supervisor
fluent    104847  104827 82 10:42 ?        02:27:40 /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd --config /fluentd/etc/fluent.conf --plugin /fluentd/plugins --under-supervisor
fluent    104848  104827 79 10:42 ?        02:22:26 /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd --config /fluentd/etc/fluent.conf --plugin /fluentd/plugins --under-supervisor
```
Once in a while some or all workers on both hosts stop flushing their file buffers. This happened (once more) this morning at ~9:30am (all times in UTC+01:00).

----
### Parenthesis

The suggested usual "quickfix" is (since 1.5 yrs I'm with this company, which may be quick but is not a fix at all but a brute-force action):

Remove all buffer files:
````
systemctl stop fluentd
rm -rf /var/lib/fluentd/buffer/*
systemctl start fluentd
````
Restart all forwarders:
````
kubectl config use-context internal
kubectl delete pods -n kube-system --selector=k8s-app=fluentd-logging
kubectl config use-context dmz
kubectl delete pods -n kube-system --selector=k8s-app=fluentd-logging
````
After that it works for a while, but we can count on it that it will happen again...and it does...reliably. It's only a matter of _when_, not of _if_. It happened appx. a dozen times in the past 1.5 yrs and my patience is at an end, I'm tired of applying this "fix". I really want to solve and get rid of this finally once and forever!

----
Now, this time I just restarted the aggregator services (to keep the buffer files for error tracing) at ~10:30am. They started to work again but existing buffer files haven't been flushed (the deep valley in the chart below stays at the baseline). And...some buffers haven't been flushed again from ~11:30 on.

Then I forced the buffers to be flushed according to [_Fluentd, Deployment, Signals_](https://docs.fluentd.org/deployment/signals#sigusr1)...or tried, at least:
```
# ps -ef|grep ruby
fluent     83489   83477  0 10:39 ?        00:00:08 /usr/bin/ruby /usr/bin/fluentd --config /fluentd/etc/fluent.conf --plugin /fluentd/plugins
fluent     83507   83489 95 10:39 ?        04:10:40 /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd --config /fluentd/etc/fluent.conf --plugin /fluentd/plugins --under-supervisor
fluent     83508   83489 94 10:39 ?        04:10:00 /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd --config /fluentd/etc/fluent.conf --plugin /fluentd/plugins --under-supervisor
fluent     83509   83489 95 10:39 ?        04:10:45 /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd --config /fluentd/etc/fluent.conf --plugin /fluentd/plugins --under-supervisor

# pkill -ce -SIGUSR1 ruby
ruby killed (pid 104846)
ruby killed (pid 104847)
ruby killed (pid 104848)
3
```
To no avail. The deep valley in the chart below stays at the baseline:

![fluentd-error-2023-02-23-detail](https://user-images.githubusercontent.com/13812402/220974793-0418d162-2df1-4d32-8f7f-edfd196049c3.png)

I don't know where the second deep valley at ~14:40 comes from. AFAIK nobody did anything on any included host.

See yesterday (2/22) how it looks normally (except the spike down at ~14:45 which is also not normal):

![fluentd-error-2023-02-23-overview](https://user-images.githubusercontent.com/13812402/221003635-7d3f5504-2cd4-4dd2-9a37-8046cea9617c.png)

### To Reproduce

Can't be reproduced at will. Happens once in a while all of a sudden.

### Expected behaviour

1. Flushing of file buffers doesn't stop once in a while all of a sudden.
2. Flushing of existing file buffers is resumed after Fluentd service restart.
3. Sending signal `SIGUSR1` according to [_Fluentd, Deployment, Signals_](https://docs.fluentd.org/deployment/signals#sigusr1) flushes file buffers. (BTW, what's exactly meant by "_and reopens Fluentd's log_" there? That the log is opened in write and not in append mode, such losing the previous log?)

### Environment
- Fluentd version: v1.14.0-1.0
- Operating system:
````
# cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.6 (Sky Tiger)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.6 (Sky Tiger)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.6"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
````
- Kernel version:
```
# uname -a
Linux [...host...] 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Tue Sep 13 06:07:14 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```
### Configuration

Which of the 5,119 lines of our `fluent.conf` would you like to see?

### Error Log
```shell
2023-02-23 09:46:54 +0000 [error]: #0 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/k8s-nginx-ingress.buffer/worker0/buffer.b5f55adfd6810c4ea97dc90b139b96638.log"
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer/file_chunk.rb:148:in `size'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer/file_chunk.rb:148:in `close'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:479:in `block (2 levels) in enqueue_chunk'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:477:in `block in enqueue_chunk'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:476:in `enqueue_chunk'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:535:in `block in enqueue_all'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:528:in `each'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:528:in `enqueue_all'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/output.rb:1435:in `enqueue_thread_run'
  2023-02-23 09:46:54 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-02-23 09:47:01 +0000 [error]: #2 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/k8s-nginx-ingress.buffer/worker2/buffer.b5f55adf9b2e8d8b6856188feff29c14a.log"
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer/file_chunk.rb:148:in `size'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer/file_chunk.rb:148:in `close'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:479:in `block (2 levels) in enqueue_chunk'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:477:in `block in enqueue_chunk'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:476:in `enqueue_chunk'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:535:in `block in enqueue_all'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:528:in `each'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:528:in `enqueue_all'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/output.rb:1435:in `enqueue_thread_run'
  2023-02-23 09:47:01 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-02-23 09:50:06 +0000 [error]: #0 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/k8s-nginx-ingress.buffer/worker0/buffer.b5f55aeb7e5a3885fdef6ce3fe009eef5.log"
  2023-02-23 09:50:06 +0000 [error]: #0 suppressed same stacktrace
2023-02-23 09:50:42 +0000 [error]: #1 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/k8s-nginx-ingress.buffer/worker1/buffer.b5f55aede275ef1106e082c9c6dccf78c.log"
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer/file_chunk.rb:148:in `size'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer/file_chunk.rb:148:in `close'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:479:in `block (2 levels) in enqueue_chunk'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:477:in `block in enqueue_chunk'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:476:in `enqueue_chunk'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:535:in `block in enqueue_all'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:528:in `each'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:528:in `enqueue_all'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/output.rb:1435:in `enqueue_thread_run'
  2023-02-23 09:50:42 +0000 [error]: #1 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-02-23 09:58:39 +0000 [error]: #0 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/k8s-nginx-ingress.buffer/worker0/buffer.b5f55b09975c8038b8c3cbf2129962989.log"
  2023-02-23 09:58:39 +0000 [error]: #0 suppressed same stacktrace
2023-02-23 09:58:39 +0000 [error]: #1 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/k8s-nginx-ingress.buffer/worker1/buffer.b5f55b0a1b21f6741ad0600db0d4c06a3.log"
  2023-02-23 09:58:39 +0000 [error]: #1 suppressed same stacktrace
2023-02-23 10:00:44 +0000 [error]: #2 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/k8s-nginx-ingress.buffer/worker2/buffer.b5f55b1203a3503bd307d78d70363a8aa.log"
  2023-02-23 10:00:44 +0000 [error]: #2 suppressed same stacktrace
2023-02-23 10:06:40 +0000 [error]: #1 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/k8s-nginx-ingress.buffer/worker1/buffer.b5f55b2707209707f74b38bcbf987d4d4.log"
  2023-02-23 10:06:40 +0000 [error]: #1 suppressed same stacktrace
2023-02-23 10:06:58 +0000 [error]: #2 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/k8s-nginx-ingress.buffer/worker2/buffer.b5f55b2738b8099ae274e52b7706ca7d8.log"
  2023-02-23 10:06:58 +0000 [error]: #2 suppressed same stacktrace
2023-02-23 10:13:16 +0000 [error]: #2 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/k8s-nginx-ingress.buffer/worker2/buffer.b5f55b3d7f8e0614fec1d9e2ddd57ba14.log"
  2023-02-23 10:13:16 +0000 [error]: #2 suppressed same stacktrace
2023-02-23 10:16:18 +0000 [error]: #1 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/k8s-nginx-ingress.buffer/worker1/buffer.b5f55b49a405e4cf89b1453eaad071799.log"
  2023-02-23 10:16:18 +0000 [error]: #1 suppressed same stacktrace
2023-02-23 13:19:31 +0000 [error]: #2 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/joe-wrapper-prod.buffer/worker2/buffer.b5f55dd91ac1c53501f7c5e976deab6f9.log"
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer/file_chunk.rb:148:in `size'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer/file_chunk.rb:148:in `close'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:479:in `block (2 levels) in enqueue_chunk'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:477:in `block in enqueue_chunk'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:476:in `enqueue_chunk'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:535:in `block in enqueue_all'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:528:in `each'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:528:in `enqueue_all'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/output.rb:1435:in `enqueue_thread_run'
  2023-02-23 13:19:31 +0000 [error]: #2 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-02-23 13:24:23 +0000 [error]: #0 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/joe-wrapper-prod.buffer/worker0/buffer.b5f55deac2524eca7abd62d1ac2d3b1ca.log"
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer/file_chunk.rb:148:in `size'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer/file_chunk.rb:148:in `close'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:479:in `block (2 levels) in enqueue_chunk'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:477:in `block in enqueue_chunk'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:476:in `enqueue_chunk'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:535:in `block in enqueue_all'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:528:in `each'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/buffer.rb:528:in `enqueue_all'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin/output.rb:1435:in `enqueue_thread_run'
  2023-02-23 13:24:23 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-02-23 13:45:40 +0000 [error]: #2 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/joe-wrapper-prod.buffer/worker2/buffer.b5f55e3676136fe308bb0d58da8f9b273.log"
  2023-02-23 13:45:40 +0000 [error]: #2 suppressed same stacktrace
2023-02-23 14:11:51 +0000 [error]: #2 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/joe-wrapper-prod.buffer/worker2/buffer.b5f55e943651f84436270be3d7e8398a5.log"
  2023-02-23 14:11:51 +0000 [error]: #2 suppressed same stacktrace
```

**Comment by daipom** [comment]
I have no idea what caused it, but similar problems have been reported.

* #4109

**Comment by daipom** [comment]
Do you get this error every time this occurs?

> 2023-02-23 09:46:54 +0000 [error]: #0 unexpected error while checking flushed chunks. ignored. error_class=Errno::EACCES error="Permission denied @ rb_file_size - /fluentd/buffer/k8s-nginx-ingress.buffer/worker0/buffer.b5f55adfd6810c4ea97dc90b139b96638.log"

**Comment by gerib** [comment]
IDK, AFAIK this is the first time someone – me – digged deeper into it and if the "quickifx" is applied the podman container's log is gone. I'm going to check `journalctl` and if I can't find anything related there I'll check next time it occurs.

**Comment by daipom** [comment]
Thanks.

**Comment by gerib** [comment]
@daipom Closing the issue for the time being. I'm not working in this field any longer so I can't check to give an update here.
