### ISSUE TITLE
undefined method `force_encoding' for nil:NilClass when reloading match with buffers kafka2 to forward

### ISSUE THREAD

**Issue by juliantaylor** [fluent/fluentd#4130]
### Describe the bug

When reloading configurations from kafka2 to the forward plugin and using persistent buffers.

The error is:
```
2023-04-06 13:25:47 +0000 [warn]: #0 [out_forward_tenant] got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `force_encoding' for nil:NilClass\n\n        tag = tag.dup.force_encoding(Encoding::UTF_8)\n                     ^^^^^^^^^^^^^^^"
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:660:in `send_data_actual'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:678:in `block in send_data'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward/connection_manager.rb:54:in `connect'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:807:in `connect'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:676:in `send_data'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:365:in `block in write'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward/load_balancer.rb:46:in `block in select_healthy_node'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward/load_balancer.rb:37:in `times'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward/load_balancer.rb:37:in `select_healthy_node'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/service_discovery/manager.rb:108:in `select_service'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/service_discovery.rb:82:in `service_discovery_select_service'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:365:in `write'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1180:in `try_flush'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/out_forward.rb:353:in `try_flush'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1501:in `flush_thread_run'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:501:in `block (2 levels) in start'
2023-04-06 13:25:47 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-04-06 13:25:47 +0000 [warn]: #0 [out_forward_store] bad chunk is moved to /tmp/fluent/backup/worker0/out_forward_store/5f8aad5016762550f1de6f57acd3211c.log
```

the configuration is changed from kafka2 to forward.
The logsinks are fully functional and and should flush correctly on reloading (no errors on flushing).

### To Reproduce

kafka2 configuration it starts out with:

```
 <match kubernetes.pods.tenant-**>
  @type kafka2
  @id out_kafka_tenant
  brokers kafka01.kafka-qa.domain:9093,kafka02.kafka-qa.domain:9093,kafka03.kafka-qa.domain:9093
  ssl_ca_certs_from_system true
  default_topic "topic"
  max_send_limit_bytes 1000000
  <inject>
    tag_key "tag"
    time_key "time"
  </inject>
  <format>
    @type "json"
  </format>
  <buffer>
    @type "file"
    path "/var/lib/fluentd/buffer-tenant"
    overflow_action block
    flush_thread_count 4
    chunk_limit_size 524288
    retry_max_interval 3600
  </buffer>
</match>
```

reloaded to:

```
  <match kubernetes.pods.tenant-**>
    @type forward
    @id out_forward_applogstore_tenant
    send_timeout 120s
    connect_timeout 5s
    expire_dns_cache 60s
    ignore_network_errors_at_startup true
    recover_wait 10s
    hard_timeout 120s
    heartbeat_type none
    keepalive false
    tls_verify_hostname false
    time_as_integer false
    transport tls
    <server>
      host "host.domain"
      port 13414
      weight 90
    </server>
    <buffer>
      @type "file"
      path "/var/lib/fluentd/buffer-tenant"
      total_limit_size 512MB
      chunk_limit_size 32MB
      chunk_full_threshold 0.50
      flush_thread_count 2
      flush_at_shutdown true
      flush_mode interval 
      flush_interval 30s
      overflow_action drop_oldest_chunk
      retry_max_interval 120s
    </buffer>
  </match>
```

### Expected behavior

Changing out match should work without errors at least after they have properly flushed.

### Your Environment

```markdown
- Fluentd version: 1.15.3
- TD Agent version: 4.4.2-1
- Operating system: flatcar linux stable
- Kernel version: 5.15

kafka2 version 0.18.1
```

### Your Configuration

```apache
see above
```

### Your Error Log

```shell
see above
```

### Additional context

The issue is also reproducable with td-agent 4.3.1-1/fluentd 1.14

**Comment by daipom** [comment]
@juliantaylor Could you please tell me how you reload?

Somehow the metadata of the chunk seems to be broken.

https://github.com/fluent/fluentd/blob/e89092ce1132a933c12bb23fe8c9323c07ca81f5/lib/fluent/plugin/out_forward.rb#L374-L375

https://github.com/fluent/fluentd/blob/e89092ce1132a933c12bb23fe8c9323c07ca81f5/lib/fluent/plugin/out_forward.rb#L660

**Comment by juliantaylor** [comment]
reload is done by calling `api/config.reload`

**Comment by daipom** [comment]
Thanks.

Isn't it possible that `out_forward` got an error trying to process the buffer file of `out_kafka2` remaining?

`api/config.reload` seems not to flush file buffers.

* https://docs.fluentd.org/deployment/rpc#http-endpoints
* https://docs.fluentd.org/deployment/signals#sighup

**Comment by juliantaylor** [comment]
so buffers are not supposed to be compatible between different plugins?

mentioning that on the reload documentation would be good.

**Comment by daipom** [comment]
I don't think there is any mention of it being compatible or not compatible.
So I think it is natural to assume that compatibility is not guaranteed.

In this case, the remained data wil not be sent in the correct format (MessagePack) since it is formatted as JSON in the previous setting.

```xml
  <format>
    @type "json"
  </format>
```

However, I am concerned about how the error appears.
I will look into this a bit.

**Comment by daipom** [comment]
For now, I suggest setting `flush_at_shutdown true` and stopping Fluentd once to clear the buffer.

**Comment by daipom** [comment]
Or use the different buffer path.

**Comment by juliantaylor** [comment]
ah yes flush_at_shutdown was what I was missing to have a clean switch path, thanks Ill try that and if thats not enough a second path should works fine.

**Comment by daipom** [comment]
Sorry for the delay.

> I don't think there is any mention of it being compatible or not compatible. So I think it is natural to assume that compatibility is not guaranteed.
> 
> In this case, the remained data wil not be sent in the correct format (MessagePack) since it is formatted as JSON in the previous setting.
> 
> ```
>   <format>
>     @type "json"
>   </format>
> ```
> 
> However, I am concerned about how the error appears. I will look into this a bit.

I have checked this.
As expected, data stored in JSON format will be corrupted as `out_forward` tries to read it as MessagePack format.

However, the error message says `tag` data is `nil`.
That is strange because it is kept as metadata in a consistent format separate from the record data itself.
I could not find the cause of this error.

Anyway, it is for sure not possible to share the buffer with different pluings.
So please try the followings.

> using the different buffer path.

> setting flush_at_shutdown true and stopping Fluentd once to clear the buffer.

If you have any more problems, please reopen this.
