### ISSUE TITLE
NoMethodError, Error undefined method `to_i' for Timestamp

### ISSUE THREAD

**Issue by LeoWinterDE** [fluent/fluentd#4163]
### Describe the bug

Our log and metric pipeline goes via [fluentbit forward out](https://docs.fluentbit.io/manual/pipeline/outputs/forward) to [fleuntd forward in](https://docs.fluentd.org/input/forward), there we get the following errors lately:

```
2023-05-03 09:20:41 +0000 [error]: #0 [input-forward-metric] unexpected error on reading data host="SOME.HOST.NAME" port=60820 error_class=NoMethodError error="undefined method `to_i' for [2023-05-03 09:20:36.264160528 +0000, {}]:Array\nDid you mean?  to_s\n               to_a\n               to_h"
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:330:in `block in on_message'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:326:in `each'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:326:in `on_message'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:226:in `block in handle_connection'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:263:in `block (3 levels) in read_messages'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:262:in `feed_each'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:262:in `block (2 levels) in read_messages'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:271:in `block in read_messages'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/server.rb:791:in `on_read_without_connection'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:123:in `on_readable'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/server.rb:752:in `on_readable'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:186:in `on_readable'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-05-03 09:20:41 +0000 [error]: #0 [input-forward-log] unexpected error on reading data host="SOME.HOST.NAME" port=58021
error_class=NoMethodError error="undefined method `to_i' for [2023-05-03 09:20:36.218898200 +0000, {}]:Array\nDid you mean?  to_s\n               to_a\n               to_h"
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:330:in `block in on_message'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:326:in `each'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:326:in `on_message'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:226:in `block in handle_connection'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:263:in `block (3 levels) in read_messages'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:262:in `feed_each'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:262:in `block (2 levels) in read_messages'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:271:in `block in read_messages'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/server.rb:791:in `on_read_without_connection'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:123:in `on_readable'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/server.rb:752:in `on_readable'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:186:in `on_readable'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-05-03 09:20:41 +0000 [error]: #0 [input-forward-log] unexpected error on reading data host="SOMEOTHER.HOST.NAME" port=58554 error_class=NoMethodError error="undefined method `to_i' for [2023-05-03 09:20:25.872351700 +0000, {}]:Array\nDid you mean?  to_s\n               to_a\n               to_h"
  2023-05-03 09:20:41 +0000 [error]: #0 suppressed same stacktrace
2023-05-03 09:20:41 +0000 [error]: #0 [input-forward-log] unexpected error on reading data host="SOMEOTHER.HOST.NAME" port=44908 error_class=NoMethodError error="undefined method `to_i' for [2023-05-03 09:20:28.397888045 +0000, {}]:Array\nDid you mean?  to_s\n               to_a\n               to_h"
  2023-05-03 09:20:41 +0000 [error]: #0 suppressed same stacktrace
2023-05-03 09:20:42 +0000 [error]: #0 [input-forward-metric] unexpected error on reading data host="YET.ANOTHER.HOST.NAME" port=60832 error_class=NoMethodError error="undefined method `to_i' for [2023-05-03 09:20:26.264489499 +0000, {}]:Array\nDid you mean?  to_s\n               to_a\n               to_h"
  2023-05-03 09:20:42 +0000 [error]: #0 suppressed same stacktrace
```

### To Reproduce

Forward logs or metrics from fluent-bit [2.1.1](https://github.com/fluent/fluent-bit/releases/tag/v2.1.1) to td-agent [4.4.2](https://www.fluentd.org/blog/td-agent-v4.4.2-has-been-released) via. [forward](https://docs.fluentd.org/input/forward) option.

### Expected behavior

Forwarding logs and metrics without timestamp error: ```error_class=NoMethodError error="undefined method `to_i' for [2023-05-03 09:20:38.538323451 +0000, {}]:Array\nDid you mean?  to_s\n               to_a\n               to_h"   2023-05-03 09:20:43 +0000 [error]: #0 suppressed same stacktrace```

### Your Environment

```markdown
- Fluentd version: 1.15.3
- Fluent-bit version: 2.1.1
- TD Agent version: 4.4.2
- Operating system: Ubuntu 20.04.6 LTS
- Kernel version: 5.4.0-147-generic #164-Ubuntu
```

### Your Configuration

```apache
...
  <source>
    @type forward
    @id input-forward-log
    port 24224
    bind "0.0.0.0"
    require_ack_response true
    tag "log"
    source_address_key "client_ip"
    source_hostname_key "client_hostname"
    <transport tls>
      cert_path "/etc/td-agent/tls/SOME.cer"
      private_key_path "/etc/td-agent/tls/SOME.key"
    </transport>
  </source>
...
  <source>
    @type forward
    @id input-forward-metric
    port 24225
    bind "0.0.0.0"
    require_ack_response true
    tag "metric"
    source_address_key "client_ip"
    source_hostname_key "client_hostname"
    <transport tls>
      cert_path "/etc/td-agent/tls/SOME.cer"
      private_key_path "/etc/td-agent/tls/SOME.key"
    </transport>
  </source>
...
```

### Your Error Log

```shell
2023-05-03 09:20:41 +0000 [error]: #0 [input-forward-metric] unexpected error on reading data host="SOME.HOST.NAME" port=60820 error_class=NoMethodError error="undefined method `to_i' for [2023-05-03 09:20:36.264160528 +0000, {}]:Array\nDid you mean?  to_s\n               to_a\n               to_h"
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:330:in `block in on_message'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:326:in `each'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:326:in `on_message'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:226:in `block in handle_connection'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:263:in `block (3 levels) in read_messages'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:262:in `feed_each'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:262:in `block (2 levels) in read_messages'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:271:in `block in read_messages'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/server.rb:791:in `on_read_without_connection'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:123:in `on_readable'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/server.rb:752:in `on_readable'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:186:in `on_readable'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-05-03 09:20:41 +0000 [error]: #0 [input-forward-log] unexpected error on reading data host="SOME.HOST.NAME" port=58021
error_class=NoMethodError error="undefined method `to_i' for [2023-05-03 09:20:36.218898200 +0000, {}]:Array\nDid you mean?  to_s\n               to_a\n               to_h"
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:330:in `block in on_message'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:326:in `each'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:326:in `on_message'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:226:in `block in handle_connection'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:263:in `block (3 levels) in read_messages'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:262:in `feed_each'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:262:in `block (2 levels) in read_messages'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_forward.rb:271:in `block in read_messages'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/server.rb:791:in `on_read_without_connection'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:123:in `on_readable'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/server.rb:752:in `on_readable'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:186:in `on_readable'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2023-05-03 09:20:41 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-05-03 09:20:41 +0000 [error]: #0 [input-forward-log] unexpected error on reading data host="SOMEOTHER.HOST.NAME" port=58554 error_class=NoMethodError error="undefined method `to_i' for [2023-05-03 09:20:25.872351700 +0000, {}]:Array\nDid you mean?  to_s\n               to_a\n               to_h"
  2023-05-03 09:20:41 +0000 [error]: #0 suppressed same stacktrace
2023-05-03 09:20:41 +0000 [error]: #0 [input-forward-log] unexpected error on reading data host="SOMEOTHER.HOST.NAME" port=44908 error_class=NoMethodError error="undefined method `to_i' for [2023-05-03 09:20:28.397888045 +0000, {}]:Array\nDid you mean?  to_s\n               to_a\n               to_h"
  2023-05-03 09:20:41 +0000 [error]: #0 suppressed same stacktrace
2023-05-03 09:20:42 +0000 [error]: #0 [input-forward-metric] unexpected error on reading data host="YET.ANOTHER.HOST.NAME" port=60832 error_class=NoMethodError error="undefined method `to_i' for [2023-05-03 09:20:26.264489499 +0000, {}]:Array\nDid you mean?  to_s\n               to_a\n               to_h"
  2023-05-03 09:20:42 +0000 [error]: #0 suppressed same stacktrace
```

**Comment by LeoWinterDE** [comment]
After testing for a while I have determined, its fixed by [Fluent Bit 2.1.2](https://github.com/fluent/fluent-bit/releases/tag/v2.1.2) and does not seem occur in [Fluent Bit 2.1.0](https://github.com/fluent/fluent-bit/releases/tag/v2.1.0).

So its a bug in [Fluent Bit 2.1.1](https://github.com/fluent/fluent-bit/releases/tag/v2.1.1) affecting linux and windows builds 😞

**Comment by kenhys** [comment]
Thanks

FYI:

https://fluentbit.io/announcements/v2.1.2/

> [Forward (Output)](https://docs.fluentbit.io/manual/pipeline/outputs/forward/)
            Added code to drop metadata by default

**Comment by kenhys** [comment]
It seems non fluentd issue, so I'll close it.
