### ISSUE TITLE
Logger: Fails to launch Fluentd without specifying the path in the command line options on Windows with rotation

### ISSUE THREAD

**Issue by daipom** [fluent/fluentd#4187]
### Describe the bug

If you enable log rotation and don't specify the log path, then Fluentd fails to start.

* Windows only
* Since v1.16.0
  * This is a bug of #4091

`nil` check for `@log_path` to be passed to `Fluent::Log.per_process_path()` is missing:

https://github.com/fluent/fluentd/blob/dc7e4b295270d6a521f43331321628dba2692ca4/lib/fluent/supervisor.rb#L696-L705

### To Reproduce

Launch Fluentd with the config below, which enables rotation. 

```console
$ bundle exec fluentd -c fluent.conf
#=> The error below occurs.
```

---

If you specify the log path, this issue doesn't occur.

```console
$ bundle exec fluentd -c fluent.conf -o fluent.log
#=> Fluentd starts correctly.
```

If the config doesn't have rotation options, this issue doesn't occur either.

### Expected behavior

If rotation is enabled but the log file path is not specified,
the rotation setting is ignored, and Fluentd normally starts with output to standard output as before v1.16.0.

### Your Environment

```markdown
- Fluentd version: 1.16.1
- Operating system: Windows Home 10
- Kernel version: 3.1.7-340.x86_64
```

### Your Configuration

```apache
<system>
  <log>
    rotate_age 5
  </log>
</system>

<source>
  @type sample
  tag test
</source>

<match test.**>
  @type stdout
</match>
```

### Your Error Log

```shell
C:/Users/reang/Documents/work/fluentd/fluentd/lib/fluent/log.rb:77:in `initialize': no implicit conversion of nil into String (TypeError)

      path = Pathname(path)
                      ^^^^
        from C:/Users/reang/Documents/work/fluentd/fluentd/lib/fluent/log.rb:77:in `Pathname'
        from C:/Users/reang/Documents/work/fluentd/fluentd/lib/fluent/log.rb:77:in `per_process_path'
        from C:/Users/reang/Documents/work/fluentd/fluentd/lib/fluent/supervisor.rb:701:in `setup_global_logger'
        from C:/Users/reang/Documents/work/fluentd/fluentd/lib/fluent/supervisor.rb:624:in `configure'
        from C:/Users/reang/Documents/work/fluentd/fluentd/lib/fluent/command/fluentd.rb:351:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from C:/Users/reang/Documents/work/fluentd/fluentd/bin/fluentd:15:in `<top (required)>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/bin/fluentd:25:in `load'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/bin/fluentd:25:in `<main>'
```

**Comment by daipom** [comment]
There was a `nil` check for `per_process_path` on v1.15.3:

https://github.com/fluent/fluentd/blob/e89092ce1132a933c12bb23fe8c9323c07ca81f5/lib/fluent/supervisor.rb#L550-L566
