### ISSUE TITLE
On 4.5.0-1 td-agent fails to start - GEM::MissingSpecVersionError for faraday

### ISSUE THREAD

**Issue by mf69** [fluent/fluentd#4204]
### Describe the bug

fluentd fails to start with this error with 4.5.0-1 on Ubuntu 20.04

fluentd[2844091]: /opt/td-agent/lib/ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'faraday' (>= 0.17.3, < 2.0) - did find: [faraday-2.7.4] (Gem::MissingSpecVersionError)

### To Reproduce

Install
sudo apt install td-agent=4.5.0-1

This should start the agent but it fails...
Setting up td-agent (4.5.0-1) ...
Job for td-agent.service failed because the control process exited with error code.                                                                                                                                 
See "systemctl status td-agent.service" and "journalctl -xe" for details.

$ sudo systemctl status td-agent
● td-agent.service - td-agent: Fluentd based data collector for Treasure Data
     Loaded: loaded (/lib/systemd/system/td-agent.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-06-16 20:46:39 UTC; 2min 41s ago
       Docs: https://docs.treasuredata.com/display/public/PD/About+Treasure+Data%27s+Server-Side+Agent
    Process: 2885496 ExecStart=/opt/td-agent/bin/fluentd --log $TD_AGENT_LOG_FILE --daemon /var/run/td-agent/td-agent.pid $TD_AGENT_OPTIONS (code=exited, status=1/FAILURE)

Jun 16 20:46:39 REDACTED systemd[1]: td-agent.service: Failed with result 'exit-code'.
Jun 16 20:46:39 REDACTED systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
Jun 16 20:46:39 REDACTED systemd[1]: td-agent.service: Scheduled restart job, restart counter is at 5.
Jun 16 20:46:39 REDACTED systemd[1]: Stopped td-agent: Fluentd based data collector for Treasure Data.
Jun 16 20:46:39 REDACTED systemd[1]: td-agent.service: Start request repeated too quickly.
Jun 16 20:46:39 REDACTED systemd[1]: td-agent.service: Failed with result 'exit-code'.
Jun 16 20:46:39 REDACTED systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.

Check in /var/log/syslog and find this error
fluentd[2885496]: /opt/td-agent/lib/ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'faraday' (>= 0.17.3, < 2.0) - did find: [faraday-2.7.4] (Gem::MissingSpecVersionError)

### Expected behavior

agent starts successfully

### Your Environment

```markdown
- Fluentd version: 1.16.1
- TD Agent version: 0.17.1
- Operating system: Ubuntu 20.04.6 LTS
- Kernel version: 5.4.0-148-generic
```

### Your Configuration

```apache
omitted for privacy
```

### Your Error Log

```shell
Jun 16 20:46:38 REDACTED systemd[1]: Starting td-agent: Fluentd based data collector for Treasure Data...
Jun 16 20:46:39 REDACTED fluentd[2885496]: /opt/td-agent/lib/ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'faraday' (>= 0.17.3, < 2.0) - did find: [faraday-2.7.4] (Gem::MissingSpecVersionError)
Jun 16 20:46:39 REDACTED fluentd[2885496]: Checked in 'GEM_PATH=/opt/td-agent/lib/ruby/gems/2.7.0', execute `gem env` for more information
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1400:in `block in activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1403:in `block in activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1403:in `block in activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1403:in `block in activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems.rb:217:in `rescue in try_activate'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems.rb:210:in `try_activate'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:151:in `rescue in require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-bigquery-2.3.0/lib/fluent/plugin/out_bigquery_insert.rb:1:in `<top (required)>'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/registry.rb:103:in `block in search'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/registry.rb:100:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/registry.rb:100:in `search'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/registry.rb:44:in `lookup'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/plugin.rb:169:in `new_impl'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/plugin.rb:114:in `new_output'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:130:in `add_match'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:74:in `block in configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:64:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:64:in `configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:149:in `configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/engine.rb:105:in `configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/engine.rb:80:in `run_configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/supervisor.rb:571:in `run_supervisor'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/bin/fluentd:15:in `<top (required)>'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/bin/fluentd:23:in `load'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/bin/fluentd:23:in `<main>'
Jun 16 20:46:39 REDACTED fluentd[2885496]: /opt/td-agent/lib/ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'faraday' (>= 0.17.3, < 2.0) - did find: [faraday-2.7.4] (Gem::MissingSpecVersionError)
Jun 16 20:46:39 REDACTED fluentd[2885496]: Checked in 'GEM_PATH=/opt/td-agent/lib/ruby/gems/2.7.0', execute `gem env` for more information
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1400:in `block in activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1403:in `block in activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1403:in `block in activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1403:in `block in activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `activate_dependencies'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems.rb:211:in `try_activate'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:151:in `rescue in require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-bigquery-2.3.0/lib/fluent/plugin/out_bigquery_insert.rb:1:in `<top (required)>'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/registry.rb:103:in `block in search'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/registry.rb:100:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/registry.rb:100:in `search'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/registry.rb:44:in `lookup'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/plugin.rb:169:in `new_impl'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/plugin.rb:114:in `new_output'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:130:in `add_match'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:74:in `block in configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:64:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:64:in `configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:149:in `configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/engine.rb:105:in `configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/engine.rb:80:in `run_configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/supervisor.rb:571:in `run_supervisor'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/bin/fluentd:15:in `<top (required)>'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/bin/fluentd:23:in `load'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/bin/fluentd:23:in `<main>'
Jun 16 20:46:39 REDACTED fluentd[2885496]: /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- fluent/plugin/out_bigquery_base (LoadError)
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-bigquery-2.3.0/lib/fluent/plugin/out_bigquery_insert.rb:1:in `<top (required)>'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/registry.rb:103:in `block in search'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/registry.rb:100:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/registry.rb:100:in `search'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/registry.rb:44:in `lookup'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/plugin.rb:169:in `new_impl'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/plugin.rb:114:in `new_output'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:130:in `add_match'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:74:in `block in configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:64:in `each'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:64:in `configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:149:in `configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/engine.rb:105:in `configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/engine.rb:80:in `run_configure'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/supervisor.rb:571:in `run_supervisor'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/bin/fluentd:15:in `<top (required)>'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/bin/fluentd:23:in `load'
Jun 16 20:46:39 REDACTED fluentd[2885496]: #011from /opt/td-agent/bin/fluentd:23:in `<main>'
Jun 16 20:46:39 REDACTED systemd[1]: td-agent.service: Control process exited, code=exited, status=1/FAILURE
Jun 16 20:46:39 REDACTED systemd[1]: td-agent.service: Failed with result 'exit-code'.
Jun 16 20:46:39 REDACTED systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
Jun 16 20:46:39 REDACTED systemd[1]: td-agent.service: Scheduled restart job, restart counter is at 5.
Jun 16 20:46:39 REDACTED systemd[1]: Stopped td-agent: Fluentd based data collector for Treasure Data.
Jun 16 20:46:39 REDACTED systemd[1]: td-agent.service: Start request repeated too quickly.
Jun 16 20:46:39 REDACTED systemd[1]: td-agent.service: Failed with result 'exit-code'.
Jun 16 20:46:39 REDACTED systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
```

### Additional context

downgrading to v4.4.2-1 "fixes" the issue for now.

**Comment by mf69** [comment]
Yes that seems to fix it.
