### ISSUE TITLE
Ruby not evaluated in match section of YAML config file

### ISSUE THREAD

**Issue by precisionconage** [fluent/fluentd#4232]
### Describe the bug

I'm trying to read credentials from environment variables to send logs to Loki, but the plugin ends up using the literal string "#{ENV['LOKI_VAR']}" for each variable instead of the environment variable values.

I'm reporting this here instead of against Grafana's plugin since I don't see code to evaluate Ruby blocks anywhere in https://github.com/fluent/fluentd/tree/master/lib/fluent/config/yaml_parser (whereas [v1parser.rb](https://github.com/fluent/fluentd/blob/master/lib/fluent/config/v1_parser.rb) does via [literal_parser.rb](https://github.com/fluent/fluentd/blob/master/lib/fluent/config/literal_parser.rb)), so it looks like an issue in FluentD itself. Please let me know if I should report it there instead.

### To Reproduce

1. Install FluentD
2. Install the Loki plugin with `fluent-gem install fluent-plugin-grafana-loki`
3. Run FluentD with the config file specified in this bug

### Expected behavior

The Ruby blocks are evaluated, and the environment variable values are used.

### Your Environment

```markdown
- Fluentd version: 1.16.1
- TD Agent version: 4.5.0
- Operating system: Windows Server 2012 R2 Standard
- Kernel version: N/A
```

### Your Configuration

```apache
config:
  - source: 
      $type: tail
      tag: test
      path: C:/logs/test.log
      path_key: source
      read_from_head: true
      pos_file: C:/logs/td-agent.pos

  - filter:
      $type: record_transformer
      $tag: test
      enable_ruby: true
      record:
        - env: dev
        - hostname: "#{Socket.gethostname}"

  - match:
      $type: loki
      $tag: test
      url: "#{ENV['LOKI_URL']}"
      username: "#{ENV['LOKI_USERNAME']}"
      password: "#{ENV['LOKI_PASSWORD']}"
      label:
        env: env
        hostname: hostname
```

### Your Error Log

```shell
PS C:\opt\td-agent\bin> .\td-agent.bat -c C:\opt\td-agent\etc\td-agent\td-agent.yml -o C:\opt\td-agent\td-agent.log
Traceback (most recent call last):
        18: from C:/opt/td-agent/bin/fluentd:23:in `<main>'
        17: from C:/opt/td-agent/bin/fluentd:23:in `load'
        16: from C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/bin/fluentd:15:in `<top (required)>'
        15: from C:/opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        14: from C:/opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        13: from C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
        12: from C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/supervisor.rb:571:in `run_supervisor'
        11: from C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/engine.rb:80:in `run_configure'
        10: from C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/engine.rb:105:in `configure'
         9: from C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:149:in `configure'
         8: from C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:64:in `configure'
         7: from C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:64:in `each'
         6: from C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:74:in `block in configure'
         5: from C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/agent.rb:132:in `add_match'
         4: from C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.1/lib/fluent/plugin.rb:187:in `configure'
         3: from C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-grafana-loki-1.2.20/lib/fluent/plugin/out_loki.r
b:88:in `configure'
         2: from C:/opt/td-agent/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
         1: from C:/opt/td-agent/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
C:/opt/td-agent/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "\\#{ENV['LOKI_URL']}/loki/api/v1/push" (URI::InvalidURIError)
```

**Comment by daipom** [comment]
https://docs.fluentd.org/configuration/config-file-yaml#embedded-ruby-code

We need to add prefix !fluent/s for YAML config format.

**Comment by precisionconage** [comment]
This worked, thanks a lot! Not sure I missed it.
