### ISSUE TITLE
worker terminates with "stack level too deep"

### ISSUE THREAD

**Issue by ztdietmaier** [fluent/fluentd#4309]
### Describe the bug

fluentd process terminates with "stack level too deep" and restarts the worker

### To Reproduce

cannot reliably reproduce, error occurs sometimes several times per hour, seems to be unrelated to the load (event rates are between 30 and 150 events per second)

### Expected behavior

worker does not terminate

### Your Environment

```markdown
- Fluentd version: docker image fluentd:v1.16.2-debian-1.0 (but error was also observed with 1.15) running on openshift 4.12
- Kernel version: 4.18.0-372.58.1.el8_6.x86_64
- /var/cache/fluentd/ is a persistent volume
```

### Your Configuration

```apache
<system>
      root_dir /var/cache/fluentd
    </system>

    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <source>
      @type prometheus
      bind 0.0.0.0
      port 24231
      metrics_path /metrics
    </source>
    <source>
      @type prometheus_monitor
    </source>    
    <source>
      @type prometheus_output_monitor
    </source>

# omitted filter sections

    <match "kubernetes.var.log.pods.{{ .Values.global.stage.openshiftNamespace }}_{metricbeat,clustermetrics,logstash}*.**">
      @type elasticsearch_data_stream
      scheme https
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      ssl_verify "#{ENV['SSL_VERIFY']}"
      ssl_version TLSv1_2
      ca_file "#{ENV['CA_FILE']}"
      user "#{ENV['FLUENTD_USERNAME']}"
      password "#{ENV['FLUENTD_PASSWORD']}"
      data_stream_name logs-pod-{{ .Values.global.stage.name }}
      log_es_400_reason true
      bulk_message_request_threshold 2MB
      reload_connections true
      sniffer_class_name Fluent::Plugin::ElasticsearchSimpleSniffer
      @label @ES_FAILED
      <buffer>
        @type file
        path /var/cache/fluentd/buffer/{{ .Values.global.stage.openshiftNamespace }}
        retry_max_times 17
        retry_wait 1.0
        flush_thread_count 2
        total_limit_size 512MB
        chunk_limit_size 12MB
        chunk_full_threshold 0.95
      </buffer>
      <secondary>
        @type secondary_file
        directory /var/cache/fluentd/error/{{ .Values.global.stage.openshiftNamespace }}
      </secondary>
    </match>

    <label @ES_FAILED>
      <match **>
        @type file
        path /var/cache/fluentd/error/{{ .Values.global.stage.openshiftNamespace }}
        <format>
          @type json
        </format>
      </match>
    </label>

    <label @ERROR>
      <match **>
        @type file
        path /var/cache/fluentd/error/
        <format>
          @type json
        </format>
      </match>
    </label>
```

### Your Error Log

```shell
2023-09-25 16:38:32 +0000 [warn]: #0 thread exited by unexpected error plugin=Fluent::Plugin::ForwardInput title=:event_loop error_class=SystemStackError error="stack level too deep"
#<Thread:0x00007f03b9e03468@event_loop /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:60:in `write': stack level too deep (SystemStackError)
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:60:in `block in to_msgpack_stream'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:196:in `block in each'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:195:in `each'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:195:in `each'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:59:in `to_msgpack_stream'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/output.rb:1016:in `block in <class:Output>'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/buffer.rb:670:in `block in write_once'
	from /usr/local/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'
	 ... 21 levels...
	from /usr/local/bundle/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
	from /usr/local/bundle/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-09-25 16:38:32 +0000 [error]: #0 unexpected error error_class=SystemStackError error="stack level too deep"
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:60:in `write'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:60:in `block in to_msgpack_stream'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:196:in `block in each'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:195:in `each'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:195:in `each'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:59:in `to_msgpack_stream'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/output.rb:1016:in `block in <class:Output>'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/buffer.rb:670:in `block in write_once'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/lib/ruby/3.1.0/monitor.rb:202:in `mon_synchronize'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/buffer.rb:661:in `write_once'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/buffer.rb:345:in `block in write'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/buffer.rb:343:in `each'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/buffer.rb:343:in `write'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/output.rb:1095:in `block in handle_stream_simple'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/output.rb:977:in `write_guard'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/output.rb:1094:in `handle_stream_simple'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/output.rb:967:in `execute_chunking'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/output.rb:897:in `emit_buffered'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event_router.rb:196:in `emit_events'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event_router.rb:115:in `emit_stream'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/in_forward.rb:318:in `on_message'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/in_forward.rb:226:in `block in handle_connection'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/in_forward.rb:263:in `block (3 levels) in read_messages'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/in_forward.rb:262:in `feed_each'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/in_forward.rb:262:in `block (2 levels) in read_messages'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/in_forward.rb:271:in `block in read_messages'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/server.rb:640:in `on_read_without_connection'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/cool.io-1.7.1/lib/cool.io/io.rb:123:in `on_readable'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/cool.io-1.7.1/lib/cool.io/io.rb:186:in `on_readable'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2023-09-25 16:38:32 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::PrometheusOutputMonitorInput title=:event_loop thread=#<Thread:0x00007f03ba822c28@event_loop /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:enqueue_thread thread=#<Thread:0x00007f03ba8236a0@enqueue_thread /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::PrometheusInput title=:in_prometheus_server thread=#<Thread:0x00007f03b9dfe878@in_prometheus_server /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::FileOutput title=:flush_thread_0 thread=#<Thread:0x00007f03ba80d008@flush_thread_0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::FileOutput title=:flush_thread_0 thread=#<Thread:0x00007f03ba8133b8@flush_thread_0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::FileOutput title=:enqueue_thread thread=#<Thread:0x00007f03ba813110@enqueue_thread /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:flush_thread_0 thread=#<Thread:0x00007f03ba810b68@flush_thread_0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:enqueue_thread thread=#<Thread:0x00007f03ba810618@enqueue_thread /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:event_loop thread=#<Thread:0x00007f03ba810168@event_loop /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:flush_thread_0 thread=#<Thread:0x00007f03ba814218@flush_thread_0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:event_loop thread=#<Thread:0x00007f03ba81b400@event_loop /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:flush_thread_0 thread=#<Thread:0x00007f03ba818868@flush_thread_0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:enqueue_thread thread=#<Thread:0x00007f03ba8180e8@enqueue_thread /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:flush_thread_0 thread=#<Thread:0x00007f03ba81e4c0@flush_thread_0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:event_loop thread=#<Thread:0x00007f03ba81f690@event_loop /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:event_loop thread=#<Thread:0x00007f03ba81db38@event_loop /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:enqueue_thread thread=#<Thread:0x00007f03ba81dfc0@enqueue_thread /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:flush_thread_1 thread=#<Thread:0x00007f03ba823948@flush_thread_1 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::FileOutput title=:enqueue_thread thread=#<Thread:0x00007f03ba80cc48@enqueue_thread /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:event_loop thread=#<Thread:0x00007f03ba823128@event_loop /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:flush_thread_1 thread=#<Thread:0x00007f03ba810898@flush_thread_1 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:flush_thread_1 thread=#<Thread:0x00007f03ba81bf68@flush_thread_1 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:enqueue_thread thread=#<Thread:0x00007f03ba81bbf8@enqueue_thread /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:flush_thread_0 thread=#<Thread:0x00007f03ba823d80@flush_thread_0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::PrometheusMonitorInput title=:event_loop thread=#<Thread:0x00007f03b9df5bd8@event_loop /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:flush_thread_1 thread=#<Thread:0x00007f03ba818570@flush_thread_1 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
2023-09-25 16:38:32 +0000 [warn]: #0 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutputDataStream title=:flush_thread_1 thread=#<Thread:0x00007f03ba81e240@flush_thread_1 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
/usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:60:in `write': stack level too deep (SystemStackError)
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:60:in `block in to_msgpack_stream'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:196:in `block in each'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:195:in `each'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:195:in `each'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/event.rb:59:in `to_msgpack_stream'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/output.rb:1016:in `block in <class:Output>'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin/buffer.rb:670:in `block in write_once'
	from /usr/local/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'
	 ... 21 levels...
	from /usr/local/bundle/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
	from /usr/local/bundle/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
	from /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2023-09-25 16:38:32 +0000 [error]: Worker 0 exited unexpectedly with status 1
2023-09-25 16:38:33 +0000 [info]: #0 init worker0 logger path=nil rotate_age=nil rotate_size=nil
2023-09-25 16:38:33 +0000 [warn]: #0 '@' is the system reserved prefix. It works in the nested configuration for now but it will be rejected: @timestamp
2023-09-25 16:38:33 +0000 [info]: adding match in @ES_FAILED pattern="**" type="file"
2023-09-25 16:38:33 +0000 [info]: adding match in @ERROR pattern="**" type="file"
2023-09-25 16:38:33 +0000 [info]: adding filter pattern="kubernetes.var.log.pods.ditro-*.**" type="record_modifier"
2023-09-25 16:38:33 +0000 [info]: adding filter pattern="kubernetes.var.log.pods.at-monitoring-*.**" type="record_modifier"
```

### Additional context

The error occurs both with file and memory buffers

we have also already tried to vary the following parameters, with no apparent effect.
flush_thread_count
chunk_limit_size
remove the secondary output

**Comment by ztdietmaier** [comment]
Sorry for the false positive -- this was caused by a log message with an astonishing number of nested JSON objects (about 1600).
