### ISSUE TITLE
Getting 503 error code in fluentd for retryable_response_codes 

### ISSUE THREAD

**Issue by prashant407** [fluent/fluentd#4387]
### Describe the bug

We are sending data from fluentd to logstash with http.We are using fluentd version fluentd-1.16.2. Previously it is working fine but after restart the fluentd pod we start getting the below errors
```
Status code 503 is going to be removed from default `retryable_response_codes` from fluentd v2. Please add it by yourself if you wish
/fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.16.2/lib/fluent/plugin/out_http.rb:189:in `initialize': no implicit conversion of nil into String (TypeError)
```

Could someone please help to understand the issue and how to resolve that ?

### To Reproduce

We are using the below configuration provided

### Expected behavior

There should not be any error as logstash pod is up and running.

### Your Environment

```markdown
- Fluentd version:1.16.2
- TD Agent version:
- Operating system: Debian GNU/Linux
- Kernel version: 11
```

### Your Configuration

```apache
<source>
      @type monitor_agent
      bind 0.0.0.0
      port 24220
    </source>

    <system>
      workers "#{ENV['FLUENTD_WORKER']}"
    </system>

    <worker 0>
      <source>
        @type tail
        #@id in_tail_fluentd_logs
        # @label @fluentdlogs
        path /var/log/containers/*.log
        pos_file /var/log/fluentd-containers.log.pos
        tag kubernetes.*
        read_from_head true
      <parse>
        #@type json
        #time_format %Y-%m-%dT%H:%M:%S.%NZ
        @type multi_format
        <pattern>
          format json
          time_key time
          keep_time_key true
        #time_format %Y-%m-%dT%H:%M:%S.%L %Z
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format none
          time_key time
          keep_time_key true
        #time_format %Y-%m-%dT%H:%M:%S.%L %Z
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
      </parse>
      </source>
    </worker>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      cache_size 20000
      cache_ttl 7200
      watch false
    </filter>


    <match **>
      @type http
      time_as_integer true
      http_method post
      tls_client_cert_path "/fluentd/etc/ssl/client.crt"
      tls_private_key_path "/fluentd/etc/ssl/client.key"
      tls_ca_cert_path "/fluentd/etc/ssl/ca.crt"
      tls_verify_mode peer
      tls_version TLSv1_2
      <buffer>
        @type file
        path /var/log/fluentd_application/kubernetes.internal.application.buffer
        chunk_limit_size 512k
        flush_interval 5s
        total_limit_size 4GB
        flush_thread_count "#{ENV['FLUENTD_THREADS']}"
        overflow_action drop_oldest_chunk
        retry_forever true
        retry_wait 5s
        retry_max_interval 5m
        retry_exponential_backoff_base 5
      </buffer>
      endpoint "https://#{ENV['LOGSTASH_HOST']}:#{ENV['LOGSTASH_PORT']}"
    </match>
```

### Your Error Log

```shell
Status code 503 is going to be removed from default `retryable_response_codes` from fluentd v2. Please add it by yourself if you wish
/fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.16.2/lib/fluent/plugin/out_http.rb:189:in `initialize': no implicit conversion of nil into String (TypeError)
```

**Comment by ashie** [comment]
> Status code 503 is going to be removed from default `retryable_response_codes` from fluentd v2. Please add it by yourself if you wish

You need to add `retryable_response_codes [503]` into your `<match>` section to suppress this warning.

> /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.16.2/lib/fluent/plugin/out_http.rb:189:in `initialize': no implicit conversion of nil into String (TypeError)

Your TLS client certification file seems empty or broken.
Please check it.
https://github.com/fluent/fluentd/blob/d5685ada81ac89a35a79965f1e94bbe5952a5d3a/lib/fluent/plugin/out_http.rb#L184-L189
