### ISSUE TITLE
CI fails on Ruby HEAD

### ISSUE THREAD

**Issue by Watson1978** [fluent/fluentd#4584]
### Describe the bug

Now, CI fails on Ruby HEAD.
https://github.com/fluent/fluentd/actions/runs/10277576606

I investigated this failures and found what webrick raises exception of `"uninitialized constant URI::REGEXP (NameError)"` at
https://github.com/ruby/webrick/blob/158a7ef85337e0e5cdce0c29cb5cb89c7beb9c53/lib/webrick/httprequest.rb#L507

Seems URI::REGEXP was removed at https://github.com/ruby/uri/pull/107 recently.

And webrick maintainer already fixed this issue at https://github.com/ruby/webrick/pull/144,
but it's not released yet.

> [!NOTE]
> I tried to use webrick from the master branch, then, CI passes.
> - Changes:
>   - https://github.com/Watson1978/fluentd/pull/1/files
> - CI Result:
>   - https://github.com/Watson1978/fluentd/actions/runs/10296597635

This issue should be solved by next release of webrick gem (v1.8.2 or above).

### To Reproduce

Run tests with Ruby HEAD

### Expected behavior

All tests will be passed.

### Your Environment

```markdown
- Fluentd version:
- Package version:
- Operating system:
- Kernel version:
```

### Your Configuration

```apache
none
```

### Your Error Log

```shell
https://github.com/fluent/fluentd/actions/runs/10277576606
```

**Comment by Watson1978** [comment]
don't close this until releasing new version of webrick.

**Comment by Watson1978** [comment]
Webrick v1.8.2 was released
https://github.com/ruby/webrick/releases/tag/v1.8.2

**Comment by Watson1978** [comment]
Seems CI has another failure...

```
4) Failure: test: failed to start(TestFluentdCommand::configuration to load plugin file with syntax error):
  fluentd failed to start, without specified regular expressions:
  2024-09-25 01:36:55 +0000 [info]: init supervisor logger path=nil rotate_age=nil rotate_size=nil
  2024-09-25 01:36:55 +0000 [info]: parsing config file is succeeded path="/home/runner/work/fluentd/fluentd/test/command/../tmp/commandfluentd/ddc62727292b887b1d0a/buggy_plugin.conf"
  2024-09-25 01:36:55 +0000 [info]: gem 'fluentd' version '1.17.1'
  bundler: failed to load command: /home/runner/work/fluentd/fluentd/bin/fluentd (/home/runner/work/fluentd/fluentd/bin/fluentd)
  /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundled_gems.rb:79:in 'Kernel.require': --> /home/runner/work/fluentd/fluentd/test/tmp/commandfluentd/ddc62727292b887b1d0a/plugin/in_buggy.rb
  Unmatched keyword, missing `end' ?
  > 2  module Fluent::Plugin
  /home/runner/work/fluentd/fluentd/test/tmp/commandfluentd/ddc62727292b887b1d0a/plugin/in_buggy.rb:6: syntax errors found (SyntaxError)
    4 |     Fluent::Plugin.register_input('buggy', self)
    5 |   end
  > 6 | 
      | ^ expected an `end` to close the `module` statement
  
      | ^ unexpected end-of-input, assuming it is closing the parent top level context
  
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundled_gems.rb:79:in 'block (2 levels) in Kernel#replace_require'
  	from /home/runner/work/fluentd/fluentd/lib/fluent/registry.rb:69:in 'Fluent::Registry#search'
  	from /home/runner/work/fluentd/fluentd/lib/fluent/registry.rb:44:in 'Fluent::Registry#lookup'
  	from /home/runner/work/fluentd/fluentd/lib/fluent/plugin.rb:169:in 'Fluent::Plugin.new_impl'
  	from /home/runner/work/fluentd/fluentd/lib/fluent/plugin.rb:110:in 'Fluent::Plugin.new_input'
  	from /home/runner/work/fluentd/fluentd/lib/fluent/root_agent.rb:315:in 'Fluent::RootAgent#add_source'
  	from /home/runner/work/fluentd/fluentd/lib/fluent/root_agent.rb:161:in 'block in Fluent::RootAgent#configure'
  	from <internal:array>:42:in 'Array#each'
  	from /home/runner/work/fluentd/fluentd/lib/fluent/root_agent.rb:155:in 'Fluent::RootAgent#configure'
  	from /home/runner/work/fluentd/fluentd/lib/fluent/engine.rb:105:in 'Fluent::EngineClass#configure'
  	from /home/runner/work/fluentd/fluentd/lib/fluent/engine.rb:80:in 'Fluent::EngineClass#run_configure'
  	from /home/runner/work/fluentd/fluentd/lib/fluent/supervisor.rb:572:in 'Fluent::Supervisor#run_supervisor'
  	from /home/runner/work/fluentd/fluentd/lib/fluent/command/fluentd.rb:352:in '<top (required)>'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundled_gems.rb:79:in 'Kernel.require'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundled_gems.rb:79:in 'block (2 levels) in Kernel#replace_require'
  	from /home/runner/work/fluentd/fluentd/bin/fluentd:15:in '<top (required)>'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundler/cli/exec.rb:58:in 'Kernel.load'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundler/cli/exec.rb:58:in 'Bundler::CLI::Exec#kernel_load'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundler/cli.rb:457:in 'Bundler::CLI#exec'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundler/vendor/thor/lib/thor.rb:527:in 'Bundler::Thor.dispatch'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundler/cli.rb:29:in 'Bundler::CLI.start'
  	from /home/runner/.rubies/ruby-head/lib/ruby/gems/3.4.0+0/gems/bundler-2.6.0.dev/exe/bundle:28:in 'block in <top (required)>'
  	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
```

https://github.com/fluent/fluentd/actions/runs/11024560399/job/30617932835

**Comment by Watson1978** [comment]
Maybe the failure is introduced by prism which is new Ruby parser...
(At least I have found one problem and reported it. https://bugs.ruby-lang.org/issues/20730)

**Comment by daipom** [comment]
Done?

**Comment by Watson1978** [comment]
OK, `Test with Ruby head` was succeeded.
https://github.com/fluent/fluentd/actions/runs/11043658331/job/30678296415

So, we can close this issue.

**Comment by daipom** [comment]
Thanks!!
