### ISSUE TITLE
CI: Fails ”test: multiple values are set to RUBYOPT(TestFluentdCommand::configured to run 2 workers)" test on Windows

### ISSUE THREAD

**Issue by Watson1978** [fluent/fluentd#4678]
### Describe the bug

Sometimes,  ”test: multiple values are set to RUBYOPT(TestFluentdCommand::configured to run 2 workers)" test fails on Windows platform.

```
1) Failure: test: multiple values are set to RUBYOPT(TestFluentdCommand::configured to run 2 workers):
  log doesn't match.
  <"[3824, #<Thread:0x00000223910f4428 run>, #<NoMethodError: undefined method `ignored?' for #<Gem::Specification:0x0000022394e25bd0 @extension_dir=nil, @full_gem_path=nil, @gem_dir=nil, @ignored=nil, @bin_dir=nil, @cache_dir=nil, @cache_file=nil, @doc_dir=nil, @ri_dir=nil, @spec_dir=nil, @spec_file=nil, @gems_dir=\"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems\", @base_dir=\"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0\", @loaded=false, @activated=false, @loaded_from=\"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/specifications/power_assert-2.0.4.gemspec\", @original_platform=nil, @installed_by_version=#<Gem::Version \"3.2.33\">, @autorequire=nil, @date=2024-10-03 00:00:00 UTC, @description=\"Power Assert shows each value of variables and method calls in the expression. It is useful for testing, providing which value wasn't correct when the condition is not satisfied.\", @email=[\"kazuki@callcc.net\"], @homepage=\"[https://github.com/ruby/power_assert\](https://github.com/ruby/power_assert/)", @name=\"power_assert\", @post_install_message=nil, @signing_key=nil, @summary=\"Power Assert for Ruby\", @version=#<Gem::Version \"2.0.4\">, @authors=[\"Kazuki Tsujimoto\"], @bindir=\"exe\", @cert_chain=[], @dependencies=[], @executables=[], @extensions=[], @extra_rdoc_files=[\"README.md\"], @files=[\"README.md\"], @licenses=[\"BSD-2-Clause\", \"Ruby\"], @metadata={}, @platform=\"ruby\", @rdoc_options=[\"--main\", \"README.md\"], @require_paths=[\"lib\"], @required_ruby_version=#<Gem::Requirement:0x0000022394e259f0 @requirements=[[\">=\", #<Gem::Version \"0\">]]>, @required_rubygems_version=#<Gem::Requirement:0x0000022394e25838 @requirements=[[\">=\", #<Gem::Version \"0\">]]>, @requirements=[], @rubygems_version=\"3.2.33\", @specification_version=4, @test_files=[], @new_platform=\"ruby\", @full_name=\"power_assert-2.0.4\" power_assert-2.0.4>\r\n" +
  "Did you mean?  ignored=>, [\"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/specification.rb:2116:in `method_missing'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `reject'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `matching_specs'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/dependency.rb:303:in `to_specs'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/specification.rb:1052:in `block in unresolved_specs'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/specification.rb:1052:in `map'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/specification.rb:1052:in `unresolved_specs'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/specification.rb:1030:in `find_in_unresolved'\", \"<internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:101:in `require'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:298:in `<module:Gem>'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `require_relative'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `<top (required)>'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `require_relative'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `<top (required)>'\", \"<internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\", \"<internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\"]]\r\n" +
  "[3824, #<Thread:0x00000223910f4428 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, [\"<internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require'\", \"<internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:167:in `require'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:298:in `<module:Gem>'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `require_relative'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `<top (required)>'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `require_relative'\", \"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `<top (required)>'\", \"<internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\", \"<internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\"]]\r\n" +
  "<internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)\r\n" +
  "\tfrom <internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:167:in `require'\r\n" +
  "<internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)\r\n" +
  "\tfrom <internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:167:in `require'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:298:in `<module:Gem>'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `require_relative'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `<top (required)>'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `require_relative'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `<top (required)>'\r\n" +
  "\tfrom <internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\r\n" +
  "\tfrom <internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\r\n" +
  "C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/specification.rb:2116:in `method_missing': undefined method `ignored?' for #<Gem::Specification:0x0000022394e25bd0 @extension_dir=nil, @full_gem_path=nil, @gem_dir=nil, @ignored=nil, @bin_dir=nil, @cache_dir=nil, @cache_file=nil, @doc_dir=nil, @ri_dir=nil, @spec_dir=nil, @spec_file=nil, @gems_dir=\"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems\", @base_dir=\"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0\", @loaded=false, @activated=false, @loaded_from=\"C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/specifications/power_assert-2.0.4.gemspec\", @original_platform=nil, @installed_by_version=#<Gem::Version \"3.2.33\">, @autorequire=nil, @date=2024-10-03 00:00:00 UTC, @description=\"Power Assert shows each value of variables and method calls in the expression. It is useful for testing, providing which value wasn't correct when the condition is not satisfied.\", @email=[\"kazuki@callcc.net\"], @homepage=\"[https://github.com/ruby/power_assert\](https://github.com/ruby/power_assert/)", @name=\"power_assert\", @post_install_message=nil, @signing_key=nil, @summary=\"Power Assert for Ruby\", @version=#<Gem::Version \"2.0.4\">, @authors=[\"Kazuki Tsujimoto\"], @bindir=\"exe\", @cert_chain=[], @dependencies=[], @executables=[], @extensions=[], @extra_rdoc_files=[\"README.md\"], @files=[\"README.md\"], @licenses=[\"BSD-2-Clause\", \"Ruby\"], @metadata={}, @platform=\"ruby\", @rdoc_options=[\"--main\", \"README.md\"], @require_paths=[\"lib\"], @required_ruby_version=#<Gem::Requirement:0x0000022394e259f0 @requirements=[[\">=\", #<Gem::Version \"0\">]]>, @required_rubygems_version=#<Gem::Requirement:0x0000022394e25838 @requirements=[[\">=\", #<Gem::Version \"0\">]]>, @requirements=[], @rubygems_version=\"3.2.33\", @specification_version=4, @test_files=[], @new_platform=\"ruby\", @full_name=\"power_assert-2.0.4\" power_assert-2.0.4> (NoMethodError)\r\n" +
  "Did you mean?  ignored=\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `reject'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `matching_specs'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/dependency.rb:303:in `to_specs'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/specification.rb:1052:in `block in unresolved_specs'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/specification.rb:1052:in `map'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/specification.rb:1052:in `unresolved_specs'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/specification.rb:1030:in `find_in_unresolved'\r\n" +
  "\tfrom <internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:101:in `require'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:298:in `<module:Gem>'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `require_relative'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `<top (required)>'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `require_relative'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `<top (required)>'\r\n" +
  "\tfrom <internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\r\n" +
  "\tfrom <internal:C:/hostedtoolcache/windows/Ruby/3.0.7/x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\r\n">
  was expected to include:
  <["#0 fluentd worker is now running worker=0"]>
  and not include:
  <["(LoadError)"]>
D:/a/fluentd/fluentd/test/command/test_fluentd.rb:219:in `assert_log_matches'
D:/a/fluentd/fluentd/test/command/test_fluentd.rb:941:in `block (2 levels) in <class:TestFluentdCommand>'
     938: </match>
     939: CONF
     940:       conf_path = create_conf_file('rubyopt_test.conf', conf)
  => 941:       assert_log_matches(
     942:         create_cmdline(conf_path),
     943:         '#0 fluentd worker is now running worker=0',
     944:         patterns_not_match: ['(LoadError)'],
```

### To Reproduce

Run CI.

### Expected behavior

CI runs without any failures.

### Your Environment

```markdown
- Fluentd version:
- Package version:
- Operating system:
- Kernel version:
```

### Your Configuration

```apache
none
```

### Your Error Log

```shell
https://github.com/fluent/fluentd/actions/runs/11435152581/job/31810002566
```

**Comment by Watson1978** [comment]
In my environment, this issue occurs with Ruby 3.0 + bundler 2.5.22  on Windows platform.
If downgrade bundler to 2.5.21, seems this issue can't be reproduced...

**Comment by Watson1978** [comment]
After updating rubygem to the latest version with ` gem update --system` command, seems this issue can't be reproduced even if use bundler 2.5.22.
