### ISSUE TITLE
CI: Fails some tests in test_in_exec.rb on Ruby HEAD under Windows

### ISSUE THREAD

**Issue by Watson1978** [fluent/fluentd#4699]
### Describe the bug

Recently, some tests have been failed in test_in_exec.rb on Ruby HEAD under Windows.

See https://github.com/fluent/fluentd/actions/runs/11652078678/job/32442835201

```
3) Failure: test: can handle non-ascii characters[immediate](ExecInputTest::encoding)
D:/a/fluentd/fluentd/test/plugin/test_in_exec.rb:239:in 'block (2 levels) in <class:ExecInputTest>'
     236: 
     237:       d.run(expect_records: 1, timeout: 10)
     238: 
  => 239:       assert_equal 1, d.events.length
     240:       tag, time, record = d.events.first
     241:       assert_equal({"message" => content}, record)
     242:     end
<1> expected but was
<0>

4) Failure: test: can handle non-ascii characters[run_interval](ExecInputTest::encoding)
D:/a/fluentd/fluentd/test/plugin/test_in_exec.rb:239:in 'block (2 levels) in <class:ExecInputTest>'
     236: 
     237:       d.run(expect_records: 1, timeout: 10)
     238: 
  => 239:       assert_equal 1, d.events.length
     240:       tag, time, record = d.events.first
     241:       assert_equal({"message" => content}, record)
     242:     end
<1> expected but was
<0>
```

### To Reproduce

Run "Test with Ruby head" action

### Expected behavior

No errors

### Your Environment

```markdown
- Fluentd version:
- Package version:
- Operating system:
- Kernel version:
```

### Your Configuration

```apache
none
```

### Your Error Log

```shell
See above
```

**Comment by Watson1978** [comment]
If it don't specify the internal/external encoding, the characters will be corrupted with Ruby HEAD on Wiindows...
```
PS C:\> ruby -v
ruby 3.4.0dev (2024-11-09 master 9588319e72) +PRISM [x64-mingw-ucrt]
PS C:\> irb
irb(main):001> `ruby -e "puts 'ひらがな漢字'"`
=> "\x82Ђ炪\x82Ȋ\xBF\x8E\x9A\n"
irb(main):002> `ruby -Eascii-8bit:ascii-8bit -e "puts 'ひらがな漢字'"`
=> "ひらがな漢字\n"
irb(main):003>
```

**Comment by ashie** [comment]
Hmm, the latest scheduled CI result seems succeeded :thinking: : https://github.com/fluent/fluentd/actions/runs/11765896740/job/32772775312
Is it addressed by the upstream of RubyInstaller?
Do you know which changes of RubyInstaller affects to this?
Does the change in RubyInstaller 3.3.6-2 is related with this?: https://github.com/oneclick/rubyinstaller2/releases

**Comment by Watson1978** [comment]
Hmm. The test fails without `-Eascii-8bit:ascii-8bit`  in my environment even if I use Ruby 3.3.6-2.
I wonder it fails on Windows for Japanese edition....?


```
PS C:\src\fluentd> bundle exec ruby -v -I"lib;test" test/plugin/test_in_exec.rb --name="test: can handle non-ascii characters"
ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x64-mingw-ucrt]
test/plugin/test_in_exec.rb:240: warning: assigned but unused variable - tag
test/plugin/test_in_exec.rb:240: warning: assigned but unused variable - time
test/plugin/test_in_exec.rb:246: warning: assigned but unused variable - d
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/serverengine-2.4.0/lib/serverengine/socket_manager_win.rb:141: warning: assigned but unused variable - type
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/async-2.18.0/lib/async/task.rb:290: warning: assigned but unused variable - error
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/async-pool-0.10.1/lib/async/pool/controller.rb:336: warning: assigned but unused variable - error
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/traces-0.14.1/lib/traces/config.rb:43: warning: assigned but unused variable - error
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/async-http-0.82.3/lib/async/http/protocol/http1/server.rb:55: warning: assigned but unused variable - error
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/async-http-0.82.3/lib/async/http/protocol/http2/connection.rb:98: warning: assigned but unused variable - ignored_error
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/protocol-http-0.42.0/lib/protocol/http/body/stream.rb:233: warning: assigned but unused variable - buffer
C:/src/fluentd/lib/fluent/plugin_helper.rb:46: warning: method redefined; discarding old inherited
C:/src/fluentd/lib/fluent/plugin_helper.rb:46: warning: previous definition of inherited was here
Loaded suite test/plugin/test_in_exec
Started
F
================================================================================================================================================================================
Failure: test: can handle non-ascii characters[immediate](ExecInputTest::encoding)
test/plugin/test_in_exec.rb:241:in `block (2 levels) in <class:ExecInputTest>'
     238:
     239:       assert_equal 1, d.events.length
     240:       tag, time, record = d.events.first
  => 241:       assert_equal({"message" => content}, record)
     242:     end
     243:
     244:     test 'raise ConfigError for invalid encoding' do
<{"message"=>"ひらがな漢字"}> expected but was
<{"message"=>"\x82Ђ炪\x82Ȋ\xBF\x8E\x9A"}>

diff:
? {"message"=>"ひらがな漢字            "}
?              \x82Ђ炪\x82Ȋ\xBF\x8E\x9A
?              ????????????
================================================================================================================================================================================
F
================================================================================================================================================================================
Failure: test: can handle non-ascii characters[run_interval](ExecInputTest::encoding)
test/plugin/test_in_exec.rb:241:in `block (2 levels) in <class:ExecInputTest>'
     238:
     239:       assert_equal 1, d.events.length
     240:       tag, time, record = d.events.first
  => 241:       assert_equal({"message" => content}, record)
     242:     end
     243:
     244:     test 'raise ConfigError for invalid encoding' do
<{"message"=>"ひらがな漢字"}> expected but was
<{"message"=>"\x82Ђ炪\x82Ȋ\xBF\x8E\x9A"}>

diff:
? {"message"=>"ひらがな漢字            "}
?              \x82Ђ炪\x82Ȋ\xBF\x8E\x9A
?              ????????????
================================================================================================================================================================================
Finished in 2.2464021 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2 tests, 4 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
0.89 tests/s, 1.78 assertions/s
```

**Comment by Watson1978** [comment]
> Is it addressed by the upstream of RubyInstaller?
> Do you know which changes of RubyInstaller affects to this?
> Does the change in RubyInstaller 3.3.6-2 is related with this?: https://github.com/oneclick/rubyinstaller2/releases

Unfortunately, I don't know about them.

If there are any problems with the CI again, I will investigate.
I will close this
