### ISSUE TITLE
CI: "can format/write data correctly" test fails with`Zlib::GzipFile::Error` on Windows

### ISSUE THREAD

**Issue by Watson1978** [fluent/fluentd#4727]
### Describe the bug

Sometimes, "can format/write data correctly" test fails with`Zlib::GzipFile::Error` on Windows

```
1) Error: test: can format/write data correctly(FileOutputTest::fully configured output): Zlib::GzipFile::Error: not in gzip format
D:/a/fluentd/fluentd/test/plugin/test_out_file.rb:338:in `initialize'
D:/a/fluentd/fluentd/test/plugin/test_out_file.rb:338:in `new'
D:/a/fluentd/fluentd/test/plugin/test_out_file.rb:338:in `block (4 levels) in <class:FileOutputTest>'
D:/a/fluentd/fluentd/test/plugin/test_out_file.rb:337:in `open'
D:/a/fluentd/fluentd/test/plugin/test_out_file.rb:337:in `block (3 levels) in <class:FileOutputTest>'
D:/a/fluentd/fluentd/test/plugin/test_out_file.rb:341:in `block (2 levels) in <class:FileOutputTest>'
```

### To Reproduce

Run CI

### Expected behavior

No error

### Your Environment

```markdown
- Fluentd version:
- Package version:
- Operating system:
- Kernel version:
```

### Your Configuration

```apache
none
```

### Your Error Log

```shell
See above
```

**Comment by Watson1978** [comment]
Sometimes, it does not match between file size and size of the file read.

```diff
diff --git a/test/plugin/test_out_file.rb b/test/plugin/test_out_file.rb
index 0e9dd17f..ec9322d1 100644
--- a/test/plugin/test_out_file.rb
+++ b/test/plugin/test_out_file.rb
@@ -335,7 +335,18 @@ class FileOutputTest < Test::Unit::TestCase

       read_gunzip = ->(path){
         File.open(path){ |fio|
-          Zlib::GzipReader.new(StringIO.new(fio.read)).read
+          begin
+            content = fio.read
+            p [path, File.size(path), content.bytesize]
+            Zlib::GzipReader.new(StringIO.new(content)).read
+          rescue => e
+            p "!" * 80
+            p path
+            p e
+            p File.stat(path)
+            p content
+          end
         }
       }
       assert_equal r1 + r2, read_gunzip.call("#{TMP_DIR}/my.data/a/full.20161003.2345.log.gz")
```

```
bundle exec ruby -Ilib:test test/plugin/test_out_file.rb -v --name='test: can format/write data correctly'
Loaded suite test/plugin/test_out_file
Started
FileOutputTest:
  fully configured output:
    test: can format/write data correctly:                                                                                                                                      ["C:/src/fluentd/test/tmp/out_file/my.data/a/full.20161003.2345.log.gz", 154, 154]
["C:/src/fluentd/test/tmp/out_file/your.data/a/full.20161003.2345.log.gz", 143, 143]
["C:/src/fluentd/test/tmp/out_file/my.data/a/full.20161004.0000.log.gz", 137, 137]
["C:/src/fluentd/test/tmp/out_file/your.data/a/full.20161004.0000.log.gz", 140, 4]
"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
"C:/src/fluentd/test/tmp/out_file/your.data/a/full.20161004.0000.log.gz"
#<Zlib::GzipFile::Error: not in gzip format, input="\x1F\x8B\b\x00">
#<File::Stat dev=0x2, ino=19140298416327971, mode=0100644, nlink=1, uid=0, gid=0, rdev=0x2, size=140, blksize=nil, blocks=nil, atime=2024-12-07 11:38:19.4141774 +0900, mtime=2024-12-07 11:38:18.3842006 +0900, ctime=2024-12-07 11:38:18.3842006 +0900>
"\u001F\x8B\b\u0000"
```

**Comment by Watson1978** [comment]
I attach a file generated by running tests when fails 
[full.20161003.2345.log.gz](https://github.com/user-attachments/files/18046202/full.20161003.2345.log.gz)

I think there is something wrong with the mode in which the file is opened.
I think 'b' should be added since we are dealing with binary files.

```ruby
path = 'full.20161003.2345.log.gz'

puts "File.size: #{File.size(path)}"

File.open(path) { |fio|
  puts "content size 'r' mode: #{fio.read.size}"
}

File.open(path, 'rb') { |fio|
  puts "content size 'rb' mode: #{fio.read.size}"
}
```

```
PS C:\tmp> ruby .\test.rb
File.size: 143
content size 'r' mode: 4
content size 'rb' mode: 143
```
