### ISSUE TITLE
out_forward Broken pipe - sendfile

### ISSUE THREAD

**Issue by loveshell** [fluent/fluentd#487]
OS:
```
CentOS release 6.3
Linux CTL_HA_054_015 2.6.32-431.29.2.el6.x86_64 #1 SMP Tue Sep 9 21:36:05 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
config:
```
<source>
type tail
path /cache/logs/%Y%m%d%H_access.log
tag apache.access
pos_file /var/log/td-agent/httpd-access.log.pos
format /^(?<host_header>[^ ]*) (?<client_ip>[^ ]*) [^ ]* [^ ]* \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")? (?<request_id>[^ ]*) (?<time_total>[^ ]*) (?<secs>[^ ]*)$/
time_format %d/%b/%Y:%H:%M:%S %z
</source>
<match apache.access>
type forward
log_level error
heartbeat_type tcp
send_timeout 60s
recover_wait 10s
heartbeat_interval 20s
phi_threshold 16
hard_timeout 60s
buffer_queue_limit 128
buffer_chunk_limit 2560m
<server>
host 1.1.1.1
port 24224
weight 60
</server>
<server>
host 2.2.2.2
port 24224
weight 60
</server>
</match>
```

and buffer type file is and so on.

errorlog

```
2014-11-22 11:23:09 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2014-11-22 11:05:07 +0800 error_class="Errno::EPIPE" error="Broken pipe - sendfile" instance=69843517700880
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/fileutils.rb:488:in `copy_stream'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/fileutils.rb:488:in `copy_stream'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/buffer.rb:100:in `block in write_to'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/plugin/buf_file.rb:65:in `open'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/buffer.rb:99:in `write_to'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/plugin/out_forward.rb:252:in `send_data'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/plugin/out_forward.rb:144:in `block in write_objects'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/plugin/out_forward.rb:138:in `times'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/plugin/out_forward.rb:138:in `write_objects'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/output.rb:449:in `write'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/buffer.rb:296:in `write_chunk'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/buffer.rb:276:in `pop'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/output.rb:310:in `try_flush'
  2014-11-22 11:23:09 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.46/lib/fluent/output.rb:132:in `run'
```

and log_level error options is not take effect

**Comment by tagomoris** [comment]
There are no other reports for same issue, and it's about too old fluentd version (0.10.46).
Please reopen this if the same problem occurs with latest fluentd on recent environment.
