### ISSUE TITLE
exit after webhdfs AlreadyBeingCreatedException lose logs

### ISSUE THREAD

**Issue by loveshell** [fluent/fluentd#494]
version

```
fluentd-0.10.50
```

configure

```
<store>
type webhdfs 
namenode         192.168.1.211:50070
standby_namenode 192.168.1.212:50070
path /weblog/access/day=%Y%m%d/localhost_%H.log
username hdfs
localtime true
retry_known_errors yes
field_separator SOH
output_include_time true 
output_include_tag false
num_threads 256
time_format %Y-%m-%d %H:%M:%S
output_data_type attr:clientip
flush_interval 10s
buffer_chunk_limit 2048M
buffer_queue_limit 32
retry_times   2
retry_interval 3
</store>
```

errorlog

```
[root@localhost ~]# tail -n 10 /var/log/td-agent/td-agent.log
2014-12-01 08:08:06 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2014-12-01 10:29:00 +0800 error_class="WebHDFS::IOError" error="{\"RemoteException\":{\"exception\":\"AlreadyBeingCreatedException\",\"javaClassName\":\"org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException\",\"message\":\"failed to create file /weblog/access/day=20141201/localhost_05.log for DFSClient_NONMAPREDUCE_-1418526085_4180312 on client 192.168.1.206 because pendingCreates is non-null but no leases found.\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.recoverLeaseInternal(FSNamesystem.java:2500)\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInternal(FSNamesystem.java:2369)\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInt(FSNamesystem.java:2598)\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFile(FSNamesystem.java:2561)\\n\\tat org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.append(NameNodeRpcServer.java:522)\\n\\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.append(ClientNamenodeProtocolServerSideTranslatorPB.java:373)\\n\\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\\n\\tat org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:585)\\n\\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1026)\\n\\tat org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1986)\\n\\tat org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1982)\\n\\tat java.security.AccessController.doPrivileged(Native Method)\\n\\tat javax.security.auth.Subject.doAs(Subject.java:415)\\n\\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)\\n\\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:1980)\\n\"}}" instance=70255223868740
  2014-12-01 08:08:06 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:317:in `request'
  2014-12-01 08:08:06 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:242:in `operate_requests'
  2014-12-01 08:08:06 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:56:in `append'
  2014-12-01 08:08:06 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-webhdfs-0.2.3/lib/fluent/plugin/out_webhdfs.rb:187:in `send_data'
  2014-12-01 08:08:06 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-webhdfs-0.2.3/lib/fluent/plugin/out_webhdfs.rb:205:in `write'
  2014-12-01 08:08:06 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2014-12-01 08:08:06 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2014-12-01 08:08:06 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2014-12-01 08:08:06 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
```

retry after some error ,but soemtimes after this error not retry.and process is still。

but no log is transmissioned

**Comment by mastermiaoge** [comment]
How is you question going ?
