### ISSUE TITLE
Old fluentd processes leaked after reloading configuration with SIGHUP.

### ISSUE THREAD

**Issue by jperville** [fluent/fluentd#540]
After upgrading fluentd to version 0.12.3, I noticed that the old fluentd processes are not reclaimed after reloading the configuration with SIGHUP. Is this expected behavior? With version 0.12.2, the configuration was not reloaded at all on SIGHUP (fixed in #537), so I was looking forward to the new release.

About my setup: I am running fluentd inside a docker image that watches the docker API. When a docker container is started or stopped, the `/etc/fluentd/fluentd.conf` file is regenerated from a template and the fluentd process is asked to reload its configuration by receiving SIGHUP.

As a workaround for this issue, I will regenerate my image to reload the configuration by completely restarting the fluentd process (SIGINT) but that is far from optimal.

Here is a lot that shows the problem (I filtered out unrelated entries).

```
# ps x
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /usr/bin/python3 -u /sbin/my_init
   15 ?        S      0:00 /usr/bin/runsvdir -P /etc/service
   19 ?        Ss     0:00 runsv fluentd
   20 ?        Ss     0:00 runsv docker-gen
   22 ?        Sl     0:00 /usr/local/bin/docker-gen -watch -notify sv hup fluentd /root/fluentd.tmpl /etc/fluent
   39 ?        Sl     0:00 /usr/bin/ruby2.1 /usr/local/bin/fluentd -c /etc/fluentd/fluentd.conf
  104 ?        Sl     0:00 /usr/bin/ruby2.1 /usr/local/bin/fluentd -c /etc/fluentd/fluentd.conf
  156 ?        Sl     0:00 /usr/bin/ruby2.1 /usr/local/bin/fluentd -c /etc/fluentd/fluentd.conf
  158 ?        Sl     0:00 /usr/bin/ruby2.1 /usr/local/bin/fluentd -c /etc/fluentd/fluentd.conf
  207 ?        R+     0:00 ps x
# sv hup fluentd
# ps aux | grep fluentd
root        19  0.0  0.0    168     4 ?        Ss   02:44   0:00 runsv fluentd
root        22  0.1  0.0 189884  4664 ?        Sl   02:44   0:00 /usr/local/bin/docker-gen -watch -notify sv hup fluentd /root/fluentd.tmpl /etc/fluentd/fluentd.conf
root        39  0.3  0.5 1211264 33796 ?       Sl   02:44   0:00 /usr/bin/ruby2.1 /usr/local/bin/fluentd -c /etc/fluentd/fluentd.conf
root       104  0.5  0.5 1211272 32280 ?       Sl   02:46   0:00 /usr/bin/ruby2.1 /usr/local/bin/fluentd -c /etc/fluentd/fluentd.conf
root       158  0.6  0.5 1211292 32244 ?       Sl   02:47   0:00 /usr/bin/ruby2.1 /usr/local/bin/fluentd -c /etc/fluentd/fluentd.conf
root       209  3.8  0.3  91168 20688 ?        Sl   02:48   0:00 /usr/bin/ruby2.1 /usr/local/bin/fluentd -c /etc/fluentd/fluentd.conf
root       211  6.1  0.5 1211336 32420 ?       Sl   02:48   0:00 /usr/bin/ruby2.1 /usr/local/bin/fluentd -c /etc/fluentd/fluentd.conf
# ps aux | grep /usr/local/bin/fluentd | grep -v grep | wc -l
5
# sv hup fluentd
# ps aux | grep /usr/local/bin/fluentd | grep -v grep | wc -l
6
# sv hup fluentd
# sv hup fluentd
# sv hup fluentd
# ps aux | grep /usr/local/bin/fluentd | grep -v grep | wc -l
9
# sv hup fluentd
# sv hup fluentd
# sv hup fluentd
# ps aux | grep /usr/local/bin/fluentd | grep -v grep | wc -l
12
```

**Comment by repeatedly** [comment]
@sonots Could you handle this?

**Comment by sonots** [comment]
Hmm, I can not reproduce on my environment. It would be a issue occurred only on Docker environment. 

@jperville Can you show me a log of Fluentd? Does not it have log like below?

```
2015-01-19 13:26:39 +0900 [error]: fluent/supervisor.rb:143:start: fluentd main process died unexpectedly. restarting.
```

**Comment by jperville** [comment]
Here is what I can see in the log instead of the expected "fluentd main process died"

```
2015-01-19 04:40:07 +0000 [info]: restarting
2015-01-19 04:40:07 +0000 [info]: reading config file path="/etc/fluentd/fluentd.conf"
/usr/lib/ruby/2.1.0/monitor.rb:246:in `mon_check_owner': current thread not owner (ThreadError)
	from /usr/lib/ruby/2.1.0/monitor.rb:195:in `mon_exit'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:143:in `ensure in require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:143:in `require'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/config.rb:28:in `parse'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/supervisor.rb:352:in `read_config'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/supervisor.rb:324:in `block in install_supervisor_signal_handlers'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/supervisor.rb:252:in `call'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/supervisor.rb:252:in `waitpid'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/supervisor.rb:252:in `supervise'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/supervisor.rb:134:in `start'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/bin/fluentd:6:in `<top (required)>'
	from /usr/local/bin/fluentd:23:in `load'
	from /usr/local/bin/fluentd:23:in `<main>'
2015-01-19 04:40:08 +0000 [info]: reading config file path="/etc/fluentd/fluentd.conf"
2015-01-19 04:40:08 +0000 [info]: starting fluentd-0.12.3
2015-01-19 04:40:08 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.3.0'
2015-01-19 04:40:08 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '0.7.0'
2015-01-19 04:40:08 +0000 [info]: gem 'fluent-plugin-exclude-filter' version '0.0.1'
2015-01-19 04:40:08 +0000 [info]: gem 'fluent-plugin-record-modifier' version '0.2.0'
2015-01-19 04:40:08 +0000 [info]: gem 'fluentd' version '0.12.3'
2015-01-19 04:40:08 +0000 [info]: gem 'fluentd' version '0.10.58'
2015-01-19 04:40:08 +0000 [info]: using configuration file: <ROOT>
  <match docker.filtered.**>
    type elasticsearch
    host logs.192.168.33.11.xip.io
    port 9200
    index_name fluentd
    type_name fluentd
    logstash_format true
  </match>
</ROOT>
2015-01-19 04:40:08 +0000 [info]: adding match pattern="docker.filtered.**" type="elasticsearch"
```

I am available for interactive debug if you need (I also live on Asian time).

**Comment by sonots** [comment]
@jperville Did you see a log senging TERM signal to the child (master) process?

**Comment by jperville** [comment]
Not at all. Here is the full log with `-vv` :+1: 

```
2015-01-19 04:44:34 +0000 [debug]: fluent/supervisor.rb:322:block in install_supervisor_signal_handlers: fluentd supervisor process get SIGHUP
2015-01-19 04:44:34 +0000 [info]: fluent/supervisor.rb:323:block in install_supervisor_signal_handlers: restarting
2015-01-19 04:44:34 +0000 [info]: fluent/supervisor.rb:343:read_config: reading config file path="/etc/fluentd/fluentd.conf"
/usr/lib/ruby/2.1.0/monitor.rb:246:in `mon_check_owner': current thread not owner (ThreadError)
	from /usr/lib/ruby/2.1.0/monitor.rb:195:in `mon_exit'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:143:in `ensure in require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:143:in `require'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/config.rb:28:in `parse'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/supervisor.rb:352:in `read_config'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/supervisor.rb:324:in `block in install_supervisor_signal_handlers'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/supervisor.rb:252:in `call'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/supervisor.rb:252:in `waitpid'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/supervisor.rb:252:in `supervise'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/supervisor.rb:134:in `start'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.3/bin/fluentd:6:in `<top (required)>'
	from /usr/local/bin/fluentd:23:in `load'
	from /usr/local/bin/fluentd:23:in `<main>'
2015-01-19 04:44:34 +0000 [info]: fluent/supervisor.rb:343:read_config: reading config file path="/etc/fluentd/fluentd.conf"
2015-01-19 04:44:34 +0000 [info]: fluent/supervisor.rb:239:supervise: starting fluentd-0.12.3
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered buffer plugin 'file'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered buffer plugin 'memory'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered filter plugin 'grep'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered filter plugin 'record_transformer'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'debug_agent'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'dummy'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'exec'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'forward'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'gc_stat'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'http'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'monitor_agent'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'object_space'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'status'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'unix'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'syslog'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'tail'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'tcp'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered input plugin 'udp'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered output plugin 'copy'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered output plugin 'exec'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered output plugin 'exec_filter'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered output plugin 'file'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered output plugin 'forward'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered output plugin 'null'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered output plugin 'relabel'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered output plugin 'roundrobin'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered output plugin 'stdout'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered output plugin 'tcp'
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered output plugin 'unix'
2015-01-19 04:44:34 +0000 [info]: fluent/engine.rb:90:block in configure: gem 'fluent-mixin-config-placeholders' version '0.3.0'
2015-01-19 04:44:34 +0000 [info]: fluent/engine.rb:90:block in configure: gem 'fluent-plugin-elasticsearch' version '0.7.0'
2015-01-19 04:44:34 +0000 [info]: fluent/engine.rb:90:block in configure: gem 'fluent-plugin-exclude-filter' version '0.0.1'
2015-01-19 04:44:34 +0000 [info]: fluent/engine.rb:90:block in configure: gem 'fluent-plugin-record-modifier' version '0.2.0'
2015-01-19 04:44:34 +0000 [info]: fluent/engine.rb:90:block in configure: gem 'fluentd' version '0.12.3'
2015-01-19 04:44:34 +0000 [info]: fluent/engine.rb:90:block in configure: gem 'fluentd' version '0.10.58'
2015-01-19 04:44:34 +0000 [info]: fluent/engine.rb:94:configure: using configuration file: <ROOT>
  <match docker.filtered.**>
    type elasticsearch
    host logs.192.168.33.11.xip.io
    port 9200
    index_name fluentd
    type_name fluentd
    logstash_format true
  </match>
</ROOT>
2015-01-19 04:44:34 +0000 [info]: fluent/agent.rb:123:add_match: adding match pattern="docker.filtered.**" type="elasticsearch"
2015-01-19 04:44:34 +0000 [trace]: fluent/plugin.rb:98:register_impl: registered output plugin 'elasticsearch'
```

**Comment by jperville** [comment]
Would you be interested in the source of the docker image so you can reproduce yourself?

**Comment by sonots** [comment]
@jperville Yes, it should be great if I can have a environment to reproduce with your Docker image.

**Comment by jperville** [comment]
I uploaded my Dockerfile, so you can reproduce at will.
Thank you so much @sonots 

```sh
$ git clone https://github.com/jperville/fluentd.git fluentd-540
$ cd fluentd-540
$ git checkout fluentd-issue-540
$ docker build -t my-fluentd .
$ docker run --rm -ti --name=my-fluentd -e ES_HOST=localhost -e ES_PORT=9999 -v /var/run/docker.sock:/tmp/docker.sock my-fluentd /sbin/my_init --enable-insecure-key
```

Then ssh (or nsenter) into the container and inside do: `sv hup fluentd`.
Watch the docker logs for the `ThreadError`.
Compare the number of fluentd processes before and after.

You should not need a real elasticsearch nor docker containers to reproduce.

**Comment by sonots** [comment]
@jperville Thanks! I will try it.

**Comment by sonots** [comment]
Thank you I could reproduce it.

`read_config` calls `require` and `core_ext/kernel_require` uses monitor. 
Mutex#lock can not be called from Signal trap https://bugs.ruby-lang.org/issues/7917

Hmm, I am thinking how I can fix this.

**Comment by jperville** [comment]
Is it possible to just set a flag in the signal handler, and have the main loop exit when the flag is set?

**Comment by sonots** [comment]
It would be nice to have SignalThread as serverengine does > https://github.com/fluent/serverengine/blob/master/lib/serverengine/signal_thread.rb. 

@repeatedly what do you think?

**Comment by sonots** [comment]
Or, just enclose with `Thread.new` as https://github.com/fluent/fluentd/blob/9eef6f9e6581d58613b61c16639b079439589281/lib/fluent/supervisor.rb#L465-L472 for now.

**Comment by jperville** [comment]
Looking forward to trying the fix on new image.

**Comment by jperville** [comment]
Thank you @sonots , I have applied the fix by hand inside image and it seems to works as expected.
