### ISSUE TITLE
emit transaction failed

### ISSUE THREAD

**Issue by uohzxela** [fluent/fluentd#577]
Trying to send fluentd logs to kafka using fluentd-plugin-kafka, but got 'emit transaction failed' error.

Here's the conf files:

```
==> hotels_impression_rates_from_tail_log.conf <==
<source>
  type tail
  tag staging.logs.hotels.impressions.rates
  path /var/apps/a/hoteru/shared/log/fluentd/rates.staging.log
  pos_file /var/apps/a/hoteru/shared/log/fluentd/rates.staging.log.pos
  format json
</source>

==> hotels_impression_rates_to_kafka.conf <==
<match staging.logs.hotels.impressions.rates>
  type kafka
  brokers kafka-staging-a-1.bezurk.org:9092
  default_topic alex
  output_data_type json
</match>
```

From /var/log/td-agent/td-agent.log:
```
2015-04-20 09:33:21 +0800 [info]: brokers has been set directly: ["kafka-staging-a-1.bezurk.org:9092"]
2015-04-20 09:33:21 +0800 [info]: adding match pattern="td.*.*" type="tdlog"
2015-04-20 09:33:22 +0800 [info]: adding match pattern="debug.**" type="stdout"
2015-04-20 09:33:22 +0800 [info]: adding source type="tail"
2015-04-20 09:33:22 +0800 [info]: adding source type="forward"
2015-04-20 09:33:22 +0800 [info]: adding source type="debug_agent"
2015-04-20 09:33:22 +0800 [info]: initialized producer kafka
2015-04-20 09:33:22 +0800 [info]: following tail of /var/apps/a/hoteru/shared/log/fluentd/rates.staging.log
2015-04-20 09:33:22 +0800 [info]: listening fluent socket on 0.0.0.0:24224
2015-04-20 09:33:22 +0800 [info]: listening dRuby uri="druby://127.0.0.1:24230" object="Engine"
2015-04-20 09:34:10 +0800 [warn]: Send exception occurred: Poseidon::Errors::UnableToFetchMetadata
2015-04-20 09:34:10 +0800 [info]: initialized producer kafka
2015-04-20 09:34:10 +0800 [warn]: emit transaction failed: error_class=Poseidon::Errors::UnableToFetchMetadata error="Poseidon::Errors::UnableToFetchMetadata" tag="staging.logs.hotels.impressions.rates"
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/poseidon-0.0.5/lib/poseidon/sync_producer.rb:95:in `ensure_metadata_available_for_topics'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/poseidon-0.0.5/lib/poseidon/sync_producer.rb:49:in `send_messages'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/poseidon-0.0.5/lib/poseidon/producer.rb:163:in `send_messages'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.0.12/lib/fluent/plugin/out_kafka.rb:135:in `block in emit'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/event.rb:128:in `call'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/event.rb:128:in `block in each'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/event.rb:127:in `each'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/event.rb:127:in `each'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kafka-0.0.12/lib/fluent/plugin/out_kafka.rb:128:in `emit'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/event_router.rb:88:in `emit_stream'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:229:in `receive_lines'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:320:in `call'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:320:in `wrap_receive_lines'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:513:in `call'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:513:in `on_notify'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:345:in `on_notify'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:446:in `call'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:446:in `on_change'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run_once'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run'
  2015-04-20 09:34:10 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:214:in `run'
```

**Comment by repeatedly** [comment]
Log shows `Poseidon::Errors::UnableToFetchMetadata`

http://www.rubydoc.info/github/bpot/poseidon/Poseidon/Errors/UnableToFetchMetadata

Maybe, your setting or your cluster has a problem.
If you want more detail, please open an issue on fluent-plugin-kafka repository.
