### ISSUE TITLE
out_forward error. undefined method `finite?'

### ISSUE THREAD

**Issue by kazeburo** [fluent/fluentd#579]
out_forward stopped with these error messages when destination server restarted/stoped.

```
2015-04-20 12:45:57 +0900 [error]: error on output thread error="undefined method `finite?' for 3:Fixnum"
  2015-04-20 12:45:57 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.58/lib/fluent/output.rb:402:in `calc_retry_wait'
  2015-04-20 12:45:57 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.58/lib/fluent/output.rb:342:in `block in try_flush'
  2015-04-20 12:45:57 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.58/lib/fluent/output.rb:338:in `synchronize'
  2015-04-20 12:45:57 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.58/lib/fluent/output.rb:338:in `rescue in try_flush'
  2015-04-20 12:45:57 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.58/lib/fluent/output.rb:293:in `try_flush'
  2015-04-20 12:45:57 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.58/lib/fluent/output.rb:136:in `run'
```

config

```
retry_limit 20
retry_wait 3s
```

Retrying forward to destination server is succeeded with this fix

```
-      retry_wait = wait.finite? ? wait + (rand * (wait / 4.0) - (wait / 8.0)) : wait
+      retry_wait = wait.to_f.finite? ? wait + (rand * (wait / 4.0) - (wait / 8.0)) : wait
```

**Comment by repeatedly** [comment]
This problem is already resolved by https://github.com/fluent/fluentd/pull/529.
So updateing td-agent 2 to 2.1.5 or 2.2.0 fixed this issue.
