### ISSUE TITLE
Runtime error: can't modify frozen String

### ISSUE THREAD

**Issue by pellaeon** [fluent/fluentd#598]
Environment: FreeBSD 10.1-RELEASE

Installed fluentd from `sysutils/rubygem-fluentd` port.

I am using elasticsearch output, plugin installed via `fluent-gem install fluent-plugin-elasticsearch`
```
2015-05-21 18:00:55 +0800 [warn]: fluent/output.rb:344:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2015-05-21 18:05:05 +0800 error_class="RuntimeError" error="can't modify frozen String" instance=17200902500
  2015-05-21 18:00:55 +0800 [warn]: /usr/local/lib/ruby/gems/2.1/gems/fluentd-0.10.53/lib/fluent/plugin/buf_memory.rb:62:in `feed_each'
  2015-05-21 18:00:55 +0800 [warn]: /usr/local/lib/ruby/gems/2.1/gems/fluentd-0.10.53/lib/fluent/plugin/buf_memory.rb:62:in `msgpack_each'
  2015-05-21 18:00:55 +0800 [warn]: /usr/local/lib/ruby/gems/2.1/gems/fluent-plugin-elasticsearch-0.8.0/lib/fluent/plugin/out_elasticsearch.rb:124:in `write'
  2015-05-21 18:00:55 +0800 [warn]: /usr/local/lib/ruby/gems/2.1/gems/fluentd-0.10.53/lib/fluent/buffer.rb:296:in `write_chunk'
  2015-05-21 18:00:55 +0800 [warn]: /usr/local/lib/ruby/gems/2.1/gems/fluentd-0.10.53/lib/fluent/buffer.rb:276:in `pop'
  2015-05-21 18:00:55 +0800 [warn]: /usr/local/lib/ruby/gems/2.1/gems/fluentd-0.10.53/lib/fluent/output.rb:311:in `try_flush'
  2015-05-21 18:00:55 +0800 [warn]: /usr/local/lib/ruby/gems/2.1/gems/fluentd-0.10.53/lib/fluent/output.rb:132:in `run'
```

**Comment by repeatedly** [comment]
What the Ruby version do you use?

**Comment by pellaeon** [comment]
```
# ruby21 -v
ruby 2.1.6p336 (2015-04-13 revision 50298) [amd64-freebsd10]
```

Seems like the `sysutils/rubygem-fluentd` port has [not been updated since December 2014](https://freshports.org/sysutils/rubygem-fluentd), I'll file a PR for the maintainer.

**Comment by repeatedly** [comment]
If you hit this problem with latest fluentd, please re-open it.

**Comment by jchauncey** [comment]
We just ran into this issue - 

```
2016-02-16 21:43:44 +0000 [info]: following tail of /var/log/containers/deis-database-wk9l8_deis_deis-database-2924bad4208165101c9c94a18d0e4e1a823cb9d6d1f0e936a07cc8cf4d52c904.log
2016-02-16 21:46:22 +0000 [info]: shutting down fluentd
2016-02-16 21:46:22 +0000 [info]: shutting down input type="tail" plugin_id="object:2b198cf3c46c"
2016-02-16 21:46:22 +0000 [warn]: emit transaction failed: error_class=RuntimeError error="can't modify frozen String" tag="fluent.info"
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluent-plugin-remote_syslog-0.3.2/lib/fluent/plugin/out_remote_syslog.rb:39:in `force_encoding'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluent-plugin-remote_syslog-0.3.2/lib/fluent/plugin/out_remote_syslog.rb:39:in `block (2 levels) in emit'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluent-plugin-remote_syslog-0.3.2/lib/fluent/plugin/out_remote_syslog.rb:37:in `each_pair'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluent-plugin-remote_syslog-0.3.2/lib/fluent/plugin/out_remote_syslog.rb:37:in `block in emit'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/event.rb:54:in `call'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/event.rb:54:in `each'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluent-plugin-remote_syslog-0.3.2/lib/fluent/plugin/out_remote_syslog.rb:36:in `emit'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/output.rb:32:in `next'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/plugin/out_copy.rb:74:in `emit'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/event_router.rb:88:in `emit_stream'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/event_router.rb:79:in `emit'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/engine.rb:165:in `block in log_event_loop'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/engine.rb:163:in `each'
  2016-02-16 21:46:22 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/engine.rb:163:in `log_event_loop'
2016-02-16 21:46:22 +0000 [error]: failed to emit fluentd's log event tag="fluent.info" event={"type"=>"tail", "plugin_id"=>"object:2b198cf3c46c", "message"=>"shutting down input type=\"tail\" plugin_id=\"object:2b198cf3c46c\""} error_class=RuntimeError error=#<RuntimeError: can't modify frozen String>
2016-02-16 21:46:22 +0000 [info]: shutting down filter type="kubernetes_metadata" plugin_id="object:2b198bfe48ac"
2016-02-16 21:46:22 +0000 [info]: shutting down output type="copy" plugin_id="object:2b198ceae004"
2016-02-16 21:46:22 +0000 [info]: process finished code=0
```
