### ISSUE TITLE
buffer files not deleted

### ISSUE THREAD

**Issue by jeesim2** [fluent/fluentd#607]
hello.

Recent days I'm struggling with buffer problem.

I am tailing a folder with in_tail plugin
and copyed a large log file(3.3GB) to the tail target folder.

in_tail plugin seems worked well. and tail position reached the end of the fole.
(offerwall.2015-06-02.diskfull.recovery.log)
```
[user@fluentd]$ cat offerwall_tail_pos.log 
/logs/offerwall/offerwall.2015-06-02.log   000000000520bbc7        00000000004c0272
/logs/offerwall/offerwall.2015-06-02.diskfull.recovery.log 00000000e2a78a4c        00000000004c0189
```

And out elasticsearch plugin sending the data in bulk.
I can know elasticsearch receiving large data by the traffic.
* fluentd server network in/out graph.
![2015-06-02 11 59 10](https://cloud.githubusercontent.com/assets/1100831/7927686/cc4d9074-091e-11e5-91d8-647c032e861c.PNG)
* elasticsearch indexing graph.
![2015-06-02 11 52 00](https://cloud.githubusercontent.com/assets/1100831/7927704/f65660ee-091e-11e5-9200-b6d31fc2ebe7.PNG)
![2015-06-02 11 52 11](https://cloud.githubusercontent.com/assets/1100831/7927707/faf508bc-091e-11e5-86b8-1662eef60d03.PNG)

During 30 minutes fluent machine sended 1GB of data.

But, the buffer files not reduced, deleted any way.
most old buffer file does not changed in size during half an hour.
```
[user@fluent buffer_backup2]$ ll -h
 3.3G
-rw-r--r-- 1 irteam irteam 24M 2015-06-02 11:49 offerwall..b5177fb7346360e32.buffer
-rw-r--r-- 1 irteam irteam 32M 2015-06-02 11:13 offerwall..q5177f7b2fa2efccd.buffer
-rw-r--r-- 1 irteam irteam 32M 2015-06-02 11:13 offerwall..q5177f7c69a49a50e.buffer
-rw-r--r-- 1 irteam irteam 32M 2015-06-02 11:14 offerwall..q5177f7e4f3a8193b.buffer
-rw-r--r-- 1 irteam irteam 32M 2015-06-02 11:14 offerwall..q5177f7fd50c43ba9.buffer
-rw-r--r-- 1 irteam irteam 32M 2015-06-02 11:14 offerwall..q5177f804ceacdced.buffer
-rw-r--r-- 1 irteam irteam 32M 2015-06-02 11:14 offerwall..q5177f80d1afc5024.buffer
-rw-r--r-- 1 irteam irteam 32M 2015-06-02 11:14 offerwall..q5177f81465eeafdb.buffer
...
```

* this is the tail target folder.
```
[irteam@xvadapi101.launcher offerwall]$ ll -h
 3.6G
-rw-rw-r-- 1 irteam irteam 3.6G 2015-06-02 11:13 offerwall.2015-06-02.diskfull.recovery.log
-rw-rw-r-- 1 irteam irteam  90M 2015-06-02 12:12 offerwall.2015-06-02.log
```

* here is fluent log
```
$ tail -f logs/fluentd/fluentd.log 
  2015-06-02 11:17:57 +0900 [warn]: /home1/irteam/apps/ruby/gems/gems/fluentd-0.12.8/lib/fluent/buffer.rb:325:in `write_chunk'
  2015-06-02 11:17:57 +0900 [warn]: /home1/irteam/apps/ruby/gems/gems/fluentd-0.12.8/lib/fluent/buffer.rb:304:in `pop'
  2015-06-02 11:17:57 +0900 [warn]: /home1/irteam/apps/ruby/gems/gems/fluentd-0.12.8/lib/fluent/output.rb:321:in `try_flush'
  2015-06-02 11:17:57 +0900 [warn]: /home1/irteam/apps/ruby/gems/gems/fluentd-0.12.8/lib/fluent/output.rb:140:in `run'
2015-06-02 11:19:51 +0900 [warn]: plugin/out_elasticsearch.rb:173:rescue in send: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2015-06-02 11:19:53 +0900 [info]: plugin/out_elasticsearch.rb:67:client: Connection opened to Elasticsearch cluster => {:host=>"10.98.168.207", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.209", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.210", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.211", :port=>9200, :scheme=>"http"}
2015-06-02 11:21:09 +0900 [warn]: plugin/out_elasticsearch.rb:173:rescue in send: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2015-06-02 11:21:13 +0900 [info]: plugin/out_elasticsearch.rb:67:client: Connection opened to Elasticsearch cluster => {:host=>"10.98.168.207", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.209", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.210", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.211", :port=>9200, :scheme=>"http"}
2015-06-02 11:22:29 +0900 [warn]: fluent/output.rb:354:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2015-06-02 11:13:36 +0900 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Could not push logs to Elasticsearch after 2 retries. read timeout reached" plugin_id="object:3f8dc3402988"
  2015-06-02 11:22:29 +0900 [warn]: suppressed same stacktrace
2015-06-02 11:24:24 +0900 [warn]: plugin/out_elasticsearch.rb:173:rescue in send: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2015-06-02 11:24:26 +0900 [info]: plugin/out_elasticsearch.rb:67:client: Connection opened to Elasticsearch cluster => {:host=>"10.98.168.207", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.209", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.210", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.211", :port=>9200, :scheme=>"http"}
2015-06-02 11:25:42 +0900 [warn]: plugin/out_elasticsearch.rb:173:rescue in send: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2015-06-02 11:25:46 +0900 [info]: plugin/out_elasticsearch.rb:67:client: Connection opened to Elasticsearch cluster => {:host=>"10.98.168.207", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.209", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.210", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.211", :port=>9200, :scheme=>"http"}
2015-06-02 11:27:03 +0900 [warn]: fluent/output.rb:354:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2015-06-02 11:13:56 +0900 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Could not push logs to Elasticsearch after 2 retries. read timeout reached" plugin_id="object:3f8dc3402988"
  2015-06-02 11:27:03 +0900 [warn]: suppressed same stacktrace
 2015-06-02 11:28:58 +0900 [warn]: plugin/out_elasticsearch.rb:173:rescue in send: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2015-06-02 11:29:00 +0900 [info]: plugin/out_elasticsearch.rb:67:client: Connection opened to Elasticsearch cluster => {:host=>"10.98.168.207", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.209", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.210", :port=>9200, :scheme=>"http"}, {:host=>"10.98.168.211", :port=>9200, :scheme=>"http"}
```

I'm using this version of fluent, fluent-gems
```
[buffer]$ fluent-gem list
bigdecimal (1.2.6)
cool.io (1.3.0)
elasticsearch (1.0.9)
elasticsearch-api (1.0.9)
elasticsearch-transport (1.0.9)
excon (0.45.3)
faraday (0.9.1)
fluent-plugin-elasticsearch (0.8.0)
fluentd (0.12.8)
http_parser.rb (0.6.0)
io-console (0.4.3)
json (1.8.1)
msgpack (0.5.11)
multi_json (1.11.0)
multipart-post (2.0.0)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
sigdump (0.2.2)
string-scrub (0.0.5)
thread_safe (0.3.5)
tzinfo (1.2.2)
tzinfo-data (1.2015.4)
yajl-ruby (1.2.1)
```

* this could be happen that buffer flushed but not deleted?
* what is the buffer file flushing order in buffer files?

any advices are appreciated.

**Comment by repeatedly** [comment]
> I can know elasticsearch receiving large data by the traffic.

It depends on setup. Elasticsearch uses JVM and default setup can't process large datasets.
How many elasticsearch instances do you use?
fluent-plugin-elasticsearch prints above error when can't send logs to elasticsearch: https://github.com/uken/fluent-plugin-elasticsearch/blob/66c1105ecda1221da4e3aabf0bc498fdf8411214/lib/fluent/plugin/out_elasticsearch.rb#L173

It means fluentd tries to flush buffer chunks but your elasticsearch rejects its access.
Maybe, your elasitcsearch status is broken or lack of capacity.

> this could be happen that buffer flushed but not deleted?

So buffer chunks are not flushed yet because fluentd failed to send logs to Elasticsearch.
Keeping buffer files is correct behaviour.

**Comment by jeesim2** [comment]
thanks @repeatedly
elasticsearch cluster didnt met any error, problems.

and it is obvious that elasticsearch received large data from fluentd in bulk.

currenltly I can not gather more information, so i am closing the issue.

**Comment by repeatedly** [comment]
Re-open it if you have more information of fluentd, elasticsearch and traffic.

**Comment by stanhu** [comment]
I'm also seeing this same issue. I see status codes 200 in my Web logs, suggesting the insert was successful. I suspect the ElasticSearch transport is timing out too quickly with large payloads, causing fluentd to retransmit unnecessarily again.

Removing the files seems to cure the issue for now. I think this is still an open issue.

**Comment by stanhu** [comment]
I suspect this issue is a duplicate of https://github.com/uken/fluent-plugin-elasticsearch/issues/50. I think the default `request_timeout` of 5 s is too short.
