### ISSUE TITLE
Fluentd fail to start because one of the out_copy plugin fail

### ISSUE THREAD

**Issue by Jackyjjc** [fluent/fluentd#613]
We setup our fluentd config to ship logs to both elasticsearch cluster and an aggregator service.

```
<match **>
    type copy
    <store>
      type elasticsearch
      ....
    </store>
    <store>
      type forward
      <server>
        host <our_host_server>
        port 443
      </server>
    </store>
  </match>
```

However, when one of the store is failing, fluentd failed to start completely. In our case, it was when the host server is down:

```
2015-06-12 05:39:29 +0000 [error]: unexpected error error="getaddrinfo: Name or service not known"
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_forward.rb:384:in `pack_sockaddr_in'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_forward.rb:384:in `resolve_dns!'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_forward.rb:376:in `resolved_host'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_forward.rb:346:in `initialize'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_forward.rb:89:in `new'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_forward.rb:89:in `block in configure'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_forward.rb:68:in `each'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_forward.rb:68:in `configure'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_copy.rb:43:in `block in configure'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_copy.rb:33:in `each'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/plugin/out_copy.rb:33:in `configure'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/engine.rb:127:in `block in configure'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/engine.rb:116:in `each'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/engine.rb:116:in `configure'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/engine.rb:77:in `run_configure'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:382:in `run_configure'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:133:in `block in start'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:250:in `call'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:250:in `main_process'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:225:in `block in supervise'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:224:in `fork'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:224:in `supervise'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:128:in `start'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/command/fluentd.rb:164:in `<top (required)>'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/bin/fluentd:6:in `<top (required)>'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/bin/fluentd:23:in `load'
  2015-06-12 05:39:29 +0000 [error]: /usr/lib/fluent/ruby/bin/fluentd:23:in `<top (required)>'
  2015-06-12 05:39:29 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2015-06-12 05:39:29 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2015-06-12 05:39:29 +0000 [info]: process finished code=256
2015-06-12 05:39:29 +0000 [warn]: process died within 1 second. exit.
```

Is it possible to stop this behaviour and make <copy> still ship logs to the store that is working? In production, we don't want to cause the logging to fail if one of the component fail.

**Comment by repeatedly** [comment]
> Is it possible to stop this behaviour and make still ship logs to the store that is working?

Currently nothing. Hmm, I know fluentd can also serve as buffered queue.
So sending logs to local fluentd is still useful on such situation.

I will consider lazy resolve host feature.

**Comment by repeatedly** [comment]
From your logs, you seems to use td-agent 1.
Treasure Data released td-agent 2 with newer components.
So if you setup new fluentd cluster, I strongly recommend to use td-agent 2.

**Comment by Jackyjjc** [comment]
Thank you! I will change to td-agent2.

We found that this only happens when it can't resolve the host so we added dummy DNS records on Route53 and that solves the problem for us at the moment. I guess this is a very specific edge case where our aggregators are not deployed yet but the forwarders are configured.

**Comment by repeatedly** [comment]
Node's `@sockaddr` is used in `on_heartbeat`.
So if we support lazy host resolution, users can't use udp type.

**Comment by repeatedly** [comment]
I'm not working on lazy DSN resolution on #735

**Comment by repeatedly** [comment]
v0.14's out_forward now has `ignore_network_errors_at_startup`
