### ISSUE TITLE
log repeat

### ISSUE THREAD

**Issue by breath-co2** [fluent/fluentd#665]
td-agent A use in_tail plugin and forward another forward B, this forward open require_ack_response, heartbeat_type is tcp.
forward B use out_mongo plugin write into mongo db.
then write 5 million logs in to the log files as soon as possible.

at last, I found 5009632 logs.

my td-agent version is 0.12.15, mongo plugin version is 0.7.10.

**Comment by breath-co2** [comment]
druing this time, there have been the following error:

```
2015-08-27 10:41:26 +0800 [info]: plugin/in_tail.rb:477:initialize: following tail of /data/testlog/log/bb.log
2015-08-27 10:41:36 +0800 [debug]: plugin/out_forward.rb:387:rescue in block in on_timer: failed to send heartbeat packet to 172.30.249.137:12100 error="Connection refused - connect(2) for \"172.30.249.137\" port 12100"
2015-08-27 10:41:37 +0800 [debug]: plugin/out_forward.rb:387:rescue in block in on_timer: failed to send heartbeat packet to 172.30.249.137:12100 error="Connection refused - connect(2) for \"172.30.249.137\" port 12100"
2015-08-27 10:41:38 +0800 [warn]: plugin/out_forward.rb:499:tick: detached forwarding server '172.30.249.137' host="172.30.249.137" port=12100 hard_timeout=true
2015-08-27 10:41:38 +0800 [debug]: plugin/out_forward.rb:217:rebuild_weight_array: rebuilding weight array lost_weight=60
2015-08-27 10:41:38 +0800 [debug]: plugin/out_forward.rb:387:rescue in block in on_timer: failed to send heartbeat packet to 172.30.249.137:12100 error="Connection refused - connect(2) for \"172.30.249.137\" port 12100"
2015-08-27 10:41:42 +0800 [warn]: plugin/out_forward.rb:526:heartbeat: recovered forwarding server '172.30.249.137' host="172.30.249.137" port=12100
2015-08-27 10:51:27 +0800 [warn]: plugin/out_forward.rb:340:send_data: no response from 172.30.249.137:12100. regard it as unavailable.
2015-08-27 10:51:28 +0800 [warn]: fluent/output.rb:354:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2015-08-27 10:51:27 +0800 error_class="Fluent::ForwardOutputACKTimeoutError" error="node 172.30.249.137:12100 does not return ACK" plugin_id="object:120b3e4"
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/plugin/out_forward.rb:342:in `send_data'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/plugin/out_forward.rb:188:in `block in write_objects'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/plugin/out_forward.rb:182:in `times'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/plugin/out_forward.rb:182:in `write_objects'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/output.rb:463:in `write'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/buffer.rb:325:in `write_chunk'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/buffer.rb:304:in `pop'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/output.rb:321:in `try_flush'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/output.rb:140:in `run'
2015-08-27 10:51:28 +0800 [warn]: fluent/output.rb:354:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2015-08-27 10:51:33 +0800 error_class="RuntimeError" error="no nodes are available" plugin_id="object:120b3e4"
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/plugin/out_forward.rb:200:in `write_objects'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/output.rb:463:in `write'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/buffer.rb:325:in `write_chunk'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/buffer.rb:304:in `pop'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/output.rb:321:in `try_flush'
  2015-08-27 10:51:28 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.15/lib/fluent/output.rb:140:in `run'
```

**Comment by repeatedly** [comment]
You use at-least-once with `require_ack_response` and your network or fluentd B condition becomes unstable.
If there is no error in fluentd B logs, check your network environment.

**Comment by repeatedly** [comment]
ping?

**Comment by repeatedly** [comment]
From fluentd logs, `at-least-once` works correctly so this is not fluentd issue.
The problem is why B server is unstable but it needs system logs to identify the problem.
