### ISSUE TITLE
Failure in gelr message: error_class="ArgumentError" error="short_message is missing. Options version, short_message and host must be set." plugin_id="object:3f7fbd316380"

### ISSUE THREAD

**Issue by worldcitizen** [fluent/fluentd#669]
I get a warning when ,"short_message":"", exists in a gelf line, not logging isn't forwarded anymore to elasticsearch/graylog2.

,"short_message":"",
2015-09-03 15:47:48 +0200 [warn]: temporarily failed to flush the buffer. next_retry=2015-09-03 15:47:49 +0200 error_class="ArgumentError" error="short_message is missing. Options version, short_message and host must be set." plugin_id="object:3f7fbd316380"
  2015-09-03 15:47:48 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/gelf-1.4.0/lib/gelf/notifier.rb:200:in `block in check_presence_of_mandatory_attributes'
  2015-09-03 15:47:48 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/gelf-1.4.0/lib/gelf/notifier.rb:198:in `each'
  2015-09-03 15:47:48 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/gelf-1.4.0/lib/gelf/notifier.rb:198:in `check_presence_of_mandatory_attributes'
  2015-09-03 15:47:48 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/gelf-1.4.0/lib/gelf/notifier.rb:162:in `extract_hash'
  2015-09-03 15:47:48 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/gelf-1.4.0/lib/gelf/notifier.rb:140:in `notify_with_level!'
  2015-09-03 15:47:48 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/gelf-1.4.0/lib/gelf/notifier.rb:118:in `notify!'
  2015-09-03 15:47:48 +0200 [warn]: /etc/td-agent/plugin/out_gelf.rb:85:in `block in write'
  2015-09-03 15:47:48 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/buf_memory.rb:61:in `feed_each'
  2015-09-03 15:47:48 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/buf_memory.rb:61:in `msgpack_each'
  2015-09-03 15:47:48 +0200 [warn]: /etc/td-agent/plugin/out_gelf.rb:84:in `write'
  2015-09-03 15:47:48 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:325:in `write_chunk'
  2015-09-03 15:47:48 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:304:in `pop'
  2015-09-03 15:47:48 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:321:in `try_flush'
  2015-09-03 15:47:48 +0200 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:140:in `run'
2015-09-03 15:47:49 +0200 [warn]: temporarily failed to flush the buffer. next_retry=2015-09-03 15:47:51 +0200 error_class="ArgumentError" error="short_message is missing. Options version, short_message and host must be set." plugin_id="object:3f7fbd316380"
  2015-09-03 15:47:49 +0200 [warn]: suppressed same stacktrace
2015-09-03 15:47:51 +0200 [warn]: temporarily failed to flush the buffer. next_retry=2015-09-03 15:47:55 +0200 error_class="ArgumentError" error="short_message is missing. Options version, short_message and host must be set." plugin_id="object:3f7fbd316380"
  2015-09-03 15:47:51 +0200 [warn]: suppressed same stacktrace

**Comment by repeatedly** [comment]
Could you paste your configuration and actual log example?
Only your log, we can't understand what is the problem.

**Comment by worldcitizen** [comment]
This is a log example. I've replaced all private and information that I don't want to be shared with a "*".
So you will see quite a lot of "*".

2015-09-03 15:47:42 +0200 graylog2.php: {"version":"1.0","host":"*","timestamp":1441288062.5722,"facility":"Library","level":4,"short_message":"","file":"/var/www/Library/*/src/DataPool/Backends/\*.php","line":75,"full_message":"Exception \"*\\Library\\DataPool\\DataPoolReaderException\" thrown in: \"/var/www/Library/*/src/DataPool/Backends/\*.php\" on line 75 with message: \"\" and errorcode 0.\nBacktrace:\n#0 /var/www/Library/*/src/DataPool/Backends/\*.php(269): *\\Library\\DataPool\\*->getFileContentFromPath('20150903-0310/p...', '306677')\n#1 /var/www/Library/*/src/DataPool/\*.php(42): *\\Library\\DataPool\\StorageBackend->getFileContentFromPath('20150903-0310/p...', '306677')\n#2 /var/www/*/*/src/Renderers/\*.php(83): *\\Library\\readers\\*->getMiniCartSnippet(Object(*\\Library\\ValueObjects\\Sku))\n#3 /var/www/*/*/src/Renderers/\*.php(57): *\\*\\renderers\\*->createSnippet(Object(TheSeer\\fDOM\\fDOMElement))\n#4 /var/www/StoreSkeleton/*/src/Renderers/\*.php(43): *\\*\\renderers\\*->doRender()\n#5 /var/www/StoreSkeleton/*/src/Handlers/\*.php(279): *\\StoreSkeleton\\renderers\\Abstract*->render(Object(*\\Library\\domwrappers\\Cart))\n#6 /var/www/StoreSkeleton/*/src/Handlers/\*.php(70): *\\StoreSkeleton\\handlers\\*->execute(Object(*\\StoreSkeleton\\models\\ProductDetailsPageModel))\n#7 /var/www/HttpFramework/*/src/Workflow/\*.php(103): *\\StoreSkeleton\\handlers\\*->execute(Object(*\\StoreSkeleton\\models\\ProductDetailsPageModel))\n#8 /var/www/HttpFramework/*/src/\*.php(30): *\\HttpFramework\\workflows\\AbstractWorkflow->execute(Object(*\\HttpFramework\\HttpGetRequest))\n#9 /var/www/*/*/\*.php(17): *\\HttpFramework\\*->run()\n#10 /var/www/StorePreBoot/\*.php(10): require('/var/www/*...')\n#11 {main}\n---------PREVIOUS--MARKER---------\n","_request_method":"GET","_request_browser":"Mozilla/5.0 (Windows NT 6.0; rv:40.0) Gecko/20100101 Firefox/40.0","_request_remoteIp":"*.*.*.*","_referer":"https://*/anmelden","_request_pageUri":"https://*/*","_domain":"*","_account_id":"*","_account_username":"*@*","_customer_number":"*","_customer_conditionCustomerNumber":"","_customer_priceGroup":"enduser"}

**Comment by repeatedly** [comment]
How to generate these records?
From your log, your events seem to have empty string `short_message` field and it rejects by gelf client.

https://github.com/emsearcy/fluent-plugin-gelf/blob/51306d6d1c9dacd75f1c18c80a7e8a3d0834e0f1/lib/fluent/plugin/out_gelf.rb#L76

From fluent-plugin-gelf source code, output plugin sets `short_message` correctly.
So I assume your original events have invalid empty `short_message` field.

**Comment by worldcitizen** [comment]
So if I understand it correctly an empty short_message isn't allowed according to the standard?

**Comment by repeatedly** [comment]
I don't know because I'm not GELF user.

**Comment by repeatedly** [comment]
Close. This seems not fluentd issue.
