### ISSUE TITLE
filter_record_transformer: a problem with enable_ruby

### ISSUE THREAD

**Issue by icy** [fluent/fluentd#694]
## Input filter

````
<filter system.syslog.cron.info>
  type record_transformer
  enable_ruby
  <record>
    user    "${message.slice(1, message.index(" ") - 2)}"
    message "${message.slice(message.index(" ") + 1, message.size)}"
  </record>
</filter>
````

## Expected result

No parser error as double-quoting is a valid ruby expression.

## Actual parser error

````
<edded/bin/ruby /usr/sbin/td-agent -c /etc/td-agent/agent.conf --log /fluentd/td-agent.log                                           
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/config/basic_parser.rb:88:in `parse_error!': expected end of line at rsylog.conf line 5,47 (Fluent::ConfigParseError)
  4:   <record>
  5:     user    "${message.slice(1, message.index(" ") - 2)}"

     -----------------------------------------------^
  6:     message "${message.slice(message.index(' ') + 1, message.size)}"
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/config/v1_parser.rb:130:in `parse_element'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/config/v1_parser.rb:93:in `parse_element'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/config/v1_parser.rb:93:in `parse_element'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/config/v1_parser.rb:163:in `block in eval_include'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/config/v1_parser.rb:157:in `each'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/config/v1_parser.rb:157:in `eval_include'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/config/v1_parser.rb:143:in `parse_include'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/config/v1_parser.rb:102:in `parse_element'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/config/v1_parser.rb:41:in `parse!'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/config/v1_parser.rb:31:in `parse'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/config.rb:29:in `parse'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:412:in `read_config'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:127:in `start'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/bin/fluentd:6:in `<top (required)>'
        from /opt/td-agent/embedded/bin/fluentd:23:in `load'
        from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
        from /usr/sbin/td-agent:7:in `load'
        from /usr/sbin/td-agent:7:in `<main>'
````

## Work-around

Use single-quote instead of double-quote

**Comment by sonots** [comment]
This is not an error of record_transformer, but an error of config parser. The config parser could not find the end of `"` well. 

You can do as

```
"${message.slice(1, message.index(\" \") - 2)}"
```

or 

```
'${message.slice(1, message.index(" ") - 2)}'
```

or

```
${message.slice(1, message.index(" ") - 2)}
```

**Comment by icy** [comment]
I see. Thanks a lot, @sonots !
