### ISSUE TITLE
error "temporarily failed to flush the buffer" in using fluentd-plugin-elasticsearch

### ISSUE THREAD

**Issue by kakalo24** [fluent/fluentd#739]
td-agent version is 2.2.1
fluentd-plugin-elasticsearch version is 1.2.1
elasticsearch version is 2.1.0

td-agent and elasticsearch are in the same machine，
td-agent.conf was be configured like this :

<match docker.*>
  type elasticsearch
  host 127.0.0.1
  port 9200
  index_name fluentd
  type_name nginx
  ssl_verify false
  logstash_format true
</match>

<source>
  type tail
  format json
  path /var/lib/docker/containers/*/*.log
  pos_file /var/log/td-agent/queue_log.pos
  tag docker.kk
</source>

but td-agent's log reported error:
[warn]: temporarily failed to flush the buffer. next_retry=2015-12-07 20:24:20 +0800 error_class="Elasticsearch::Transport::Transport::Errors::Found" error="[302] " plugin_id="object:3fcf5df04558"
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:136:in `__raise_transport_error'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:228:in `perform_request'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/client.rb:119:in `perform_request'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/ping.rb:20:in `block in ping'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:191:in `__rescue_from_not_found'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/ping.rb:19:in `ping'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.2.1/lib/fluent/plugin/out_elasticsearch.rb:71:in `client'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.2.1/lib/fluent/plugin/out_elasticsearch.rb:178:in `rescue in send'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.2.1/lib/fluent/plugin/out_elasticsearch.rb:176:in `send'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.2.1/lib/fluent/plugin/out_elasticsearch.rb:170:in `write'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:325:in `write_chunk'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:304:in `pop'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:321:in `try_flush'
  2015-12-07 20:24:05 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:140:in `run'
2015-12-07 20:24:20 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2015-12-07 20:24:46 +0800 error_class="Elasticsearch::Transport::Transport::Errors::Found" error="[302] " plugin_id="object:3fcf5df04558"
  2015-12-07 20:24:20 +0800 [warn]: suppressed same stacktrace

I don't know what problem with td-agent, please help me to solve the problem,thanks.

**Comment by repeatedly** [comment]
This is fluent-plugin-elasticsearch issue.
Please re-submit it on fluent-plugin-elasticsearch repository.
