### ISSUE TITLE
Fluentd process gets killed for out of memory cause

### ISSUE THREAD

**Issue by comtef** [fluent/fluentd#740]
I'm using fluentd to parse logs in json with the tail plugin, from several machines.
The messages are forwarded to an aggregator instance that is sending all the trafic to Kinesis.

The agregator instance fails on the following error resulting in the process consuming more and more memory then gets killed.

2015-12-06 07:43:59 +0100 [error]: error on forwerder thread error=" size of string is too long to pack: 4536379735 bytes should be <= 4294967295" 
2015-12-06 07:43:59 +0100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/process.rb:251:in `to_msgpack' 
2015-12-06 07:43:59 +0100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/process.rb:251:in `block in run' 
2015-12-06 07:43:59 +0100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/process.rb:249:in `each' 
2015-12-06 07:43:59 +0100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/process.rb:249:in `run'

**Comment by repeatedly** [comment]
> then gets killed.

It means fluentd's worker process is dead, right?

> 2015-12-06 07:43:59 +0100 [error]: error on forwerder thread error=" size of string is too long to pack: 4536379735 bytes should be <= 4294967295" 

You tried to serialize long size string as msgpack.
Did you send 4GB data in one chunk?

For correct answer, we need to check actual configuration.
I assume you use `in_http` plugin because `in_http` is only built-in plugin which uses process.rb module .

**Comment by comtef** [comment]
> It means fluentd's worker process is dead, right?

Here is a top output a system engineer was able to provide me.
If this is not enough, please tell me how to get useful data.
```
top - 10:46:57 up 16 days, 11:26,  2 users,  load average: 0.08, 0.03, 0.05
Tasks: 722 total,   2 running, 720 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.8 us,  0.8 sy,  0.0 ni, 97.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 26386520+total, 11624640+free, 14429030+used,  3328504 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used. 11825168+avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND

145074 td-agent  20   0  0.126t 0.096t   2932 S   0.0 39.0   4589:09 ruby
145104 td-agent  20   0 16.626g 0.014t   4052 S   0.3  5.6 689:34.64 ruby
145124 td-agent  20   0 14.517g 0.012t   4048 S   0.3  4.9 582:46.86 ruby
145078 td-agent  20   0 6657108 5.231g   3964 S   0.3  2.1 679:59.86 ruby
145086 td-agent  20   0 6018132 4.670g   4056 S   0.3  1.9 722:00.64 ruby
145153 td-agent  20   0 5952596 866888   4036 S   0.3  0.3 723:22.28 ruby
```

The configuration for the nodes :
```
<source>
  type monitor_agent                                      
  bind 0.0.0.0                                            
  port 24220                                              
</source>

<source>
  type tail
  path /ESTAT/prof.estat.com/logs/json_log-all.estat.com
  pos_file /ESTAT/tmp/httpd.json.pos
  tag apache.json
  format json
  rotate_wait 30
  log_level info
</source>

<filter apache.**>
  type grep
  regexp1 metrics streaming
</filter>

<match apache.**>                                         
  type forward                                            
  send_timeout 60s                                        
  recover_wait 10s                                        
  heartbeat_interval 1s                                   
  heartbeat_type tcp
  phi_failure_detector true
  phi_threshold 16                                        
  hard_timeout 60s                                        
  buffer_type file                                        
  buffer_path /ESTAT/fluentd/buffer/                      
  buffer_chunk_limit 8m                                   
  buffer_queue_limit 1024                                 
  flush_interval 30s                                      
  retry_wait 20s                                          
  retry_limit 20                                          
  disable_retry_limit false                               
  log_level debug
  <server>
    host xxxx                          
    port 24284                                            
    weight 100
  </server>
  <server>
    host yyyy                 
    port 24284                                            
    standby yes                                           
    weight 100
  </server>
</match>
  
<match fluent.**>                                         
  type grep
  regexp1 message pattern not match                       
  tag error.parsing
</match>
 
<match error.parsing>                                     
  type copy                                               
  <store>
    type file                                             
    path /tmp/fluentd.out
    buffer_type memory
    flush_interval 1
    append true
  </store>
  <store>
    type datacounter                                      
    count_interval 1                                      
    count_key message                                     
    pattern1 error pattern
    tag error.parsing.count
    outcast_unmatched yes
  </store>
</match>
 
<match error.parsing.count>
  type stdout                                             
</match>
```

And the configuration for the aggregator

```
<source>
  type monitor_agent
  bind 0.0.0.0
  port 24220
</source>
 
<source>                            
  type forward                      
  bind 0.0.0.0                      
  port 24284                        
  log_level warn
</source>

<filter apache.**>
  type record_transformer
  enable_ruby
  <record>
   fluentd_timestamp ${Time.now.to_i
  </record>
  log_level warn
</filter>
 
<match apache.**>
  type kinesis                      
  region eu-west-1                  
  stream_name STREAMING_FLUENTD     
  aws_key_id XXXXX
  aws_sec_key XXXXX                 
  random_partition_key true         
  use_yajl true                     
# zlib_compression true             
  detach_process 5                  
  num_threads 8                     
  order_events false                
  buffer_type file                  
  buffer_path /opt/td-agent/buffer/ 
  buffer_chunk_limit 32m            
  buffer_queue_limit 1024           

  flush_interval 5s                 
  retry_wait 20s
  disable_retry_limit true          
  log_level warn                    
</match>
```

> Did you send 4GB data in one chunk?

No, the buffers size are 8m and 32m, is there anything wrong in the configuration that would lead to this problem?

**Comment by repeatedly** [comment]
Thanks. Configuration seems correct for me.
Could you teach me how volume, e.g. xx MB/s, did you send to kinesis plugin?
And this problem happens frequently or not?

**Comment by comtef** [comment]
We're sending up to 20MB/s and this is happening after a few days.

**Comment by comtef** [comment]
We had to use the multi process plugin on the aggregator to get enough throughput and, it was a huge bottleneck with only one process. The out of memory problem never happened again. Still, I can't explain the cause.
