### ISSUE TITLE
uninitialized constant Fluent::TextParser::Parser

### ISSUE THREAD

**Issue by amyth** [fluent/fluentd#758]
I am facing an issue while creating a custom parser plugin to be used with "in_tail" plugin. Any parser plugin file that I put inside the loadable plugin path `/etc/td-agent/plugin`, I see the following error in the `td-agent.log`

```
2015-12-23 15:26:58 +0530 [info]: starting fluentd-0.10.50
2015-12-23 15:26:58 +0530 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2015-12-23 15:26:58 +0530 [error]: unexpected error error="uninitialized constant Fluent::TextParser::Parser"
  2015-12-23 15:26:58 +0530 [error]: /etc/td-agent/plugin/parser_kv.rb:3:in `<class:TextParser>'
  2015-12-23 15:26:58 +0530 [error]: /etc/td-agent/plugin/parser_kv.rb:2:in `<module:Fluent>'
  2015-12-23 15:26:58 +0530 [error]: /etc/td-agent/plugin/parser_kv.rb:1:in `<top (required)>'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/plugin.rb:59:in `block in load_plugin_dir'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/plugin.rb:57:in `each'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/plugin.rb:57:in `load_plugin_dir'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/engine.rb:129:in `load_plugin_dir'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/supervisor.rb:369:in `block in init_engine'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/supervisor.rb:366:in `each'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/supervisor.rb:366:in `init_engine'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/supervisor.rb:129:in `block in start'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/supervisor.rb:246:in `call'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/supervisor.rb:246:in `main_process'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/supervisor.rb:221:in `block in supervise'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/supervisor.rb:220:in `fork'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/supervisor.rb:220:in `supervise'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/supervisor.rb:126:in `start'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/lib/fluent/command/fluentd.rb:160:in `<top (required)>'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.50/bin/fluentd:6:in `<top (required)>'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2015-12-23 15:26:58 +0530 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2015-12-23 15:26:58 +0530 [error]: /usr/sbin/td-agent:7:in `load'
  2015-12-23 15:26:58 +0530 [error]: /usr/sbin/td-agent:7:in `<main>'
2015-12-23 15:26:58 +0530 [info]: process finished code=256
2015-12-23 15:26:58 +0530 [warn]: process died within 1 second. exit.
```

This [stackoverflow question](http://stackoverflow.com/questions/34432257/fluentd-custom-parser-plugin-raises-uninitialized-constant-fluent-error) I asked has more information.

**Comment by repeatedly** [comment]
It seems your fluentd is too old.
`Fluent::TextParser::Parser` class is introduced since fluentd v0.10.58.
Using newer td-gent resolve this problem.

**Comment by repeatedly** [comment]
Ah, I close the issue by mistake.
Please close this issue after update your fluentd / td-agent.

**Comment by amyth** [comment]
@repeatedly Thanks. Closing it.
