### ISSUE TITLE
Possible bug in the behaviour of exclude_path in tail plugin ? 

### ISSUE THREAD

**Issue by nicktgr15** [fluent/fluentd#768]
Hi,

I'm using fluentd with the following configuration for the tail plugin. The configuration works as expected with rotated .bz2 files ignored by the agent. 
```
<source>
type tail
path /var/log/stats/livestats/%Y/%m/%d/*
refresh_interval 5
pos_file /var/log/td-agent/tail.pos
exclude_path ["/var/log/stats/livestats/%Y/%m/%d/*.bz2"]
read_from_head true
tag mytag
format none
</source>
```

However I came across the following log output today where fluentd was trying to read a .bz2 file that was supposed to be ignored. There were no changes in the config and the system is running with the above configuration without problems for months. Could be an "edge case" bug in the tail plugin?

After the errors the agent went back to normal so it was in that state for about 10 seconds.

```
2016-01-10 22:00:02 +0000 [info]: following tail of /var/log/stats/livestats/2016/01/10/s103.2016-01-10-22-GMT
2016-01-10 22:01:02 +0000 [error]: Permission denied @ rb_sysopen - /var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT.bz2
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:554:in `initialize'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:554:in `open'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:554:in `on_notify'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:343:in `on_notify'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:326:in `attach'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:135:in `setup_watcher'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:153:in `block in start_watchers'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:140:in `each'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:140:in `start_watchers'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:130:in `refresh_watchers'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:430:in `call'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:430:in `on_timer'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run_once'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run'
  2016-01-10 22:01:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:214:in `run'
2016-01-10 22:01:03 +0000 [error]: Permission denied @ rb_sysopen - /var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT.bz2
  2016-01-10 22:01:03 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:554:in `initialize'
  2016-01-10 22:01:03 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:554:in `open'
  2016-01-10 22:01:03 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:554:in `on_notify'
  2016-01-10 22:01:03 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:343:in `on_notify'
  2016-01-10 22:01:03 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:430:in `call'
  2016-01-10 22:01:03 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:430:in `on_timer'
  2016-01-10 22:01:03 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run_once'
  2016-01-10 22:01:03 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run'
  2016-01-10 22:01:03 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:214:in `run'
2016-01-10 22:01:04 +0000 [error]: Permission denied @ rb_sysopen - /var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT.bz2
  2016-01-10 22:01:04 +0000 [error]: suppressed same stacktrace
2016-01-10 22:01:05 +0000 [error]: Permission denied @ rb_sysopen - /var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT.bz2
  2016-01-10 22:01:05 +0000 [error]: suppressed same stacktrace
2016-01-10 22:01:06 +0000 [error]: Permission denied @ rb_sysopen - /var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT.bz2
  2016-01-10 22:01:06 +0000 [error]: suppressed same stacktrace
2016-01-10 22:01:07 +0000 [error]: Permission denied @ rb_sysopen - /var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT.bz2
  2016-01-10 22:01:07 +0000 [error]: suppressed same stacktrace
2016-01-10 22:01:07 +0000 [error]: Permission denied @ rb_sysopen - /var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT.bz2
  2016-01-10 22:01:07 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:554:in `initialize'
  2016-01-10 22:01:07 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:554:in `open'
  2016-01-10 22:01:07 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:554:in `on_notify'
  2016-01-10 22:01:07 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:343:in `on_notify'
  2016-01-10 22:01:07 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:446:in `call'
  2016-01-10 22:01:07 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:446:in `on_change'
  2016-01-10 22:01:07 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run_once'
  2016-01-10 22:01:07 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run'
  2016-01-10 22:01:07 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:214:in `run'
2016-01-10 22:01:08 +0000 [error]: Permission denied @ rb_sysopen - /var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT.bz2
  2016-01-10 22:01:08 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:554:in `initialize'
  2016-01-10 22:01:08 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:554:in `open'
  2016-01-10 22:01:08 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:554:in `on_notify'
  2016-01-10 22:01:08 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:343:in `on_notify'
  2016-01-10 22:01:08 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:430:in `call'
  2016-01-10 22:01:08 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:430:in `on_timer'
  2016-01-10 22:01:08 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run_once'
  2016-01-10 22:01:08 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run'
  2016-01-10 22:01:08 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/plugin/in_tail.rb:214:in `run'
2016-01-10 22:01:09 +0000 [error]: Permission denied @ rb_sysopen - /var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT.bz2
  2016-01-10 22:01:09 +0000 [error]: suppressed same stacktrace
2016-01-10 22:01:10 +0000 [error]: Permission denied @ rb_sysopen - /var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT.bz2
  2016-01-10 22:01:10 +0000 [error]: suppressed same stacktrace
2016-01-10 22:01:11 +0000 [error]: Permission denied @ rb_sysopen - /var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT.bz2
  2016-01-10 22:01:11 +0000 [error]: suppressed same stacktrace
2016-01-10 22:11:24 +0000 [info]: detected rotation of /var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT; waiting 5 seconds
```

**Comment by repeatedly** [comment]
Listing files operation is not atomic so if refresh files is executed over two consecutive days,
this problem happens.
Avoiding this problem, there are several approaches.

- Use more strict pattern in `path`
- Use more wider pattern in `exclude_path`, e.g. without `%d`.

**Comment by nicktgr15** [comment]
Thanks the quick response!

The issue happened in a directory that included logs of a specific day (i.e. not two consecutive days).
```
/var/log/stats/livestats/2016/01/10/s103.2016-01-10-22-GMT
/var/log/stats/livestats/2016/01/10/s103.2016-01-10-21-GMT.bz2
```

I had a look at the code and based on what I understand the ```refresh_watchers``` is called every 60 seconds (with the current config) and the ```expand_paths``` is called as part of it. I can't see something happening concurrently :S 
Would be possible to outline the steps that are not atomic to better understand the problem? 

To me at the moment it looks like:
- refresh_watchers
- list all paths matching /var/log/stats/livestats/%Y/%m/%d/*
- exclude all paths matching /var/log/stats/livestats/%Y/%m/%d/*.bz2
- done

**Comment by repeatedly** [comment]
I see. I think the possible situation is below:

- Expands `exclude_path` paths: https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_tail.rb#L119
- Rotation program rotates file and creates new bz2 file
- Expands each `path` paths: https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_tail.rb#L120

In this situation, `exclude_path`'s path is ignored.
In your case, `/var/log/stats/livestats/%Y/%m/%d/*-GMT` seems to work without `exclude_path` parameter.

**Comment by nicktgr15** [comment]
Great! Thanks a lot for the detailed explanation.. it all makes sense now. I will update the config to remove the "exclude_path" option and set the "path" as suggested.
