### ISSUE TITLE
monitor_agent: debug=true broken for a long time

### ISSUE THREAD

**Issue by giner** [fluent/fluentd#793]
Querying data from monitor_agent with "?debug=true" was broken somewhere between v0.10.45 and v0.10.50 and still does not work.

```
$ curl localhost:24220/api/plugins.json

{"plugins":[{"plugin_id":"object:3fdbde3cd378","plugin_category":"input","type":"forward","config":{"type":"forward"},"output_plugin":false,"retry_count":null},{"plugin_id":"object:3fdbde3cc11c","plugin_category":"input","type":"http","config":{"type":"http","port":"8888"},"output_plugin":false,"retry_count":null},{"plugin_id":"object:3fdbde3b8c98","plugin_category":"input","type":"debug_agent","config":{"type":"debug_agent","bind":"127.0.0.1","port":"24230"},"output_plugin":false,"retry_count":null},{"plugin_id":"object:3fdbde369670","plugin_category":"input","type":"monitor_agent","config":{"type":"monitor_agent","bind":"0.0.0.0","port":"24220"},"output_plugin":false,"retry_count":null},{"plugin_id":"object:3fdbde9ecd30","plugin_category":"output","type":"tdlog","config":{"type":"tdlog","apikey":"xxxxxx","auto_create_table":"","buffer_type":"file","buffer_path":"/var/log/td-agent/buffer/td"},"output_plugin":true,"buffer_queue_length":0,"buffer_total_queued_size":0,"retry_count":0},{"plugin_id":"object:3fdbdde43ec0","plugin_category":"output","type":"stdout","config":{"type":"stdout"},"output_plugin":true,"retry_count":null}]}
```

```
$ curl localhost:24220/api/plugins.json?debug=true

{"message ":"Internal Server Error","error":"undefined method `respond_to?' for #<Fluent::Config::Section:0x007fb7bc798f80>","backgrace":["/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/config/section.rb:73:in `method_missing'","/opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:285:in `generate'","/opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:285:in `pretty_generate'","/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_monitor_agent.rb:132:in `render_json_error'","/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_monitor_agent.rb:127:in `render_json'","/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_monitor_agent.rb:168:in `process'","/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_monitor_agent.rb:40:in `do_GET'","/opt/td-agent/embedded/lib/ruby/2.1.0/webrick/httpservlet/abstract.rb:106:in `service'","/opt/td-agent/embedded/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'","/opt/td-agent/embedded/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'","/opt/td-agent/embedded/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'"]
```

**Comment by repeatedly** [comment]
Thanks for the report!
I will fix it.
