### ISSUE TITLE
out_file + logrotate error

### ISSUE THREAD

**Issue by perrin4869** [fluent/fluentd#869]
I have the following setup:

```
<match foo>
  type file
  path /var/log/td-agent/foo
  format csv
  time_slice_format %H
  append true # append to already existing file instead of creating a new file, ie, log.20140608_0.log, log.20140608_1.log, etc...
  flush_interval 1m
</match>
```

It works exactly as expected as long as I don't point `logrotate` to it. However, if I use `logrotate`, for example, as follows:

```
/var/log/td-agent/foo.*.log {
    size 1000k
    create 700 username groupname
    rotate 4
}
```

In that case, at around 3AM in the morning I'll most likely find the following kind of log in `/var/log/td-agent/td-agent.log`:

```
2016-03-17 03:15:28 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-17 03:15:29 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/foo.03.log" plugin_id="object:3ffed140e254"
  2016-03-17 03:15:28 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin/out_file.rb:91:in `initialize'
  2016-03-17 03:15:28 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin/out_file.rb:91:in `open'
  2016-03-17 03:15:28 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin/out_file.rb:91:in `write'
  2016-03-17 03:15:28 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/buffer.rb:345:in `write_chunk'
  2016-03-17 03:15:28 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/buffer.rb:324:in `pop'
  2016-03-17 03:15:28 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/output.rb:329:in `try_flush'
  2016-03-17 03:15:28 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/output.rb:140:in `run'
2016-03-17 03:15:29 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-17 03:15:31 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/foo.03.log" plugin_id="object:3ffed140e254"
  2016-03-17 03:15:29 +0900 [warn]: suppressed same stacktrace
2016-03-17 03:15:31 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-17 03:15:35 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/foo.03.log" plugin_id="object:3ffed140e254"
  2016-03-17 03:15:31 +0900 [warn]: suppressed same stacktrace

...
```
After that, all consecutive flushing fails even for logs at 4AM (`/var/log/td-agent/foo.04.log`),
5AM, etc., while the buffer files keep getting written.

Using td-agent 0.12.20 on CentOS 6.4

PS: In a slightly unrelated note, is there a plan to support variables in `out_file` paths, based on tag parts or record fields? Would you be open to accepting a pull request adding such feature?

Edit: I removed the `logrotate` configuration for 2 days and the problems have gone, so it's safe to assume this is some incompatibility between `fluentd` and `logrotate`

**Comment by repeatedly** [comment]
If the problem doesn't happen without logrotate,
logrotate seems to create new file with invalid permission.
I'm not sure how to handle this in out_file plugin because
the logrotate is the outside of fluentd...

**Comment by perrin4869** [comment]
Well, the thing is that if I check the permissions of the log files after the fact, they seem to be just fine... And yet fluentd still fails to flush the logs

**Comment by repeatedly** [comment]
Could you apply following patch to your fluentd?

```rb
diff --git a/lib/fluent/plugin/out_file.rb b/lib/fluent/plugin/out_file.rb
index d2d795a..cea8aa6 100644
--- a/lib/fluent/plugin/out_file.rb
+++ b/lib/fluent/plugin/out_file.rb
@@ -106,6 +106,9 @@ module Fluent
       end
 
       return path  # for test
+    rescue => e
+      log.error "unexpected error", stat: File::stat(path)
+      raise e
     end
 
     def secondary_init(primary)
```

We want to know how fluentd/ruby handle target file, e.g. uid, gid and permission.

**Comment by perrin4869** [comment]
Any ideas as to how to troubleshoot this problem? I will re-enable logrotate and try to look at the change of permissions today

**Comment by perrin4869** [comment]
```
2016-03-29 03:24:36 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532559, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:22:23 +0900, mtime=2016-03-29 03:22:23 +0900, ctime=2016-03-29 03:22:23 +0900>
2016-03-29 03:24:36 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 03:26:55 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purelatency_python.03.log" plugin_id="object:3fbac0456194"
  2016-03-29 03:24:36 +0900 [warn]: suppressed same stacktrace
2016-03-29 03:24:36 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532558, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:23:33 +0900, mtime=2016-03-29 03:23:33 +0900, ctime=2016-03-29 03:23:33 +0900>
2016-03-29 03:24:36 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 03:25:31 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purevol_python.03.log" plugin_id="object:3fbac0407684"
  2016-03-29 03:24:36 +0900 [warn]: suppressed same stacktrace
2016-03-29 03:25:31 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532558, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:23:33 +0900, mtime=2016-03-29 03:23:33 +0900, ctime=2016-03-29 03:23:33 +0900>
2016-03-29 03:25:31 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 03:27:24 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purevol_python.03.log" plugin_id="object:3fbac0407684"
  2016-03-29 03:25:31 +0900 [warn]: suppressed same stacktrace
2016-03-29 03:26:55 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532559, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:22:23 +0900, mtime=2016-03-29 03:22:23 +0900, ctime=2016-03-29 03:22:23 +0900>
2016-03-29 03:26:55 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 03:30:49 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purelatency_python.03.log" plugin_id="object:3fbac0456194"
  2016-03-29 03:26:55 +0900 [warn]: suppressed same stacktrace
2016-03-29 03:27:24 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532558, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:23:33 +0900, mtime=2016-03-29 03:23:33 +0900, ctime=2016-03-29 03:23:33 +0900>
2016-03-29 03:27:24 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 03:31:33 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purevol_python.03.log" plugin_id="object:3fbac0407684"
  2016-03-29 03:27:24 +0900 [warn]: suppressed same stacktrace
2016-03-29 03:30:49 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532559, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:22:23 +0900, mtime=2016-03-29 03:22:23 +0900, ctime=2016-03-29 03:22:23 +0900>
2016-03-29 03:30:49 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 03:40:08 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purelatency_python.03.log" plugin_id="object:3fbac0456194"
  2016-03-29 03:30:49 +0900 [warn]: suppressed same stacktrace
2016-03-29 03:31:33 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532558, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:23:33 +0900, mtime=2016-03-29 03:23:33 +0900, ctime=2016-03-29 03:23:33 +0900>
2016-03-29 03:31:33 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 03:39:57 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purevol_python.03.log" plugin_id="object:3fbac0407684"
  2016-03-29 03:31:33 +0900 [warn]: suppressed same stacktrace
2016-03-29 03:39:57 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532558, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:23:33 +0900, mtime=2016-03-29 03:23:33 +0900, ctime=2016-03-29 03:23:33 +0900>
2016-03-29 03:39:57 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 03:58:15 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purevol_python.03.log" plugin_id="object:3fbac0407684"
  2016-03-29 03:39:57 +0900 [warn]: suppressed same stacktrace
2016-03-29 03:40:08 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532559, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:22:23 +0900, mtime=2016-03-29 03:22:23 +0900, ctime=2016-03-29 03:22:23 +0900>
2016-03-29 03:40:08 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 03:59:14 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purelatency_python.03.log" plugin_id="object:3fbac0456194"
  2016-03-29 03:40:08 +0900 [warn]: suppressed same stacktrace
2016-03-29 03:58:15 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532558, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:23:33 +0900, mtime=2016-03-29 03:23:33 +0900, ctime=2016-03-29 03:23:33 +0900>
2016-03-29 03:58:15 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 04:28:57 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purevol_python.03.log" plugin_id="object:3fbac0407684"
  2016-03-29 03:58:15 +0900 [warn]: suppressed same stacktrace
2016-03-29 03:59:14 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532559, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:22:23 +0900, mtime=2016-03-29 03:22:23 +0900, ctime=2016-03-29 03:22:23 +0900>
2016-03-29 03:59:14 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 04:34:19 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purelatency_python.03.log" plugin_id="object:3fbac0456194"
  2016-03-29 03:59:14 +0900 [warn]: suppressed same stacktrace
2016-03-29 04:28:57 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532558, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:23:33 +0900, mtime=2016-03-29 03:23:33 +0900, ctime=2016-03-29 03:23:33 +0900>
2016-03-29 04:28:57 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 05:45:34 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purevol_python.03.log" plugin_id="object:3fbac0407684"
  2016-03-29 04:28:57 +0900 [warn]: suppressed same stacktrace
2016-03-29 04:34:19 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532559, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:22:23 +0900, mtime=2016-03-29 03:22:23 +0900, ctime=2016-03-29 03:22:23 +0900>
2016-03-29 04:34:19 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 05:48:26 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purelatency_python.03.log" plugin_id="object:3fbac0456194"
  2016-03-29 04:34:19 +0900 [warn]: suppressed same stacktrace
2016-03-29 05:45:34 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532558, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:23:33 +0900, mtime=2016-03-29 03:23:33 +0900, ctime=2016-03-29 03:23:33 +0900>
2016-03-29 05:45:34 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 07:50:20 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purevol_python.03.log" plugin_id="object:3fbac0407684"
  2016-03-29 05:45:34 +0900 [warn]: suppressed same stacktrace
2016-03-29 05:48:26 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532559, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:22:23 +0900, mtime=2016-03-29 03:22:23 +0900, ctime=2016-03-29 03:22:23 +0900>
2016-03-29 05:48:26 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 08:03:47 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purelatency_python.03.log" plugin_id="object:3fbac0456194"
  2016-03-29 05:48:26 +0900 [warn]: suppressed same stacktrace
2016-03-29 07:50:20 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532558, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:23:33 +0900, mtime=2016-03-29 03:23:33 +0900, ctime=2016-03-29 03:23:33 +0900>
2016-03-29 07:50:20 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 12:15:08 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purevol_python.03.log" plugin_id="object:3fbac0407684"
  2016-03-29 07:50:21 +0900 [warn]: suppressed same stacktrace
2016-03-29 08:03:47 +0900 [error]: unexpected error stat=#<File::Stat dev=0xfd00, ino=532559, mode=0100644, nlink=1, uid=8576, gid=1000, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2016-03-29 03:22:23 +0900, mtime=2016-03-29 03:22:23 +0900, ctime=2016-03-29 03:22:23 +0900>
2016-03-29 08:03:47 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-29 12:48:47 +0900 error_class="Errno::EACCES" error="Permission denied @ rb_sysopen - /var/log/td-agent/purelatency_python.03.log" plugin_id="object:3fbac0456194"
  2016-03-29 08:03:47 +0900 [warn]: suppressed same stacktrace
```

That's the output of the patch from yesterday :)

**Comment by perrin4869** [comment]
OK, sorry, I this might have been a permission error after all ><;;
I'll close this for now, report back if the error persists, thanks for the help!

**Comment by GLStephen** [comment]
@repeatedly I can confirm that this is happening in fluentd 0.14.21 standalone and google-fluentd, the restart approach used leads to a dead supervisor process and an odd log file

**Comment by zffocussss** [comment]
@GLStephen  same here
