### ISSUE TITLE
Why is path to pos_file required when the path to the log file itself does not exist?

### ISSUE THREAD

**Issue by portante** [fluent/fluentd#879]
If the path to the log file does not exist, fluentd will happily wait for the path to get created and will start watching the file:

```
# /usr/bin/fluentd -c example.conf 
2016-04-01 20:29:47 +0000 [info]: reading config file path="example.conf"
2016-04-01 20:29:47 +0000 [info]: starting fluentd-0.12.5
2016-04-01 20:29:47 +0000 [info]: gem 'fluent-plugin-add' version '0.0.3'
2016-04-01 20:29:47 +0000 [info]: gem 'fluentd' version '0.12.5'
2016-04-01 20:29:47 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type tail
    path /var/log/_nonexist_/my.log
    tag foobar
    format /^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) (?<message>.*)/
    time_format %F %T.%L
  </source>
  <match **>
    type stdout
    output_type json
  </match>
</ROOT>
2016-04-01 20:29:47 +0000 [info]: adding match pattern="**" type="stdout"
2016-04-01 20:29:47 +0000 [info]: adding source type="tail"
2016-04-01 20:29:47 +0000 [warn]: 'pos_file PATH' parameter is not set to a 'tail' source.
2016-04-01 20:29:47 +0000 [warn]: this parameter is highly recommended to save the position to resume tailing.
2016-04-02 20:30:27 +0000 [info]: following tail of /var/log/_nonexist_/my.log
2016-04-02 20:30:27 +0000 fluent.info: {"message":"following tail of /var/log/_nonexist_/my.log"}
```

However, if the configuration specifies `pos_file` and the directory does not exist, fluentd errors out with `ENOENT`:

```
# /usr/bin/fluentd -c example.conf 
2016-04-01 20:33:30 +0000 [info]: reading config file path="example.conf"
2016-04-01 20:33:30 +0000 [info]: starting fluentd-0.12.5
2016-04-01 20:33:30 +0000 [info]: gem 'fluent-plugin-add' version '0.0.3'
2016-04-01 20:33:30 +0000 [info]: gem 'fluentd' version '0.12.5'
2016-04-01 20:33:30 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type tail
    path /var/log/_nonexist_/my.log
    pos_file /var/log/_nonexist_/my.log.pos
    tag foobar
    format /^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) (?<message>.*)/
    time_format %F %T.%L
  </source>
  <match **>
    type stdout
    output_type json
  </match>
</ROOT>
2016-04-01 20:33:30 +0000 [info]: adding match pattern="**" type="stdout"
2016-04-01 20:33:30 +0000 [info]: adding source type="tail"
2016-04-01 20:33:30 +0000 [error]: unexpected error error_class=Errno::ENOENT error=#<Errno::ENOENT: No such file or directory - /var/log/_nonexist_/my.log.pos>
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/plugin/in_tail.rb:77:in `initialize'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/plugin/in_tail.rb:77:in `open'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/plugin/in_tail.rb:77:in `start'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/root_agent.rb:111:in `block in start'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/root_agent.rb:110:in `each'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/root_agent.rb:110:in `start'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/engine.rb:201:in `start'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/engine.rb:151:in `run'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:481:in `run_engine'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:140:in `block in start'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:266:in `call'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:266:in `main_process'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:241:in `block in supervise'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:240:in `fork'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:240:in `supervise'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:134:in `start'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-04-01 20:33:30 +0000 [error]: /usr/share/gems/gems/fluentd-0.12.5/bin/fluentd:6:in `<top (required)>'
  2016-04-01 20:33:30 +0000 [error]: /usr/bin/fluentd:23:in `load'
  2016-04-01 20:33:30 +0000 [error]: /usr/bin/fluentd:23:in `<main>'
2016-04-01 20:33:30 +0000 [info]: shutting down fluentd
2016-04-01 20:33:30 +0000 [info]: process finished code=0
2016-04-01 20:33:30 +0000 [warn]: process died within 1 second. exit.
```

If fluentd knows when the file comes into existence, why can't it wait until the point to create the `pos_file`?

**Comment by repeatedly** [comment]
pos_file is created during start phase so `No such file or directory - /var/log/_nonexist_/my.log.pos` happens when directory doesn't exist.

**Comment by repeatedly** [comment]
I'm not sure what is the problem.

**Comment by portante** [comment]
@repeatedly, so are you saying that it is expected that fluentd should fail when a pos file is specified with a missing directory path, but not fail with a *log* file is specified on the same path?  If so, why?

**Comment by repeatedly** [comment]
pos_file is created by fluentd but log file is created by another system.
I think dynamic pos_file creation has no merit.

**Comment by portante** [comment]
Huh, so if the log file does not exist yet, but will be created shortly, fluentd dies and won't work.  But once the path to the log file is created, then the pos file could be created.

So why not wait until the log file exists and is actually being tracked by fluentd before creating the pos file?

**Comment by portante** [comment]
In other words, don't fail fluentd if a log file does not exist to be tracked.  Once it does exist, fluentd should fail if it can't create the log file, as that would be a bad configuration. And when the file winks out of existence again, the pos file should not be touched or considered.

Does that seem reasonable?

**Comment by portante** [comment]
The current use case is for OpenStack.  I have about 17 different OpenStack services I would like to track their log files, but some services run in fail-over modes, where the paths to the log files might not be created yet.  So I don't want to have to update my fluentd configuration file when a service fails over.

**Comment by repeatedly** [comment]
Hmm... I can't still imagine what is the problem.
pos_file content is updated after actual log file is created. So creating it during the start phase is no problem.

> So I don't want to have to update my fluentd configuration file when a service fails over.

If you know the log file path of fail overed services, writing it in in_tail seems enough.

**Comment by portante** [comment]
@repeatedly, in the example posted, the path to the log file does not exist initially, meaning there is a missing directory.  Fluentd does great with that, it just waits patiently for the entire path to come into existence and then it will start tailing the log file.

However, if that log file does not exist, it still tries to create the position file.  Today, I have create a positio file in an existing directory since the position file must be created at startup time.  But if I want to keep my position file with my log file, because I don't readily have another place to keep the position file, I can't use a position file.

So what I am asking is, don't create the position file until fluentd actively starts tailing a log file.  And if the log file disappears, don't access the position file anymore.

That way, I can keep the position file with the log file, and not have to ensure a directory exists just for position files.

**Comment by repeatedly** [comment]
> But if I want to keep my position file with my log file, because I don't readily have another place to keep the position file, I can't use a position file.

Why? I want to know why you don't want to create position file in existing directory.

**Comment by tagomoris** [comment]
@portante pos_file has position in reading in file, and also has inode of files to be tracked. It is required to detect log rotation and others such like that.
If fluentd removes pos_file when tracked file (and its directory), fluentd cannot track log rotation using directory renaming or deleting-and-creating parent directory.

**Comment by repeatedly** [comment]
We can implement delay pos_file initialization but it introduces lots of complexity to in_tail, e.g. seperate routines for `/path/to/fixed` and `/path/to/*`, avoid race condition and etc.
I think the merit of delay pos_file initialization is smaller than above complexity.

**Comment by portante** [comment]
So here is the fluentd configuration we have: https://gist.github.com/portante/407ffdecdfe4326ccfae50e82c075c28

All of these files are log rotated (via `logrotate`).

We have a jinja template the generates this.  If I add a pos file in the cinder stanzas, creating a file along side the cinder log file, then I can't start fluentd on those boxes because the cinder directory does not exist.

I can create a separate /var/log/fluentd directory and put all the pos files there, but then I'll have pos files created that I don't need.

So should just one the same `pos_file /var/log/fluentd/pos.file` in each stanza and share it that way?

**Comment by tagomoris** [comment]
"Shared pos file" is a kind of idea of "Plugin Storage" which is now I'm developing to introduce it in v0.14.
If @portante can wait it, you can use it.

**Comment by portante** [comment]
@tagomoris, sounds good.

**Comment by portante** [comment]
@tagomoris, any updates on these related efforts?

**Comment by tagomoris** [comment]
I'll be done after #1059 merged (in other words, it's proceeding).

**Comment by tagomoris** [comment]
#1395

**Comment by knasim** [comment]
— Load RUN 2 ---------------------------------------------------------------
— Load RUN 2 ---------------------------------------------------------------
— Load RUN 2 ---------------------------------------------------------------

— Load RUN 2 ---------------------------------------------------------------
— Load RUN 2 ---------------------------------------------------------------
— Load RUN 2 ---------------------------------------------------------------

— Load RUN 2 ---------------------------------------------------------------
— Load RUN 2 ---------------------------------------------------------------
— Load RUN 2 ---------------------------------------------------------------

— Load RUN 2 ---------------------------------------------------------------
— Load RUN 2 ---------------------------------------------------------------
— Load RUN 2 ---------------------------------------------------------------

**Comment by ashie** [comment]
> ```
> 2016-04-01 20:33:30 +0000 [error]: unexpected error error_class=Errno::ENOENT error=#<Errno::ENOENT: No such file or directory - /var/log/_nonexist_/my.log.pos>
> ```

Such error doesn't occur on Fluentd 1.14.3, because the directory and pos_file are created automatically.

> #1395

Although this feature isn't implemented yet, I think the problem mentioned in this issue is already fixed.
So I close this.
