### ISSUE TITLE
uninitialized constant Fluent::TextFormatter::Formatter

### ISSUE THREAD

**Issue by miketonks** [fluent/fluentd#911]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) After ugrading fluentd version to 0.12.21 or 0.12.22 

we see the error: unexpected error error="uninitialized constant Fluent::TextFormatter::Formatter"

works with 0.12.17

Here is the output from the old working version:

	fluentd --config /fluentd/etc/fluent.conf -p /fluentd/plugins/
	2016-04-21 13:33:34 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
	2016-04-21 13:33:34 +0000 [info]: starting fluentd-0.12.17
	2016-04-21 13:33:34 +0000 [info]: gem 'fluent-plugin-docker-format' version '0.2.3'
	2016-04-21 13:33:34 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.4.0'
	2016-04-21 13:33:34 +0000 [info]: gem 'fluentd' version '0.12.17'
	2016-04-21 13:33:34 +0000 [info]: gem 'fluentd' version '0.10.61'
	2016-04-21 13:33:34 +0000 [info]: adding match pattern="*.*" type="kafka_buffered"
	2016-04-21 13:33:34 +0000 [info]: brokers has been set directly: ["foo"]
	2016-04-21 13:33:34 +0000 [info]: adding source type="forward"
	2016-04-21 13:33:34 +0000 [info]: using configuration file: <ROOT>
	  <source>
	    type forward
	    port 24224
	    bind 0.0.0.0
	  </source>
	  <match *.*>
	    type kafka_buffered
	    brokers foo
	    default_topic bar.messages
	    output_data_type mycustom_json
	    buffer_queue_limit 500
	    flush_interval 5s
	  </match>
	</ROOT>
	2016-04-21 13:33:34 +0000 [info]: initialized producer kafka
	2016-04-21 13:33:34 +0000 [info]: listening fluent socket on 0.0.0.0:24224

Here is the output from the new version showing error:

	fluentd --config /fluentd/etc/fluent.conf -p /fluentd/plugins/
	2016-04-21 13:28:40 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
	2016-04-21 13:28:40 +0000 [info]: starting fluentd-0.12.21
	2016-04-21 13:28:40 +0000 [error]: unexpected error error="uninitialized constant Fluent::TextFormatter::Formatter"
	  2016-04-21 13:28:40 +0000 [error]: /fluentd/plugins/formatter_mycustom_json.rb:3:in `<module:TextFormatter>'
	  2016-04-21 13:28:40 +0000 [error]: /fluentd/plugins/formatter_mycustom_json.rb:2:in `<module:Fluent>'
	  2016-04-21 13:28:40 +0000 [error]: /fluentd/plugins/formatter_mycustom_json.rb:1:in `<top (required)>'
	  2016-04-21 13:28:40 +0000 [error]: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	  2016-04-21 13:28:40 +0000 [error]: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/plugin.rb:89:in `block in load_plugin_dir'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/plugin.rb:87:in `each'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/plugin.rb:87:in `load_plugin_dir'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/engine.rb:138:in `load_plugin_dir'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/supervisor.rb:512:in `block in init_engine'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/supervisor.rb:509:in `each'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/supervisor.rb:509:in `init_engine'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/supervisor.rb:151:in `block in start'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/supervisor.rb:359:in `call'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/supervisor.rb:359:in `main_process'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/supervisor.rb:332:in `block in supervise'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/supervisor.rb:331:in `fork'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/supervisor.rb:331:in `supervise'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/supervisor.rb:149:in `start'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
	  2016-04-21 13:28:40 +0000 [error]: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	  2016-04-21 13:28:40 +0000 [error]: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	  2016-04-21 13:28:40 +0000 [error]: /var/lib/gems/1.9.1/gems/fluentd-0.12.21/bin/fluentd:5:in `<top (required)>'
	  2016-04-21 13:28:40 +0000 [error]: /usr/local/bin/fluentd:23:in `load'
	  2016-04-21 13:28:40 +0000 [error]: /usr/local/bin/fluentd:23:in `<main>'
	2016-04-21 13:28:40 +0000 [info]: process finished code=256
	2016-04-21 13:28:40 +0000 [warn]: process died within 1 second. exit.

The formatter_mycustom_json.rb file has this code:

	module Fluent
	  module TextFormatter
	    class MyCustomJsonFormatter < Formatter
	      Plugin.register_formatter("mycustom_json", self)

	      include HandleTagAndTimeMixin # If you wish to use tag_key, time_key, etc.

...

It seems that for some reason it is not finding the library files, but in both version it is present:

/var/lib/gems/1.9.1/gems/fluentd-0.12.17/lib/fluent/formatter.rb

/var/lib/gems/1.9.1/gems/fluentd-0.12.21/lib/fluent/formatter.rb

**Comment by repeatedly** [comment]
Maybe, you need `require 'fluent/formatter'` in the top of source code.

**Comment by miketonks** [comment]
Yes, that solves it.  Thanks!

**Comment by repeatedly** [comment]
Good to hear. We refactor fluentd's `require` dependencies and it causes this problem.
I will update fluentd-docs to add `require` to each example.
