### ISSUE TITLE
tests of fluent-plugin-config-expander fails with v0.14 (master) branch (uninitialized constant Fluent::Input/Fluent::Output)

### ISSUE THREAD

**Issue by sonots** [fluent/fluentd#973]
## HOW TO REPRODUCE

```
git clone https://github.com/tagomoris/fluent-plugin-config-expander
cd fluent-plugin-config-expander
# fix Gemfile
# + gem 'fluentd', git: 'https://github.com/fluent/fluentd'
bundle update
bundle exec rake
```

## ERROR1. uninitialized constant Fluent::Input (NameError)

```
lib/fluent/plugin/in_config_expander.rb:3:in `<top (required)>': uninitialized constant Fluent::Input (NameError)
```

**REASON**

It looks this is caused because `fluent/test` now does not require 'fluent/input`

Adding `require 'fluent/input'` into test/helper.rb of the plugin made tests succeed.

## ERROR2. Fluent::ConfigError: '<store>' sections are required

```
Error: test_emit(ConfigExpanderOutputTest): Fluent::ConfigError: '<store>' sections are required
/Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/fluentd-0b6e5048da40/lib/fluent/config/section.rb:160:in `block in generate'
/Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/fluentd-0b6e5048da40/lib/fluent/config/section.rb:146:in `each'
/Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/fluentd-0b6e5048da40/lib/fluent/config/section.rb:146:in `generate'
/Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/fluentd-0b6e5048da40/lib/fluent/configurable.rb:68:in `configure'
/Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/fluentd-0b6e5048da40/lib/fluent/plugin/base.rb:39:in `configure'
/Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/fluentd-0b6e5048da40/lib/fluent/plugin_id.rb:34:in `configure'
/Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/fluentd-0b6e5048da40/lib/fluent/log.rb:423:in `configure'
/Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/fluentd-0b6e5048da40/lib/fluent/plugin_helper/event_emitter.rb:52:in `configure'
/Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/fluentd-0b6e5048da40/lib/fluent/plugin/multi_output.rb:53:in `configure'
/Users/seo.naotoshi/src/github.com/tagomoris/fluent-plugin-config-expander/lib/fluent/plugin/out_config_expander.rb:33:in `configure'
/Users/seo.naotoshi/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/fluentd-0b6e5048da40/lib/fluent/test/base.rb:71:in `configure'
/Users/seo.naotoshi/src/github.com/tagomoris/fluent-plugin-config-expander/test/plugin/test_out_config_expander.rb:22:in `create_driver'
/Users/seo.naotoshi/src/github.com/tagomoris/fluent-plugin-config-expander/test/plugin/test_out_config_expander.rb:65:in `test_emit'
```

**REASON**

I am not investigating yet.

**Comment by sonots** [comment]
ERROR2 was fixed via https://github.com/fluent/fluentd/pull/974, but ERROR1 still remains

**Comment by sonots** [comment]
@tagomoris For ERROR1, do you fix fluentd itself (fluent/test) for compatibility, or should each plugin be fixed?

**Comment by tagomoris** [comment]
IMO, each (test) code should require files which are used from code in that file.
I'll add that require in `v0.14.1` or so if there are too many build errors in various plugins. Let me see how it goes.

**Comment by sonots** [comment]
With this change https://github.com/tagomoris/fluent-plugin-config-expander/pull/14, all tests of fluent-plugin-config-expander passed on v0.14. Let me close.
