### ISSUE TITLE
[v0.14] tests of fluent-plugin-sql fails with fluentd v0.14.0.rc.1

### ISSUE THREAD

**Issue by kakoni** [fluent/fluentd#977]
### How to reproduce
```
git clone https://github.com/fluent/fluent-plugin-sql
cd fluent-plugin-sql
```

### Change in Gemspec
```
gem.add_dependency "fluentd", [">= 0.14.rc.1", "< 2"]
```

### Run tests
```
bundle exec rake test 
```

### Result
```
/Users/kakoni/dev/fluent-plugin-sql/lib/fluent/plugin/in_sql.rb:22:in `<module:Fluent>': uninitialized constant Fluent::Input (NameError)
        from /Users/kakoni/dev/fluent-plugin-sql/lib/fluent/plugin/in_sql.rb:18:in `<top (required)>'
        from /Users/kakoni/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /Users/kakoni/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /Users/kakoni/dev/fluent-plugin-sql/test/helper.rb:6:in `<top (required)>'
        from /Users/kakoni/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /Users/kakoni/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /Users/kakoni/dev/fluent-plugin-sql/test/plugin/test_in_sql.rb:1:in `<top (required)>'
        from /Users/kakoni/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /Users/kakoni/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /Users/kakoni/.gem/ruby/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
        from /Users/kakoni/.gem/ruby/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:4:in `select'
        from /Users/kakoni/.gem/ruby/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:4:in `<main>'
```

### Expected result
Pass tests.

### Proposed fix 
Include needed requires as per https://github.com/fluent/fluentd/commit/7d4baa06b8dc8c89cb05e7ce7950ed867b5c4a98

**Comment by kakoni** [comment]
Also compat/output failures as in https://github.com/fluent/fluentd/issues/975

**Comment by sonots** [comment]
duplicated with https://github.com/fluent/fluentd/issues/973
