### ISSUE TITLE
[v0.14] tests of fluent-plugin-webhdfs fails with fluentd v0.14.0.rc.1(master) (uninitialized constant Fluent::MemoryBufferChunk)

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluentd#979]
### How to reproduce

```bash
$ git@github.com:fluent/fluent-plugin-webhdfs.git
$ cd fluent-plugin-webhdfs
```

Append the following line into Gemfile:

```bash
gem "fluentd", git: "git@github.com:fluent/fluentd.git", branch: "master"
```

Fluentd master revision is d5476d747846117187de355f72287f64727b103e.

Run tests:

```
$ bundle exec rake test
```

### Result

Tests failed.

```log
$ bundle exec rake test
...(snip)...
E
=================================================================================================================================================================================================
Error: test_compress(CompressorTest::Snappy): NameError: uninitialized constant Fluent::MemoryBufferChunk
/Users/hhatake/Github/fluent-plugin-webhdfs/test/plugin/test_compressor.rb:16:in `test_compress'
     13:     end
     14: 
     15:     def test_compress
  => 16:       chunk = Fluent::MemoryBufferChunk.new("test")
     17:       chunk << "hello snappy\n" * 32 * 1024
     18:       io = Tempfile.new("snappy-")
     19:       @compressor.compress(chunk, io)
=================================================================================================================================================================================================
.E
=================================================================================================================================================================================================
Error: test_compress[gzip](WebHDFSOutputTest::ConfigureTest): Fluent::ConfigError: 'path' parameter is required
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/config/section.rb:140:in `block in generate'
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/config/section.rb:127:in `each_pair'
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/config/section.rb:127:in `generate'
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/configurable.rb:68:in `configure'
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/plugin/base.rb:39:in `configure'
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/plugin/buffer.rb:86:in `configure'
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/plugin/buf_file.rb:57:in `configure'
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/plugin/output.rb:259:in `configure'
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/plugin_helper/event_emitter.rb:52:in `configure'
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/compat/output.rb:524:in `configure'
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/gems/fluent-mixin-config-placeholders-0.3.1/lib/fluent/mixin/config_placeholders.rb:106:in `configure'
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/gems/fluent-mixin-plaintextformatter-0.2.6/lib/fluent/mixin/plaintextformatter.rb:21:in `configure'
/Users/hhatake/Github/fluent-plugin-webhdfs/lib/fluent/plugin/out_webhdfs.rb:126:in `configure'
/Users/hhatake/Github/fluent-plugin-webhdfs/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/base.rb:71:in `configure'
/Users/hhatake/Github/fluent-plugin-webhdfs/test/plugin/test_out_webhdfs.rb:13:in `create_driver'
/Users/hhatake/Github/fluent-plugin-webhdfs/test/plugin/test_out_webhdfs.rb:76:in `test_compress'
     73:          lzo: ['lzo_command', Fluent::WebHDFSOutput::LZOCommandCompressor])
     74:     def test_compress(data)
     75:       compress_type, compressor_class = data
  => 76:       d = create_driver %[
     77: namenode server.local:14000
     78: path /hdfs/path/file.%Y%m%d.%H%M.log
     79: compress #{compress_type}
=================================================================================================================================================================================================
...(snip)...
```

### Expected result

Tests succeeded without any changes.

**Comment by tagomoris** [comment]
I think that plugin should NOT be dependent on classes of other plugins (even in tests).
And it must not break behavior of real plugin. Fluentd itself doesn't take care about it.
