### ISSUE TITLE
[v0.14] tests of fluent-plugin-forest fails with fluentd v0.14.0.rc.1(master)

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluentd#980]
### How to reproduce

```bash
$ git@github.com:tagomoris/fluent-plugin-forest.git
$ cd fluent-plugin-forest.
```

Append the following line into Gemfile:

```bash
gem "fluentd", git: "git@github.com:fluent/fluentd.git", branch: "master"
```

Fluentd master revision is d5476d747846117187de355f72287f64727b103e.

Run tests:

```
$ bundle exec rake test
```

### Result

Tests failed.

```log
$ bundle exec rake test
/Users/hhatake/.rbenv/versions/2.3.0/bin/ruby -w -I"lib:lib:test" -I"/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/lib" "/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" 
/Users/hhatake/Github/fluent-plugin-forest/test/plugin/test_out_forest.rb:36: warning: assigned but unused variable - d
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/cool.io-1.4.3/lib/cool.io/loop.rb:41: warning: method redefined; discarding old initialize
(eval):1: warning: method redefined; discarding old on_read
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/cool.io-1.4.3/lib/cool.io/io.rb:79: warning: previous definition of on_read was here
(eval):1: warning: method redefined; discarding old on_write_complete
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/cool.io-1.4.3/lib/cool.io/io.rb:83: warning: previous definition of on_write_complete was here
(eval):1: warning: method redefined; discarding old on_close
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/cool.io-1.4.3/lib/cool.io/io.rb:87: warning: previous definition of on_close was here
(eval):1: warning: method redefined; discarding old on_readable
(eval):1: warning: method redefined; discarding old on_writable
(eval):1: warning: method redefined; discarding old on_timer
(eval):1: warning: method redefined; discarding old on_signal
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/cool.io-1.4.3/lib/cool.io/async_watcher.rb:24: warning: previous definition of on_signal was here
(eval):1: warning: method redefined; discarding old on_connection
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/cool.io-1.4.3/lib/cool.io/listener.rb:35: warning: previous definition of on_connection was here
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/cool.io-1.4.3/lib/cool.io/dns_resolver.rb:171: warning: assigned but unused variable - ancount
(eval):1: warning: method redefined; discarding old on_success
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/cool.io-1.4.3/lib/cool.io/dns_resolver.rb:89: warning: previous definition of on_success was here
(eval):1: warning: method redefined; discarding old on_failure
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/cool.io-1.4.3/lib/cool.io/dns_resolver.rb:93: warning: previous definition of on_failure was here
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/cool.io-1.4.3/lib/cool.io/socket.rb:30: warning: method redefined; discarding old attach
(eval):1: warning: previous definition of attach was here
(eval):1: warning: method redefined; discarding old on_connect
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/cool.io-1.4.3/lib/cool.io/socket.rb:42: warning: previous definition of on_connect was here
(eval):1: warning: method redefined; discarding old on_connect_failed
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/cool.io-1.4.3/lib/cool.io/socket.rb:46: warning: previous definition of on_connect_failed was here
Loaded suite /Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader
Started
.E
=================================================================================================================================================================================================
Error: test_emit(ForestOutputTest): RuntimeError: BUG: use router.emit instead of Engine.emit
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/engine.rb:132:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/test/output/out_forest_test.rb:39:in `block in emit'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/event.rb:74:in `each'
/Users/hhatake/Github/fluent-plugin-forest/test/output/out_forest_test.rb:31:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/lib/fluent/plugin/out_forest.rb:171:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/compat/output.rb:158:in `process'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/plugin/bare_output.rb:53:in `emit_sync'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/output_test.rb:46:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/test/plugin/test_out_forest.rb:541:in `block in test_emit'
     538:   def test_emit
     539:     d = create_driver
     540:     time = Time.parse("2012-01-02 13:14:15").to_i
  => 541:     d.tag = 'test.first';  d.run { d.emit({'f' => "message 1"}, time) }
     542:     d.tag = 'test.second'; d.run { d.emit({'f' => "message 2"}, time) }
     543:     d.tag = 'test.foo.bar'; d.run { d.emit({'f' => "message 3"}, time) }
     544:     d.tag = 'test.foo.baz'; d.run { d.emit({'f' => "message 4"}, time) }
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/input_test.rb:123:in `block in run'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/base.rb:81:in `run'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/input_test.rb:122:in `run'
/Users/hhatake/Github/fluent-plugin-forest/test/plugin/test_out_forest.rb:541:in `test_emit'
=================================================================================================================================================================================================
E
=================================================================================================================================================================================================
Error: test_faild_plant(ForestOutputTest): RuntimeError: BUG: use router.emit instead of Engine.emit
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/engine.rb:132:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/test/output/out_forest_test.rb:39:in `block in emit'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/event.rb:74:in `each'
/Users/hhatake/Github/fluent-plugin-forest/test/output/out_forest_test.rb:31:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/lib/fluent/plugin/out_forest.rb:171:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/compat/output.rb:158:in `process'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/plugin/bare_output.rb:53:in `emit_sync'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/output_test.rb:46:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/test/plugin/test_out_forest.rb:507:in `block in test_faild_plant'
     504:   def test_faild_plant
     505:     d = create_driver
     506:     time = Time.parse("2012-01-02 13:14:15").to_i
  => 507:     d.tag = 'test.xxxxxx';  d.run { d.emit({'f' => "message 1"}, time) }
     508:     emits = d.emits
     509:     assert_equal 1, emits.length
     510: 
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/input_test.rb:123:in `block in run'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/base.rb:81:in `run'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/input_test.rb:122:in `run'
/Users/hhatake/Github/fluent-plugin-forest/test/plugin/test_out_forest.rb:507:in `test_faild_plant'
=================================================================================================================================================================================================
............E
=================================================================================================================================================================================================
Error: test_emit(ForestTestOutputTest): RuntimeError: BUG: use router.emit instead of Engine.emit
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/engine.rb:132:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/test/output/out_forest_test.rb:39:in `block in emit'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/event.rb:74:in `each'
/Users/hhatake/Github/fluent-plugin-forest/test/output/out_forest_test.rb:31:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/compat/output.rb:139:in `process'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/plugin/output.rb:499:in `emit_sync'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/output_test.rb:46:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/test/plugin/test_out_forest_test.rb:31:in `block in test_emit'
     28:     d = create_driver
     29:     time = Time.parse("2012-01-02 13:14:15").to_i
     30:     d.run do
  => 31:       d.emit({'msg' => 'xyz 123', 'alt' => 'aaa bbb ccc'}, time)
     32:       d.emit({'msg' => 'xyz 456', 'alt' => 'aaa bbb ccc ddd'}, time)
     33:     end
     34:     emits = d.emits
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/input_test.rb:123:in `block in run'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/base.rb:81:in `run'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/input_test.rb:122:in `run'
/Users/hhatake/Github/fluent-plugin-forest/test/plugin/test_out_forest_test.rb:30:in `test_emit'
=================================================================================================================================================================================================
E
=================================================================================================================================================================================================
Error: test_emit1(ForestTestOutputTest): RuntimeError: BUG: use router.emit instead of Engine.emit
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/engine.rb:132:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/test/output/out_forest_test.rb:39:in `block in emit'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/event.rb:74:in `each'
/Users/hhatake/Github/fluent-plugin-forest/test/output/out_forest_test.rb:31:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/compat/output.rb:139:in `process'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/plugin/output.rb:499:in `emit_sync'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/output_test.rb:46:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/test/plugin/test_out_forest_test.rb:54:in `block in test_emit1'
     51:     d = create_driver
     52:     time = Time.parse("2012-01-02 13:14:15").to_i
     53:     d.run do
  => 54:       d.emit({'msg' => 'xyz 123', 'alt' => 'aaa bbb ccc'}, time)
     55:       d.tag = 'test2'
     56:       d.emit({'msg' => 'xyz 456', 'alt' => 'aaa bbb ccc ddd'}, time)
     57:     end
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/input_test.rb:123:in `block in run'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/base.rb:81:in `run'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/input_test.rb:122:in `run'
/Users/hhatake/Github/fluent-plugin-forest/test/plugin/test_out_forest_test.rb:53:in `test_emit1'
=================================================================================================================================================================================================
E
=================================================================================================================================================================================================
Error: test_emit2(ForestTestOutputTest): RuntimeError: BUG: use router.emit instead of Engine.emit
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/engine.rb:132:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/test/output/out_forest_test.rb:39:in `block in emit'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/event.rb:74:in `each'
/Users/hhatake/Github/fluent-plugin-forest/test/output/out_forest_test.rb:31:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/compat/output.rb:139:in `process'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/plugin/output.rb:499:in `emit_sync'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/output_test.rb:46:in `emit'
/Users/hhatake/Github/fluent-plugin-forest/test/plugin/test_out_forest_test.rb:80:in `block in test_emit2'
     77:     d = create_driver
     78:     time = Time.parse("2012-01-02 13:14:15").to_i
     79:     d.run do
  => 80:       d.emit({'msg' => 'xyz 123', 'alt' => 'aaa bbb ccc'}, time)
     81:     end
     82:     d.tag = 'test2'
     83:     d.run do
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/input_test.rb:123:in `block in run'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/base.rb:81:in `run'
/Users/hhatake/Github/fluent-plugin-forest/vendor/bundle/ruby/2.3.0/bundler/gems/fluentd-d5476d747846/lib/fluent/test/input_test.rb:122:in `run'
/Users/hhatake/Github/fluent-plugin-forest/test/plugin/test_out_forest_test.rb:79:in `test_emit2'
=================================================================================================================================================================================================
```

### Expected result

Tests succeeded without any changes.

**Comment by cosmo0920** [comment]
This problem is caused by fluent-plugin-forest's test class not Fluentd itself.
