### ISSUE TITLE
fluent-plugin-sql fails with fluentd v0.14.0.rc.3 (error="undefined method `key')

### ISSUE THREAD

**Issue by kakoni** [fluent/fluentd#990]
Testing RC3 with fluent-plugin-sql.
out-sql fails because
```
2016-05-25 11:10:32 +0300 [warn]: failed to flush the buffer. plugin_id="object:3fc15cdfc728" retry_time=0 next_retry=2016-05-25 11:10:33 +0300 chunk="533a63190cdc0d19f6dd96b
a60e49317" error_class=NoMethodError error="undefined method `key' for #<Fluent::Plugin::Buffer::MemoryChunk:0x007f82be13ab30>"
  2016-05-25 11:10:33 +0300 [warn]: /Users/kakoni/dev/fluentd/lib/fluent/plugin/out_sql.rb:224:in `block (2 levels) in write'
  2016-05-25 11:10:33 +0300 [warn]: /Users/kakoni/dev/fluentd/lib/fluent/plugin/out_sql.rb:223:in `each'
  2016-05-25 11:10:33 +0300 [warn]: /Users/kakoni/dev/fluentd/lib/fluent/plugin/out_sql.rb:223:in `block in write'
  2016-05-25 11:10:33 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_conne
ction'
  2016-05-25 11:10:33 +0300 [warn]: /Users/kakoni/dev/fluentd/lib/fluent/plugin/out_sql.rb:221:in `write'
  2016-05-25 11:10:33 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/bundler/gems/fluentd-69df4fe63215/lib/fluent/compat/output.rb:109:in `write'
  2016-05-25 11:10:33 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/bundler/gems/fluentd-69df4fe63215/lib/fluent/plugin/output.rb:778:in `try_flush'
  2016-05-25 11:10:33 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/bundler/gems/fluentd-69df4fe63215/lib/fluent/plugin/output.rb:953:in `flush_thread_run'
  2016-05-25 11:10:33 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/bundler/gems/fluentd-69df4fe63215/lib/fluent/plugin/output.rb:360:in `block (2 levels) in start'
  2016-05-25 11:10:33 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/bundler/gems/fluentd-69df4fe63215/lib/fluent/plugin_helper/thread.rb:66:in `block in thread_create'
```

**Comment by tagomoris** [comment]
@kakoni Thank you for reporting!
I pushed a change to fix this issue. Can you fetch & install fluentd from branch `fix-compat-buffered-output-overrides-emit` to check this problem?

**Comment by kakoni** [comment]
Confirmed, `fix-compat-buffered-output-overrides-emit` fixes this issue.

**Comment by tagomoris** [comment]
Great. Thank you!

**Comment by tagomoris** [comment]
#992 was merged.
