### ISSUE TITLE
fluent-plugin-parser fails test with fluentd v0.14.0.rc.3 

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluentd#996]
### How to reproduce

```
$ git clone git@github.com:tagomoris/fluent-plugin-parser.git
$ cd fluent-plugin-parser
```

Apply the following patch:

```diff
diff --git a/Gemfile b/Gemfile
index 9a01568..0863edc 100644
--- a/Gemfile
+++ b/Gemfile
@@ -2,3 +2,4 @@ source 'https://rubygems.org'
 
 # Specify your gem's dependencies in fluent-plugin-parser.gemspec
 gemspec
+gem "fluentd", "= 0.14.0.rc.1"
diff --git a/fluent-plugin-parser.gemspec b/fluent-plugin-parser.gemspec
index 5feb2b9..c0a859f 100644
--- a/fluent-plugin-parser.gemspec
+++ b/fluent-plugin-parser.gemspec
@@ -17,5 +17,5 @@ Gem::Specification.new do |gem|
   gem.add_development_dependency "test-unit"
   gem.add_development_dependency "rake"
   gem.add_development_dependency "oj"
-  gem.add_runtime_dependency "fluentd", "~> 0.12.0"
+  gem.add_runtime_dependency "fluentd", [">= 0.12.0", "< 2"]
 end
```

```
$ echo 'gem "fluentd", "=0.14.0.rc.3"' >> Gemfile
$ bundle install
$ bundle exec rake test
```

### Result

Some test fails as follows:

```log
=================================================================================================================================================================================================
Failure: test_parser_error_warning(ParserFilterTest)
/Users/hhatake/Github/fluent-plugin-parser/test/plugin/test_filter_parser.rb:630:in `block in test_parser_error_warning'
     627:   def test_parser_error_warning
     628:     d = create_driver(CONFIG_INVALID_TIME_VALUE, 'test.no.change')
     629:     swap_logger(d.instance) do
  => 630:       assert_raise(DummyLoggerWarnedException) {
     631:         d.run do
     632:           d.filter({'data' => '{"time":[], "f1":"v1"}'}, Time.now.to_i)
     633:         end
/Users/hhatake/Github/fluent-plugin-parser/test/plugin/test_filter_parser.rb:622:in `swap_logger'
/Users/hhatake/Github/fluent-plugin-parser/test/plugin/test_filter_parser.rb:629:in `test_parser_error_warning'

<ParserFilterTest::DummyLoggerWarnedException> expected but was
<NoMethodError(<undefined method `reset' for #<ParserFilterTest::DummyLogger:0x007fdb19e578a0>>)>

diff:
?                                               ParserFilterTest::DummyLoggerW              arnedException
? NoMethodError(<undefined method `reset' for #<                             :0x007fdb19e578 0>>)         
=================================================================================================================================================================================================
(snip)
=================================================================================================================================================================================================
Failure: test_suppress_parse_error_log(ParserOutputTest)
/Users/hhatake/Github/fluent-plugin-parser/test/plugin/test_out_parser.rb:700:in `block in test_suppress_parse_error_log'
     697:     d = create_driver(CONFIG_DEFAULT_SUPPRESS_PARSE_ERROR_LOG, 'test.in')
     698: 
     699:     swap_logger(d.instance) do
  => 700:       assert_raise(DummyLoggerWarnedException) {
     701:         d.run do
     702:           d.emit({'message' => INVALID_MESSAGE}, Time.now.to_i)
     703:         end
/Users/hhatake/Github/fluent-plugin-parser/test/plugin/test_out_parser.rb:679:in `swap_logger'
/Users/hhatake/Github/fluent-plugin-parser/test/plugin/test_out_parser.rb:699:in `test_suppress_parse_error_log'

<ParserOutputTest::DummyLoggerWarnedException> expected but was
<NoMethodError(<undefined method `reset' for #<ParserOutputTest::DummyLogger:0x007fdb19df59c0>>)>

diff:
?                                               ParserOutputTest::DummyLoggerWarne  dEx     ception
? NoMethodError(<undefined method `reset' for #<                             :0x007f b19df59 0>>)  
=================================================================================================================================================================================================
.
```

**Comment by cosmo0920** [comment]
Ah, this issue is already fixed with: https://github.com/tagomoris/fluent-plugin-parser/pull/34/files
