### ISSUE TITLE
fluent-plugin-geoip test fails with fluentd v0.14.0.rc.3

### ISSUE THREAD

**Issue by okkez** [fluent/fluentd#997]
### How to reproduce

```
$ git clone git@github.com:y-ken/fluent-plugin-geoip.git
$ cd fluent-plugin-geoip
$ echo 'gem "fluentd", "=0.14.0.rc.3'" >> Gemfile
(sudo apt-get install libgeoip-dev if you needed)
$ bundle install
$ bundle exec rake test
```

### Result

Some tests failed.

```
========================================================================================================================
Failure: <Fluent::ConfigError> exception expected but none was thrown.
test_configure(GeoipOutputTest)
/home/kenji/Data/ruby/td-family/fluent-plugin-geoip/test/plugin/test_out_geoip.rb:20:in `test_configure'
     17:   end
     18:
     19:   def test_configure
  => 20:     assert_raise(Fluent::ConfigError) {
     21:       d = create_driver('')
     22:     }
     23:     assert_raise(Fluent::ConfigError) {
========================================================================================================================
```

This should raise `Fluent::ConfigError: geoip: required at least one option of 'tag', 'remove_tag_prefix', 'remove_tag_suffix', 'add_tag_prefix', 'add_tag_suffix'.`

```
F
========================================================================================================================
Failure: test_emit(GeoipOutputTest)
/home/kenji/Data/ruby/td-family/fluent-plugin-geoip/test/plugin/test_out_geoip.rb:83:in `test_emit'
     80:       d1.emit({'message' => 'missing field'})
     81:     end
     82:     emits = d1.emits
  => 83:     assert_equal 2, emits.length
     84:     assert_equal 'geoip.access', emits[0][0] # tag
     85:     assert_equal 'Mountain View', emits[0][2]['geoip_city']
     86:     assert_equal nil, emits[1][2]['geoip_city']
<2> expected but was
<0>
========================================================================================================================
(snip)
```

`Fluent::Test::OutputTestDriver#emit` does not append events to `@emit_streams` and does not call `@instance.write`.

**Comment by okkez** [comment]
filter geoip workes well following config:

```
<source>
  type dummy
  tag raw.dummy
  dummy {"host":"66.102.9.80", "message":"test"}
</source>

<filter raw.**>
  type geoip
  #remove_tag_suffix .dummy
  add_tag_prefix debug.
  #tag raw.geoip
  geoip_lookup_key  host
  #geoip_database    "/path/to/your/GeoIPCity.dat"
  <record>
    city            ${city["host"]}
    latitude        ${latitude["host"]}
    longitude       ${longitude["host"]}
    country_code3   ${country_code3["host"]}
    country         ${country_code["host"]}
    country_name    ${country_name["host"]}
    dma             ${dma_code["host"]}
    area            ${area_code["host"]}
    region          ${region["host"]}
  </record>
  flush_interval    1s
</filter>

<match raw.**>
  type stdout
</match>
```

output geoip does not work well.

```
<source>
  type dummy
  tag raw.dummy
  dummy {"host":"66.102.9.80", "message":"test"}
</source>

<match raw.**>
  type geoip
  #add_tag_suffix .geoip
  add_tag_prefix debug.
  #tag raw.geoip
  geoip_lookup_key  host
  #geoip_database    "/path/to/your/GeoIPCity.dat"
  <record>
    city            ${city["host"]}
    latitude        ${latitude["host"]}
    longitude       ${longitude["host"]}
    country_code3   ${country_code3["host"]}
    country         ${country_code["host"]}
    country_name    ${country_name["host"]}
    dma             ${dma_code["host"]}
    area            ${area_code["host"]}
    region          ${region["host"]}
  </record>
  flush_interval    1s
</match>

<match debug.**>
  type stdout
</match>
```

**Comment by okkez** [comment]
```
plugin.class.ancestors # => [Fluent::Compat::CallSuperMixin, Fluent::GeoipOutput, Fluent::Mixin::RewriteTagName, Fluent::SetTagKeyMixin, Fluent::HandleTagNameMixin, Fluent::RecordFilterMixin, Fluent::Compat::BufferedOutput, Fluent::Compat::PropagateDefault, Fluent::PluginHelper::EventEmitter, Fluent::Plugin::Output, Fluent::PluginHelper::Thread, Fluent::PluginHelper::RetryState, Fluent::UniqueId::Mixin, Fluent::PluginHelper::Mixin, Fluent::PluginLoggerMixin, Fluent::PluginId, Fluent::Plugin::Base, Fluent::SystemConfig::Mixin, Fluent::Configurable, Object, JSON::Ext::Generator::GeneratorMethods::Object, Kernel, BasicObject]
```

This does not include `Fluent::Output`.

**Comment by tagomoris** [comment]
That plugin depends on that all output plugins are subclass of `Fluent::Output`. Hmm.

**Comment by tagomoris** [comment]
"Fluent::Test::OutputTestDriver#emit does not append events to @emit_streams and does not call @instance.write."

About this problem, that plugin's test code should use `Fluent::Test::BufferedOutputTestDriver` instead of `OutputTestDriver`. These are different things.

**Comment by okkez** [comment]
On v0.14 (master),
*  `Fluent::Output == Fluent::Compat::Output`
* `Fluent::BufferedOutput == Fluent::Compat::BufferedOutput`
* `Fluent::CompatBufferedOutput` inherits `Fluent::Plugin::Output` not `Fluent::Output` or `Fluent::Comapt::Output`.

**Comment by okkez** [comment]
> About this problem, that plugin's test code should use Fluent::Test::BufferedOutputTestDriver instead of OutputTestDriver. These are different things.

OK, I will try.

**Comment by okkez** [comment]
Using `Fluent::Test::BufferedOutpuTestDriver` fixes the problem. I will create PR for fluent-plugin-geoip.

**Comment by tagomoris** [comment]
Thank you!

**Comment by okkez** [comment]
Ah! `Fluent::Test::BufferedOutputTestDriver` on v0.12 does not handle `@emit_streams`.
fluent-plugin-geoip test fails with `Fluent::Test::BufferedOutputTestDriver` against Fluentd v0.12.
